### PR TITLE
docs(std/log): update example

### PR DESCRIPTION
**Pull request by matthewadams**

### CODE REVIEW

**Comment by bartlomieju** [comment]
@matthewadams thanks, please run `tools/format.py` and `tools/lint.py` to get CI to green

**Comment by matthewadams** [comment]
@bartlomieju I'd be happy to.  Can you please point me to some docs on `tools/format.py` & `tools/lint.py`?  I can't tell from the output of `tools/format.py --help` how to invoke it.  I've tried all options, but just get output like
```
🍺 pwd
/Users/matthewadams/dev/deno/deno
🍺 tools/format.py
Traceback (most recent call last):
  File "tools/format.py", line 89, in <module>
    sys.exit(main())
  File "tools/format.py", line 51, in main
    dprint()
  File "tools/format.py", line 59, in dprint
    run(command, shell=False, quiet=True)
  File "/Users/matthewadams/dev/deno/deno/tools/util.py", line 62, in run
    rc = subprocess.call(args, cwd=cwd, env=env, shell=shell)
  File "/usr/local/Cellar/python@2/2.7.17/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/local/Cellar/python@2/2.7.17/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python@2/2.7.17/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
Sorry if this is a FAQ.

**Comment by bartlomieju** [comment]
CC @dsherret could you take a look?

**Comment by dsherret** [comment]
@matthewadams does the `third_party` directory exist? I think the command to get the submodules is `git submodule update --recursive`, but I'm not sure.

**Comment by matthewadams** [comment]
@dsherret  Ok so I did `git submodule init` then `git submodule update` & got the `third_party` directory.  Then, ran `tools/format.py` and it produced a ton of changes.  I don't understand why _anything_ is changing because my only commit was to `std/log/README.md`.  Please unconfuse me.  :)

**Comment by lucacasonato** [comment]
Can you merge with master, then try again?

**Review by bartlomieju — APPROVED** [review]
LGTM

**Pull request merged**
