### PR TITLE
fix: incorrect type for Env.toObject

### PR DESCRIPTION
**Pull request by sheepsteak**
Since an object is returned it's possible that for a given key there could be no value:

image

### CODE REVIEW

**Comment by nayeemrmn** [comment]
This change is correct, but unfortunately it's breaking and may have to wait for 2.0...

**Comment by lucacasonato** [comment]
Closing as 2.0 is still a while out. @nayeemrmn do you know if we have a tracking issue for this?

**Comment by nayeemrmn** [comment]
I've opened #10267.

**Comment by lucacasonato** [comment]
Thanks 🙏

**Pull request closed without merging**
