### PR TITLE
Disallow memory slices as inputs to async ops

### PR DESCRIPTION
**Pull request by andreubotella**
In Rust, it is UB if a slice is mutated while borrowed except through the slice itself, and it is also UB if a mutable slice is read while borrowed. The op macro allows borrowing an `ArrayBuffer{,View}` as a memory slice for the duration of an op, but this is not sound for async ops, since the `ArrayBuffer` could be accessed from JS during the await points. This PR therefore disallows such automatic borrowing only for async ops.

### CODE REVIEW

**Comment by andreubotella** [comment]
@littledivy PTAL

**Comment by crowlKats** [comment]
@andreubotella a test is failing; could you take a look?

**Comment by andreubotella** [comment]
> @andreubotella a test is failing; could you take a look?

The failing test is simply an ops optimizer test added in #16579 that passes a memory slice to a fast async op. Since the point of that PR seems to be to allow `op_read` to use fast calls, disallowing memory slices might limit the usefulness of that optimization, even though implementing `op_read` like this would make UB inevitable.

cc @littledivy

**Review by littledivy — APPROVED** [review]
LGTM. I'm in favour of disabling slices in async ops. IIRC there is no fast async op using it anyways

**Pull request merged**
