### PR TITLE
fix(cli/test): fix clear screen behavior when run `deno test --watch`

### LINKED ISSUE #19725: deno test --watch does not clear screen
I noticed that running `deno run --watch <script>` will clear the terminal when files change, while `deno test --watch <script>` will not clear the screen on file changes. `deno test --help` still shows the `--no-clear-screen` option, so it appears that it is supposed to clear the screen by default. Poking around at a few other commands, they also seem to be missing the cleared screen by default (`deno lint --watch` for instance)

### PR DESCRIPTION
**Pull request by liruifengv**
fix #19725

### CODE REVIEW

**Comment by bartlomieju** [comment]
Thanks for the PR @liruifengv, could you update some of unit tests in `cli/args/flags.rs` to make sure we don't have a regression in the future?

**Comment by liruifengv** [comment]
> Thanks for the PR @liruifengv, could you update some of unit tests in `cli/args/flags.rs` to make sure we don't have a regression in the future?↳

I'd be happy to update the unit tests, but could you give a little more hints, I've just changed an incorrect bool value being passed, and I'm not quite sure how to update the unit tests.

**Comment by bartlomieju** [comment]
There's `test_watch` test in `cli/args/flags.rs` - make sure that it has correct value for the "no clear screen" argument. That should be enough :)

**Comment by liruifengv** [comment]
I don't think this test needs updating, it's correct

**Comment by liruifengv** [comment]
This incorrect behavior is that the screen is not cleared when the `--no-clear-screen` flag is not passed by default, and the screen is cleared when the `--no-clear-screen` flag is passed true.

This is because we passed the opposite value to the `file_watcher::watch_func` function, incorrectly using ` ! ` for the inverse.

```rust
  file_watcher::watch_func(
    flags,
    file_watcher::PrintConfig {
      job_name: "Test".to_string(),
      clear_screen: !test_flags
        .watch
        .as_ref()
        .map(|w| !w.no_clear_screen)
        .unwrap_or(true),
    },
    ...
  )
  .await?;
```

So much so that `watch_func` gets the wrong `PrintConfig.clear_screen` parameter, performing the opposite action.

The value of `test_flags` is correct, so test was also correct.

**Comment by bartlomieju** [comment]
> This incorrect behavior is that the screen is not cleared when the `--no-clear-screen` flag is not passed by default, and the screen is cleared when the `--no-clear-screen` flag is passed true.
> 
> This is because we passed the opposite value to the `file_watcher::watch_func` function, incorrectly using `!` for the inverse.
> 
> ```rust
>   file_watcher::watch_func(
>     flags,
>     file_watcher::PrintConfig {
>       job_name: "Test".to_string(),
>       clear_screen: !test_flags
>         .watch
>         .as_ref()
>         .map(|w| !w.no_clear_screen)
>         .unwrap_or(true),
>     },
>     ...
>   )
>   .await?;
> ```
> 
> So much so that `watch_func` gets the wrong `PrintConfig.clear_screen` parameter, performing the opposite action.
> 
> The value of `test_flags` is correct, so test was also correct.

Oh, got it, sorry for the confusion. In such case - maybe we could adjust the integration tests in `cli/tests/integration/watcher_tests.rs` (`test_watch_basic`) and check that the `CLEAR_SCREEN` character is printed?

**Comment by liruifengv** [comment]
I can also write the test code:
```rust
 let line = next_line(&mut stderr_lines).await.unwrap();
  assert_not_contains!(&line, CLEAR_SCREEN);
  assert_contains!(&line, "Restarting");
```
But I don't think it's meaningful because it always not_contains in non-TTY environments.

**Comment by bartlomieju** [comment]
Okay, let's land it as is.

**Review by bartlomieju — APPROVED** [review]

**Pull request merged**
