### PR TITLE
refactor: remove Deno.core

### PR DESCRIPTION
**Pull request by bartlomieju**
This commit removes "Deno.core" namespace. It is strictly private API that has
no stability guarantees, we were supposed to remove it long time ago, but oh well.

### CODE REVIEW

**Comment by bartlomieju** [comment]
@iuioiua I'm having trouble making latest `deno_std` commit work in this PR, it seems you were the last person to touch relevant API (`BufReader`). Could you take a look?

**Comment by iuioiua** [comment]
Ah, my bad. I realise my approach around deprecated exports was wrong in https://github.com/denoland/deno_std/pull/2975. Apologies. Lesson learnt.

I've submitted a likely fix in https://github.com/denoland/deno_std/pull/3051. I'll do the same for other such modules that have been restructured as soon as I can. I don't think the change should be reverted, but rather be done better, as it's overall better for the developer.

**Review by kt3k — APPROVED** [review]
LGTM

**Review by ry — APPROVED** [review]
LGTM - thanks!

**Pull request merged**
