### PR TITLE
feat(extensions/webstorage): Allow user to specify the amount of space to use for `webstorage`

### PR DESCRIPTION
**Pull request by getspooky**
I think it would be a good idea to let the user specify how much space they want to reserve,
By default deno take `5MB`.

## Example:

```ts
localStorage.setLimitStorage(80000);
```

### CODE REVIEW

**Review by lucacasonato — CHANGES_REQUESTED** [review]
This is not a web standard API. Further discussion is needed in the issue.

**Comment by getspooky** [comment]
Yes , please see https://github.com/denoland/deno/issues/10557

**Comment by crowlKats** [comment]
@getspooky what Luca meant is that this is not a viable solution because this is changing a standard Web API. This needs more discussing than just a single comment.

In regards to the actual changes: this makes having a limit completely useless because anyone can change it during runtime; at that point might as well just remove a limit whatsoever.

**Comment by exside** [comment]
Not happy with the cap, can't use Deno.kv() because of another bug (memory leak in v8) which prevents me from upgrading Deno to a version that has Deno KV...so I'm stuck writing dumb JSON files (or adding an entire DB to the stack, which I don't want) instead of being able to access the SQLite backed WebStorage API... I agree that it should not be a non-standard API method like suggested here, but it should be a runtime flag like `--storage-limit=<MB>`, don't understand why this wasn't done, would it be very hard? I mean yeah, not really changeable in the browser, but in a browser you don't do the same things as on a server...so I don't think that argument counts 😉

**Pull request closed without merging**
