### PR TITLE
fix(core): introduce `SafeRegExp` to primordials

### LINKED ISSUE #17485: primordials: Introduce `SafeRegExp`
`RegExp` methods access properties directly, [e.g. `"flags"`](https://tc39.es/ecma262/#sec-regexp.prototype-@@split), so we should introduce `SafeRegExp`.

### PR DESCRIPTION
**Pull request by petamoriken**
Closes #17485

### CODE REVIEW

**Comment by petamoriken** [comment]
benchmark for console

```js
const count = 100000;
Deno.bench("console", () => {
  for (let i = 0; i < count; i++) console.log("Hello World");
});
```

---

before:

```
cpu: Apple M1
runtime: deno 1.30.0 (aarch64-apple-darwin)

benchmark      time (avg)             (min … max)       p75       p99      p995
------------------------------------------------- -----------------------------
console     64.63 ms/iter   (64.02 ms … 65.64 ms)   64.9 ms  65.64 ms  65.64 ms
```

after:

```
cpu: Apple M1
runtime: deno 1.30.0 (aarch64-apple-darwin)

benchmark      time (avg)             (min … max)       p75       p99      p995
------------------------------------------------- -----------------------------
console     64.15 ms/iter   (63.52 ms … 64.92 ms)  64.41 ms  64.92 ms  64.92 ms
```

**Comment by petamoriken** [comment]
rebased

**Comment by petamoriken** [comment]
@littledivy please review this

**Review by kt3k — APPROVED** [review]
LGTM

**Pull request merged**
