### PR TITLE
fix: createSecKey logic

### PR DESCRIPTION
**Pull request by suguru03**
I just found a tiny issue. 
It sometimes includes `undefined` because of `Math.round`, like `cqF-vcjundefinedqZxmomrJ`.

### CODE REVIEW

**Comment by ry** [comment]
Ah cool thanks. Could you add a test with the expected output in a corner case?

**Comment by suguru03** [comment]
Sure, I will do it. 😄

**Comment by suguru03** [comment]
You can reproduce the error when you run only the file with `Math.round`, it will be `undefinedzQGtYXbBRnYByMg`. 
```sh
cargo run -- --seed=86 -A testing/runner.ts --exclude "**/testdata" ws/mod_test.ts
```

Could you review it?

**Comment by suguru03** [comment]
@ry Thank you very much for cleaning up! 🙏

**Comment by suguru03** [comment]
Thanks!

**Pull request merged**
