### PR TITLE
feat: granular --unstable-* flags

### PR DESCRIPTION
**Pull request by bartlomieju**
This commit adds granular `--unstable-*` flags:
- "--unstable-broadcast-channel"
- "--unstable-ffi"
- "--unstable-fs"
- "--unstable-http"
- "--unstable-kv"
- "--unstable-net"
- "--unstable-worker-options"
- "--unstable-cron"

These flags are meant to replace a "catch-all" flag - "--unstable", that
gives a binary control whether unstable features are enabled or not. The
downside of this flag that allowing eg. Deno KV API also enables the FFI
API (though the latter is still gated with a permission).

These flags can also be specified in `deno.json` file under `unstable` key.

Currently, "--unstable" flag works the same way - I will open a follow up
PR that will print a warning when using "--unstable" and suggest to use
concrete "--unstable-*" flag instead. We plan to phase out "--unstable"
completely in Deno 2.

### CODE REVIEW

**Comment by lucacasonato** [comment]
I am generally in favor of this, but also `--unstable-worker` is so meaningless! Shouldn't we generally have flags for specific features?

**Comment by bartlomieju** [comment]
> I am generally in favor of this, but also `--unstable-worker` is so meaningless! Shouldn't we generally have flags for specific features?

There are potentially many unstable features for Worker API (eg. loading an import map), would we really want separate flags for each of these features if they are contained in `new Worker()` constructor's `deno` option?

**Comment by nayeemrmn** [comment]
I think it should be `--unstable-worker-options` at least.

**Comment by bartlomieju** [comment]
> I think it should be `--unstable-worker-options` at least.

I'm fine with that name 👍

**Review by dsherret — APPROVED** [review]
LGTM! (once the config file test is added)

**Pull request merged**
