### PR TITLE
feat: stabilize Deno.serveHttp and Deno.upgradeWebSocket

### PR DESCRIPTION
**Pull request by bartlomieju**

### CODE REVIEW

**Comment by bartlomieju** [comment]
Blocked by https://github.com/denoland/deno/issues/11400

**Comment by lucacasonato** [comment]
Want to mention it here real quick: not in favor of stabilizing upgradeWebsocket yet (not enough real world use and feedback). serveHttp I am in favor.

**Comment by kitsonk** [comment]
And there have been issues, like the header stuff.  I am also not in favour of stabilising the socket stuff yet.

**Comment by bartlomieju** [comment]
Agreed, I'll open a new PR

**Pull request closed without merging**
