### PR TITLE
docs: add a Powershell autocomplete example

### LINKED ISSUE #7328: Docs: add a Powershell autocomplete example at section setup_your_environment
Additionally to the others terminal examples (bash, zsh, ...), it would be helpful a Powershell example on how to configure deno completion at https://deno.land/manual/getting_started/setup_your_environment:

Example (Powershell):

```shel
deno completions powershell > $profile
.$profile
```

This will be create a Powershell profile at `$HOME\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1` by default, and it will be run whenever you launch the PowerShell.

### PR DESCRIPTION
**Pull request by danilosampaio**
Additionally to the others terminal examples (bash, zsh, ...), this adds a Powershell example on how to configure deno completion.

Fix #7328

### CODE REVIEW

**Comment by tokiedokie** [comment]
lint

**Comment by danilosampaio** [comment]
thanks @tokiedokie 
fixing my local python environment... to run format.py locally.

**Comment by danilosampaio** [comment]
Done. 🎉

**Comment by bartlomieju** [comment]
@danilosampaio thanks for the contribution! Everything looks great, just need you to sign the CLA so this PR can be landed

**Review by lucacasonato — APPROVED** [review]
LGTM - thanks @danilosampaio

**Pull request merged**
