### PR TITLE
Fixes benchmark page spinner not hiding on Edge #2508

### PR DESCRIPTION
**Pull request by davidjamesstone**
Also fixes a couple of typos and css positioning of spinner.

https://github.com/denoland/deno/issues/2508

### CODE REVIEW

**Comment by ry** [comment]
@davidjamesstone Thanks! CI is failing due to formatting. Can you run "tools/format.py" ?

**Comment by davidjamesstone** [comment]
Thanks & sorry about that, I failed to read https://deno.land/manual.html#submittingapullrequest.

It's not clear to me from the [Travis output](https://travis-ci.com/denoland/deno/jobs/208234868) what it's failing on - is it a linting problem?

I can't run `tools/format.py` at the moment.
I've never setup the full deno build environment before. I don't have XCode or Rust on this work machine either so I think I might be better off setting up a linux vm.

If you're happy to wait I'll hopefully get time this weekend to do it but please feel free to step in and fix if it's quicker.

**Comment by ry** [comment]
@davidjamesstone It's at the end of [the very verbose output](https://travis-ci.com/denoland/deno/jobs/208234868):
```
Run tools/format.py 
 M website/app.ts
```
I've pushed the format change

**Comment by davidjamesstone** [comment]
Thanks Ryan. LOL I actually had line breaks in initially then took them out.

I did see this
```
Run tools/format.py 
 M website/app.ts
```

But I was kind of expecting the linting error afterwards but the output ended there.

**Pull request merged**
