### PR TITLE
fix(cli): make hashes of tsconfig deterministic 

### LINKED ISSUE #8163: "Permission denied (os error 13)" with read-only Deno cache dir and `--config` flag using Deno 1.5.0
### Error

```
$ deno run --config tsconfig.json hello.ts
Check file:///home/hello.ts
error: Permission denied (os error 13) (for '"/home/cache/gen/file/home/hello.ts.js"')
```

### To reproduce

**tsconfig.json**

```json
{
  "compilerOptions": {
    "strict": false,
    "noImplicitAny": false,
    "noImplicitThis": false,
    "alwaysStrict": false,
    "strictNullChecks": false,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": false,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true
  }
}
```

**hello.ts**

```typescript
import { ServerRequest } from 'https://deno.land/std@0.75.0/http/server.ts';

export default async (req: ServerRequest) => {
	req.respond({ body: `Hello, from Deno v${Deno.version.deno}!` });
};
```

Run commands:

```bash
$ deno --version
deno 1.5.0
v8 8.7.220.3
typescript 4.0.3

$ export DENO_DIR=cache

$ deno cache --config tsconfig.json hello.ts
Download https://deno.land/std@0.75.0/http/server.ts
Download https://deno.land/std@0.75.0/encoding/utf8.ts
Download https://deno.land/std@0.75.0/async/mod.ts
Download https://deno.land/std@0.75.0/http/_io.ts
Download https://deno.land/std@0.75.0/io/bufio.ts
Download https://deno.land/std@0.75.0/_util/assert.ts
Download https://deno.land/std@0.75.0/http/http_status.ts
Download https://deno.land/std@0.75.0/textproto/mod.ts
Download https://deno.land/std@0.75.0/bytes/mod.ts
Download https://deno.land/std@0.75.0/async/mux_async_iterator.ts
Download https://deno.land/std@0.75.0/async/delay.ts
Download https://deno.land/std@0.75.0/async/deferred.ts
Download https://deno.land/std@0.75.0/async/pool.ts
Check file:///home/hello.ts

# Before `chmod` - works
$ deno run --config tsconfig.json hello.ts
Check file:///home/hello.ts

# Mark cache dir as read-only (simulating AWS Lambda runtime environment)
$ chmod -R -w cache

# After `chmod` - errors
$ deno run --config tsconfig.json hello.ts
Check file:///home/hello.ts
error: Permission denied (os error 13) (for '"/home/cache/gen/file/home/hello.ts.js"')
```

### Notes

* This appears to be a regression in Deno 1.5.0. Following the reproduction steps above using Deno 1.4.6 works as expected.
* The error seems to only happen when using the `--config` flag (perhaps something related to this specific tsconfig setup). Following the reproduction steps above using Deno 1.5.0, _and omitting the `--config tsconfig.json` flag_ works as expected.

### PR DESCRIPTION
**Pull request by kitsonk**
Fixes #8163

### CODE REVIEW

**Review by bartlomieju — APPROVED** [review]
LGTM

**Comment by ry** [comment]
@kitsonk Did you try the preserve_order feature flag for serde_json ? https://github.com/serde-rs/json/blob/64bb3962bd70ae74d6e8a9daa496504c64033760/Cargo.toml#L53-L56

**Comment by bartlomieju** [comment]
> @kitsonk Did you try the preserve_order feature flag for serde_json ? https://github.com/serde-rs/json/blob/64bb3962bd70ae74d6e8a9daa496504c64033760/Cargo.toml#L53-L56

@ry using this flag affects all `serde` APIs, I don't think it's desirable

**Comment by kitsonk** [comment]
I think it is best to do what we are doing here, which is ensuring the order only at the one point where it matters. There are other risks that the insertion order might not actually be deterministic too, this ensures that no matter how we got to the config, that the final value of the config becomes part of the hash.

**Pull request merged**
