### PR TITLE
feat(ext/web): cancel support for TransformStream

### PR DESCRIPTION
**Pull request by lucacasonato**
Fixes https://github.com/denoland/deno/issues/20741

### CODE REVIEW

**Review by crowlKats — APPROVED** [review]
LGTM

**Comment by KnorpelSenf** [comment]
I had to look twice before I understood that you aren't actually cancelling your support for `TransformStream`.

Cool changes tho!

**Comment by sant123** [comment]
Are these changes reverted? I can't see `cancel` on the TransformStream options:

image

Using Deno 2.6.5

**Comment by bartlomieju** [comment]
@sant123 that looks like a TypeScript type declaration bug. Commenting on a 2 year pull request is not the best way to report problems like this. Please open an a new issue with reproduction instead.

**Pull request merged**
