### PR TITLE
fix(ext/web): formatting of DOMException

### PR DESCRIPTION
**Pull request by bartlomieju**
Given `new DOMException("a", "b")` the browsers will format it in the console like so:
```
DOMException: a
  at ...
```
However Deno v1.44 formats it like so:
```
b: a
  at ...
```
This is caused by the change from https://github.com/denoland/deno/pull/23986.

This commit aligns the formatting with the browsers, but doing a little string manipulation
when displaying the error.

### CODE REVIEW

**Review by satyarohith — COMMENTED** [review]
The fix looks good to me if CI passes

**Review by satyarohith — COMMENTED** [review]
FYI: this didn't fix the issue when tested on the repl:
```
➜  deno git:(fix_dom_exception) ./target/debug/deno
Deno 1.44.1
exit using ctrl+d, ctrl+c, or close()
REPL is running with all permissions allowed.
To specify permissions, run `deno repl` with allow flags.
> new DOMException("a", "b");
b: a
    at <anonymous>:1:22
```

**Comment by 0f-0b** [comment]
It was a deliberate change to include the exception's name in the stack trace, in line with Safari's behavior.

**Comment by bartlomieju** [comment]
After further discussion offline, we will not be changing the output.

**Pull request closed without merging**
