### PR TITLE
feat(std/node/stream): Add Duplex, Transform, Passthrough, pipeline, finished and promises

### PR DESCRIPTION
**Pull request by Soremwar**
Based on #7934

### CODE REVIEW

**Review by guybedford — APPROVED** [review]
There's no way this can be reviewed, rather merging and building in feedback from usage seems the only real way to tackle this, so for that reason I'm all for going ahead with a merge.

readable-stream hasn't been updated in months, and relying on a third-party implementation seems to go against the Deno process.

Please do make sure all sources you have copied from have their licenses fully credited, even if there has been significant modification.

**Comment by Soremwar** [comment]
Once #7569 is merged i'll rebase this but it seems it will pass in it's current state.

**Comment by Soremwar** [comment]
This is rebased over latest master

**Review by bartlomieju — APPROVED** [review]
LGTM, thanks @Soremwar. It's a huge PR and it's really hard to review it properly, I think we'll just have to iterate on it

**Pull request merged**
