### PR TITLE
Revert "fix(ext/node): use primordials in `ext/node/polyfills/https.ts` (#26323)"

### PR DESCRIPTION
**Pull request by bartlomieju**
…s` (#26323)"

This reverts commit afb33b3c2597c9ec943f71218b236486fbc86e23.

Reverting because it caused a regression - https://github.com/denoland/deno/issues/26612.

Closes https://github.com/denoland/deno/issues/26612.

### CODE REVIEW

**Comment by bartlomieju** [comment]
CC @jiang1997

**Review by dsherret — APPROVED** [review]

**Comment by irbull** [comment]
Just built deno from source with this commit reverted and the issue no longer happens.

**Comment by petamoriken** [comment]
It seems that the first argument of `ObjectPrototypeIsPrototypeOf` is wrong...

**Comment by jiangjieke** [comment]
> It seems that the first argument of `ObjectPrototypeIsPrototypeOf` is wrong...

My bad. It should be `URLPrototype`.
I will try it later today.

**Comment by jiang1997** [comment]
> It seems that the first argument of `ObjectPrototypeIsPrototypeOf` is wrong...

My bad. It should be `URLPrototype`.
I will try it later today.

**Pull request merged**
