### PR TITLE
chore(ext): update webgpu

### PR DESCRIPTION
**Pull request by danteissaias**

### CODE REVIEW

**Comment by danteissaias** [comment]
Here is google's example to test new syntax https://gist.github.com/danteissaias/b855d765996ef46b8a5b05d0fa62db76

Currently there is an issue with `webidl.converters.GPUBindGroupLayoutEntry` which prevents `createBindGroup` from working.

**Comment by crowlKats** [comment]
whats up with the typings?

**Comment by danteissaias** [comment]
I copied the latest ones from the repo was unsure of whether to keep in the documentation.

**Comment by crowlKats** [comment]
which repo?

**Comment by danteissaias** [comment]
https://github.com/gpuweb/gpuweb

**Comment by danteissaias** [comment]
There was a commit ID in a comment references this repo.

**Comment by crowlKats** [comment]
ah, we always handroll our webgpu typings

**Comment by danteissaias** [comment]
Ok, I’ll do that tomorrow.

**Comment by danteissaias** [comment]
Could you investigate the error with `createBindGroup`?

**Comment by crowlKats** [comment]
yes, i will do that

**Comment by crowlKats** [comment]
> There was a commit ID in a comment references this repo.

ah we havent updated in a while afaik. that commit used to refer to the commit of the webidl that the typings match to, but i think its better we remove it as we have an idl file stored alongside the code

**Comment by crowlKats** [comment]
@danteissaias fixed the createBindGroup problem, now the result I am getting is an typedarray with `0`s

**Comment by danteissaias** [comment]
Somethings going wrong…. Will have to investigate.

**Comment by crowlKats** [comment]
@danteissaias 
manually validated the wgsl with the same naga version that wgpu is using:
```
error: unknown attribute: 'stage'
   ┌─ test.wgsl:10:2
   │
10 │ @stage(compute) @workgroup_size(8, 8)
   │  ^^^^^ unknown attribute

Could not parse WGSL
```

**Comment by danteissaias** [comment]
So either google’s example is outdated to the spec or wgpu-rs…

**Comment by danteissaias** [comment]
https://www.w3.org/TR/WGSL/#entry-point-decl looks like the example is outdated. Try with this syntax.

**Comment by crowlKats** [comment]
yep, was just going through the spec as well, thank god its not a problem with wgpu/naga 😅

**Comment by crowlKats** [comment]
hm no luck still, the shader validates now, but still getting 0s in typedarray

**Comment by danteissaias** [comment]
I updated the gist. Try with new shader changes.

**Comment by crowlKats** [comment]
interesting new output:
```
Vector component[0] type Scalar { kind: Float, width: 4 }
Float32Array(6) [ 0, 0, 0, 0, 0, 0 ]
```

**Comment by danteissaias** [comment]
https://gist.github.com/danteissaias/ba81b617ef1143a7ceb83e63f116c3c9

This is the hello-compute example updated with the newest shader syntax from the wgpu repo. It works. So must be an issue with google's shader.

**Comment by danteissaias** [comment]
What's the web spec behaviour for if the shader has invalid syntax?

**Comment by danteissaias** [comment]
> interesting new output:
> 
> ```
> Vector component[0] type Scalar { kind: Float, width: 4 }
> Float32Array(6) [ 0, 0, 0, 0, 0, 0 ]
> ```

Not sure why there is this extra log here. Something left in wgpu-rs accidentally?

**Review by crowlKats — APPROVED** [review]
LGTM, thanks a lot for this!

**Comment by danteissaias** [comment]
👍

**Pull request merged**
