### PR TITLE
docs: Add documentation to a subset of available extensions

### PR DESCRIPTION
**Pull request by rscarson**
I was able to use my experience with some of the Deno extensions to flesh out their documentation a bit

I've provided docs for the following:
- web
- fetch
- net
- webidl
- url
- io
- crypto
- console

The only code change I have made is to formalize the previously undocumented dependency between `deno_io` and `deno_tty`

I do plan to eventually add support in my own crate for all deno extensions, and plan to document them as I get through them

If there are internal guidelines for documentation which I am not adhering to, I will happily modify these to match them

### CODE REVIEW

**Comment by crowlKats** [comment]
i am in favour of making the documentation more expansive, however having the ops seems a bit much, as these will most likely get out of date

**Comment by rscarson** [comment]
> i am in favour of making the documentation more expansive, however having the ops seems a bit much, as these will most likely get out of date 

`deno_net` already provided such a list, I tried to match that

Also to be fair, most documentation goes out of date on a regular basis, especially with APIs that change as quickly as this one

I expect a lot of the JS side to change often too, like the change to move timers away from deno_web for example

**Comment by rscarson** [comment]
The linter appears to be applying code style guides to the markdown files? If that's correct I'll make the described changes

**Comment by rscarson** [comment]
Alright finally got linter to accept the formatting

**Comment by rscarson** [comment]
Linter has now accepted the formatting; unsure why checks are still failing

**Comment by rscarson** [comment]
Adjusted pr title as per lint

**Review by bartlomieju — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
