### PR TITLE
fix(websocket): allow any close code for server

### LINKED ISSUE #11611: Native websockets: allow WebSocket.close to be called with codes from 1000 through 3000
Sending a code of e.g. 1101 to [WebSocket](https://doc.deno.land/builtin/stable#WebSocket).close() on a websocket created from `Deno.upgradeWebSocket` yields:

`DOMException: The close code must be either 1000 or in the range of 3000 to 4999.`

I am writing a deno host for existing server code that cannot be modified, and expects sending these codes through to the client.

deno 1.12.2

### PR DESCRIPTION
**Pull request by crowlKats**
Fixes #11611

### CODE REVIEW

**Comment by bartlomieju** [comment]
Can we get a test please?

**Comment by crowlKats** [comment]
> Can we get a test please?

There already is: i modified existing test to use an invalid code. but if needed, sure i can make a separate one

**Comment by bartlomieju** [comment]
> > Can we get a test please?
> 
> There already is: i modified existing test to use an invalid code. but if needed, sure i can make a separate one

Oooops, you're right

**Review by bartlomieju — APPROVED** [review]
LGTM, thanks

**Pull request merged**
