### PR TITLE
chore(ext/node): cleanup empty internal_bindings

### PR DESCRIPTION
**Pull request by littledivy**

### CODE REVIEW

**Review by bartlomieju — COMMENTED** [review]
IIRC these modules are actually reachable from user code - removing them might (and possibly will) break compatibility with existing packages

**Comment by littledivy** [comment]
> IIRC these modules are actually reachable from user code 

Can you give an example? I thought `internalBinding` calls in Node was supposed to be completely isolated from users.

**Comment by bartlomieju** [comment]
I might have messed it up, there's this API:
https://github.com/nodejs/node/blob/7e6bc93add1e5b8e9ede20354b098d6ebceeeaf4/lib/internal/bootstrap/loaders.js#L232-L241

But I think it's only about `internal/` modules, not `internalBindings`. Could you double check it?

**Comment by littledivy** [comment]
sheesh - ok so that code was a mess but I found this issue: https://github.com/nodejs/node/issues/27061 internal_bindings are not accessible from userland. It's very sus if a module is using it somehow (just like Deno.core)

**Review by bartlomieju — APPROVED** [review]

**Pull request merged**
