### PR TITLE
docs: explicitly import assert in examples

### PR DESCRIPTION
**Pull request by caspervonb**

### CODE REVIEW

**Review by satyarohith — COMMENTED** [review]
Looks good! I like examples that can directly be run when copy-pasted.

**Comment by kt3k** [comment]
I like this change and maybe this is necessary when we start doc testing. Does anyone have concern about importing std from main repo example?

**Comment by caspervonb** [comment]
> I like this change and maybe this is necessary when we start doc testing. Does anyone have concern about importing std from main repo example?

Yup, I need this (and the others to come) to get more of cli/dts passing!
We already use `std/testing/assert.ts` other examples above and below so ship has kinda already sailed.
Altho I think we could just use console.assert for the `Deno` namespace examples but that's a discussion for another day.

**Review by kt3k — APPROVED** [review]
Thank you for the explanation. Right, we already do this in many places. LGTM

**Pull request merged**
