### PR TITLE
perf(ext/node): move winerror binding to rust

### PR DESCRIPTION
**Pull request by littledivy**
16873 lines of JS removed from the snapshot.

### CODE REVIEW

**Comment by bartlomieju** [comment]
Are you sure it's that many lines? The diff doesn't show it. What's the size difference of the snapshot?

**Comment by ry** [comment]
@bartlomieju note the JS file got renamed to RS

**Review by ry — COMMENTED** [review]
Is this PR ready? 

Does it improve startup time?

**Comment by bartlomieju** [comment]
It's a bit concerning there's no difference in startup time :/ let's push forward with other modules we listed before fully evaluating it.

**Comment by littledivy** [comment]
Fully hooked up now, and no difference in execution time :(

...maybe thats because winerror.ts is just constants that don't impact deserilazation as much. IMO Let's continue porting larger parts to Rust.

**Review by bartlomieju — APPROVED** [review]
LGTM

**Pull request merged**
