### PR TITLE
Revert "fix(cli): ipv6 parsing for --allow-net params (#6453)"

### PR DESCRIPTION
**Pull request by bartlomieju**
This reverts commit 702547d65a9cb60ca6672792c08225b1c3099bad.

CI is red after landing #6453, segfaulting: https://github.com/denoland/deno/runs/803876247

Reverting to see if this commit causes segfault on mac

### CODE REVIEW

**Comment by bartlomieju** [comment]
Not sure if this commit caused problems, running CI on `master` yields green now: https://github.com/denoland/deno/runs/803925938

**Comment by bartlomieju** [comment]
Seems that it was intermittent failure. Closing.

**Comment by bartlomieju** [comment]
Another failure: https://github.com/denoland/deno/runs/804251920

**Comment by bartlomieju** [comment]
CC @ColinHarrington

**Comment by ColinHarrington** [comment]
I don't think this is necessarily related to #6453.  It seems to be that the ci build with macOS-latest has some instability.

My first version of the PR died with a `SIGSEGV: invalid memory reference`  I amended just the commit message - no changes to the code and the build passed.  I wrote it off as build instability with the macOS-latest build. 

I'm seeing a number of ci runs dying on `test_release macOS-latest` with similar issues, including failures prior to my PR.

- https://github.com/denoland/deno/runs/803752521?check_suite_focus=true
Caused by:
  process didn't exit successfully: `/Users/runner/runners/2.263.0/work/deno/deno/target/release/deps/deno-155067cc6f246010` (signal: 6, SIGABRT: process abort signal)
##[error]Process completed with exit code 101.

- https://github.com/denoland/deno/runs/803741363?check_suite_focus=true
Caused by:
  process didn't exit successfully: `/Users/runner/runners/2.263.0/work/deno/deno/target/release/deps/deno-155067cc6f246010` (signal: 11, SIGSEGV: invalid memory reference)
##[error]Process completed with exit code 101.

- https://github.com/denoland/deno/runs/803589580?check_suite_focus=true
Caused by:
  process didn't exit successfully: `/Users/runner/runners/2.263.0/work/deno/deno/target/release/deps/deno-155067cc6f246010` (signal: 11, SIGSEGV: invalid memory reference)
##[error]Process completed with exit code 101.

- https://github.com/denoland/deno/runs/804251920?check_suite_focus=true
process didn't exit successfully: `/Users/runner/runners/2.263.0/work/deno/deno/target/release/deps/deno-155067cc6f246010` (signal: 4, SIGILL: illegal instruction)

- https://github.com/denoland/deno/runs/800973207?check_suite_focus=true (Before the merge of #6453 )
Caused by:
  process didn't exit successfully: `/Users/runner/runners/2.263.0/work/deno/deno/target/release/deps/deno-155067cc6f246010` (signal: 11, SIGSEGV: invalid memory reference)
##[error]Process completed with exit code 101.

- https://github.com/denoland/deno/runs/790981909?check_suite_focus=true (from 5 days ago)
Caused by:
  process didn't exit successfully: `/Users/runner/runners/2.263.0/work/deno/deno/target/release/deps/deno-155067cc6f246010` (signal: 11, SIGSEGV: invalid memory reference)
##[error]Process completed with exit code 101.

**Comment by bartlomieju** [comment]
Thanks for investigating @ColinHarrington I also can't reproduce this problem locally on mac. It seems that all of the failing CI steps were run after merging `master` with #6453 landed, but I'm not entirely convinced that it was problematic commit - there's nothing strange going on in there. That said, I'll monitor CI today and try to re-land your PR. Thanks!

**Comment by bartlomieju** [comment]
@ColinHarrington I've pinpointed the culprit to #6362 and it's being reverted in https://github.com/denoland/deno/pull/6475. 
I'll reland your patch in https://github.com/denoland/deno/pull/6472

**Pull request merged**
