### PR TITLE
fix(cli): zsh completions

### LINKED ISSUE #8472: zsh completion fails for 1.5.4
Reproducing:

Fresh debian container

```
$ apt update
$ apt install -y wget unzip
$ wget https://github.com/denoland/deno/releases/download/v1.5.4/deno-x86_64-unknown-linux-gnu.zip
$ unzip deno-x86_64-unknown-linux-gnu.zip
$ ./deno --help
$ ./deno completions bash
$ ./deno completions zsh
thread 'main' panicked at 'Fatal internal error. Please consider filing a bug report at https://github.com/clap-rs/clap/issues', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.3/src/completions/zsh.rs:407:29
```

Also failing in https://github.com/NixOS/nixpkgs/pull/104674
Issue filed in the clap repo: https://github.com/clap-rs/clap/issues/2220

Since I don't have familiarity with the changes in `1.5.4` if someone else wants to take over the clap issue by posting a new one I'll be happy to close mine.

### PR DESCRIPTION
**Pull request by crowlKats**
Closes #8472

### CODE REVIEW

**Review by ry — COMMENTED** [review]
Should we add a test to do `deno completions zsh`?

**Comment by crowlKats** [comment]
maybe... this isnt an issue in clap v3 as there you cant do conflicts with non-existent args; it will not compile

**Comment by crowlKats** [comment]
i changed the current completions test to make compeltions for zsh instead bash as this is a zsh-only issue

**Review by bartlomieju — APPROVED** [review]
LGTM

**Pull request merged**
