### PR TITLE
feat: deprecate `deno vendor`

### LINKED ISSUE #20584: Deprecate `deno vendor` and replace with `"vendor": true`?
Deno 1.37 (and actually some earlier versions) has the ability to vendor by specifying the following in a deno.json:

```json
{
  "vendor": true
}
```

After running your program or caching (ex. `deno cache mod.ts`), a `./vendor` folder will be automatically populated with the remote dependencies.

This is considerably easier to use than `deno vendor` and we should consider deprecating `deno vendor` in favour of this feature and move the existing `deno vendor` out into a separate tool.

### PR DESCRIPTION
**Pull request by iuioiua**
Closes #20584

### CODE REVIEW

**Review by dsherret — COMMENTED** [review]
LGTM, but let's hold off on merging this until we get support in Deploy.

**Comment by iuioiua** [comment]
Sorry, what do you mean?

**Comment by lino-levan** [comment]
Why is this being deprecated? We need this to publish to JSR as far as I am aware? Happy to be wrong about that.

**Comment by dsherret** [comment]
@lino-levan yeah, that might keep this built-in. Please comment with use cases in #20584

**Review by dsherret — APPROVED** [review]
LGTM

**Pull request merged**
