### PR TITLE
Enable "strict" mode for runtime code.

### LINKED ISSUE #3324: User libraries should be strict by default if written in TypeScript
My opinion is that:

* `.ts` files should be as strict as possible (you can do anything with `as any` trickery still)
* `.js` files should be free to do what ever you want.

Also I think there is no audience who loves working with non-strict TypeScript, it's mainly used by people who are migrating to TypeScript. Catering to "non-strict" TypeScript people is failure in waiting.

(Going in the reverse is more painful, because the libraries will then not type check, if we allow non-strict scripts to prevail.)

Point being that if you use TS you probably love the types and the strictness, if you don't you use JS anyway.

Opening this on suggestion by @kitsonk in #504

### PR DESCRIPTION
**Pull request by kitsonk**
We should be able to do this now.

Fixes #3324

### CODE REVIEW

**Comment by kitsonk** [comment]
Too many changes, will take another stab at this at some point in the future.

**Comment by Ciantic** [comment]
What do you mean by too many changes? I hope this makes it before 1.0, because that's when the libraries will start to gather speed.

**Comment by maxmellen** [comment]
@kitsonk Would you be open to contributions on this?

**Comment by kitsonk** [comment]
Too many changes upstream, making it difficult to land the PR.

Yeah, @maxmellen, if you wanted to try.

**Comment by maxmellen** [comment]
Great! Having a go at it.

I noticed these compiler options moved to `compiler_host.ts` where there are now multiple sets of compiler options: https://github.com/denoland/deno/blob/ed680552a24b7d4b936b7c16a63b46e0f24c0e60/cli/js/compiler_host.ts#L33-L73

I was wondering if strict mode should also be enabled in these other options, notably the `defaultTranspileOptions`.

@kitsonk What do you think?

**Comment by maxmellen** [comment]
@kitsonk I've opened a PR here: https://github.com/denoland/deno/pull/3899

**Comment by kitsonk** [comment]
Transpile does no type checking, so strict mode makes no sense there.

**Pull request closed without merging**
