### PR TITLE
Print error and exit when fails to load custom config

### PR DESCRIPTION
**Pull request by viktor-ku**
Fixes https://github.com/denoland/deno/issues/2549

### CODE REVIEW

**Comment by ry** [comment]
Hi @viktor-ku - Sorry for the slow reply! In order to land this we need a test, which could be done using the integration test mechanism in the tests directory: https://github.com/denoland/deno/tree/master/tests

**Comment by viktor-ku** [comment]
@ry got it. Will look into it this weekend. Should I add a test case in which I am trying to load a config by a wrong path and verify that I got the error (exited with 1) or should I also test how the stderr looks?

**Comment by ry** [comment]
> by a wrong path and verify that I got the error (exited with 1) or should I also test how the stderr looks?

Yes, both should be possible with an integration test. Thanks!

**Comment by bartlomieju** [comment]
@viktor-ku are you working on this issue? If not I can easily address it while working on #2686.

**Comment by viktor-ku** [comment]
@bartlomieju yeah, it will make more sense to address it with your PR. Let me know if you decide to take this part and I will close this issue then.

**Comment by bartlomieju** [comment]
@viktor-ku so I fixed the problem in #2686

**Pull request closed without merging**
