### PR TITLE
feat(cli/installer): Default directory to ~/.local/bin on Unix

### PR DESCRIPTION
**Pull request by nayeemrmn**
Matches https://github.com/denoland/deno_install.

### CODE REVIEW

**Comment by ry** [comment]
This makes it more difficult to uninstall deno, since all the installed scripts will be in a global directory. Cargo uses `$HOME/.cargo/bin/`.

**Comment by nayeemrmn** [comment]
Hmm... it also puts the cargo executable there, though.

`deno install` just creates helper shell scripts for people, right? Maybe "uninstalling Deno" doesn't need to include easily clearing your file system of any shell script which uses Deno, or at least that's another way of looking at it.

**Comment by ry** [comment]
I would be open to making deno_install put the binary into `~/.deno/bin`

**Comment by nayeemrmn** [comment]
Ref https://github.com/denoland/deno_install/issues/40 😄

**Pull request closed without merging**
