### PR TITLE
feat(op_crate/web): TextEncoderStream

### PR DESCRIPTION
**Pull request by crowlKats**

### CODE REVIEW

**Comment by kitsonk** [comment]
I haven't looked at this in detail, but this needs tests, ideally based off the WPT (https://github.com/web-platform-tests/wpt/tree/master/encoding/streams), plus we shouldn't implement it without the `TextDecodingStream`, IMO.

I guess it should also be noted that while it is part of the WHATWG Encoding living standard, it only exists in Chromium based browsers: https://chromestatus.com/feature/4881011259211776.  I don't have any major issue with it, because it has been there for a while, but it wouldn't be the first time something changes.

**Comment by caspervonb** [comment]
Only found two test cases for this in wpt so far.

- https://github.com/web-platform-tests/wpt/blob/e1e713c842e54ea0a9410ddc988b63d0e1d31973/encoding/streams/encode-bad-chunks.any.js
- https://github.com/web-platform-tests/wpt/blob/e1e713c842e54ea0a9410ddc988b63d0e1d31973/encoding/streams/encode-utf8.any.js

Fairly trivial to bring over.

**Comment by kitsonk** [comment]
@crowlKats I can rebase this and deal with the wpt tests if you don't have the time or desire.

**Comment by crowlKats** [comment]
@kitsonk well ideally this PR was also going to take care of TextDecoderStream, but i didnt manage it, then @caspervonb said he would look at it and even he got scared when seeing the spec.

**Comment by crowlKats** [comment]
Closing in favour of #10842

**Pull request closed without merging**
