### PR TITLE
Commits from v1.19.3 to main

### PR DESCRIPTION
**Pull request by kt3k**

### CODE REVIEW

**Review by bartlomieju — APPROVED** [review]

**Review by dsherret — APPROVED** [review]
LGTM

**Comment by kt3k** [comment]
Should this be merge with 'Rebase and merge'?

**Comment by dsherret** [comment]
Probably, but I'm not sure it matters now that there's just one commit.

**Comment by bartlomieju** [comment]
No, doing a squash is fine since the commits are already on `main`.

**Comment by kt3k** [comment]
Ok. I'll do squash this time

**Pull request merged**
