### PR TITLE
perf(ext/websocket): use opAsync2 to avoid spread deopt

### PR DESCRIPTION
**Pull request by littledivy**
This commit adds a new core API `opAsync2` to call an async op with atmost 2 arguments. Spread argument iterators has a pretty big perf hit when calling ops.

| name | avg msg/sec/core |
| --- | --- |
| 1.32.1 | `127820.750000` |
| #18506 | `140079.000000` |
| #18506 + #18509 | `150104.250000` |
| #18506 + #18509 + this | `157340.000000` |

### CODE REVIEW

**Review by aapoalas — APPROVED** [review]
Looks good to me. One thing I wonder is what was the performance impact of doing async ops with a callback API? Ie. Create a CB taking the promiseid parameter that core then synchronously calls to init the actual op.

**Review by bartlomieju — CHANGES_REQUESTED** [review]
Please migrate all relevant ops to this variant

**Comment by littledivy** [comment]
@aapoalas For promises, we currently batch multiple completed operations in one single `opresolve` call. With callbacks for each one, it will be multiple entries into JS. I think we did investigate this some time ago.

**Comment by aapoalas** [comment]
> @aapoalas For promises, we currently batch multiple completed operations in one single `opresolve` call. With callbacks for each one, it will be multiple entries into JS. I think we did investigate this some time ago.

No I mean for starting the op: What the opAsync call essentially does is that it injects the promiseid argument to the actual call's arguments. If instead it took as parameter a single callback that it called with the promiseid then the caller of opAsync could in that callback call the actual op binding function without spreading args.

**Comment by littledivy** [comment]
> No I mean for starting the op: What the opAsync call essentially does is that it injects the promiseid argument to the actual call's arguments. If instead it took as parameter a single callback that it called with the promiseid then the caller of opAsync could in that callback call the actual op binding function without spreading args.

Yup that would work. We could also try `arguments.length` if thats faster. For now, I like opAsync2, opAsync3 because its easier to mass replace.

**Review by bartlomieju — APPROVED** [review]
LGTM

**Pull request merged**
