### PR TITLE
improve(std/assert): Diff message improvements

### PR DESCRIPTION
**Pull request by wongjiahau**
This PR addresses #6572.

With this PR, the following operations are performed before diffing:
- sort object keys
- stringify properly
- dont truncate array
- always print entries of array/object in multiple line
- dont group array items

### CODE REVIEW

**Comment by wongjiahau** [comment]
Some examples :
```ts
Deno.test('object with short keys', () => {
  assertEquals(
    { x: { y: { z: 2 } } },
    { x: { y: { z: 3 } } }
  )
})
```
image

---

```ts
Deno.test('unordered keys', () => {
  assertEquals({ a: 1, b: 2, c: 3 }, { c: 2, b: 2, a: 1 })
})
```
image

---
```ts
Deno.test('array of objects (1)', () => {
  assertEquals([2, { a: 1, b: 2, c: 3 }], [{ c: 3, b: 2, a: 1 }])
})
```
image

---
```ts
Deno.test('nested array objects', () => {
  assertEquals([{ x: [{ y: 2 }] }], [{ x: [{ y: 3 }] }])
})
```
image

**Comment by wongjiahau** [comment]
@nayeemrmn I updated by using `Deno.inspect` instead of my own `stringify`, anything else I need to change?

**Comment by nayeemrmn** [comment]
A `pretty` option in `InspectOptions` which does a bunch of arbitrary things is not a great design. This PR still adds some unnecessary structure to the diffing in `std`. I've opened #6591. It doesn't address wrapping lines for small objects but if you insist on that change and people agree, I can add `Deno.InspectOptions::alwaysWrap` or something.

**Comment by wongjiahau** [comment]
@nayeemrmn I can break the `pretty` options into `trailingComma` and `sortKeys`.

**Comment by wongjiahau** [comment]
Hi @bartlomieju can you help me review this PR?

**Comment by wongjiahau** [comment]
Closing in favour of #6591

**Pull request closed without merging**
