### PR TITLE
fix(ext/flash): Avoid sending Content-Length when status code is 204

### PR DESCRIPTION
**Pull request by ayame113**
Currently Content-Length is sent when the status code is 204. However, according to the spec, this should not be sent.
Modify the if statement below to prevent the Content-Length from being sent.

https://github.com/denoland/deno/blob/b26d0b8a03e0ee616a42d8903fa3db6e9b255802/ext/flash/01_http.js#L154-L156

### CODE REVIEW

**Comment by bartlomieju** [comment]
@littledivy please review

**Comment by ayame113** [comment]
If any additional work is required to merge this, please let me know.

**Review by littledivy — APPROVED** [review]
LGTM. Sorry for the delay 🙇

**Comment by ayame113** [comment]
> Sorry for the delay 🙇

No problem, thanks for the review!

**Pull request merged**
