### PR TITLE
fix(cli): uninstall command accept short flags

### LINKED ISSUE #16763: uninstall subcommand does not accept short flags
I noticed that deno's subcommand for removing executable scripts from root's bin directory does not accept short flags.
In particular, the option for printing help information and the option for suppressing diagnostic output do not work as expected.

**help option**
```
$ deno uninstall -h
error: No installation found for -h
```

**quiet option**
```
$ deno uninstall -q
error: No installation found for -q
```
```
$ deno uninstall -q serve
error: Found argument 'serve' which wasn't expected, or isn't valid in this context
```
note that the long flag prints to the console
```
$ deno uninstall --quiet serve
deleted /home/user/.deno/bin/serve
✅ Successfully uninstalled serve
```
version: deno 1.28.1

### PR DESCRIPTION
**Pull request by rubiagatra**
There is an error about short flags in uninstall subcommand and it will fixes #16763 

Current Situation
```
➜ deno uninstall -h
error: No installation found for -h
```

With this PR 

```
❯ ./target/debug/deno uninstall -h
deno-uninstall
Uninstall a script previously installed with deno install

USAGE:
    deno uninstall [OPTIONS] <name>

ARGS:
    <name>

OPTIONS:
    -h, --help           Print help information
    -q, --quiet          Suppress diagnostic output
        --root <root>    Installation root
        --unstable       Enable unstable features and APIs
```

### CODE REVIEW

**Comment by rubiagatra** [comment]
could you check this PR @lucacasonato?

**Review by dsherret — CHANGES_REQUESTED** [review]
Would you be able to add a unit test in cli/args/flags.rs to demonstrate this fixes the issue and to help prevent regressions? Thanks!

**Comment by rubiagatra** [comment]
I accidentally delete my for repo i will close the PR

**Comment by iuioiua** [comment]
Your forked repo appears not to be deleted: https://github.com/rubiagatra/deno/tree/bugfix/16763-uninstall-subcommand-does-not-accept-short-flags

**Comment by rubiagatra** [comment]
I fork once again and create another PR.

I created with the same branch but not connected with this PR @iuioiua

**Pull request closed without merging**
