### PR TITLE
Support single dash CLI flags like -help

### LINKED ISSUE #1014: support command-line args with only one dash
Golang style. So we should be able to do
```
deno -allow-net server.js
```

### PR DESCRIPTION
**Pull request by ry**
Fixes #1014 

cc @kevinkassimo

### CODE REVIEW

**Comment by bartlomieju** [comment]
I'll to check if this won't break [flags module from std lib](https://github.com/denoland/deno_std).

**Comment by hayd** [comment]
So this is:

> At the cost of requiring that each option be specified with a separate command-line argument

right?

**Comment by ry** [comment]
@hayd That's correct

**Comment by ry** [comment]
@piscisaureus I like it because its simpler and less to type. 

Here are other discussions:

>"Traditionally, UNIX command-line options consist of a dash, followed by one or more lowercase letters. The GNU utilities added a double-dash, followed by a complete word or compound word."

http://tldp.org/LDP/abs/html/standard-options.html

> The Go flag package's command lines adopt the observation made by the Google C++ command line flag parser (https://gflags.github.io/gflags/): the long/short --/- two-names-for-every-flag dichotomy was useful for backwards compatibility when recreating original Unix commands, but for new programs, it doesn't pull its weight. At the cost of requiring that each option be specified with a separate command-line argument, you can drop the distinction between - and -- entirely. (This is similar to what X11 programs do, although I believe they do not admit --x as a synonym for -x.)
> It's not clear to me what is "ugly" about not having to keep alternating between - and -- as you spell out options on the command line.

Rob Pike, https://news.ycombinator.com/item?id=9206782

**Comment by piscisaureus** [comment]
On tldp:

> "Traditionally, UNIX command-line options consist of a dash, followed by one or more lowercase letters. The GNU utilities added a double-dash, followed by a complete word or compound word."

I read this comment as "traditionally there was only `rm -rf` but gnu added `rm --recursive --force`.
In other words, it's not an argument in favor of this PR but against it.

Rob Pike defers to gflags, which notes in it's documentation:

> Note that flags do not have single-letter synonyms, like they do in the getopt library, nor do we allow "combining" flags behind a single dash, as in ls -la.

However I think that having shorthand options for `--allow-write` and `--allow-net` at some point is highly desirable. Let 's say we pick -W and and -N. Then `deno -W -N foo.ts` is already nice, and `deno -WN foo.ts` is even nicer.

**Comment by ry** [comment]
> However I think that having shorthand options for --allow-write and --allow-net at some point is highly desirable. Let 's say we pick -W and and -N. Then deno -W -N foo.ts is already nice, and deno -WN foo.ts is even nicer.

I'd rather keep the number of flags restricted and open for user code to take advantage of - so I'm not keen to add `-W` or `-N`.... but you're right that this precludes the ability to combine abbreviated flags in a single argument. But we only have `-A`, `-r` (which is questionable and maybe should be removed), `-D` and I don't want to add more... so I don't think it's much of a problem.

The single dash flag parsing is used in Go... and so it is increasingly standard practice. I find it quite ergonomic.

**Comment by piscisaureus** [comment]
> I'd rather keep the number of flags restricted and open for user code to take advantage of - so I'm not keen to add `-W` or `-N`.... but you're right that this precludes the ability to combine abbreviated flags in a single argument. But we only have `-A`, `-r` (which is questionable and maybe should be removed), `-D` and I don't want to add more... so I don't think it's much of a problem.

I don't our current practice of allowing deno flags everywhere is sustainable at all. We may not have any users yet, but at some point when we are "stable" won't be able to add any flags because it'll break user code. Also, we won't be able to upgrade v8 *ever again*. So we'll migrate flag parsing to `deno --deno-flag script.ts --user-flag`.

**Comment by ry** [comment]
@piscisaureus I'd like to avoid that. Actually I just commented a few minutes ago on my reasoning in a separate thread: https://github.com/denoland/deno/issues/1554#issuecomment-457322722

**Comment by piscisaureus** [comment]
I think it should be telling that there is nobody in support of your ideas on flag parsing and lots of people against it.

**Comment by ry** [comment]
Ok I recognize people are skeptical, so I will withdraw this PR.
I do think my flag scheme is good and reasonable - but I will write up a more formal proposal and try to obtain consensus.

**Pull request closed without merging**
