### PR TITLE
feat(ext/weblocks): Web Locks Api

### PR DESCRIPTION
**Pull request by load1n9**

### CODE REVIEW

**Comment by bartlomieju** [comment]
@load1n9 thanks for working on this, are there any WPT tests that we could enable?

**Comment by sgwilym** [comment]
@bartlomieju There do seem to be WPT tests for web locks: https://github.com/web-platform-tests/wpt/tree/master/web-locks

**Comment by bartlomieju** [comment]
> @bartlomieju There do seem to be WPT tests for web locks: https://github.com/web-platform-tests/wpt/tree/master/web-locks

@load1n9 please enable these tests

**Comment by sgwilym** [comment]
@load1n9 Why did you close this? Mistake?

**Comment by load1n9** [comment]
yeah opened it again

**Pull request closed without merging**
