### PR TITLE
refactor: split RecursiveLoad

### PR DESCRIPTION
**Pull request by bartlomieju**

### CODE REVIEW

**Comment by ry** [comment]
@bartlomieju Can you draft a commit message for this?

**Comment by bartlomieju** [comment]
@ry 
```
refactor: split RecursiveLoad

* factor out MainImportRecursiveLoad - to be used when executing main module on Isolate
* factor out DynImportRecursiveLoad - to be used when loading dynamic imports from Isolate
```

**Comment by ry** [comment]
@piscisaureus Please review

**Comment by bartlomieju** [comment]
@ry just FYI this PR is really half baked - it just splits `RecursiveLoad`, there's some code duplication as well. My plan for this PR was to do way more, but as we discussed offline it's waiting on new V8 binding lib. Anyway, if you feel this is an improvement then let's land :+1:

**Comment by bartlomieju** [comment]
This PR is stale and doesn't introduce any improvements. Closing for now

**Pull request closed without merging**
