### PR TITLE
fix(ext/ffi): check for permissions in UnsafeFnPointer#call

### PR DESCRIPTION
**Pull request by DjDeveloperr**
UnsafeFnPointer calls did not check for FFI permission.

### CODE REVIEW

**Review by piscisaureus — APPROVED** [review]

**Review by piscisaureus — CHANGES_REQUESTED** [review]
Thanks @DjDeveloperr, the patch looks good.
Would it be possible to add a test for this?

**Comment by aapoalas** [comment]
I would like to challenge this PR:

Imagine an FFI library that has been loaded for the purpose of using a single API call. That API call will return a function pointer that should be later called periodically.

To guard the safety of the environment running this code, the library user revokes the FFI permission after loading the library. This way no malicious foreign code (dependency or other) can use the FFI permission to load eg. their custom DLL payload (if they had rw rights to some folder) or just load some well-known DLL that offers more APIs they need to further their attack.

Now, if the FFI permission is needed to call the received function pointer, it means that the permission cannot be revoked and still keep the code running. Unfortunately this same issue currently applies to `UnsafePointerView` reads as well, which are likely to be necessary for some FFI work.

I feel that the FFI permission may need to be more granular (load vs use), or otherwise somehow rethought to allow "load, revoke, use" sort of flow.

**Comment by DjDeveloperr** [comment]
I think that security model is pretty hard to implement in reality, loading a library vs using pointer APIs are both very unsafe on their own. Even if we are to add it, that would be for another PR.

**Comment by aapoalas** [comment]
After some discussion on Discord, I heartily support this PR.

**Pull request closed without merging**
