### PR TITLE
fix(ext/node): refactor http.ServerResponse into function class

### LINKED ISSUE #19901: Package compatibility problem with `light-my-request`
A Node/npm compatibility issue was reported by a Discord user with the [`light-my-request`](https://github.com/fastify/light-my-request) module. The following code should theoretically work in Deno, but produces an error.

```ts
import http from "node:http";
import inject from "npm:light-my-request";

const dispatch = function (_req, res) {
  const reply = "Hello World";
  res.writeHead(200, {
    "Content-Type": "text/plain",
    "Content-Length": reply.length,
  });
  res.end(reply);
};

const server = http.createServer(dispatch);

inject(dispatch, { method: "get", url: "/" }, (err, res) => {
  console.log(err);
  console.log(res.payload);
});
```

Error:

```
kevin@kevin-deno deno-support % deno run -A test.ts 
error: Uncaught TypeError: Class constructor ServerResponse cannot be invoked without 'new'
    at new Response (file:///Users/kevin/Library/Caches/deno/npm/registry.npmjs.org/light-my-request/5.10.0/lib/response.js:10:23)
    at doInject (file:///Users/kevin/Library/Caches/deno/npm/registry.npmjs.org/light-my-request/5.10.0/index.js:56:17)
    at inject (file:///Users/kevin/Library/Caches/deno/npm/registry.npmjs.org/light-my-request/5.10.0/index.js:15:12)
    at file:///Users/kevin/dev/deno-support/test.ts:15:1
```

### PR DESCRIPTION
**Pull request by nicolabovolato**
Fixes #19901

## Context

[light-my-request](https://www.npmjs.com/package/light-my-request) is used internally by `fastify.inject()`, which in turn is used to [test routes](https://fastify.dev/docs/latest/Guides/Testing/#testing-with-http-injection) without spinning up an HTTP server.

Since it relied on `http.ServerResponse.call()` it could not work on Deno, which used an ES6 class.
This PR should fix that.

## Technical

While testing, I found out that light-my-request relies on `ServerResponse.connection`, which is deprecated, so I added that and `socket`, the non deprecated property.

It also relies on an undocumented `_header` property, apparently for [raw header processing](https://github.com/fastify/light-my-request/blob/v6.1.0/lib/response.js#L180-L186). 
I added it as an empty string, feel free to provide other approaches.

Code is definitely uglier now, but there are not many options... suggestions are welcome!

### CODE REVIEW

**Comment by nicolabovolato** [comment]
> @nicolabovolato thanks for the PR. Could you please add a test to tests/unit_node/http_test.ts that tests new APIs you added as well as creating a ServerResponse using "ES5 style classes"?

I added some, let me know if we should have more 👍🏼

**Comment by nicolabovolato** [comment]
@bartlomieju I think I've found abetter way to do this, without es5 classes and without rewriting the whole `ServerResponse` class.

```ts
import { EventEmitter } from "node:events";
import { EventEmitterOptions } from "npm:@types/node";

class Base extends EventEmitter {
  constructor(options?: EventEmitterOptions) {
    super(options);
  }

  static override call(cls: any, options?: EventEmitterOptions) {
    const x = new this(options);
    Object.assign(cls, x);
  }
}

function Class(this: any) {
  Base.call(this, {});
}
Object.setPrototypeOf(Class.prototype, Base.prototype);

const x = new (Class as any)();
console.log(x);

x.on("foo", (data: any) => console.log(data));

x.emit("foo", "bar");
```

I'll open another pr in the following days.

**Comment by bartlomieju** [comment]
@nicolabovolato I think the current solution is fine, it's closer to what Node.js is doing, so I'd prefer to go with this approach.

**Comment by bartlomieju** [comment]
@littledivy please take a look - this is fine for me so if you don't have any objections we should land it.

**Review by littledivy — APPROVED** [review]
LGTM

**Pull request merged**
