### PR TITLE
feat(core): return v8::Value from JsRuntime::execute_script

### PR DESCRIPTION
**Pull request by bartlomieju**
This commit changes return type of JsRuntime::execute_script to include
v8::Value returned from evaluation.

When embedding deno_core it is sometimes useful to be able to inspect
script evaluation value without the hoops of adding ops to store the
value on the OpState.

v8::Global<v8::Value> is used so consumers don't have to pass
scope themselves.

Closes https://github.com/denoland/deno/issues/11105

### CODE REVIEW

**Review by ry — COMMENTED** [review]
1. This exposes V8 API to deno_core callers. This has not been 100% the case already, but generally we expect that deno_core callers do not need to interact with V8.

2. This unnecessarily creates a `v8::Global`, it could use a local handle.

**Comment by bartlomieju** [comment]
> This exposes V8 API to deno_core callers. This has not been 100% the case already, but generally we expect that deno_core callers do not need to interact with V8.

Correct, but current API is very limiting - for simple one-off scripts you need to setup an op to store some result on state instead of getting the result back directly - some caller actually want to inspect the value.

As a counter argument `v8` objects already leak in `runtime/` crate for web worker and inspector server implementation.

> This unnecessarily creates a v8::Global, it could use a local handle.

Correct, otherwise I'd need to change the signature to accept `scope` parameter, which would be even more unwieldy. 

I presume you're not happy with that change.

**Comment by lucacasonato** [comment]
Why not just return a generic `T: Deserialize` and deserialize the result with serde_v8?

**Comment by bartlomieju** [comment]
> Why not just return a generic `T: Deserialize` and deserialize the result with serde_v8?

Because you might return a value that doesn't implement this trait - eg. a class instance

**Comment by caspervonb** [comment]
At-least for my use case in the test runner I could derive `Deserializable` on `TestResult` and return it directly.
So `T: Deserializable` be sufficient to remove the test message ops.

Either way, this PR will let me untangle the test runner quite a bit and remove all of the "test message ops" 👍

**Comment by bartlomieju** [comment]
@ry #11169 is a good example why this change is desirable, besides requests on Discord

**Comment by ry** [comment]
I don't like the unnecessary use of Global and leaking of v8 objects into the deno_core API. But maybe @piscisaureus has a different opinion.

**Comment by piscisaureus** [comment]
> I don't like the unnecessary use of Global and leaking of v8 objects into the deno_core API.

I agree with this.

**Comment by bartlomieju** [comment]
@ry @piscisaureus do you alternative approach to #11169 that doesn't require ops?

**Comment by lucacasonato** [comment]
I would still argue it should just return a serde_v8 deserializable. We already have the limitation that you can only return simple objects and primitives through ops, so I don't see how `execute_script` should be any different in that regard. Using a deserializable should be enough to resolve #11169 according to @caspervonb.

**Comment by caspervonb** [comment]
>  Using a deserializable should be enough to resolve #11169 according to @caspervonb.

Actually, I guess from `evaluate_script` I would get a promise since I can't await it and we can't deserialise that.
Altho that could probably be punted to rusty_v8?

**Review by piscisaureus — APPROVED** [review]

**Pull request merged**
