### PR TITLE
chore: fix & update node compat config

### PR DESCRIPTION
**Pull request by kt3k**
This PR moves the below compat test cases to `unit_node` test cases:

- `parallel/test-module-run-main.js`
- `parallel/test-worker-threads-broadcast-channel.js`
- `parallel/test-worker-threads-message-channel.js`

These are not copied from Node.js source tree, but they are our own test cases. We should test them under `cli/test/unit_node`.

ref. #19086 #19080

### CODE REVIEW

**Comment by kt3k** [comment]
I'll try to add a lint checker for preventing this kind of issue

**Review by bartlomieju — APPROVED** [review]
Oooops, sorry for that I should have verified that they are coming from Node.

CC @marvinhagemeister if you decide to add more tests

**Comment by bartlomieju** [comment]
No worries, I should have double checked before landing :)

**Comment by kt3k** [comment]
I think the current setup for node compat testing is too confusing. I'll try to add some checks in CI

**Pull request merged**
