### PR TITLE
fix(ext/web): better typings for ReadableByteStream

### PR DESCRIPTION
**Pull request by crowlKats**
Currently extending `ReadableStream` and using a bytestream is not possible (ts will complain one way or the other). In reality on the changes in `declare var ReadableStream` are necessary. I am not too sure the other changes are accurate to spec

### CODE REVIEW

**Review by lucacasonato — COMMENTED** [review]
All the `V`'s need to have defaults, otherwise this change is backwards incompatible. Also, is TS doing something similar?

**Comment by crowlKats** [comment]
TS doesnt have any readablebytestream related typings

**Comment by bartlomieju** [comment]
Is this PR somehow blocked? Can we land it for 1.19?

**Review by lucacasonato — COMMENTED** [review]
Does this pass all `deno_std` tests?

**Comment by crowlKats** [comment]
@lucacasonato yep!

**Review by kitsonk — APPROVED** [review]
LGTM

**Review by ry — COMMENTED** [review]
Test?

**Comment by crowlKats** [comment]
> LGTM

@kitsonk as from my original comment, i actually am a bit unsure about if the `ReadableStreamBYOBRequest` part of things is actually correct. i think it is possible to pass any typed array and the spec does conversions, but unsure

**Comment by crowlKats** [comment]
Closing as am unsure of the validity of this PR & staleness.

**Pull request closed without merging**
