### PR TITLE
refactor(tests): Watcher test timeout

### LINKED ISSUE #17438: Add timeout to `wait_contains()` in watcher tests
## Problem

A common failure indicator of `watcher_tests.rs` is that a test case gets stuck.  
Affected test cases can be debugged by rerunning tests with `--nocapture` and carefully comparing output to expected output.  
This is not possible in CI, and inefficient on developer machines.

## Steps to reproduce

Change the `s` argument of any `wait_contains()` call and run the relevant test case.

## Suggested solution

Add a timeout, say 60 seconds.  
When the timeout expires, abort the test case and log `s` (The text being waited for).

Bonus points if `stdout` and `stderr` can be logged, this would be especially useful for failures that only occur in CI.

### PR DESCRIPTION
**Pull request by Cre3per**
Closes #17438

I combined `#[flaky_test]` with `#[tokio::main]`. It's working but I'm not sure this is the right way to make a flaky test async.

### CODE REVIEW

**Comment by Cre3per** [comment]
Converted to draft, because I need to restore `eprintln!()` calls that I removed from `child_lines()`

**Comment by Cre3per** [comment]
`ci / test debug ubuntu-22.04-xl` failed because of #18442  
Can't tell what's up with `ci / test debug windows-2022-xl`. All steps are stopped but the job has been running for over 2 days.

@bartlomieju Seeing that you were active in this PR already, could you have a look the workflow? I don't know how I could get the checks to pass without pushing to trigger a rerun.

**Comment by bartlomieju** [comment]
Sorry @Cre3per I missed the ping. Yes, I will take a look at what's going on.

**Review by dsherret — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
