### PR TITLE
fix: move the permission check at the beginning of the upgrade process

### LINKED ISSUE #13723: Skip deno upgrade if user lacks write permission to deno executable
Currently `deno upgrade` downloads the approximately 32mb archive first then informs the user they lack permission to write to /bin.
Instead, it should should do a quick check for write permission to the `deno` executable location prior to downloading to save bandwidth.

### PR DESCRIPTION
**Pull request by mlemesle**
Fix #13723

### CODE REVIEW

**Comment by crowlKats** [comment]
@mlemesle please run `tools/format.ts`

**Comment by mlemesle** [comment]
Done !
However, 89 files (including the one I pushed) have been modified by the format.js then the lint.js.
Should I push them all or only the one concerned by this PR ?

**Comment by bartlomieju** [comment]
> Done ! However, 89 files (including the one I pushed) have been modified by the format.js then the lint.js. Should I push them all or only the one concerned by this PR ?

This sounds wrong, there should only be a single file formatted. What versions of Deno and `rustfmt` you have installed?

**Comment by mlemesle** [comment]
```zsh
➜ deno --version
deno 1.19.0 (release, x86_64-apple-darwin)
v8 9.9.115.7
typescript 4.5.2
```

```zsh
➜ rustfmt --version
rustfmt 1.4.38-stable (db9d1b20 2022-01-20)
```

I used Deno that i built from the main branch directly. Rustfmt comes with the Rust toolchain and I'm in 1.58.1

**Comment by bartlomieju** [comment]
> ```shell
> ➜ deno --version
> deno 1.19.0 (release, x86_64-apple-darwin)
> v8 9.9.115.7
> typescript 4.5.2
> ```
> 
> ```shell
> ➜ rustfmt --version
> rustfmt 1.4.38-stable (db9d1b20 2022-01-20)
> ```
> 
> I used Deno that i built from the main branch directly. Rustfmt comes with the Rust toolchain and I'm in 1.58.1

These versions look ok. It's surprising that so many files were changed. After running `./tools/format.js` only the file you did changes too should be reformatted.

**Comment by mlemesle** [comment]
I just reseted and re-ran the format.js and lint.js scripts and this time only the file I changed is showing up as modified. This is kinda weird, maybe something happened the very first time I tried to run those without pulling the submodules...
Anyway, seems fine now, I'll add the properly formatted file

**Comment by crowlKats** [comment]
ideally we'd add a test for this, but this seems something quite challenging to test

**Review by dsherret — APPROVED** [review]
LGTM. Thanks @mlemesle!

**Comment by mlemesle** [comment]
Wasn't much!
Glad I could contribute, thanks for the opportunity!

**Pull request merged**
