### PR TITLE
website: fixes for dark color scheme

### PR DESCRIPTION
**Pull request by vaaski**
fixed the logo invert and made the code block readable.

### CODE REVIEW

**Comment by vaaski** [comment]
sure. I think you know how the proper inverted logo looks, so here is the code block with my commit:
image
it's not pretty but at least it's not white, and you can read all the text.

here's before:
image

**Comment by kt3k** [comment]
@vaaski Which browser do you use?

On my machine, the current code block looks like the below:
スクリーンショット 2019-07-06 22 13 04
(↑this is firefox, but it's similar in chrome canary and safari.)

And this branch looks like the below:
スクリーンショット 2019-07-06 22 15 32

**Comment by vaaski** [comment]
Just normal Google Chrome 75 and I changed the CSS in the dev console like this;
image

**Comment by ry** [comment]
@vaaski Thanks but I have the same concerns as @kt3k - going to close this one.

**Pull request closed without merging**
