### PR TITLE
chore: upgrade Rust version to `1.56.1`

### PR DESCRIPTION
**Pull request by abdfnx**
> upgrade Rust version to **1.56.1** in

1. `.devcontainer/Dockerfile`
2. `.github/workflows/ci.yml`

### CODE REVIEW

**Comment by dsherret** [comment]
Looks like the CI keeps saying it's out of space. Maybe the cache needs to be cleared somehow when doing this upgrade? I'm not sure how to do that on the CI.

**Comment by abdfnx** [comment]
ok, so is the problem is from me or from the CI ?

**Comment by bartlomieju** [comment]
> ok, so is the problem is from me or from the CI ?

I pushed a commit that rotates cache keys, let's see if it helps.

**Comment by abdfnx** [comment]
> > ok, so is the problem is from me or from the CI ?
> 
> I pushed a commit that rotates cache keys, let's see if it helps.

looks like you fixed it

**Review by dsherret — APPROVED** [review]
LGTM. Thanks @abdfnx!

And thanks Bartek for busting the cache :)

**Comment by abdfnx** [comment]
> LGTM. Thanks @abdfnx!
> 
> And thanks Bartek for busting the cache :)

glad to help @denoland

`deno` one of the best tools that I used ever

**Pull request merged**
