### PR TITLE
fix #7660

### LINKED ISSUE #7660: Fetching https://1.1.1.1 or any other bare IP address fails with 'invalid dnsname'
HTTPS fetch with bare IPv4 address fails:
```
> deno run --allow-net https://deno.land/std@0.70.0/examples/curl.ts https://1.1.1.1/
error: Uncaught Http: error sending request for url (https://1.1.1.1/): error trying to connect: invalid dnsname
    at Object.jsonOpAsync (core.js:236:13)
    at async fetch (deno:op_crates/fetch/26_fetch.js:1272:29)
    at async https://deno.land/std@0.70.0/examples/curl.ts:3:13
```

HTTPS fetch with bare IPv6 address fails:
```
> deno run --allow-net https://deno.land/std@0.70.0/examples/curl.ts https://[2606:4700:4700::1111]
error: Uncaught Http: error sending request for url (https://[2606:4700:4700::1111]/): error trying to connect: invalid dnsname
    at Object.jsonOpAsync (core.js:236:13)
    at async fetch (deno:op_crates/fetch/26_fetch.js:1272:29)
    at async https://deno.land/std@0.70.0/examples/curl.ts:3:13
```

Real curl is fine:
```
> curl -sI https://[2606:4700:4700::1111] | head -n1
HTTP/1.1 200 OK

> curl -sI https://1.1.1.1/ | head -n1
HTTP/1.1 200 OK
```

HTTPS fetch with DNS name that resolves to said IP addresses works:
```
> deno run --allow-net https://deno.land/std@0.70.0/examples/curl.ts https://one.one.one.one | grep \\.\\.
............................................................
.........1............1............1............1...........
........11...........11...........11...........11...........
.......111..........111..........111..........111...........
......1111.........1111.........1111.........1111...........
........11...........11...........11...........11...........
........11...........11...........11...........11...........
........11...........11...........11...........11...........
........11...........11...........11...........11...........
........11...........11...........11...........11...........
........11...........11...........11...........11...........
........11...........11...........11...........11...........
........11...........11...........11...........11...........
........11...........11...........11...........11...........
........11....ooo....11....ooo....11....ooo....11...........
......111111..ooo..111111..ooo..111111..ooo..111111.........
............................................................
```

```
> deno --version
deno 1.4.1
v8 8.7.75
typescript 4.0.2
```

### PR DESCRIPTION
**Pull request by CGQAQ**
switch from `rusttls-tls` to `native-tls`

image

Closes #7660

### CODE REVIEW

**Comment by kitsonk** [comment]
Switching from `rustls` to something else is a big change and needs a lot more consideration.

cc/ @piscisaureus @bartlomieju

**Comment by CGQAQ** [comment]
> Switching from `rustls` to something else is a big change and needs a lot more consideration.

Working code better than performant code

**Comment by kitsonk** [comment]
I am not just talking about performance here.  We just don't google core foundational crates and bang them into Deno.

This is something you discuss with the core team _before_ you start raising PRs.  Something like "hey, I think this might fix this issue..."

**Comment by CGQAQ** [comment]
MB, I was just tested on Windows 10, and it worked

**Review by crypt096 — APPROVED** [review]

**Comment by kitsonk** [comment]
As discussed online, I am going to close this.  For fixing #7660 we need to first figure out why `rustls` is failing, and if there is any way to get it to work _before_ we attempt to replace it.

**Pull request closed without merging**
