### PR TITLE
build: write a gcc-style depfile when using clang-cl on windows

### PR DESCRIPTION
**Pull request by piscisaureus**
Because clang-cl doesn't support msvc-style `/showIncludes` header dep detection, at least not in such way that it works properly with sccache.

### CODE REVIEW

**Comment by ry** [comment]
Does this fix https://github.com/denoland/deno/issues/1424 ?

**Comment by piscisaureus** [comment]
> I can't say I really understand what's happening here. So I'm mostly concerned from a long term maintenance perspective: Should this patch be undone when [mozilla/sccache#246](https://github.com/mozilla/sccache/issues/246) is fixed? Or is this something that could be sent upstream to Chrome?

It could probably go upstream; there's no disadvantages to it.
The underlying issue can't be fixed in sccache; it should be (and has been) fixed in in clang (https://reviews.llvm.org/D46394) but that hasn't made it into a stable release yet.

**Comment by piscisaureus** [comment]
> Does this fix #1424 ?

It fixes the rebuild issues I was experiencing locally, so I expect it solves #1424 also. 
But who knows... the only way to find out is to try.

**Comment by ry** [comment]
So maybe add a comment that lets the future maintainer know when they can safely undo that patch. I guess it's when https://reviews.llvm.org/D46394 gets into stable?

**Comment by piscisaureus** [comment]
> I can't say I really understand what's happening here.

MSVC (cl.exe) can't write a depfile, but it has the `/showIncludes` flag that prints included headers to stdout, and ninja parses that output.

sccache adds the `/E` flag that writes preprocessor output to stdout. It uses that compute the hash.

Now what happens if you pass *both* flags?
cl -> writes preprocessor output to stdout and headers to *stderr*
clang-cl -> writes preprocessor output to stdout, and does *not write headers at all*.

So dependency tracking was broken.

With some effort clang-cl *can* however write a gcc-style depfile, so that's what I'm making it do here.

**Comment by piscisaureus** [comment]
> So maybe add a comment that lets the future maintainer know when they can safely undo that patch. I guess it's when https://reviews.llvm.org/D46394 gets into stable?

Did you see this https://github.com/denoland/chromium_build/compare/75a7f82d326101e16b1f99dc1cc173287b0a8b82...1e3840b6d9c3fd3dc7be4fc2c1a2de7798d63df6#diff-215e0f644aef180fe353893e8703f3f2R186 ?

**Comment by piscisaureus** [comment]
er, https://github.com/denoland/chromium_build/compare/75a7f82d326101e16b1f99dc1cc173287b0a8b82...1e3840b6d9c3fd3dc7be4fc2c1a2de7798d63df6#diff-215e0f644aef180fe353893e8703f3f2R186

**Pull request merged**
