### PR TITLE
[WIP] Web Notification API

### PR DESCRIPTION
**Pull request by littledivy**
Uses `notify_rust` which is quite stable on windows and linux, although uses deprecated NS* API for OSX (also used by Tauri). 

The new OSX api for sending notifications is [UN* API](https://developer.apple.com/documentation/usernotifications/unmutablenotificationcontent?language=objc) requires that the application be code-signed whereas `NSUserNotification` does not have this requirement.

### CODE REVIEW

**Comment by littledivy** [comment]
- [ ] Constructor as per spec https://notifications.spec.whatwg.org/#dom-notification-notification
- [ ] Events wherever possible (`onclose`, `onerror`)

**Comment by zorbyte** [comment]
I know it's not my place, but is it possible to get Deno coee signed if they wanted to?

**Comment by crowlKats** [comment]
@zorbyte #575

**Comment by littledivy** [comment]
On hold - I'm waiting to know whether we are "ok" with using the deprecated NS* API for OSX

**Comment by bartlomieju** [comment]
> On hold - I'm waiting to know whether we are "ok" with using the deprecated NS* API for OSX

@littledivy is there an alternative to this approach?

**Comment by crowlKats** [comment]
@bartlomieju as the PR description states, builds would need to be signed. Also as far as my research went there is no crate for the current API, so one would also need to make that. It is a lot of work, but I am personally against using a deprecated API.

**Comment by littledivy** [comment]
I agree with @crowlKats - we should not use the deprecated API. The solution would be to implement a crate for the current API.

**Comment by lucacasonato** [comment]
I am going to close this, as I don't think we are going to land this in the close future as it requires signing the binary, and would bind us to window managers, something we have decided not to pursue in the CLI in the near future with WebGPU. Before we revisit this, more thorough discussion should take place in an issue.

**Pull request closed without merging**
