### PR TITLE
fix(core): fix fetch `size_hint`

### PR DESCRIPTION
**Pull request by marcosc90**
When `max` is known and is greater than `grow_len` initial value is being set to `min` / `grow_len` instead of `max`. This is causing unnecessary resizes.

### CODE REVIEW

**Review by lucacasonato — CHANGES_REQUESTED** [review]
Max is an upper bound. We don't necessarily want to or can allocate that much space. The idea behind this logic is that we allocate the exact size we need if we know it, and otherwise we start at the lesser of `min` or `grow_length`. This prevents initial over-allocation.

As such I don't think this change is necessarily beneficial.

**Comment by marcosc90** [comment]
> Max is an upper bound. We don't necessarily want to or can allocate that much space. The idea behind this logic is that we allocate the exact size we need if we know it, and otherwise we start at the lesser of `min` or `grow_length`. This prevents initial over-allocation.
> 
> As such I don't think this change is necessarily beneficial.

If max is known, we should allocate that much space, otherwise, it shouldn't be set. both fetch & http `size_hint` is returning the exact size of the body in `max` (the only two resources setting max currently), which is being ignored completely by `read_all`. What's the use of `max` if we're not allocating the max size at once, currently unnecessary resizes are being done. Setting `max` is specifically for that fast path.

We know exactly the body size, we should use that fast path when available.

**Comment by marcosc90** [comment]
Furthermore this patch increases `fetch` performance when consuming a body (the most common operation when using `fetch`)

**main**

```
cpu: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
runtime: deno 1.26.1 (x86_64-unknown-linux-gnu)

benchmark       time (avg)             (min … max)       p75       p99      p995
-------------------------------------------------- -----------------------------
fetch 1mb   957.65 µs/iter   (538.74 µs … 4.36 ms) 949.99 µs   2.99 ms   3.91 ms
fetch 5mb     4.06 ms/iter     (3.25 ms … 7.66 ms)   4.11 ms   7.51 ms   7.66 ms
fetch 128k  265.63 µs/iter   (162.47 µs … 3.33 ms) 289.15 µs 914.62 µs   1.14 ms
fetch 16kb  127.55 µs/iter (105.26 µs … 953.49 µs) 130.66 µs 255.74 µs 324.11 µs
```

**this patch**

```
cpu: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
runtime: deno 1.26.1 (x86_64-unknown-linux-gnu)

benchmark       time (avg)             (min … max)       p75       p99      p995
-------------------------------------------------- -----------------------------
fetch 1mb   613.06 µs/iter   (398.42 µs … 3.29 ms) 715.54 µs   1.42 ms   1.71 ms
fetch 5mb     2.82 ms/iter     (1.69 ms … 6.26 ms)   3.08 ms   5.82 ms   6.26 m
fetch 128k  194.14 µs/iter   (145.34 µs … 1.93 ms) 208.52 µs 454.15 µs 581.11 µs
fetch 16kb  122.34 µs/iter (103.14 µs … 949.53 µs) 119.81 µs 248.41 µs 332.82 µs
```

> This prevents initial over-allocation.

Only two resources overriding `size_hint` set `max` to the exact body size, so it doesn't prevent initial over-allocation, it only causes extra resize operations.


|  |128kb|1mb|5mb|2gb
|--|--|--|--|--|
| main: resizes |1|6|14|4100
| patch: resizes |0|0|0|0|0

**Review by lucacasonato — COMMENTED** [review]
Sorry for not responding to this earlier. The logic in `op_read_all` is correct. The size_hint for the HTTP resources is just not. It currently is:

```
  fn size_hint(&self) -> (u64, Option<u64>) {
    (0, self.size)
  }
```

but it should be

```
  fn size_hint(&self) -> (u64, Option<u64>) {
    (self.size.unwrap_or(0), self.size)
  }
```

If the **exact** size is known (`self.size == Some(_)`), then the upper and lower bound should both be set to that exact size. Once you do this the existing `op_read_all` optimisation starts working.

This is already the case for the `size_hint()` in `ext/http`.

**Comment by marcosc90** [comment]
> Sorry for not responding to this earlier. The logic in `op_read_all` is correct. The size_hint for the HTTP resources is just not. It currently is:
> 
> ```
>   fn size_hint(&self) -> (u64, Option<u64>) {
>     (0, self.size)
>   }
> ```
> 
> but it should be
> 
> ```
>   fn size_hint(&self) -> (u64, Option<u64>) {
>     (self.size.unwrap_or(0), self.size)
>   }
> ```
> 
> If the **exact** size is known (`self.size == Some(_)`), then the upper and lower bound should both be set to that exact size. Once you do this the existing `op_read_all` optimisation starts working.
> 
> This is already the case for the `size_hint()` in `ext/http`.

While that will fix the performance issue, IMO that's patching incorrect logic of `op_read_all`. There's no need to set `max` at all if we're using `min` instead and ignoring `max` when it's set. I'll submit the changes for fetch `size_hint` to improve performance though.

**Comment by lucacasonato** [comment]
We're not ignoring max. We're just ignoring max for pre-allocation. But we do use max to prevent over-allocation for example. Under-allocation is always better than over-allocation, as over-allocation can hard crash the process with an OOM error.

**Comment by marcosc90** [comment]
> We're not ignoring max. We're just ignoring max for pre-allocation. But we do use max to prevent over-allocation for example. Under-allocation is always better than over-allocation, as over-allocation can hard crash the process with an OOM error.

My point is that if `max` causes over-allocation, that resource `size_hint` is setting incorrect `max` which should be only set (that's why it's `Option`) when maximum body size is known.

**Review by lucacasonato — APPROVED** [review]
LGTM. We can review the pre-allocation for max if it turns out to be a performance issue in the future for other resources.

**Pull request merged**
