### PR TITLE
fix(dts): `URLPatternComponentResult` groups should have possibly undefined key values

### LINKED ISSUE #18640: Invalid type for `URLPatternComponentResult` according to W3C Web API
Hi! I was trying to shim the URLPattern for nodejs and noticed a difference in the types for URLPatternComponentResult. 

Nodejs type for the shim library that I used ([urlpattern-polyfill](https://github.com/kenchris/urlpattern-polyfill))
```ts
interface URLPatternComponentResult {
  input: string;
  groups: {
    [key: string]: string | undefined;
  };
}
```

Deno type
https://github.com/denoland/deno/blob/25aac6c7a8e015c24966168d0e3897849fefc68a/ext/url/lib.deno_url.d.ts#L207-L210

I checked the [W3C URLPattern API](https://wicg.github.io/urlpattern/#dictdef-urlpatterncomponentresult) and it look like this:
```
dictionary URLPatternComponentResult {
  USVString input;
  record<USVString, (USVString or undefined)> groups;
};
```

It would be nice to have one type for all implementations.

### PR DESCRIPTION
**Pull request by dsherret**
Closes #18640

### CODE REVIEW

**Comment by crowlKats** [comment]
behaviour wise, I believe we currently always give string values, never undefined, so this wouldnt match what we currently do

**Comment by dsherret** [comment]
@crowlKats here's an example

```ts
const pattern = new URLPattern("https://example.com/:id");
const result = pattern.exec("https://example.com/1")!;
console.log(result.port.groups.test.toString()); // type checks fine, fails at runtime
```

**Comment by crowlKats** [comment]
An example of the behaviour I am mentioning which this is actually linked to is:
```
const pattern = new URLPattern("/books/:id?", "https://example.com");
pattern.exec("https://example.com/books")
```
The output is:
```
{
  inputs: [ "https://example.com/books" ],
  protocol: { input: "https", groups: {} },
  username: { input: "", groups: {} },
  password: { input: "", groups: {} },
  hostname: { input: "example.com", groups: {} },
  port: { input: "", groups: {} },
  pathname: { input: "/books", groups: { id: "" } },
  search: { input: "", groups: {} },
  hash: { input: "", groups: {} }
}
```
`pathname.groups.id` is not undefined, even though it should. this didnt use to be the case, and we havent implemented this change from the spec yet.

**Comment by dsherret** [comment]
Currently you can access arbitrary properties on `group` and it won't type error, but it should so this is a fix for that.

**Comment by crowlKats** [comment]
I would say this is definitively related as its the reason the spec changed the type from <string, string> to <string, string | undefined>, but i guess it would make sense to have this regardless of the spec change.

**Review by crowlKats — APPROVED** [review]

**Comment by dsherret** [comment]
Thinking about it more, I can see how the type doesn't exactly match the current behaviour, but considering we don't have `noUncheckedIndexedAccess` enabled by default and this will eventually have properties that have a key with possibly an undefined value in the future, then let's just merge it (but in 1.33 since it might cause some annoyance).

**Comment by lucacasonato** [comment]
@crowlKats does this cause `rutt` to fail typechecking?

**Comment by crowlKats** [comment]
@lucacasonato yes, it does. We can make a release for rutt and update it in fresh and do a release there as well, but seems quite a breaking change

**Review by bartlomieju — APPROVED** [review]
LGTM

**Pull request merged**
