### PR TITLE
feat(core): Reorder extension initialization

### PR DESCRIPTION
**Pull request by Suficio**
Allow passing a custom `ResourceTable` during `JsRuntime` initialization using `RuntimeOptions.resource_table` such that resources can be made available during extension initialization.

### CODE REVIEW

**Review by littledivy — APPROVED** [review]
LGTM.

**Review by bartlomieju — CHANGES_REQUESTED** [review]
Is there an immediate need for this API? If so, I would love to see examples

**Comment by Suficio** [comment]
> Is there an immediate need for this API? If so, I would love to see examples

I have been working on https://github.com/Suficio/bevy_js_prototype/pull/13 which basically embeds Deno in a Bevy context.

I would like to guarantee to the user that at any stage of execution of the program they can have exclusive access to the Bevy world. Since `Extensions` are initialized during the creation of `JsRuntime` they will not have access to the resource that facilitates communication between Bevy and Deno which is what this PR allows them to do.

It is possible to achieve this using the current implementation, but the synchronization code will quickly become un-maintainable.

In the linked PR I am using the resource to determine `TypeIds` of reflectable types as static properties of their constructors which will be the basis for type management across Bevy and Deno. Overall, it's a huge ergonomic improvement for my use case.

If you would like me to provide an example of this functionality as a `deno_core` example, I would be glad to.

**Review by bartlomieju — COMMENTED** [review]
I'm fine with landing this, but @Suficio could you add asserts to `runtime/ops/io.rs` where stdio resources are added to verify that they have expected ids (0 for stdio, 1 for stdout, 2 for stderr)

**Comment by Suficio** [comment]
After a bit of discussion, I realized this could be achieved by reordering the initialization functions.

**Review by bartlomieju — APPROVED** [review]

**Pull request merged**
