### PR TITLE
feat(cli/repl): use completion candidate as hint

### PR DESCRIPTION
**Pull request by caspervonb**
This shows the first completion candidate as a hint, which is rendered as gray text to the right of the cursor.

### CODE REVIEW

**Comment by caspervonb** [comment]
Example

Screenshot 2020-10-26 at 10 12 30 AM

**Review by bartlomieju — CHANGES_REQUESTED** [review]
Discussed offline, needs a test case, we'll land it for 1.6.0

**Review by lucacasonato — CHANGES_REQUESTED** [review]
I like the concept, but there is one major issue. There is a significant lag when typing or removing characters. We seem to be blocking until we get the hint from V8. We should be acquiring the hint asynchronously, and not blocking on that.

Also it would be nice if you could use the up and down keys to navigate through the hints before pressing tab. That is not strictly required for this PR to land though.

**Comment by caspervonb** [comment]
> I like the concept, but there is one major issue. There is a significant lag when typing or removing characters. We seem to be blocking until we get the hint from V8. We should be acquiring the hint asynchronously, and not blocking on that.

Ugh assumed the lag was my ssh connection but compared to bash on the same server indeed it is slow.
Unfortunately the entire rustyline interface is synchronous and callback based so hints have to block until resolved. There's no way to push the current hint at this time 😟 

Most likely won't end up landing this due to the input lag, but I'll see what can be done.

> Also it would be nice if you could use the up and down keys to navigate through the hints before pressing tab. That is not strictly required for this PR to land though.

Don't think this is something the rustyline editor is currently capable of (all the interesting bits are private), but can look into it.

**Comment by bartlomieju** [comment]
@caspervonb seems we can't do much about it until https://github.com/kkawakam/rustyline/issues/126 is resolved. I'm going to provisionally close this PR, let's discuss alternate approaches on Discord.

**Comment by caspervonb** [comment]
Yup, this introduces too much latency at the moment.

**Pull request closed without merging**
