### PR TITLE
fix SHA1 hash of Uint8Array returned from read operation

### LINKED ISSUE #5085: [util/sha1] SHA1 hash of Uint8Array returned from read operation is wrong
`Sha1.update` does not handle `Uint8Array`-s, instead it uses their `.buffer` (`ArrayBuffer`) for hashing, but when `Uint8Array` comes from, e.g. `Deno.readFile` operation, its `.buffer` and actual file contents are not equivalent.

Current workaround would be:

```typescript
const data = await Deno.readFile(fileName);

const t = new Uint8Array(data.byteLength);
copyBytes(data, t);

const hash = new Sha1().update(t).hex();
```

### PR DESCRIPTION
**Pull request by trebler**
Resolves #5085

### CODE REVIEW

**Comment by kitsonk** [comment]
A Uint8Array is an ArrayBufferView. The code is handling this already. I am not sure this is being fixed properly and the test failures seem to verify that, but I am on mobile ATM.

**Comment by trebler** [comment]
@kitsonk, the test fails on old code, and succeeds with the fix. 
`Uint8Array` is indeed `ArrayBufferView`, but `.buffer` cannot be used blindly.

**Comment by kitsonk** [comment]
The fix should follow sha256.ts: https://github.com/denoland/deno/blob/master/std/util/sha256.ts#L108. Just copying the reference to the buffer is dangerous.

**Comment by trebler** [comment]
@kitsonk, `Uint8Array` is not an `instanceof ArrayBuffer`, so I am not sure how the referenced line helps.

I could: 

```typescript
if (data instanceof Uint8Array) {
  message = data.subarray()
// or
  message = new Uint8Array(data.byteLength);
  copyBytes(data, message);
}
```

**Comment by seishun** [comment]
This will still calculate the hash incorrectly for Uint16Array etc, won't it?

**Comment by trebler** [comment]
> This will still calculate the hash incorrectly for Uint16Array etc, won't it?

Why? `Uint16Array` is not `instanceof Uint8Array`

**Comment by seishun** [comment]
https://github.com/denoland/deno/pull/5086/files#diff-9ba2e466fadc40f97f4d70ef40fead37L58

**Comment by trebler** [comment]
> https://github.com/denoland/deno/pull/5086/files#diff-9ba2e466fadc40f97f4d70ef40fead37L58

You reference line not touched in this PR. I have not checked if hash is/was calculated correctly for other data types other than `Uint8Array`.

**Comment by ry** [comment]
Unrelated to this PR - but I want to move these modules out of std/util and into a more appropriately named directory. Maybe std/crypto or std/hash?

**Comment by kitsonk** [comment]
@ry `std/hash`

@trebler sha256 handles Uint8Array's properly (https://github.com/denoland/deno/blob/master/std/util/sha256_test.ts#L159-L162) and the original source they were based on is the same, but adapted by two different people.  We should keep the logic for handling the message the same (https://github.com/denoland/deno/blob/master/std/util/sha256.ts#L103-L121).  In fact it could be DRY'ed up, but that would be a different thing.

**Comment by trebler** [comment]
@kitsonk, I agree that SHA256 code works. And it works exactly because it does exactly the same thing as my PR: assign `Uint8Array` reference to `message` which you commented as:

> Just copying the reference to the buffer is dangerous

<details>
  <summary>Proof (expandable):</summary>
  
```typescript
type Message = string | number[] | ArrayBuffer | Uint8Array;

const test = (message: Message) => {
  const ERROR = "input is invalid type";

  let msg: string | number[] | Uint8Array | undefined;
  if (typeof message !== "string") {
    if (typeof message === "object") {
      if (message === null) {
        throw new Error(ERROR);
      } else if (message instanceof ArrayBuffer) {
        msg = new Uint8Array(message);
      } else if (!Array.isArray(message)) {
        if (!ArrayBuffer.isView(message)) {
          throw new Error(ERROR);
        }
      }
    } else {
      throw new Error(ERROR);
    }
  }

  if (msg === undefined) {
    console.log('Assigning Uint8Array reference to msg');
    msg = message as string | number[];
  }
}

test(new Uint8Array(10));

// > Assigning Uint8Array reference to msg
```
</details>

Would you want me to refactor SHA1 `update` method to be consistent with SHA256?

**Comment by kitsonk** [comment]
I have a right to change my mind 😛🤦. I was on my mobile device late at night my time!  I didn't realise that sha256 was just allowing it to pass through.

It would be great if we kept the logic consistent, hopefully to DRY it up at some point in the future!  The same author has SHA3 as well and the API isn't the worst in the world, so adapting that as well would be good.

**Comment by ry** [comment]
I'll wait to move sha* modules to std/hash (#5160) until this PR lands.

I will also wait for @kitsonk's approval before landing this one.

**Comment by ry** [comment]
Oops, I lied. I'm going to move sha* to hash first in #5087. Sorry. 
I think the merge commit won't be difficult tho.

**Comment by trebler** [comment]
@kitsonk, I have pushed an update to my PR (most code change in `SHA1`). What has been done:

- `SHA1` code has been refactored to resemble `SHA256` as closely as possible (next step is create common interface for all hash types, but that will be done in a new PR) 
- `SHA1` has gotten similar set of tests to `SHA256` (borrowed from the original repo)
- Those test allowed to find and fix bug in `SHA1` `arrayBuffer` method. (Still mystery to me why `Uint32Array.buffer` does not work)
- Type inference logic of `message` has been stripped to minimum. In the context of TypeScript, all those asserts and type checks is imho waste of CPU cycles. Current code is as simple as this:

```typescript
let msg: string | number[] | Uint8Array | undefined;
if (message instanceof ArrayBuffer) {
  msg = new Uint8Array(message);
} else {
  msg = message;
}
```
All typed arrays, `string`, Array<number> , `ArrayBuffer` are properly handled here.

**Comment by trebler** [comment]
@kitsonk can this PR be merged?..

**Comment by kitsonk** [comment]
@trebler I don't have the power.  ping @bartlomieju.

**Comment by trebler** [comment]
> @trebler I don't have the power. ping @bartlomieju.

@bartlomieju, could you review/merge this PR?

**Comment by trebler** [comment]
@ry could this be merged?

**Comment by bartlomieju** [comment]
Thanks @trebler!

**Pull request merged**
