### PR TITLE
Added compodoc for better documentation

### PR DESCRIPTION
**Pull request by deepakshrma**
Hi @ry,

Thanks for creating beautiful language. I am big fan of you. :)

This PR is to add better documentation for TypeScript file. TypeDoc is does not look nice. I used compodoc from my Angular.io projects. It looks nice and clean. I tried to find some other tools to generate doc very specific to typescript. I didn't found. Please check the PR and check the output. If  it look nice i can customise more to get better output. Please refer to below given details.

Running App:
https://denolang-docs.herokuapp.com/

How to run in local:
Pre-Requisite: nodejs npm, compodoc, lite-server
```bash
npm install -g compodoc lite-server
```
Run:
```bash
compodoc -p tsconfig.docs.json --theme stripe
```
Output:
```bash 
cd documentation &&  lite-server
```
Using docs.py:
```bash
python2 tools/docs.py
cd target/compodoc &&  lite-server
```

### CODE REVIEW

**Comment by deepakshrma** [comment]
Sample for basic doc support:
https://github.com/denoland/deno/issues/573

**Comment by kitsonk** [comment]
@deepakshrma sorry I missed this until now.  The compodoc certainly looks like it could be better than TypeDoc, but at the moment it is documenting the internals of Deno, versus what we want to document, which is the Deno runtime environment.  Is there anyway to build the documents off of `lib.deno_runtime.d.ts` that is generated, which is what TypeDoc was being based on?  It is in the `$BUILD_PATH/gen/lib/lib.deno_runtime.d.ts`.

**Comment by deepakshrma** [comment]
Yes can be easy done by basic command.
**using d.ts:**
https://denolang-docs.herokuapp.com/external/
**using .ts:**
https://denolang-docs.herokuapp.com/internal/

**Command to run:**
```bash
rm -rf target/compodoc && mv target/debug/gen/lib/lib.deno_runtime.d.ts target/debug/gen/lib/lib.deno_runtime.ts && compodoc -p tsconfig.json --theme readthedocs --output target/compodoc && mv target/debug/gen/lib/lib.deno_runtime.ts target/debug/gen/lib/lib.deno_runtime.d.ts
```
**Patch:**
```patch
Index: tsconfig.json
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- tsconfig.json	(revision f2447f6a2307369c16322861735a87fdd30f7233)
+++ tsconfig.json	(date 1544715340000)
@@ -22,5 +22,7 @@
     "target": "esnext",
     "types": []
   },
-  "files": ["node_modules/typescript/lib/lib.esnext.d.ts", "js/main.ts"]
+  "files": [
+    "target/debug/gen/lib/lib.deno_runtime.ts"
+  ]
 }
Index: package.json
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- package.json	(revision f2447f6a2307369c16322861735a87fdd30f7233)
+++ package.json	(date 1544715656000)
@@ -1,5 +1,8 @@
 {
   "name": "deno",
+  "scripts": {
+    "docs": "rm -rf target/compodoc && mv target/debug/gen/lib/lib.deno_runtime.d.ts target/debug/gen/lib/lib.deno_runtime.ts && compodoc -p tsconfig.json --theme stripe --output target/compodoc && mv target/debug/gen/lib/lib.deno_runtime.ts target/debug/gen/lib/lib.deno_runtime.d.ts"
+  },
   "devDependencies": {
     "@types/base64-js": "^1.2.5",
     "@types/flatbuffers": "^1.9.0",
````
**After patch:**
```bash
npm run docs
```

**Comment by deepakshrma** [comment]
I can create react-material-app using
https://material-ui.com/ for entry docs
https://deno.land/

**Comment by ry** [comment]
I will review soon. It looks good. Please give me a few days tho.

**Comment by vogloblinsky** [comment]
> npm install -g compodoc lite-server

@deepakshrma Did you use the correct package ? this one is deprecated, the official one is at @compodo/compodoc

**Comment by deepakshrma** [comment]
@vogloblinsky It is just CLI, anything can be used. I can try with new CLI

**Comment by ry** [comment]
@deepakshrma I apologize for not having reviewed this. The thing is we're looking for a more comprehensive documentation solution - and this is more of a bandaid. I appreciate the effort tho.

**Comment by vogloblinsky** [comment]
> @deepakshrma I apologize for not having reviewed this. The thing is we're looking for a more comprehensive documentation solution - and this is more of a bandaid. I appreciate the effort tho.
Thanks for the feedback. (I am the author of Compodoc...)
Have a look at TypeDoc if you want a more standard solution.

**Pull request closed without merging**
