### PR TITLE
fix(console): inspect for `{Set,Map}Iterator` and `Weak{Set,Map}`

### PR DESCRIPTION
**Pull request by petamoriken**
This PR includes the following fixes:

## strict runtime type checking

Fixed a bug that `{Set, Map}Iterator`'s `[[Prototype]]` were not displaying properly

current:

```
> Object.getPrototypeOf( new Set([1, 2, 3]).values() )
[Internal Formatting Error] TypeError: Method Set Iterator.prototype.next called on incompatible receiver #<Iterator>
    at Set Iterator.next (<anonymous>)
    at previewEntries (ext:deno_console/01_console.js:143:21)
    at formatIterator (ext:deno_console/01_console.js:1511:41)
    at formatRaw (ext:deno_console/01_console.js:1053:14)
    at formatValue (ext:deno_console/01_console.js:736:10)
    at Object.inspectArgs (ext:deno_console/01_console.js:3128:28)
    at <anonymous>:3:55
```

this PR:

```
> Object.getPrototypeOf( new Set([1, 2, 3]).values() )
Iterator [Set Iterator] {}
```

This change also improves inspect, such as `Promise` and `AsyncFunction` and so on.

## use `op_preview_entries`

Since JavaScript consumes Iterators in inspect, so `op_preview_entries` is used

current:

```
> const setIterator = new Set([1, 2, 3]).values()
undefined
> setIterator
[Set Iterator] { 1, 2, 3 }
> setIterator
[Set Iterator] {  }
```

this PR:

```
> const setIterator = new Set([1, 2, 3]).values()
undefined
> setIterator
[Set Iterator] { 1, 2, 3 }
> setIterator
[Set Iterator] { 1, 2, 3 }
```

It also allows previews against the `Weak{Set, Map}` with `showHidden: true`

current:

```
> Deno.inspect(new WeakSet([{}]), { showHidden: true })
"[Internal Formatting Error] TypeError: iter is not iterable\n" +
  "    at previewEntries (ext:deno_console/"... 287 more characters
```

this PR:

```
> Deno.inspect(new WeakSet([{}]), { showHidden: true })
"WeakSet { {} }"
```

### CODE REVIEW

**Comment by petamoriken** [comment]
@kt3k please take a look!

**Comment by kt3k** [comment]
Looks like this bug itself has already been fixed in https://github.com/denoland/deno/pull/21370 (`Deno.inspect(new Set([1, 2, 3]).values())` doesn't error anymore with 1.39.0)

But the addition of test cases looks useful. Can you split test addition part into a separate PR? @petamoriken 

Also the changes of type detections (from stringTag based to op based) are maybe useful as perf improvements. Can you split that part as `perf` PR?

**Comment by petamoriken** [comment]
@kt3k Updated description! I think the bug is still active, should I use a different PR?

**Comment by petamoriken** [comment]
It seems that there is also a bug with `Weak{Set, Map}`, so I will add a test.

**Comment by kt3k** [comment]
Confirmed the inspection of `Object.getPrototypeOf( new Set([1, 2, 3]).values() )` is fixed with this change. Nice work!

**Comment by kt3k** [comment]
> It seems that there is also a bug with Weak{Set, Map}, so I will add a test.

Thanks!

**Review by kt3k — APPROVED** [review]
LGTM

@bartlomieju @crowlKats Can you also take a look?

**Review by crowlKats — APPROVED** [review]
LGTM

**Pull request merged**
