### PR TITLE
Py3 compat

### PR DESCRIPTION
**Pull request by j4qfrost**
Makes build scripts compatible with python 3.

### CODE REVIEW

**Comment by nayeemrmn** [comment]
Huh, is this all we need for #2893 now?

**Comment by j4qfrost** [comment]
> Huh, is this all we need for #2893 now?

That's as far as I can tell. This works on OSX and Linux.

**Review by kitsonk — APPROVED** [review]
LGTM

**Comment by hayd** [comment]
Should [this](https://github.com/denoland/deno/blob/4c779b5e8ca427faf24c26443a8054004827d450/.github/workflows/ci.yml#L79) be python 3 for at least some of the build matrix?

**Comment by j4qfrost** [comment]
> Should [this](https://github.com/denoland/deno/blob/4c779b5e8ca427faf24c26443a8054004827d450/.github/workflows/ci.yml#L79) be python 3 for at least some of the build matrix?

That's a point I forgot to consider. Maybe this issue should be addressed in the context of sunsetting python 2. The intention with this PR was just to make the tests play nice with python 3. I have a weird feeling about changing up the python versions in just some places.

**Comment by hayd** [comment]
This may regress without using python3 in at least one test in the matrix (e.g. linux).

Note: Building with python3 works _provided_ you don't build V8. 😎

**Pull request merged**
