### PR TITLE
Revert "perf(core): preserve ops between snapshots (#18080)"

### PR DESCRIPTION
**Pull request by bartlomieju**
This reverts commit 4b6305f4f25fc76f974bbdcc9cdb139d5ab8f5f4.

### CODE REVIEW

**Review by crowlKats — APPROVED** [review]
LGTM

**Review by littledivy — APPROVED** [review]

**Comment by ry** [comment]
Why?

**Comment by bartlomieju** [comment]
Because it makes benchmarks fail on `main` branch.

**Comment by bartlomieju** [comment]
The bug seems to lie in `deno_ops` which mistakenly generates Fast Call function for return type of `i64` which is explicitly not supported by V8:
https://github.com/denoland/v8/blob/feca58c1c122f1bfc079054804f8b6fdf25676df/src/compiler/effect-control-linearizer.cc#L5776-L5809

**Pull request merged**
