### PR TITLE
fix(ext/node): http2session ready state

### LINKED ISSUE #25142: ClientHttp2Session reports Connecting, even after 'connect' event has been sent
Version: Deno 1.46.0

`ClientHttp2Session` property `connected` is `true`, even after the 'connect' event has been sent.  

image

Per node [http2session.connecting](https://nodejs.org/api/http2.html#http2sessionconnecting) it should be `false` after connect event

Looks like `this[kState].flags` needs to be set to `SESSION_FLAGS_READY` here:

https://github.com/denoland/deno/blob/3314a0ceb8f874986d5da9f36f683740bd813750/ext/node/polyfills/http2.ts#L516

### PR DESCRIPTION
**Pull request by caleblloyd**
Fixes #25142

### CODE REVIEW

**Review by satyarohith — APPROVED** [review]
LGTM - thanks for your contribution @caleblloyd!

**Comment by marvinhagemeister** [comment]
@satyarohith Should we add a test for this?

**Comment by satyarohith** [comment]
> @satyarohith Should we add a test for this?

Sure. I verified that the flag is set correctly but didn't ask for a test to avoid bloating the suite.

**Comment by marvinhagemeister** [comment]
We can never have enough tests. The more tests we have, the easier it will be to do refactorings in the future as it allows us to be more confident that we didn't break something accidentally in the process.

**Comment by caleblloyd** [comment]
If you can point me to the right file to write a test in, I can attempt to add one!

**Pull request merged**
