### PR TITLE
Drop assert!() from untrack_task()

### LINKED ISSUE #1756: untrack_task() is_some check occasionally fails
When running two `wrk` benchmarks one immediately after another, I almost always get
```
thread 'tokio-runtime-worker-0' panicked at 'assertion failed: t.is_some()', ../../src/resources.rs:205:7
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', src/libcore/result.rs:997:5
fatal runtime error: failed to initiate panic, error 5
Abort trap: 6
```
Basically, 
https://github.com/denoland/deno/blob/b2fb8261e700c75cfb9a626ae57bbd3098e08454/src/resources.rs#L199-L208
`assert!(t.is_some());` fails.

From my investigation,
https://github.com/denoland/deno/blob/b2fb8261e700c75cfb9a626ae57bbd3098e08454/src/tokio_util.rs#L64-L86
some connections immediately yields `Ok(futures::prelude::Async::Ready(t))` without ever yields `Ok(futures::prelude::Async::NotReady)`. Thus no task is waiting => assertion would fail.

This happens because in `eager_unix` `tcp_accept`,
https://github.com/denoland/deno/blob/b2fb8261e700c75cfb9a626ae57bbd3098e08454/src/eager_unix.rs#L68-L84
It is possible that an accept attempt would yield `WouldBlock` on first check, but would immediately success on the first `poll` once spawned in thread pool as a Future.

To address this issue, we need to remove the assertion from `untrack_task()`

### PR DESCRIPTION
**Pull request by kevinkassimo**
Closes #1756
See reasoning of this patch in #1756.

### CODE REVIEW

**Comment by kevinkassimo** [comment]
@ry I would assume inserting a ridiculously long sleep after checking WouldBlock and before spawning the task in the thread pool would make even a single HTTP request to fail the assert. (Cannot verify since not with my machine rn

**Comment by ry** [comment]
@kevinkassimo Ridiculously long sleep isn't doable in the tests. I'll hold off landing until you get a chance to check. Otherwise will land.

**Comment by kevinkassimo** [comment]
I think a black box test would be very hard due to lack of control of timing. A contrived Rust test in test_rs might work but would need explicit control of involving something similar to adding a sleep/channels... not so sure if that is considered adequate for demonstrating the problem...

**Comment by kevinkassimo** [comment]
Since this breaks tcp and I would be somewhat busy next few days, we might as well land it first to include in v0.3

**Pull request merged**
