### PR TITLE
fix(cli/fs): Resolve tilde in path

### LINKED ISSUE #5825: --allow-read whitelist does not work with tilde
Reproduction:
```
deno run --allow-read=~ https://deno.land/std/examples/cat.ts ~/.bashrc
```
Output:
```
error: Uncaught PermissionDenied: read access to "/home/chris/.bashrc", run again with the --allow-read flag
    at unwrapResponse ($deno$/ops/dispatch_json.ts:43:11)
    at Object.sendAsync ($deno$/ops/dispatch_json.ts:98:10)
    at async Object.open ($deno$/files.ts:37:15)
    at async https://deno.land/std/examples/cat.ts:4:16
```
Specifying an absolute path in `--allow-read` correctly outputs the file content.

This is on:
```
deno --version
deno 1.0.2
v8 8.4.300
typescript 3.9.2
```

### PR DESCRIPTION
**Pull request by tumile**
Resolve #5825 by adding checks for tilde in path in resolve_from_cwd @ cli/fs.rs.
- If the path is only `~`, return the home dir.
- If the path first dir is `~`, strip the prefix `~/` and join with home dir.  
- Added tests for these changes.

### CODE REVIEW

**Comment by ry** [comment]
Hi @tumile, thanks for the patch - this certainly fixes the problem. I have a little concern: typically programs do not expand tilde - this is a concern of the shell. Having Deno expand tilde might create some surprising behavior (tho I can't think of a specific example). I want to get a second opinion on this before landing it...

**Comment by SyrupThinker** [comment]
There are two I can think of.
- When a `~` directory exists in the `pwd`. Then it would resolve to home instead of that directory. The user would need disambiguate with `./~`.
- This patch does not implement `~user` expansion. That would in reverse try to use a directory in the `pwd` instead of the users home directory.

**Comment by tumile** [comment]
Thanks @SyrupThinker, agree with disambiguation for Windows.
What do you mean `~user` expansion? Directories starting with tilde will not be expanded, I have a test for it
```
let cwd = current_dir().unwrap();

assert_eq!(
  resolve_from_cwd(Path::new("~a/b")).unwrap(),
  cwd.join(Path::new("~a/b"))
);
```

**Comment by tumile** [comment]
Thanks @SyrupThinker. Agree that there is ambiguity with Windows. We can check for OS, but it even depends on the type of shell the script is executed from (bash vs cmd). I can't think of a way to account for that. Seems like the best thing is just let the shell expands the path, but for that we need to omit the "=".

**Comment by bartlomieju** [comment]
My two cents: we could verify that paths passed to `--allow-read` et al are either relative (`./`, `../`) or absolute (`/`) and refuse to take other paths. That way we can still levarage `resolve_from_cwd` without any changes and suggest to use shell expansion if user wants to start with `~`

**Comment by bartlomieju** [comment]
@tumile thank you for opening the PR and the effort, we really appreciate it. However I'm going to close this PR without merge - we've resisted to urge to expand globs in subcommands for some time now and I believe the same rules should apply to resolving tilde in permission flags - it should be left out to your shell. 

That said, my previous comment still holds true and I would gladly land a PR that validates paths passed to `--allow-*`.

**Comment by andykais** [comment]
just to be clear, is this something that Deno is marking as "wontfix", or is it just that a better way to solve this has not yet been written?

**Comment by bartlomieju** [comment]
@andykais yes, as of now this is "wontfix". It might change in the future, but we are rather opinionated on what CLI does and shell/glob expansion is currently not a thing we want to support.

**Comment by python-pk** [comment]
I am using `pwsh.exe` in the windows terminal which is essentially `PowerShell 7.5.1` .

With many common commands `~` is expanded without any problems to the home directory which is `C:/Users/USER`

I have a script in my home directory called fget.ts and I want to run it when I am in a different directory like `C:\Users\USER\Code\Cpp\+emacs`
In this case I get the below error.

```powershell

PS C:\Users\USER\Code\Cpp\+emacs> deno run --allow-net --allow-write ~/fget.ts https://ftp.fau.de/gnu/emacs/windows/emacs-30/emacs-30.1.zip
error: Module not found "file:///C:/Users/USER/Code/Cpp/+emacs/~/fget.ts".

```

I am in the process of making deno my main tool for scripting and that would be very important change.

PS:
I know that windows is not very popular in open source project, but please do not assume that most users would use `cmd.exe`. 

Thank you so much for the amazing tool you have created.

**Pull request closed without merging**
