### PR TITLE
feat: #2428 added ISSUE_TEMPLATE

### PR DESCRIPTION
**Pull request by d337**
As per discussed on issue #2428 this ISSUE_TEMPLATE.md can help the people while creating any of below:
1. bug report
2. feature request
3. documentation issue
4. question

### CODE REVIEW

**Comment by zekth** [comment]
A mention on the naming of the issue could be nice i think.

**Comment by deepchudasama** [comment]
> A mention on the naming of the issue could be nice i think.

Asking on issue_template or issue I crated?

**Comment by zekth** [comment]
> 
> 
> > A mention on the naming of the issue could be nice i think.
> 
> Asking on issue_template or issue I created?

On the issue template.

**Comment by deepchudasama** [comment]
@zekth that sounds good! Actually @ry asked for minimal template.

**Comment by kt3k** [comment]
@deepchudasama You need to run `./tools/format.py` to pass the CI checks.

**Comment by deepchudasama** [comment]
> @deepchudasama You need to run `./tools/format.py` to pass the CI checks.

@kt3k when I tried to run `tools/setup.py` I get error something like this
```
ERROR at //buildtools/third_party/libc++/BUILD.gn:32:5: Undefined identifier
if (libcxx_is_shared) {
    ^---------------
See //build/config/BUILD.gn:288:22: which caused the file to be included.
    public_deps += [ "//buildtools/third_party/libc++" ]
                     ^--------------------------------
```
I tried to find solution but haven't got one to resolve do you have any idea?

Thanks in advance

**Comment by kt3k** [comment]
@deepchudasama `libcxx_is_shared` is defined in a submodule https://github.com/denoland/chromium_build and it's connected at `//build`. Is your ./build directory initialized correctly? If it isn't, try the command `git submodule update --init`.

**Comment by deepchudasama** [comment]
> @deepchudasama `libcxx_is_shared` is defined in a submodule https://github.com/denoland/chromium_build and it's connected at `//build`. Is your ./build directory initialized correctly? If it isn't, try the command `git submodule update --init`.

Thanks man! It's working perfectly. I don't why but actually I manually cloned sub-modules :smiley:

**Comment by d337** [comment]
Closing because having some issues

**Pull request closed without merging**
