### PR TITLE
fix(ext/websocket): restore op_ws_send_ping

### PR DESCRIPTION
**Pull request by bartlomieju**
This op doesn't exist anymore and is pings are handled automatically by
the Rust crate.

### CODE REVIEW

**Review by ry — COMMENTED** [review]
Test?

**Comment by bartlomieju** [comment]
> Test?

Fixed and reenabled existing test.

**Review by ry — APPROVED** [review]
LGTM

**Review by littledivy — APPROVED** [review]
LGTM, if the test passes. It might hang as described in this issue: https://github.com/denoland/deno/issues/14283

**Pull request merged**
