### PR TITLE
fix(node/http(s)): export globalAgent

### LINKED ISSUE #18312: node: http(s).globalAgent is missing
When I quote npm inclusion as below:
var useSSL = endpoint.protocol === 'https:';
     var http = require('https');
     if (httpOptions.maxSockets) {
       http.globalAgent.maxSockets = httpOptions.maxSockets;
     } else {
       http.globalAgent.maxSockets = 300;
     }

Show: Cannot set properties of undefined (setting 'maxSockets')

I have seen: https://deno.land/std@0.166.0/node/https.ts?source
Legal definition: export const globalAgent = undefined;

Not this: export const globalAgent = new Agent();

### LINKED ISSUE #21080: https.globalAgent exists on default export but not on module namespace
```js
jcbhmr@PIG-2016:~$ deno
Deno 1.38.0
exit using ctrl+d, ctrl+c, or close()
REPL is running with all permissions allowed.
To specify permissions, run `deno repl` with allow flags.
> let m = await import("node:https")
undefined
> Object.keys(m)
[ "Agent", "Server", "createServer", "default", "get", "request" ]
> Object.keys(m.default)
[ "Agent", "Server", "createServer", "get", "globalAgent", "request" ]
> m.globalAgent
undefined
>
```

```sh
jcbhmr@PIG-2016:~$ node
Welcome to Node.js v20.8.0.
Type ".help" for more information.
> let m = await import("node:https")
undefined
> Object.keys(m)
[
  'Agent',
  'Server',
  'createServer',
  'default',
  'get',
  'globalAgent',
  'request'
]
> Object.keys(m.default)
[ 'Agent', 'globalAgent', 'Server', 'createServer', 'get', 'request' ]
>
```

```
Node.js https module namespace has: Agent, Server, createServer, get, globalAgent, request
Deno https module namespace has   : Agent, Server, createServer, get,              request
Node.js https default export has  : Agent, Server, createServer, get, globalAgent, request
Deno https default export has     : Agent, Server, createServer, get, globalAgent, request
```

in summary: pls export the globalAgent on the main module namespace thx

### PR DESCRIPTION
**Pull request by jcbhmr**
fix #21080 
fix #18312

### CODE REVIEW

**Review by littledivy — APPROVED** [review]
LGTM, thanks

**Comment by littledivy** [comment]
@jcbhmr  You can add one in `cli/tests/unit_node/http_test.ts`

**Comment by jcbhmr** [comment]
added tests. anything else i need to do?

**Comment by littledivy** [comment]
@jcbhmr CI is failing on format: https://github.com/denoland/deno/actions/runs/6800677587/job/18510257746?pr=21081

Can you run `./tools/format.js`

**Pull request merged**
