### PR TITLE
fix(runtime/js/spawn): Pass stdio options for spawn() and spawnSync()

### PR DESCRIPTION
**Pull request by nayeemrmn**

### CODE REVIEW

**Comment by crowlKats** [comment]
This is intentional, but after working on porting all `Deno.run` usages to the new subprocess API, I agree we should allow it

**Comment by nayeemrmn** [comment]
Oh, I assumed it was unintentional because the types allowed it. I expected this to work as it seems like a reasonable use of the shorthand:
```ts
const { stdout } = await Deno.spawn("cat", { stdin: "inherit" });
```

**Comment by crowlKats** [comment]
@nayeemrmn could you also update the tsdoc on the typings? There is a line that states that stdin options are ignored on spawn/spawnSync

**Comment by crowlKats** [comment]
One question remains: what happens when `stdin` is set to `"piped`"? that will cause issues

**Comment by bartlomieju** [comment]
> One question remains: what happens when `stdin` is set to `"piped`"? that will cause issues

I think it makes no sense to have "piped" setting in `Deno.spawnSync` API as there would be no way to actually write something to stdin, but it could be used in async version.

**Comment by nayeemrmn** [comment]
> I think it makes no sense to have "piped" setting in `Deno.spawnSync` API as there would be no way to actually write something to stdin, but it could be used in async version.

But there's no handle returned on the stdin. We should just map `"piped"` to `"null"` there and note it in the docs.

**Comment by crowlKats** [comment]
> I think it makes no sense to have "piped" setting in `Deno.spawnSync` API as there would be no way to actually write something to stdin, but it could be used in async version.

yes, but what would be the beviour? right now, as the PR is, if someone sets stdin to `"piped"`, a stdin resource will be added that has to be manually closed thorugh `spawnChild`, however the user wont be able to close that resource

**Comment by bartlomieju** [comment]
Ah this is good point. In such case Nayeem's suggestion seems reasonable. IIRC Leo wanted to add `input` option as well that would be passed to stdin and then close it.

**Comment by nayeemrmn** [comment]
Yeah, I think in the future we should have:
```ts
export interface SpawnOptions {
  stdin?: "piped" | "inherit" | "null" | Uint8Array;
}
```

**Comment by crowlKats** [comment]
Could you add a test for disallowed stdin?

**Review by crowlKats — APPROVED** [review]
LGTM, thanks

**Comment by littledivy** [comment]
I recently hit this for node:child_process. Piped stdio absolutely makes sense, it means the parent's stdio is piped to the child (not the other way around). 

Removing the stdin check in `outputSync` fixes #23051

**Pull request merged**
