### PR TITLE
WIP: handle worker error

### PR DESCRIPTION
**Pull request by bartlomieju**
Work towards addressing #2444

### CODE REVIEW

**Comment by bartlomieju** [comment]
I got error handling in worker's event handler more-or-less figured out and should be able to handle that without a problem, but please consider example below.

Example:
```ts
// main.js
let worker = new Worker("./worker.js");
worker.postMessage("hello");

worker.onerror = (e) => {
    console.log("uncaught error from worker:", e);
}

setTimeout(() => {
    worker.postMessage("msg after timeout")
}, 2000);
```
```ts
onmessage = (e) => {
  console.log("worker recieved message", e.data);
  new DoesNotExist();
  console.log("end worker");
}

setTimeout(() => {
  console.log("worker after timeout!");
}, 5000);

console.log("hello world");
throw new Error("foobar!")
```

Output in Chrome's console:
```
hello world
uncaught error from worker:
Uncaught Error: foobar!
    at worker.js:10
worker recieved message hello
uncaught error from worker:
Uncaught ReferenceError: DoesNotExist is not defined
    at onmessage (worker.js:5)
worker recieved message msg after timeout
uncaught error from worker:
Uncaught ReferenceError: DoesNotExist is not defined
    at onmessage (worker.js:5)
worker after timeout!
```

We can see that in Chrome's implementation even after error is thrown in worker's main code (`throw new Error("foobar!");`) worker's event loop continues to work.

I'm not yet sure how we'll be to do that in Deno; firstly any error in workers main code will cause `Uncaught WorkerInitFailed: worker init failed`. The same thing applies if error would be thrown in timeout. Basically Deno will return error from `Isolate.last_exception()`. 

Question is: can we still run code on `Isolate` even after `Isolate.last_exception()` returns error?

CC @ry @afinch7

**Comment by ry** [comment]
> Question is: can we still run code on Isolate even after Isolate.last_exception() returns error?

Yes, I think it should work. But the question is do we want to match browser behavior in this case? This is not what I would expect to have happened...

**Comment by bartlomieju** [comment]
Neither do I - it's also in contrary to "always dies on uncaught errors", but I had to take some reference.

Let me finish this patch and we'll get back to it.

**Comment by bartlomieju** [comment]
Reference: https://html.spec.whatwg.org/multipage/workers.html#runtime-script-errors-2

**Comment by ry** [comment]
@bartlomieju Are you still working on this? If not please close - we'll pick it up another time. If so, rebase.

**Comment by bartlomieju** [comment]
Yes, it's still in my backlog. I'll revisit soon.

**Comment by bartlomieju** [comment]
Closing now, I need to rethink it, let's revisit it later.

**Pull request closed without merging**
