### PR TITLE
Migrate from dprint-ignore to deno-fmt-ignore

### PR DESCRIPTION
**Pull request by kitsonk**
The latest version of `dprint` supports a custom ignore string, which @dsherret set to `deno-fmt-ignore`, so for `deno fmt` we need to migrate to `// deno-fmt-ignore`.

I don't know if there is any docs we need to update or not...

### CODE REVIEW

**Comment by bartlomieju** [comment]
When we're gonna switch to `dprint` for internal formatting we will probably use `dprint-ignore` instead of `deno-fmt-ignore` - after all we'll be using standalone `dprint` CLI instead of `deno fmt`.

**Comment by dsherret** [comment]
@bartlomieju most likely your config will have `”deno”: true` which causes it to use `deno-fmt-ignore` so I think you’ll end having it almost exactly like deno fmt even though the dprint cli is running it.

**Comment by bartlomieju** [comment]
> @bartlomieju most likely your config will have `”deno”: true` which causes it to use `deno-fmt-ignore` so I think you’ll end having it almost exactly like deno fmt even though the dprint cli is running it.

Thanks for explanation @dsherret 👍 then I agree we should land it

**Comment by kitsonk** [comment]
@bartlomieju all green now/again

**Pull request merged**
