### PR TITLE
[WIP] setup.py : adding path to third party

### PR DESCRIPTION
**Pull request by zekth**
Fixing the setup.py : https://github.com/denoland/deno/issues/1898

### CODE REVIEW

**Comment by ry** [comment]
Does this fix the problem you were having before?

**Comment by zekth** [comment]
This fixes this error:
```
 GetWinSDKDir
    import vs_toolchain
ImportError: No module named vs_toolchain
```

The other one concerning the env variable `GYP_MSVS_VERSION=2017` is more related to environment. I have to figure out what changes this value (maybe an old version of node). A note in the manual could be a good addition. I also encounter an error at the build and i've already discussed with @afinch7 on this subject. But it may also be related to my environment and not the script itself. Still investigating.

**Comment by ry** [comment]
Can you move this addition to the top of tools/third_party.py and add a comment
```
# Needed for vs_toolchain in v8/tools/clang/scripts/update.py
``` 
Thank you

**Comment by zekth** [comment]
After a dry start, seems to be buggy too. I'll fix this.

**Comment by zekth** [comment]
Closing totally wrong way to solve the problem

**Pull request closed without merging**
