### PR TITLE
fix(ext/node): remove unnecessary and incorrect type priority_t

### PR DESCRIPTION
**Pull request by jirutka**
`getpriority` and `setpriority` on musl libc accepts `int` / `c_int` / `i32` as the first argument, not `u32`.

Since the `PRIO_PROCESS` constant is imported from the same crate (libc) as the `getpriority` and `setpriority` functions, this type cast seems to be completely unnecessary here.

It was introduced in aa8078b6888ee4d55ef348e336e076676dffc25f by @crowlKats.

Relevant sources:

- https://github.com/rust-lang/libc/blob/835661543db1ec42a6d9a809d69c3c5b5b978b81/src/unix/linux_like/linux/musl/mod.rs#L739-L740
- https://git.musl-libc.org/cgit/musl/tree/src/misc/setpriority.c
- https://git.musl-libc.org/cgit/musl/tree/src/misc/getpriority.c

### CODE REVIEW

**Comment by bartlomieju** [comment]
Hey @jirutka and sorry for a slow response. I think someone opened another PR (https://github.com/denoland/deno/pull/20286) that addressed the same issue already? It's a bummer because you were first to open yours.

**Comment by jirutka** [comment]
No, it’s not exactly the same issue and the resolution is different, that PR doesn’t fix the bug on musl libc

**Comment by bartlomieju** [comment]
@aapoalas could you take a look at this PR?

**Review by aapoalas — APPROVED** [review]
Looks good to me: I checked that at least all the most common freebsd, openbsd, musl and linux-gnu platform libc packages indeed match setpriority and PRIO_PROCESS types and thus as said, the type assert should be entirely unnecessary.

Thank you for the nice fix!

**Pull request merged**
