### PR TITLE
fix(ext/node): better inspector support

### PR DESCRIPTION
**Pull request by devsnek**
implement local inspector

future changes:
- wire up InspectorServer to enable open/close/url
- wire up connectToMainThread

Fixes https://github.com/denoland/deno/issues/25004

### CODE REVIEW

**Comment by lucacasonato** [comment]
What should the permissions be to access inspector?

**Comment by bartlomieju** [comment]
> What should the permissions be to access inspector?

That's a good question that I was wondering when I first started working on this. Do we need to add permissions at all?

**Comment by bartlomieju** [comment]
@lucacasonato I spoke with @devsnek offline and we are thinking that we could piggy-back off of `--allow-sys=inspector` so that we don't have to add another `--allow-*` flag.

**Comment by lucacasonato** [comment]
How confident are we that inspector does not imply `--allow-run`?

**Comment by devsnek** [comment]
@lucacasonato I spoke to someone on the devtools team and they said it was ok.

**Pull request merged**
