### PR TITLE
fix(ext/webgpu): GPUDevice.features should be SetLike.

### LINKED ISSUE #15702: [deno_webgpu] WebGPU GPUSupportedFeatures object doesn't include `has` method
Code:
```
const adapter = await navigator.gpu.requestAdapter();
const device = await adapter?.requestDevice();

console.log(device.features.has('timestamp-query'));
```
Output:
```
error: Uncaught (in promise) TypeError: device.features.has is not a function
console.log(device.features.has('timestamp-query'));
```
Expected output:
True or False

Due to  [WebGPU spec](https://www.w3.org/TR/webgpu/#gpu-supportedfeatures) and webidl spec, `device.features` is a [setlike](https://webidl.spec.whatwg.org/#dfn-set-entries) Object and should includes `has` method, but there is not.

### PR DESCRIPTION
**Pull request by vicary**
Fixes #15702.

### CODE REVIEW

**Review by vicary — COMMENTED** [review]
-

**Comment by vicary** [comment]
Sorry to ping you again @crowlKats, just want to know if there is anything I can do to move this forward.

**Review by crowlKats — CHANGES_REQUESTED** [review]
The typings in cli/dts/lib.deno_webgpu.d.ts need to be updated as well

**Comment by vicary** [comment]
Updated!

**Review by crowlKats — APPROVED** [review]
LGTM, thanks

**Comment by vicary** [comment]
Just to be safe I did a whole project grep, should I update these lines too?

https://github.com/denoland/deno/blob/1ebbe232da1e81ad75808a9158203830f6b9d042/ext/webgpu/src/01_webgpu.js#L746-L747

https://github.com/denoland/deno/blob/1ebbe232da1e81ad75808a9158203830f6b9d042/ext/webgpu/src/01_webgpu.js#L755-L758

**Comment by crowlKats** [comment]
Oh yea that would be helpful

**Comment by vicary** [comment]
Rebased upstream along with the change.

**Comment by vicary** [comment]
Hm I don't quite understand the failing tests, how should I fix it?

**Comment by crowlKats** [comment]
I took care of it, was just flaky CI

**Pull request merged**
