### PR TITLE
feat(cli/jupyter): Support Out

### PR DESCRIPTION
**Pull request by mmastrac**
Implements `Out`, but not `In`.

~This should fix https://github.com/denoland/deno/issues/20528~

### CODE REVIEW

**Comment by rgbkrk** [comment]
Still occurring with this branch.

image

**Review by bartlomieju — APPROVED** [review]
LGTM, should we provide a maximum number of saved output cells? That could potentially consume quite a lot of memory.

**Comment by mmastrac** [comment]
@rgbkrk Is there a max limit to how many output cells are saved in ipython?

**Comment by rgbkrk** [comment]
It is an unbounded list in IPython.

I agree with @bartlomieju that it has potential to OOM a runtime. We actually see this in production (in the Python kernel) if people display copies of large dataframes. If it's the same object or a view on an object it's not _terrible_ most of the time. Workflow wise, people are either doing small local stuff or running the kernel in a container.

**Comment by mmastrac** [comment]
I think we should avoid merging this for now -- perhaps we can add some sort of gc pressure callback first.

**Pull request closed without merging**
