### PR TITLE
feat(install): Add support for --importmap

### LINKED ISSUE #3929: `deno install` does not support import maps
The `deno install` command should support the `--importmap` flag so that you would be able to write:
```
deno install --importmap import_map.json asd asd.ts
```
without it complaining about `Found argument '--importmap' which wasn't expected, or isn't valid in this context`.

### PR DESCRIPTION
**Pull request by ntedgi**
adding  to deno install command support to the --importmap flag so that you would be able to write:

`deno install --importmap import_map.json asd asd.ts`

without it complaining about Found argument '--importmap' which wasn't expected, or isn't valid in this context.

Closes #3929

### CODE REVIEW

**Review by nayeemrmn — CHANGES_REQUESTED** [review]
It would also have to save the import map near the installed script and include the import map in the written command.

**Comment by ntedgi** [comment]
@nayeemrmn thanks a lot it's my first PR can you please suggest another command with an example how 
the save is implemented?

**Comment by nayeemrmn** [comment]
@ntedgi Sorry, that kind of thing isn't done anywhere yet. We need to do the same with `--config` as well. This PR might help: https://github.com/denoland/deno/pull/5276/files#diff-46c2c9ed8c9b0fccbbca630c94cccdf6R85.

**Comment by ntedgi** [comment]
@nayeemrmn  thanks 
Do you think the scoop of this task still should be label as "good first issue"?
this task is still good for a first-timer?

**Comment by nayeemrmn** [comment]
@ntedgi It's not as trivial as it was likely assumed to be but it still doesn't involve anything complex in the deeper codebase. It's up to you.

**Comment by lucacasonato** [comment]
@ntedgi You might want to take a look at https://github.com/denoland/deno/pull/6204/files. It implements this, but for `--config`. The implementation for import map should be pretty similar.

**Comment by ntedgi** [comment]
thanks a lot to both of you @lucacasonato @nayeemrmn 👍👍
this is the best experience I ever add  in contributing to a project 
I continue working on it

**Comment by nayeemrmn** [comment]
Oops, I was testing it with the flags in the wrong place! Yes it's already supported for `--config`.

**Comment by ntedgi** [comment]
@nayeemrmn @lucacasonato 
ok so just  to make sure I understand the rest of the task goals 

- save the import map JSON file near the location of the installed script 

- include the import map in the written  install command

**Comment by ntedgi** [comment]
@nayeemrmn @lucacasonato 
I solve this issue by making the same changes for the import map  as describe [here](https://github.com/denoland/deno/pull/6204/files ) for the config file  
after merging head commit from deno I see the changes made at  that branch removed

the future I currently working on still needed? 😬

**Comment by nayeemrmn** [comment]
@ntedgi Will you continue this PR? It seems like the main changes got removed in your merge.

**Comment by ntedgi** [comment]
@nayeemrmn 
I solve this issue by making the same changes for the import map as describe here for the config file
after merging head commit from deno I see the changes made at that branch removed

the future I currently working on still needed? grimacing

save the import map JSON file near the location of the installed script

include the import map in the written install comm

**Comment by nayeemrmn** [comment]
@ntedgi I believe the changes are still needed, and the deletion was a merge error.

**Comment by XGHeaven** [comment]
Any update here?

**Comment by ntedgi** [comment]
Still need an improvement of the definition of done? Can you please elaborate?

**Comment by nayeemrmn** [comment]
I'm addressing this as part of #7601. I refactored the code that does this for tsconfig making it a really simple addition.

**Comment by ntedgi** [comment]
Ok thanks @nayeemrmn

**Comment by bartlomieju** [comment]
Thanks for contribution @ntedgi! I'm gonna close this one without merge as it's already part of https://github.com/denoland/deno/pull/7601

**Pull request closed without merging**
