### PR TITLE
fix(ext/kv): increment versionstamp by random number

### LINKED ISSUE #19875: KV: increment versionstamps monotonically with random amounts
Right now, every change increments the versionstamp by one. We should instead update it with an amount between 1-10.

This is because there is no guarantee that versionstamps must be incremented monotonically by 1.

### PR DESCRIPTION
**Pull request by lino-levan**
Closes #19875

### CODE REVIEW

**Comment by lino-levan** [comment]
Updating tests to this is going to be really painful.

**Review by lucacasonato — COMMENTED** [review]
@lino-levan The tests can be changed to `assert(oldVersionstamp < newVersionstamp)`. We don't have to assert the exact versionstamp value.

**Comment by lino-levan** [comment]
> @lino-levan The tests can be changed to assert(oldVersionstamp < newVersionstamp). We don't have to assert the exact versionstamp value.

That was what I was planning on doing, will try to get around to it today.

**Comment by bartlomieju** [comment]
@lino-levan are you still interested in getting this landed? If so you will need to open a new PR to https://github.com/denoland/denokv. I'm gonna close this one for now.

**Comment by lino-levan** [comment]
I will get this landed, bit behind on work. I will open a PR on the new repo.

**Pull request closed without merging**
