### PR TITLE
perf(core): Deno.core.unsafeBuffer

### PR DESCRIPTION
**Pull request by AaronO**
To create a non bzero'd ArrayBuffer of a given size. Useful when creating a buffer for IO that will be immediately written to

### CODE REVIEW

**Comment by lucacasonato** [comment]
This can be used to leak heap contents into the isolate. As such I am not in favour. If we want to do I/O reads using non zeroed buffers then create an op that takes a length to read and does the allocation and reading inside of that op. You can then return the clean buffer to the runtime.

**Comment by ry** [comment]
I agree with Luca. We can just make `Deno.core.opSync("op_fake_read")` return the allocated buf - then it's (probably) even more efficient one opcall instead of two

**Review by lucacasonato — COMMENTED** [review]
Also, just generally: calling some unsafe code in an op or binding with a safety comment "caveat emptor" (caller beware), but then just directly exposing that to userland is just really very very questionable.

**Comment by AaronO** [comment]
Will replace with an `op_readn`

**Pull request closed without merging**
