### PR TITLE
Rename BadFileDescriptor

### PR DESCRIPTION
**Pull request by J2P**
* Rename `BadFileDescriptor` to `BadResource`
* Rename `fd` to `rid`

### CODE REVIEW

**Comment by ry** [comment]
There are many places in js/* where we use "fd" instead of "rid" - for example in js/files.ts. Could you also rename those?

**Comment by J2P** [comment]
@ry 
I will change "fd" to "rid" Is that right?
Should I add a commit to this PR?

**Comment by ry** [comment]
@J2P yes please.

**Comment by J2P** [comment]
@ry Added.

**Pull request merged**
