### PR TITLE
fix(cli/buffer): allow Buffer to store MAX_SIZE bytes (ALT)

### LINKED ISSUE #6543: Buffer fails to store up to MAX_SIZE bytes
Take the following snippet, where I'm trying to read `MAX_SIZE` from a `Reader`

https://github.com/denoland/deno/blob/2da084058397efd6f517ba98c9882760ec0a7bd6/cli/js/buffer.ts#L15

```javascript
const MAX_SIZE = 2 ** 32 - 2;
const capacities = [MAX_SIZE, MAX_SIZE - 1, MAX_SIZE - 512];
for (const capacity of capacities) {
    const reader = new Deno.Buffer(new ArrayBuffer(capacity));
    const buf = new Deno.Buffer();
    buf.readFromSync(reader);
}
```

```
error: Uncaught Error: The buffer cannot be grown beyond the maximum size.
    at Buffer.#grow ($deno$/buffer.ts:137:13)
    at Buffer.readFromSync ($deno$/buffer.ts:176:27)
```

### PR DESCRIPTION
**Pull request by marcosc90**
fixes #6543. 

This is an alternative implementation of #6568

### CODE REVIEW

**Comment by ry** [comment]
@marcosc90 which PR do you prefer?

**Comment by marcosc90** [comment]
> @marcosc90 which PR do you prefer?

I prefer #6568, it is a cleaner implementation IMHO.

I'd like to run some benchmarks. This one (#6570) might be a bit faster since we avoid an extra `buf.set`, it reads directly into the buffer. The exception is when it grows the buffer when it's not needed, that happens when there are less than MIN_READ bytes remaining.

**Comment by marcosc90** [comment]
@ry I have a version that's a mixed between the two, that seems to be faster & pretty clean. I'm doing some tests and I'll push it shortly.

**Comment by marcosc90** [comment]
@ry This is ready for review.

**Pull request merged**
