### PR TITLE
chore: upgrade Rust to 1.54.0

### PR DESCRIPTION
**Pull request by magurotuna**
Upgrades Rust to 1.54.0 and applys clippy's fixes.

### CODE REVIEW

**Comment by kitsonk** [comment]
@kt3k I don't know if you know, but it seems that somehow the upgrade to Rust 1.54 causes us to run out of disk space on CI on Windows. I suspect it is something to do with our build caches, but I don't know enough to "fix" it.

**Comment by kt3k** [comment]
'Post Clone repository' step says `There is not enough space on the disk. : 'D:\a\_temp\_runner_file_commands\set_env_b44b1bfe-1ffe-40fd-8e4d-37c9df5dd52d'`, but I think that step only does clean-ups. So I doubt we actually run out of disk space..

'Test release' step shows `Error: thread 'basic' panicked at 'assertion failed: build_plugin_output.status.success()', test_plugin\tests\integration_tests.rs:21:3`. I guess that one would be the actual problem we need to address

I'll rerun CI anyway

**Comment by kitsonk** [comment]
@kt3k yeah, I re-ran CI already and it continuously fails with the same error... 😕

**Comment by bartlomieju** [comment]
> @kt3k I don't know if you know, but it seems that somehow the upgrade to Rust 1.54 causes us to run out of disk space on CI on Windows. I suspect it is something to do with our build caches, but I don't know enough to "fix" it.

Changing cache keys here: 
https://github.com/denoland/deno/blob/c909faf9e6cd2964398da7c0852d0229cdd1a22b/.github/workflows/ci.yml#L248-L287
should help

**Review by bartlomieju — APPROVED** [review]
LGTM, thank you @magurotuna

**Pull request merged**
