### PR TITLE
Use BTreeMap for deterministic key order

### PR DESCRIPTION
**Pull request by KSXGitHub**
Fix https://github.com/denoland/deno/issues/4790

**Testing Needed:** I want a way to test not only parsed content of lock files, but also its key order. I don't know how, so I would appreciate some help.

### CODE REVIEW

**Comment by bartlomieju** [comment]
We already have `IndexMap` as a dependency used in import maps exactly for the purpose to preserve insertion order. Maybe use that one? Another approach would be to sort the hashmap and construct json manually.

**Comment by KSXGitHub** [comment]
> We already have `IndexMap` as a dependency used in import maps exactly for the purpose to preserve insertion order. Maybe use that one?

First, we must have a test, then we may know what approach gives us desired result.

> Another approach would be to sort the hashmap and construct json manually.

That would be less efficient (performance wise) and more convoluted (readability wise) that just use BTreeMap. I don't think there is a reason for that.

**Comment by bartlomieju** [comment]
@KSXGitHub PTAL: https://stackoverflow.com/questions/42723065/how-to-sort-hashmap-keys-when-serializing-with-serde - very concise example how to ensure ordering during serialization using BTreeMap. 

As for test case, you can use one of existing test files that has imports (look in `cli/tests/`) to write an integration test. Take a look at `bundle_exports` in `cli/tests/integration_tests.rs` - it's a test that uses temporary directory for a "fresh" environment which would be perfect in this situation - run a test with `--lock` and `--lock-write` flags and assert that content of output file is alphabetically sorted (hardcoded `assert_eq!` compare is fine).

Let me know if you need more info 👍

**Comment by KSXGitHub** [comment]
> PTAL: https://stackoverflow.com/questions/42723065/how-to-sort-hashmap-keys-when-serializing-with-serde - very concise example how to ensure ordering during serialization using BTreeMap.

The example in the link you've given is very convoluted compared to "just use BTreeMap directly". It was to answer "how to guarantee key order **without changing data structure**" by using a custom function to convert/clone a HashMap into a BTreeMap, which is very inefficient. Is there any reason to avoid change data structure?

**Comment by bartlomieju** [comment]
Thanks @KSXGitHub but I'm gonna close this PR without merge. Lock file requires more refactors (#5231) and deterministic output will be one of them.

**Pull request closed without merging**
