### PR TITLE
fix(core): Have custom errors be created in the right realm

### PR DESCRIPTION
**Pull request by andreubotella**
Although PR #16366 did not fully revert `deno_core`'s support for realms, since `JsRealm` still existed after that, it did remove the `ContextState` struct, originally introduced in #14734. This change made `js_build_custom_error_cb`, among other properties, a per-runtime callback, rather than per-realm, which cause a bug where errors thrown from an op would always be constructed in the main realm, rather than in the current one.

This change adds back `ContextState` to fix this bug, adds back the `known_realms` field of `JsRuntimeState` (needed to be able to drop the callback when snapshotting), and also relands #14750, which adds the `js_realm_sync_ops` test for this bug that was removed in #16366.

### CODE REVIEW

**Comment by bartlomieju** [comment]
@andreubotella please rebase

**Review by bartlomieju — COMMENTED** [review]
@littledivy are you fine with these changes?

**Review by littledivy — APPROVED** [review]
LGTM.

@bartlomieju Yes, it isn't in the hot path. Let's watch for regressions anyways

**Review by bartlomieju — APPROVED** [review]
LGTM, thanks Andreu

**Pull request merged**
