### PR TITLE
Support top-level-await in TypeScript

### PR DESCRIPTION
**Pull request by ry**
Fixes https://github.com/denoland/deno/issues/471

After this we should clean up the documentation...

### CODE REVIEW

**Comment by kitsonk** [comment]
TLA for TypeScript is scheduled for 3.7, planned for Nov 7th.

Refs: microsoft/TypeScript#33352 and microsoft/TypeScript#25988

**Comment by ry** [comment]
> I am expecting many subtle bugs in our top level await support. E.g. certain type checks that typescript will get wrong, module initialization in the wrong order / racy, etc.

I wouldn't be surprised either - but some preliminary checks I did with TLA + type errors did report the correct error. But this is just a bandaid until TypeScript properly parses TLA.

**Comment by hayd** [comment]
Is top level for-await a distinct typescript/V8 issue?

**Comment by ry** [comment]
@hayd yes - it’s not yet supported in v8

**Pull request merged**
