### PR TITLE
Use discord instead of gitter

### PR DESCRIPTION
**Pull request by ry**

### CODE REVIEW

**Comment by dstaley** [comment]
@ry As someone who is in the middle of [moving to Gitter](https://github.com/Kinto/kinto/issues/2440), I'd love to hear a bit about what prompted the switch to Discord. Also, did you consider other options?

**Comment by ry** [comment]
It’s buggy and not being updated.

**Comment by chuckxD** [comment]
@ry Discord is great although the learning curve for implementing some of channel configuration, moderation, user permission management can be quite steep depending on how you to administer/interact with contributors and anyone else in between. A good Discord setup can help you min/max the signal-to-noise you might have been getting in Gitter. I'd lean one of your close buds and maybe some pre-existing/larger Discord dev groups to help you maybe bootstrap some good guidelines, channel rules, and moderation settings to create an effective *you* want to engage with  the rest of the deno community. ♥

**Comment by jakeg** [comment]
I could see the old Gitter chat just by clicking a look from the Deno home page without having to log in. Now when I click the link I get told that ry "invited me" to join the chat, and clicking that takes me to download the app from the Android Play store. This is a regression unfortunately. Is it possible to view Discord chats without logging in or downloading an app?

**Comment by crowlKats** [comment]
@jakeg no you need to be logged in to use discord. Though if you are on the discord website on desktop and click "Open Discord in your browser" you can interact with discord (and so join servers etc) without doing an actual registration.
The control you have in discord as a server moderator is quite nice to have, especially once you add bots etc, so i think it isnt a regression but progression. There is to remember that discord was intended for gaming, and not for coding (though does have code markdown), so stuff like viewing the chat channels from a website with an embed is not a thing as there would be little to no point. The only embed discord provides is to view the voice channels and who is in them, but nothing more.

**Comment by jakeg** [comment]
@crowlkats oh, don't get me wrong, I'm sure there are lots of benefits. I'm just saying that the lack of this particular feature (web based viewing without logging in) is an unfortunate regression. Seeing as that was the only way I was using it before, it's a shame for me, and I'm sure others too.

**Comment by Picoseconds** [comment]
@jakeg I believe the intention is for people to already use Discord for other purposes, and so be able to view. Discord is not developer oriented, in fact, you must be invited to view messages. This is unfortunately just the style of Discord.

**Comment by T3NED** [comment]
Created a discord server for Deno's community: https://discord.gghJMjY7J

**Comment by lucacasonato** [comment]
Deno already has a discord server: https://discord.gg/deno :-)

**Comment by T3NED** [comment]
> Deno already has a discord server: https://discord.gg/deno :-)

Damn checked earlier and couldn't find one

**Pull request merged**
