### PR TITLE
docs(JsRealm.execute_script): Adding info and doc test about the isolate parameter

### PR DESCRIPTION
**Pull request by Vagelis-Prokopiou**

### CODE REVIEW

**Comment by andreubotella** [comment]
This restriction applies to every `&mut v8::Isolate` argument in `JsRealm` methods, so either all methods with such an argument should be updated to include this piece of documentation, or it should be moved to the `JsRealm` struct docs.

**Comment by Vagelis-Prokopiou** [comment]
Thanks. I will move it to the struct.

**Comment by Vagelis-Prokopiou** [comment]
@andreubotella the necessary updates are applied.
Waiting on you feedback. Thanks again for the guidance.

**Comment by Vagelis-Prokopiou** [comment]
@andreubotella just a reminder for this PR.
It should be quite easy to get this merged and get it over with :-)

**Review by aapoalas — APPROVED** [review]
LGTM

**Comment by Vagelis-Prokopiou** [comment]
@aapoalas this is failing in an unrelated to the changes point.
I suppose this is coming from the main branch itself.
How shall we handle it?

**Comment by aapoalas** [comment]
> @aapoalas this is failing in an unrelated to the changes point. I suppose this is coming from the main branch itself. How shall we handle it?

By rechecking ;)

**Pull request merged**
