### PR TITLE
fix(cli): fetch works in Jupyter

### LINKED ISSUE #20534: [jupyter kernel] fetch requests show `BadResource: Bad resource ID`
Hello deno crew! :wave:

I've really enjoyed testing out deno with the new `jupyter` kernel subcommand with @rgbkrk, but I'm a bit stumped on one thing: after cloning `main` (as recent as e995ba66cd7400e0c87af6e530e74a6aa7c7c934), I'm seeing consistent odd errors with fetch requests: 
image

I've tried running the following on WSL with Ubuntu 22.04:
```bash
deno on  main [?] via 🦀 v1.72.0
❯ deno jupyter --unstable --install
[InstallKernelSpec] Removing existing kernelspec in <home>/.local/share/jupyter/kernels/deno
[InstallKernelSpec] Installed kernelspec deno in <home>/.local/share/jupyter/kernels/deno
✅ Deno kernelspec installed successfully.
```
```bash
deno on  main [?] via 🦀 v1.72.0
❯ cargo run -- jupyter --unstable --install
   Compiling deno_runtime v0.126.0 (<home>/dev/deno/runtime)
   Compiling deno v1.36.4 (<home>/dev/deno/cli)
    Finished dev [unoptimized + debuginfo] target(s) in 2m 10s
     Running `target/debug/deno jupyter --unstable --install`
[InstallKernelSpec] Removing existing kernelspec in <home>/.local/share/jupyter/kernels/deno
[InstallKernelSpec] Installed kernelspec deno in <home>/.local/share/jupyter/kernels/deno
✅ Deno kernelspec installed successfully.
```
Then, followed by `jupyter notebook` with Jupyter Notebook 7.0.3 (also seen with Jupyter Lab 4.0.6)
image

Re-running the cell, executing a "Run All" from the notebook UI, and/or waiting multiple seconds between cell executions don't have any effect that I've seen.

_However_, when I `cargo run` with `--features __runtime_js_sources`, shut down my existing kernel, restart local jupyter (probably overkill), and start a new kernel, the issue mysteriously disappears altogether.
```bash
deno on  main [?] via 🦀 v1.72.0
❯ cargo run --features __runtime_js_sources -- jupyter --unstable --install
    Finished dev [unoptimized + debuginfo] target(s) in 0.29s
     Running `target/debug/deno jupyter --unstable --install`
[InstallKernelSpec] Removing existing kernelspec in <home>/.local/share/jupyter/kernels/deno
[InstallKernelSpec] Installed kernelspec deno in <home>/.local/share/jupyter/kernels/deno
✅ Deno kernelspec installed successfully.
```
image

(And then, if I go back to `cargo run -- jupyter --unstable --install`, shut down my existing kernel, restart local jupyter, start a new kernel, the `BadResource` issue consistently reappears.)

❔ I have _no_ idea why that would fix things based on the feature flag description and @bartlomieju's explanation in https://github.com/denoland/deno/issues/20524#issuecomment-1722286670, but it's the only thing I've found that makes these errors seem to go away.

I couldn't tell if this overlapped at all with https://github.com/denoland/deno/issues/19255 or a couple other issues mentioning the BadResource issue, but this was the most minimal example I could provide specifically running with the jupyter subcommand.

---

Similarly, I saw issues with `Deno.mkdir` and `Deno.writeFile` after using `cargo run -- jupyter --unstable --install`:
image

...but not with `cargo run --features __runtime_js_sources -- jupyter --unstable --install`:
image

Hopefully these examples help - let me know if there's any other information I can provide!

### PR DESCRIPTION
**Pull request by mmastrac**
Fixes #20534  

An op2 needs to be overloaded by an op2, not an op1.

### CODE REVIEW

**Review by dsherret — APPROVED** [review]
LGTM

**Comment by lucacasonato** [comment]
Does it also fix https://github.com/denoland/deno/issues/20524?

**Comment by rgbkrk** [comment]
Confirmed fixed. We were able to run the canary of the deno jupyter kernel in Docker with this!

**Comment by shouples** [comment]
Thank you @mmastrac! 👏

**Pull request merged**
