### PR TITLE
feat(node): stabilize Node-API

### PR DESCRIPTION
**Pull request by bartlomieju**
Closes https://github.com/denoland/deno/issues/16709

### CODE REVIEW

**Comment by aapoalas** [comment]
A bit sad to see N-API become stable before FFI, but on the other hand FFI is nowhere near stable so I think this is fine :D

**Comment by bartlomieju** [comment]
> A bit sad to see N-API become stable before FFI, but on the other hand FFI is nowhere near stable so I think this is fine :D

Yeah - I kinda agree with that, but the thing is Node-API is defined and if something doesn't work as expected is simply a bug. FFI on the other hand is still being worked on (mostly by you 😛) so I think it's fair that it would still remain unstable. 

I'm still thinking if it should use other flag than `--allow-ffi`

**Comment by aapoalas** [comment]
> Yeah - I kinda agree with that, but the thing is Node-API is defined and if something doesn't work as expected is simply a bug. FFI on the other hand is still being worked on (mostly by you stuck_out_tongue) so I think it's fair that it would still remain unstable.

Yeah, N-API simply _is_ a stable interface to implement, there's no way around it :)

> I'm still thinking if it should use other flag than `--allow-ffi`

This may probably a good idea.

I'm bouncing between ideas of splitting `--allow-ffi` internally into two (`--allow-ffi-extend` for opening new libraries and creating new functions from pointers, and `--allow-ffi-use` for the rest, roughly) and implementing some sort of "key" API to enable usage of some FFI APIs with a "key" created using the `--allow-ffi` permission which can then be ditched.

**Review by aapoalas — DISMISSED** [review]
Test still currently requires `--unstable` due to `Deno.Command` usage. Need to either wait for https://github.com/denoland/deno/pull/17628 or change the test.

**Review by littledivy — APPROVED** [review]
LGTM - towards a reliable node-api 🥂

**Pull request merged**
