### PR TITLE
fix(cli): drop isolate in watch mode

### PR DESCRIPTION
**Pull request by littledivy**
Fixes https://github.com/denoland/deno/issues/18120 https://github.com/denoland/deno/issues/18137 https://github.com/denoland/fresh/issues/1073

### CODE REVIEW

**Comment by bartlomieju** [comment]
@littledivy I suggest we revert this change for now if you can't figure out the test hang quickly

**Comment by lucacasonato** [comment]
I would like to revert the entire change. We should clean data up properly

**Comment by ry** [comment]
I also think we should revert the entire drop optimization for now.

Generally if a process is exiting, not cleaning up is better - but we should understand better what's happening here.

**Comment by bartlomieju** [comment]
Closing in favor of https://github.com/denoland/deno/commit/224cff7a2f1de9cc821c34ccac63cc9e4ef17531

**Pull request closed without merging**
