### PR TITLE
perf(compile): code cache

### PR DESCRIPTION
**Pull request by dsherret**
Adds a lazily created code cache to `deno compile` by default.

The code cache is created on first run to a single file in the temp directory and is only written once. After it's been written, the code cache becomes read only on subsequent runs. Only the modules loaded during startup are cached (dynamic imports are not code cached).

The code cache can be disabled by compiling with `--no-code-cache`.

```
> hyperfine --warmup 2 scratch.exe scratch_new.exe
Benchmark 1: scratch.exe
  Time (mean ± σ):     282.9 ms ±   6.5 ms    [User: 78.1 ms, System: 15.6 ms]
  Range (min … max):   276.5 ms … 295.2 ms    10 runs

Benchmark 2: scratch_new.exe
  Time (mean ± σ):     129.7 ms ±   6.8 ms    [User: 17.1 ms, System: 9.7 ms]
  Range (min … max):   120.9 ms … 138.4 ms    21 runs

Summary
  scratch_new.exe ran
    2.18 ± 0.13 times faster than scratch.exe
```

Closes https://github.com/denoland/deno/issues/26502

### CODE REVIEW

**Comment by felipecrs** [comment]
This is very promising. Have you thought of including the initial code cache inside the compiled executable as well?

**Comment by dsherret** [comment]
Yeah, maybe at a later time and as a separate option. The problem is it will make the binary much larger.

**Review by bartlomieju — APPROVED** [review]
LGTM

**Comment by felipecrs** [comment]
@dsherret, how do I verify code cache is actually working on Deno 2.1.0?

**Comment by felipecrs** [comment]
I ran a benchmarks and the improvements I found are very subtle, I wonder if code cache is indeed working:

```
$ hyperfine --warmup 2 --shell none --runs 50 './pkgx-deno-2.0.6 git@2.44.0 --version' './pkgx-deno-2.1.0 git@2.44.0 --version'
Benchmark 1: ./pkgx-deno-2.0.6 git@2.44.0 --version
  Time (mean ± σ):     560.8 ms ±  17.2 ms    [User: 580.2 ms, System: 216.7 ms]
  Range (min … max):   534.8 ms … 615.1 ms    50 runs
 
Benchmark 2: ./pkgx-deno-2.1.0 git@2.44.0 --version
  Time (mean ± σ):     523.0 ms ±   8.3 ms    [User: 549.1 ms, System: 224.0 ms]
  Range (min … max):   508.6 ms … 549.8 ms    50 runs
 
Summary
  ./pkgx-deno-2.1.0 git@2.44.0 --version ran
    1.07 ± 0.04 times faster than ./pkgx-deno-2.0.6 git@2.44.0 --version
```

**Comment by bartlomieju** [comment]
@felipecrs if you compile with `--log-level debug` you should be able to see logs like `Loaded N code cache entries`

**Comment by felipecrs** [comment]
Thank you, I guess there's something wrong then:

```
❯ ./pkgx --version 2>&1 | grep cache
DEBUG RS - denort::cache::cache_db:170 - Opening cache /home/felipecrs/.cache/deno/node_analysis_cache_v2...
DEBUG RS - denort::standalone::code_cache:56 - Failed to deserialize code cache: Cache key mismatch

❯ ./pkgx --version 2>&1 | grep cache
DEBUG RS - denort::cache::cache_db:170 - Opening cache /home/felipecrs/.cache/deno/node_analysis_cache_v2...
DEBUG RS - denort::standalone::code_cache:56 - Failed to deserialize code cache: Cache key mismatch

❯ deno clean
Removed /home/felipecrs/.cache/deno (7865 files, 58.14MB)

❯ ./pkgx --version 2>&1 | grep cache
DEBUG RS - denort::cache::cache_db:170 - Opening cache /home/felipecrs/.cache/deno/node_analysis_cache_v2...
DEBUG RS - denort::standalone::code_cache:56 - Failed to deserialize code cache: Cache key mismatch
DEBUG RS - denort::cache::cache_db:389 - Created parent directory for cache db.

❯ ./pkgx --version 2>&1 | grep cache
DEBUG RS - denort::cache::cache_db:170 - Opening cache /home/felipecrs/.cache/deno/node_analysis_cache_v2...
DEBUG RS - denort::standalone::code_cache:56 - Failed to deserialize code cache: Cache key mismatch
```

**Comment by dsherret** [comment]
@felipecrs can you open an issue with a reproduction?

**Comment by dsherret** [comment]
The performance improvement will be most noticable when there's files that are quite large. For a bunch of smallish files it won't be that much.

**Pull request merged**
