### PR TITLE
chore: update `mtime cache` action to use `node16`

### PR DESCRIPTION
**Pull request by iuioiua**
This PR updates the `mtime cache` GitHub action to use `node16` instead of the soon-to-be-deprecated `node12`. This removes one of the repeated warnings from CI.

### CODE REVIEW

**Comment by bartlomieju** [comment]
Note to self: if landed, apply these changes to https://github.com/denoland/deno/pull/14448

**Comment by iuioiua** [comment]
@bartlomieju, is there anything else you need for this PR?

**Comment by bartlomieju** [comment]
> @bartlomieju, is there anything else you need for this PR?

No, I'll land it when resuming work on CI refactor

**Comment by bartlomieju** [comment]
Thanks, I included your changes in https://github.com/denoland/deno/pull/17358, gonna close this one.

**Pull request closed without merging**
