### PR TITLE
perf(core): Avoid using `Function.prototype.bind` in primordials for performance

### PR DESCRIPTION
**Pull request by petamoriken**
I thought that `Function.prototype.bind` was not good for performance because of [the large number of execution steps](https://tc39.es/ecma262/#sec-function.prototype.bind) and creating [bound function exotic objects](https://tc39.es/ecma262/#sec-bound-function-exotic-objects).

Function.prototype.bind spec

I don't know how to benchmark the core, so I need someone to tell me how to do it.

### CODE REVIEW

**Comment by petamoriken** [comment]
Failed in Windows 🤔

```
error: Uncaught (in worker "") Error
  throw new Error();
         ^
     at file:///C:/a/deno/deno/cli/tests/testdata/workers/drop_handle_race.js:2:9
     at deno:core/00_primordials.js:45:5
     at Object.action (deno:ext/web/02_timers.js:147:13)
     at handleTimerMacrotask (deno:ext/web/02_timers.js:64:12)
error: Uncaught (in promise) Error: Unhandled error in child worker.
     at Worker.#pollControl (deno:runtime/js/11_workers.js:155:21)
```

**Comment by kt3k** [comment]
Looks like that test case asserts about the stack trace on error and this PR's change seems affecting it. Can you update the expectation of it? (`cargo test integration::run::worker_drop_handle_race` command executes only that test case)

**Comment by kt3k** [comment]
Can you also compare the results of `cargo bench --bench deno_bench` in this branch and main?

**Comment by petamoriken** [comment]
@kt3k It fails in `cli/bench/http/deno_http_flash_ops_spawn.js` unless it's in Linux. I don't have its environment.

**Comment by kt3k** [comment]
@petamoriken Thanks for updating. I'll take a look

**Comment by kt3k** [comment]
@petamoriken What benchmarks do you think this PR improves?

I tried hello (`cli/tests/testdata/run/002_hello.ts`, measured exec time by hyperfine) and http (`cli/bench/http/deno_http_flash.js`, measured req/sec by wrk), but I couldn't find significant differences in numbers.

**Comment by bartlomieju** [comment]
> @petamoriken What benchmarks do you think this PR improves?
> 
> I tried hello (`cli/tests/testdata/run/002_hello.ts`, measured exec time by hyperfine) and http (`cli/bench/http/deno_http_flash.js`, measured req/sec by wrk), but I couldn't find significant differences in numbers.

If that's the case I would be -1 to land this PR.

**Comment by petamoriken** [comment]
I will try to find out if this PR is effective.

**Comment by bartlomieju** [comment]
> I could't find it too, so I close this PR. I'm sorry for taking your time 🙇

That's fine, thanks for the PR anyway!

**Pull request closed without merging**
