### PR TITLE
re-fix permissions for dial and listen

### LINKED ISSUE #2397: Re-land "Fix permissions for dial and listen (#2373)"
Reverted due to Mac CI breakage.

### PR DESCRIPTION
**Pull request by bartlomieju**
Closes #2397

### CODE REVIEW

**Comment by ry** [comment]
Can you provide a diff from the original patch?

**Comment by bartlomieju** [comment]
For now these patches are the same, I'm checking if tests hang on Mac in CI, but as in original PR everything is green

**Comment by bartlomieju** [comment]
I'm running build on master on my forked repo. Will get back to you

**Comment by bartlomieju** [comment]
Alright I can repeat the problem when building master: https://travis-ci.org/bartlomieju/deno/jobs/536185134

I'll investigate and get back

**Comment by bartlomieju** [comment]
Note to self - output from travis debug build:
```
test_write_inside_tests_and_js_dir ... /Users/travis/build/bartlomieju/deno/target/release/deno run --no-prompt --allow-write=/Users/travis/build/bartlomieju/deno/tests,/Users/travis/build/bartlomieju/deno/js tools/complex_permissions_test.ts write js/dir_test.ts tests/subdir/config.json
ok
test_write_relative ... /Users/travis/build/bartlomieju/deno/target/release/deno run --no-prompt --allow-write=./tests tools/complex_permissions_test.ts write tests/subdir/config.json
ok
test_write_no_prefix ... /Users/travis/build/bartlomieju/deno/target/release/deno run --no-prompt --allow-write=tests tools/complex_permissions_test.ts write tests/subdir/config.json
ok
test_net_fetch_allow_localhost_4545 ... /Users/travis/build/bartlomieju/deno/target/release/deno run --no-prompt --allow-net=localhost:4545 tools/complex_permissions_test.ts net_fetch http://localhost:4545
127.0.0.1 - - [23/May/2019 13:20:42] "GET / HTTP/1.1" 200 -
ok
test_net_fetch_allow_deno_land ... /Users/travis/build/bartlomieju/deno/target/release/deno run --no-prompt --allow-net=deno.land tools/complex_permissions_test.ts net_fetch http://localhost:4545
ok
test_net_fetch_allow_localhost_4545_fail ... /Users/travis/build/bartlomieju/deno/target/release/deno run --no-prompt --allow-net=localhost:4545 tools/complex_permissions_test.ts net_fetch http://localhost:4546
ok
test_net_fetch_allow_localhost ... /Users/travis/build/bartlomieju/deno/target/release/deno run --no-prompt --allow-net=localhost tools/complex_permissions_test.ts net_fetch http://localhost:4545 http://localhost:4546 http://localhost:4547
127.0.0.1 - - [23/May/2019 13:20:42] "GET / HTTP/1.1" 301 -
127.0.0.1 - - [23/May/2019 13:20:42] "GET / HTTP/1.1" 301 -
127.0.0.1 - - [23/May/2019 13:20:42] "GET / HTTP/1.1" 200 -
ok
test_net_dial_allow_localhost_4545 ... /Users/travis/build/bartlomieju/deno/target/release/deno run --no-prompt --allow-net=localhost:4545 tools/complex_permissions_test.ts net_dial localhost:4545
FAILED
Traceback (most recent call last):
  File "./tools/complex_permissions_test.py", line 276, in <module>
    main()
  File "./tools/complex_permissions_test.py", line 272, in main
    complex_permissions_test(deno_exe)
  File "./tools/complex_permissions_test.py", line 265, in complex_permissions_test
    p.test()
  File "./tools/complex_permissions_test.py", line 122, in test
    ["localhost:4545"])
  File "./tools/complex_permissions_test.py", line 60, in wrap_test
    test_method(*argv)
  File "./tools/complex_permissions_test.py", line 220, in test_allow_localhost_4545
    assert code == 0
AssertionError
Traviss-Mac-6:deno travis$ /Users/travis/build/bartlomieju/deno/target/release/deno run --no-prompt --allow-net=localhost:4545 tools/complex_permissions_test.ts net_dial localhost:4545
Uncaught ConnectionRefused: Connection refused (os error 61)
    at DenoError (js/errors.ts:22:5)
    at maybeError (js/errors.ts:33:12)
    at handleAsyncMsgFromRust (js/dispatch.ts:41:17)
    at handleAsyncMsgFromRust (shared_queue.js:157:9)
```

**Comment by bartlomieju** [comment]
I've done several runs of release build on Travis (latest one available [here](https://travis-ci.org/bartlomieju/deno/jobs/536331286)) and failing tests are:
- `test_net_dial_allow_localhost_4545` - this one fails occasionally
- `test_net_dial_allow_localhost` - this one fails always

Both of them fail with `Uncaught ConnectionRefused: Connection refused (os error 61)` but the strange thing is they only fail on release builds on Travis (ran locally multiple times, always passing). 

CC @piscisaureus @ry

**Comment by ry** [comment]
@bartlomieju Is it an issue with resolving localhost? What if 127.0.0.1 is used?

**Comment by bartlomieju** [comment]
@ry using 127.0.0.1 makes tests pass on Travis. I can update test cases to use that address and get build green. Still it's interesting why using `localhost` make tests fail...

**Comment by ry** [comment]
@bartlomieju It may be possible /etc/hosts is set differently during master build?

**Comment by piscisaureus** [comment]
I've seen the failure during PR builds too so I suspect its not the hosts file.
I'd look into whether the http server is fully up and running before running the test.
Or maybe another instance of the http server is still in the process of shutting down.

**Comment by bartlomieju** [comment]
@piscisaureus I've checked hosts file, in both cases they're the same:
```
// release build
Traviss-Mac-6:deno travis$ cat /etc/hosts
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
255.255.255.255 broadcasthost
::1             localhost
127.0.0.1 localhost 127.0.0.1   Traviss-Mac-6.local

// PR build
Traviss-Mac-6:deno travis$ cat /etc/hosts
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
255.255.255.255 broadcasthost
::1             localhost
127.0.0.1 localhost 127.0.0.1   Traviss-Mac-6.local
```

I run tests both in suite and in isolation and HTTP server doesn't seem to be a problem.

I'm checking how URLs are resolved for each op, we'll get back to you

**Comment by bartlomieju** [comment]
```
test_net_dial_allow_localhost ... /Users/travis/build/bartlomieju/deno/target/release/deno run --no-prompt --allow-net=localhost tools/complex_permissions_test.ts net_dial localhost:4545 localhost:4546 localhost:4547
stdout:  	op_dial, resolved address: V6([::1]:4545)
stderr:  Uncaught ConnectionRefused: Connection refused (os error 61)
    at DenoError (js/errors.ts:22:5)
    at maybeError (js/errors.ts:33:12)
    at handleAsyncMsgFromRust (js/dispatch.ts:41:17)
    at handleAsyncMsgFromRust (shared_queue.js:157:9)
FAILED

test_net_dial_allow_localhost ... /Users/travis/build/bartlomieju/deno/target/release/deno run --no-prompt --allow-net=127.0.0.1 tools/complex_permissions_test.ts net_dial 127.0.0.1:4545 127.0.0.1:4546 127.0.0.1:4547
stdout:  	op_dial, resolved address: V4(127.0.0.1:4545)
	op_dial, resolved address: V4(127.0.0.1:4546)
	op_dial, resolved address: V4(127.0.0.1:4547)
stderr:  
ok
```

Okay so using `localhost` resolves to IPv6 `[::1]:4545` and fails. Using `127.0.0.1:4545` resolves to  IPv4 `127.0.0.1:4545` and passes. 

Output from `/etc/hosts` shows that `::1` should resolve the same as `127.0.0.1`

CC @piscisaureus @ry

**Comment by ry** [comment]
Cool - thanks for investigating!

Let's land and see.

**Comment by yazaddaruvala** [comment]
Was it intentional that this change so drastically improved the Max Latency benchmarks for hyper?

**Comment by ry** [comment]
@yazaddaruvala Hyper has a bug which is causing bad tail latency. It's not related to this change. They have been informed (tho I don't have an issue number...)

**Pull request merged**
