### PR TITLE
refactor(core): make `borrow_mut` more explicit in the ops macro

### PR DESCRIPTION
**Pull request by MarinPostma**
This PR fixes a potentially hard to debug compilation failure in the case where `std::borrow::BorrowMut` is in scope when ops are defined:

```
use std::borrow::BorrowMut;

//later

#[deno_core::op]
fn my_op(state: &mut deno_core::OpState) //...
```

This will refuse to compile because `Rc::borrow_mut` gets called instead of `RefCell::borrow_mut` on `Rc<RefCell<OpState>>` in the generated macro code.

see also: https://github.com/rust-lang/rust/issues/39232

### CODE REVIEW

**Review by littledivy — COMMENTED** [review]
Thanks for the PR. Maybe `std::cell::RefCell::borrow_mut(&ctx.state)` is better / more explicit?

**Comment by MarinPostma** [comment]
Fair, let me change that

**Comment by bartlomieju** [comment]
@littledivy please take a look

**Review by littledivy — APPROVED** [review]
LGTM, thank you

**Pull request merged**
