### PR TITLE
feat(ext/fetch) add referrer and referrerPolicy implementation to Request and fetch

### PR DESCRIPTION
**Pull request by sevenwithawp**
Hi Deno team, going through the code, you can definitely see and feel how much time, effort, and love is put into Deno ❤️

I discovered that `referrer` and `referrerPolicy` logic was not implemented for `Request` class and `fetch`. I used the spec to implement the referrer determination logic, and the tests seems to prove that this logic is working. The only doubts I get is about the adding/removing referrer to/from the `headerList`. It seems hacky. Please let me know if there are any comments. I'm more than happy to resolve them

### CODE REVIEW

**Review by lucacasonato — COMMENTED** [review]
I don't quite see how `referrer` is useful for Deno (and especially `referrerPolicy`, considering we intentionally do not implement CORS or other same site security restrictions that browsers have. If there is no origin on the context, there is no default referrer to set, rendering `reffererPolicy` not very useful.

**Comment by sevenwithawp** [comment]
Sure, for example, somebody wants to make some analytics on top of coming requests to the server using the referrer values something like:

**Internal**
Internal referrers occur when a visitor navigates between two pages of the same domain. Example: http://site.com/ => http://site.com/about

**Link**
If there is a referrer present but it's unrecognized above, we'll just call it a link referrer.

**Direct**
When a visitor navigates to a site by typing in the url into the address bar, document.referrer is blank.

Developers can do so right now by getting the header value, but if we have the value, it's not hard to implement it as the spec says for the Request WEB API.
`Request.referrer`
Maybe some libraries are relying on that.

Using this example, the developers might want to test their tool using Deno by setting the needed referrer value. By spec, they can do it like:
`fetch('http://site.com/about', { referrer: 'http://site.com/', referrerPolicy: 'unsafe-url' });`

Or some web scraper functionality might be wanting to set the referrer to get different pages and so different data.

But I got your point that other than 'unsafe-url' for the ReferrerPolicy, there potentially are no other use cases. Maybe it's better to get rid of the determination logic and just allow to set the referrer.

What do you think?

**Comment by lucacasonato** [comment]
I think users could already set the referrer by setting the appropriate header, so even unsafe-url may be slightly misguided.

**Comment by sevenwithawp** [comment]
Fair enough. So what about adding `referrer` and `referrerPolicy` getters to the `Request` class due to the spec and allowing setting `referrer` from `fetch` options(also due to the spec) and removing the referrerPolicy logic?

**Comment by sevenwithawp** [comment]
@lucacasonato a friendly reminder, so I will be able to start working on changes during the weekends if we agree on the topic

**Comment by SimonHausdorf** [comment]
I also require the referrer for analytics purpose. Will this be implemented?

**Review by lucacasonato — COMMENTED** [review]
Thank you for the contribution @sevenwithawp, but after more consideration we are not interested in implementing `referrer` and `referrerPolicy` at this time. I do not think it is a useful feature on the server.

I looked through the PR implementation, and I am impressed by the amount of code you wrote for this.

I explicitly do not want to discourage you from making other contributions in the future by closing this PR. If you have another issue you'd like to work on, please do! Let's discuss in a GitHub Issue or on Discord first though, to avoid work that may not get merged.

Thank you.

**Pull request closed without merging**
