### PR TITLE
Vendor Acorn; Use Acorn parser in REPL

### LINKED ISSUE #3112: Deno does not throw an error on syntax error, but instead gives a new line
## Problem
I had just something to test with deno repl. I was trying this code:

```ts
objWithFunc =
   { sayHi: function() {
       console.log(`hi, ${this.name}!;`; 
       console.log(this))
        }, 
      name: 'Joel' 
   };
```

obviously it contained syntax errors, but I didn't know that (primarily because I just typed all that in one line) until I ran this code again with node repl and threw an error, while Deno stayed silent. It just does nothing and allows you to type anything more, like as if the code has not been finished yet:

[asciicast](https://asciinema.org/a/mrwZjD7FFV8XAX77yqYF2mt3R)

It throws an error on node. But it does not on deno. I think the expected action should be to throw an error. 

## Environment
```bash
$ uname -a
Darwin 7o 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
$ deno -v
deno: 0.20.0
v8: 7.9.218
typescript: 3.6.3
```

### PR DESCRIPTION
**Pull request by kevinkassimo**
If accepted, would close #3112

Add Acorn and use it to check if REPL input is terminated. This is basically adapted from [corresponding Node.js code](https://github.com/nodejs/node/blob/57c70835af07485948bb3690b78adbf52d2205cd/lib/internal/repl/utils.js).

### CODE REVIEW

**Comment by ry** [comment]
How much larger does this make the deno executable in release mode?

**Comment by kevinkassimo** [comment]
@ry seems to be +1M (comparing to deno v0.20)

**Comment by kitsonk** [comment]
This seems like a hammer to crack a nut (no pun intended).  Acorn's introduction would be _another_ whole AST parser included in Deno in addition to the TypeScript one.  It feels like we should be able to use the TypeScript languages services to the same effect, it would just be a matter of exposing them in an effective way.  Wouldn't that make more sense in the longer term than dramatically increasing the complexity of the REPL just so if someone makes a mistake in the REPL we behave better?

If we still want/need another parser, then I would suggest we look at something like Meriyah.  It is about 3.5x faster than Acorn (https://meriyah.github.io/meriyah/performance/).

**Comment by kitsonk** [comment]
(plus it is written in TypeScript...)

**Comment by kevinkassimo** [comment]
@kitsonk Meriyah seems to have less customizability on a cursory look.
I am not so familiar with the interface with TS language service. In Node's solution, Acorn essentially allow it to notice an early unexpected EOF with everything parsed okay so far, thus deducing it might be waiting for more user input. Believe it would work since it worked for ts-node.

**Comment by kitsonk** [comment]
Well, TS in the REPL is a different problem. The language services in TS compiler though are how things are handled in VScode for JavaScript.

I can take a look again how it was done with ts-node and how we might expose it.

What sort of customisation do we need? It seems really like we have a "simple" problem that shouldn't need anything complex. As you say, it really is a simple question of "do we have a full statement which can be run or fail".

**Comment by kitsonk** [comment]
Looking at `ts-node` it basically says that if the error is of the following:

```ts
const RECOVERY_CODES: Set<number> = new Set([
  1003, // "Identifier expected."
  1005, // "')' expected."
  1109, // "Expression expected."
  1126, // "Unexpected end of text."
  1160, // "Unterminated template literal."
  1161, // "Unterminated regular expression literal."
  2355 // "A function whose declared type is neither 'void' nor 'any' must return a value."
]);
```

That the error is recoverable and that more input should be sought.

The mechanism for the compilation isn't the language services, it is an incremental builder program.

**Comment by kevinkassimo** [comment]
@kitsonk these codes seems to be more concrete than the V8 ones. I'll investigate some time later this week.

**Comment by ry** [comment]
Closing this one because we don't want to add another parser. But thank you for the patch @kevinkassimo it will be instructive to have this. We should either be using TS or V8 parser.

**Pull request closed without merging**
