### PR TITLE
core: Add types for `Deno.core.print()`

### LINKED ISSUE #15282: `Deno.core.print()` Is Not Present in `lib.deno_core.d.ts`
While looking for the Deno core type declarations I found that the `print()` function wasn't included. We should add the `print()` function to the typescript declarations file with the other `Deno.core` declarations.

_Pull request incoming_

### PR DESCRIPTION
**Pull request by zicklag**
Resolves #15282.

Unfortunately I was unable to run the format script because `dprint` doesn't work behind my HTTP proxy.

Also, I'm getting an error when I try to run the lint script. It could be related:

```
dlint
error: Uncaught (in promise) Error: gitLsFiles failed
    throw new Error("gitLsFiles failed");
          ^
    at getFilesFromGit (file:///home/zicklag/git/other/deno/tools/util.js:23:11)
    at async getSources (file:///home/zicklag/git/other/deno/tools/util.js:87:12)
    at async dlint (file:///home/zicklag/git/other/deno/tools/lint.js:16:23)
    at async main (file:///home/zicklag/git/other/deno/tools/lint.js:149:5)
    at async file:///home/zicklag/git/other/deno/tools/lint.js:155:1
```

This is a super small change, that should pass both, I think.

### CODE REVIEW

**Comment by bartlomieju** [comment]
Please format the code using `tools/format.js`

**Comment by zicklag** [comment]
Once I get the chance, I'll try to find a workaround, but unfortunately `dprint` doesn't work for me behind my corporate proxy with a custom certificate:

```
Error resolving plugin https://plugins.dprint.dev/typescript-0.70.0.wasm: Error downloading https://plugins.dprint.dev/typescript-0.70.0.wasm - Error: https://plugins.dprint.dev/typescript-0.70.0.wasm: Connection Failed: tls connection init failed: invalid peer certificate contents: invalid peer certificate: UnknownIssuer
error: Uncaught (in promise) Error: dprint failed
    throw new Error("dprint failed");
          ^
    at dprint (file:///home/zicklag/git/other/deno/tools/format.js:14:11)
    at async main (file:///home/zicklag/git/other/deno/tools/format.js:20:3)
    at async file:///home/zicklag/git/other/deno/tools/format.js:41:1
```

I might be able to download the plugin through my browser and re-configure dprint to use a local file, but I've got to figure out how to do that.

**Comment by bartlomieju** [comment]
@zicklag that's okay, I formatted the code for you.

**Review by bartlomieju — APPROVED** [review]
Thanks

**Pull request merged**
