### PR TITLE
Only use Locker when calling into JS

### PR DESCRIPTION
**Pull request by afinch7**
cc @kevinkassimo

### CODE REVIEW

**Comment by ry** [comment]
Hmm good point. But `dyn_import_done` also calls into JS.

cc @piscisaureus

**Comment by afinch7** [comment]
@ry `dyn_import_done` uses Locker on the c++ side.

**Comment by ry** [comment]
Maybe that was better. It's very marginal but it is the highest req/sec yet for deno_tcp

Screen Shot 2019-07-18 at 9 28 52 PM

**Comment by ry** [comment]
The benefit to deno_tcp didn't pan out, the above peak was just noise. I'm now concerned that this patch actually caused a slow down. It's too soon to tell, but deno_core_single seems to be slower...

Screen Shot 2019-07-22 at 9 52 02 AM

**Pull request merged**
