### PR TITLE
fix(upgrade): don't prompt if latest version is older than current bi…

### LINKED ISSUE #16462: Harden update checker version matching
It appears some folks hit an issue with latest version propagation on our CDN, which might have caused a prompt showing to upgrade from "1.27.0" to "1.26.2". 

We should harden the upgrade checker to only show prompt if the latest available version is actually newer than the currently running version.

### PR DESCRIPTION
**Pull request by bartlomieju**
…nary

Closes #16462

### CODE REVIEW

**Comment by littledivy** [comment]
+bench

**Comment by bartlomieju** [comment]
@littledivy this PR doesn't change anything in the hot path

**Review by littledivy — APPROVED** [review]

**Review by dsherret — APPROVED** [review]
LGTM

**Review by dsherret — CHANGES_REQUESTED** [review]
Wait, no, let's remove the unwrap.

**Comment by bartlomieju** [comment]
Unwrap removed

**Review by dsherret — APPROVED** [review]

**Pull request merged**
