### PR TITLE
fix: Response/Body type definitons

### PR DESCRIPTION
**Pull request by keroxp**
Global type `Response` and `Body` (from __domTyeps) are different from return type of `fetch` (from __fetch).

### CODE REVIEW

**Comment by ry** [comment]
I don't really understand this.`__fetch.Response` is a class that implements the interface `__domTypes.Response`. It seems we should only be exposing the interface, not the class.

**Comment by keroxp** [comment]
Currently `Response` is defined as `__domTypes.Response`and its body as `__domTypes.Body`. if you use `Response` as a type, you can't refer to `body.close()`.

```ts
async function _fetch(): Promise<Response> {
  return fetch("https://deno.land")
}

const resp = await _fetch();
resp.body?.close()

```

```
error TS2339: Property 'close' does not exist on type 'ReadableStream<Uint8Array>'.

► file:///Users/keroxp/src/servest/hoge.ts:7:12

7 resp.body?.close()
             ~~~~~
```

**Comment by keroxp** [comment]
@ry This PR may be outdated. But still issue remains. Return type of `fetch` and global type `Response` differ from each other. Why?

**Comment by keroxp** [comment]
Close as outdated.

**Pull request closed without merging**
