### PR TITLE
fix(ext/ffi): Panic when arguments are of incorrect type in Deno.dlopen

### LINKED ISSUE #11741: Panic when arguments are of  incorrect type in Deno.dlopen
Any of the following statements panic 

```
let d=Deno.dlopen('/usr/lib/libc.so.6',{malloc:null})
let d=Deno.dlopen('/usr/lib/libc.so.6',null)
let d=Deno.dlopen('/usr/lib/libc.so.6')
let d=Deno.dlopen('/usr/lib/libc.so.6',{malloc:{parameters:['a'],result:'b'}})
```

### PR DESCRIPTION
**Pull request by F3n67u**
fix #11741

### CODE REVIEW

**Review by ry — COMMENTED** [review]
Thanks for the patch @F3n67u ! Can you please provide a test?

**Comment by F3n67u** [comment]
> Thanks for the patch @F3n67u ! Can you please provide a test?

Yes. Added a typescript unit test. but I am not sure if the test file is in the right directory.

**Comment by F3n67u** [comment]
Btw,  when test invalid argument type which ts-check will complain, what's the best practice? Now I use `as any` type assertion to make ts-check pass.

**Comment by bartlomieju** [comment]
> Btw, when test invalid argument type which ts-check will complain, what's the best practice? Now I use `as any` type assertion to make ts-check pass.

You can use `//@ts-ignore` or `//@ts-expect-error` directives, or just write the test case in JavaScript

**Comment by F3n67u** [comment]
> > Btw, when test invalid argument type which ts-check will complain, what's the best practice? Now I use `as any` type assertion to make ts-check pass.
> 
> You can use `//@ts-ignore` or `//@ts-expect-error` directives, or just write the test case in JavaScript

Thanks for your advice. I opted for `//@ts-expect-error` because:
1. `@ts-ignores` is easier to be forgotten about than `//@ts-expect-error`: see  https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/prefer-ts-expect-error.md
2. Test case written in Typescript is more consistent with other unit test in `unit` dir and latter added dlopen related unit test will benefit from typescript type check.

**Review by eliassjogreen — APPROVED** [review]
LGTM

**Comment by lucacasonato** [comment]
Thanks for the effort @F3n67u, but I managed to solve this in Rust instead in #11815 (less overhead). I have added you as a co-author in that PR.

**Pull request closed without merging**
