### PR TITLE
docs(console): Update docstrings for install and uninstall

### PR DESCRIPTION
**Pull request by McSneaky**
When running `deno -h` then `install` and `uninstall` scripts had description since deno 1 times :)

image

I tried to search for existing issue / PR, but couldn't find anything already existing

### CODE REVIEW

**Comment by McSneaky** [comment]
Not sure what's supposed to be there in the contribution agreement thingy, it's not loading for me
image

There's plank page and nothing is clickable. Only the logo in upper center of page
image

**Comment by McSneaky** [comment]
Tried in Private Mode in browser also, same thing
image

**Comment by bartlomieju** [comment]
Looks good, thanks! Unfortunately the CLA assistant is sometimes flaky, please try again later.

**Review by bartlomieju — APPROVED** [review]

**Comment by McSneaky** [comment]
CLA worked on mobile :+1:

**Pull request merged**
