### PR TITLE
feat(ext/ffi): support `null` in buffer argument

### LINKED ISSUE #12809: feature request: support for null value in FFI buffer argument
There's no way to pass a null pointer to a buffer argument in FFI right now. It would be great to support passing JS `null` value corresponding to a `nullptr` in FFI. I'm currently trying to use WinAPI which (of course) makes use of those.

I'd like to try work on this

### PR DESCRIPTION
**Pull request by DjDeveloperr**
- [x] Adds support for `null` in buffer argument. Corresponds to `nullptr` in FFI.
- [x] Adds relevant test case.

Fixes #12809

### CODE REVIEW

**Review by bartlomieju — CHANGES_REQUESTED** [review]
@DjDeveloperr tentatively this looks good to me, but please update type declarations to reflect that if buffer is `null` then buffer length shouldn't be passed as the next argument. Also an update to manual would be appreciated too.

**Comment by DjDeveloperr** [comment]
Do I add that to type declarations of `Deno.ForeignFunction`'s `parameters` field? I didn't quite get as passing length of buffer as next argument is not required.

**Comment by bartlomieju** [comment]
> 

I guess you don't need to add any types to `ForeignFunction`, but I'd be good to add some examples into the JSDoc for it.

**Comment by DjDeveloperr** [comment]
@bartlomieju Added an example for buffer argument and some notes about null buffer argument in JS doc.

**Comment by DjDeveloperr** [comment]
Looks like #12828 adds this too.. I guess I'll close this.

**Pull request closed without merging**
