### PR TITLE
Remove debug symbols by stripping the executable

### PR DESCRIPTION
**Pull request by patrickschur**
By default the release `deno` binary contains debug symbols which are not necessary for program execution. By stripping the binary we can remove these debug symbols and also reduce the file size by 15.66 MB (27.58 %).

Before: 56.78 MB
After: 41.12 MB

### CODE REVIEW

**Comment by ry** [comment]
But maybe we want debug symbols?

I think this could be done in Cargo.toml with
```toml
[profile.release]
strip = "symbols"
```

**Comment by patrickschur** [comment]
You don't want to have debug symbols inside your **release** version. They are totally useless for people who just want to use `deno`. 

I didn't know cargo already implemented this feature. Let me change that. :)

**Comment by kitsonk** [comment]
> They are totally useless and not necessary for people who just want to use `deno`.

But I believe they are necessary for getting meaningful stack traces when someone encounters a bug, right?

**Comment by Yamboy1** [comment]
Yes. I've encountered this before. When I tried to use the deno binary provided through the aur, which automatically strips executables, it gave me maybe a copule of readable lines of stack traces on a panic, which the official deno executable gave me all 30 odd lines.

**Comment by Yamboy1** [comment]
I guess the question is whether it's necessary for most users. Maybe there should be an alternative download which isn't stripped? For those who need to debug a rust panic for example?

**Comment by kitsonk** [comment]
Usually you realise you want the debug symbols _after_ the panic happens.  If we only had time machines.

**Comment by patrickschur** [comment]
I like the idea from @Yamboy1 to add an alternative download.

Here is my suggestion: Per default the release binary should be stripped and we keep the current naming scheme. But the debug version gets the suffix `-debug`.

[stripped]
deno-x86_64-apple-darwin.zip
deno-x86_64-unknown-linux-gnu.zip

[not stripped]
deno-x86_64-apple-darwin-debug.zip
deno-x86_64-unknown-linux-gnu-debug.zip

This way we don't break any existing download script. This will also have a positive effect on Docker images, where you want your image as small as possible.

**Comment by Spoonbender** [comment]
AFAIK you can split the debug symbols to a separate file, enabling them to be used only if needed (i.e. for crash dump analysis or callstack enrichment). In the Windows world these debug symbols often reside in a PDB file.
I don't have 1st hand experience of doing this with Rust, but Google shows some results: 
- https://users.rust-lang.org/t/debug-symbols-in-separate-file/14110
- https://frehberg.com/2019/05/rust-handling-executables-and-their-debug-symbols/

**Comment by Yamboy1** [comment]
Having thought about this a bit overnight, I feel like the best option would be to provide the debug binary as default, at least while deno is still quite new. I've seen a few bug reports on rust panics inside deno, and these would be basically impossible to debug without the debug symbols. As for the size difference, I'm not sure if the benefit of an extra 15MB saved is actually that big of a deal, especially as deno is provided as a zip in the releases. IMO we should wait a bit on this decision, maybe come back to it with 2.0, when deno is more stable and there will be less need for the debugging symbols. Just my 2c

**Comment by patrickschur** [comment]
So what do we do now and why does the build fail?

**Comment by ry** [comment]
@patrickschur I appreciate the patch, but I'm not ready to ship a stripped exe. I think it's going to be problematic for us to get meaningful bug reports. I'm going to close this without merge - thank you for the discussion tho!

(Also it turns out your original patch was probably the best way to do this. The toml snippit I gave you apparently only works on nightly.)

**Pull request closed without merging**
