### PR TITLE
feat: support deno-coverage-ignore-file comment

### PR DESCRIPTION
**Pull request by zhenfeng-zhu**
This PR is for https://github.com/denoland/deno/issues/16626

The solution is to read the file content. If it start with `// deno-coverage-ignore-file`, just filter it. 

For now, I did't find the way to implement `deno-coverage-ignore`. If you have any good idea, please tell me.

### CODE REVIEW

**Review by bartlomieju — COMMENTED** [review]
Can you please add a test that exercises this change?

> For now, I did't find the way to implement deno-coverage-ignore. If you have any good idea, please tell me.

This will be more involved and will require changes to `generate_coverage_report` - I suggest to take a look at `deno_lint` to see how it uses ignore directives and try to emulate similar behavior for coverage report generation

**Comment by zhenfeng-zhu** [comment]
Thanks. I will try it.

**Comment by zhenfeng-zhu** [comment]
After reading the deno_lint code, I think it's better to use deno_ast to parse the source code. And then, read the flag from the parsed_code to ignore the function or file.

**Comment by bartlomieju** [comment]
> After reading the deno_lint code, I think it's better to use deno_ast to parse the source code. And then, read the flag from the parsed_code to ignore the function or file.
> 
> ```rust
>     let syntax = deno_ast::get_syntax(self.media_type);
>     let parse_result = parse_program(&file_name, syntax, source_code);
> ```

Makes sense!

**Comment by zhenfeng-zhu** [comment]
Sorry, I got a covid. This pr will complete a little later than expected.

**Comment by bartlomieju** [comment]
> Sorry, I got a covid. I will do it later

Sorry to hear, feel better!

**Comment by bartlomieju** [comment]
@zhenfeng-zhu I feel that this would be a welcome change, are you still interested in finishing it?

**Comment by bartlomieju** [comment]
I'm gonna close this PR for now, due to lack of updates. There's still sizeable changes that need to happen to make it landable. Please feel free to reopen if you can pick it up again, thanks!

**Pull request closed without merging**
