### PR TITLE
update Tokio to 0.2.16

### PR DESCRIPTION
**Pull request by bartlomieju**

### CODE REVIEW

**Comment by bartlomieju** [comment]
I'm experiencing hanging of `std_tests`...

**Comment by ry** [comment]
It might be flaky. I was experiencing something like that yesterday. Possibly related to https://github.com/denoland/deno/commit/12c6b2395be2bd1371284adf03e4826ba5edc761 ?

**Comment by bartlomieju** [comment]
@ry I'm not sure, it hangs consistently, just after start of `std_tests`, both locally and on CI

**Comment by ry** [comment]
Then it’s a different issue. We’ll need to debug it. Can you narrow it down to a specific test?

**Comment by bartlomieju** [comment]
> Then it’s a different issue. We’ll need to debug it. Can you narrow it down to a specific test?

I can narrow it locally - `test [textproto] Reader : MIME Header Single ...` however, one of CI runs seems to hang on other test

**Comment by bartlomieju** [comment]
LLDB dump on hang:

<details>

```
▶ lldb
(lldb) attach 55934
Process 55934 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
    frame #0: 0x000000010d7e6459 deno`_$LT$core..result..Result$LT$T$C$E$GT$$u20$as$u20$core..ops..try..Try$GT$::into_result::hab751b09da0cbe4d(self=Result<&core::cell::Cell<core::option::Option<core::ptr::non_null::NonNull<core::task::wake::Context>>>, std::thread::local::AccessError> @ 0x00007ffee37b0648) at result.rs:1502:8
Target 0: (deno) stopped.

Executable module set to "/Users/biwanczuk/dev/deno/target/debug/deno".
Architecture set to: x86_64h-apple-macosx-.
(lldb) bt
error: need to add support for DW_TAG_base_type '()' encoded with DW_ATE = 0x7, bit_size = 0
error: need to add support for DW_TAG_base_type '()' encoded with DW_ATE = 0x7, bit_size = 0
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
  * frame #0: 0x000000010d7e6459 deno`_$LT$core..result..Result$LT$T$C$E$GT$$u20$as$u20$core..ops..try..Try$GT$::into_result::hab751b09da0cbe4d(self=Result<&core::cell::Cell<core::option::Option<core::ptr::non_null::NonNull<core::task::wake::Context>>>, std::thread::local::AccessError> @ 0x00007ffee37b0648) at result.rs:1502:8
    frame #1: 0x000000010c4f18d9 deno`std::thread::local::LocalKey$LT$T$GT$::try_with::h46efe2310cb69b50(self=0x000000010ff734f8, f=closure-0 @ 0x00007ffee37b0698) at local.rs:261:31
    frame #2: 0x000000010c4eb6c5 deno`std::thread::local::LocalKey$LT$T$GT$::with::h02d0167c10de327f(self=0x000000010ff734f8, f=closure-0 @ 0x00007ffee37b0728) at local.rs:239:8
    frame #3: 0x000000010c6fbfa6 deno`std::future::poll_with_tls_context::h83793542e4e2bb6c(f=Pin<&mut core::pin::Pin<alloc::boxed::Box<Future>>> @ 0x00007ffee37b0768) at future.rs:80:17
    frame #4: 0x000000010c4b3aff deno`deno::ops::dispatch_minimal::minimal_op::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hfd75b49852d1e21e at dispatch_minimal.rs:138:12
    frame #5: 0x000000010c708039 deno`_$LT$std..future..GenFuture$LT$T$GT$$u20$as$u20$core..future..future..Future$GT$::poll::hac0841377fc2471e(self=Pin<&mut std::future::GenFuture<generator-0>> @ 0x00007ffee37b09a8, cx=0x00007ffee37b0ac0) at future.rs:43:14
    frame #6: 0x000000010c8f09d7 deno`futures_executor::local_pool::block_on::_$u7b$$u7b$closure$u7d$$u7d$::ha2586e1cec588beb(cx=0x00007ffee37b0ac0) at local_pool.rs:317:22
    frame #7: 0x000000010c8eeffc deno`futures_executor::local_pool::run_executor::_$u7b$$u7b$closure$u7d$$u7d$::hbf137da8258ad335(thread_notify=0x00007ff819009ec0) at local_pool.rs:87:36
    frame #8: 0x000000010c4f0dab deno`std::thread::local::LocalKey$LT$T$GT$::try_with::h2da041736d96f0b3(self=0x000000010ff789f8, f=closure-0 @ 0x00007ffee37b0b58) at local.rs:262:15
    frame #9: 0x000000010c4ee201 deno`std::thread::local::LocalKey$LT$T$GT$::with::hdac7d06a9ccf56bf(self=0x000000010ff789f8, f=closure-0 @ 0x00007ffee37b0bd0) at local.rs:239:8
    frame #10: 0x000000010c8ee2b3 deno`futures_executor::local_pool::run_executor::hc85095ff6c1a2103(f=closure-0 @ 0x00007ffee37b0c38) at local_pool.rs:83:4
    frame #11: 0x000000010c8f040c deno`futures_executor::local_pool::block_on::hf0eae79158148e96(f=<unavailable>) at local_pool.rs:317:4
    frame #12: 0x000000010c4b48a0 deno`deno::ops::dispatch_minimal::minimal_op::_$u7b$$u7b$closure$u7d$$u7d$::he70e3e5a461406b6(control=(data_ptr = "", length = 12), zero_copy=Option<deno_core::isolate::ZeroCopyBuf> @ 0x00007ffee37b1168) at dispatch_minimal.rs:161:15
    frame #13: 0x000000010c9ff39a deno`deno::state::State::core_op::_$u7b$$u7b$closure$u7d$$u7d$::h4d462e16de3f1635(control=(data_ptr = "", length = 12), zero_copy=Option<deno_core::isolate::ZeroCopyBuf> @ 0x00007ffee37b1418) at state.rs:91:15
    frame #14: 0x000000010dc70138 deno`deno_core::ops::OpRegistry::call::h59253e48963711ad(self=0x00007ff818e085c0, op_id=32, control=(data_ptr = "", length = 12), zero_copy_buf=Option<deno_core::isolate::ZeroCopyBuf> @ 0x00007ffee37b15f8) at ops.rs:95:11
    frame #15: 0x000000010dc95350 deno`deno_core::isolate::Isolate::dispatch_op::h57c1681667bde8f7(self=0x00007ff818e08630, scope=0x00007ffee37b1db8, op_id=32, control_buf=(data_ptr = "", length = 12), zero_copy_buf=Option<deno_core::isolate::ZeroCopyBuf> @ 0x00007ffee37b1c48) at isolate.rs:383:19
    frame #16: 0x000000010dccecbd deno`deno_core::bindings::send::h7e963f184c9c94d2(scope=0x00007ffee37b1db8, args=FunctionCallbackArguments @ 0x00007ffee37b1a18, rv=ReturnValue @ 0x00007ffee37b1a20) at bindings.rs:448:4
    frame #17: 0x000000010dc99af1 deno`core::ops::function::Fn::call::he7d821d2420733f3((null)=0x00007ffee37b1dd8, (null)=(&mut rusty_v8::scope::Entered<rusty_v8::function::FunctionCallbackInfo, ()>, rusty_v8::function::FunctionCallbackArguments, rusty_v8::function::ReturnValue) @ 0x00007ffee37b1d50) at function.rs:72:4
    frame #18: 0x000000010dc4f5e0 deno`rusty_v8::function::_$LT$impl$u20$rusty_v8..support..MapFnFrom$LT$F$GT$$u20$for$u20$extern$u20$$u22$C$u22$$u20$fn$LP$$BP$const$u20$rusty_v8..function..FunctionCallbackInfo$RP$$GT$::mapping::_$u7b$$u7b$closure$u7d$$u7d$::hfe00b3605aca1f1d((null)=0x00007ffee37b1f00, info=0x00007ffee37b2030) at function.rs:252:6
    frame #19: 0x000000010dc7d277 deno`_$LT$extern$u20$$u22$C$u22$$u20$fn$LP$A0$RP$$u20$.$GT$$u20$R$u20$as$u20$rusty_v8..support..CFnFrom$LT$F$GT$$GT$::mapping::c_fn::hb1083a9ef56dc7dd(a0=0x00007ffee37b2030) at support.rs:434:10
    frame #20: 0x000000010de1ceaf deno`::Call() at api-arguments-inl.h:158:3 [opt]
    frame #21: 0x000000010de1b54e deno`::HandleApiCallHelper<false>() at builtins-api.cc:111:36 [opt]
    frame #22: 0x000000010de194f9 deno`::Builtin_Impl_HandleApiCall() at builtins-api.cc:141:5 [opt]
    frame #23: 0x000000010de19008 deno`::Builtin_HandleApiCall() at builtins-api.cc:129:1 [opt]
    frame #24: 0x000000010ef4c57f deno`Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit + 63
    frame #25: 0x000000010ed2e131 deno`Builtins_InterpreterEntryTrampoline + 209
    frame #26: 0x000000010ed2e131 deno`Builtins_InterpreterEntryTrampoline + 209
    frame #27: 0x000000010ed2e131 deno`Builtins_InterpreterEntryTrampoline + 209
    frame #28: 0x000000010ed2e131 deno`Builtins_InterpreterEntryTrampoline + 209
    frame #29: 0x000000010ed2e131 deno`Builtins_InterpreterEntryTrampoline + 209
    frame #30: 0x000000010ed2e131 deno`Builtins_InterpreterEntryTrampoline + 209
    frame #31: 0x000000010ed2e131 deno`Builtins_InterpreterEntryTrampoline + 209
    frame #32: 0x000000010ee01f0e deno`Builtins_AsyncFunctionAwaitResolveClosure + 430
    frame #33: 0x000000010f089e94 deno`Builtins_PromiseFulfillReactionJob + 564
    frame #34: 0x000000010edbe00e deno`Builtins_RunMicrotasks + 2062
    frame #35: 0x000000010ed24b58 deno`Builtins_JSRunMicrotasksEntry + 120
    frame #36: 0x000000010df6938b deno`::Invoke() [inlined] Call at simulator.h:142:12 [opt]
    frame #37: 0x000000010df69386 deno`::Invoke() at execution.cc:382 [opt]
    frame #38: 0x000000010df69ec8 deno`::InvokeWithTryCatch() at execution.cc:427:20 [opt]
    frame #39: 0x000000010df6a20a deno`::TryRunMicrotasks() at execution.cc:504:10 [opt]
    frame #40: 0x000000010dfa32e4 deno`::RunMicrotasks() at microtask-queue.cc:165:22 [opt]
    frame #41: 0x000000010dfa30b7 deno`::PerformCheckpoint() at microtask-queue.cc:117:5 [opt]
    frame #42: 0x000000010df90126 deno`::FireCallCompletedCallback() at isolate.cc:3940:44 [opt]
    frame #43: 0x000000010dd63a1f deno`::~CallDepthScope() [inlined] ~CallDepthScope at api.cc:308:32 [opt]
    frame #44: 0x000000010dd637f2 deno`::~CallDepthScope() at api.cc:298 [opt]
    frame #45: 0x000000010dd6605f deno`::Evaluate() at api.cc:2390:1 [opt]
    frame #46: 0x000000010dcb5e69 deno`rusty_v8::module::_$LT$impl$u20$rusty_v8..data..Module$GT$::evaluate::h7075ea46c8110622(self=0x00007ff819062c08, scope=0x00007ffee37b2fc0, context=Local<rusty_v8::data::Context> @ 0x00007ffee37b2e10) at module.rs:215:28
    frame #47: 0x000000010dcab366 deno`deno_core::es_isolate::EsIsolate::mod_evaluate::h3dfad59e57e3812e(self=0x00007ff818e088d0, id=422959103) at es_isolate.rs:240:15
    frame #48: 0x000000010c5aaac2 deno`deno::worker::Worker::execute_module::_$u7b$$u7b$closure$u7d$$u7d$::h3a2dc3195997b961 at worker.rs:163:4
    frame #49: 0x000000010c708b69 deno`_$LT$std..future..GenFuture$LT$T$GT$$u20$as$u20$core..future..future..Future$GT$::poll::hb9b0f8987b39ce44(self=Pin<&mut std::future::GenFuture<generator-0>> @ 0x00007ffee37b3328, cx=0x00007ffee37b45c0) at future.rs:43:14
    frame #50: 0x000000010c6fbc6c deno`std::future::poll_with_tls_context::h76c0a57253d9d192(f=Pin<&mut std::future::GenFuture<generator-0>> @ 0x00007ffee37b33c8) at future.rs:98:13
    frame #51: 0x000000010caf578a deno`deno::test_command::_$u7b$$u7b$closure$u7d$$u7d$::h71c1e1295a8812c6 at lib.rs:486:23
    frame #52: 0x000000010c705a29 deno`_$LT$std..future..GenFuture$LT$T$GT$$u20$as$u20$core..future..future..Future$GT$::poll::h84dbb83d090ffd25(self=Pin<&mut std::future::GenFuture<generator-0>> @ 0x00007ffee37b41e8, cx=0x00007ffee37b45c0) at future.rs:43:14
    frame #53: 0x000000010c52944a deno`_$LT$core..pin..Pin$LT$P$GT$$u20$as$u20$core..future..future..Future$GT$::poll::h7b61db8106cc2b6b(self=Pin<&mut core::pin::Pin<alloc::boxed::Box<Future>>> @ 0x00007ffee37b4290, cx=0x00007ffee37b45c0) at future.rs:119:8
    frame #54: 0x000000010cb06234 deno`tokio::runtime::basic_scheduler::BasicScheduler$LT$P$GT$::block_on::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::ha962b37ec5c1cabe at basic_scheduler.rs:131:57
    frame #55: 0x000000010ccc05c3 deno`tokio::coop::budget::_$u7b$$u7b$closure$u7d$$u7d$::h82bd0d49736af92d(hits=0x00007ff819009cb8) at coop.rs:97:8
    frame #56: 0x000000010c4f09e9 deno`std::thread::local::LocalKey$LT$T$GT$::try_with::h2769dffc828a1589(self=0x000000010ff7d650, f=closure-0 @ 0x00007ffee37b43c8) at local.rs:262:15
    frame #57: 0x000000010c4edcb7 deno`std::thread::local::LocalKey$LT$T$GT$::with::hbf0b1e3e03f85177(self=0x000000010ff7d650, f=closure-0 @ 0x00007ffee37b4468) at local.rs:239:8
    frame #58: 0x000000010cb04bbe deno`tokio::runtime::basic_scheduler::BasicScheduler$LT$P$GT$::block_on::_$u7b$$u7b$closure$u7d$$u7d$::h2af06071a94954c3 [inlined] tokio::coop::budget::h0c9662c68e81ab62(f=closure-0 @ 0x00007ffee37b4700) at coop.rs:79:4
    frame #59: 0x000000010cb04b93 deno`tokio::runtime::basic_scheduler::BasicScheduler$LT$P$GT$::block_on::_$u7b$$u7b$closure$u7d$$u7d$::h2af06071a94954c3(scheduler=0x00007ffee37b4cf0, context=0x00007ffee37b48d0) at basic_scheduler.rs:131
    frame #60: 0x000000010cb07460 deno`tokio::runtime::basic_scheduler::enter::_$u7b$$u7b$closure$u7d$$u7d$::h256401d40ccbdde6 at basic_scheduler.rs:213:28
    frame #61: 0x000000010ca66113 deno`tokio::macros::scoped_tls::ScopedKey$LT$T$GT$::set::h47c8d311ed30afd1(self=0x000000010ffc9fa8, t=0x00007ffee37b48d0, f=closure-0 @ 0x00007ffee37b4a18) at scoped_tls.rs:64:8
    frame #62: 0x000000010cb06aec deno`tokio::runtime::basic_scheduler::enter::habb860370da46e8d(scheduler=0x00007ffee37b4cf0, f=closure-0 @ 0x00007ffee37b4860) at basic_scheduler.rs:213:4
    frame #63: 0x000000010cb042e5 deno`tokio::runtime::basic_scheduler::BasicScheduler$LT$P$GT$::block_on::h8e38316121b94dc4(self=0x00007ffee37b4cf0, future=(pointer = core::future::future::Box<core::future::future::Future> @ 0x00007ffee37b4a80)) at basic_scheduler.rs:123:8
    frame #64: 0x000000010c4e1e90 deno`tokio::runtime::Runtime::block_on::_$u7b$$u7b$closure$u7d$$u7d$::h8e045a513ce8bd3f at mod.rs:418:33
    frame #65: 0x000000010c72fbd5 deno`tokio::runtime::context::enter::h0243bf138f4d1d03(new=<unavailable>, f=closure-0 @ 0x00007ffee37b4c10) at context.rs:72:4
    frame #66: 0x000000010c8652a4 deno`tokio::runtime::handle::Handle::enter::h104f74dcf9380c44(self=0x00007ffee37b4de0, f=closure-0 @ 0x00007ffee37b4c88) at handle.rs:39:8
    frame #67: 0x000000010c4e187a deno`tokio::runtime::Runtime::block_on::h52a16a44123c9aa5(self=0x00007ffee37b4ce8, future=(pointer = core::future::future::Box<core::future::future::Future> @ 0x00007ffee37b4c70)) at mod.rs:415:8
    frame #68: 0x000000010ca68ef8 deno`deno::tokio_util::run_basic::h9470e67a8b5e29a1(future=(pointer = core::future::future::Box<core::future::future::Future> @ 0x00007ffee37b4cd8)) at tokio_util.rs:18:2
    frame #69: 0x000000010c60313c deno`deno::main::he1cd78495f4d614a at lib.rs:575:15
    frame #70: 0x000000010c4414f9 deno`deno::main::h85c603ffed94bc71 at main.rs:4:2
    frame #71: 0x000000010c441462 deno`std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::h138b73d7974405d5 at rt.rs:67:33
    frame #72: 0x000000010f54a228 deno`std::panicking::try::do_call::hf2b35caddf59127c [inlined] std::rt::lang_start_internal::_$u7b$$u7b$closure$u7d$$u7d$::hd38dd0e12f275c20 at rt.rs:52:12 [opt]
    frame #73: 0x000000010f54a21c deno`std::panicking::try::do_call::hf2b35caddf59127c at panicking.rs:305 [opt]
    frame #74: 0x000000010f5556eb deno`__rust_maybe_catch_panic at lib.rs:86:7 [opt]
    frame #75: 0x000000010f54ab1e deno`std::rt::lang_start_internal::h8e563903bf99e7c1 [inlined] std::panicking::try::hc278c045b5a17f13 at panicking.rs:281:12 [opt]
    frame #76: 0x000000010f54aaeb deno`std::rt::lang_start_internal::h8e563903bf99e7c1 [inlined] std::panic::catch_unwind::h21f9aef85494420b at panic.rs:394 [opt]
    frame #77: 0x000000010f54aaeb deno`std::rt::lang_start_internal::h8e563903bf99e7c1 at rt.rs:51 [opt]
    frame #78: 0x000000010c441442 deno`std::rt::lang_start::hf244d8bc4d3c18af(main=(deno`deno::main::h85c603ffed94bc71 at main.rs:3), argc=4, argv=0x00007ffee37bf698) at rt.rs:67:4
    frame #79: 0x000000010c441522 deno`main + 34
    frame #80: 0x00007fff71d8bcc9 libdyld.dylib`start + 1
    frame #81: 0x00007fff71d8bcc9 libdyld.dylib`start + 1
(lldb)
```
</details>

**Comment by bartlomieju** [comment]
Culprit:
https://github.com/denoland/deno/blob/6204555be3feaf5171dfb1bba15203ef2bb33265/cli/js/testing.ts#L151-L160

Changing `log` to be asynchronous fixes the hang.

**Comment by ry** [comment]
done in https://github.com/denoland/deno/commit/b7e673ba9357495820b07fcdba1dffef92d24ea3

**Pull request closed without merging**
