### PR TITLE
refactor: cli doesn't need to depend on deno_tls

### PR DESCRIPTION
**Pull request by ry**
plus some other small refactors

### CODE REVIEW

**Review by lucacasonato — CHANGES_REQUESTED** [review]
The 30 second timeout will break users of streaming data, like SSE. A default timeout is not good. If you want to do timeouts, do a connection timeout, not a request timeout.

**Comment by andreubotella** [comment]
Also, the `AbortSignal.timeout()` API is being considered in the DOM spec (whatwg/dom#1032), which will let users add custom request timeouts.

**Comment by ry** [comment]
Ok - I'm reverting the 30 second timeout change. This PR will just be some innocent refactoring.

**Review by bartlomieju — APPROVED** [review]
LGTM

**Pull request merged**
