### PR TITLE
fix(add): error when config file contains importMap field

### PR DESCRIPTION
**Pull request by dsherret**
The "imports" field has higher precedence than "importMap", so we should error when `deno add` goes to add an `"imports"` field.

Closes https://github.com/denoland/deno/issues/24264
Closes https://github.com/denoland/deno/pull/24478

### CODE REVIEW

**Review by satyarohith — APPROVED** [review]
LGTM

**Review by bartlomieju — APPROVED** [review]
LGTM

**Comment by KnorpelSenf** [comment]
Wouldn't it be better to respect the `importMap` option and modify the import map file instead?

**Comment by dsherret** [comment]
@KnorpelSenf see https://github.com/denoland/deno/issues/24264#issuecomment-2299575055

**Pull request merged**
