### PR TITLE
Cleanup setTimeout repl test and alphabetize

### PR DESCRIPTION
**Pull request by hayd**
Alphabetization is a little bit churny, but there was an existing test called `test_settimeout` vs the new one `test_set_timeout` from #1233. If they collided only the last defined would have run.

The main change is to allow a sleep kwarg to input (see `test_set_timeout_interlaced`).

cc @kevinkassimo

### CODE REVIEW

**Comment by kevinkassimo** [comment]
Hmm the tests are for some reason failing. But otherwise the code looks fine to me

**Comment by hayd** [comment]
This works for me consistently with sleep=0.4.
Which is strange... why would it be different in the previous version?!

**Comment by hayd** [comment]
I modified the test slightly:
```
        out, err, code = self.input(
            "setTimeout(() => console.log('a'), 250)",
            "setTimeout(() => console.log('b'), 150)",
            sleep=0.2)
        assertEqual(out, '1\n2\na\nb\n')
```
and it passes now. It seems like the boot time (~130ms) was the issue, confusingly.

**Comment by ry** [comment]
@hayd It's a race condition - using such small timeouts (as I suggested) is causing it to be flaky. The proper way to handle this is to not wait for actual timeouts, but modify an internal clock.... 

Instead of the interlaced timeouts you add - keep the simpler test and - increase the timeout/sleep time.

**Pull request merged**
