### PR TITLE
fix(perm): allow-net with port 80

### PR DESCRIPTION
**Pull request by irbull**
This change-set adds a test case that demonstrates an issues with `allow-net`. If `allow-net` specifies a host and port, and the port is 80, then all ports are allowed.

This doesn't appear to happen with other well known ports.

This test demonstrates the problem reported in https://github.com/denoland/deno/issues/21220.

### CODE REVIEW

**Comment by irbull** [comment]
I've updated the PR with the following commit:
```
When setting `allow-net` to a host and port, if the port is 80, then
all ports are allowed. During the parsing of the host and port,
the scheme was assumed to be `http` which makes the port redundant.
In this case, Url::parse assumed `None` for the port, which allowed
for all ports.

This change-set uses the term `unknown` for the scheme as this has
no effect on the parsing of the host and port and ensures that the
specified port is used.

Fixes https://github.com/denoland/deno/issues/21220
```

**Comment by irbull** [comment]
Looks like when you call `Url::parse` on `http://` the parse will return an error (EmptyHost) but if you use a custom scheme `unknown://` it won't.

**Comment by irbull** [comment]
Updated the change-set to explicitly return a `url::ParseError::EmptyHost` if the host is not set. This is what `Url::Parse` does for well known schemes. It's also probably a bit safer anyways, instead of blindly calling `unwrap`.

**Comment by irbull** [comment]
The tests appear to run locally for me, so we should be able to kick this off again on the infra. Do you want me to rebase this change-set on `main`?

**Comment by bartlomieju** [comment]
Hey @irbull, sorry for a slow turnaround. Someone will review the PR this week.

**Comment by irbull** [comment]
No worries. I'm actually travelling right now. Let me know if you'd like me to rebase this first?

**Comment by irbull** [comment]
The test failures here seem to come from the integration tests for the server and the server not being shut down properly. I saw these too, but others were also suggesting that a transient issue in the tests may have been at play then. I rebased locally and ran the tests again today and I don't see this, although I'm running them on Mac not Windows.

**Pull request merged**
