### PR TITLE
chore: release crates for v1.18.2

### PR DESCRIPTION
**Pull request by ry**

### CODE REVIEW

**Comment by bartlomieju** [comment]
What about a PR that bumps all crates?

**Comment by lucacasonato** [comment]
@ry We usually just cherry pick directly to the patch branch (don't use a PR).

**Comment by lucacasonato** [comment]
Would be great if we could get https://github.com/denoland/deno/pull/13581 in here to. Any chance this can wait another couple of minutes?

**Review by bartlomieju — APPROVED** [review]
LGTM, but please change commit message

**Pull request merged**
