### PR TITLE
docs(tools): add documentation for deno compile cmd

### PR DESCRIPTION
**Pull request by FabianTe**
This PR adds documentation for the new `deno compile` command introduced in PR #8539 and discussed in #986

### CODE REVIEW

**Comment by FabianTe** [comment]
@lucacasonato I figure you may be the correct person to review this. Please excuse me if not or I am unintentionally spamming.

**Comment by bartlomieju** [comment]
Thanks @FabianTe, make sure to run `tools/format.js` and `tools/lint.js` to make CI pass

**Comment by FabianTe** [comment]
Hi Bartek, I'd love to. Turns out in my local project `third_party` is empty, `dprint` therefore can't be called and I don't know how to fix that. I tried building Deno myself, hoping that would populate the given folder but it doesn't. I guess I am missing something very obvious here? Sorry to bother.

**Comment by bartlomieju** [comment]
@FabianTe you need to check out git submodules, following command should do the trick: `git submodule update --init --recursive`

**Review by ry — COMMENTED** [review]
Thanks - please update `docs/toc.json` too

**Review by bartlomieju — APPROVED** [review]
LGTM, thank you @FabianTe!

**Pull request merged**
