### PR TITLE
fix(deno_node/require): Fix error with require.resolve when called with paths option

### PR DESCRIPTION
**Pull request by b123400**
When running the following code from a node module, an error occurs: 

```
require.resolve('anything', {paths:['any path']})

Error: Empty filepath.
    at pathDirname (deno:ext/node/02_require.js:50:13)
    at new Module (deno:ext/node/02_require.js:257:17)
    at Function.Module._resolveFilename (deno:ext/node/02_require.js:566:30)
    at Function.resolve (deno:ext/node/02_require.js:824:21)
```

This is caused by using an empty string for the fake package's id:

https://github.com/denoland/deno/blob/a09296322e1fd4451e903515a497d9e02e14ace6/ext/node/02_require.js#L566

while at the same time enforcing package id to be non-empty:

https://github.com/denoland/deno/blob/a09296322e1fd4451e903515a497d9e02e14ace6/ext/node/02_require.js#L48-L51

It looks like `pathDirname` is an implementation for `path.dirname`, but [the real one returns `"."` when an empty string is passed](https://github.com/denoland/deno_std/blob/dfbd08fd408cb4e6cbf1c664ce61c8dcc9b09b3f/path/posix.ts#L228-L229).
This PR fixes the issue by returning `"."` for `""`.

Related issue: https://github.com/denoland/deno/issues/17175 https://github.com/denoland/deno/issues/17176

### CODE REVIEW

**Comment by bartlomieju** [comment]
Thanks for the PR @b123400, could you add a test case that exercises this code path?

**Comment by b123400** [comment]
@bartlomieju Thanks for the reply. I am not familar with Deno, can you point to me where should I look / add a test case?
[The related test cases I can find are from deno_std](https://github.com/denoland/deno_std/blob/dfbd08fd408cb4e6cbf1c664ce61c8dcc9b09b3f/node/module_test.ts), however it's testing [the Module implementation in deno_std](https://github.com/denoland/deno_std/blob/dfbd08fd408cb4e6cbf1c664ce61c8dcc9b09b3f/node/module.ts) instead of the one in this repository.
Why are there 2 implementations?

**Comment by aapoalas** [comment]
> @bartlomieju Thanks for the reply. I am not familar with Deno, can you point to me where should I look / add a test case? [The related test cases I can find are from deno_std](https://github.com/denoland/deno_std/blob/dfbd08fd408cb4e6cbf1c664ce61c8dcc9b09b3f/node/module_test.ts), however it's testing [the Module implementation in deno_std](https://github.com/denoland/deno_std/blob/dfbd08fd408cb4e6cbf1c664ce61c8dcc9b09b3f/node/module.ts) instead of the one in this repository. Why are there 2 implementations?

The Node compat code recently moved from the `deno_std` repository into this repository. If you look at the main branch of `deno_std` you'll see that those files are no longer there. Though, I am not sure where the `module_test.ts` is now...

**Comment by b123400** [comment]
This is fixed in #18447

**Pull request closed without merging**
