### PR TITLE
feat(check): allow using side effect imports with unknown module kinds (ex. css modules)

### PR DESCRIPTION
**Pull request by dsherret**
This allows people to use imports like:

```ts
import "./app.css";
```

...with `deno check` in systems where there's a bundle step (ex. Vite). This will still error when using it with `deno run` or if the referenced file does not exist.

See test cases for behaviour.

### CODE REVIEW

**Comment by scarf005** [comment]
would this behavior be configurable? for projects not using bundlers like vite, this might introduce subtle import bugs that might be only be found on runtime

**Comment by dsherret** [comment]
> would this behavior be configurable? for projects not using bundlers like vite, this might introduce subtle import bugs that might be only be found on runtime

@scarf005 Probably not. This change aligns more with TypeScript which already doesn't error for these kind of imports:

No compiler errors for importing files that exist and do not exist

This branch in Deno is still more strict than TypeScript:

Still compiler errors for importing files that do not exist

**Comment by scarf005** [comment]
ah, so it will check for missing import. makes sense then.

**Review by bartlomieju — APPROVED** [review]
LGTM

**Pull request merged**
