### PR TITLE
Fix test cases of //website/app_test.js

### PR DESCRIPTION
**Pull request by kt3k**
This PR tries to fix failed test cases in //website/app_test.js.

(CI seems skipping these tests. See #888 for details)

### CODE REVIEW

**Comment by kevinkassimo** [comment]
Was discussing about this in #885. Like #882 failed to update tests

**Comment by ry** [comment]
Thanks @kt3k looks good. Two comments:
- I want to land the timers patch (#885) first. 
- The tests for benchmarks could be improved further still. Adding the fetch_deps syscall count has now required three changes: b7fd6e9c69f0bf8b6517bef0474f84f0a5623f77, 545109cf2df4548aae754734cc7b0852485d4edd, and this patch. Ideally if I made only the first change to `tools/benchmark.py` and ran the tests, I would get a failure indicating that I needed to update `website/app.js` as well. (Or better yet, `website/app.js` automatically detected the columns for each benchmark.) This is beyond the scope of what you're doing here - but I'm mentioning it in case you or @kevinkassimo would like do a refactor.

**Comment by kt3k** [comment]
@ry OK. No problem. I'll update this PR after #885 landed 👍 And going to consider the latter part as well.

**Comment by ry** [comment]
please rebase.

**Comment by kt3k** [comment]
Rebased and restored fixed test cases.

**Pull request merged**
