### PR TITLE
feat: Add "deno check --watch"

### PR DESCRIPTION
**Pull request by cuobiezi**

### CODE REVIEW

**Comment by VishnuJin** [comment]
@cuobiezi thanks for taking up the PR

I just tried to run check with watch args and have the following doubt

- after watch is run it is expected to catch and display the errors to right, but nothing changes in the watch windows

#### Start point - all good


### Expected error - but not update


Am I missing something here ?

**Comment by cuobiezi** [comment]
> @cuobiezi thanks for taking up the PR
> 
> I just tried to run check with watch args and have the following doubt
> 
> * after watch is run it is expected to catch and display the errors to right, but nothing changes in the watch windows
> 
> #### Start point - all good
> 
> 
> ### Expected error - but no update
> 
> 
> Am I missing something here ?

@VishnuJin Would you help to test hello(100) without watch ?Because I think I only add watch module for check with original check logic.

**Comment by VishnuJin** [comment]
> @VishnuJin Would you help to test hello(100) without watch ?Because I think I only add watch module for check with original check logic. 

sure, this is the error message from check

**Comment by cuobiezi** [comment]
@VishnuJin Thanks ,Let me check why.

**Comment by cuobiezi** [comment]
> > @VishnuJin Would you help to test hello(100) without watch ?Because I think I only add watch module for check with original check logic.
> 
> sure, this is the error message from check
> 
> 

@VishnuJin Do you pulled my last commit ? I added check at first time yesterday , And I can't reproduce your issue in my last version.

**Comment by cuobiezi** [comment]
Screen Shot 2022-07-29 at 8 04 28 PM

**Comment by VishnuJin** [comment]
@cuobiezi 
I just double checked the commit hash in my local and it seems to match the latest in remote

_feel free to let me know Incase some more info is needed from myside_ 

```
commit 4ed32acfeb4344c58f8b0fd2387954791c85875b (cuobiezi/fix/14858)
Author: cuobiezi <>
Date:   Thu Jul 28 20:17:03 2022 +0800

    feature: Add check at first time when --watch
```

**Comment by cuobiezi** [comment]
> @cuobiezi 
> 
> I just double checked the commit hash in my local and it seems to match the latest in remote
> 
> 
> 
> _feel free to let me know Incase some more info is needed from myside_ 
> 
> 
> 
> ```
> 
> commit 4ed32acfeb4344c58f8b0fd2387954791c85875b (cuobiezi/fix/14858)
> 
> Author: cuobiezi <>
> 
> Date:   Thu Jul 28 20:17:03 2022 +0800
> 
> 
> 
>     feature: Add check at first time when --watch
> 
> ```

Yeah I got it .Seem current code only catch first result. Can't catch new change.

**Comment by cuobiezi** [comment]
@VishnuJin fixed ,Please try again ,Many thanks.

**Comment by VishnuJin** [comment]
Kudos, I can confirm its working now...



_Also I have opened a new PR in your fork with a small unit test_

**Comment by aapoalas** [comment]
Can you rebase this?

**Comment by cuobiezi** [comment]
I will rebase it later

**Comment by lino-levan** [comment]
Gentle reminder to rebase this if you get the chance!

**Review by aapoalas — CHANGES_REQUESTED** [review]
Marking down the need for rebase.

**Pull request closed without merging**
