### PR TITLE
feat(repl): Don't type check when importing

### PR DESCRIPTION
**Pull request by a-lafrance**
This (very small) PR implements the change described in #13640: using `no-check` by default when the REPL is run.

Although it's just a one-line change, I do have a couple questions about my (potentially rough-around-the-edges) implementation:
1. I updated the existing `repl` flag tests to verify that when the `--no-check` flag is not supplied, it's set to `None` automatically, but there's no dedicated test case that verifies this behavior. I wasn't sure whether or not it would be good to add an entirely new test for this so I decided not to, but I'm just wondering if that would be a good idea. If desired, I'm happy to add it.

2. A few integration tests (they were all under `integration::compat`) consistently didn't pass when I ran `cargo test`. Although, I also ran them again without the change I made and the same failures seemed to happen, so I'm not sure if it's directly caused by that change. So I guess I'm just looking for a little guidance on what to do about those failures, and whether or not they're relevant to the change I made. I'm happy to provide more info about the failures (e.g. which tests failed and how) if that would help.

Thanks in advance for the review!

### CODE REVIEW

**Comment by bartlomieju** [comment]
Thanks @a-lafrance this looks good. I think we should add one more integration test to check that there is no `Check <url>` output; @dsherret what do you think?

**Comment by a-lafrance** [comment]
>  I think we should add one more integration test to check that there is no Check <url> output

Sure, just let me know if you think this would be good and I'll add it

**Comment by dsherret** [comment]
@bartlomieju I think it would be a lot of work to add a test for this because we don't have anything right now in the repl tests to read stderr. I think this PR is ok to merge as-is and if the behaviour regresses it's not a big deal.

**Comment by bartlomieju** [comment]
@dsherret sounds good!

**Comment by bartlomieju** [comment]
Tried locally, I think this is fine 👍

**Review by bartlomieju — APPROVED** [review]
LGTM, thank you @a-lafrance

**Pull request merged**
