### PR TITLE
fix(Response): use byte stream for string or uint8array

### PR DESCRIPTION
**Pull request by crowlKats**
For #17386

### CODE REVIEW

**Comment by bartlomieju** [comment]
@crowlKats could you look into enabling relevant WPT tests for this change?

**Comment by crowlKats** [comment]
@bartlomieju as per the linked issue, there currently arent any, this is a deno-specific problem; wpt tests around this will be available once the spec change is completed

**Comment by crowlKats** [comment]
though seems wpts are failing for some reason. will investigate

**Comment by Macil** [comment]
It's not enough to add `type: "bytes"` to get a usable byte stream. The `controller.byobRequest` value must be checked and used correctly in streams that set the type to bytes. This PR would cause the same issue that exists in Blob streams currently: https://github.com/denoland/deno/issues/14219#issuecomment-1407538689.

**Pull request closed without merging**
