### PR TITLE
fix: Deno.isatty throws for negative numbers

### PR DESCRIPTION
**Pull request by bartlomieju**
Closes https://github.com/denoland/deno/issues/14398

### CODE REVIEW

**Review by cjihrig — APPROVED** [review]
The code LGTM, but `deserialize_unsigned()` will still be wrong anywhere else where a negative number is passed.

**Comment by bartlomieju** [comment]
@kt3k is this still needed? I believe you already fixed it in deno_std

**Comment by cjihrig** [comment]
This might have been worked around in std, but this is still fundamentally broken.

**Comment by kt3k** [comment]
@bartlomieju 

> is this still needed? I believe you already fixed it in deno_std

Not fixed in std, but I think it's not urgently needed right now as far as I know. I think we should fix the root cause instead as @cjihrig suggests

**Pull request closed without merging**
