### PR TITLE
fix broken path in chat example in windows

### PR DESCRIPTION
**Pull request by disizali**
fix this : #4647

### CODE REVIEW

**Comment by disizali** [comment]
Thank you very much and I hope to be able to collaborate on the project in the long run

Unfortunately, this is not the case in Windows, and u.pathname is not same to "./index.html" , it will be :
`/C:/Users/Ali/Desktop/deno/std/examples/chat/index.html`

**Comment by Drunpy** [comment]
I see, as you mentioned in #4647 the problem is the same in node. The problem seems to be within URL parsing rather than in server.ts. I've found [this](https://github.com/nodejs/node/issues/10703) issue with a deeper troubleshooting at this topic, you may drive your solution there. I'm willing to help, just hit me up.

**Comment by disizali** [comment]
new URL href & pathname are standardized [[here](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL)] and cannot be changed separately in node or deno ,
problem is first slash in given pathname 

in node , a function in **url** library [[here](https://github.com/nodejs/node/blob/78e6d2484fcacdee0cc0a1303e49a5328f3470dd/lib/internal/url.js#L1348)] is provided for convert this kind of file path in windows , which solves this problem .

 anyway , currently this file has problems on Windows, and the shortest way to solve is to use **./index.html**

alternatives :
 in deno fs module itself used this function [[here](https://github.com/denoland/deno/blob/12c6b2395be2bd1371284adf03e4826ba5edc761/std/fs/expand_glob_test.ts#L42)] :
```javascript
function urlToFilePath(url: URL): string {
  // Since `new URL('file:///C:/a').pathname` is `/C:/a`, remove leading slash.
  return url.pathname.slice(url.protocol == "file:" && isWindows ? 1 : 0);
}
```

or another approach in node module [ [here](https://github.com/denoland/deno/blob/bced52505f32d6cca4f944bb610a8a26767908a8/std/node/module.ts#L1219) ]: 

and the last solution is to change fs readFile functions behavior to work with `file:///` path entirely.

**Comment by Drunpy** [comment]
I would go with node's approach. Simple because it's already done there and we know it works.

**Pull request closed without merging**
