### PR TITLE
BREAKING(std/path): Split basename() into fileName() and fileStem()

### PR DESCRIPTION
**Pull request by nayeemrmn**
- fix(std/node/path): Don't re-export `fromFileUrl()`

---

As I mentioned in #6829, the current specification of `basename()` (get the base file name and optionally strip a suffix if it's present) is unjustifiably silly and should not be stabilised on. I've split it into `fileName()` (get the base file name) and `fileStem()` (get the base file name without the extension) based on Rust APIs. Not every path has a base file name, so it can return null. This will make code safer than returning an empty string.

### CODE REVIEW

**Comment by AviVahl** [comment]
It looks like the naming in the path module followed the same API as Node.js's `path`. Getting it consistent with Rust is nice, but having it consistent with Node might prove more useful in the long run (for developers migrating between the two ecosystems).

I personally find `basename` to make more sense in those cases where I have a `/path/to/some-directory` and I want to parse out `some-directory`. Having to call `fileName` on a path I know points to a directory feels unintuitive, even though I realize the same path could have pointed to a file.

**Comment by nayeemrmn** [comment]
We already have `FileInfo`, so I'm not too concerned about `file` vs `base`. Anyway, that's for #6897. This is less about the name and more about the signature/behaviour.

**Comment by bartlomieju** [comment]
I'm in favor of landing this PR, @nayeemrmn could you rebase the branch when you get a moment?

**Comment by lucacasonato** [comment]
Putting this on hold until this is discussed in std working group.

**Comment by bartlomieju** [comment]
@nayeemrmn we won't land this PR before standard library migration to a separate repository. I'm still very much interested in discussing these changes on upcoming meetings and potentially landing the PR. 

Let's keep it open until the migration is done.

**Comment by bartlomieju** [comment]
Deno standard library was moved to [denoland/deno_std](https://github.com/denoland/deno_std), please reopen your PR there.

**Pull request closed without merging**
