### PR TITLE
fix(network): adjust Listener type params

### PR DESCRIPTION
**Pull request by jodinathan**
fixes https://github.com/denoland/deno/issues/18635

### CODE REVIEW

**Review by bartlomieju — CHANGES_REQUESTED** [review]
I'm marking this as "Request changes" because this PR changes types of the public stable Deno APIs that might have big impact on users. We need to carefully check if this will cause any breakages and if so we should line this change for Deno 2.0 release.

**Comment by jodinathan** [comment]
were you able to check this?  
it doesn't seem to be a breakable change

**Comment by bartlomieju** [comment]
Hey @jodinathan, sorry for a slow response. I haven't had a chance to verify it, I'll try to get someone to check it before the next minor release.

**Review by nayeemrmn — APPROVED** [review]
LGTM

Here's how I checked for breaking changes:
```ts
export interface Listener2<T extends Deno.Conn = Deno.Conn> extends AsyncIterable<T> {
  accept(): Promise<T>;
  close(): void;
  readonly addr: Deno.Addr;
  readonly rid: number;
  [Symbol.asyncIterator](): AsyncIterableIterator<T>;
  ref(): void;
  unref(): void;
}

export type TlsListener2 = Listener2<Deno.TlsConn>;

let a: Deno.Listener = eval("{}");
let b: Listener2 = eval("{}");
a = b;
b = a;
let c: Deno.TlsListener = eval("{}");
let d: TlsListener2 = eval("{}");
c = d;
d = c;

// No type checking errors on the assignments. Types are equivalent.
```

**Review by bartlomieju — APPROVED** [review]
LGTM, thanks @jodinathan

**Comment by jodinathan** [comment]
was this published?

**Comment by bartlomieju** [comment]
Yes, this was published in Deno v1.37

**Pull request merged**
