### PR TITLE
feat(ext/net): support Server Name Indication (SNI) for virtual hosts

### PR DESCRIPTION
**Pull request by wille-io**
The TLS protocol comes with extensions like ALPN and SNI. Deno already supports ALPN, but unfortunately doesn't support SNI. Why is SNI so important for Deno *now*? Deno's big focus on 'web services' (like Deno Deploy and Deno Fresh) means Deno has to be a good web server to catch on with e.g. Node. Unfortunately without SNI there can't be multiple virtual hosts for one listener, which means that one can only have one hostname / one TLS certificate per IP and port. This PR adds the possibility to create a TLS listener with multiple hostnames / TLS certificates.

If there is interest in this PR and the biggest shortcomings are resolved, I will start working on the missing bits listed below.

Also, please, call out any mistakes and misuses that I did in the Rust code.

What's missing for now:

- Node wrapper
- Docs
- A more fitting name than `sniInfo` 

Note: This is my first time using Rust, please be gentle. Thank you.

### CODE REVIEW

**Comment by bartlomieju** [comment]
Thanks for the PR @wille-io, we will discuss it internally this week and get back to you, but it seems like a useful addition 👍

**Comment by bartlomieju** [comment]
@wille-io I spoke with @lucacasonato and here's what he suggested:
1. Go with `resolveCertificate` API instead:
```ts
interface ServeTlsOptions extends ServeOptions {
  /** The default server certificate in PEM format. */
  cert?: string;
  /** The default server private key in PEM format. */
  key?: string;

  /** A function to return a certificate for a connection, based on the name
   * specified in the TLS ClientHello packet (SNI). If the function throws or
   * returns a rejected promise, the connection with the client will be aborted.
   *
   * The results of this function are cached by name, if the returned
   * certificate and key are valid. This function will never be invoked in
   * parallel for the same name.
   *
   * Multiple names may return the same certificate and key. */
  resolveCertificate?(name: string): Promise<{ cert: string; key: string }>;
}
```
It's a bit more cumbersome to handle but provides a lot more flexibility due to not requiring list of hostnames upfront. This would allow a library to implement something like https://caddyserver.com/docs/automatic-https, which would be really dope.
2. `op_accept_tls` can return either a ready TLS socket as a rid, <b>or a want-to-be-tls socket that is missing a certificate. in the latter case it returns a hostname and a rid. in that latter case it creates a ‘want-to-be-tls socket’ resource.</b>
3. in case a ready TLS socket is returned, yield it to the usercode, <b>if a want-to-be-tls socket is returned, invoke the callback with the hostname and await a response. if the callback fails, close the ‘want-to-be-tls socket’ resource. if it succeeds, call `op_accept_tls_finish(rid, cert, key)` to upgrade the  ‘want-to-be-tls socket’ resource into a ‘tls socket’ resource</b>

Parts in <b>bold</b> are what is needed to implement that. Let me know how that sounds and if you're interested in tackling this.

**Comment by wille-io** [comment]
I'll be tackling this and keep you updated! 
Looks like by using a callback function, the usage of the `cert_resolver` is out of scope now. Which might mean fiddling around with some part of the ClientHello ourselves instead of handing this completely to rustls. It would help to call the proposed `resolveCertificate` function directly from rust from within rustls' `cert_resolver`. Would this be acceptable or even possible? That would be the safest and cleanest solution I think.

**Comment by wille-io** [comment]
I'll try to feed a custom cert resolver with a rust promise, create a new op which waits for that promise to resolve. So `op_net_accept_tls` becomes a two-part thing. If the cert resolver is finally called from within rustls, we can resolve the promise from within the cert resolver. The `02_tls.js` part would call the callback function and feed the result back to the cert resolver.

**Comment by wille-io** [comment]
I talked to the very friendly developers of the rustls project on Discord. `cert_resolver` is for non-async only. What we need is `Acceptor` and `Accepted`, which seems to fit the workflow perfectly. The docs were already updated stating the async alternative for `cert_resolver`. 
First tests went great. Unfortunately I still have problems with tests that utilize `handshake()` on their connections. But I'm on it.

**Comment by bartlomieju** [comment]
@wille-io sounds good, thanks for keeping the PR updated. Is there anything I can help you with?

**Comment by bartlomieju** [comment]
@wille-io sorry for a slow response. Could you please update what's the state of this PR? What's the current blocker?

**Comment by wille-io** [comment]
@bartlomieju I'm stuck with the handshake problem. I committed a dirty work-in-progress branch with the new `resolveCertificate` function for the `TlsListener`. Please see my branch at https://github.com/wille-io/deno/tree/tls-handshake-problem. I added two test cases which were stolen from `tls_test.ts`. Running `cargo run run -A handshake_test_good.ts` will result in a successful handshake. However, running `cargo run run -A handshake_test_bad.ts` will be stuck in the handshake step at `op_tls_handshake`. 
Would be awesome if someone could have a look at it.

**Comment by mmastrac** [comment]
@wille-io I just added support for async cert validation in rustls-tokio-stream. What you should be able to do now is strip out the existing TlsStream implementation and replace it with the one from rustls-tokio-stream. There's a constructor that will allow you to provide a "ServerConfigProvider" that returns a future that gives you the ability to specify the right server config given the `ClientHello` message's SNI information.

https://docs.rs/rustls-tokio-stream/0.2.10/rustls_tokio_stream/struct.TlsStream.html#method.new_server_side_acceptor

If you want to start down this path I can help guide you towards to getting this implemented.

**Comment by Rocknerve** [comment]
+1 on the need for SNI.
It is impossible to serve both https://foo.com and https://bar.org from the same box without SNI.
Neither Deno nor Bun support SNI yet.
A lot of us are stuck with Node for serving our HTTPS until SNI works.

It sounds like @mmastrac already implemented the “SNICallback” functionality on the Tokio side? And so all that remains is for someone to hook that into the Deno frontend?

**Comment by mmastrac** [comment]
@wille-io -- thanks for all this early work! We landed https://github.com/denoland/deno/pull/23686 which should pave the way for this to fully land. 

What's left here is going to be the last bit of API work to get it across the line. I will try to get the last bits done if I find some time in the near future, however if you have some bandwidth I'm happy to help you with the last pieces. 😄

**Pull request closed without merging**
