### PR TITLE
refactor: rewrite tests in std/ to use Deno.test

### PR DESCRIPTION
**Pull request by bartlomieju**
* rewrite all tests in "std/" to use "Deno.test()"
* remove "std/testing/mod.ts"

### CODE REVIEW

**Comment by bartlomieju** [comment]
> LGTM - I love these big numbers of lines removed.
> 
> Please be extra sure this isn't silently breaking tests in std and cli/js. (If you change an assert there they should still break cargo test)

Confirmed, that adding failing assertion breaks `cargo test`

**Comment by galkowskit** [comment]
I asked about it on Gitter too (once I get an answer there I'll leave it here for posterity as well) but this change broke my CI. https://github.com/galkowskit/denofun/pull/43/checks?check_run_id=439140417

It looks like removal of `mod.ts` wasn't an issue for local tests (cached?) but it 404'd on CI. I need to update my tests to `Deno.test`, that's for sure.

But what would be the recommended approach for community to lock dependencies and update them later? `import { assertEquals, test } from "https://deno.land/std/testing/mod.t@<commit-hash>"`? Would that even work for removed files?

**Comment by bartlomieju** [comment]
@galkowskit 
```
import { assertEquals, test } from "https://deno.land/std@v0.32.0/testing/mod.ts
```

**Comment by nayeemrmn** [comment]
There are some references to `std/testing/mod.ts` in the manual.

**Pull request merged**
