### PR TITLE
fix(cli/typings): move WebGPU types to unstable

### PR DESCRIPTION
**Pull request by crowlKats**

### CODE REVIEW

**Review by lucacasonato — COMMENTED** [review]
the types are still loaded at runtime due to the `// <references` comment in deno.shared_globals.d.ts.

**Comment by bartlomieju** [comment]
@crowlKats please rebase

**Comment by crowlKats** [comment]
@bartlomieju this is actually a bit more complex and needs #7989

**Comment by crowlKats** [comment]
Closing as not strictly needed and needs a fair amount of effort

**Pull request closed without merging**
