### PR TITLE
refactor: clean up `unwrap` and `clone`

### PR DESCRIPTION
**Pull request by attila-lin**

### CODE REVIEW

**Review by bartlomieju — COMMENTED** [review]
Could you please revert changes to imports ordering? They are very noise and don't change anything besides making git diffs bigs

**Comment by attila-lin** [comment]
Reverted.

I have a little bit code style cleanliness. 😀

**Comment by crowlKats** [comment]
@attila-lin could you fix the merge conflicts?

**Review by littledivy — APPROVED** [review]
LGTM!

**Pull request merged**
