### PR TITLE
fix(lsp): timeout registry config fetching after 10 seconds

### LINKED ISSUE #16426: `deno repl` hangs without network access
Running the repl in 1.25.4 and 1.26.2 in a debian:11 container hangs when there's no network access. 

There are connection attempts to deno.land / tcp / 443, that seem to do a retry backoff which takes a couple of minutes

```
$ date; docker run -ti me/deno /deno repl --eval 'console.log(new Date())'
Wed 26 Oct 2022 01:45:56 UTC

2022-10-26T01:48:07.230Z
Deno 1.25.4
exit using ctrl+d or close()
> 
```

I think it might be related to the connections being dropped rather than getting an ICMP response. 

The `--no-remote` options don't seem to affect whatever is loading.

Could the remote lookups be disabled optionally? Is there a way to pre cache the remote lookup?

### PR DESCRIPTION
**Pull request by crowlKats**
Fixes #16426.

Or would we rather want to timeout directly in `FileFetcher.fetch`?

### CODE REVIEW

**Comment by bartlomieju** [comment]
Besides timeout (which I think should be lower like 10s) could you make sure that LSP is not downloading these files more often than once per day?

**Comment by crowlKats** [comment]
> could you make sure that LSP is not downloading these files more often than once per day (or at least every hour)?

below the changes i added it says they are cached for a week

**Comment by bartlomieju** [comment]
> below the changes i added it says they are cached for a week

I see, it's confusing that LSP shows "Download ..." on each startup. Maybe we could remove it if the file is not actually downloaded?

**Comment by crowlKats** [comment]
> > below the changes i added it says they are cached for a week
> 
> I see, it's confusing that LSP shows "Download ..." on each startup. Maybe we could remove it if the file is not actually downloaded?

the download message happens when starting to make a fetch, which i think is right behaviour; obviously this means it will log that even if timed out.

**Comment by bartlomieju** [comment]
> > > below the changes i added it says they are cached for a week
> > 
> > 
> > I see, it's confusing that LSP shows "Download ..." on each startup. Maybe we could remove it if the file is not actually downloaded?
> 
> the download message happens when starting to make a fetch, which i think is right behaviour; obviously this means it will log that even if timed out.

Okay, now I'm confused - if the message happens when starting a fetch, does that mean that LSP is actually downloading these files or not? If not, then I think this message should be deferred to when the actual request is getting fired off.

**Comment by crowlKats** [comment]
the log happens here https://github.com/denoland/deno/blob/fac64478157ee563b185edb5734688e4523df3a1/cli/file_fetcher.rs#L450-L455. the fetch call is 10 lines later

**Review by aapoalas — APPROVED** [review]
Looks fine to me.

**Review by satyarohith — COMMENTED** [review]
Is there anything preventing (apart from conflicts) from landing this PR or can we close it?

**Comment by crowlKats** [comment]
Closing since i cannot reproduce this anymore

**Pull request closed without merging**
