### PR TITLE
Add PR link to Releases.md

### PR DESCRIPTION
**Pull request by J2P**
`Releases.md` file did not have a PR link.
I added a link to quickly find the PR.

### CODE REVIEW

**Comment by shirshak55** [comment]
how about creating a bot that will fill releases.md once pr is accepted.

**Comment by J2P** [comment]
> did you do this automatically somehow? Maintaining these links is a pain. Isn’t there someway for the markdown to auto link to issues ?

No ... I did it manually.
When I heard you, I thought it would be hard.
We'll see how to link automatically.

**Comment by J2P** [comment]
> how about creating a bot that will fill releases.md once pr is accepted.

It's a good idea.
But I don't know how to make a robot.
I have to find a way to make a robot.

**Comment by kitsonk** [comment]
@J2P Here is a bot (https://github.com/kitsonk/bubba) I did a while ago which was capable of doing release notes based on PRs and a few other tools.  It should give you an idea of how to work with GitHub's APIs in TypeScript and be fairly straightforward to adapt to Deno.

**Comment by J2P** [comment]
@kitsonk Thank you

**Pull request closed without merging**
