### PR TITLE
Replace all CI with GitHub Actions

### PR DESCRIPTION
**Pull request by lucacasonato**
Replaced all of the CI with GitHub Actions. Still working on benchmark uploading. This should work soon.

### CODE REVIEW

**Comment by ry** [comment]
Nice ! Can you remove the .travis and .appveyor files - so the queue doesn’t get blocked by this work?

**Comment by lucacasonato** [comment]
> Nice ! Can you remove the .travis and .appveyor files - so the queue doesn’t get blocked by this work?

I already did a few days ago. I don't know why Travis and Appveyor are still trying to run this PR thru the pipeline. Maybe they just don't want to let us go 😂

**Comment by ry** [comment]
@lucacasonato where can i see the output of the github action runs?

**Comment by lucacasonato** [comment]
> @lucacasonato where can i see the output of the github action runs?

https://github.com/lucacasonato/deno/commit/fa3030e63ac7d56336282f5b930a9b0bb740c9d5/checks

**Comment by ry** [comment]
Very awesome @lucacasonato ! 

Let's move discussion to #2966 - I've pulled your yaml files in there.

**Pull request closed without merging**
