### PR TITLE
Remove tsconfig files - they are not part of build process

### PR DESCRIPTION
**Pull request by ry**

### CODE REVIEW

**Comment by bartlomieju** [comment]
I strongly opt to keep `std/tsconfig.test.json` - it ensures standard library code is written in such a way it passes strict type checks.

**Comment by ry** [comment]
@bartlomieju where is that specified?
```
~/src/deno> grep -R tsconfig.test.json .
./third_party/v8/tools/turbolizer/package.json
9:    "test": "ts-mocha -p tsconfig.test.json test/**/*-test.ts",
~/src/deno>
```

**Comment by bartlomieju** [comment]
@ry looks like it got removed during merging of deno_std.
It was used before in CI:
https://github.com/denoland/deno_std/blob/master/.ci/template.common.yml

**Comment by ry** [comment]
Added https://github.com/denoland/deno/issues/3266 to resolve the strict type checking.

**Pull request merged**
