### PR TITLE
fix(kernel): Do not increase counter if store_history=false

### PR DESCRIPTION
**Pull request by DonJayamanne**
Fixes https://github.com/denoland/deno/issues/20847
@bartlomieju I couldn't find a way to add tests for this.
Would appreciate some help here, thanks.

### CODE REVIEW

**Comment by bartlomieju** [comment]
> @bartlomieju I couldn't find a way to add tests for this.
> Would appreciate some help here, thanks.

We have an "integration test notebook" at `cli/tests/testdata/jupyter/integration_test.ipynb`. Would you be able to exercise this change there (or in a new notebook)?

**Comment by DonJayamanne** [comment]
>  Would you be able to exercise this change there (or in a new notebook)?

Unfortunately no, Notebooks always make requests that end up incrementing the execution counter, 
Messages with `store_history=false` can only be sent outside the context of cell execution in notebooks, ie when a message is crafted and sent via some other code

**Comment by bartlomieju** [comment]
> > Would you be able to exercise this change there (or in a new notebook)?
> 
> Unfortunately no, Notebooks always make requests that end up incrementing the execution counter, Messages with `store_history=false` can only be sent outside the context of cell execution in notebooks, ie when a message is crafted and sent via some other code
> 
> Basically a kernel has to be started & request sent manually in a test for this scenario.

I see, we'll have to write proper integration tests then - I think it's not very troublesome, just need to figure out which messages should be exchanged first to properly "setup" the kernel, before we can make "execute_request" messages working properly. Do you happen to have a reference what VSCode does to test the Jupyter integration?

**Comment by DonJayamanne** [comment]
>  Do you happen to have a reference what VSCode does to test the Jupyter integration?

In VS Code, we do not have tests for such messages, such messages do not produce any side effects, hence nothing to be tested. Also, this isn't something we need to test, we expect these to work (we're just calling an API and not really expecting any side effects except for some results)

Thus all tests in VS Code have notebooks, to test side effects such as Widgets, and outputs

Here are some of the test
* https://github.com/microsoft/vscode-jupyter/blob/0324dd1527df58788902cfc78f4c74c552c03a18/src/test/datascience/notebook/executionService.vscode.test.ts
* https://github.com/microsoft/vscode-jupyter/blob/771ea019f36a7b653eb43fdbbd085aef7c6b07fd/src/test/datascience/widgets/standardWidgets.vscode.common.test.ts
* https://github.com/microsoft/vscode-jupyter/blob/771ea019f36a7b653eb43fdbbd085aef7c6b07fd/src/test/datascience/widgets/thirdpartyWidgets.vscode.common.test.ts

**Comment by DonJayamanne** [comment]
> I see, we'll have to write proper integration tests then - I think it's not very troublesome,

Would that be in rust or TS?

**Comment by bartlomieju** [comment]
> > I see, we'll have to write proper integration tests then - I think it's not very troublesome,
> 
> Would that be in rust or TS?

The tests would be in Rust; probably something similar to what can be seen in `cli/tests/integration/inspector_tests.rs`

**Comment by DonJayamanne** [comment]
@bartlomieju would appreciate it if you could create the initial test
I think writing a test in rust for this would be a little difficult for me, as we might need to read the zmq messages and then translate that to JSON, i.e. lots of code just to setup the infrastructure.

Unless you have a better idea on how to test this without ZMQ, sockets and a lot of that infrastructure code.

**Comment by DonJayamanne** [comment]
> We have an "integration test notebook" at cli/tests/testdata/jupyter/integration_test.ipynb.

btw, how are these integration tests executed? Are they run manually by hand (i.e. by an individual) or is it automated?
Coultnt find code that ran this, hence the question.

**Comment by bartlomieju** [comment]
> > We have an "integration test notebook" at cli/tests/testdata/jupyter/integration_test.ipynb.
> 
> btw, how are these integration tests executed? Are they run manually by hand (i.e. by an individual) or is it automated? Coultnt find code that ran this, hence the question.

Yes, currently they are run manually when updating the integration. I'll write up an integration test in Rust to set up basic infrastructure and get back to you.

**Comment by bartlomieju** [comment]
@nathanwhit once you add the integration test for Jupyter, can you please rebase this PR and shepherd it to landing?

**Review by nathanwhit — APPROVED** [review]
LGTM! Thanks for the contribution and sorry it took a while to get this merged!

**Pull request merged**
