### PR TITLE
refactor(std/ws): add 'Sec-WebSocket-Protocol' support

### PR DESCRIPTION
**Pull request by ije**
add 'Sec-WebSocket-Protocol' support:
```javascript
const socket = new WebSocket(url, 'protocol');
```

### CODE REVIEW

**Comment by crowlKats** [comment]
This PR is unneeded due to #7051

**Comment by caspervonb** [comment]
> This PR is unneeded due to #7051

Are we removing std/ws? I quite like having a promise based option available.

**Comment by lucacasonato** [comment]
I would vote for deprecating the std/ws client for 1.4.0, then removing it in 1.5.0.

**Comment by bartlomieju** [comment]
Looks like https://github.com/denoland/deno/pull/6162 is very similar

**Review by lucacasonato — APPROVED** [review]
@ije Can you add a test that checks this behaviour? Can you also merge with master?

**Review by lucacasonato — CHANGES_REQUESTED** [review]
@ije Can you add a test that checks this behaviour? Can you also merge with master?

**Pull request closed without merging**
