### PR TITLE
test: add std_lint test

### PR DESCRIPTION
**Pull request by ry**
```
cargo test std_lint
```

Problem: no way to disabling no-explicit-any on next line while supporting both eslint and deno-lint

### CODE REVIEW

**Comment by bartlomieju** [comment]
There's quite a few of `no-explicit-any`:
```
(no-explicit-any) `any` type is not allowed
type Replacer = (key: string, value: any) => any;
                                     ~~~
    at ./std/fs/write_json.ts:3:37

(no-explicit-any) `any` type is not allowed
type Replacer = (key: string, value: any) => any;
                                             ~~~
    at ./std/fs/write_json.ts:3:45

(no-explicit-any) `any` type is not allowed
  object: any,
          ~~~
    at ./std/fs/write_json.ts:13:10

(no-explicit-any) `any` type is not allowed
  object: any,
          ~~~
    at ./std/fs/write_json.ts:35:10
```

`write_json.ts` has `/* eslint-disable @typescript-eslint/no-explicit-any */` comment at the top. `deno_lint` has no support for disabling rule for whole file. I suggest we just add inline ignores instead. @ry WDYT?

**Comment by ry** [comment]
> deno_lint has no support for disabling rule for whole file. I suggest we just add inline ignores instead. @ry WDYT?

SGTM

**Comment by bartlomieju** [comment]
`std_lint` should go green after landing https://github.com/denoland/deno/pull/6248

**Comment by ry** [comment]
Thanks for doing this patch @bartlomieju

**Pull request merged**
