### PR TITLE
feat(runtime): stabilize Deno.symlink and Deno.symlinkSync

### PR DESCRIPTION
**Pull request by caspervonb**
This makes Deno.symlink and Deno.symlinkSync stable.

These interfaces are well known; I've previously tried to drop the type option (https://github.com/denoland/deno/pull/7242) and we aren't going to do that so I don't see this interface changing at all in the future.

### CODE REVIEW

**Comment by caspervonb** [comment]
cc @piscisaureus @ry

**Comment by caspervonb** [comment]
As for the security review part; sandboxing of symlinks should be handled when they're followed not created. 

WASI does the same, you can create a symlink to outside of the sandbox as a dangling symlink but you cannot verify that said symlink is valid without having the proper capabilities.

Also matches the permission semantics of symlink(2).
 
> The permissions of a symbolic link are irrelevant; the ownership
> is ignored when following the link, but is checked when removal
> or renaming of the link is requested and the link is in a
> directory with the sticky bit (S_ISVTX) set.

**Comment by ry** [comment]
Do we need read/write permissions on both ends of the link?

**Review by ry — APPROVED** [review]
Thank you for the security review - makes sense to me.

Let's land it.

Thanks Capser.

**Pull request merged**
