### PR TITLE
syntax highlighting on the website

### PR DESCRIPTION
**Pull request by fengmu456**

### CODE REVIEW

**Comment by kitsonk** [comment]
Duplicate of #1768. We should always mention the issue we are trying to resolve to try to avoid duplicated efforts.

**Comment by solkaz** [comment]
@kitsonk my PR was made after this one, I hadn't bothered to check first, which was my mistake. Could I suggest amending the PR template to request mentioning the issue number(s) that the PR closes (if any)? or to check that a duplicate PR is already up?

**Comment by kitsonk** [comment]
@solkaz we have avoided having a complex template... I have raised a PR to update the contribution guidelines which are linked to in the existing template (#1771).

**Comment by fengmu456** [comment]
So should I close it?

**Comment by fengmu456** [comment]
Turn to #1780

**Pull request closed without merging**
