### PR TITLE
chore: add dependabot for automated dependency updates

### PR DESCRIPTION
**Pull request by F3n67u**
This pr add dependabot for rust automated dependency updates. I am not sure if the automated deps update suits deno, so I post a dicussion here: https://github.com/denoland/deno/discussions/11919

Dependabot creates pull requests to keep your Rust dependencies up-to-date. see introduction page: https://dependabot.com/rust/

The documentation for all configuration options:
https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

### CODE REVIEW

**Comment by bartlomieju** [comment]
There was a thread on #off-topic channel a couple days ago about adding dependabot: https://discord.com/channels/684898665143206084/688040863313428503/883012732205555843

I'm not strictly against it, but we bump dependencies manually before every minor release and it's not a big deal. Plus when there's an update to SWC and/or `deno_lint`, `deno_doc` it often involves manual changes anyway. So I'm not sure I'm in favor of landing this PR. @lucacasonato @dsherret thoughts?

**Comment by kitsonk** [comment]
I'm not in favour. Just like we don't run `cargo update` every time either, I would much rather leave it specific, intentional updates.  There is too much of a risk that automated updates are more likely to break CI.  Auto-rolling v8 is important, but it hasn't been without it challenges.

**Comment by dsherret** [comment]
I'm also not in favour and agree with what Kitson said. I find it creates a lot of noise and isn't that useful.

**Comment by bartlomieju** [comment]
Thanks for the PR @F3n67u, but closing without a merge.

**Pull request closed without merging**
