### PR TITLE
[WIP] feat(cli/flags): add `jobs` flag to fmt and lint subcommands

### LINKED ISSUE #9585: Add --jobs flag to relevant subcommands
Add a `-j, --jobs N`(most common name in the wild) flag to `deno lint` and `deno fmt` to let users control how many concurrent threads it will consume.

Might be applicable for other subcommands, like deno test soon'ish.
Not sure if we should apply this to the runtime commands like run, eval, etc.

### PR DESCRIPTION
**Pull request by mrkldshv**
Add `jobs` flag to fmt and lint subcommands.

Closes #9585.

### CODE REVIEW

**Review by caspervonb — COMMENTED** [review]
This doesn't seem hook it up to any of the respective job pools?

**Comment by mrkldshv** [comment]
@caspervonb Oh, right. Thanks for pointing this out! I'll make this PR draft and work on this.

**Comment by caspervonb** [comment]
I'd wait and see what the active maintainers sentiment is towards this change before putting any more effort into it 🙂

**Comment by bartlomieju** [comment]
This flag seems unnecessary since `deno fmt` and `deno lint` already run on thread pool.

**Pull request closed without merging**
