### PR TITLE
feat(unstable): FFI string arguments

### PR DESCRIPTION
**Pull request by littledivy**

### CODE REVIEW

**Comment by aapoalas** [comment]
Hmm... I'm not completely sold on this. Fast call would pass Latin-1, whereas slow call would pass UTF-8: These do not agree on all characters so the receiver would need to basically check if they receive valid UTF-8 and if not then parse the data as Latin-1.

Furthermore since this is mostly copying data, except for fast calls, then the performance in the general case is either equivalent or worse than a manual TextDecoder use, as with the manual case you can manually deduplicate copies when you know you're passing the same string over and over again.

**Comment by littledivy** [comment]
My particular use case is SQlite3 when binding TEXT values. The reciever (sqlite) in this case does not care about the encoding and will happily store/give it back as TEXT - good example of the GIGO (Garbage-In Garbage Out) rule.

And for the slow case, one fallback op to encode and call is faster than using TextEncoder#encode on the binding value again and again.

**Comment by aapoalas** [comment]
Are you sure there isn't an edge case where a Latin-1 string that is not ASCII gets read from sqlite and gets interpreted as UTF-8, leading to corrupted data?

**Comment by littledivy** [comment]
@aapoalas 

https://sqlite.org/invalidutf.html#best_effort_to_preserve_text
> Generally speaking, if you insert invalid UTF into SQLite, you will get the exact same byte sequence back out, as long as you do not ask SQLite to transform the text in any way.

**Comment by aapoalas** [comment]
> @aapoalas
> 
> https://sqlite.org/invalidutf.html#best_effort_to_preserve_text
> 
> > Generally speaking, if you insert invalid UTF into SQLite, you will get the exact same byte sequence back out, as long as you do not ask SQLite to transform the text in any way.

Yes, now when we get this Latin-1 encoded string back from sqlite, what will we do with it?

There are three possibilities that seem to be coming up now:
1. We get an ASCII string back from sqlite (or any FFI API). In this case it's safe to read it as OneByte or as UTF-8.
2. We get a UTF-8 string from it. This can be only read as UTF-8.
3. We get a non-ASCII Latin-1 string. This can be only read as OneByte.

Can we tell these three (or rather the two latter) cases apart? Sqlite will happily save both encodings and will not give us any hint on what was saved specifically, it's indeed garbage in and out. But can we actually safely use the garbage we get out?

**Pull request closed without merging**
