### PR TITLE
fix(node): Add op_node_unstable_os_uptime to allow for node interop

### PR DESCRIPTION
**Pull request by kamilogorek**
Based on work from https://github.com/denoland/deno/pull/16520

### CODE REVIEW

**Comment by kamilogorek** [comment]
> Unstable API 'Deno.osUptime'. The --unstable flag must be provided.

I'm not sure which test fails due to this tbh, as it's not clear from the logs.

**Comment by bartlomieju** [comment]
> > Unstable API 'Deno.osUptime'. The --unstable flag must be provided.
> 
> I'm not sure which test fails due to this tbh, as it's not clear from the logs.

Exit code 70 suggests that it was unstable check, but it is indeed strange there are no logs there.

**Comment by bartlomieju** [comment]
Actually logs are there, they are just interleaved with other output (because we run multiple test binaries on multiple threads). It is coming from:
```
2022-12-28T10:40:35.9736918Z Unstable API 'Deno.osUptime'. The --unstable flag must be provided.
```

**Comment by bartlomieju** [comment]
@kamilogorek it's most likely coming from these lines:
```
osUptime: __bootstrap.os.osUptime(ops.op_node_unstable_os_uptime),
```
This is directly calling `osUptime` op during bootstrapping process. I think we need to remove `__bootstrap.os.osUptime` and replace it with `__bootstrap.os.createOsUptime()` that will accept `opFn` as an argument

**Review by bartlomieju — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
