### PR TITLE
Added Code of Conduct, Bug Report template, Feature Template. Updated Pull Request Template

### PR DESCRIPTION
**Pull request by larson-carter**
As the title states.
* I created the Code of Conduct!
* I updated the Pull Request Template to be more descriptive
* I created a Bug Report template. This will help response time to issues
* I created the feature request template. This will help users be more through.

### CODE REVIEW

**Comment by anthonyhumphreys** [comment]
Hey, maybe update to the v2.0 of the contributor's covenant? Like this
https://github.com/anthonyhumphreys/edon/blob/master/.github/CODE_OF_CONDUCT.md

Fingers crossed this issue can be discussed in the open and settled properly :)

**Comment by larson-carter** [comment]
@anthonyhumphreys I'm going to wait and see what others say. I do agree v2 is better. However I'm going to wait and see what others say fits the project better. Unless you have any direct affiliation with the project?

**Comment by anthonyhumphreys** [comment]
Nah I don’t, I’m hoping to contribute in the future as it seems so promising, but been trying to push for this CoC situation to be resolved first, like I said it would be great to have a discussion in the open here on github and settle on something.

________________________________

**Comment by nayeemrmn** [comment]
See https://github.com/denoland/deno/pull/5151#issuecomment-626147299.

**Comment by anthonyhumphreys** [comment]
Not sure that’s a great approach to take, issue templates help the contributor to ensure they have done everything they need and prevents back and forth frustrations, but I guess it’s up to the core team 🤷‍♂️

________________________________

**Comment by nayeemrmn** [comment]
@anthonyhumphreys Personally I think templates are only worth it if they relay something specific to the project, like in #5151. This one's a couple steps down. It's obviously not intuitive to put generally acquired knowledge or git tutorials in every project's documentation. Not sure submitting duplicate PRs because (?) the others weren't resolved in a way one agreed with is a great approach to take 🤷‍♂️

**Comment by anthonyhumphreys** [comment]
Apologies if I wasn’t clear, I was agreeing with your original comment - i didn’t suggest generally acquired knowledge should go there, I think the things you suggested in your previous PR seem reasonable. Also agree on the duplicate PR front, perhaps a broader discussion needs to happen on these issues. I just listened to Kit Kelly discussing community focussed issues over on the JS Party podcast, sounds like some community building discussions will be taking place within the core team that should resolve these issues.

________________________________

**Comment by ry** [comment]
Thanks for the patch - but I don't like maintain all these files. I don't think it really helps anything and I'd prefer to be minimal and have less stuff in the repo.

**Comment by bnb** [comment]
@ry what would people need to do to get Deno to ship a Code of Conduct that the project will uphold its contributors to?

**Comment by larson-carter** [comment]
@ry It's quite simple to include a code of conduct. All you do is establish it (i did this in the PR) then you put it into effect. I'm still confused on why you wouldn't want a bug report, feature, and a pull request template. 

All of these are used to help you maintain the project easier?

**Comment by anthonyhumphreys** [comment]
@bnb thanks for chipping into this discussion. The more voices on this one the better. This is a new and growing community, and @ry et al. need to take the appropriate steps to foster such a community - I still say simply linking to another project's CoC is insufficient. 

I've been shouting into a void about this over here https://anthonyhumphreys.dev/IntroducingEdon/

@larson-carter makes an excellent point. Multiple contributors have now opened PRs which have been abruptly closed and quite frankly dismissed.

As discussed in the link above, I heard @shortdiv interview @kitsonk and part of that discussion involved the CoC which apparently the project core team was going to be looking into, but it seems no progress has been made on that which is really disappointing and I'm sure that some developers are reluctant to contribute or engage with the project without a CoC in place and a commitment made by the team to support and enforce this CoC.

**Pull request closed without merging**
