### PR TITLE
cleanup(ext/http): simpler http write ops

### PR DESCRIPTION
**Pull request by AaronO**
Facilitates making `op_http_write_headers` sync and thus faster (will do in follow-up, already experimented locally)

### CODE REVIEW

**Review by bartlomieju — APPROVED** [review]
LGTM, much cleaner

**Comment by lucacasonato** [comment]
@AaronO Please don't mark PRs as pure "cleanup" if they rewrite code to cause behavioral changes. Some examples:

- much more loose about invalid headers
- compresses irregardless of if `content-encoding` is already set on the response
- handles invalid UTF8 vary headers differently
- has an early return **true** inside of the `should_cache` function

At least half of this should have been caught in review.

Please revert this PR, or fix the above issues.

**Comment by AaronO** [comment]
> * compresses irregardless of if `content-encoding` is already set on the response

My bad, submitted a regression fix here https://github.com/denoland/deno/pull/14641

> much more loose about invalid headers

Could you elaborate ?

> handles invalid UTF8 vary headers differently

Not sure this is true, logic is effectively (which I believe is preserved in both cases):
```rs
vary =
  | utf8 && lowecase -> add prefix,
  | utf8 && !lowercase -> untouched,
  | _ -> "Accept-Encoding",
```

> has an early return true inside of the should_cache function when a header is invalid
I believe this behaviour is also unchanged. We're ultimately impacting the predicate of compressing based on headers, which is negatively controlled by `cache_control_no_transform`:

```rs
cache_control_prevents_compressing =
  | utf8 && Some(c) => c.no_transform,
  | utf8 && None => false,
  | !utf8 => true,
  | _ -> false,
  
headers_allow_compression = !cache_control_prevents_compressing && ...;
```

**Comment by lucacasonato** [comment]
> has an early return true inside of the should_cache function when a header is invalid

I mean this early return. If the `cache-control` header is invalid UTF-8, we compress irregardless of if `content-range` and friends are set. https://github.com/denoland/deno/pull/14552/files#diff-90dfe8e7faf01dad4a43d5f274862d01e5c6c53c07ec35ec28f6d73189b2f52fR659

> Not sure this is true, logic is effectively (which I believe is preserved in both cases):

Sorry, you're right I misread the code here.


> > much more loose about invalid headers
>
> Could you elaborate ?

I mean this `filter_map` here. We just skip over invalid header names and values now, rather than propagating the error of the header being invalid like we did previously. https://github.com/denoland/deno/pull/14552/files#diff-90dfe8e7faf01dad4a43d5f274862d01e5c6c53c07ec35ec28f6d73189b2f52fR507-R513

**Comment by AaronO** [comment]
> I mean this early return. If the `cache-control` header is invalid UTF-8, we compress irregardless of if `content-range` and friends are set. https://github.com/denoland/deno/pull/14552/files#diff-90dfe8e7faf01dad4a43d5f274862d01e5c6c53c07ec35ec28f6d73189b2f52fR659

The early return is in an inner function not the outer, will clarify these predicates in a follow-up PR so they're easier to grok

> I mean this filter_map here. We just skip over invalid header names and values now, rather than propagating the error of the header being invalid like we did previously. https://github.com/denoland/deno/pull/14552/files#diff-90dfe8e7faf01dad4a43d5f274862d01e5c6c53c07ec35ec28f6d73189b2f52fR507-R513

Discarding invalid headers could indeed be fair, but I'll revert back to erroring on invalid headers

**Pull request merged**
