### PR TITLE
feat: improve AsyncLocalStorage api

### PR DESCRIPTION
**Pull request by himself65**
Fixes: https://github.com/denoland/deno/issues/23174

Refs: https://github.com/nodejs/node/blob/9efc84a2cb32af325f06c465ba82175b67089fe0/lib/async_hooks.js#L290-L296

### CODE REVIEW

**Comment by bartlomieju** [comment]
Cool, thanks for the PR! Could you add some tests in `tests/unit_node/async_hooks_test.ts` and run `tools/format.js` script? Let me know if you need any pointers.

**Comment by himself65** [comment]
@bartlomieju please review

**Comment by himself65** [comment]
seems like a flaky

**Review by bartlomieju — APPROVED** [review]
LGTM, thank you @himself65!

**Pull request merged**
