### PR TITLE
fix(http_client): Fix Deno.createHttpClient to accept poolIdleTimeout parameter

### PR DESCRIPTION
**Pull request by raashidanwar**
## Description
Fixed the bug ***Deno.createHttpClient*** to accept `poolIdleTimeout` parameter.

## Issue
- https://github.com/denoland/deno/issues/21546

### CODE REVIEW

**Review by bartlomieju — COMMENTED** [review]
Looks good, can you add a unit test that exercises this change? They should go into `cli/tests/unit/fetch_test.ts`

**Comment by raashidanwar** [comment]
> Looks good, can you add a unit test that exercises this change? They should go into `cli/tests/unit/fetch_test.ts`

added test case

**Comment by raashidanwar** [comment]
@bartlomieju did you get a chance to look again?

**Review by bartlomieju — APPROVED** [review]
LGTM, thanks

**Review by littledivy — APPROVED** [review]
LGTM too

**Pull request merged**
