### PR TITLE
feat(ext/url): add `URLPatternList` constructor

### PR DESCRIPTION
**Pull request by lucacasonato**
This commit adds support for the `URLPatternList` interface.

See https://github.com/WICG/urlpattern/pull/166

### CODE REVIEW

**Comment by danteissaias** [comment]
Does this open the possibility of a router being included in the standard library?

**Comment by crowlKats** [comment]
@danteissaias thats completely unrelated. would already be possible

**Comment by danteissaias** [comment]
I meant does it open the door for a simple router based entirely on web standards being included but I understand it’s out of scope for this PR.

**Comment by danteissaias** [comment]
UrlPatternList makes it a much simpler task is what I’m trying to say.

**Pull request closed without merging**
