### PR TITLE
fix(cli/js/process): Fix conditional types for process sockets

### LINKED ISSUE #6270: Narrowing type guard bug for Deno.Process.stdin in v1.1.0
Consider this (contrived) example, `echo.ts`, which uses the `cat` binary to print `stdin`:

```ts
export const echo = async (data: string): Promise<void> => {
  const runOpts: Deno.RunOptions = {
    cmd: ['cat'],
    stdin: 'piped',
  };

  const p = Deno.run(runOpts);

  if (!p.stdin) throw new Error('stdin not available');
  await p.stdin.write(new TextEncoder().encode(`${data}\n`));
  p.stdin.close();

  const {success} = await p.status();
  if (!success) throw new Error('Process encountered an error');

  p.close();
}

const main = (): void => {
  const text = Deno.args.join(' ') || 'hello world';
  echo(text);
};

if (import.meta.main) main();

export default echo;
```

It compiles and runs using Deno v1.0.5:

```shell
> deno --version
deno 1.0.5
v8 8.4.300
typescript 3.9.2
> deno run --allow-run echo.ts
hello world
```

but in Deno v1.1.0, this TypeScript compilation error occurs:

```shell
> deno --version
deno 1.1.0
v8 8.4.300
typescript 3.9.2
> deno run --allow-run echo.ts
Compile file:///mnt/path/redacted/for/privacy/echo.ts
error: TS2531 [ERROR]: Object is possibly 'null'.
  await p.stdin.write(new TextEncoder().encode(`${data}\n`));
        ~~~~~~~
    at file:///mnt/path/redacted/for/privacy/echo.ts:10:9

TS2531 [ERROR]: Object is possibly 'null'.
  p.stdin.close();
  ~~~~~~~
    at file:///mnt/path/redacted/for/privacy/echo.ts:11:3

Found 2 errors.
```

I see that the type definition has changed from 1.0.5 to 1.1.0:

[1.0.5 `lib.deno.d.ts`](https://github.com/denoland/deno/releases/download/v1.0.5/lib.deno.d.ts#L1744):
```ts
export class Process {
    readonly rid: number;
    readonly pid: number;
    readonly stdin?: Writer & Closer;
```

[1.1.0 `lib.deno.d.ts`](https://github.com/denoland/deno/releases/download/v1.1.0/lib.deno.d.ts#L1782):
```ts
export class Process<T extends RunOptions = RunOptions> {
    readonly rid: number;
    readonly pid: number;
    readonly stdin: T["stdin"] extends "piped" ? Writer & Closer : null;
```

### PR DESCRIPTION
**Pull request by nayeemrmn**
Fixes #6270.

### CODE REVIEW

**Comment by jsejcksn** [comment]
I'm don't think this is a fix yet.

@nayeemrmn ([comment](https://github.com/denoland/deno/issues/6270#issuecomment-643513576)):
> I think I've misused the ternary in the type expression. I was under the impression that if the predicate is generically unknown it would be a union of the LHS and RHS. I guess it's just the RHS. Fix coming.

I don't think the conditional type guard is ever going to have enough information (to yield the LHS) when using the assertion `Deno.RunOptions` on the options... even then, it still yields the RHS. The only way to get the LHS is to drop 
`Deno.RunOptions` and use the `as const` assertion on `stdin`/`stdout`/`stderr`.

If you want to experiment, [here's a minimal reproduction at the TypeScript playground](https://www.typescriptlang.org/play/#code/HYQwtgpgzgDiDGEAEARCwD2SDeBYAUEkUhAB4wYBOALkgJbDUSUBmCyASgK7ADyM1OhmBQcBYhKTwwAEwBcSKNUoMA5gG0AugG5xkovADuMgPwKlK4Kt2F9JYADczY2-vUBrCAE9zytZt9Laz19AF8bO0VqGQwuamcAIgYAC2Y6agSkAB8kBJg6GAgZTJyE4C4AGwqSpHKwACNmCLslGWZKRJS0jOzc-MLi3rLK6t66xspm-VaGTuBUlR7S-qKa4aqa8aaQpFCCHbIKGiRqL0KkAAVKDEQoKABlahBqLlEAXh2JHLxXSMUueC3KAKZRcCBTP7wDBtBQABghkSgdFUoAqzh4bRYDCKCOIe1+Xxcf2IUABQIUbAqUHBnzsUJhtS4DW2BJayNRzi2k1pRHC+1+hyotAYTFY7CQHAgIDalCJdkoUpkAAoYAoAKoigAcAEFKJQQF4AJQKK4YMB0akAHi5YxGAD4IfiDuQhfRGMw2IgkAB1RbMOX6Qx+lXqrW6-VGk3Xc1WrkOnZOgUu44ij3igDCFQw1NlP0i8Cz1KVxqQDgwdBkjv5EkFxzaBZACqkFRAd0u1yBloAKiRSExgDJRNw+AIhCIkG8JTx+IJhFA7QHJArpcIKl4kCp5IzmdzWURlzFgGukPkt1zcfvFav1zNgAou+oEreEppe-3B30CqskCYfX7ZQAZEgmbZv6ChKr66T+kBIE5oatpVBeG5XkeN7RLE1D3o+rQYS+b7oB+eRfoMv6StK0HAYWYFIBB-5IDBVGUPBOTlIhPLISuqFRDKlBYU+0TtHhZDvqIREDJkpGKhRsHUbRUGAZRoFMQhFRIUozyvMWUZmhaECWqaQKPBp85IRhMBxFp7Y6VaGqMDqeoGvGe7ce0vBxOZ1CWaaMZ6bZ1D2RGTn5lRlllhWSHuHQVRKkiKIYAoXIlmFlYJtWxC1rQ9Ytk2LA8PAs7ABuPDdvhA5DtOo5zhOU4jgV85KhgAj3iWBnQFA3ZOYmGVSHOtAQPAyRYJOrZeMA8A0TIzwgIEagtdGumWslC5vAuebEFCIi0JQFXUMCqDoBgAB0w4zmO7yLhI0hbuoADk8DPDdmgADTsbeCg3SsMg3S9vx8vgOwbUoJ7VWgmCHdtwBKhDM5QIaNgA71JzJBa9yDZUMi8KhABCEDapBoragOMmypOMCHbe8O-HQLA0QAhGTt7wdQyTXIYtQQGzACiepUEqN23rUGC0CADggFFID1BUEA3XDOwgIYYu0Az0QMIdQZQUqwAc0gXbCZzY3QswxaHeg9IQEqAAGAAk2CTU8oQADrABbhqy78ysyKrBagcWlOXYj2CkoCbWhNV8uKye5NPC8UC+zs1N00HQJMyzGBs1rXM85QfOtW2puxO6CoyEgICFe0VAy37xBk97RZu-iQA), with the types taken from `lib.deno.d.ts` + your changes in this PR. Look at line 61, specifically:

```ts
const thisShouldOnlyBeAWriterAndCloser = p.stdin;
```

**Comment by nayeemrmn** [comment]
> I don't think the conditional type guard is ever going to have enough information (to yield the LHS) when using the assertion `Deno.RunOptions` on the options... even then, it still yields the RHS. The only way to get the LHS is to drop

@jsejcksn Try inlining `runOpts`. You won't need `as const` either. The type inference addresses that use case. This is actually dog-fooded is a couple of places in `std`, wouldn't have landed if it didn't do anything :)

When storing the options or process objects in typed variables, you have to add extra information to the type annotations for it to carry: https://github.com/denoland/deno/blob/2e830f80ea1729a9f755e7002c57ba553d8a9bb8/std/http/racing_server_test.ts#L5 ^ that's how you formally represent the stronger types.

**Comment by jsejcksn** [comment]
> you have to add extra information to the type annotations for it to carry

@nayeemrmn Why's that? Why isn't the `RunOptions` annotation (combined with the literal string value of `"piped"`) enough to narrow `"inherit" | "piped" | "null" | number` to `"piped"`?

**Comment by nayeemrmn** [comment]
> Why's that? Why isn't the `RunOptions` annotation (combined with the literal string value of `"piped"`) enough to narrow `"inherit" | "piped" | "null" | number` to `"piped"`?

Because the type annotation overrides anything more specific? 🤷‍♂️ TS stuff.

**Pull request merged**
