### PR TITLE
fix(coverage): Exclude comment lines from coverage reports

### LINKED ISSUE #25938: Exclude comment lines from coverage reports
Version: Deno v1.46.3, v2.0.0

I really appreciate this amazing product. Thank you!

I'm unsure if I should call it a bug, but I don't think it's a feature request, so I'm filing it under the bug label for convenience.

### Exclude comment lines from coverage reports

In the report generated by `deno coverage`, comments are included in the line coverage, but I think it would be better to exclude them. There are two reasons for this.

* In the reports of many other major tools such as "gcov" and "vitest", comment lines are not included in line coverage
* If comment lines are included in line coverage, the coverage rate will change when comments are added or deleted, which is undesirable behavior

### PR DESCRIPTION
**Pull request by usualoma**
fixes #25938

I think comments should be excluded from line coverage.

### current result

html-report-unpached

### patched result

html-report-pached

### CODE REVIEW

**Comment by bartlomieju** [comment]
Thanks for the PR @usualoma, it looks good at first glance. We're a bit swamped with Deno 2.0 release ATM, so it might have a couple weeks before we merge it. Thanks!

**Comment by bartlomieju** [comment]
Note to self: compare how other tools like `nyc` or `istanbul` do that. Are the comment lines excluded from the total line count or are they always counted as covered.

**Comment by kt3k** [comment]
Tested `istanbul` (via `jest`). The comment lines seem excluded from total line count.

Screenshot 2024-10-28 at 19 39 18

**Review by kt3k — APPROVED** [review]
LGTM

**Pull request merged**
