### PR TITLE
feat(jupyter): Await return from `Jupyter.display`

### PR DESCRIPTION
**Pull request by manzt**
Allows `Jupyter.display` to return a promise.

Silly example:

```javascript
class WikiPage {
    constructor(public name) {}
    async [Symbol.for("Jupyter.display")]() {
        let response = await fetch("https://en.wikipedia.org/wiki/" + this.name);
        return { "text/html": await response.text() }
    }
}

new WikiPage("Deno_(software)")
```

image

### CODE REVIEW

**Review by bartlomieju — COMMENTED** [review]
Cool, can you update the integration test notebook to showcase that async functions are supported as well? You add add a promise that resolves after 100ms and only then provides an output.

**Review by rgbkrk — APPROVED** [review]

**Comment by manzt** [comment]
> Cool, can you update the integration test notebook to showcase that async functions are supported as well? You add add a promise that resolves after 100ms and only then provides an output.

Done!

**Review by bartlomieju — APPROVED** [review]
LGTM, thank you @manzt!

**Comment by rgbkrk** [comment]
Thanks @manzt and @bartlomieju!

I made a `display` release that adapts to async displayables. https://github.com/rgbkrk/display.js/releases/tag/v1.1.0

**Pull request merged**
