### PR TITLE
test(ext/node): added assertion errors test

### PR DESCRIPTION
**Pull request by ktfth**
added assertion errors test to node compatible unit test

### CODE REVIEW

**Comment by ktfth** [comment]
@kt3k Have an equilivalent to file:
https://github.com/denoland/deno_std/blob/e90ede3e0f2ee4cf244840119d96eef9dd97d793/node/assertion_error_test.ts#L14C31-L14C31

Is good to know because the need to port dependants. You can help to discover a better solution for this case?

**Comment by ktfth** [comment]
@kt3k ready for review

**Comment by kt3k** [comment]
AssertionError class is available from `node:assert` module (`import { AssertionError } from "node:assert"`). Please use that version. Porting non-test code to `cli/tests/unit_node/` doesn't make sense. Also copying source code under `node/internal/` and `node/internal_binding` doesn't make much sense. Please revert those changes (These files are already ported to `ext/node/polyfills` and should be accessible somehow via `node:` specifier).

Regarding the APIs `copyError`, `createErrDiff`, `inspectValue`, these are not public APIs of Node.js and not available from `node:assert`. I'd suggest we should remove test cases of those.

**Comment by ktfth** [comment]
@kt3k all done for a new review, thank you so much

**Review by kt3k — APPROVED** [review]
@ktfth LGTM. Thanks!

**Pull request merged**
