### PR TITLE
Fix: Deno.args typings

### PR DESCRIPTION
**Pull request by scf4**
`Deno.args` is always an immutable string array ~~(which may be empty)~~, but the typings don't seem to reflect this. E.g., the following line passes compile-time checks but causes a runtime error:

```typescript
Deno.args.push("xyz"); 
// Compile file:///[...]/test.ts
// error: Uncaught TypeError: Cannot add property 0, object is not extensible
```

This PR changes `Deno.args` from `string[]` to `readonly string[]`.

Thanks!

**Update: removed undefined index issue and updated PR accordingly**

```typescript
// Deno.args[0].split("");
// Compile file:///[...]/test.ts
// error: Uncaught TypeError: Cannot read property 'split' of undefined
```

### CODE REVIEW

**Comment by nayeemrmn** [comment]
This doesn't make sense. It's an array of `string`s, how is the `string[]` type not applicable? You're pointing out a flaw in TS array semantics.

As for `readonly`, every binding in the `Deno` namespace is readonly. It's got nothing to do with the array being immutable. Should we add `readonly` to every property?

**Comment by SyrupThinker** [comment]
@scf4 Can you provide an example for which an entry is undefined?

**Comment by SyrupThinker** [comment]
@nayeemrmn The `readonly` marker in this position rightfully marks the array as immutable. It is equivalent to `ReadonlyArray<...>`.

**Comment by scf4** [comment]
Hi Nayeem, thanks for the quick response.

I’m not sure I follow. It’s not _always_ an array of strings, i.e., if no arguments are provided. 

And I’m not sure of the internals, but as an end user I would expect modifying the args array (however bad an idea) to cause a compile time error, so yes. Why not?

@SyrupThinker If you copy/paste the second line above into a test.ts file and run `deno run test.ts` you’ll get this error.

**Comment by nayeemrmn** [comment]
> I’m not sure I follow. It’s not _always_ an array of strings, i.e., if no arguments are provided.

That's an empty array of strings.

**Comment by scf4** [comment]
> > I’m not sure I follow. It’s not _always_ an array of strings, i.e., if no arguments are provided.
> 
> That's an empty array of strings.

As far as V8 is concerned it’s an immutable empty array.

**Comment by SyrupThinker** [comment]
@scf4 Because the array access is out of bounds. The type only reflects the arrays contents within its bounds.

**Comment by nayeemrmn** [comment]
@scf4 You're not understanding. When you get at an arbitrary index of an array, there is always the possibility of getting undefined. When can the `string[]` type ever be used, then?

**Comment by scf4** [comment]
I see, I guess this may be related to https://github.com/Microsoft/TypeScript/issues/13778

**Comment by scf4** [comment]
Thanks guys, I've updated the PR to use `readonly string[]`.

**Comment by scf4** [comment]
> @scf4 You're not understanding. When you get at an arbitrary index of an array, there is always the possibility of getting undefined. When can the `string[]` type ever be used, then?

Is there a reason Deno.args couldn't return null if no args are provided, for better type safety?

**Comment by nayeemrmn** [comment]
> Is there a reason Deno.args couldn't return null if no args are provided, for better type safety?

That's not more type safe. It's less logical and less convenient. If the args are given in an array of strings, and no args are given, I would expect that to be an empty array. You would set it to `null` if args were not applicable for some reason.

**Comment by scf4** [comment]
> > Is there a reason Deno.args couldn't return null if no args are provided, for better type safety?
>
> @nayeemrmn : That's not more type safe. It's less logical and less convenient. If the args are given in an array of strings, and no args are given, I would expect that to be an empty array. You would set it to `null` if args were not applicable for some reason. 

You're right. But re: type safety, the possibility of `null` would require something like `let filePath = Deno.args?.[0];`, reinforcing the notion that args may not be provided. 

Currently, `let filePath = Deno.args[0]` will infer `filePath` as a guaranteed string. However I understand it's something of a TypeScript issue and would be a breaking change for Deno — plus it's consistent with Node's `process.argv`) so yeah, scratch that.

---

> @caspervonb: This is a breaking change to a stable interface so if we want to make this change, it would have to wait until the next major release.

Disregard the undefined args conversation, sorry. The current PR simply catches a runtime error at compile time.

**Comment by caspervonb** [comment]
> Disregard the undefined args conversation, sorry. The current PR simply catches a runtime error at compile time.

Yep, I think it shows the semantics of Deno.args more accurately but as the breaking tests show it is a breaking change as the two types are not interchangeable.

Just pointing it out so it doesn't accidentally land on the next minor because it looks like a trivial change.

**Comment by bartlomieju** [comment]
> > Disregard the undefined args conversation, sorry. The current PR simply catches a runtime error at compile time.
> 
> Yep, I think it shows the semantics of Deno.args more accurately but as the breaking tests show it is a breaking change as the two types are not interchangeable.
> 
> Just pointing it out so it doesn't accidentally land on the next minor because it looks like a trivial change.

If this breaks types on `Deno` namespace, I don't think we could land it before 2.0. @ry thoughts?

**Comment by ry** [comment]
I mean, I don't think we need to be that strict. I doubt anyone is manipulating `Deno.args` anyway. Let's just land it.

**Comment by caspervonb** [comment]
See https://www.typescriptlang.org/play?#code/MYewdgzgLgBAIgUzCGAuGBvAUDXMCGATgOYTqEL4Am4ANgJ4zSECWYxA2gLoDcWAvjAC8mHHiKl03ADQC+WBAA8ADiEKwAZgFcwwKC3Aw20fGH34oCABQSyTKK3bcAlKP5YsxqKfOWriZAA6W2ceIA

**Comment by nayeemrmn** [comment]
Very good catch by @caspervonb. Not only is this a _realistically_ breaking change, the proposed definition is a lot less convenient. People reasonably want to just use `string[]` for array arg types whether they intend on mutating it or not, and `readonly string[]` is not assignable to that.

**Comment by nayeemrmn** [comment]
That's why this PR is red 😅 it breaks any usage of `std/flags/mod.ts`.

**Comment by bartlomieju** [comment]
> See https://www.typescriptlang.org/play?#code/MYewdgzgLgBAIgUzCGAuGBvAUDXMCGATgOYTqEL4Am4ANgJ4zSECWYxA2gLoDcWAvjAC8mHHiKl03ADQC+WBAA8ADiEKwAZgFcwwKC3Aw20fGH34oCABQSyTKK3bcAlKP5YsxqKfOWriZAA6W2ceIA

Well that makes it non-landable. @scf4 thank you for the effort, but we'll have to keep current types not to break user code. Closing without merge.

**Comment by scf4** [comment]
That's fair, thanks!

**Pull request closed without merging**
