### PR TITLE
Filesystem4

### PR DESCRIPTION
**Pull request by dubiousjim**
op_fxxx operations on open rid/fds for #4017 (PR 4 of 4).

This is based upon PRs #4192, #4193, and #4195.

### CODE REVIEW

**Comment by dubiousjim** [comment]
I tried to split the PRs into four segments of related commits (Filesystem1-4), but I wasn't sure how to generate PRs in Github that were premised on other PRs pending review. What happened is that now Filesystem4 includes all the previous 3 PRs, and so on. I guess that'll make reviewing harder; sorry! (Or you could just look at Filesystem4 and ignore the other 3, but it includes a lot of stuff: 30 commits.)

**Comment by hayd** [comment]
> but it includes a lot of stuff

This should probably be 8+ PRs that don't depend on each other and are much more focused. IMO this PR is too large and there's too many independent things going on.

E.g. Option->Options, readDir -> readdir, fs -> tokio_fs, improve debug calls, add perms, should **each** be their own PRs (and not depend on any unrelated commits).

_(You want to create a new branch off of master for each PR and cherry-pick those commits you want to include.)_

**Comment by dubiousjim** [comment]
Yeah, I appreciate that. I'm sorry it's grown so big. But after a couple of days rebasing this stuff, and limits to the amount of time I can give to it, I thought it'd be best to put it out there for other eyes to have a look at it now, rather than wait even longer until I could figure out how to parcel it better. Most of this stuff was ready some weeks ago, but it got hard to keep up with advances with denoland/master.

The earlier commits in the sequence (Option->Options, & so on) would indeed be easy to separate off. From the middle of the sequence on, though, it becomes a lot harder to make them stand alone. I was hoping someone could review the sequence as is, then based on their feedback I'd pick off smaller pieces to push one at a time. (And with the later pushes relying on earlier pushes already being pulled into master.)

**Comment by ecyrbe** [comment]
hi @dubiousjim , this is a lot of work, so first things first, thanks.

Now i do agree that you should try to make things as separate small PR.

For exemple, each new feature i do that only add one function to ops is a PR because it add already a lot of stuff to a lot of files.
for exemple as i'm doing std/node/os this mean i'm preparing around 16 PR.
i do no refactoring in these PR, and they are already individually long to review.

It only takes discipline to create a branch for everything you do that are not related. once you are used to do it, you'll never go back.

**Comment by dubiousjim** [comment]
Thanks, I did close these big PRs and am breaking things into smaller pieces. I had filtered all of the non-semantic changes to the top of the queue though (rewording comments, except where it didn't make sense until the new feature was added, renaming internal variables, etc.). And when I tried to make smaller standalone PRs, I kept finding them too difficult to rebase off of (and then remerge again onto) those changes. So I'm first proposing #4205. That touches a lot of files, but none of the changes it contains should be substantial. Once that (or some descendent of it) gets merged into master, I'll push the rest of the work out as smaller PRs, as focused and standalone as I can make them. (There are some other blockers in the sequence, too, though, that later PRs will have to wait on, like renaming mode->perm, and filename->path.)

**Pull request closed without merging**
