### PR TITLE
Turn on v8_postmortem_support

### PR DESCRIPTION
**Pull request by ry**
So we can use https://github.com/nodejs/llnode/

### CODE REVIEW

**Comment by ry** [comment]
```
./gen/third_party/v8/debug-support.cc:14:21: error: using namespace directive in global context in header [-Werror,-Wheader-hygiene]
using namespace v8::internal;
                    ^
```
@indutny says I think they just forgot to remove the namespace from generated code. `debug-support.cc` is generated by `tools/gen-postmortem-metadata.py`

**Comment by ry** [comment]
https://bugs.chromium.org/p/v8/issues/detail?id=8838

**Comment by indutny** [comment]
Yep, pending bug report: https://bugs.chromium.org/p/v8/issues/detail?id=8838 cc @hashseed

**Comment by hashseed** [comment]
Not sure what the issue is, but enabling `v8_postmortem_support` seems to work well [here](https://chromium.googlesource.com/v8/node-ci/+/master/.gn#66). We also build Node.js with `--build-v8-with-gn` and have `v8_postmortem_support` enabled and that seems to work fine too.

**Comment by ry** [comment]
depends on https://github.com/denoland/deno/pull/1767 which has a fix for the above problem

**Comment by indutny** [comment]
@hashseed might have been broken because of jumbo builds.

**Comment by hashseed** [comment]
Yeah I realized that too now. Anyways, a fix has already landed?

**Comment by indutny** [comment]
I believe so! Thank you so much for looking into, @hashseed

**Pull request merged**
