### PR TITLE
 fix(cli) fix close websocket with code is not working (recreated)

### PR DESCRIPTION
**Pull request by Preta-Crowz**
original pr : #8611 
original pr has conflict with #8640 and that was merged first.
so I created this pull request again.

### CODE REVIEW

**Comment by bartlomieju** [comment]
@crowlKats please take a look

**Review by crowlKats — APPROVED** [review]
LGTM

**Review by hwahyang1 — APPROVED** [review]

**Comment by bartlomieju** [comment]
@Preta-Crowz @crowlKats can we get some test case for this PR?

**Comment by Preta-Crowz** [comment]
@bartlomieju 
sorry for dirty code
here's test code
```js
const cases = [
    1000, // 1000, valid
    3000, // 3000, valid
    5000, // 5000, invalid
    3141, // in range, valid
    1024, // lower than 3000 and not 1000, invalid
    6000  // higher than 5000 and not 1000, invalid
]

for (const code of cases) {
    console.log(code + " on old code : " +
        ((code && (code !== 1000 && !(3000 <= code > 5000))) ? "\u001b[31minvalid" : "\u001b[32mvalid") + "\u001b[0m\t" +
        code + " on new code : " +
        ((code && !(code === 1000 || (3000 <= code && code < 5000))) ? "\u001b[31minvalid" : "\u001b[32mvalid") + "\u001b[0m"
    );
}
```

output
```
1000 on old code : valid        1000 on new code : valid
3000 on old code : invalid      3000 on new code : valid
5000 on old code : invalid      5000 on new code : invalid
3141 on old code : invalid      3141 on new code : valid
1024 on old code : invalid      1024 on new code : invalid
6000 on old code : invalid      6000 on new code : invalid
```

**Comment by Preta-Crowz** [comment]
colored image of output
image

**Comment by Preta-Crowz** [comment]
I. Hate. Conflicts.

**Comment by Skillz4Killz** [comment]
Any ETA on this?

**Comment by gateaubleu** [comment]
ETA on this ? 

Thanks in advance

**Comment by crowlKats** [comment]
Once conflicts are resolved and tests are provided

**Comment by gateaubleu** [comment]
> Once conflicts are resolved and tests are provided

Yes I know, but I'm talking to author
If he not fix this, I'm gonna make my own PR about this

Have a good day

**Comment by Preta-Crowz** [comment]
I already made this pr once and someone moved files to other folders and I got conflicts. Then I recreated it. I'll fix it soon. Also, changed code was tested.

P.S. I'm not he/him. I'm she/her.

**Comment by crowlKats** [comment]
> Also, changed code was tested.

We need actual tests. Look at `cli/tests/websocket_test.ts`

**Review by kt3k — APPROVED** [review]
LGTM

**Comment by Preta-Crowz** [comment]
merged main to patch once because file was moved

**Comment by kt3k** [comment]
@Preta-Crowz Thank you for your fix!

Note: we can add test cases for this fix later. It's tracked in #9001.

**Pull request merged**
