### PR TITLE
[WIP] - dialTLS

### PR DESCRIPTION
**Pull request by jorsi**
I would like to write some test cases for this, however I'm pretty lost as to where to start. I looked at dial for TCP, but it uses the listen() api. Another idea would be some sort of python server to dialTLS to.

Let me know what you think, and any future tasks needing to be done.

Thanks.

### CODE REVIEW

**Comment by jorsi** [comment]
Not sure what test is failing in AppVeyor. I imagine it has something to do with this:

Summary for <no permissions>
undefined

But there doesn't seem to be any <no permissions> tests that failed.

**Comment by ry** [comment]
@jorsi Any luck with testing? I'd love to land this but we need some way to test it...

**Comment by jorsi** [comment]
Hey Ryan,

I made a python tls server in the same style as http_server.py which I’ve been trying to get working for the past week, but unfortunately I can’t seem to figure out why my machine actively refuses the connection when testing it from a deno script. TcpStream::connect throws the error and I am lost as to what is causing it. 



My windows firewall is off, powershell tcp-connection command confirms the tcp socket is being listened to on :5000 :p.

I can push it up to my branch as-is later this evening and perhaps you can take a look at it?

Jon Orsi

**Comment by ry** [comment]
> I can push it up to my branch as-is later this evening and perhaps you can take a look at it?

Yes, please

**Comment by jorsi** [comment]
I can't seem to get past the windows os error (error code 10061: No connection could be made because the target machine actively refused it). 

I've tried disabling my firewall settings, all anti-virus features; alas, no avail. I don't think it has anything to do with deno, probably just a bad setup on my machine. Very frustrating.

**Comment by jorsi** [comment]
Did you get a chance to look at the python script? I hit a roadblock and got busy with work, but plan on taking another go at it next week when I have time. Also will try to put in more of tls options that The dial tls for Go has as well. 

Jon Orsi

**Comment by ry** [comment]
Not yet - very sorry - soon.

**Comment by ry** [comment]
@jorsi Adding a test to this is still on my TODO. I've rebased and squashed the patch.

**Comment by jorsi** [comment]
Been out of commission for awhile since my laptop died on me. Just got a new macbook and started to update to the new changes made. Hopefully will make progress on these tests with my new setup.

**Comment by jorsi** [comment]
I think this is about as far as I can go on this one. I don't seem to have enough knowledge about ssl/tls and certificates to get this working properly.

I've gotten the build to actually connect to the tls_server now, however there is an issue with self-signed certificates that I can't seem to overcome.

Screen Shot 2019-07-27 at 10 50 25 PM

Other things that I noticed while debugging this that seemed to cause errors:
- when using localhost as a host (i.e. 'localhost:4443'), resolve_addr() returns an ipv6 address, which the python http server as is can't listen on easily
- when using an empty host/part string (i.e. ':4443'), the tokiorustls DNSNameRef can't verify a domain name, so I ended up replacing an empty host string with 'localhost' as a fix

**Comment by ry** [comment]
closed in favor of https://github.com/denoland/deno/pull/2894

**Pull request closed without merging**
