### PR TITLE
Remove exact version constraint from libc

### PR DESCRIPTION
**Pull request by cd-work**
As a system dependency, libc can only be used with a single version in the dependency graph. As such, restricting it to a single fixed version will prevent dependents from specifying a higher version and make deno impossible to use should they require it.

---

I've run into this issue when building with a dependent that has a version constraint of `0.2.135`. I could have just bumped the libc version to the latest available version, but since I didn't see any reason in the git history for why this was explicitly locked down to a single version I assume it was just a mistake.

### CODE REVIEW

**Comment by cd-work** [comment]
CI failure is unrelated to the patch as far as I can tell.

**Review by dsherret — APPROVED** [review]
LGTM. We pin all versions in the cli to reduce the chance of being bitten by cargo publish patch version breakage, but now that this has moved to the workspace that doesn't make as much sense. We might want to pin this versions in the CLI crate only in the future if it becomes a problem again.

**Comment by cd-work** [comment]
I feel like a lockfile should mostly help with that if that's a common issue. That said, there's pretty much no scenario where I would recommend pinning system libs because while in this case the issue was for consumers of deno, it could easily happen the other way around. All it takes is one dependency that pulls libc to define a higher version than what deno defines.

I also think that with libc the chances of patch versions breaking stuff are rather low. So that should probably help out too.

That said, since I'm personally not using `cli` directly it doesn't really matter to me, just my 2 cents.

**Comment by dsherret** [comment]
> I feel like a lockfile should mostly help with that if that's a common issue.

cargo publish ignores the lockfile. It's bit us so many times.

**Pull request merged**
