### PR TITLE
docs(cli/dts): fix `Deno.createHttpClient` example

### PR DESCRIPTION
**Pull request by caspervonb**

### CODE REVIEW

**Review by kt3k — APPROVED** [review]
Thanks! LGTM

**Comment by kt3k** [comment]
BTW this kind of example probably won't pass doc testing in an usual way, but it still 'works' as an example... Should we have some special control about this kind examples?

**Comment by caspervonb** [comment]
> BTW this kind of example probably won't pass doc testing in an usual way, but it still 'works' as an example... Should we have some special control about this kind examples?

I will add `no-run` when we add running again, mirroring `deno test --no-run` so that's the first step for examples that are more hassle than it's worth to run.

**Comment by caspervonb** [comment]
Oh and client/server dependencies can be handled with hidden lines.

```
# const server = // ...;
const client = // ...;
```

**Pull request merged**
