### PR TITLE
perf(ext/web): improve performance of timers

### PR DESCRIPTION
**Pull request by littledivy**
Implement lazy scheduling and avoid massive GC pressure from promises

Fixes https://github.com/denoland/deno/issues/20356

### CODE REVIEW

**Comment by josephrocca** [comment]
Any chance this will merge soon?

**Comment by josephrocca** [comment]
@bartlomieju Sorry for the ping - I'm wondering if you have any (super) rough ETA on this?

**Comment by bartlomieju** [comment]
Hi @josephrocca, sorry for a slow response. Unfortunately no ETA for this yet, but I want to get it done this month.

**Comment by josephrocca** [comment]
Looking forward to this! Just to confirm, is part of the goal of this pull request improve performance here?

image

Or is this pull request just for the GC pressure, and improving the above would require further work?

**Comment by bartlomieju** [comment]
It's both to lower GC pressure and improve performance in that critical section.

**Comment by josephrocca** [comment]
Apologies again and please know that I 100% understand if there's unlikely to be any progress on this any time soon, or if it's simply too hard to put any estimate on this, but I'm just wondering if there is an updated (rough) ETA? Please completely ignore this comment if there are no updates at this time.

(Also, if Deno has an Algora.io or similar, I'd be more than happy to chip in $1000 in case it motivates a community member to spend some weekend time on this.)

**Comment by mmastrac** [comment]
We are definitely getting closer but no ETA at this time. We may be able to land some timer improvements behind a flag earlier (though not all deno modes would be supported -- eg: tests would probably be broken).

**Comment by littledivy** [comment]
Closing. Matt's work landed in https://github.com/denoland/deno/pull/22569

**Pull request closed without merging**
