### PR TITLE
fix(ext/timers): create primordial `eval`

### PR DESCRIPTION
**Pull request by Phosra**
Includes `eval` in primordials; this was needed to prevent user modification of timers execution.
Alternatively it could've used `Deno.core.evalContext`?

### CODE REVIEW

**Review by ry — COMMENTED** [review]
could you add a test?

**Comment by Phosra** [comment]
@ry May you review this again?

**Comment by bartlomieju** [comment]
@Phosra any chance you could update `prefer-primordials` rule in `deno_lint`, so we are guarded against accidental mistakes of using `eval` from a global scope?

**Comment by Phosra** [comment]
> @Phosra any chance you could update `prefer-primordials` rule in `deno_lint`, so we are guarded against accidental mistakes of using `eval` from a global scope?

> @Phosra any chance you could update `prefer-primordials` rule in `deno_lint`, so we are guarded against accidental mistakes of using `eval` from a global scope?

I opened an issue about it there about a week ago: https://github.com/denoland/deno_lint/issues/1062.
I wasn't certain how rules such as `Set` -> `primordials.SafeSet` were handled, so I held off, but sure - I can make an attempt anyways.

**Review by bartlomieju — APPROVED** [review]
LGTM, thank you @Phosra, nice fix

**Comment by Phosra** [comment]
Checks pass, this should be clear to merge.

**Pull request merged**
