### PR TITLE
chore(ci): update windows runners to 2022

### PR DESCRIPTION
**Pull request by GJZwiers**
The 2022 runners are the default for GitHub Actions now.

### CODE REVIEW

**Comment by bartlomieju** [comment]
Thanks, I'll land it after cutting the next patch release.

**Comment by iuioiua** [comment]
I believe `ubuntu-22.04-xl` hasn't yet been released as a GitHub runner. Hence the failures.

**Comment by GJZwiers** [comment]
Should I close this PR for now?

**Comment by iuioiua** [comment]
Perhaps just update windows?

**Comment by bartlomieju** [comment]
Thanks, I included your changes in https://github.com/denoland/deno/pull/17358, gonna close this one.

**Pull request closed without merging**
