### PR TITLE
fix(ext/node): support private key export in JWK format

### PR DESCRIPTION
**Pull request by bartlomieju**
Closes https://github.com/denoland/deno/issues/26643

### CODE REVIEW

**Comment by codegod100** [comment]
waiting on this so I can use node atproto oauth lib with deno

**Comment by technoY2K** [comment]
Bumping this, I am also blocked from using atproto oauth in deno. Is there a work-around while we wait for this PR?

**Review by littledivy — APPROVED** [review]
LGTM

**Comment by technoY2K** [comment]
Nice! Thank you @bartlomieju and @littledivy 

Not 100% sure how this works from here. Now that its merged into main, do we need to wait for a release and then update deno?

**Comment by littledivy** [comment]
Yep, you can try it out now using canary builds (`deno upgrade --canary`) or wait for a patch release.

**Comment by technoY2K** [comment]
> Yep, you can try it out now using canary builds (`deno upgrade --canary`) or wait for a patch release.

I will try that, thx!

**Pull request merged**
