### PR TITLE
docs(readme): Update readme to include MacPorts install

### PR DESCRIPTION
**Pull request by micziz**
This PR changes readme.md to include a option using MacPorts. Deno_install includes MacPorts, and since scoop and chocolatey are included, MacPorts should be included too.

### CODE REVIEW

**Comment by micziz** [comment]
There are no issues related to this. Is this a problem? Thx

**Review by littledivy — COMMENTED** [review]
> See [deno_install](https://github.com/denoland/deno_install/blob/master/README.md) and [releases](https://github.com/denoland/deno/releases) for other options.

MacPorts is already listed in deno_install's readme https://github.com/denoland/deno_install/blob/master/README.md

**Comment by micziz** [comment]
Yes, but it cloud be listed in the main readme. Not to be rude or anything, but a lot of people use MacPorts over brew.

**Comment by littledivy** [comment]
The README just lists some of the ways in no particular order of preference. We can't list every option here.

Screenshot 2022-03-18 at 1 23 38 PM

For other options, people are redirected to deno_install's README - any new installation methods should be added there. So respectfully closing.

**Comment by micziz** [comment]
Ok! Completely understand it!

**Pull request closed without merging**
