### PR TITLE
feat(runtime): allow URL for permissions

### LINKED ISSUE #11036: Deno.permissions APIs should accept URLs where appropriate
Currently `PermissionDescriptor`s accept only strings as paths.

As suggested in https://github.com/denoland/deno/issues/11035, we should add support for URLs where appropriate, in line with recent changes APIs such as:
- Deno.chdir
- Deno.realPath
- Deno.realPathSync
- Deno.rename
- Deno.renameSync
- Deno.symlink
- Deno.symlinkSync
- Deno.utime
- Deno.utimeSync

So this should work:
```ts
const url = new URL("some/path", import.meta.main);
const status = await Deno.permissions.query({ name: "read", path: url });
```

### PR DESCRIPTION
**Pull request by crowlKats**
Closes #11036
not only for `Deno.permissions`, but worker & test permissions as well.

### CODE REVIEW

**Comment by bartlomieju** [comment]
Thanks @crowlKats this is very useful, could add some tests that exercise this test? After that we're good to land.

**Review by bartlomieju — APPROVED** [review]
LGTM, thanks Leo

**Comment by lucacasonato** [comment]
I am not in favor for having this for net permissions as it would impede our ability to add full URL network permissions in the allow list down the line.

**Comment by bartlomieju** [comment]
> I am not in favor for having this for net permissions as it would impede our ability to add full URL network permissions in the allow list down the line.

How does that conflict with accepting URLs in runtime APIs?

**Pull request merged**
