### PR TITLE
fix: source maps in inspector

### LINKED ISSUE #4501: inspector should support source maps

### PR DESCRIPTION
**Pull request by bartlomieju**
This commit fixes problems with source maps in Chrome Devtools
by substituting source map URL generated by TS compiler with
actual file URL pointing to DENO_DIR.

Dummy value of "source_map_url" has been removed from
"ScriptOrigin".

Also fixes lock file which used compiled source code to generate
lock hash; it now uses source code of the file that is 
being compiled.

Fixes #4501

### CODE REVIEW

**Comment by ry** [comment]
Nice work! It would be very cool to get an integration test...

**Comment by piscisaureus** [comment]
It's good, but oddly it shows all source files twice for me:

image

**Comment by piscisaureus** [comment]
Edit: ah, so the "other" .ts file is actually the typescript output.

**Comment by bartlomieju** [comment]
@piscisaureus I observed similar problem that the "source file" has the same presentation as source map. I'm not really sure what's causes it...

**Comment by piscisaureus** [comment]
It seems that chrome doesn't really load/apply the source map until it breaks inside the transpiled js file. That might be something that's fixable (or not), but this is definitely an improvement.

**Pull request merged**
