### PR TITLE
Prevent circular imports in ts code

### PR DESCRIPTION
**Pull request by ShinDarth**
Closes: #523

### CODE REVIEW

**Comment by ShinDarth** [comment]
@ry ok. Apart from that, is the code OK? Shall we move also the export of `window` to a separate file?

**Comment by kt3k** [comment]
The code change seems ok to me, but CIs seem failing with the following error:

```
/home/travis/out/Default/deno js/unit_tests.ts --allow-write
Error: No such asset "libdeno.d.ts"
    at assert (deno/js/util.ts:20:11)
    at DenoCompiler.resolveModule (deno/js/compiler.ts:354:7)
    at DenoCompiler.resolveModuleName (deno/js/compiler.ts:398:33)
    at moduleNames.map.name (deno/js/compiler.ts:554:33)
    at Array.map (<anonymous>)
    at DenoCompiler.resolveModuleNames (deno/js/compiler.ts:545:24)
    at Object.compilerHost.resolveModuleNames (deno/third_party/node_modules/typescript/lib/typescript.js:111649:117)
    at resolveModuleNamesWorker (deno/third_party/node_modules/typescript/lib/typescript.js:82561:106)
    at resolveModuleNamesReusingOldState (deno/third_party/node_modules/typescript/lib/typescript.js:82768:24)
    at processImportedModules (deno/third_party/node_modules/typescript/lib/typescript.js:84005:35)
```

@ShinDarth Do you have any idea about the above?

**Comment by ShinDarth** [comment]
@kt3k I don't know why that is happening. Somehow the module resolution is not working properly: it looks for `libdeno.d.ts`, it doesn't find it and it just fails. It should instead also look for `libdeno.ts`  before failing.

https://www.typescriptlang.org/docs/handbook/module-resolution.html

Is there a way I can debug the `compiler.ts` ?

**Comment by ShinDarth** [comment]
@kt3k fixed with https://github.com/denoland/deno/pull/576/commits/e99b82ff27687c44783824e9d90799338a18f050

@ry addressed in https://github.com/denoland/deno/pull/576/commits/8b569b15f6fa35ed37eebb176c36363a6d5063b4

**Comment by ry** [comment]
Looks good - but don’t add the package-lock and avoid the package.json update if possible (otherwise we also need to make a change to deno_third_party)

**Comment by ShinDarth** [comment]
@ry done, thanks

**Pull request merged**
