### PR TITLE
third_party: add 'indicatif' crate

### PR DESCRIPTION
**Pull request by piscisaureus**

### CODE REVIEW

**Comment by piscisaureus** [comment]
18,650 additions and 0 deletions.

**Comment by piscisaureus** [comment]
Lot of code for displaying a progress bar.
@bartlomieju

**Comment by bartlomieju** [comment]
Agreed. I'll look out for alternatives.

**Comment by bartlomieju** [comment]
@piscisaureus [https://github.com/a8m/pb](https://github.com/a8m/pb) seemed promising, but... It's a lot less popular, been some time since it was updated, and I believe it's not thread safe which is pretty much required for our use case.

**Comment by ry** [comment]
@bartlomieju I like how ninja does its progress - which is very simple - it looks like
```
[4/34] STAMP obj/cli/msg_rs.stamp
```
maybe we can just do that manually in a few lines of code.

**Pull request closed without merging**
