### PR TITLE
Revert "feat: URL support in Deno filesystem methods (#5990)"

### PR DESCRIPTION
**Pull request by caspervonb**
This reverts commit 818a8010928cb8cef0b7043bd881c8cdce9b6efc.

See #6401

### CODE REVIEW

**Comment by nayeemrmn** [comment]
The problematic thing was string URLs, right? Why this over #6412? Note that the string URL thing was suggested and added halfway through #5990, everything before that was discussed prior. This is a breaking change without a bug fix.

**Comment by bartlomieju** [comment]
We should fix the bug, not reverting the feature. Closing in favor of https://github.com/denoland/deno/pull/6412

**Comment by caspervonb** [comment]
> The problematic thing was string URLs, right? Why this over #6412? 

Well URLs are just not compatible with file-paths, so at-best #6412 will just end up duplicating fromFileUrl as overloads in the lowest level of file access available at the cost of non trivial runtime overhead of several function calls and branches.

|                          | this branch      | master branch    |
|--------------------------|-----------------------|-----------------------|
| readTextFileSync         | 0.05443627729999995ms | 0.08073104320000017ms |
| writeTextFileSync        | 0.2174000651999981ms  | 0.23136435010000263ms |
| readAndWriteTextFileSync | 0.2233696526000013ms  | 0.24361926710000222ms |
----

```typescript
import { BenchmarkTimer, bench, runBenchmarks } from "./std/testing/bench.ts";

bench({
  name: "readTextFileSync",
  runs: 10000,
  func(b): void {
    b.start();
	  const data = Deno.readTextFileSync("./README.md");
    b.stop();
  },
});

bench({
  name: "writeTextFileSync",
  runs: 10000,
  func(b): void {
    b.start();
	  Deno.writeTextFileSync("out.txt", "output");
    b.stop();
  },
});

bench({
  name: "readAndwriteTextFileSync",
  runs: 10000,
  func(b): void {
    b.start();
	  const data = Deno.readTextFileSync("./README.md");
	  Deno.writeTextFileSync("out.txt", data);
    b.stop();
  },
});

runBenchmarks();import { BenchmarkTimer, bench, runBenchmarks } from "./std/testing/bench.ts";
```

**Comment by caspervonb** [comment]
> We should fix the bug, not reverting the feature. Closing in favor of #6412

#6412 still has the bug; urls in the file system

**Comment by nayeemrmn** [comment]
> non trivial runtime overhead

@caspervonb I'm aware of where the overhead is. Instead of master branch, try #6412. One `instanceof` check won't do that.

**Comment by caspervonb** [comment]
|                          | #6478                 | #5990                 | #6412                  |
|--------------------------|-----------------------|-----------------------|------------------------|
| readTextFileSync         | 0.05443627729999995ms | 0.08073104320000017ms | 0.067312613700000476ms |
| writeTextFileSync        | 0.2174000651999981ms  | 0.23136435010000263ms | 0.24990729750000168ms  |
| readAndwriteTextFileSync | 0.2233696526000013ms  | 0.24361926710000222ms | 0.2227832824000036ms   |
| statSync                 | 339.36735230000005ms  | 567.7075031799998ms   | 449.0708186400001ms    |

**Comment by ry** [comment]
@caspervonb Thanks for making those benchmarks. Interesting to see. Presumably you did these in a loop and took the average?

**Comment by cknight** [comment]
@ry see benchmark code above

**Comment by ry** [comment]
Oops - thanks Chris.

The slowdown is unfortunate. But I don't think we can roll back the URL support since it's already released (that is until 2.0). I think the URLs are fine - maybe we should provide access to the raw ops so WASI doesn't need to go through such high level interfaces.

**Comment by bartlomieju** [comment]
I think that slow down comes from parsing paths and url in JS, and IMO it should be done in Rust, please see my comment: https://github.com/denoland/deno/pull/6412#issuecomment-649779523

**Comment by nayeemrmn** [comment]
@bartlomieju We're talking about overhead in the non-URL case. After #6412 lands, the only overhead of URL support is the one `pathOrURL instanceof URL` check. Is it possible for that to make a noticable difference? Some of the numbers above are already a bit everywhere, I'd want to see benchmarks on CI at least. But again, I'm not sure it's possible for one `instanceof` check to make any difference.

> PR was mostly due to no one answering the question of "apply hacky fix or revert"

Removing string URL support, which wasn't part of the original proposal and doesn't match Node, is "hacky"?

**Pull request closed without merging**
