### PR TITLE
fix(op_crates/web) Make TextEncoder.encodeInto more efficient. Also fixes #9006

### LINKED ISSUE #9006: bug: encodeInto implementation is not correct
You can enable the failing WPT tests by adding this snippet to `cli/tests/wpt.jsonc`:

```json
{
   "name": "encodeInto",
   "expectFail": [
     // TODO(lucacasonato): enable once we support MessageChannel
     "encodeInto() and a detached output buffer"
   ]
},
```

Errors from the failing tests look like this:
```
encodeInto() into ArrayBuffer with �A�A¥Hi and destination length 10, offset 4, filler random
assert_equals: expected 239 but got 237
Error
    at AssertionError.get_stack (file:///tmp/wpt-bundle-J6kGw.js:3617:21)
    at new AssertionError (file:///tmp/wpt-bundle-J6kGw.js:3610:27)
    at assert (file:///tmp/wpt-bundle-J6kGw.js:3600:19)
    at assert_equals (file:///tmp/wpt-bundle-J6kGw.js:1225:9)
    at Test.<anonymous> (file:///tmp/wpt-bundle-J6kGw.js:4320:13)
    at Test.step (file:///tmp/wpt-bundle-J6kGw.js:2041:25)
    at test (file:///tmp/wpt-bundle-J6kGw.js:569:30)
    at file:///tmp/wpt-bundle-J6kGw.js:4286:7
    at Array.forEach (<anonymous>)
    at file:///tmp/wpt-bundle-J6kGw.js:4285:42
```

### PR DESCRIPTION
**Pull request by tarruda**
The current implementation of TextEncoder.encodeInto does a lot of allocations which significantly impacts performance. This new implementation aims to be more efficient and correct (fixes part of #9006, the other part is fixed by #10116).

To show the performance gains, the first commit adds a benchmark (cli/tests/text_encoder_into_perf.js) that can be run with the old version. Here are the results:

```
Benchmark #2: /home/tarruda/deno/target/release/deno run cli/tests/text_encoder_into_perf.js
  time (mean ± σ):     829.6 ms ±  12.1 ms    [user: 837.5 ms, system: 25.6 ms]
  range (min … max):   808.1 ms … 849.2 ms    10 runs
```

These are the new results:

```
Benchmark #2: /home/tarruda/deno/target/release/deno run cli/tests/text_encoder_into_perf.js
  Time (mean ± σ):     144.8 ms ±   3.2 ms    [User: 146.3 ms, System: 7.1 ms]
  Range (min … max):   140.1 ms … 149.8 ms    20 runs
```

The old version is uses about 5.7x the time used by the new version. Here's how it compares with TextEncoder.encode (backed by a very efficient Rust implementation):

```
Benchmark #1: /home/tarruda/deno/target/release/deno run cli/tests/text_encoder_perf.js
  Time (mean ± σ):      75.0 ms ±   4.5 ms    [User: 67.4 ms, System: 15.1 ms]
  Range (min … max):    66.1 ms …  85.1 ms    38 runs
```

### CODE REVIEW

**Comment by tarruda** [comment]
I've rebased the PR on `main` to obtain the changes from #10104 and removed some extra unused code (`UTF8Encoder` class and `stringToCodePoints` function)

**Comment by tarruda** [comment]
I've rebased the PR on `main` to obtain the changes from #10104 and removed some extra unused code (`UTF8Encoder` class and `stringToCodePoints` function)

**Comment by CrimsonCodes0** [comment]
If performance matters, couldn't this be directly be written in Rust for better performance than the current `TextEncoder#encode`?

Although it's not required, users and libraries expect `TextEncoder#encodeInto` to be implemented in a more performant manner than `TextEncoder#encoder`. Rust has proper integer types, and direct buffer writing capabilities, which should help a lot.

**Comment by tarruda** [comment]
> If performance matters, couldn't this be directly be written in Rust for better performance than the current TextEncoder#encode?

An implementation of `TextEncoder#encodeInto` that uses the rust version to to encode to a temporary buffer, then copies only what fits into the input buffer passed to  `TextEncoder#encodeInto`, would probably beat the implementation here in benchmarks. But raw benchmark timings are not telling the whole story. 

The purpose of `encodeInto` is to avoid temporary allocations, which ultimately puts less pressure in V8 garbage collector. If we could write directly to Javascript heap from Rust, then yes a pure Rust implementation would be better, but I'm not familiar enough with Rust or V8 API to know if that is possible.

**Comment by CrimsonCodes0** [comment]
> TextEncoder#encodeInto that uses the rust version to encode to a temporary buffer, then copies only what fits into the input buffer passed to `TextEncoder#encodeInto`, would probably beat the implementation here in benchmarks...

Oh no, for clarification, I'm suggesting just rewriting the JS you used into Rust, and writing into the Uint8Array's raw buffer.

To make a temporary buffer and then copy into the Uint8Array would likely be much slower, as it would do a lot of unnecessay work; consider a 1000 character long UTF-16 string, passed along with a 2-byte Uint8Array, the buffer could be at most roughly 4000 bytes, while only most, 8 would be needed.

The V8 API's ArrayBuffer class provides a method to access the underlying bytes, but I'm not sure if rusty_v8 does.

Regardless, don't let my comment detract you, those are good performance numbers! Someone could port it to Rust later, if necessary.

**Comment by tarruda** [comment]
> Regardless, don't let my comment detract you, those are good performance numbers! Someone could port it to Rust later, if necessary.

Later I might investigate and give it a shot, it would be a good exercise to get more familiar with Rust and V8.

**Comment by tarruda** [comment]
Rebased to resolve conflicts and update expectations.json for encodeInto (after #10116 and this PR, only one encodeInto test is failing).

**Review by lucacasonato — APPROVED** [review]
Awesome. Thanks a lot for the fix, and the performance improvements. Those are always very welcome :-)

LGTM

**Pull request merged**
