### PR TITLE
feat(ext/url): URLSearchParams two-argument delete() and has()

### LINKED ISSUE #19000: Add value argument to URLSearchParams's has() and delete()
This was the most-requested feature in the URL Standard backlog.

Standard: https://github.com/whatwg/url/pull/735.

WPT: https://github.com/web-platform-tests/wpt/pull/39865.

### PR DESCRIPTION
**Pull request by lino-levan**
Round 2 of trying to close #19000.

Trying codespaces to see if it's any faster than local dev.

### CODE REVIEW

**Comment by lino-levan** [comment]
@crowlKats please take a look

**Comment by andreubotella** [comment]
LGTM. But you should change the PR title to include "URLSearchParams".

**Review by bartlomieju — APPROVED** [review]
LGTM, but I'll wait for @crowlKats review before merging.

**Review by crowlKats — APPROVED** [review]
LGTM

**Pull request merged**
