### PR TITLE
unstable: remove Deno.spawn, Deno.spawnSync, Deno.spawnChild APIs

### PR DESCRIPTION
**Pull request by bartlomieju**
This commit removes three unstable Deno APIs:
- "Deno.spawn()"
- "Deno.spawnSync()"
- "Deno.spawnChild()"

These APIs were replaced by a unified "Deno.Command" API.

### CODE REVIEW

**Comment by iuioiua** [comment]
Should `Deno.run` also be removed?

**Comment by bartlomieju** [comment]
> Should `Deno.run` also be removed?

No, it's a stable API that can't be removed until Deno 2.0 happens. We will deprecate it though, once we stabilize `Deno.Command`.

**Comment by iuioiua** [comment]
> No, it's a stable API that can't be removed until Deno 2.0 happens. We will deprecate it though, once we stabilize `Deno.Command`.

Oh, I thought it was unstable for some reason...

**Review by dsherret — APPROVED** [review]
LGTM

**Pull request merged**
