### PR TITLE
fix(console) - log function object properties / do not log non-enumerable props by default 

### PR DESCRIPTION
**Pull request by DavidDeSimone**
Addresses https://github.com/denoland/deno/issues/9333 

Running `deno eval "const x=()=>'x'; x.y=()=>'y'; x.z = function z() {return 'z'}; console.log({x});"` now properly logs the function's properties. I've added a basic test for this behavior.

### CODE REVIEW

**Comment by caspervonb** [comment]
This changes the output of a bunch of things which also differs from Node (since Node was mentioned as the reason for the change).

```
> Array
[Function: Array] { [Symbol(Symbol.species)]: [Getter] }

> Regexp
[Function: RegExp] { [Symbol(Symbol.species)]: [Getter] }
```

**Comment by DavidDeSimone** [comment]
Good catch @caspervonb . I think the root cause here is that deno logs non-enumerable symbols by default, while node doesn't:

```bash
user@ubuntu:~/proj/deno$ node -e "let x = {}; let s = Symbol('foo'); Object.defineProperty(x, s, {enumerable: false }); console.log(x)"
{}
user@ubuntu:~/proj/deno$ deno eval "let x = {}; let s = Symbol('foo'); Object.defineProperty(x, s, {enumerable: false }); console.log(x)"
{ [Symbol(foo)]: undefined }
```

If that behavior were changed, then this PR would be aligned with Node for function constructors like Array. It shouldn't hard to add that on.

**Comment by DavidDeSimone** [comment]
I've updated this PR to have Deno.inspect not log non-enumerable properties by default, and I've added a new flag named "showNonEnumerable" to InspectOptions. Setting this flag to true will show non-enumerable properties, similar to setting showHidden=true in node's inspect function. 

I've updated the tests to reflect the new desired behavior, along with adding additional cases around the new flags.

**Comment by caspervonb** [comment]
>  Setting this flag to true will show non-enumerable properties, similar to setting showHidden=true in node's inspect function.

If there's prior art for this option, maybe we should just adopt that prior art?

**Review by caspervonb — APPROVED** [review]

**Review by kt3k — APPROVED** [review]
Chrome seems doing the different thing for non-enumerable symbols, but we had #3165, so this change make sense to me. LGTM.

**Comment by kt3k** [comment]
@DavidDeSimone Thank you for your contribution!

**Pull request merged**
