### PR TITLE
typings: Make FileInfo as returned by readdir not null

### PR DESCRIPTION
**Pull request by KSXGitHub**
## Reason

It is annoying to write `const name = info.name!` when we know for sure that `info.name` will never be `null`.
This change would enable us to write `const { name } = info`.

### CODE REVIEW

**Comment by nayeemrmn** [comment]
We should just remove `FileInfo::name`.

`readdir()` should return `Array<FileInfo & { name: string }>` or `Array<[string, FileInfo]>`.

**Comment by KSXGitHub** [comment]
@nayeemrmn What you suggest is bigger than the scope of my concern right now, not that I am against it, but we have to wait for others' opinion (perhaps another PR).

**Comment by nayeemrmn** [comment]
Well if so we shouldn't merge this, since it adds an API symbol.

**Comment by KSXGitHub** [comment]
@nayeemrmn I can make another PR for `Array<FileInfo & { name: string}>`.

**Comment by nayeemrmn** [comment]
And remove `FileInfo::name`. Also having a type alias isn't a problem, but it should probably be something like:
```ts
export interface DirEntry extends FileInfo {
  name: string
}
```
(like Node's [`Dirent`](https://nodejs.org/api/fs.html#fs_class_fs_dirent)).

**Comment by KSXGitHub** [comment]
@nayeemrmn So just rename `NamedFileInfo` to `DirEntry`? Removing `FileInfo::name` is a bigger change.

**Comment by nayeemrmn** [comment]
Let's keep things in sync. As well as the `FileInfo::name` thing there is also the implementation and interfaces in `std` which need to inherit this change.

**Comment by KSXGitHub** [comment]
I have renamed `NamedFileInfo` to `DirEntry` and removed `FileInfo::name`

**Comment by KSXGitHub** [comment]
If the test fail because I removed `FileInfo::name`, I will undo it.

**Comment by KSXGitHub** [comment]
Undo removing `FileInfo::name` because of TypeScript errors. I may remove it again in the future, but that's for another PR. Do you have any objection @nayeemrmn?

**Comment by nayeemrmn** [comment]
@KSXGitHub https://github.com/denoland/deno/pull/4733#issuecomment-612925104

**Comment by KSXGitHub** [comment]
I don't know why tests broken on windows-2019.

**Comment by KSXGitHub** [comment]
> @KSXGitHub [#4733 (comment)](https://github.com/denoland/deno/pull/4733#issuecomment-612925104)

I already read it. I also said that is for another PR. I need sleep right now.

**Comment by ry** [comment]
@KSXGitHub Looks good so far. I agree with @nayeemrmn that read_dir.ts and std should to be updated.

**Comment by KSXGitHub** [comment]
@ry @nayeemrmn I am trying to update `read_dir.ts` and `std` in https://github.com/denoland/deno/pull/4740. But if it proves to be more complicated than I anticipate, I will simply give up.

**Comment by ry** [comment]
@KSXGitHub Thanks - I appreciate you looking into it! Let me know if you get stuck.

**Comment by KSXGitHub** [comment]
@ry [I just get stuck](https://github.com/denoland/deno/pull/4740#issuecomment-613219223)

**Pull request closed without merging**
