### PR TITLE
Added path info to error message from stat/statSync

### LINKED ISSUE #10553: Improve the error message from `stat/statSync`
Currently the error message of the exception, thrown from the `Deno.stat/statSync`, when the file is missing, does not include the file name:
```
nickolay@frontier:~/workspace/Bryntum/siesta-monorepo/siesta$ deno
Deno 1.9.2
exit using ctrl+d or close()
> Deno.statSync('/home/nickolay/not_existing_file')
Uncaught NotFound: No such file or directory (os error 2)
    at unwrapOpResult (deno:core/core.js:99:13)
    at Object.opSync (deno:core/core.js:113:12)
    at Object.statSync (deno:runtime/js/30_fs.js:224:22)
    at <anonymous>:2:6
> 
```
Is this intentional with some rationale behind, or just an oversight? From usability perspective the filename should be included in the message of course.

### PR DESCRIPTION
**Pull request by CGQAQ**
Fixed #10553

### CODE REVIEW

**Comment by bnoordhuis** [comment]
Your patch contains a bunch of whitespace changes and it looks like you clobbered `test_util/std` somehow? Can you run `cargo fmt` to fix the former and revert the latter?

As to the change itself: it mostly LGTM, I think, but, as mentioned in the issue, I'd like to see it consistently applied to all fs methods in that file. Thanks!

**Comment by CGQAQ** [comment]
I just ran tools/format.js, and it changed std, should I revert all of it?

**Review by bartlomieju — CHANGES_REQUESTED** [review]
@CGQAQ thank you for the PR, but I agree with @bnoordhuis - we should have a unified error messages for all file system ops. 

Also there's a bunch of whitespace changes that look accidental; please revert them.

**Comment by CGQAQ** [comment]
> @CGQAQ thank you for the PR, but I agree with @bnoordhuis - we should have a unified error messages for all file system ops.
> 
> Also there's a bunch of whitespace changes that look accidental; please revert them.

I already reverted white spaces that I accidentally changed

**Comment by CGQAQ** [comment]
> @CGQAQ thank you for the PR, but I agree with @bnoordhuis - we should have a unified error messages for all file system ops.
> 
> Also there's a bunch of whitespace changes that look accidental; please revert them.

@bartlomieju sure you can take it, I am currently don't have time to do this PR

**Comment by bartlomieju** [comment]
Closing this one as @abakfja wants to look into the issue for all FS ops.

**Comment by F3n67u** [comment]
> @CGQAQ thank you for the PR, but I agree with @bnoordhuis - we should have a unified error messages for all file system ops.
> 
> Also there's a bunch of whitespace changes that look accidental; please revert them.

Come across the same problem. It's annoy that stat complain error but not provide the path info.

@bartlomieju  How about use https://docs.rs/fs-err/2.6.0/fs_err/ to replace all std::fs call to provide a unified error message with `path` context?

**Comment by F3n67u** [comment]
I create a pr for my idea. feedback welcome.

**Pull request closed without merging**
