### PR TITLE
feat: better help output

### PR DESCRIPTION
**Pull request by crowlKats**
Additionally adds an internal JSON help output.
Screenshot 2024-08-09 at 13 33 38

Screenshot 2024-08-09 at 13 34 02

### CODE REVIEW

**Comment by bartlomieju** [comment]
FYI `./target/debug/deno --help` prints nicely with colors, but `./target/debug/deno help` has no colors whatsoever.

**Comment by bartlomieju** [comment]
Also on my machine I don't see descriptions being grayed out:
Screenshot 2024-08-09 at 23 28 11

**Review by bartlomieju — APPROVED** [review]
LGTM!

**Comment by littledivy** [comment]
Reason for reverting tokio upgrade: https://github.com/tokio-rs/tokio/issues/6767

**Comment by robtfm** [comment]
> Reason for reverting tokio upgrade: [tokio-rs/tokio#6767](https://github.com/tokio-rs/tokio/issues/6767)

looks like upstream is fixed, could this be unfrozen now?

**Pull request merged**
