### PR TITLE
test(cli): add test for deno test --shuffle

### PR DESCRIPTION
**Pull request by getspooky**
Add testing for `shuffle` options.

### CODE REVIEW

**Comment by bartlomieju** [comment]
This look good to me, however CI is failing. Please re-run it.

Tangentially: I still can't push commits to your branches as the repo seems to belong to an org. Please make sure the PRs you're opening are coming from the fork under your personal account so that maintainers can push commits as needed.

**Comment by getspooky** [comment]
@bartlomieju  done , all test has been passed. 👍🏼

**Review by bartlomieju — APPROVED** [review]

**Comment by bartlomieju** [comment]
@getspooky please rebase

**Comment by bartlomieju** [comment]
@getspooky something is not right, there shouldn't be 5k lines changed in this PR. Please make sure the rebase is done properly or open a new PR from your own fork so I can push to it.

**Comment by getspooky** [comment]
@bartlomieju https://github.com/denoland/deno/pull/11523

**Pull request closed without merging**
