### PR TITLE
chore(test): increase timeout duration on macOS

### PR DESCRIPTION
**Pull request by magurotuna**
Ref #8571 

Watcher-related tests are so flaky on macOS of GitHub Actions. I'm totally unsure what the cause is. All I can confirm is the performance of macOS instance is kinda worse compared to ubuntu or windows:
https://github.community/t/macos-performance/125281
So I suspect that the flakiness is simply because of performance issues on macOS. In this PR, I'll try to see it.

### CODE REVIEW

**Comment by magurotuna** [comment]
It failed on a test other than watcher-related ones 🤷 
https://github.com/denoland/deno/runs/1541140343#step:24:4102

```
Error: thread 'local_sources_not_cached_in_memory' panicked at 'pattern match failed', test_util/src/lib.rs:914:7
stack backtrace:
   0:        0x10b4b1d33 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hcfc48256a5ab8835
   1:        0x10b4490a0 - core::fmt::write::haf3903118f694c48
error: test failed, to rerun pass '-p deno --test integration_tests'
   2:        0x10b509b5a - std::io::Write::write_fmt::h15aa2f50e681f5ef
   3:        0x10b4cc868 - std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt::h60f8c617b1dd6b36
   4:        0x10b4b0ddf - std::panicking::default_hook::{{closure}}::h91bd4c58cf71392b
   5:        0x10b4b04fa - std::panicking::rust_panic_with_hook::hae2b05f08a320721
   6:        0x10b43a3e1 - std::panicking::begin_panic::{{closure}}::he9a35dfa6dbc8747
   7:        0x10b43a3b2 - std::sys_common::backtrace::__rust_end_short_backtrace::h2368b6636658f135
   8:        0x10b67f458 - std::panicking::begin_panic::hed3ba9c9d354ea40
   9:        0x10b517bd8 - test_util::CheckOutputIntegrationTest::run::h2bc29af5580561a0
  10:        0x10b420397 - core::ops::function::FnOnce::call_once::hd1365913ed18cf82
  11:        0x10b504bca - test::__rust_begin_short_backtrace::h8c20647892dadc50
  12:        0x10b504ef4 - test::run_test::run_test_inner::{{closure}}::hadc7a51fce6724fe
  13:        0x10b506bfb - std::sys_common::backtrace::__rust_begin_short_backtrace::h6e10ee62b301fe5a
  14:        0x10b506af0 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h48bb72bd4d1e4e41
  15:        0x10b4e0a9d - std::sys::unix::thread::Thread::new::thread_start::he3e6719579180a65
  16:     0x7fff730f1109 - __pthread_start


failures:
    local_sources_not_cached_in_memory
```

**Comment by bartlomieju** [comment]
@magurotuna `local_sources_not_cached_in_memory` failures are caused by #8556

**Review by bartlomieju — APPROVED** [review]
LGTM, let's land and see if that helps, if not I'll revert it

**Comment by bartlomieju** [comment]
Unfortunately it still fails: https://github.com/denoland/deno/runs/1542414977

Reverting in https://github.com/denoland/deno/pull/8737

**Pull request merged**
