### PR TITLE
feat(test): use gray color for 'running n tests from ...'

### PR DESCRIPTION
**Pull request by bartlomieju**
Closes https://github.com/denoland/deno/issues/14186

Alternative to https://github.com/denoland/deno/pull/13930

Screenshot 2022-04-02 at 21 02 44
Screenshot 2022-04-02 at 21 00 16

I'm tempted to do the same for `test` on each lines before the test name

### CODE REVIEW

**Comment by bartlomieju** [comment]
Thoughts?

Screenshot 2022-04-02 at 21 05 00

**Comment by bartlomieju** [comment]
Actually I'm tempted to completely remove `test` prefix 🤣

**Comment by jespertheend** [comment]
> Actually I'm tempted to completely remove `test` prefix 🤣

I was about to suggest this. I'm not sure what `test` is supposed to tell us, I think we know they are tests xD.

**Comment by bartlomieju** [comment]
Some more ideas:

Screenshot_2022-04-02_at_21 55 07

**Comment by jespertheend** [comment]
Ooh I like it. Especially that there's no need for a list of failures like this anymore, and the `>` makes it super clear where you have to look for the implementation of a failing test.

Not entirely sure how I feel about the list of stats yet. When you have failing tests I think the new list is better, but my current test results look like this:
image
Which would end up as a long list of all zeros.
Maybe you can omit the stats that have zero items?
Or maybe even something like `All 756 tests passed (14s)` when there are no other items.

**Comment by bartlomieju** [comment]
> Ooh I like it. Especially that there's no need for a list of failures like this anymore, and the `>` makes it super clear where you have to look for the implementation of a failing test.
> 
> 
> 
> Not entirely sure how I feel about the list of stats yet. When you have failing tests I think the new list is better, but my current test results look like this:
> 
> image
> 
> Which would end up as a long list of all zeros.
> 
> Maybe you can omit the stats that have zero items?
> 
> Or maybe even something like `All 756 tests passed (14s)` when there are no other items.

I'm not sure I'm in favor of varying output depending on the outcome of the tests. I'll give it another thought tomorrow.

**Comment by jespertheend** [comment]
Hmm yeah maybe it's not entirely fair to compare the two screenshots. One screenshot shows a failing test and the other only passing tests. So naturally the later will seem more satisfying.

I do think the new layout is a lot more readable though, even if you don't end up omitting the stats with zero items.

**Comment by bartlomieju** [comment]
This is blocked by https://github.com/denoland/deno/pull/13799 which contains API that will come in handy for test runner.

**Comment by bartlomieju** [comment]
I'm gonna close this PR for now. Worked on this with @kt3k last week and we got a few more ideas. I will open a new PR once https://github.com/denoland/deno/pull/14159 lands

**Pull request closed without merging**
