### PR TITLE
fix(ext/node): add the missing path information when the file is not found in `fs.stat` and `fs.statSync`

### LINKED ISSUE #25921: node-compa: better error message
Version: Deno 1.46.1

```ts

// main.ts
import fs from "node:fs";

/**
 * read file with node compa
 */
function readFileWithNode(file: string) {
  try {
    fs.statSync(file);
  } catch (error: unknown) {
    // No path information in error
    console.log(`Error occurred while reading file with node: ${error}`);
  }
}

/**
 * read file with deno
 */
function readFileWithDeno(file: string) {
  try {
    Deno.statSync(file);
  } catch (error: unknown) {
    // Has path information in error
    console.log(`Error occurred while reading file with deno: ${error}`);
  }
}

readFileWithNode("non-exist-file");
readFileWithDeno("non-exist-file");
```

Run below command:
```sh
deno run -A main.ts
```

The output is:
```text
Error occurred while reading file with node: Error: ENOENT: no such file or directory, stat
Error occurred while reading file with deno: NotFound: 系统找不到指定的文件。 (os error 2): stat 'non-exist-file'
```

In this case, better error message(has path information) is useful for debug.

### PR DESCRIPTION
**Pull request by familyboat**
Fix #25921.
See more details in #25921.

### CODE REVIEW

**Comment by familyboat** [comment]
I test it with
```js
// main.js
import fs from "node:fs";

const file = "non-exist-file";
const fileUrl = new URL(file, import.meta.url);
const nonFileUrl = new URL(file, "https://example.com");

const files = [file, fileUrl, nonFileUrl];

function testStatSync() {
  files.forEach((item) => {
    try {
      fs.statSync(item);
    } catch (error) {
      console.log(`Error occurred in fs.statSync: ${error}`);
    }

    try {
      Deno.statSync(item);
    } catch (error) {
      console.log(`Error occurred in Deno.statSync: ${error}\n`);
    }
  });
}

async function testStat() {
  for (const item of files) {
    await fs.stat(item, (error) => {
      console.log(`Error occurred in fs.stat: ${error}`);
    });

    try {
      await Deno.stat(item);
    } catch (error) {
      console.log(`Error occurred in Deno.stat: ${error}\n`);
    }
  }
}

testStatSync();
testStat();
```
Run it with `deno run -A main.js`
The output is:
```plain
Error occurred in fs.statSync: Error: ENOENT: no such file or directory, stat 'non-exist-file'
Error occurred in Deno.statSync: NotFound: No such file or directory (os error 2): stat 'non-exist-file'

Error occurred in fs.statSync: Error: ENOENT: no such file or directory, stat '/root/test/node-file-error-message/non-exist-file'
Error occurred in Deno.statSync: NotFound: No such file or directory (os error 2): stat '/root/test/node-file-error-message/non-exist-file'

Error occurred in fs.statSync: TypeError: Must be a file URL.
Error occurred in Deno.statSync: TypeError: Must be a file URL.

Error occurred in fs.stat: Error: ENOENT: no such file or directory, stat 'non-exist-file'
Error occurred in Deno.stat: NotFound: No such file or directory (os error 2): stat 'non-exist-file'

Error occurred in fs.stat: Error: ENOENT: no such file or directory, stat '/root/test/node-file-error-message/non-exist-file'
Error occurred in Deno.stat: NotFound: No such file or directory (os error 2): stat '/root/test/node-file-error-message/non-exist-file'

Error occurred in fs.stat: TypeError: Must be a file URL.
Error occurred in Deno.stat: TypeError: Must be a file URL.
```

Running `cargo test` took several hours, so I gave up.

**Comment by littledivy** [comment]
@familyboat You can add your test to `tests/unit_node/fs_test.ts` and run it with:

```shell
target/debug/deno test -A --config tests/config/deno.json tests/unit_node/fs_test.ts
```

**Comment by familyboat** [comment]
I add tests for `node:fs/statSync` and `node:fs/promises/sync`(which is promisify of `node:fs/stat`).

**Review by littledivy — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
