### PR TITLE
Uses `dirs::home_dir` to replace deprecated `std::env::home_dir`

### LINKED ISSUE #745: Fix new rust 1.29 deprecation warning
```
warning: use of deprecated item 'std::env::home_dir': This function's behavior is unexpected and probably not what you want. Consider using the home_dir function from https://crates.io/crates/dirs instead.
  --> ../../src/deno_dir.rs:42:20
   |
42 |     let home_dir = std::env::home_dir().expect("Could not get home directory.");
   |                    ^^^^^^^^^^^^^^^^^^
   |
   = note: #[warn(deprecated)] on by default
```

### PR DESCRIPTION
**Pull request by kevinkassimo**
## DEPENDS on denoland/deno_third_party#12

Closes #745

- [x] Uses `dirs::home_dir` to replace deprecated `std::env::home_dir` for Rust 1.29

__PR checks expected to fail before third-party PR merged__

### CODE REVIEW

**Comment by J2P** [comment]
I have a question.
Don't we have to add `dirs = "1.0.3"` to [Cargo.toml](https://github.com/denoland/deno/blob/master/Cargo.toml) file?

**Comment by J2P** [comment]
@kevinkassimo Thank you for answer :smile:

**Comment by piscisaureus** [comment]
@kevinkassimo Can you `git add third_party`, commit, push ?
That way CI will be able to test this PR.

**Comment by kevinkassimo** [comment]
@piscisaureus Will do once having access to my machine (in 30 min)

**Comment by piscisaureus** [comment]
LGTM, thanks! Prepared for landing in #762.

**Comment by piscisaureus** [comment]
Thanks again! Landed in https://github.com/denoland/deno/compare/denoland:ba8757b...piscisaureus:c7a4ca3

**Pull request closed without merging**
