### PR TITLE
Display anchors only on hover

### LINKED ISSUE #1669: Website: Hate the anchors
I really hate the current anchors on the website.  I find them very distracting.  Looks like Deno is named #Deno.

deno

Why can't we style them out of the flow of the text and only have them visible on hover, just like GitHub:

target hover

### PR DESCRIPTION
**Pull request by sh7dm**
Fixes #1669.

### CODE REVIEW

**Comment by ry** [comment]
I don't like how it's indented...

**Comment by sh7dm** [comment]
@ry maybe move it to end?

**Comment by saadq** [comment]
In case you want to keep it on the left side and handle it similar to GitHub, you could do so using similar styles as them:

```css
a[href^="#"] {
  visibility: hidden;
  float: left;
  margin-left: -20px;
}
```

and then set it to `visibility: visible` only when hovered/focused. 

anchors

But as someone mentioned in the issue, you will probably want to play around with the margin sizing to make sure its okay for mobile so that it doesn't go offscreen like GitHub.

**Comment by ry** [comment]
I'll wait until someone properly solves it. Let's not iterate trivial things (like CSS) in the PRs - every time you push it blocks the CI. Closing without merge.

**Pull request closed without merging**
