### PR TITLE
test(std): ensure mod.ts modules have a test coverage

### PR DESCRIPTION
**Pull request by caspervonb**
This ensures that adds a test.ts module for every mod.ts module in std so that the imports and exports of top level modules are always checked during test runs.

See https://github.com/denoland/deno/issues/6849#issuecomment-662798871

### CODE REVIEW

**Comment by bartlomieju** [comment]
I'm not sure I understand this change, aren't test files picked up automatically by `deno test` or do `mod.ts` files contain some tests?

**Comment by caspervonb** [comment]
> I'm not sure I understand this change, aren't test files picked up automatically by deno test or do mod.ts files contain some tests?

Not all modules are importing their "top level" mod.ts file in tests.

We've had at-least one regression(#6849) that would've been caught by this.

**Comment by ry** [comment]
So basically this is a code coverage problem? Some top-level mod.ts were not being type checked?

**Comment by caspervonb** [comment]
> So this is a code coverage problem? Some top-level mod.ts were not being type checked?

Yup

**Pull request merged**
