### PR TITLE
refactor: use primordials for extensions/crypto

### PR DESCRIPTION
**Pull request by littledivy**
Towards #11224

### CODE REVIEW

**Comment by littledivy** [comment]
Actually, let's wait for #11228 so we can use `window.__bootstrap.domException`

**Comment by lucacasonato** [comment]
@littledivy I want to land #9614 first. Hoping to do that tomorrow.

**Comment by lucacasonato** [comment]
@littledivy Now landed.

**Review by bartlomieju — APPROVED** [review]
LGTM, thanks @littledivy!

**Pull request merged**
