### PR TITLE
BREAKING(std/log): remove string formatter

### PR DESCRIPTION
**Pull request by timreichen**
Breaking change: remove string based formatter  in favor of function based formatter and template strings.

### CODE REVIEW

**Comment by bartlomieju** [comment]
@timreichen what's the reason for this change?

**Comment by timreichen** [comment]
@bartlomieju 
1. Curly bracket string replacement is not a standard nor natively supported by `js`. `std` should not support non-standards as discussed in this [issue](https://github.com/denoland/deno/issues/6917).
2. To prevent unintentional wrong logs as described [here](https://github.com/denoland/deno/issues/6701) since string formatter does not check passed names.
3. Everything the string formatter does is doable by [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) which is `js` native.

**Comment by bartlomieju** [comment]
@timreichen thanks for pointing this out. Then I'm in favor of this change.

**Review by bartlomieju — APPROVED** [review]
LGTM

**Comment by timreichen** [comment]
Might want to consider #7293 instead of this PR.

**Comment by bartlomieju** [comment]
Closing in favor of #7293

**Pull request closed without merging**
