### PR TITLE
Pin lspower, because it made semvar incompatible patch release

### PR DESCRIPTION
**Pull request by ry**

### CODE REVIEW

**Review by kitsonk — APPROVED** [review]
LGTM

**Comment by lucacasonato** [comment]
@hvithrafn In the future please don't update lsp-types a minor release in a lspower patch release. lsp-types is part of the lspower public interface so if that has a minor release (pre 1.x breaking change), then lspower must bump at minimum a minor too. The lsp-types update between lspower@0.6.3 and lspower@0.6.4 broke our 1.8.0 release. Thanks :-)

**Comment by bl-ue** [comment]
Hey, what's 'semvar'? :smile:

**Comment by hvithrafn** [comment]
Oops. Sorry. 🙏

**Comment by bl-ue** [comment]
But that wasn't your commit :)

**Pull request merged**
