### PR TITLE
docs: use const assertion for PermissionDescriptor

### PR DESCRIPTION
**Pull request by trivikr**
Fixes https://github.com/denoland/deno/issues/7731

### CODE REVIEW

**Review by nayeemrmn — CHANGES_REQUESTED** [review]
Can you do the rest as well? `const desc* = ...`

**Comment by trivikr** [comment]
> Can you do the rest as well? `const desc* = ... as const;`

Updated in [`518661c` (#7733)](https://github.com/denoland/deno/pull/7733/commits/518661ccf74e1fc3f359f021a1a187f645a25824)

**Review by nayeemrmn — APPROVED** [review]
LGTM

**Review by kitsonk — APPROVED** [review]
LGTM

**Pull request merged**
