### PR TITLE
refactor: worker is no longer a resource

### PR DESCRIPTION
**Pull request by bartlomieju**
Exploring yet another approach to handling `Worker`. 

This PR changes make it that `Worker` is no longer a resource but rather CLI internal structure. When creating child workers they are placed inside `ThreadSafeState.workers` (previously only shared future of `Worker` was placed there). 

With this changes it becomes quite easy to scope resources per worker (no sharing of resources between workers, resource tables are created per worker). Also it opens a way to implement changes described in #3116.

There's still some cleanup to do, but I wanted to get feedback about this approach.

CC @ry @piscisaureus

### CODE REVIEW

**Comment by ry** [comment]
So in this change a worker has an id but it's not a resource. There is a separate special table for workers to be stored? What  are the problems caused by having a worker be a resource?

**Comment by bartlomieju** [comment]
> So in this change a worker has an id but it's not a resource. There is a separate special table for workers to be stored? What are the problems caused by having a worker be a resource?

That's correct. The reason is that worker was "split" into 3 parts before; internal channels (held inside `state`), external channels (that was the resource) and "shared future" of worker (again held in `state` in `workers` field). It led to situation where worker finished it's job but was never actually closed because resource was not removed nor was this shared future removed from `workers` table. This PR makes workers self-contained and spawning sub workers are only ever owned/referenced by their' parent worker.

Because `workers` are special - they are basically new instances of V8 isolate (with some additional Deno infra) I believe it makes sense to treat them in a bit special way and not expose anyhow to interaction by user except `Worker` API (eg. doing `close(worker_rid)` crashes the process, I think you did it in one of the talks btw).

**Comment by ry** [comment]
My initial thought is that it sounds reasonable.

Summoning @piscisaureus for a second opinion.

**Comment by bartlomieju** [comment]
Although I felt this is a right way forward I'm not entirely sure now.  When you look at https://github.com/denoland/deno/issues/3282 there's mention of [`SharedWorker`](https://developer.mozilla.org/en-US/docs/Web/API/SharedWorker).

> The SharedWorker interface represents a specific kind of worker that can be accessed from several browsing contexts, such as several windows, iframes or even workers.

If we're interested in supporting `SharedWorker`s this PR would make it kinda impossible to do that, but it's overall an upgrade to current situation.  We might tackle it later when we'll be tackling resources shared between workers. WDYT?

**Comment by piscisaureus** [comment]
I have no objections per se to this patch. It looks quite clean by itself, and at this time I think a per-worker resource table is the way to go.
That said, I can't fully oversee the consequences for SharedWorker and shared resources that we might want to support in the future.

**Pull request merged**
