### PR TITLE
fix(cli): use upstream type definitions for WebAssembly

### LINKED ISSUE #7212: Missing type definitions for WebAssembly
Seems like we don't have the full type definition of the WebAssembly namespace available to the compiler.

```typescript
type ImportValue = WebAssembly.ImportValue;
type ExportValue = WebAssembly.ExportValue;
```

```
error: TS2694 [ERROR]: Namespace 'WebAssembly' has no exported member 'ImportValue'.
type ImportValue = WebAssembly.ImportValue;
                               ~~~~~~~~~~~
    at file:///home/caspervonb/deno/test.ts:1:32

TS2694 [ERROR]: Namespace 'WebAssembly' has no exported member 'ExportValue'.
type ExportValue = WebAssembly.ExportValue;
                               ~~~~~~~~~~~
    at file:///home/caspervonb/deno/test.ts:2:32
```

### PR DESCRIPTION
**Pull request by caspervonb**
We apparently have a bit of an ad-hoc or out of date definition of the WebAssembly namespace that is incompatible with the current dom and webworker definitions.

This copies in the current WebAssembly namespace declaration defined in lib.dom.d.ts.

Closes #7212

### CODE REVIEW

**Comment by kitsonk** [comment]
The change LGTM, and is the right approach but obviously caused some assignability regressions with the revised types.

**Comment by caspervonb** [comment]
> The change LGTM, and is the right approach but obviously caused some assignability regressions with the revised types.

Yeah the old definition unfortunately makes use of any and object in a lot of places.
All of these errors are potential runtime errors or silent errors that should be fixed regardless.

Question is, can we land this without a major?

WDYT @ry @bartlomieju?

**Comment by lucacasonato** [comment]
> Question is, can we land this without a major? We did do that with the URL constructor.

I think we can if we test that this will not impact the large majority of people (ie not break recent std versions, or commonly used third party modules using wasm). I will go and do some testing on this tomorrow.

**Comment by kitsonk** [comment]
I am also of the opinion that in this case it would impact a lot less, as we had it "wrong" and a lot of `std` was abusing that wrongness (even though runtime behaviour allowed it).

It does bring up the situation that we might want to start figuring out how we do a regression test against some popular Deno libraries.  TypeScript does this as well, so they know what sort of pains occur when people have coupled to unintended behaviours that get changed.

**Comment by caspervonb** [comment]
> I think we can if we test that this will not impact the large majority of people (ie not break recent std versions, or commonly used third party modules using wasm).

It doesn't break wasm-bindgen produced modules such as std/hash at-least, which is what pretty much everyone uses as all the talks and articles on WebAssembly tell you to use it.

**Review by lucacasonato — APPROVED** [review]
I tested this against some WASM modules on /x and they all seem unaffected:
- https://deno.land/std@0.67.0/hash/mod.ts
- https://deno.land/x/wasm_gzip@v1.0.0/mod.ts
- https://deno.land/x/encoding_wasm@v0.1.0/mod.ts
- https://deno.land/x/brotli@v0.1.4/mod.ts
- https://deno.land/x/lz4@v0.1.2/mod.ts

So LGTM - thanks Casper

**Pull request merged**
