### PR TITLE
feat: update to TypeScript 4.7.4

### PR DESCRIPTION
**Pull request by espindola**
Also update the update_typescript.md document to match the current
status.

### CODE REVIEW

**Comment by bartlomieju** [comment]
What's the reason for this update? We usually don't upgrade TypeScript in-between minor versions.

**Comment by espindola** [comment]
> What's the reason for this update? We usually don't upgrade TypeScript in-between minor versions.

I hit an issue trying https://github.com/deepkit/deepkit-framework/tree/master/packages/type-compiler, which is based on 4.7.4. I decided to first update deno to the same version to check if was an incompatibility with 4.7.2. It wasn't (the issue is https://github.com/deepkit/deepkit-framework/issues/283), but since I had the upgrade I decided to offer it.

Would you be interested in the update to tools/update_typescript.md?

**Comment by bartlomieju** [comment]
I see, makes sense. I think we can land it then.

**Review by kitsonk — APPROVED** [review]
LGTM

**Pull request merged**
