### PR TITLE
feat(std): add mail parsing to std/mail

### PR DESCRIPTION
**Pull request by littledivy**
Adds support for email parsing -
- [x] `parseAddr` 
- [x] `parseDate`

Ref #7906 

https://golang.org/pkg/net/mail/

### CODE REVIEW

**Review by crypt096 — APPROVED** [review]

**Comment by lucacasonato** [comment]
@littledivy Is this ready, or are you going to add bindings for actual mail parsing too?

**Comment by littledivy** [comment]
@lucacasonato Yup it's ready - has parsing functions matching Go's std/mail and features can be added as and when there is a need for it.

**Comment by bartlomieju** [comment]
I'm -1 on this PR - adding another WASM module to std/ just for two utility functions seems like a big overkill to me. I'd be happy to add if it was broader implementation.

**Comment by lucacasonato** [comment]
I think that introducing this module for just the address and date parser is not great. We should at least be able to parse an email into structured data before this goes into std.

**Comment by littledivy** [comment]
What should I do then? I'm happy to add bindings to `parseMail` - https://docs.rs/mailparse/0.13.0/mailparse/fn.parse_mail.html or just close the PR.

**Comment by bartlomieju** [comment]
@littledivy sorry for late response. Thanks for the PR but I'd prefer not to use WASM module for this purpose. I think a TypeScript implementation would be better and I suggest coordinating with @uki00a on https://github.com/denoland/deno/pull/8413 as both functionalities are closely related. Respectfully closing without merge.

**Pull request closed without merging**
