### PR TITLE
fix(runtime): don't crash when window is deleted

### PR DESCRIPTION
**Pull request by bartlomieju**
This commit fixes an error when user deletes "window" global JS
variable. Instead of relying on "window" or "globalThis" to dispatch
"load" and "unload" events, we are default to global scope of the
worker.

Fixes https://github.com/denoland/deno/issues/13358

### CODE REVIEW

**Comment by andreubotella** [comment]
This still crashes when `globalThis` is deleted.

**Comment by bartlomieju** [comment]
> This still crashes when `globalThis` is deleted, even when incorporating #13387

I'm aware of that, preventing such crash will require bigger refactor that I'll do when I get more time.

**Comment by bartlomieju** [comment]
As @andreubotella this PR will start crashing after https://github.com/denoland/deno/pull/13387 is merged. The proper fix is to store a `v8::Global<v8::Value>` on `MainWorker`, that will point to `globalThis`. This global should be created just after bootstrapping a worker. Then when `load` and `unload` events are dispatched they should call `dispatchEvent` method directly on a `v8::Local<v8::Value>` obtained from the stored global, instead of using `self.js_runtime.execute_script()`.

**Review by dsherret — APPROVED** [review]
LGTM

**Comment by bartlomieju** [comment]
@andreubotella PTAL

**Review by andreubotella — APPROVED** [review]
LGTM

**Pull request merged**
