### PR TITLE
chore(std/wasi): enable and fix lint errors in snapshot_preview1

### PR DESCRIPTION
**Pull request by caspervonb**
On the initial merge from deno.land/x/wasi to std/wasi, linting was reduced to only pass deno lint due to a formatter/linter conflict.

This re-enables full linting for snapshot_preview1.ts.

### CODE REVIEW

**Comment by caspervonb** [comment]
Saw the camelcase rule is incoming soon'ish so I'll address that here too so hold off on merging for a bit.

**Comment by bartlomieju** [comment]
Ref https://github.com/denoland/deno_lint/pull/302

**Comment by caspervonb** [comment]
This should be good to go and unblock deno lint @bartlomieju

**Comment by bartlomieju** [comment]
> This should be good to go and unblock deno lint @bartlomieju (passes eslint with camelcase set to error at-least).

Thanks @caspervonb, we need need to address `Sha256_*` identifiers before `camelcase` can be used. That said I think this PR is fine to be landed. I will double check with linter before merging.

**Comment by caspervonb** [comment]
> Thanks @caspervonb, we need need to address Sha256_* identifiers before camelcase can be used. That said I think this PR is fine to be landed. I will double check with linter before merging.

Please do; eslint wasn't catching internal identifiers, might have configured the rule wrong when testing.

**Comment by bartlomieju** [comment]
@caspervonb just to be sure, does this PR change public interface of `std/wasi`?

**Comment by caspervonb** [comment]
Hmm actually, technically yes as the exports signature is changed ever so slightly.

Context.exports changed from records of type `Function` to `WebAssembly.ImportValue` which is a tuple.
This was always the intended type, but we didn't have it until a few patches ago.

**Comment by bartlomieju** [comment]
@caspervonb a few more lint errors:
```
(camelcase) Identifier 'wasi_snapshot_preview1' is not in camel case.
  wasi_snapshot_preview1: context.exports,
  ^^^^^^^^^^^^^^^^^^^^^^
    at /Users/biwanczuk/dev/deno/std/wasi/snapshot_preview1_test_runner.ts:16:2

(camelcase) Identifier 'data_len' is not in camel case.
          const data_len = memoryView.getUint32(iovsOffset, true);
                ^^^^^^^^
    at /Users/biwanczuk/dev/deno/std/wasi/snapshot_preview1.ts:688:16

(camelcase) Identifier 'data_len' is not in camel case.
          const data = new Uint8Array(this.memory.buffer, dataOffset, data_len);
                                                                      ^^^^^^^^
    at /Users/biwanczuk/dev/deno/std/wasi/snapshot_preview1.ts:691:70

(camelcase) Identifier 'data_len' is not in camel case.
          const data_len = memoryView.getUint32(iovsOffset, true);
                ^^^^^^^^
    at /Users/biwanczuk/dev/deno/std/wasi/snapshot_preview1.ts:765:16

(camelcase) Identifier 'data_len' is not in camel case.
          const data = new Uint8Array(this.memory.buffer, dataOffset, data_len);
                                                                      ^^^^^^^^
    at /Users/biwanczuk/dev/deno/std/wasi/snapshot_preview1.ts:768:70

(camelcase) Identifier 'data_len' is not in camel case.
          const data_len = memoryView.getUint32(iovsOffset, true);
                ^^^^^^^^
    at /Users/biwanczuk/dev/deno/std/wasi/snapshot_preview1.ts:796:16

(camelcase) Identifier 'data_len' is not in camel case.
          const data = new Uint8Array(this.memory.buffer, dataOffset, data_len);
                                                                      ^^^^^^^^
    at /Users/biwanczuk/dev/deno/std/wasi/snapshot_preview1.ts:799:70

(camelcase) Identifier 'data_len' is not in camel case.
          const data_len = memoryView.getUint32(iovsOffset, true);
                ^^^^^^^^
    at /Users/biwanczuk/dev/deno/std/wasi/snapshot_preview1.ts:968:16

(camelcase) Identifier 'data_len' is not in camel case.
          const data = new Uint8Array(this.memory.buffer, dataOffset, data_len);
                                                                      ^^^^^^^^
    at /Users/biwanczuk/dev/deno/std/wasi/snapshot_preview1.ts:971:70
```

**Review by bartlomieju — APPROVED** [review]
LGTM, thanks @caspervonb

**Pull request merged**
