### PR TITLE
Add sync permissions

### PR DESCRIPTION
**Pull request by cknight**
A proposed solution for #6388

### CODE REVIEW

**Comment by ry** [comment]
But this isn't part of the spec https://w3c.github.io/permissions/#permissions-interface ...

**Comment by cknight** [comment]
Yes.  This somewhat speculative PR was focused on extending the existing spec, retaining compliance with it while at the same time exposing sync alternatives. I fully understand if you don't want to take this approach (in which case please close without merge), though I'd be interested if you had any alternative suggestions for exposing a synchronous method for accessing permissions.

**Comment by bartlomieju** [comment]
@cknight do you have some specific use case that requires sync permissions? I can imagine situation that sync APIs would be useful, but as with other APIs we should refrain from adding them unless there's a real world use case

**Comment by cknight** [comment]
@bartlomieju I first encountered this problem in a personal project where I needed to get the value of an environment variable in a constructor, but wanted to check first if the permission had been granted.  Constructors are synchronous and therefore I could not use the permissions API there. There are workarounds for this of course, but it is unnecessarily limiting, especially so when the underlying ops call is synchronous.  Another use case would be embedding a permissions call into an existing workflow.  Imagine that module a calls module b, calls module c, calls function d, calls function e, etc.  all in a synchronous nature.  If within 'e' or below, you want to embed a permission call you have to retrofit a,b,c,d,e, etc. with async and consider any implications of doing so. This is a poor user experience.

**Comment by bartlomieju** [comment]
@cknight thanks for the clear examples, the constructor case is a especially stark.

**Comment by kitsonk** [comment]
I don't think we should introduce this. We should keep alignment to the browser APIs, IMO.

**Comment by cknight** [comment]
Closing due to lack of interest and support.  I still believe that the current async only permissions model, though it is a compliant web standard, gives a poor user experience.  Perhaps another way forward can be found.

**Comment by ry** [comment]
@cknight Thanks for the effort. I'm sorry for not landing this. It's often frustrating working within the standard APIs - but I think in the long run it will pay to be cautious...

**Comment by cknight** [comment]
No worries @ry, fully understand. For info I've left the related issue open to capture other thoughts or ideas on this space.

**Pull request closed without merging**
