### PR TITLE
fix: panic in bundler

### PR DESCRIPTION
**Pull request by bartlomieju**
Fixes https://github.com/denoland/deno/issues/8166

Need to come up with test

### CODE REVIEW

**Comment by bartlomieju** [comment]
@kitsonk could you take over this PR?

**Review by kitsonk — COMMENTED** [review]
Still needs a test... 😄

**Comment by jveres** [comment]
test.ts

```typescript
function Decorator() {
  return function (
    target: Record<string, any>,
    propertyKey: string,
    descriptor: TypedPropertyDescriptor<any>,
  ) {
    const originalFn: Function = descriptor.value as Function;
    descriptor.value = async function (...args: any[]) {
      return await originalFn.apply(this, args)
    };
    return descriptor;
  };
}

class SomeClass {
  @Decorator()
  async test(): Promise<void> {}
}

new SomeClass().test();
```

```sh
deno bundle test.ts test.bundle.js      
Bundle file:///Users/U715864/temp/test.ts
Check file:///Users/U715864/temp/test.ts
thread 'main' panicked at 'cannot access a scoped thread local variable without calling `set` first', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:168:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by bartlomieju** [comment]
Thanks @jveres I added your test case

**Comment by jveres** [comment]
```typescript
// deno-lint-ignore-file no-explicit-any
```
should be added to the top of `test.ts` to pass linter checks (cc @bartlomieju)

**Comment by jveres** [comment]
thanks @bartlomieju, now I hope it find its way into `1.5.1`

**Review by crypt096 — APPROVED** [review]

**Review by kitsonk — APPROVED** [review]
LGTM

**Pull request merged**
