### PR TITLE
BREAKING(std): Move std/testing/asserts.ts to std/assert/mod.ts

### LINKED ISSUE #6104: Move std/testing/asserts.ts to std/assert/mod.ts
The `testing` prefix is more noisy than helpful. `std/testing/bench.ts` should be moved out as well.

- `std/testing/asserts.ts` -> `std/assert/mod.ts`
- `std/testing/diff.ts` -> `std/assert/_diff.ts`
- `std/testing/bench.ts` -> `std/bench/mod.ts`

### PR DESCRIPTION
**Pull request by nayeemrmn**
- Move `std/testing/bench.ts` to `std/bench/mod.ts`.
- Privatize `std/testing/diff.ts` to `std/assert/_diff.ts`

Closes #6104.

### CODE REVIEW

**Comment by littletof** [comment]
Just a heads up, benching changed in #6175 since the PR was opened.

**Comment by nayeemrmn** [comment]
@ry Any decision on this? Please review.

**Comment by bartlomieju** [comment]
I'm torn on this one... 

On one hand I agree with @kitsonk's opinion in https://github.com/denoland/deno/issues/5684; it's silly and needlessly cumbersome to have to import `std/` just to use `assert`. It should be available in the main runtime without additional imports.

On the other hand I agree with @nayeemrmn that `std/testing` is more noisy than helpful...

I also agree with @ry that we could do `std/assert.ts`, but that gives a precedent to start adding more single-file top level modules - the next obvious one would be `std/bench.ts`.

Here's my proposal:
- add `Deno.assert()` method - even with the downside described in https://github.com/denoland/deno/issues/5684
- rename `std/testing/` to `std/test/` - fewer letters, module's purpose is obvious, not adding single file top level module

**Comment by nayeemrmn** [comment]
> add Deno.assert() method

I don't think `Deno.assert()` is strictly related to this change, but see https://github.com/denoland/deno/pull/6252#issuecomment-649196133 as well. The summary of my disagreement is that a simple assertion is non-specific enough to Deno's problem-space for it to be an upstream issue with ECMAScript or the Web.
1. Will an `assert()` construct be added upstream in the future?
2. If not, why? Does Deno have any self-specific cause to override that?

**Comment by kitsonk** [comment]
@nayeemrmn in my PR, I have moved it to the Deno namespace because I was under the mistaken expression there was precedence in Node.js, there isn't.  I think it being in the Deno namespace makes more sense, and just requires a type annotation to be "re-exported" elsewhere.

That gives me what I feel is lacking, the ability to use assert style coding for non-testing code (as well as exposes an `AssertionError` type built into Deno).  After that, I am perfectly fine breaking it out in `std` because it is arguable that assertions and testing are two different things.  If we don't put `Deno.assert()` in, then I would want there to be `std/assert/assert.ts` which contains `assert()` and `AssertionError` as well as `std/assert/mod.ts` because I don't want to drag in a half a dozen modules with pretty printing and colours to just be able to use `assert()` in my functional code.

**Comment by ry** [comment]
I'm also conflicted on this... ([See comment](https://github.com/denoland/deno/issues/6104#issuecomment-638899545)) I think we should hold off merging until we can arrive at some consensus about how to organize the asserts module.

**Comment by bartlomieju** [comment]
@nayeemrmn I'm gonna close this PR without merge, sorry for wasted effort. It seems we haven't reached any consensus and it's very much out-of-date.

**Pull request closed without merging**
