### PR TITLE
WIP: feat(std/node): Added querystring builtin

### PR DESCRIPTION
**Pull request by lucacasonato**
From https://github.com/mike-spainhower/querystring

### CODE REVIEW

**Comment by ecyrbe** [comment]
Hi, these seems to be missing :
- escape
- unescape

**Comment by lucacasonato** [comment]
> Hi, these seems to be missing :
> 
> * escape
> * unescape

Correct, because https://github.com/mike-spainhower/querystring does not implement them. I realized that this all does not work particularly well with strict mode right now, so I have to update some things anyway.

**Comment by kevinkassimo** [comment]
Note a similar attempt was made in https://github.com/denoland/deno/pull/3485 .
That PR is closed due to being stale. Note I do agree for pure compatibility concerns we should polyfill it anyways.

**Comment by kevinkassimo** [comment]
Oh as to `escape` and `unescape`, I believe we already have implementation available from `window.escape` and `window.unescape`.

**Comment by lucacasonato** [comment]
I can't get this to work atm - I'll try again later. To do this probably involves rewriting this polyfill for ES6.

**Pull request closed without merging**
