### PR TITLE
feat(ext/ffi): Improve FFI types

### PR DESCRIPTION
**Pull request by aapoalas**
Few improvements to FFI types:
1. Export `PointerObject` for convenience. It's fairly commonly used in library code and thus should be exported.
2. Fix various comments around `PointerValue` and `UnsafePointer` and expand upon them to better reflect reality.
3. Instead of using a `Record<"value", type>[T]` for determining the type of an FFI symbol parameter use direct `T extends "value" ? type : never` comparison.

The last part enables smuggling extra information into the parameter and return value string declarations at the type level. eg. Instead of just `"u8"` the parameter can be `"u8" & { [brand]: T }` for some `T extends number`. That `T` can then be extracted from the parameter to form the TypeScript function's parameter or return value type. Essentially, this enables type-safe FFI!

The foremost use-cases for this are enums and pointer safety. These are implemented in the second commit which should enable, in a backwards compatible way, for pointer parameters to declare what sort of pointer they mean, functions to declare what the API definition of the native function is, and for numbers to declare what Enum they stand for (if any).

### CODE REVIEW

**Review by bartlomieju — COMMENTED** [review]
LGTM, but should we wait until v1.37 to release this?

**Comment by aapoalas** [comment]
> LGTM, but should we wait until v1.37 to release this?

I'll try get some feedback from frequent FFI users. This should be a backwards-compatible change with no breaks so I think it should be okay to include in a patch version but I'll see if eg. loading wouldn't test this for me.

**Comment by load1n9** [comment]
Tested and LGTM

**Comment by load1n9** [comment]
> > LGTM, but should we wait until v1.37 to release this?
> 
> I'll try get some feedback from frequent FFI users. This should be a backwards-compatible change with no breaks so I think it should be okay to include in a patch version but I'll see if eg. loading wouldn't test this for me.

Tested and LGTM

**Review by littledivy — APPROVED** [review]
LGTM, I'm in favour of landing this in a patch release.

**Pull request merged**
