### PR TITLE
fix(cli/colors): color mismatch

### LINKED ISSUE #7358: Slight mismatch between crate::colors and rt/colors
Minor but seems that crate::colors use the bright variants where-as our rt utils use the regular colors.

Screenshot 2020-09-04 at 12 58 01 PM

### PR DESCRIPTION
**Pull request by EathonYe**
fixes #7358

### CODE REVIEW

**Review by caspervonb — CHANGES_REQUESTED** [review]
In the ansi range used here, 0 is black which is the wrong value for gray.

**Comment by EathonYe** [comment]
Thanks for you suggestion, i will fix it.

**Comment by EathonYe** [comment]
I'm sorry, i don't know how to revert my commits what is unnecessary, so i‘m going to resubmit pr.

**Comment by caspervonb** [comment]
> i don't know how to revert my commits what is unnecessary

```
git revert <hash>
```

Or you can just manually revert the change in your editor as a new commit, we squash everything into a single commit anyways :)

**Pull request closed without merging**
