### PR TITLE
Hide line with value zero

### PR DESCRIPTION
**Pull request by kanishkarj**
There are some benchmarks that show up as zero values. So it looks like something was very zero and then jumped. This PR just hides that line.

### CODE REVIEW

**Comment by kevinkassimo** [comment]
@kanishkarj Good point. Could you run `./tools/format.py` and `./tools/lint.py` for this PR?

**Comment by kanishkarj** [comment]
Is it required? Because I made changes to the "gh-pages" branch, and that branch doesn't have the tools folder.

**Comment by kanishkarj** [comment]
executing format.py leads to error.

**Comment by liangchunn** [comment]
@kanishkarj 
AFAIK deno uses prettier in default settings to format .js/.ts files, but the tooling is missing in the `gh-branch` branch in the project.

You can do this manually by executing the following in the `gh-pages` branch:
```
$ npm install --global prettier
$ prettier --write *.js
```

**Comment by kanishkarj** [comment]
Oh, thanks a lot !:)

**Comment by kanishkarj** [comment]
I ran the prettier command. Also, shall I add a grunt/gulp task to do it? might be helpful over time.

**Comment by ry** [comment]
@kanishkarj We don't use grunt/gulp. Please rebase your branch on master so the CI can run.

**Comment by kanishkarj** [comment]
I have rebased it. I am not sure what I am supposed to do next, please look into it and let me know

**Comment by kevinkassimo** [comment]
@kanishkarj Hmm, I am not sure either why the checks are still not running (probably some mysterious side effects from CLAassistant). In worst case you could choose to close this and open another issue.

**Comment by kanishkarj** [comment]
@kevinkassimo how do I know if it has been rebased successfully ? can you check, please.

**Comment by ry** [comment]
@kanishkarj  I’m not sure why CI isn’t running but could you please open a new PR . I will close this one . Maybe that will fix it. Thanks

**Pull request closed without merging**
