### PR TITLE
fix(lock): add --no-lock flag to disable auto discovery of lock file

### PR DESCRIPTION
**Pull request by bartlomieju**

### CODE REVIEW

**Review by dsherret — APPROVED** [review]
LGTM

**Comment by ry** [comment]
In which situation did this come up? Does Cargo have something like this?

**Comment by jsejcksn** [comment]
> In which situation did this come up?

Inquiry/request at https://github.com/denoland/deno/pull/16498#issuecomment-1301727204

**Comment by dsherret** [comment]
I'm not sure cargo is a good analogue here because in our case you can have one-off remote scripts or npm package commands that could contribute to the lockfile that you don't want to. It's nice to have a way to opt out of automatically opted into behaviour, it's analogous to `--no-config`, and this is low effort to maintain.

**Pull request merged**
