### PR TITLE
fix: exit process on panic in a tokio task

### LINKED ISSUE #11567: Consider using panic hook to exit deno process on panic
In Deploy, we use a panic hook to exit the process whenever a panic occurs.

```
let orig_hook = std::panic::take_hook();
std::panic::set_hook(Box::new(move |panic_info| {
  orig_hook(panic_info);
  std::process::exit(1);
}));
```

It might be useful for us to implement a similar panic hook in Deno in order to change the default behaviour of tokio.

Right now we do `.await.unwrap()` on the returned `JoinHandle` from created tasks in most places though, which would cause the process to exit. I have not investigated how this would affect those areas (we could look into it and see how we could have similar output). This might be not that big of a deal and perhaps alternatively we could change everywhere that doesn't exit on panic to exit on panic then be diligent about this in the future (somewhat error prone).

Related #9263

### LINKED ISSUE #11937: Signal test failing on Windows but not causing test failure
This can been seen in all current builds for example https://github.com/denoland/deno/runs/3528022235
```
2021-09-06T21:37:26.8941171Z test runStdinPiped ... [0m[32mok[0m [0m[38;5;8m(44ms)[0m
2021-09-06T21:37:26.9360119Z test runStdoutPiped ... [0m[32mok[0m [0m[38;5;8m(42ms)[0m
2021-09-06T21:37:26.9770009Z test runStderrPiped ... [0m[32mok[0m [0m[38;5;8m(41ms)[0m
2021-09-06T21:37:27.0159714Z test runOutput ... [0m[32mok[0m [0m[38;5;8m(39ms)[0m
2021-09-06T21:37:27.0564044Z test runStderrOutput ... [0m[32mok[0m [0m[38;5;8m(40ms)[0m
2021-09-06T21:37:27.0799992Z test integration::lsp::lsp_hover_change_mbc ... ok
2021-09-06T21:37:27.1128373Z test runRedirectStdoutStderr ... [0m[32mok[0m [0m[38;5;8m(54ms)[0m
2021-09-06T21:37:27.1597300Z test runRedirectStdin ... [0m[32mok[0m [0m[38;5;8m(48ms)[0m
2021-09-06T21:37:27.2034679Z test runEnv ... [0m[32mok[0m [0m[38;5;8m(44ms)[0m
2021-09-06T21:37:27.2110712Z test runClose ... [0m[32mok[0m [0m[38;5;8m(8ms)[0m
2021-09-06T21:37:27.2428136Z hello
2021-09-06T21:37:27.2524548Z ##[error]thread '<unnamed>' panicked at 'not implemented', runtime\ops\signal.rs:135:3
2021-09-06T21:37:27.2541946Z stack backtrace:
2021-09-06T21:37:27.3119199Z    0:     0x7ff6b1f2ef24 - std::backtrace_rs::backtrace::dbghelp::trace
2021-09-06T21:37:27.3121211Z                                at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
2021-09-06T21:37:27.3122771Z    1:     0x7ff6b1f2ef24 - std::backtrace_rs::backtrace::trace_unsynchronized
2021-09-06T21:37:27.3124577Z                                at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
2021-09-06T21:37:27.3126052Z    2:     0x7ff6b1f2ef24 - std::sys_common::backtrace::_print_fmt
2021-09-06T21:37:27.3127506Z                                at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\sys_common\backtrace.rs:67
2021-09-06T21:37:27.3129273Z    3:     0x7ff6b1f2ef24 - std::sys_common::backtrace::_print::***impl***::fmt
2021-09-06T21:37:27.3130762Z                                at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\sys_common\backtrace.rs:46
2021-09-06T21:37:27.3148842Z    4:     0x7ff6b1673dea - core::fmt::write
2021-09-06T21:37:27.3150238Z                                at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\core\src\fmt\mod.rs:1110
2021-09-06T21:37:27.3153996Z    5:     0x7ff6b1f2d768 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
2021-09-06T21:37:27.3155551Z                                at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\io\mod.rs:1588
2021-09-06T21:37:27.3159700Z    6:     0x7ff6b1f2dff2 - std::sys_common::backtrace::_print
2021-09-06T21:37:27.3161247Z                                at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\sys_common\backtrace.rs:49
2021-09-06T21:37:27.3164830Z    7:     0x7ff6b1f2dff2 - std::sys_common::backtrace::print
2021-09-06T21:37:27.3166432Z                                at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\sys_common\backtrace.rs:36
2021-09-06T21:37:27.3168734Z    8:     0x7ff6b1f2dff2 - std::panicking::default_hook::***closure***
2021-09-06T21:37:27.3170249Z                                at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\panicking.rs:208
2021-09-06T21:37:27.3176768Z    9:     0x7ff6b1f2d192 - std::panicking::default_hook
2021-09-06T21:37:27.3178222Z                                at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\panicking.rs:225
2021-09-06T21:37:27.3181760Z   10:     0x7ff6b1f2d192 - std::panicking::rust_panic_with_hook
2021-09-06T21:37:27.3183299Z                                at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\panicking.rs:622
2021-09-06T21:37:27.3195948Z   11:     0x7ff6b1f353cb - std::panicking::begin_panic_handler::***closure***
2021-09-06T21:37:27.3197495Z                                at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\panicking.rs:517
2021-09-06T21:37:27.3199114Z   12:     0x7ff6b1f3534f - std::sys_common::backtrace::__rust_end_short_backtrace<closure-0,!>
2021-09-06T21:37:27.3200659Z                                at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\sys_common\backtrace.rs:141
2021-09-06T21:37:27.3202171Z   13:     0x7ff6b1f352ef - std::panicking::begin_panic_handler
2021-09-06T21:37:27.3203556Z                                at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\panicking.rs:515
2021-09-06T21:37:27.3205101Z   14:     0x7ff6b2fbbc90 - core::panicking::panic_fmt
2021-09-06T21:37:27.3207589Z                                at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\core\src\panicking.rs:92
2021-09-06T21:37:27.3208923Z   15:     0x7ff6b2fbbbdc - core::panicking::panic
2021-09-06T21:37:27.3210299Z                                at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\core\src\panicking.rs:50
2021-09-06T21:37:27.3301803Z   16:     0x7ff6b197867c - core::alloc::layout::***impl***::fmt
2021-09-06T21:37:27.3398564Z   17:     0x7ff6b197840a - core::alloc::layout::***impl***::fmt
2021-09-06T21:37:27.3487920Z   18:     0x7ff6b18c4102 - core::alloc::layout::***impl***::fmt
2021-09-06T21:37:27.3500893Z   19:     0x7ff6b16ad726 - core::alloc::layout::***impl***::fmt
2021-09-06T21:37:27.3517851Z   20:     0x7ff6b16b1b9e - core::alloc::layout::***impl***::fmt
2021-09-06T21:37:27.3520445Z   21:     0x7ff6b2501cf2 - v8::internal::FunctionCallbackArguments::Call
2021-09-06T21:37:27.3521912Z                                at .\..\..\..\..\v8\src\api\api-arguments-inl.h:152
2021-09-06T21:37:27.3523407Z   22:     0x7ff6b25011cb - v8::internal::`anonymous namespace'::HandleApiCallHelper<0>
2021-09-06T21:37:27.3524707Z                                at .\..\..\..\..\v8\src\builtins\builtins-api.cc:112
2021-09-06T21:37:27.3527252Z   23:     0x7ff6b25006fe - v8::internal::Builtin_Impl_HandleApiCall
2021-09-06T21:37:27.3528214Z                                at .\..\..\..\..\v8\src\builtins\builtins-api.cc:142
2021-09-06T21:37:27.3529096Z   24:     0x7ff6b2500337 - v8::internal::Builtin_HandleApiCall
2021-09-06T21:37:27.3530535Z                                at .\..\..\..\..\v8\src\builtins\builtins-api.cc:130
2021-09-06T21:37:27.3531668Z   25:     0x7ff6b2de2e7c - Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit
2021-09-06T21:37:27.3532859Z   26:      0x1dd000871e1 - <unknown>
2021-09-06T21:37:27.3533609Z   27:      0x1dd00087357 - <unknown>
2021-09-06T21:37:27.3534963Z   28:     0x7ff6b2d707e0 - Builtins_InterpreterEntryTrampoline
2021-09-06T21:37:27.3536140Z   29:     0x7ff6b2d707e0 - Builtins_InterpreterEntryTrampoline
2021-09-06T21:37:27.3537308Z   30:     0x7ff6b2d707e0 - Builtins_InterpreterEntryTrampoline
2021-09-06T21:37:27.3538717Z   31:     0x7ff6b2da1f41 - Builtins_AsyncFunctionAwaitResolveClosure
2021-09-06T21:37:27.3539971Z   32:     0x7ff6b2e2e0b8 - Builtins_PromiseFulfillReactionJob
2021-09-06T21:37:27.3540971Z   33:     0x7ff6b2d936f0 - Builtins_RunMicrotasks
2021-09-06T21:37:27.3542072Z   34:     0x7ff6b2d6e75b - Builtins_JSRunMicrotasksEntry
2021-09-06T21:37:27.3543124Z   35:     0x7ff6b22fa113 - v8::internal::`anonymous namespace'::Invoke
2021-09-06T21:37:27.3544121Z                                at .\..\..\..\..\v8\src\execution\execution.cc:391
2021-09-06T21:37:27.3545492Z   36:     0x7ff6b22fa825 - v8::internal::`anonymous namespace'::InvokeWithTryCatch
2021-09-06T21:37:27.3546577Z                                at .\..\..\..\..\v8\src\execution\execution.cc:436
2021-09-06T21:37:27.3547589Z   37:     0x7ff6b22fa92f - v8::internal::Execution::TryRunMicrotasks
2021-09-06T21:37:27.3548622Z                                at .\..\..\..\..\v8\src\execution\execution.cc:513
2021-09-06T21:37:27.3549924Z   38:     0x7ff6b23ddf58 - v8::internal::MicrotaskQueue::RunMicrotasks
2021-09-06T21:37:27.3551026Z                                at .\..\..\..\..\v8\src\execution\microtask-queue.cc:173
2021-09-06T21:37:27.3552243Z   39:     0x7ff6b23ddd43 - v8::internal::MicrotaskQueue::PerformCheckpointInternal
2021-09-06T21:37:27.3553458Z                                at .\..\..\..\..\v8\src\execution\microtask-queue.cc:126
2021-09-06T21:37:27.3554962Z   40:     0x7ff6b228fa45 - v8::internal::Isolate::FireCallCompletedCallbackInternal
2021-09-06T21:37:27.3556175Z                                at .\..\..\..\..\v8\src\execution\isolate.cc:4240
2021-09-06T21:37:27.3561543Z   41:     0x7ff6b2207801 - v8::Function::Call
2021-09-06T21:37:27.3562507Z                                at .\..\..\..\..\v8\src\api\api.cc:5095
2021-09-06T21:37:27.3567475Z   42:     0x7ff6b21f1e4b - v8__Function__Call
2021-09-06T21:37:27.3568763Z                                at .\..\..\..\..\src\binding.cc:1546
2021-09-06T21:37:27.3676291Z   43:     0x7ff6b1efd3d3 - rustc_demangle::try_demangle
2021-09-06T21:37:27.3713129Z   44:     0x7ff6b16c0472 - core::alloc::layout::***impl***::fmt
2021-09-06T21:37:27.3726718Z   45:     0x7ff6b125518b - main
2021-09-06T21:37:27.3734655Z   46:     0x7ff6b12542ab - main
2021-09-06T21:37:27.3739475Z   47:     0x7ff6b1253bec - main
2021-09-06T21:37:27.3744203Z   48:     0x7ff6b1252e77 - main
2021-09-06T21:37:27.3749508Z   49:     0x7ff6b1253a70 - main
2021-09-06T21:37:27.3753323Z   50:     0x7ff6b1f4f8eb - alloc::boxed::***impl***::call_once
2021-09-06T21:37:27.3754586Z                                at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\library\alloc\src\boxed.rs:1575
2021-09-06T21:37:27.3756464Z   51:     0x7ff6b1f4f8eb - alloc::boxed::***impl***::call_once
2021-09-06T21:37:27.3757731Z                                at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\library\alloc\src\boxed.rs:1575
2021-09-06T21:37:27.3759064Z   52:     0x7ff6b1f4f8eb - std::sys::windows::thread::***impl***::new::thread_start
2021-09-06T21:37:27.3760356Z                                at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\sys\windows\thread.rs:56
2021-09-06T21:37:27.3775283Z   53:     0x7ffa1eaa7974 - BaseThreadInitThunk
2021-09-06T21:37:27.3798225Z   54:     0x7ffa2101a2f1 - RtlUserThreadStart
2021-09-06T21:37:27.3818745Z ##[error]thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Any *** .. ***', cli\tools\test.rs:626:28
2021-09-06T21:37:27.3820676Z stack backtrace:
2021-09-06T21:37:27.3821516Z    0:     0x7ff6b1f2ef24 - std::backtrace_rs::backtrace::dbghelp::trace
2021-09-06T21:37:27.3822962Z                                at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
2021-09-06T21:37:27.3825426Z    1:     0x7ff6b1f2ef24 - std::backtrace_rs::backtrace::trace_unsynchronized
2021-09-06T21:37:27.3826811Z                                at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
2021-09-06T21:37:27.3828019Z    2:     0x7ff6b1f2ef24 - std::sys_common::backtrace::_print_fmt
2021-09-06T21:37:27.3829277Z                                at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\sys_common\backtrace.rs:67
2021-09-06T21:37:27.3830519Z    3:     0x7ff6b1f2ef24 - std::sys_common::backtrace::_print::***impl***::fmt
2021-09-06T21:37:27.3831797Z                                at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\sys_common\backtrace.rs:46
2021-09-06T21:37:27.3833073Z    4:     0x7ff6b1673dea - core::fmt::write
2021-09-06T21:37:27.3834196Z                                at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\core\src\fmt\mod.rs:1110
2021-09-06T21:37:27.3835463Z    5:     0x7ff6b1f2d768 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
2021-09-06T21:37:27.3836671Z                                at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\io\mod.rs:1588
2021-09-06T21:37:27.3837878Z    6:     0x7ff6b1f2dff2 - std::sys_common::backtrace::_print
2021-09-06T21:37:27.3839116Z                                at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\sys_common\backtrace.rs:49
2021-09-06T21:37:27.3840402Z    7:     0x7ff6b1f2dff2 - std::sys_common::backtrace::print
2021-09-06T21:37:27.3841631Z                                at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\sys_common\backtrace.rs:36
2021-09-06T21:37:27.3843641Z    8:     0x7ff6b1f2dff2 - std::panicking::default_hook::***closure***
2021-09-06T21:37:27.3845048Z                                at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\panicking.rs:208
2021-09-06T21:37:27.3850948Z    9:     0x7ff6b1f2d192 - std::panicking::default_hook
2021-09-06T21:37:27.3852362Z                                at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\panicking.rs:225
2021-09-06T21:37:27.3855971Z   10:     0x7ff6b1f2d192 - std::panicking::rust_panic_with_hook
2021-09-06T21:37:27.3857255Z                                at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\panicking.rs:622
2021-09-06T21:37:27.3858623Z   11:     0x7ff6b1f353f5 - std::panicking::begin_panic_handler::***closure***
2021-09-06T21:37:27.3859872Z                                at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\panicking.rs:519
2021-09-06T21:37:27.3861380Z   12:     0x7ff6b1f3534f - std::sys_common::backtrace::__rust_end_short_backtrace<closure-0,!>
2021-09-06T21:37:27.3862716Z                                at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\sys_common\backtrace.rs:141
2021-09-06T21:37:27.3863880Z   13:     0x7ff6b1f352ef - std::panicking::begin_panic_handler
2021-09-06T21:37:27.3865151Z                                at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\panicking.rs:515
2021-09-06T21:37:27.3866457Z   14:     0x7ff6b2fbbc90 - core::panicking::panic_fmt
2021-09-06T21:37:27.3867627Z                                at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\core\src\panicking.rs:92
2021-09-06T21:37:27.3868703Z   15:     0x7ff6b2fbc3f3 - core::result::unwrap_failed
2021-09-06T21:37:27.3869872Z                                at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\core\src\result.rs:1355
2021-09-06T21:37:27.3870863Z   16:     0x7ff6b12533da - main
2021-09-06T21:37:27.3874510Z   17:     0x7ff6b1252e77 - main
2021-09-06T21:37:27.3879410Z   18:     0x7ff6b1252894 - main
2021-09-06T21:37:27.3935270Z   19:     0x7ff6b210f6f7 - core::core_arch::x86::xsave::_xgetbv
2021-09-06T21:37:27.3990095Z   20:     0x7ff6b2116c1e - core::core_arch::x86::xsave::_xgetbv
2021-09-06T21:37:27.3994571Z   21:     0x7ff6b1252e77 - main
2021-09-06T21:37:27.4049821Z   22:     0x7ff6b211732d - core::core_arch::x86::xsave::_xgetbv
2021-09-06T21:37:27.4052523Z   23:     0x7ff6b1f4f8eb - alloc::boxed::***impl***::call_once
2021-09-06T21:37:27.4053793Z                                at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\library\alloc\src\boxed.rs:1575
2021-09-06T21:37:27.4056252Z   24:     0x7ff6b1f4f8eb - alloc::boxed::***impl***::call_once
2021-09-06T21:37:27.4057610Z                                at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\library\alloc\src\boxed.rs:1575
2021-09-06T21:37:27.4058985Z   25:     0x7ff6b1f4f8eb - std::sys::windows::thread::***impl***::new::thread_start
2021-09-06T21:37:27.4060464Z                                at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\sys\windows\thread.rs:56
2021-09-06T21:37:27.4061562Z   26:     0x7ffa1eaa7974 - BaseThreadInitThunk
2021-09-06T21:37:27.4062418Z   27:     0x7ffa2101a2f1 - RtlUserThreadStart
2021-09-06T21:37:27.4609370Z test runKillAfterStatus ...running 1 test from file:///D:/a/***/***/cli/tests/unit/progressevent_test.ts
2021-09-06T21:37:27.6142251Z test progressEventConstruct ... [0m[32mok[0m [0m[38;5;8m(7ms)[0m
2021-09-06T21:37:27.6834904Z running 10 tests from file:///D:/a/***/***/cli/tests/unit/read_dir_test.ts
2021-09-06T21:37:27.8732168Z test readDirSyncSuccess ... [0m[32mok[0m [0m[38;5;8m(68ms)[0m
2021-09-06T21:37:27.8754543Z test readDirSyncWithUrl ... [0m[32mok[0m [0m[38;5;8m(127ms)[0m
2021-09-06T21:37:27.8908201Z test readDirSyncPerm ... [0m[32mok[0m [0m[38;5;8m(15ms)[0m
2021-09-06T21:37:27.9136687Z test readDirSyncNotDir ... [0m[32mok[0m [0m[38;5;8m(13ms)[0m
```

### PR DESCRIPTION
**Pull request by dsherret**
Tokio does not exit the process when a task panics, so this change exits the process when any panic occurs.

Closes #11567
Closes #11937

Edit: As shown in the CI, we now get the desired behaviour and the CI fails.

```
hello
Error: thread '<unnamed>' panicked at 'not implemented', runtime\ops\signal.rs:135:3
stack backtrace:
   0:     0x7ff6605cf8d4 - std::backtrace_rs::backtrace::dbghelp::trace
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
   1:     0x7ff6605cf8d4 - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff6605cf8d4 - std::sys_common::backtrace::_print_fmt
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\sys_common\backtrace.rs:67
   3:     0x7ff6605cf8d4 - std::sys_common::backtrace::_print::{{impl}}::fmt
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\sys_common\backtrace.rs:46
   4:     0x7ff65fd13b8a - core::fmt::write
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\core\src\fmt\mod.rs:1110
   5:     0x7ff6605cdb58 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\io\mod.rs:1588
   6:     0x7ff6605ce9a2 - std::sys_common::backtrace::_print
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\sys_common\backtrace.rs:49
   7:     0x7ff6605ce9a2 - std::sys_common::backtrace::print
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\sys_common\backtrace.rs:36
   8:     0x7ff6605ce9a2 - std::panicking::default_hook::{{closure}}
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\panicking.rs:208
   9:     0x7ff6605cdfd2 - std::panicking::default_hook
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\panicking.rs:225
  10:     0x7ff65fcc9bb8 - main
  11:     0x7ff6605cd98f - std::panicking::rust_panic_with_hook
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\panicking.rs:626
  12:     0x7ff6605d5d7b - std::panicking::begin_panic_handler::{{closure}}
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\panicking.rs:517
  13:     0x7ff6605d5cff - std::sys_common::backtrace::__rust_end_short_backtrace<closure-0,!>
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\sys_common\backtrace.rs:141
  14:     0x7ff6605d5c9f - std::panicking::begin_panic_handler
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\panicking.rs:515
  15:     0x7ff66165c650 - core::panicking::panic_fmt
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\core\src\panicking.rs:92
  16:     0x7ff66165c59c - core::panicking::panic
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\core\src\panicking.rs:50
  17:     0x7ff66001841c - core::alloc::layout::{{impl}}::fmt
  18:     0x7ff6600181aa - core::alloc::layout::{{impl}}::fmt
  19:     0x7ff65ff63ea2 - core::alloc::layout::{{impl}}::fmt
  20:     0x7ff65fd4d4c6 - core::alloc::layout::{{impl}}::fmt
  21:     0x7ff65fd5193e - core::alloc::layout::{{impl}}::fmt
  22:     0x7ff660ba26b2 - v8::internal::FunctionCallbackArguments::Call
                               at .\..\..\..\..\v8\src\api\api-arguments-inl.h:152
  23:     0x7ff660ba1b8b - v8::internal::`anonymous namespace'::HandleApiCallHelper<0>
                               at .\..\..\..\..\v8\src\builtins\builtins-api.cc:112
  24:     0x7ff660ba10be - v8::internal::Builtin_Impl_HandleApiCall
                               at .\..\..\..\..\v8\src\builtins\builtins-api.cc:142
  25:     0x7ff660ba0cf7 - v8::internal::Builtin_HandleApiCall
                               at .\..\..\..\..\v8\src\builtins\builtins-api.cc:130
  26:     0x7ff66148383c - Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit
  27:      0x3df000871e1 - <unknown>
  28:      0x3df00087357 - <unknown>
  29:     0x7ff6614111a0 - Builtins_InterpreterEntryTrampoline
  30:     0x7ff6614111a0 - Builtins_InterpreterEntryTrampoline
  31:     0x7ff6614111a0 - Builtins_InterpreterEntryTrampoline
  32:     0x7ff661442901 - Builtins_AsyncFunctionAwaitResolveClosure
  33:     0x7ff6614cea78 - Builtins_PromiseFulfillReactionJob
  34:     0x7ff6614340b0 - Builtins_RunMicrotasks
  35:     0x7ff66140f11b - Builtins_JSRunMicrotasksEntry
  36:     0x7ff66099aad3 - v8::internal::`anonymous namespace'::Invoke
                               at .\..\..\..\..\v8\src\execution\execution.cc:391
  37:     0x7ff66099b1e5 - v8::internal::`anonymous namespace'::InvokeWithTryCatch
                               at .\..\..\..\..\v8\src\execution\execution.cc:436
  38:     0x7ff66099b2ef - v8::internal::Execution::TryRunMicrotasks
                               at .\..\..\..\..\v8\src\execution\execution.cc:513
  39:     0x7ff660a7e918 - v8::internal::MicrotaskQueue::RunMicrotasks
                               at .\..\..\..\..\v8\src\execution\microtask-queue.cc:173
  40:     0x7ff660a7e703 - v8::internal::MicrotaskQueue::PerformCheckpointInternal
                               at .\..\..\..\..\v8\src\execution\microtask-queue.cc:126
  41:     0x7ff660930405 - v8::internal::Isolate::FireCallCompletedCallbackInternal
                               at .\..\..\..\..\v8\src\execution\isolate.cc:4240
  42:     0x7ff6608a81c1 - v8::Function::Call
                               at .\..\..\..\..\v8\src\api\api.cc:5095
  43:     0x7ff66089280b - v8__Function__Call
                               at .\..\..\..\..\src\binding.cc:1546
  44:     0x7ff66059d173 - rustc_demangle::try_demangle
  45:     0x7ff65fd60212 - core::alloc::layout::{{impl}}::fmt
  46:     0x7ff65f8f4ecb - main
  47:     0x7ff65f8f3feb - main
  48:     0x7ff65f8f392c - main
test runKillAfterStatus ...test integration::js_unit_tests ... FAILED
  49:     0x7ff65f8f2bb7 - main
  50:     0x7ff65f8f37b0 - main
  51:     0x7ff6605f02ab - alloc::boxed::{{impl}}::call_once
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\library\alloc\src\boxed.rs:1575
  52:     0x7ff6605f02ab - alloc::boxed::{{impl}}::call_once
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\library\alloc\src\boxed.rs:1575
  53:     0x7ff6605f02ab - std::sys::windows::thread::{{impl}}::new::thread_start
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\sys\windows\thread.rs:56
  54:     0x7ffd87a57974 - BaseThreadInitThunk
  55:     0x7ffd8890a2f1 - RtlUserThreadStart

...

failures:

---- integration::js_unit_tests stdout ----
```

### CODE REVIEW

**Comment by caspervonb** [comment]
Not sure if this is desirable, changes the test runner in implicit ways.

**Comment by dsherret** [comment]
> Not sure if this is desirable as a global change, changes the test runner in implicit ways.

@caspervonb could you expand on that?

**Comment by caspervonb** [comment]
> > Not sure if this is desirable as a global change, changes the test runner in implicit ways.
> 
> @caspervonb could you expand on that?

CI output isn't desirable as that output hasn't been captured.
It looks acceptable simply a side effect of stdout streaming, the panic is unwrapped at the moment but it should just be captured but if there's a global panic handler that exits then it doesn't matter if I try to capture it because it will still force an exit.

**Comment by dsherret** [comment]
@caspervonb I don't think it's desirable for the panic to be captured by the test reporter, linter, or any other code.

Panics not bringing down the process have been a source of bugs in the past and a source of a bug here in `deno test` in this case. In my opinion, it's best not to leave panic handling up to any code and instead it should bring down the process including while running tests. This change completely eliminates this class of bug.

We also have some parts of the code that spawn a tokio task without waiting on the join handle to check for a panic. I think it should bring down the process similar to how unawaited promises bring down the process. We can say that we should fix all the code to properly handle panics, but this is hard to test and requires too much maintenance overhead than its worth in my opinion.

Also, a panic occurring and not bringing down the process might leave the program state in a weird place and cause bugs that are hard to track down.

**Review by caspervonb — CHANGES_REQUESTED** [review]
Please provide a way to opt-out or reset this for test_subcommand.

**Comment by caspervonb** [comment]
> @caspervonb I don't think it's desirable for the panic to be captured by the test reporter, linter, or any other code.
> 
> Panics not bringing down the process have been a source of bugs in the past and a source of a bug here in `deno test` in this case. In my opinion, it's best not to leave panic handling up to any code and instead it should bring down the process including while running tests. This change completely eliminates this class of bug.

It brings down the thread, runtime and worker already, there is no need to exit directly without controlling the output.

**Comment by dsherret** [comment]
> There isn't a bug in the behaviour of deno test but in lack of good reporting, it brings down the thread, runtime and worker already just fine so there is no need to exit directly without controlling the output. The problem is just that the way it outputs the failure isn't optimal for readability and is causing confusion.

@caspervonb I disagree. This should have brought down the entire process or at least failed the test command.

**Comment by caspervonb** [comment]
> @caspervonb I disagree. This should have brought down the entire process or at least failed the test command.

@dsherret it did fail and we do fail on panics, we just aren't reporting them correctly yet.

**Comment by dsherret** [comment]
> > @caspervonb I disagree. This should have brought down the entire process or at least failed the test command.
> 
> @dsherret it did fail and we do fail on panics, we just aren't reporting them correctly yet, currently just let them be dumped to stderr.

I'm confused. Why is this panic not causing `deno test` to fail on main then? Opened #11948 to resolve this.

It also stops all the other tests in the module from running.

**Comment by piscisaureus** [comment]
A panic during a test is silently ignored - that's bad and should be fixed urgently.
Note that this applies to panics (bugs in Deno) only.

If we were to handle panics then at least the test should show as failed, other tests would run, and the process should exit with a nonzero exit code.

**Review by piscisaureus — APPROVED** [review]

**Comment by caspervonb** [comment]
> I'm confused. If this is not a bug, why is this panic not causing deno test to fail on main then? 

Me too, thought for sure I saw red on the issue earlier.
Fix for the test runner isn't this tho and I think it's a problem that this makes all calls to thread.join() recovery not what they appear to be.

**Comment by dsherret** [comment]
@caspervonb I talked with @piscisaureus and we are going to merge this for now because this is something we've wanted to do globally anyway. Afterwards we can discuss possibly allowing certain parts of the code to not exit the process on panic, but if we go that route whatever solution we come up with should be opt-out instead of opt-in.

By the way, I think the panic was not being propagated in deno test because of this line which converts the `Result` to an `Option`:

https://github.com/denoland/deno/blob/e3a484ae44ade06d4e4a24fcf07ade6605968010/cli/tools/test.rs#L720

**Pull request merged**
