### PR TITLE
refactor: FeatureChecker integration in ext/ crates

### PR DESCRIPTION
**Pull request by bartlomieju**
Towards https://github.com/denoland/deno/issues/20779.

### CODE REVIEW

**Review by bartlomieju — COMMENTED** [review]
Blocked by https://github.com/denoland/deno_core/pull/259

**Comment by kt3k** [comment]
Looks like the error like the below seems happening. Do you see what causes this?
```
error: Uncaught TypeError: toUtf8 is not a function
const blob = new Blob(
             ^
    at Object.encode (ext:core/01_core.js:862:38)
    at processBlobParts (ext:deno_web/09_file.js:162:26)
    at new Blob (ext:deno_web/09_file.js:235:29)
    at file:///Users/kt3k/denoland/deno/a.js:1:14
```

**Comment by kt3k** [comment]
The code diffs look good to me.

**Review by littledivy — APPROVED** [review]
LGTM

**Pull request merged**
