### PR TITLE
feat: change shade of "gray" color in eye-catchers

### PR DESCRIPTION
**Pull request by bartlomieju**
Closes https://github.com/denoland/deno/issues/14303

This commit changes shade of color "gray" used in various eye-catchers
in the "deno" binary.

### CODE REVIEW

**Review by lucacasonato — APPROVED** [review]
I am happy with this, but as Ansi256(n>16) is going to work in less terminals than Ansi256(n<=16), I'd like to get a second opinion from @ry.

**Comment by bartlomieju** [comment]
> I am happy with this, but as Ansi256(n>16) is going to work in less terminals than Ansi256(n<=16), I'd like to get a second opinion from @ry.

That's true. I'll try with Ansi256(7) too

**Comment by lucacasonato** [comment]
:+1: 

7 is usually `hsl(0,0%,75%)` and 8 is `hsl(0,0%,50%)`. 245 is `hsl(0,0%,54%)`. Probably going to be too light on light backgrounds.

**Comment by bartlomieju** [comment]
This color won't work, there's almost no visible difference
Screenshot 2022-04-18 at 14 12 11
Screenshot 2022-04-18 at 14 12 38
Screenshot 2022-04-18 at 14 13 31

**Comment by bartlomieju** [comment]
Discussed, reverting back to 245

**Comment by bartlomieju** [comment]
Done in https://github.com/denoland/deno/pull/14262

**Pull request merged**
