### PR TITLE
fix(ext/http): when body is empty, `Request.body` should be null

### PR DESCRIPTION
**Pull request by piscisaureus**
Fixes: #12741

### CODE REVIEW

**Review by lucacasonato — CHANGES_REQUESTED** [review]
I am not in favor, because `request.size_hint().exact()` always returns `None` on HTTP/2. This would make HTTP/1.1 and HTTP/2 work differently.

**Comment by piscisaureus** [comment]
> I am not in favor, because `request.size_hint().exact()` always returns `None` on HTTP/2. This would make HTTP/1.1 and HTTP/2 work differently.

Yeah I had some doubts as well (I suspect it might not be possible to always detect an empty body even with HTTP/1.1, e.g. when using "transfer-encoding: chunked"). 

I'll leave this PR open for a bit to allow for the discussion, though.

**Comment by piscisaureus** [comment]
If we decide to not land this, I'll change the test so that it checks "DELETE" requests do have a body.

**Comment by kitsonk** [comment]
The biggest argument is that it is a pretty significant change in behaviour that we landed in a patch release.  Just relying on `transfer-encoding` or `content-length` don't look sufficient in determining if a body exists in oak, as it breaks other things.  I can be self absorbed about oak, but then there is every other RESTful Deno server out there that might have basic logic that tries to see if something has a body or not that could be broken now.

I get the inconsistent behaviour, but there are a few other subtle differences between HTTP 1.1 and HTTP 2 as well, like HTTP 2 doesn't support transfer encoding at all.

**Comment by lucacasonato** [comment]
> I get the inconsistent behaviour, but there are a few other subtle differences between HTTP 1.1 and HTTP 2 as well, like HTTP 2 doesn't support transfer encoding at all.

But only because HTTP/2 is always transfers data in chunks.

**Comment by kitsonk** [comment]
That is arguing it is different because it is different.  Which is the point I am trying to make.  There are different behaviours between HTTP/2 and HTTP/1.1.

**Comment by piscisaureus** [comment]
> The biggest argument is that it is a pretty significant change in behaviour that we landed in a patch release.

I agree that this is not ideal, and a reason to seriously consider landing this patch.

> There are different behaviours between HTTP/2 and HTTP/1.1.

You opened #12741 because the ext/http refactor was breaking oak.
It turns out that the new behavior was already there but for HTTP2 only.
Does that mean that oak was broken with HTTP2 before?

**Comment by kitsonk** [comment]
> Does that mean that oak was broken with HTTP2 before?

Yes, but no-one had reported it and I didn't test for it. I have fixed oak anyway, basically saying that `.hasBody` is an unreliable API and allowing empty bodies to be returned when a specific type of body is asserted, but trying to think of the greater good.

**Comment by kitsonk** [comment]
And when we say broken, it meant that if you had HTTP/2 and sent a DELETE or OPTIONS request, it would report that the request had a body, but that body would be zero length. Which is accurate, but some people coupled to the behaviour of the HTTP/1.1 in their middleware, basically asserting that they didn't have bodies and broke their middleware logic.

Basically `.hasBody` isn't a good idea in HTTP/2 as it really is a Schrödinger's body in that it doesn't exist or not exist until it is observed. Now that behaviour occurs for native HTTP/1.1 results.

**Comment by piscisaureus** [comment]
Discussed off-github: unfortunate as it is that this change was introduced in a a patch release, we think that in the long term this is the desirable behavior, so we are not going to land a patch to revert to pre-1.16.1 behavior.

**Pull request closed without merging**
