### PR TITLE
fix(test): typecheck blocks annotated with long js/ts notations

### LINKED ISSUE #13783: `deno test --doc` doesn't pick up `typescript`-annotated blocks
This works as expected and throws an error:

\`\`\`ts
let str: string = 0;
\`\`\`

```
error: TS2322 [ERROR]: Type 'number' is not assignable to type 'string'.
let str: string = 0;
    ~~~
    at file:///C:/Users/GJZwiers/repos/test_test/thingy.md$3-6.ts:1:5
```

But it doesn't if the `typescript` annotation is used:

\`\`\`typescript
let str: string = 0;
\`\`\`

### PR DESCRIPTION
**Pull request by GJZwiers**
Closes #13783

### CODE REVIEW

**Comment by bartlomieju** [comment]
@GJZwiers looks good! The test failure seems to be unrelated. Could you add some test case to exercise this change?

**Comment by GJZwiers** [comment]
> @GJZwiers looks good! The test failure seems to be unrelated. Could you add some test case to exercise this change?

I've added a test, the pipeline keeps failing on a few compat tests but other than it seems fine. Will this be OK?

**Comment by bartlomieju** [comment]
@GJZwiers it seems the errors were coming from `test_util/std` git submodule which was mistakenly changed in this PR. I reverted that change and tests seem to pass locally now.

**Review by bartlomieju — APPROVED** [review]
LGTM, thank you

**Pull request merged**
