### PR TITLE
upgrade: rusty_v8 0.19.0

### PR DESCRIPTION
**Pull request by bartlomieju**
Actual ICU implementation will follow in a separate PR

### CODE REVIEW

**Comment by kitsonk** [comment]
This will allow the tests to pass, but I think something is wrong with ICU in Deno:

```diff
diff --git a/cli/tsc/99_main_compiler.js b/cli/tsc/99_main_compiler.js
index 50631e83..a1ea5612 100644
--- a/cli/tsc/99_main_compiler.js
+++ b/cli/tsc/99_main_compiler.js
@@ -8,10 +8,25 @@
 // that is created when Deno needs to type check TypeScript, and in some
 // instances convert TypeScript to JavaScript.
 
+"use strict";
+
 // Removes the `__proto__` for security reasons.  This intentionally makes
 // Deno non compliant with ECMA-262 Annex B.2.2.1
 delete Object.prototype.__proto__;
 
+// TODO(@kitsonk) this is hacky and shouldn't be here at all...
+Intl.Collator = (() => {
+  function Collator() {}
+
+  Collator.prototype = {
+    compare(a, b) {
+      return a < b ? -1 : a > b ? 1 : 0;
+    }
+  }
+
+  return Collator;
+})();
+
 ((window) => {
   /** @type {DenoCore} */
   const core = window.Deno.core;
```

**Comment by kitsonk** [comment]
Ah, yeah, didn't pay attention that the ICU implementation happens later... yeah, maybe it is just best to ignore the tests as is currently done until ICU is implemented and then re-enable them.

**Comment by ry** [comment]
Intl.Collator is not working. I'm investigating it in rusty_v8 https://github.com/denoland/rusty_v8/pull/617

**Comment by ry** [comment]
The `Intl.Collator` issue should be resolved now. The problem was that the ICU data needs to be 16-bit aligned.

Happy to land this, but ICU should probably wait for 1.8.0? Maybe we should wait until after 1.7.3 is released.

**Review by ry — APPROVED** [review]
LGTM

**Comment by bartlomieju** [comment]
Waiting on `v0.19.0` of `rusty_v8` before landing this one

**Pull request merged**
