### PR TITLE
BREAKING(std/path): Rename some symbols

### LINKED ISSUE #6829: [Discussion] std/path: rename methods
I came across a naming inconsistency. I know that the naming convention for some of these methods has historic reasons,  but in ```JS``` there are normally no abbreviations for functions and methods.

Affected exports are
- ```sep```
- ```extname(path: string)```
- ```dirname(path: string)```

So I wonder if it would make sense to rename them to have full descriptive names. Maybe something like this:

- ```separator```
- ```extension(path: string)```
- ```directory(path: string)```

What do you think?

### PR DESCRIPTION
**Pull request by nayeemrmn**
Uses Rust names for functions.
- `basename()` -> `fileName()`
- `dirname()` -> `parent()`
- `extname()` -> `extension()`
- `sep` -> `separator`

Closes #6829.

Refs:
- https://doc.rust-lang.org/std/path/struct.Path.html
- https://en.cppreference.com/w/cpp/filesystem/path

### CODE REVIEW

**Comment by ry** [comment]
These names come from Node's path module - so there is precedence. Is it really worth it to change?

**Comment by nayeemrmn** [comment]
> These names come from Node's path module - so there is precedence. Is it really worth it to change?

@ry Yes, the current names are bad. `dirname()` to get the parent of the path is especially nonsensical. The casing inconsistency will become a problem when we want to add new things that don't share that precedence -- for example I think we should separate [`fileStem()`](https://doc.rust-lang.org/std/path/struct.Path.html#method.file_stem) from `basename()` rather than keeping the silly extension replacement thing. It's better to maintain consistency with the Rust APIs which are more well designed.

**Comment by caspervonb** [comment]
> so there is precedence.

Asa mentioned in #6829, there's a strong precedence, not only Node but also Python, Go, PHP, Ruby, etc.

What if we just broke completely here and introduced a path object with these new properties? effectively reimplementing Rust's std::path::Path

**Comment by zhmushan** [comment]
This change is worthwhile for me. When I first started learning `nodejs`, I needed to consult the docs every time I used the path module, due to these strange names.

**Comment by nayeemrmn** [comment]
> What if we just broke completely here and introduced a path object with these new properties? effectively reimplementing Rust's std::path::Path

@caspervonb It doesn't work as well here due to the inferior conversion constructs in JS and the fact that it's not built-in. Primitives are easier to work with.

> Parent... I'd never have guessed what that was.

Really? Parent path is a well-known and properly formed name. As in a parent node in any tree structure? There's a lot of things you have to be unfamiliar with for that to be strange, unless anything that isn't `dirname()` is un-guessable.

**Comment by ry** [comment]
Let's have a vote: 
@ry against
@lucacasonato for
@bartlomieju ?
@piscisaureus ?
@kitsonk ?

**Comment by kitsonk** [comment]
While `dirname()` is non sensical to some, `parent()` is non sensical to others.

Go Lang, which is the "default" for `std` APIs:

* `basename()` -> `base()`
* `dirname()` -> `dir()`
* `extname()` -> `ext()`
* `sep` -> `separator`

Also, this wouldn't be a minor breaking change, it would have significant impacts, and we originally thought correcting `URL | string` was a good idea and look at the impact that had.  If this was a year ago, I would have thought it would be a good conversation to debate, but sadly, I think the [cowpath is already paved](https://en.wiktionary.org/wiki/pave_the_cowpath).

**Comment by nayeemrmn** [comment]
> Also, this wouldn't be a minor breaking change, it would have significant impacts, and we originally thought correcting `URL | string` was a good idea and look at the impact that had.

@kitsonk This is not at all the same as that...

That was a breaking change for a built-in, where upgrading a minor version of Deno broke the `std` module people were already using. This would have no effect without explicitly upgrading `std` and there's no transitive effect from an intermediary dependency updating it's version of `std`. Why are we v0 if it's too late to change anything?

**Comment by kitsonk** [comment]
> This would have no effect without explicitly upgrading `std` and there's no transitive effect from an intermediary dependency updating its version of `std`.

That is the residual issue.  When we merged with master, we had a load of people up in arms, because they were on 1.1.3 and their dependency was using `std` from master, which then was breaking.  The fix of not serving the main branch, but the latest release with a "bare" specifier wouldn't fix it either, because as soon as we release that version of standard, we would break a lot of libraries that exist out there that are using the latest release of `std` that would need to be updated.  I know it would break the main branch of oak, and the fact that this required changes in 20+ files indicates how pervasive this API.  Mostly because there really isn't anything in the browser standards that comes close to providing the functionality, so we have no choice.

I am all for breaking things, but as pointed out, this is 6 of one, half dozen of another.  For every argument on this API there is an equal counter argument against.  In my mind, the APIs in `std` are JavaScript convention first, Go Lang second, then other prior art.  There is a strong convention with Node.js in this space, and Go Lang is semi-aligned to that.  Sadly, Rust is the outlier here.

In my mind, a breaking change that doesn't have a strong compelling argument coupled with wide 3rd party adoption, is a challenge.

**Comment by nayeemrmn** [comment]
> That is the residual issue. When we merged with master, we had a load of people up in arms, because they were on 1.1.3 and their dependency was using `std` from master, which then was breaking.

We got these issues all of the time when we made even additive changes to the Deno namespace that were used in `std`, some recent, they weren't that problematic. Not many popular modules are using implicit versions anymore. (From what I've heard, imports like this are going away anyway.)

The reason it's so different when its caused by the built-in API (an implicit peer dependency of everything you've imported!) is because now a very specific alignment needs to be struck between what versions of modules you're importing _and_ what version of Deno all of you are using. Most people's complaints had something to do with their Deno version. I maintain that this change to a versioned userspace library would not be the same at all.
> I know it would break the main branch of oak

`deno info https://raw.githubusercontent.com/oakserver/oak/main/deps.ts` doesn't show me any implicit master imports. By "break" do you mean having to update your own `std/path` import symbols once you opt into upgrading `std`? That's expected of v0... it has no similarity to the 1.2.0 incident.

**Comment by piscisaureus** [comment]
My 2 cents:

* The names @kitsonk proposed (`base`, `dir`, `ext`) do seem better to me. (However, it seems inconsequential to use short abbreviations for those names, and then change `sep` to `separator`). `parent()` is too generic and worse.
* I would be -1 on making this if it is a breaking change. If we added the new names and then left the old ones in place (undocumented) I am okay with it.

**Comment by nayeemrmn** [comment]
I honestly didn't expect the breaking change to be such an issue. Now I regret not raising the issue myself much earlier, not that I could have known. But it seems like those pointing this out have no problem with the current names, so I hope to put a dent there at least.

> While `dirname()` is non sensical to some, `parent()` is non sensical to others.

I forgot, I never really explained why I think the "directory" of a path referring to its parent is nonsensical:
```js
import { dirname } from "https://deno.land/std@0.63.0/path/mod.ts";
const perfectlyValidPath = "/etc/passwd/foo";
console.log(Deno.statSync(dirname(perfectlyValidPath)).isDirectory); // false
```
Golang's [doc]("/etc/passwd/foo") even qualifies that the result is "typically" a directory. We can go back and forth about how that path is perhaps not actually valid even though it will never fail any of our path functions, but again... the correct term is right there for us to use. The "directory name" of a path which points to a directory is also a very iffy concept. I can't see this as a minor preference issue. We know all of the precedents for the current names just took them from the same place. Rust seems to be the one of the few that thought up a consistent scheme for itself and respected its casing conventions. We should try to [point the language in better directions where we can](https://github.com/denoland/deno/issues/4666#issue-596085035).

**Comment by bartlomieju** [comment]
I'm mostly in favor of the changes - I believe shorter ones are less helpful and indeed Rust's naming has been the friendlies I've come across to date.

@nayeemrmn could you rebase the branch?

**Comment by caspervonb** [comment]
If we're going to rename std/fs, I'd be more in favour of taking from C# with descriptive DOM style named functions, e.g the very explicit `getParentDirectoryPath`.

The path module is often the only module that is more or less always imported as a namespace because of its ambiguous naming.

**Comment by nayeemrmn** [comment]
It would just be `parentPath()`. But then there's a stutter when you _do_ use namespace imports. And as you said those are the most used right now so let's accommodate that.

**Comment by caspervonb** [comment]
I'm still for a rename but would like to see more descriptive function names that aren't cryptic in an `import { } from` context otherwise we're just going from bad but well known naming to bad naming.

**Comment by nayeemrmn** [comment]
@caspervonb There have _been_ names like `format()`, `join()`, `normalize()`, `parse()`, `resolve()` as well. Also the `parse()` functions in the encoding module,  we've explicitly decided to used names like that depending on common usage: https://github.com/denoland/deno/pull/3509#pullrequestreview-332316676, https://github.com/denoland/deno/pull/3509#issuecomment-568003919.

**Comment by lucacasonato** [comment]
Putting this on hold until this is discussed in std working group.

**Comment by bartlomieju** [comment]
@nayeemrmn we won't land this PR before standard library migration to a separate repository. I'm still very much interested in discussing these changes on upcoming meetings and potentially landing the PR. 

Let's keep it open until the migration is done.

**Comment by bartlomieju** [comment]
Deno standard library was moved to [denoland/deno_std](https://github.com/denoland/deno_std), please reopen your PR there.

**Pull request closed without merging**
