### PR TITLE
fixed assertThrows throws TypeError when thrown undefined or null

### PR DESCRIPTION
**Pull request by Code-Hex**
I fixed assertThrows throws AssertionError when thrown `undefined` or `null`.

## Why

We can now get this error. (assertThrowsAsync will also occur)

```
TypeError: Cannot convert undefined or null to object
    at Function.getPrototypeOf (<anonymous>)
```

I don't know whether `undefined` or `null` was thrown, so I want to be clear.

### reproduce

```typescript
test("throw undefined", () => {
  assertThrows(
    () => {
      throw null; // throw undefined;
    },
    Error
  );
});
```

### CODE REVIEW

**Comment by kitsonk** [comment]
I am not sure this is what is desired.  If someone omits an `ErrorClass` and throw an `undefined` that is perfectly acceptable.  But if  `ErrorClass` is defined, and what is thrown not of that instance (which means if it is not an object or not an instance of the error class it should then throw).

**Comment by Code-Hex** [comment]
@kitsonk I think we should avoid throwing undefined or null when ErrorClass is explicitly specified.

```
error: Uncaught TypeError: Cannot convert undefined or null to object
    if (ErrorClass && !(Object.getPrototypeOf(e) === ErrorClass.prototype)) {
                               ^
    at Function.getPrototypeOf (<anonymous>)
    at assertThrows (file:///Users/codehex/go/src/github.com/Code-Hex/deno/std/testing/asserts.ts:341:32)
    at file:///Users/codehex/go/src/github.com/Code-Hex/deno/std/testing/asserts_test.ts:394:1
```

Surely the current change was valid even when ErrorClass was not specified, so I'll fix it. thanks!!

**Comment by Code-Hex** [comment]
I agree we have to accept this case.

```
test("throw undefined", () => {
  assertThrows(
    () => {
      throw null; // throw undefined;
    },
  );
});
```
However, if the error is explicitly specified, it should not be accepted.

```
test("throw undefined", () => {
  assertThrows(
    () => {
      throw null; // throw undefined;
    },
    Error
  );
});
```

Surely the current change was valid even when ErrorClass was not specified, so I'll fix it.

**Comment by Code-Hex** [comment]
I don't know why is failed on cli/tests/integration_tests.rs...

**Comment by Code-Hex** [comment]
I force-pushed the same commit content and ran the CI again.

**Comment by Code-Hex** [comment]
@kitsonk I fixed this logic!!

**Comment by bartlomieju** [comment]
@kitsonk please review

**Comment by bartlomieju** [comment]
Already fixed in https://github.com/denoland/deno/pull/6330

**Pull request closed without merging**
