### PR TITLE
fix(check): expose more globals from @types/node

### PR DESCRIPTION
**Pull request by dsherret**
Extracted out of https://github.com/denoland/deno/pull/26558

Closes https://github.com/denoland/deno/issues/26578

### CODE REVIEW

**Comment by dmint789** [comment]
Has this been released? I'm still getting the error in VS code when using the process global.

**Comment by dsherret** [comment]
Works for me. Maybe open an issue?

image

**Comment by dsherret** [comment]
Yes. In your case, are you sure the `@types/node` package is being included?

image

**Comment by dmint789** [comment]
> Yes. In your case, are you sure the `@types/node` package is being included?
> 
> image

I tried adding that line at the top, but it's not helping, even though I have @types/node installed through my package.json (I'm using it, because I have a Next JS project). Attaching the screenshot below.

image

**Comment by dmint789** [comment]
@dsherret do you know how I could make this error go away? I'm on Deno 2.1.4 and it still happens.

**Comment by dsherret** [comment]
Maybe provide a full reproducible reproduction with a github repo? Otherwise there's no way to help because it's not reproducible.

**Comment by dsherret** [comment]
Also, it's best to do this in a github issue instead of an old merged pr.

**Comment by dmint789** [comment]
> Maybe provide a full reproducible reproduction with a github repo? Otherwise there's no way to help because it's not reproducible.

I made a reproducible example [in the original issue](https://github.com/denoland/deno/issues/26578#issuecomment-2564494059)

**Pull request merged**
