### PR TITLE
upgrade: deno_lint v0.1.17

### PR DESCRIPTION
**Pull request by bartlomieju**

### CODE REVIEW

**Comment by bartlomieju** [comment]
It seems the upgrade broke `fmt_check_tests_dir` test. I'm not entirely sure what's going on... but it looks like a regression in dprint (because there's an error now). @dsherret could you take a look?

```
OUTPUT

from ./badly_formatted.mjs:
2| -console.log("Hello World"
3| -
4| -)
2| +console.log("Hello World");

Error checking: ./error_syntax_empty_trailing_line.mjs
   Line 2, column 22: Unexpected eof

  etTimeout(() => {}),

error: Found 1 not formatted file

OUTPUT
EXPECTED
[WILDCARD]
error: Found [WILDCARD] not formatted files

EXPECTED
```

**Comment by dsherret** [comment]
I’ll take a look tomorrow, but I think all that’s changed in dprint-plugin-typescript since the last update is swc (not sure though).

**Comment by dsherret** [comment]
@bartlomieju found the issue. There's only 1 changing file now which is correct, but previously there were 2. You need to update that test to just say "Found 1 not formatted file"

Previously, dprint-plugin-typescript would incorrectly remove the comma for comma separated values when it had a `// deno-fmt-ignore` comment, but that's fixed now:

image

**Comment by bartlomieju** [comment]
> @bartlomieju found the issue. There's only 1 changing file now which is correct, but previously there were incorrectly 2. You need to update that test to just say "Found 1 not formatted file"
> 
> Previously, dprint-plugin-typescript would incorrectly remove the comma for comma separated values when it had a `// deno-fmt-ignore` comment, but that's fixed now (screenshot is of previous incorrect behaviour):
> 
> image

Thanks for checking, but I think this error is unexpected?
```
Error checking: ./error_syntax_empty_trailing_line.mjs
   Line 2, column 22: Unexpected eof

  etTimeout(() => {}),

error: Found 1 not formatted file
```

**Pull request merged**
