### PR TITLE
feat: remove conditional unstable type-checking

### PR DESCRIPTION
**Pull request by bartlomieju**
This commit removes conditional type-checking of unstable APIs.

Before this commit `deno check` (or any other type-checking command and the LSP)
would error out if there was an unstable API in the code, but not `--unstable` flag
provided.

This situation hinders DX and makes it harder to configure Deno. Failing during
runtime unless `--unstable` flag is provided is enough in this case.

### CODE REVIEW

**Comment by bartlomieju** [comment]
I wonder if we should remove all the code related to "unstable" from the LSP. Thoughts on that?

**Review by nayeemrmn — APPROVED** [review]
LGTM

**Review by dsherret — APPROVED** [review]
LGTM

**Comment by jsejcksn** [comment]
Does this change completely prevent the ability to type-check code that is intended to use only stable features (in order to detect invalid unstable references prior to runtime), or is there some alternative mechanism to do so?

**Comment by bartlomieju** [comment]
> Does this change completely prevent the ability to type-check code that is intended to use only stable features (in order to detect invalid unstable references prior to runtime), or is there some alternative mechanism to do so?

That's correct. Now all APIs are unconditionally type-checked.

**Pull request merged**
