### PR TITLE
typings: Make FileInfo as returned by readdir not null (Alternate) (WIP) 

### PR DESCRIPTION
**Pull request by KSXGitHub**
This is an alternative to https://github.com/denoland/deno/pull/4733 that tries to keep things in sync.

### CODE REVIEW

**Comment by KSXGitHub** [comment]
Weird, I have fix TS errors for `std/fs/walk` in https://github.com/denoland/deno/pull/4740/commits/47de5b94301b1dffdc0748cdd3b397b71273a1fe, yet the same errors still appear.

**Comment by ry** [comment]
I fixed a couple lint errors (run `./tools/lint.py --js` and `./tools/format.py --js` to fix these). Seems there's some work to be done in std/fs still. I suppose `WalkInfo` which currently has this

```ts
export interface WalkInfo {
  filename: string;
  info: DirEntry;
}
```
should probably be turned into

```ts
export interface WalkInfo {
  filename: string;
  info: FileInfo;
}
```
Since the filename already contains the name...

Feel free to leave this PR as is if you want, I can clean it up later, or you get it to green if you're feeling generous. Either way - I think this is on the right track - tho I'm interested in @nayeemrmn's review.

**Comment by KSXGitHub** [comment]
> I suppose `WalkInfo` which currently has this
> 
> ```ts
> export interface WalkInfo {
>   filename: string;
>   info: DirEntry;
> }
> ```
> 
> should probably be turned into
> 
> ```ts
> export interface WalkInfo {
>   filename: string;
>   info: FileInfo;
> }
> ```

Is there a gain from using `FileInfo` in place of `DirEntry`? I never used `walk` before, but I guess `filename` is not base name but a path? If so, user avoid re-calculating basename by re-using `DirEntry::name` .

---

BTW, `walk` API is pretty complex for a `std` library. I have a much simple [deno-tree](https://github.com/KSXGitHub/deno-tree).

**Comment by KSXGitHub** [comment]
This endeavor proves to be more complicated than I expected. I give up.

**Pull request closed without merging**
