### PR TITLE
chore(core): Deduplicate code related to `op_event_loop_has_more_work`

### PR DESCRIPTION
**Pull request by andreubotella**
The `op_event_loop_has_more_work` op, introduced in #14830, duplicates code from `JsRuntime::poll_event_loop`. That PR also added the unused method `JsRuntime::event_loop_has_work`, which is another duplication of that same code, and which isn't used anywhere.

This change deduplicates this by renaming `JsRuntime::event_loop_has_work` to `event_loop_pending_state`, and making it the single place to determine what in the event loop is pending. This result is then returned in a struct which is used both in the event loop and in the `op_event_loop_has_more_work` op.

### CODE REVIEW

**Comment by cjihrig** [comment]
@andreubotella it looks like there are some failures in the CI.

**Comment by andreubotella** [comment]
> @andreubotella it looks like there are some failures in the CI.

I'd left off `maybe_sheduling` as a condition. Thanks to @littledivy for pointing this out!

**Review by bartlomieju — CHANGES_REQUESTED** [review]
I'm marking this PR as "Request changes" because `op_event_loop_has_more_work` is currently not working as we intended. @cjihrig and I were working on https://github.com/denoland/deno_std/pull/2331 and needed to add that binding, but it doesn't work as expected by Node tests. We need more investigation before finishing it, so let's postpone landing this PR.

**Review by bartlomieju — APPROVED** [review]
Discussed on Discord, we're gonna land it now and circle back to it when resuming work on `process.on("beforeExit")`

**Pull request merged**
