### PR TITLE
chore: Deprecate node compat itests

### PR DESCRIPTION
**Pull request by MohammadSu1**
chore: Deprecate node compat itests
This PR is part of solving #22907.
In this PR, The node_compat_tests.rs file was deprecated, and all the tests were moved under specs/node_compat_tests.
Additionally, the related files under testdata/node were removed after ensuring that they weren't related to any other test.

### CODE REVIEW

**Comment by MohammadSu1** [comment]
@dsherret Can you please review this pull request?

**Review by bartlomieju — COMMENTED** [review]
Can you please update `tools/lint.js` and remove `node_compat_tests.rs` entry from `ensureNoNewITests()`?

**Comment by MohammadSu1** [comment]
@bartlomieju Done.
I have decreased the number of tests to zero for both node_compat_tests.rs and worker_tests.rs, which I deprecated in the previous pull request.

**Comment by MohammadSu1** [comment]
@dsherret Can you please review this

**Review by dsherret — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
