### PR TITLE
feat(ext/crypto): add x25519 and Ed25519 CFRG curves

### PR DESCRIPTION
**Pull request by littledivy**
Implements Curve25519 from https://github.com/WICG/webcrypto-secure-curves

We will probably have to rollout our own Curve448, there is no ring, RustCrypto OR rust-dalek crate for that. Left that for now.

### CODE REVIEW

**Comment by littledivy** [comment]
Not stale!

**Review by ry — APPROVED** [review]
LGTM 🙌

**Comment by littledivy** [comment]
>  Do you plan for X448 and Ed448 as well?

Yes, planned but we'll have to evaluate existing Rust crates that do curve448 - I couldn't find a 'widely-used' crate. That said it shouldn't be too hard to write our own.

**Comment by panva** [comment]
@littledivy I'm finding it hard to navigate what has been implemented here. I'm able to generate both key types. Despite import code being added for both I can import neither one (Ed says the algorithm is unrecognized, X says the key data is invalid). X export seems to be omitted despite being the same as Ed wrt to the key material. Ed signatures fail to validate.

**Comment by littledivy** [comment]
Yikes! Seems like I didn't push all changes from my local branch :(

**Comment by panva** [comment]
@littledivy I hope it's not lost ;)

**Pull request merged**
