### PR TITLE
feat(compat): add .code to dyn import error

### LINKED ISSUE #12588: [compat] when using dynamic import in Node compat mode and module is not found, err.code needs to be set to 'ERR_MODULE_NOT_FOUND'
In Node.js, it's common to check err.code to detect the kind of errors:

```ts
if (err.code === 'ERR_MODULE_NOT_FOUND') {
  // do something
}
```

`std/node` simulates these error codes in API layer (ref: https://github.com/denoland/deno_std/blob/0b31c1647649f9b6aa53432370daab4483803e77/node/_errors.ts#L289-L304 )

But in the case of dynamic import, the above shim can't be used. So `err.code` needs to be set to `ERR_MODULE_NOT_FOUND` directly in CLI runtime when `--compat` flag is specified.

This feature is used in `mocha` when looking up the test files (ref: https://github.com/mochajs/mocha/blob/97b84708afb42e552cb906a54f9f2aa2e6a98ba4/lib/nodejs/esm-utils.js#L47-L56 )

related: #12577

### PR DESCRIPTION
**Pull request by kt3k**
part of #12577, closes #12588

This PR changes the error class for dynamic import rejection in compat mode. Some tools (e.g. mocha) uses .code property of error object to detect the resolution failure of dynamic import (ref: https://github.com/mochajs/mocha/blob/97b84708afb42e552cb906a54f9f2aa2e6a98ba4/lib/nodejs/esm-utils.js#L47-L56 ). This change simulates the above behavior in compat mode.

This change enables compat mode to run the basic feature of mocha cli

### CODE REVIEW

**Comment by kt3k** [comment]
`cli/tests/testdata/fix_dynamic_import_errors.js` test case strangely panicks at the 2nd dynamic import..

**Comment by kt3k** [comment]
Now ready for review

I first tried to reuse class_name of CustomError for accessing the custom js error constructor, but that didn't work because some errors cause panic during getting error class (caused by `cli/tests/testdata/fix_dynamic_import_errors.js`). Now I created a dedicated error class for that purpose `CustomErrorWithJsConstructor` and retrieves js constructor name from that class during rejections of dynamic imports

**Comment by bartlomieju** [comment]
Please discuss this change in the design letting before landing.

**Review by lucacasonato — COMMENTED** [review]
I am not in favor of this `Deno.compat.errors` namespace. In node `await import("xxxxxx")` throws a regular `Error` (no subclass), with a `.code` on it. In the browser it throws a `TypeError`. I think we should always throw a `TypeError` (also in non-compat mode), and in compat mode add a `code` property to that.

**Review by lucacasonato — APPROVED** [review]
LGTM

**Pull request merged**
