### PR TITLE
Json ops metrics

### PR DESCRIPTION
**Pull request by romainPrignon**
ref #2801

depends on #2799

### CODE REVIEW

**Comment by bartlomieju** [comment]
@romainPrignon I suggest to start afresh from `master` - it should be easier than rebasing

**Comment by romainPrignon** [comment]
yes ! I'll do it soon

**Comment by nayeemrmn** [comment]
@romainPrignon I think @bartlomieju went ahead and done this in #2809.

**Comment by romainPrignon** [comment]
you're right, thanks
I'll close this one

**Pull request closed without merging**
