### PR TITLE
docs: Improve inline docs for permissions (deno run --help)

### PR DESCRIPTION
**Pull request by kwhinnery**
Hey there! I took a crack at improving these embedded docs [as requested here](https://github.com/denoland/deno/issues/18685). These should accurately reflect the functionality of the permission-related flags for `deno run`.

### Highlights
* Adds human-readable argument string in the format [prescribed in the docs](https://docs.rs/clap/latest/clap/struct.Arg.html#method.value_name)
* Keeps text description terse, but includes a relevant copy/pasteable docs link
* Includes example argument usage/formatting

### Formatting preview
image

### Testing locally
* [Configure local environment](https://deno.land/manual@v1.32.4/references/contributing/building_from_source)
* Build CLI with `cargo build -vv`
* Run `./target/debug/deno run --help`

### CODE REVIEW

**Comment by bartlomieju** [comment]
@kwhinnery thanks, this looks good! Could you do the same for remaining permission flags?

**Comment by kwhinnery** [comment]
You bet! If we feel good about this format, I will knock out the others.

**Comment by bartlomieju** [comment]
@kwhinnery yes, this format look great. Thanks!

**Comment by kwhinnery** [comment]
While not strictly necessary for this, it might be nice to also [merge this PR](https://github.com/denoland/manual/pull/621) - while making this change, I noticed that the possible values for `--allow-sys` were not documented anywhere, so I added the possible options to the manual.

**Review by bartlomieju — APPROVED** [review]
LGTM, thanks so much @kwhinnery!

**Pull request merged**
