### PR TITLE
feat(extensions/webstorage): optimize db calls with pragmas

### PR DESCRIPTION
**Pull request by littledivy**
Certain combination of pragmas to optimize database. 

Enables write-ahead-log, memory mapped I/O and re-analyzes database on first connection.

Benchmarks

```
divy@lappy:~/Desktop/gh/deno$ hyperfine --prepare 'rm -rf ~/.cache/deno/location_data/' -m 5 'target/release/deno run --unstable --location=https://a.com bench_localstorage.js' 'deno run --unstable --location=https://a.com bench_localstorage.js'
Benchmark #1: target/release/deno run --unstable --location=https://a.com bench_localstorage.js
  Time (mean ± σ):      3.743 s ±  0.166 s    [User: 45.9 ms, System: 22.0 ms]
  Range (min … max):    3.555 s …  3.984 s    5 runs
 
Benchmark #2: deno run --unstable --location=https://a.com bench_localstorage.js
  Time (mean ± σ):     15.032 s ±  0.557 s    [User: 42.6 ms, System: 70.6 ms]
  Range (min … max):   14.436 s … 15.940 s    5 runs
 
Summary
  'target/release/deno run --unstable --location=https://a.com bench_localstorage.js' ran
    4.02 ± 0.23 times faster than 'deno run --unstable --location=https://a.com bench_localstorage.js'
```
(Note: benchmarks recorded on a "potato" [i7 + HDD] , disk I/O is slow)

### CODE REVIEW

**Comment by crowlKats** [comment]
M1:
```
Benchmark #1: target/release/deno run --unstable --location=https://a.com bench_localstorage.js
  Time (mean ± σ):      22.8 ms ±   0.9 ms    [User: 12.3 ms, System: 7.4 ms]
  Range (min … max):    21.8 ms …  27.3 ms    101 runs
 
Benchmark #2: deno run --unstable --location=https://a.com bench_localstorage.js
  Time (mean ± σ):      22.1 ms ±   1.2 ms    [User: 12.5 ms, System: 7.6 ms]
  Range (min … max):    20.5 ms …  27.9 ms    118 runs
 
Summary
  'deno run --unstable --location=https://a.com bench_localstorage.js' ran
    1.03 ± 0.07 times faster than 'target/release/deno run --unstable --location=https://a.com bench_localstorage.js'
```
The test used in both our benchmarks is 
```
var key = "name";
var val = "x"

for(let i = 0; i < 100; i ++) localStorage.setItem(key, val);
```

**Comment by littledivy** [comment]
> On M1 this branch is slower than main:
> 
> ```
> Benchmark #1: target/release/deno run --unstable --location=https://a.com bench_localstorage.js
>   Time (mean ± σ):      22.8 ms ±   0.9 ms    [User: 12.3 ms, System: 7.4 ms]
>   Range (min … max):    21.8 ms …  27.3 ms    101 runs
>  
> Benchmark #2: deno run --unstable --location=https://a.com bench_localstorage.js
>   Time (mean ± σ):      22.1 ms ±   1.2 ms    [User: 12.5 ms, System: 7.6 ms]
>   Range (min … max):    20.5 ms …  27.9 ms    118 runs
>  
> Summary
>   'deno run --unstable --location=https://a.com bench_localstorage.js' ran
>     1.03 ± 0.07 times faster than 'target/release/deno run --unstable --location=https://a.com bench_localstorage.js'
> ```
> 
> The test used in both our benchmarks is
> 
> ```
> var key = "name";
> var val = "x"
> 
> for(let i = 0; i < 100; i ++) localStorage.setItem(key, val);
> ```

That's almost no change since the number of runs differ and possible disk cache resulting into the tiny difference. Still quite significant improvement in my case.

**Comment by littledivy** [comment]
Much noticeable when running fresh without a `$DENO_DIR/location_data/`

**Comment by bartlomieju** [comment]
@littledivy I would be interested in landing this PR, but I'm a bit worried about problems on M1 as pointed by @crowlKats. Could you please share you benchmark code so I could also run them locally?

**Comment by evanwashere** [comment]
there is actually no regression on M1, @crowlKats test just didn't delete optimized sqlite database from pr test

here are benchmarks redone with more accurate measurement of improvement itself on M1

proper test:
```js
rm -rf ~/Library/Caches/deno/location_data
➜  /tmp ./deno-new run -A --location https://google.com test.js
{
  min: "38,126 ns/iter",
  max: "446,292 ns/iter",
  avg: "46,517 ns/iter",
  "50th": "45,666 ns/iter",
  "75th": "48,125 ns/iter",
  "99th": "58,167 ns/iter",
  "99.5th": "84,418 ns/iter",
  "99.9th": "202,709 ns/iter"
}
rm -rf ~/Library/Caches/deno/location_data
➜  /tmp ./deno-old run -A --location https://google.com test.js
{
  min: "203,042 ns/iter",
  max: "1,691,168 ns/iter",
  avg: "222,941 ns/iter",
  "50th": "213,251 ns/iter",
  "75th": "217,418 ns/iter",
  "99th": "337,293 ns/iter",
  "99.5th": "364,834 ns/iter",
  "99.9th": "681,251 ns/iter"
}
```

crowls test case (reusing optimized sqlite database by first run)
```js
➜  /tmp ./deno-new run -A --location https://google.com test.js
{
  min: "38,834 ns/iter",
  max: "369,750 ns/iter",
  avg: "46,337 ns/iter",
  "50th": "45,876 ns/iter",
  "75th": "48,084 ns/iter",
  "99th": "56,542 ns/iter",
  "99.5th": "63,834 ns/iter",
  "99.9th": "98,460 ns/iter"
}
➜  /tmp ./deno-old run -A --location https://google.com test.js
{
  min: "39,208 ns/iter",
  max: "382,167 ns/iter",
  avg: "47,249 ns/iter",
  "50th": "46,750 ns/iter",
  "75th": "49,043 ns/iter",
  "99th": "57,918 ns/iter",
  "99.5th": "66,085 ns/iter",
  "99.9th": "96,292 ns/iter"
}
```

source:
```js
import { sync } from 'https://gist.githubusercontent.com/evanwashere/7ee592870e46f80405b9776dcd56e1e8/raw/85f150581accc7d987b806093c32aada21463d41/bench.js';

console.log(sync(1e4, () => localStorage.setItem('a', 'aaaaa')));
```

**Comment by crowlKats** [comment]
I actually did clear the location_data folder back then, divy can confirm, but alright

**Comment by littledivy** [comment]
Closing. This was done in #11709

**Pull request closed without merging**
