### PR TITLE
[WIP] Use std::future

### PR DESCRIPTION
**Pull request by afinch7**
Still waiting on a stable release of tokio, but it shouldn't be necessary(I can just use `futures::compat` for now).

### CODE REVIEW

**Comment by ry** [comment]
Great - I'm happy to make the switch now if we can get it green. Tokio 0.2 is due out at the end of the month

**Comment by trivikr** [comment]
Fixes: #3074

**Comment by afinch7** [comment]
Only a few things left:

* Proxy test(`045_proxy_test.ts`) gets stuck for some reason. Maybe a incompatibility with the old version of `tokio-process`.
* The process never terminates at the end of `allow-net` unit tests.

**Comment by bartlomieju** [comment]
> Only a few things left:
> 
> * Proxy test(`045_proxy_test.ts`) gets stuck for some reason. Maybe a incompatibility with the old version of `tokio-process`.
> * The process never terminates at the end of `allow-net` unit tests.

We have this hacky way of letting other future know that listener has been closed:
https://github.com/denoland/deno/blob/31115067cd3156db1ead0dc0f11c78875840dc4f/cli/ops/net.rs#L245-L281

I suppose this might be the issue for hanging tests

**Comment by afinch7** [comment]
@bartlomieju `target/debug/deno run --allow-net --reload cli/js/unit_tests.ts` appears to run fine, but it never terminates.

**Comment by hayd** [comment]
@afinch7 perhaps a hacky fix is to add the corresponding Deno.exit() if successful?
https://github.com/denoland/deno/blob/31115067cd3156db1ead0dc0f11c78875840dc4f/cli/js/unit_test_runner.ts#L99

**Comment by bartlomieju** [comment]
@afinch7 I did a little bit of testing and can confirm that the problem is in `netConcurrentAccept` - it hangs and there's one pending promise. Looks like `Listener has been closed` is never errored which suggests problem with notifying future that listener has been closed. 

```ts
testPerm({ net: true }, async function netConcurrentAccept(): Promise<void> {
  const listener = Deno.listen({ port: 4502 });
  let acceptErrCount = 0;
  const checkErr = (e): void => {
    console.error(`check err ${e.kind} ${e}`);
    assertEquals(e.kind, Deno.ErrorKind.Other);
    if (e.message === "Listener has been closed") {
      assertEquals(acceptErrCount, 1);
    } else if (e.message === "Another accept task is ongoing") {
      acceptErrCount++;
    } else {
      throw new Error("Unexpected error message");
    }
  };
  const p = listener.accept().then(() => {
    console.error('p resolved');
  }, () => {
    console.error('p rejected');
  }).catch(checkErr);
  const p1 = listener.accept().then(() => {
    console.error('p1 resolved');
  }).catch(checkErr);
  await Promise.race([p, p1]);
  listener.close();
  console.error(`pre await ${p} ${p1}`);
  await Promise.all([p, p1]);
  console.error(`post await`);
  console.error(Deno.resources());
  assertEquals(acceptErrCount, 1);
  console.error(`post assert`);
});
```

`post await` is never reached.

**Comment by afinch7** [comment]
@bartlomieju I managed to solve that issue. Still not entirely sure what the problem was, but it works now. Only thing still broken is std tests and some of the lockfile tests on platforms other than linux.

**Comment by bartlomieju** [comment]
@afinch7 nice, I can take a look and try to solve it in the evening

**Comment by bartlomieju** [comment]
@afinch7 I just test your branch locally (macOS) a few times, all of them working fine. Can you try rerunning CI? Also try merging latests master, @ry disabled some of flaky test for lock files.

Anyway, this is a huge PR and it's gonna be a merge-conflict nightmare so I suggest we land it as soon as we get it to green and start linting codebase later.

**Comment by afinch7** [comment]
> EDIT: Ha! After few more runs of standard library tests I managed to hang it on subprocess

**Comment by bartlomieju** [comment]
@afinch7 over the weekend I'll fork this branch and try to get it up to speed with master - I did a lot of changes in #3342 and need to get up to speed with new futures API anyway :+1:

**Comment by afinch7** [comment]
Ok. I'll see what other problems I can fix before then.

**Comment by afinch7** [comment]
I went ahead and rebased this, but I forked the branch before I did [afinch7/use_std_future_11_14_19](https://github.com/afinch7/deno/tree/native_bindings_rust_futures_api).

**Comment by afinch7** [comment]
Closing in favor of #3358

**Pull request closed without merging**
