### PR TITLE
feat(ext/net): Use Socket2 crate to create TcpListener

### PR DESCRIPTION
**Pull request by Trolloldem**
After a first attempt in solving #1195 in #13794, it has been noticed that the **SO_REUSEADDR** option has to be defaulted to true in order to pass the `net` unit tests. In the same PR was proposed to do the porting to Socket2 and the support to the options **SO_REUSEADDR** and **SO_REUSEPORT** in two separate PR. This PR presents the TcpListener implementation based on Socket2.

It is possible to notice that:
1. the **SO_REUSEADDR** option is defaulted to true only for non-windows systems, following the implementation of `TcpListener.bind()` of [std::net](https://github.com/rust-lang/rust/blob/6343edfa11c80ffed02de7e059178d4c1637ecdb/library/std/src/sys_common/net.rs)
2. similarly, the socket type is set to `SOCK_STREAM` and the `backlog` argument of `listen()` is set to 128

These steps should produce a TcpListener equal to the one produce by the instruction `std::net::TcpListener::bind(&addr)?;`

### CODE REVIEW

**Comment by bartlomieju** [comment]
@Trolloldem something is off in this PR, it contains commits that were already landed on `main` branch

**Comment by Trolloldem** [comment]
> @Trolloldem something is off in this PR, it contains commits that were already landed on `main` branch

My bad, now it should be solved with a correct rebase

**Comment by Trolloldem** [comment]
@bartlomieju the CI failure seems related to a rustc failure. On my branch all the CI seem to pass. It is possible to try to re-run the tests?

**Comment by bartlomieju** [comment]
> @bartlomieju the CI failure seems related to a rustc failure. On my branch all the CI seem to pass. It is possible to try to re-run the tests?

Yes, you need to push empty commit to trigger new CI run: `git commit --allow-empty -m "reset CI"`

**Comment by Trolloldem** [comment]
@bartlomieju all CI seem fine now. Are there any additional changes / information required?

**Review by bartlomieju — APPROVED** [review]
LGTM, thank you @Trolloldem

**Pull request merged**
