### PR TITLE
doc: Fix duplicated words 'use of use of'

### PR DESCRIPTION
**Pull request by tedhexaflow**

### CODE REVIEW

**Review by satyarohith — APPROVED** [review]
LGTM - Thanks!

**Comment by tedhexaflow** [comment]
The first-time committer, and It just a minor typo fix.  
I'm not sure why the check is failing.
Can someone please helps me advise how to fix the failing checks?
Many Many Thanks 🙏

**Comment by lucacasonato** [comment]
The markdown file you changed was not formatted correctly. I have formatted it and pushed to this branch :-)

**Comment by tedhexaflow** [comment]
Thank you so much @lucacasonato.

I've just created the PR directly from Github. 
I should have cloned and check locally first before submitting the PR.
🙏

**Review by piscisaureus — APPROVED** [review]

**Pull request merged**
