### PR TITLE
chore: upgrade deno_core

### PR DESCRIPTION
**Pull request by bartlomieju**

### CODE REVIEW

**Comment by 0f-0b** [comment]
#23986 fixes the failed test.

**Comment by bartlomieju** [comment]
@0f-0b thanks, I remember that your PR needed to be landed, however I'm trying to land one more `deno_core` before doing final upgrade. Would you mind, if I merged your branch into this one and add attribution?

**Comment by 0f-0b** [comment]
> Would you mind, if I merged your branch into this one and add attribution?

No, I wouldn't. Thanks.

**Comment by bartlomieju** [comment]
Closing in favor of https://github.com/denoland/deno/pull/23986

**Pull request closed without merging**
