### PR TITLE
releases v1.7.5

### PR DESCRIPTION
**Pull request by justjavac**

### CODE REVIEW

**Comment by lucacasonato** [comment]
Thanks, but the changelog was updated in https://github.com/denoland/deno/commit/e9669bf0656c2478416f6705ff218539dc42c126 on the https://github.com/denoland/deno/tree/v1.7 branch.

**Comment by ry** [comment]
I think we still want to keep a record of the releases in the main branch tho? I would land this.

**Comment by nayeemrmn** [comment]
Intuitively I think the release PR should target `main`, be cherry-picked into the minor branch and get tagged there.

**Review by ry — APPROVED** [review]
Thanks @justjavac

**Pull request merged**
