### PR TITLE
feat(std/datetime): generalise parser, add formatter

### PR DESCRIPTION
**Pull request by timreichen**
# Changes
- generalise parser to parse ```string``` to ```date``` with custom format
- rename ```parseDate``` and ```parseDateTime``` functions to ```parse```
- add tokenizer
- add formatter to format a ```date``` to ```string``` with custom format
- update readme

### CODE REVIEW

**Comment by timreichen** [comment]
@bartlomieju could you do en evaluation and review on this?

**Comment by timreichen** [comment]
@Soremwar I think you need to resign the CLA.

**Comment by timreichen** [comment]
Thanks for your answer.
### RegExp
I agree, that would make more sense.
I changed the test to a function that can handle both regexp and string comparisons.
Also replaced all possible values to string comparison instead of regexp.

### Breaking change
Yes, the breaking change will be the renaming of ```parseDate``` and ```parseDateTime``` to ```parse``` since it can handle both now.

**Comment by timreichen** [comment]
@ry One test did not finish, don't know why. Do you know what's going on?

**Comment by timreichen** [comment]
@ry finally ready for merge.

**Comment by ry** [comment]
@timreichen Looks like the diff is a bit messed up. Please rebase/squash this branch so there's a clean diff.

**Comment by timreichen** [comment]
@ry rebase done. Diffs are clean now.

**Pull request merged**
