### PR TITLE
fix: revert changes to test output for uncaught errors

### PR DESCRIPTION
**Pull request by bartlomieju**
Alternative to https://github.com/denoland/deno/pull/15230 as suggested in https://github.com/denoland/deno/pull/15230#discussion_r923425583

CC @dsherret @nayeemrmn

### CODE REVIEW

**Comment by nayeemrmn** [comment]
I suggest removing this loop which causes the change in output (`... cancelled` and num failures): https://github.com/denoland/deno/blob/45c49034a7ea20f27287cd8559ea050d8973bfae/cli/tools/test.rs#L1156-L1164 and also any place `TestResult::Cancelled` is referenced which would become dead code.

**Comment by nayeemrmn** [comment]
Or I guess changing the test is valid as well... out of curiosity has anyone been able to reproduce the flaky unexpected output locally? Running repeatedly on main (debug), https://github.com/denoland/deno/commit/0f6b455c964933692f4c82476692ab66eba242c2 on canary linux (release), https://github.com/denoland/deno/commit/0f6b455c964933692f4c82476692ab66eba242c2 on canary windows (release), I still haven't seen it. Seems to only happen on windows fastci.

**Comment by bartlomieju** [comment]
> Or I guess changing the test is valid as well... out of curiosity has anyone been able to reproduce the flaky unexpected output locally? Running repeatedly on main (debug), [0f6b455](https://github.com/denoland/deno/commit/0f6b455c964933692f4c82476692ab66eba242c2) on canary linux (release), [0f6b455](https://github.com/denoland/deno/commit/0f6b455c964933692f4c82476692ab66eba242c2) on canary windows (release), I still haven't seen it. Seems to only happen on windows fastci.

No, I haven't been really able to reproduce the problem locally (M1, both debug and release). I'm more than open to changing the test output to avoid the flakiness.

**Review by dsherret — APPROVED** [review]
LGTM. I haven't been able to reproduce it on linux or windows after ~40mins of repeating the test in multiple test runners.

**Pull request merged**
