### PR TITLE
feat(upgrade): link to release notes

### LINKED ISSUE #16350: Add link to changelog in denon upgrade output.
I think it would be useful for the console output of deno upgrade to include a link to the changelog — I always end up trying to remember where it is when I upgrade. 🦕

### PR DESCRIPTION
**Pull request by iuioiua**
This change prints a link to the release notes to `deno upgrade` output and its variations.

Release notes aren't printed for commands relating to canary versions. My main concern is, is testing required for this change?

Also, on second thought, I've omitted the note for `deno --version`.

Closes #16350.

### CODE REVIEW

**Review by bartlomieju — COMMENTED** [review]
I think we should link to a blog post as well (`https://deno.com/blog/v{version}`).

@crowlKats can you verify locally that it works as expected?

**Comment by iuioiua** [comment]
> I think we should link to a blog post as well (`https://deno.com/blog/v{version}`).
> 
> @crowlKats can you verify locally that it works as expected?

Minor versions don't usually get their own blog posts. What if we instead link to the blog post within the changelog for those versions with one?

**Comment by bartlomieju** [comment]
> > I think we should link to a blog post as well (`https://deno.com/blog/v{version}`).
> > @crowlKats can you verify locally that it works as expected?
> 
> Minor versions don't usually get their own blog posts. What if we instead link to the blog post within the changelog for those versions with one?

Minor versions do get blog posts, but patches don't - that's a good point. Maybe you could add a conditional to check if that's a minor version we upgraded to?

**Comment by iuioiua** [comment]
> Minor versions do get blog posts, but patches don't - that's a good point. Maybe you could add a conditional to check if that's a minor version we upgraded to?

Yeah, sorry, I meant the patch version.

**Comment by iuioiua** [comment]
Done 👍🏾

**Review by crowlKats — APPROVED** [review]
LGTM. 
The output looks right as well:
Screenshot 2023-01-24 at 13 23 42

**Pull request merged**
