### PR TITLE
feat: use trust-dns-resolver in HTTP client

### PR DESCRIPTION
**Pull request by bartlomieju**
Follow up to #2822

### CODE REVIEW

**Comment by bartlomieju** [comment]
This is pretty esoteric error... @ry, @piscisaureus can you tell why `sccache` is stopped after tests on AppVeyor but is never stopped on Travis?

**Comment by bartlomieju** [comment]
@ry should be landable now. Strange sccache error is gone after removal of `build.py`

**Comment by ry** [comment]
Deferring to @piscisaureus because he was looking into this earlier.

**Comment by ry** [comment]
This patch caused the executable to grow by 1.5 MB

Screen Shot 2019-09-09 at 6 24 06 PM

I'm considering backing out of this change because it doesn't seem to have reduced the number of threads as I was hoping... @bartlomieju what do you think?

**Comment by bartlomieju** [comment]
I was to propose it... @ry I agree we should revert it, there's no apparent gain now from using this crate

**Pull request merged**
