### PR TITLE
feat(core): Ability to create snapshots from existing snapshots

### PR DESCRIPTION
**Pull request by bartlomieju**
## DON'T MERGE YET

### CODE REVIEW

**Review by crowlKats — APPROVED** [review]

**Review by littledivy — APPROVED** [review]

**Comment by KnorpelSenf** [comment]
The fact that the PR description hasn't been updated gives me anxiety. Will v1.28.2 kill innocent kittens now?

**Comment by bartlomieju** [comment]
> The fact that the PR description hasn't been updated gives me anxiety. Will v1.28.2 kill innocent kittens now?

No

**Comment by KnorpelSenf** [comment]
Good to hear

**Comment by bartlomieju** [comment]
I updated the description of the PR. It's nothing user-facing and there's no need for panic that it might break something.

**Comment by KnorpelSenf** [comment]
Haha nice, thanks. I wasn't seriously worried, I assumed that you had some internal communication about this, but still I appreciate the transparency :)

**Pull request merged**
