### PR TITLE
Add FileInfo.anyModified

### PR DESCRIPTION
**Pull request by dubiousjim**
This is part of a series of PRs towards #4017.

This reports the `ctime` field from Unix (and that's what the field is
named in the internal StatResponse structure).

Better names to use on the TypeScript side are welcome. `ctime` is
problematic because it often gets confused with creation-time.
`metadataModified` is a reasonable candidate, because this field (unlike
`modified`) gets refreshed whenever a file is chmod-ed, etc. But this
field is *also* refreshed whenever data is written. (So it will always
be at least as new as `modified`.)

### CODE REVIEW

**Comment by ry** [comment]
What’s it called in Go, Node, Rust, and Python? Let’s choose from one of those.

**Comment by dubiousjim** [comment]
> What’s it called in Go, Node, Rust, and Python? Let’s choose from one of those.

They didn't seem to give much guidance. When they exposed `ctime`, it was using a naming pattern that we already departed from.

Go: os.Stat returns a `FileInfo`, which has only a method `ModTime()` (nothing for atime, ctime, birthtime, so far as I can see)

For mtime, atime, and birthtime, we're started with the naming pattern of Rust's std::fs::Metadata. They use `modifed`, `accessed`, and `created` for these respectively. (Different host OSs call birthtime by different names, if they expose it at all.) std::fs::Metadata doesn't expose ctime.

Rust's std::os::unix::fs::MetadataExt uses `ctime`, `mtime`, `atime` (doesn't expose birthtime).

The nix crate for Rust uses `st_ctime`, `st_mtime`, `st_atime` (also lacks birthtime).

Node: fs.statSync returns a Stats, which has fields `ctime`, `mtime`, `atime`, `birthtime`

Python: os.stat returns a stat_result, which has fields `st_ctime`, `st_mtime`, `st_atime`, `st_birthtime`

**Comment by dubiousjim** [comment]
So we'd be breaking new ground in choosing how to extend the Rust std::fs naming pattern to `ctime`. Perhaps a conservative name-choice would be `ctime` or `changed`. But for the former we'd be breaking the pattern we've started following (and it would end up sometimes being confused with `created`). For the latter, it'd end up sometimes being confused with `modified`.

I'm not fond of `anyModified`, and of course it'd need explaining too. Maybe someone else will have a more inspired name choice.

**Comment by ry** [comment]
I'm closing this one because stale. I don't think there is any burning need for ctime right now. We can revisit at some other time and refer back to this patch as a guide. I appreciate the work @dubiousjim - sorry for not getting it in.

**Pull request closed without merging**
