### PR TITLE
docs: update readme hello world example

### LINKED ISSUE #20873: Getting started shell snippet needs to be updated
``` bash
$ deno run https://deno.land/std/examples/welcome.ts
Warning Implicitly using latest version (0.203.0) for https://deno.land/std/examples/welcome.ts
error: Module not found "https://deno.land/std/examples/welcome.ts".
$ deno run https://examples.deno.land/hello-world.ts
Hello, World!
```

### PR DESCRIPTION
**Pull request by hexmode**
Fixes #20873

### CODE REVIEW

**Review by dsherret — APPROVED** [review]
Thanks!

**Comment by dsherret** [comment]
@hexmode sorry, could you push an empty commit to fix the CI? I would do it myself, but I can't push to other people's main branches.

**Comment by hexmode** [comment]
Did updating the PR do what you wanted?

**Comment by dsherret** [comment]
Yup, thanks!

**Pull request merged**
