### PR TITLE
fix(cli): Use safe shell escaping in `deno install`

### PR DESCRIPTION
**Pull request by solson**
I was hesitant to add a new dependency, but shell escaping is one of those things you really don't want to get wrong. The `shell-escape` crate is used by `cargo` itself.

I did not handle Windows, if any similar issue exists there, since I cannot easily test it.

This also adds `exec` so the parent shell process doesn't stick around — I think this should close https://github.com/denoland/deno/issues/3961.

### CODE REVIEW

**Comment by ry** [comment]
Could you add a test case that demonstrates an escaping failure?

**Comment by solson** [comment]
I added a simple test for something which currently generates a syntactically invalid shell script:

```console
$ deno install foo.ts '"'

$ /home/scott/.deno/bin/foo
/home/scott/.deno/bin/foo: line 3: unexpected EOF while looking for matching `"'
/home/scott/.deno/bin/foo: line 4: syntax error: unexpected end of file

$ cat /home/scott/.deno/bin/foo
#!/bin/sh
# generated by deno install
deno "run" "file:///home/scott/foo.ts" """ "$@"
```

On another note, the Windows tests are going to be broken — I just noticed that the existing tests assume the Windows batch scripts and the non-Windows shell scripts will contain the same syntax, which shouldn't generally be true. How would you prefer to deal with this? We could use platform-specific `if cfg!(windows)` assertions.

**Comment by bartlomieju** [comment]
> I just noticed that the existing tests assume the Windows batch scripts and the non-Windows shell scripts will contain the same syntax, which shouldn't generally be true. How would you prefer to deal with this? We could use platform-specific if cfg!(windows) assertions.

Adding `cfg!(windows)` for Windows tests sounds good to me. @solson please rebase the branch so we can land it.

**Comment by solson** [comment]
Added `cfg!(windows)` to tests and rebased. All behaviour on Windows should be unchanged before and after this PR.

**Review by ry — APPROVED** [review]
LGTM - thanks @solson - sorry for the delayed response!

**Pull request merged**
