### PR TITLE
docs(cli/dts): delete a repeating sentence

### PR DESCRIPTION
**Pull request by RobyCigar**
I remove the second sentence and merge into one sentence, because it's redundant and annoy user to read the same sentences twice.

### CODE REVIEW

**Review by nayeemrmn — APPROVED** [review]

**Comment by bartlomieju** [comment]
@RobyCigar please sign the CLA

**Comment by kt3k** [comment]
Seems targeting a very old branch?

@RobyCigar Can you rebase or merge `main` and change the target branch to `main`?

**Comment by RobyCigar** [comment]
> Seems targeting a very old branch?
> 
> @RobyCigar Can you rebase or merge `main` and change the target branch to `main`?

Alright

**Comment by kitsonk** [comment]
Ok, this PR is still based off a really old branch and has changes in it that are not desired or wanted, reverting old document generation code. 😞   This is because it was assumed the correct branch was `docs_rs` but that is actually a really outdated branch that should be used.

I have extracted the changes and moved it into #10694.  Closing in favour of #10694.

**Pull request closed without merging**
