### PR TITLE
Add service worker for website

### PR DESCRIPTION
**Pull request by sh7dm**
Add service worker for website to make it load faster & offline.

### CODE REVIEW

**Comment by ry** [comment]
I don't think this helps. Closing without merge.

**Comment by sh7dm** [comment]
@ry why? Service worker increases load speed

**Comment by ry** [comment]
Because it increases complexity and the website doesn’t load slowly for me.  If the speed problem is something I’m overlooking - please show some benchmarks.

**Comment by sh7dm** [comment]
@ry this will help users with bad connection (2G/3G). And offline viewing will be possible.

**Comment by sh7dm** [comment]
Does this 9 lines of code increase complexity?
``` js
if ('serviceWorker' in navigator) {
  navigator.serviceWorker.register('/sw.js')
    .then(function(reg) {
      console.log('Service worker has been registered for scope: '+ reg.scope);
    })
    .catch(function(err) {
      console.error("Error when registering service worker:", err);
    })
}
```

**Comment by ry** [comment]
Yes

**Comment by sh7dm** [comment]
@ry If it is, we can remove
``` js
    .then(function(reg) {
      console.log('Service worker has been registered for scope: '+ reg.scope);
    })
```

**Pull request closed without merging**
