### PR TITLE
Add progress bar for 'Downloading...' messages

### LINKED ISSUE #1320: Progress bars for "Downloading" messages
Should be completely in Rust.
This looks like a good library to use: https://github.com/mitsuhiko/indicatif

Starting points is here:
https://github.com/denoland/deno/blob/a8c3b448049912ead5ba025fee9568dcc0786573/src/deno_dir.rs#L152

(After #975 the "Compiling" messages can also be added to the progress bar. It will move the compilation step into Rust. Currently "Compiling" is printed from JS.)

### PR DESCRIPTION
**Pull request by loujiayu**
Closes #1320
The progress bar looks like this:
screen shot 2019-02-11 at 3 56 32 pm

If chunked response has no Content-Length header, the progress bar is hidden.

### CODE REVIEW

**Comment by loujiayu** [comment]
Need create a PR in deno_third_party.

**Comment by kevinkassimo** [comment]
@loujiayu You can create a PR for `deno_third_party`. Once done the CI here should run just fine.

**Comment by hayd** [comment]
I think #1320 was to have a single progress bar for all module downloads (and then a second for compiles)..?

 At the moment this adds another line for every dependency downloaded... IMO the output is already too noisy.

**Comment by ry** [comment]
Hi @loujiayu - I'm quite sorry for the slow response and non-merge. I appreciate the PR but we weren't ready for the progress bar yet. This work is now done in #2309. Many thanks for the effort.

**Pull request closed without merging**
