### PR TITLE
refactor(ext/ffi): use v8::Value instead of serde_v8::Value

### PR DESCRIPTION
**Pull request by bartlomieju**
Follow up to https://github.com/denoland/deno/pull/23034 that removes
another usage of `serde_v8::Value`.

### CODE REVIEW

**Review by aapoalas — APPROVED** [review]
LGTM: Partially I guess I would ask "why?" though?

It's definitely an okay change, no problem, but its also an entirely cold path. Are we trying to get rid of serde?

**Comment by bartlomieju** [comment]
> It's definitely an okay change, no problem, but its also an entirely cold path. Are we trying to get rid of serde?

Yes, we want to remove `serde_v8::Value`. It's an unnecessary indirection in the whole `serde_v8` code that we'd like to eliminate.

**Comment by bartlomieju** [comment]
I actually don't want to do out array, I'll just create one directly in the op.

**Comment by aapoalas** [comment]
> I actually don't want to do out array, I'll just create one directly in the op.

Sounds good to me :)

**Review by aapoalas — APPROVED** [review]

**Review by mmastrac — APPROVED** [review]
LGTM

**Pull request merged**
