### PR TITLE
chore(ext/console): add 'quotes' internal option to Deno.inspect

### PR DESCRIPTION
**Pull request by kt3k**
This adds `quotes` (internal) option to `InspectOptions` and makes `Deno.inspect` optionally compatible to `util.inspect` of Node.

This prepares for https://github.com/denoland/deno/pull/17960

### CODE REVIEW

**Review by bartlomieju — APPROVED** [review]
LGTM

**Review by aapoalas — APPROVED** [review]
LGTM.

**Review by littledivy — COMMENTED** [review]
This should be a symbol exposed to `node:util` via `__bootstrap` namespace (and not userland). We do something similar in ext/web for hidden options for Event class
```js
const { _quotes } = __bootstrap.console;
Deno.inspect(..., { [_quotes]: ["'"] });
```

**Comment by kt3k** [comment]
@littledivy 
> This should be a symbol exposed to node:util via __bootstrap namespace (and not userland). We do something similar in ext/web for hidden options for Event class

Sounds a good idea, but how to write a unit test in that case?

**Comment by bartlomieju** [comment]
> @littledivy
> 
> > This should be a symbol exposed to node:util via __bootstrap namespace (and not userland). We do something similar in ext/web for hidden options for Event class
> 
> Sounds a good idea, but how to write a unit test in that case?

There's no way, you'd need to assign it to `Deno[Deno.internal]` namespace to write a test

**Comment by kt3k** [comment]
Added a TODO comment above the option name for now.

**Pull request merged**
