### PR TITLE
CI: Separate std tests to speed up process.

### LINKED ISSUE #5179: Test std with the latest released deno binary
With a different release cycle, it is no longer correct to test `std` with a `deno` binary from master. CI (and developers) should install and use Deno at the latest release when testing it, just like a third party library. The release notes of any new version of `std` should say "Tested with deno vX.X.X".

### LINKED ISSUE #5186: ci should discriminate between std and core
for discussion and tracking, i'll put together a PR.

Currently, even for a small change in std the entire 20 minute long build process is run. This would enable fixes to std to be tested much quicker.

This is related to #5179 .

### PR DESCRIPTION
**Pull request by sunsetkookaburra**
Closes #5186
~~~Closes #5179 ~~~
this should speed up testing for deno/std, and does not affect testing of the other components of deno.
Add a new (cutdown) CI process to test deno/std separate to the rest of the deno build. This will speed up CI for new std modules, bringing testing time down from 20min to 1-2min. It will ensure modules in std which would affect testing deno itself are tested with the full CI.

### CODE REVIEW

**Comment by sunsetkookaburra** [comment]
the change to the blob test file allows other modules and patches to be added to std/encoding without needing to wait for full ci to lint and test.

**Comment by sunsetkookaburra** [comment]
Any comments on whether this is needed would be appreciated.

**Comment by bartlomieju** [comment]
@sunsetkookaburra thanks for opening the PR. Can you explain a bit what's going on in here? 

Is it adding a second pipeline that tests `std/` against latest release (in addition to `master`)?

**Comment by sunsetkookaburra** [comment]
@bartlomieju 
#5179 was about testing with the latest binary, given that std was separated. But this was seen as unnecessary, so it was closed. (I will remove the work done for this, I put them in the same PR as it was pretty similar to 5186)

This PR is about #5186, and will test std separate to the rest of the deno build (excepting those parts which are more integral and used for testing the binary). This will speed up CI for new std modules, bringing testing time down from 20min to 1-2min.

**Comment by ry** [comment]
@sunsetkookaburra Closing because stale. I'm interested in this if you can actually speed up CI. Thanks for the patch anyway.

**Pull request closed without merging**
