### PR TITLE
Azure pipelines

### PR DESCRIPTION
**Pull request by ry**

### CODE REVIEW

**Comment by ry** [comment]
@kaylangan Thanks! I'm going to start with pipelines in our deno_std module - it seems to work well  https://github.com/denoland/deno_std/blob/master/azure-pipelines.yml 
There was one small UI issue I ran into: https://github.com/Microsoft/azure-pipelines-yaml/issues/89

I'll look into using it for the core deno again in the future - at the moment it's to disruptive. 

Closing this for now.

**Comment by kaylangan** [comment]
Hi @ry,

I just wanted to check in to see how Azure Pipelines is working for you. Have you given any more thought to using it with this repo? Are there blocking issues?

Thanks!

**Comment by ry** [comment]
@kaylangan We've ported the deno standard modules (deno_std) over to azure pipelines - it's working great! Proudly green pipelines on https://deno.land/ 
screen shot 2019-02-12 at 5 51 59 pm

As for porting Deno core over... Well it's complicated. See our massive appveyor file: https://github.com/denoland/deno/blob/master/.appveyor.yml
If you guys have resources to help us port over azure pipelines, that would be welcome and I can support. But it's too low priority for us to take on ourselves now.

**Comment by kaylangan** [comment]
@ry Sounds great! We would definitely be interested in helping. I'll reach out when we start just to make sure we don't duplicate any efforts. I don't anticipate we'd be able to take a look until late March or so.

**Pull request closed without merging**
