### PR TITLE
fix: do not panic running invalid file specifier

### LINKED ISSUE #20056: Bug: Panic when trying to run invalid file
## Steps to reproduce

1. Run `deno run 'file://asdf'`

Error:

```sh
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos aarch64
Version: 1.36.0
Args: ["deno", "run", "file://asdf"]

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', cli/args/flags.rs:671:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### PR DESCRIPTION
**Pull request by yazan-abdalrahman**
This update prevents a panic in `specifier_to_file_path` on Windows by validating the file URL before calling `to_file_path()`. It ensures that:

Paths are checked to be absolute and are converted if needed.
The path is verified to exist before passing it to `to_file_path()`, ensuring invalid paths don't cause the application to crash.
This fix gracefully handles invalid or non-standard file URLs, avoiding panics during path resolution.

fix #20056

Co-authored-by: Bedis Nbiba [bedisnbiba@gmail.com](mailto:bedisnbiba@gmail.com)

### CODE REVIEW

**Comment by yazan-abdalrahman** [comment]
@bartlomieju @dsherret  
Please verify this solution again.  I overwrite it

**Review by dsherret — APPROVED** [review]
LGTM. Thanks!

**Comment by yazan-abdalrahman** [comment]
@dsherret 

Why don’t we check if the file exists directly within the `specifier_to_file_path` method instead of handling it separately in places that use this method?


The current approach in `specifier_to_file_path `checks only for the validity of the URL format but does not ensure that the file it points to exists. This leads to issues in different parts of the code where it didn't handle invalid or non-existent paths might cause panics, such as when running scripts.

For example, I insert this code to handle the running script to prevent it from panic if file doesn't exist, but u revert it.
 ```
   for path in &start_paths {
            if !path.exists() || !path.is_dir() || path == Path::new("/") {
              let path_str = match &flags.subcommand {
                DenoSubcommand::Run(run) => &run.script,
                _ => path.to_str().unwrap_or("Invalid path"),
              };
              return Err(deno_core::error::uri_error(format!(
                "Invalid file path.\n  Specifier: {path_str}"
              )));
            }
          }
```

```
		       if let Ok(file_path) = specifier_to_file_path(&module_specifier) {
              if let Some(parent_path) = file_path.parent() {
                Some(vec![parent_path.to_path_buf()])
              } else {
                Some(vec![file_path.to_path_buf()])
              }
```
		  

I think we should handle the file existence check directly within `specifier_to_file_path`. so, we avoid handling this check in multiple places, reducing the risk of missing it and preventing potential panics when paths don’t exist. This centralizes the validation, ensuring both the specifier format is valid and the file exists in one step, simplifying the overall error handling. 


If we centralize the file existence check in` specifier_to_file_path`, we'll need to update tests that currently use valid specifiers but point to non-existent files. These tests should be modified to add actual files to the test data to ensure they pass.

**Comment by dsherret** [comment]
> Why don’t we check if the file exists directly within the specifier_to_file_path method instead of handling it separately in places that use this method?

That would be slow. Additionally, we don't always use `specifier_to_file_path` with paths that exist.

> For example, I insert this code to handle the running script to prevent it from panic if file doesn't exist like deno run  'file:///a/b.ts' , but u revert it.

That code didn't have a test that failed after it was removed and I don't believe it's the right approach (instead stuff should fail when it goes to load the file)

**Pull request merged**
