### PR TITLE
refactor use primordials in extensions/webgpu

### PR DESCRIPTION
**Pull request by bartlomieju**
https://github.com/denoland/deno/issues/11224

### CODE REVIEW

**Review by satyarohith — APPROVED** [review]
WebGPU flies are huge. I should've checked the line count of the files before I started the review. 😄 

Nice work, Bartek. I couldn't find a single instance unaddressed.

LGTM.

**Comment by SimonRask** [comment]
Found some things in `01_webgpu.js`:
- line 615
- line 1761

Found nothing in `02_idl_types.js`

**Comment by satyarohith** [comment]
Thanks for taking a look, @SimonRask!

**Comment by CrimsonCodes0** [comment]
There were a few accesses on TypedArray/DataView objects that aren't using primordials here, e.g. directly accessing the `.buffer` property.

**Comment by bartlomieju** [comment]
> There were a few accesses on TypedArray/DataView objects that aren't using primordials here, e.g. directly accessing the `.buffer` property.

@CrimsonCodes0 I believe this is the same situation as with `.length`. Node doesn't really use primordials for such accesses.

**Comment by CrimsonCodes0** [comment]
> > There were a few accesses on TypedArray/DataView objects that aren't using primordials here, e.g. directly accessing the `.buffer` property.
> 
> @CrimsonCodes0 I believe this is the same situation as with `.length`. Node doesn't really use primordials for such accesses.

String length are array length properties are safe to access, as that is the only way to access them. String have an immutable own property length, while arrays have a "magic" own property that has setting intercepted by the engine to cast the written value to an unsigned integer.

TupedArray properties are very different, in that they aren't nearly as safe, nor are they own properties. `%TypedArray%.prototype.{buffer, byteLength, length}` are all getters that exist on the `%TypedArray%` prototype, amd thus are able to be mutated by user code.

If it would be appreciated, I can make some PRs tommorow to implement these accessors and use them across Deno's builtin JavaScript.

**Comment by bartlomieju** [comment]
@CrimsonCodes0 thanks explanation. Please do open a PR.

**Pull request merged**
