### PR TITLE
fix(ext/node): ECDH.publicKey() point encoding 

### PR DESCRIPTION
**Pull request by littledivy**
Fixes https://github.com/denoland/deno/issues/22921

### CODE REVIEW

**Review by satyarohith — APPROVED** [review]
LGTM

**Comment by DeabitTech** [comment]
guys but isn't fixed by the way, from my supabase edge function using deno i have this error using web-push deno version: "Not implemented: crypto.ECDH" please fix it

**Comment by bartlomieju** [comment]
@DeabitTech you should contact Supabase directly, they are using a forked version of Deno.

**Comment by DeabitTech** [comment]
```
import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
import webpush from "https://esm.sh/web-push@3.6.5?target=deno";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
};

// ENV
const VAPID_PUBLIC_KEY = Deno.env.get("VAPID_PUBLIC_KEY")!;
const VAPID_PRIVATE_KEY = Deno.env.get("VAPID_PRIVATE_KEY")!;

webpush.setVapidDetails(
  "mailto:info@gargandeli.com",
  VAPID_PUBLIC_KEY,
  VAPID_PRIVATE_KEY
);

Deno.serve(async (req) => {
  // OPTIONS per i CORS
  if (req.method === "OPTIONS") {
    return new Response("ok", { status: 200, headers: corsHeaders });
  }

  if (req.method !== "POST") {
    return new Response("Method Not Allowed", {
      status: 405,
      headers: corsHeaders,
    });
  }

  try {
    const { orderId } = await req.json();

    if (!orderId) {
      return new Response("Missing orderId", {
        status: 400,
        headers: corsHeaders,
      });
    }

    /* 1) Supabase client */
    const supabase = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
    );

    /* 2) Rider disponibili */
    const now = new Date();
    const dow = now.getDay();
    const hh = now.getHours().toString().padStart(2, "0");
    const mm = now.getMinutes().toString().padStart(2, "0");
    const current = `${hh}:${mm}:00`;

    const { data: riders } = await supabase
      .from("RiderAvailability")
      .select("rider_id")
      .eq("is_active", true)
      .eq("day_of_week", dow)
      .or(
        `all_day.eq.true,and(start_time.lte.${current},end_time.gte.${current})`
      );

    const riderIds = riders?.map((r) => r.rider_id).filter(Boolean) ?? [];

    /* 3) Recupero subscriptions */
    const { data: subscriptions } = await supabase
      .from("PushSubscription")
      .select("endpoint, p256dh, auth")
      .in("profile_id", riderIds);

    if (!subscriptions || subscriptions.length === 0) {
      return new Response(JSON.stringify({ noSubscriptions: true }), {
        status: 200,
        headers: corsHeaders,
      });
    }

    /* 4) Payload */
    const payload = JSON.stringify({
  notification: {
    title: "Nuovo ordine disponibile 🚴",
    body: "Vuoi accettarlo?",
  },
  data: {
    orderId
  }
});

    /* 5) Invia push */
    let sent = 0;
    let failures = [];

    for (const s of subscriptions) {
      try {
        await webpush.sendNotification(
          {
            endpoint: s.endpoint,
            keys: {
              p256dh: s.p256dh,
              auth: s.auth,
            },
          },
          payload
        );

        sent++;
      } catch (err) {
        failures.push(err?.message ?? "unknown");
      }
    }

    return new Response(
      JSON.stringify({ ok: true, sent, failures }),
      { status: 200, headers: corsHeaders }
    );
  } catch (err) {
    return new Response(JSON.stringify({ error: err.message }), {
      status: 500,
      headers: corsHeaders,
    });
  }
});
```


this is my simple function, so if i import Deno from the source code, will i avoid this error? can you provide to me a right remote import about Deno to insert in my code? Thank you for the support

**Pull request merged**
