### PR TITLE
perf(ext/url): use Ada URL parser

### PR DESCRIPTION
**Pull request by littledivy**
Ada is fast URL parser used in Node.js. https://github.com/ada-url/ada

```
# this patch
target/release/deno run -A cli/bench/url_parse.js
time 2258 ms rate 4428697
time 2240 ms rate 4464285

# main
deno run -A cli/bench/url_parse.js
time 2855 ms rate 3502626
time 2835 ms rate 3527336
```

### CODE REVIEW

**Review by lucacasonato — COMMENTED** [review]
I am very concerned about using a separate URL parser for user code and internal code. Because these parse differently, it is very likely we will run into security vulnerabilities down the line where the two different parsers parse the same string into different representations, which bypasses some security mechanism.

`rust-url` is very widely used throughout Deno (especially in module resolution, at startup), so improvements to `rust-url` would be much more impactful than replacing the implementation backing `URL`.

**Comment by lucacasonato** [comment]
And the point is not that ada is better or worse at WPT or anything else like that. Ada seems cool, and is specifically not my point of contention. The problem is that if there are URLs where ada and rust-url disagree on how they parse a string into the URL representation, then two different parts of the system might disagree on, for example, what the host name is. If the permissions system says the hostname is `x.com` and checks this, and the `fetch` implementation thinks the hostname is `y-x.com` and connects there, we have a problem.

**Comment by littledivy** [comment]
Fair enough. I'm convinced this is not the best way forward.

**Comment by anonrig** [comment]
Is there anything we can do on Ada make your lives easier? cc @lemire

**Comment by lemire** [comment]
@lucacasonato 

>  The problem is that if there are URLs where ada and rust-url disagree on how they parse a string into the URL representation (...)

Are there such URLs?

**Pull request closed without merging**
