### PR TITLE
Add support for X-Deno-Warning header

### PR DESCRIPTION
**Pull request by ry**

### CODE REVIEW

**Comment by lucacasonato** [comment]
We should have docs about this header.

**Comment by ry** [comment]
@lucacasonato ok docs added

**Comment by ry** [comment]
@bartlomieju This would be better in the file_fetcher module, but I couldn't find any place that actually worked for displaying the message. Hence http_util. I figure this can be moved at a later point. Or if you know a better place to put it now we can move it...

**Comment by lucacasonato** [comment]
> LGTM, but I want to once again express my dislike for this solution and propose to remove untagged imports from `deno.land/std/` (instead use `deno.land/std@master` or `deno.land/std@1.0.0`).

Ref https://github.com/denoland/deno_website2/issues/250

**Comment by ry** [comment]
> In my opinion this header shouldn't be documented or considered public. I can think of many usages of this header to display unwanted info (just like stuff displayed during npm install).

I'm not so worried about registry spam - but I changed my mind and agree it should be undocumented. This isn't something we necessarily want to support forever - let's just keep it an internal feature until some future date.

> LGTM, but I want to once again express my dislike for this solution and propose to remove untagged imports from deno.land/std/ (instead use deno.land/std@master or deno.land/std@1.0.0).

Noted. Let's discuss in a couple weeks when the dust has settled. I predict the number of incompatibility complaints drops to zero.

**Comment by nayeemrmn** [comment]
> I'm not so worried about registry spam - but I changed my mind and agree it should be undocumented. This isn't something we necessarily want to support forever - let's just keep it an internal feature until some future date.

I infer that this is being added just to warn people against linking to master for `deno.land`. In response to a security concern, I once suggested this feature as a way for publishers to warn users of vulnerabilities that can be updated against. I think some kind channel for this is important.

**Pull request merged**
