### PR TITLE
fix(websocket): add missing close events and remove extra error event

### LINKED ISSUE #7604: WebSocket don't call close event when error occurs
I am run a server with 
```sh
deno run -A https://deno.land/std@0.70.0/ws/example_server.ts
```

And consume with

```js
import { deferred } from "https://deno.land/std@0.70.0/async/deferred.ts";

const p = deferred();

const endpoint = "ws://localhost:8080";

const ws = new WebSocket(endpoint);
ws.onopen = (e) => {
  console.log("open");
};
ws.onerror = (e) => {
  console.log("error", e, ws.readyState);
};
ws.onclose = (e) => {
  console.log("close", e.code, e.reason);
  p.resolve();
};
ws.onmessage = (e) => {
  console.log("message", e.data);
};

await p;
```

When I stop server, "onclose" wasn't called, only "onerror"

I realized that this also occurs when I try to connect to a server that responds with http 503

```
deno 1.4.1
v8 8.7.75
typescript 4.0.2
```

### PR DESCRIPTION
**Pull request by crowlKats**
Fixes #7604

### CODE REVIEW

**Review by bartlomieju — COMMENTED** [review]
@crowlKats thanks, could you add a test case exercising this change?

**Comment by crowlKats** [comment]
@bartlomieju not really, as the errors that would cause these events are unexpected errors from either the client or the server.

**Comment by ry** [comment]
@crowlKats what about a test that counts the number of events? Wouldn't that be a sufficient test?

**Comment by crowlKats** [comment]
@ry well we would need to somehow force an unexpected error to happen to test anything of the sort

**Review by bartlomieju — APPROVED** [review]

**Pull request merged**
