### PR TITLE
feat(doc): Add importmap flag (#7783)

### LINKED ISSUE #7783: deno doc --importmap option
In Deno 1.4.1 the `doc` command doesn't support the `--importmap` option

This makes it impossible to generate documentation for modules using import maps

### PR DESCRIPTION
**Pull request by SyrupThinker**
Closes #7783

### CODE REVIEW

**Comment by kitsonk** [comment]
This probably needs an integration test (`cli/tests/integration.rs`), as the flag tests only test that the flag gets parsed out.

**Comment by bartlomieju** [comment]
@SyrupThinker LGTM, please rebase

**Comment by SyrupThinker** [comment]
PR #7032 needs to be updated to account for this new usage

**Review by kitsonk — APPROVED** [review]
LGTM

**Pull request merged**
