### PR TITLE
feat(extensions/web): add structuredClone function

### LINKED ISSUE #11539: Add self.structuredClone()
Spec: https://github.com/whatwg/html/commit/1b5099fcf55cc6332fb9af5d36ac4db47749438b

### PR DESCRIPTION
**Pull request by crowlKats**
Closes #11539

### CODE REVIEW

**Comment by bartlomieju** [comment]
Changing milestone to 1.14 as additional work is required in WPT (upstream).

**Comment by jeremyBanks** [comment]
Should we consider giving this a more-precise type signature, instead of returning `any`?

I'm not sure whether this would be appropriate or not, but here's a first take at a function signature that preserves most type information for supported types, while stripping out methods for custom types.

It might not be perfect, but we should be able to get it close enough that the type information comes in handy much more often than it gets in the way (by forcing a cast).

```ts
export const structuredClone = <Value>(
  value: Value,
): Cloned<Value> => {
  // deno-lint-ignore no-explicit-any
  const core = (Deno as any).core;
  return core.deserialize(core.serialize(value));
};

type StructuredCloneablePrimitives =
  | bigint
  | boolean
  | number
  | string
  | null
  | undefined;

type StructuredClonable =
  | StructuredCloneablePrimitives
  | { [key: string]: StructuredClonable }
  | Array<StructuredClonable>
  | ArrayBuffer
  | ArrayBufferView
  | BigInt
  | Blob
  // deno-lint-ignore ban-types
  | Boolean
  | Date
  | Error
  | EvalError
  | Map<StructuredClonable, StructuredClonable>
  // deno-lint-ignore ban-types
  | Number
  | RangeError
  | ReferenceError
  | RegExp
  | Set<StructuredClonable>
  // deno-lint-ignore ban-types
  | String
  | SyntaxError
  | TypeError
  | URIError;

/**
 * Modifies a type to remove any values that will not be preserved by
 * structured cloning.
 */
type Cloned<Value> = Mutable<Value> extends StructuredCloneablePrimitives ? // Leave primitives and primitive constants as-is.
Value
  : {
    [Property in keyof Value]: Value[Property] extends // Leave primitives and primitive constants as-is.
    StructuredCloneablePrimitives ? Value[Property]
      : // For most collection types, recursively apply over their type arguments.
      Value[Property] extends Map<infer K, infer V> ? Map<Cloned<K>, Cloned<V>>
      : Value[Property] extends Set<infer V> ? Set<Cloned<V>>
      : Value[Property] extends [] ? []
      : Value[Property] extends Array<unknown> ? Cloned<Value[Property]>
      : Value[Property] extends Record<string, unknown>
        ? Cloned<Value[Property]>
      : // If it's a non-collection type that's directly clonable, keep it as-is
      // to preserve its methods and other type information.
      Value[Property] extends StructuredClonable ? Value[Property]
      : // Matching this, but not Array above, may indicate a tuple type.
      Mutable<Value[Property]> extends Array<infer V> ? // If it only contains primitives, preserve as-is for convenience.
      V extends StructuredCloneablePrimitives ? Value[Property]
      : // Otherwise, we treat it as a simple array. It's unclear whether
      // there's any supported and stable way to map Cloned over the tuple
      // items instead.
      Cloned<Value[Property]>
      : never;
  };

type Mutable<T> = {
  -readonly [P in keyof T]: Mutable<T[P]>;
};

const v = structuredClone({
  x: 2,
  y: 3,
  q: [1, [2], "hello"] as const,
  r: [3, 5, 6],
  d: new Uint8Array(1),
  magnitude() {
    return Math.sqrt(this.x + this.y);
  },
  child: {
    name: "child",
    echo() {
      alert("echo");
    },
  } as const,
});

console.log(v.x);
console.log(v.y);
console.log(v.q[1][0].toExponential()); // allowed: method on number in tuple
console.log(v.r.at(4)); // allowed: method on array
console.log(v.d.fill(0)); // allowed: method on Uint8Array
console.log(v.magnitude()); // error: method on non-supported type
console.log(v.child.name);
console.log(v.child.echo()); // error: method on non-supported type
```

**Comment by lucacasonato** [comment]
The WPT fix is up at https://github.com/web-platform-tests/wpt/pull/29942.

I have verified manually that all expected tests pass:

```
Going to run 1 test files.
----------------------------------------
/html/webappapis/structured-clone/structured-clone.any.html

test primitive undefined ... ok
test primitive null ... ok
test primitive true ... ok
test primitive false ... ok
test primitive string, empty string ... ok
test primitive string, lone high surrogate ... ok
test primitive string, lone low surrogate ... ok
test primitive string, NUL ... ok
test primitive string, astral character ... ok
test primitive number, 0.2 ... ok
test primitive number, 0 ... ok
test primitive number, -0 ... ok
test primitive number, NaN ... ok
test primitive number, Infinity ... ok
test primitive number, -Infinity ... ok
test primitive number, 9007199254740992 ... ok
test primitive number, -9007199254740992 ... ok
test primitive number, 9007199254740994 ... ok
test primitive number, -9007199254740994 ... ok
test primitive BigInt, 0n ... ok
test primitive BigInt, -0n ... ok
test primitive BigInt, -9007199254740994000n ... ok
test primitive BigInt, -9007199254740994000900719925474099400090071992547409940009007199254740994000n ... ok
test Array primitives ... ok
test Object primitives ... ok
test Boolean true ... ok
test Boolean false ... ok
test Array Boolean objects ... ok
test Object Boolean objects ... ok
test String empty string ... ok
test String lone high surrogate ... ok
test String lone low surrogate ... ok
test String NUL ... ok
test String astral character ... ok
test Array String objects ... ok
test Object String objects ... ok
test Number 0.2 ... ok
test Number 0 ... ok
test Number -0 ... ok
test Number NaN ... ok
test Number Infinity ... ok
test Number -Infinity ... ok
test Number 9007199254740992 ... ok
test Number -9007199254740992 ... ok
test Number 9007199254740994 ... ok
test Number -9007199254740994 ... ok
test BigInt -9007199254740994n ... ok
test Array Number objects ... ok
test Object Number objects ... ok
test Date 0 ... ok
test Date -0 ... ok
test Date -8.64e15 ... ok
test Date 8.64e15 ... ok
test Array Date objects ... ok
test Object Date objects ... ok
test RegExp flags and lastIndex ... ok
test RegExp sticky flag ... ok
test RegExp unicode flag ... ok
test RegExp empty ... ok
test RegExp slash ... ok
test RegExp new line ... ok
test Array RegExp object, RegExp flags and lastIndex ... ok
test Array RegExp object, RegExp sticky flag ... ok
test Array RegExp object, RegExp unicode flag ... ok
test Array RegExp object, RegExp empty ... ok
test Array RegExp object, RegExp slash ... ok
test Array RegExp object, RegExp new line ... ok
test Object RegExp object, RegExp flags and lastIndex ... ok
test Object RegExp object, RegExp sticky flag ... ok
test Object RegExp object, RegExp unicode flag ... ok
test Object RegExp object, RegExp empty ... ok
test Object RegExp object, RegExp slash ... ok
test Object RegExp object, RegExp new line ... ok
test Blob basic ... failed
test Blob unpaired high surrogate (invalid utf-8) ... failed
test Blob unpaired low surrogate (invalid utf-8) ... failed
test Blob paired surrogates (invalid utf-8) ... failed
test Blob empty ... failed
test Blob NUL ... failed
test Array Blob object, Blob basic ... ok
test Array Blob object, Blob unpaired high surrogate (invalid utf-8) ... ok
test Array Blob object, Blob unpaired low surrogate (invalid utf-8) ... ok
test Array Blob object, Blob paired surrogates (invalid utf-8) ... ok
test Array Blob object, Blob empty ... ok
test Array Blob object, Blob NUL ... ok
test Array Blob object, two Blobs ... ok
test Object Blob object, Blob basic ... ok
test Object Blob object, Blob unpaired high surrogate (invalid utf-8) ... ok
test Object Blob object, Blob unpaired low surrogate (invalid utf-8) ... ok
test Object Blob object, Blob paired surrogates (invalid utf-8) ... ok
test Object Blob object, Blob empty ... ok
test Object Blob object, Blob NUL ... ok
test File basic ... failed
test Array sparse ... ok
test Array with non-index property ... ok
test Object with index property and length ... ok
test Array with circular reference ... ok
test Object with circular reference ... ok
test Array with identical property values ... ok
test Object with identical property values ... ok
test Object with property on prototype ... ok
test Object with non-enumerable property ... ok
test Object with non-writable property ... ok
test Object with non-configurable property ... ok
test ObjectPrototype must lose its exotic-ness when cloned ... ok
test ArrayBuffer ... failed
test MessagePort ... ok

failures:

Blob basic
assert_true: instanceof Blob expected true got false
    at compare_Blob (http://web-platform.test:8000/html/webappapis/structured-clone/structured-clone-battery-of-tests.js:279:3)
    at Object.f (http://web-platform.test:8000/html/webappapis/structured-clone/structured-clone-battery-of-tests.js:19:13)
    at async Test.<anonymous> (http://web-platform.test:8000/html/webappapis/structured-clone/structured-clone-battery-of-tests-harness.js:37:9)

Blob unpaired high surrogate (invalid utf-8)
assert_true: instanceof Blob expected true got false
    at compare_Blob (http://web-platform.test:8000/html/webappapis/structured-clone/structured-clone-battery-of-tests.js:279:3)
    at Object.f (http://web-platform.test:8000/html/webappapis/structured-clone/structured-clone-battery-of-tests.js:19:13)
    at async Test.<anonymous> (http://web-platform.test:8000/html/webappapis/structured-clone/structured-clone-battery-of-tests-harness.js:37:9)

Blob unpaired low surrogate (invalid utf-8)
assert_true: instanceof Blob expected true got false
    at compare_Blob (http://web-platform.test:8000/html/webappapis/structured-clone/structured-clone-battery-of-tests.js:279:3)
    at Object.f (http://web-platform.test:8000/html/webappapis/structured-clone/structured-clone-battery-of-tests.js:19:13)
    at async Test.<anonymous> (http://web-platform.test:8000/html/webappapis/structured-clone/structured-clone-battery-of-tests-harness.js:37:9)

Blob paired surrogates (invalid utf-8)
assert_true: instanceof Blob expected true got false
    at compare_Blob (http://web-platform.test:8000/html/webappapis/structured-clone/structured-clone-battery-of-tests.js:279:3)
    at Object.f (http://web-platform.test:8000/html/webappapis/structured-clone/structured-clone-battery-of-tests.js:19:13)
    at async Test.<anonymous> (http://web-platform.test:8000/html/webappapis/structured-clone/structured-clone-battery-of-tests-harness.js:37:9)

Blob empty
assert_true: instanceof Blob expected true got false
    at compare_Blob (http://web-platform.test:8000/html/webappapis/structured-clone/structured-clone-battery-of-tests.js:279:3)
    at Object.f (http://web-platform.test:8000/html/webappapis/structured-clone/structured-clone-battery-of-tests.js:19:13)
    at async Test.<anonymous> (http://web-platform.test:8000/html/webappapis/structured-clone/structured-clone-battery-of-tests-harness.js:37:9)

Blob NUL
assert_true: instanceof Blob expected true got false
    at compare_Blob (http://web-platform.test:8000/html/webappapis/structured-clone/structured-clone-battery-of-tests.js:279:3)
    at Object.f (http://web-platform.test:8000/html/webappapis/structured-clone/structured-clone-battery-of-tests.js:19:13)
    at async Test.<anonymous> (http://web-platform.test:8000/html/webappapis/structured-clone/structured-clone-battery-of-tests-harness.js:37:9)

File basic
assert_true: instanceof File expected true got false
    at compare_File (http://web-platform.test:8000/html/webappapis/structured-clone/structured-clone-battery-of-tests.js:352:3)
    at Object.f (http://web-platform.test:8000/html/webappapis/structured-clone/structured-clone-battery-of-tests.js:19:13)
    at async Test.<anonymous> (http://web-platform.test:8000/html/webappapis/structured-clone/structured-clone-battery-of-tests-harness.js:37:9)

ArrayBuffer
promise_test: Unhandled rejection with value: object "DataCloneError: Value not transferable"
Error
    at get_stack (http://web-platform.test:8000/resources/testharness.js:3780:21)
    at new AssertionError (http://web-platform.test:8000/resources/testharness.js:3773:22)
    at assert (http://web-platform.test:8000/resources/testharness.js:3763:19)
    at Test.<anonymous> (http://web-platform.test:8000/resources/testharness.js:664:29)
    at Test.step (http://web-platform.test:8000/resources/testharness.js:2087:25)
    at http://web-platform.test:8000/resources/testharness.js:2114:35

failures:

        "Blob basic"
        "Blob unpaired high surrogate (invalid utf-8)"
        "Blob unpaired low surrogate (invalid utf-8)"
        "Blob paired surrogates (invalid utf-8)"
        "Blob empty"
        "Blob NUL"
        "File basic"
        "ArrayBuffer"

file result: failed. 99 passed; 8 failed; 0 expected failure; total 107

========================================

failures:

        "/html/webappapis/structured-clone/structured-clone.any.html - Blob basic"
        "/html/webappapis/structured-clone/structured-clone.any.html - Blob unpaired high surrogate (invalid utf-8)"
        "/html/webappapis/structured-clone/structured-clone.any.html - Blob unpaired low surrogate (invalid utf-8)"
        "/html/webappapis/structured-clone/structured-clone.any.html - Blob paired surrogates (invalid utf-8)"
        "/html/webappapis/structured-clone/structured-clone.any.html - Blob empty"
        "/html/webappapis/structured-clone/structured-clone.any.html - Blob NUL"
        "/html/webappapis/structured-clone/structured-clone.any.html - File basic"
        "/html/webappapis/structured-clone/structured-clone.any.html - ArrayBuffer"

final result: failed. 0 passed; 1 failed; 0 expected failure; total 1
```

I would be comfortable with landing this as is, and enabling the tests on our next regular WPT roll once they have been merged upstream. @bartlomieju WDYT?

**Comment by bartlomieju** [comment]
@lucacasonato fine for me, feel free to land

**Review by lucacasonato — APPROVED** [review]
LGTM. Thanks @crowlKats

@bartlomieju could you also review?

**Review by bartlomieju — APPROVED** [review]
This looks good to me 👍

**Pull request merged**
