### PR TITLE
net: Check for closing status when iterating Listener

### LINKED ISSUE #3308: Closing a Listener causes pending iterators to throw
Reported by @hayd.

```js
const listener = Deno.listen({ port: 8000 });
(async () => {
  for await (const conn of listener);
})();
listener.close();
```
The program should exit without any iterations happening.

```js
const listener = Deno.listen({ port: 8000 });
listener.close();
for await (const conn of listener);
```
Same. It's nonsensical to iterate a listener that's been closed but given the normal behaviour of this iteration it's more intuitive to just skip. Iterators should rarely throw.

### PR DESCRIPTION
**Pull request by nayeemrmn**
Fixes #3308.

### CODE REVIEW

**Comment by nayeemrmn** [comment]
```js
import { serve } from "https://deno.land/std@v0.23.0/http/server.ts";

const body = new TextEncoder().encode("Hello World\n");
const s = serve(":8000");

const f = fetch("http://localhost:8000");

(async () => {
  console.log("http://localhost:8000/");
  for await (const req of s) {
    req.respond({ body });
    s.close()
  }
})();

f.then(x => console.log("fetched"));
```
It seems like @hayd's original example ^ needs a separate fix in std since the server iterator calls `Listener::accept()` directly. Should I do that here?

**Comment by hayd** [comment]
Should this work on latest master?
```
import { serve } from "https://deno.land/std@335e8bd3/http/server.ts";

const body = new TextEncoder().encode("Hello World\n");
const s = serve(":8000");

const f = fetch("http://localhost:8000");

(async () => {
  console.log("http://localhost:8000/");
  for await (const req of s) {
    await req.respond({ body });
    // only service the first req
    break
  }
  s.close();
})();

f.then(x => console.log("fetched"));
```

I'm still seeing the same error.

**Comment by nayeemrmn** [comment]
@hayd You're using `deno` on master, too?

**Comment by hayd** [comment]
`./target/release/deno` after a `cargo build --all`

**Comment by hayd** [comment]
@nayeemrmn Sorry, I made a mistake! It works!

(cargo build --all doesn't build release)

**Pull request merged**
