### PR TITLE
[WIP] console.log() should stringify objects exactly as Node does 

### LINKED ISSUE #3165: console.log() should stringify objects exactly as Node does
Match colors and semantics. 

node's stringify has been tweaked and optimized over many years, changing anything is likely surprising in a bad way.

### PR DESCRIPTION
**Pull request by mhvsa**
Log should have same effect as in Node.js. Fixes https://github.com/denoland/deno/issues/3165

- [ ] Objects with many attirbutes are printed correctly https://github.com/denoland/deno/issues/3213
- [ ] Symbols are displayed https://github.com/denoland/deno/issues/3253

### CODE REVIEW

**Comment by bartlomieju** [comment]
@mhvsa I merged latest master, will you see the rest through?

**Comment by mhvsa** [comment]
Sorry for being unactive for such a long time. I'll again work on it.

**Comment by bartlomieju** [comment]
@mhvsa notified that he'll try to land this PR this week

**Comment by bartlomieju** [comment]
@mhvsa closing as stale, please open a new PR when you're ready

**Pull request closed without merging**
