### PR TITLE
Add instructions for using Deno with Emacs

### PR DESCRIPTION
**Pull request by zeusdeux**

### CODE REVIEW

**Comment by zeusdeux** [comment]
It says prettier failed but doesn’t what failed about said formatting. Any ideas?

**Comment by ry** [comment]
Please run "tools/format.py"

**Comment by zeusdeux** [comment]
Ah I was hoping the check output would gimme that since I committed via GitHub directly haha

Will clone and run that now. Thanks!

**Comment by zeusdeux** [comment]
Ok so this seems a bit weird. I get no errors locally (?)

image

**Comment by zeusdeux** [comment]
Ran it manually on the md file. 🤞

**Comment by zeusdeux** [comment]
Thanks for landing it!

**Pull request merged**
