### PR TITLE
feat(std/testing): add assertInstanceOf

### PR DESCRIPTION
**Pull request by buttercubz**
Add an assertInstanceOf function for std/testing/asserts.ts

### CODE REVIEW

**Comment by bartlomieju** [comment]
Is there prior art for such assert? It's the same amount of chars to type as `assert(foo instanceof Person)` and it seems it's superfluous.

**Comment by buttercubz** [comment]
@bartlomieju should i change it in the test?

**Comment by nayeemrmn** [comment]
Duplicate of #5749.

**Comment by bartlomieju** [comment]
Thanks for the effot @buttercubz but I'm gonna close this PR without merge, as it is a duplicate of already closed PR as pointed by @nayeemrmn. It's always good to open an issue first and discuss before adding new APIs.

**Comment by buttercubz** [comment]
@bartlomieju 
Thank you, I'll have it in mind

**Pull request closed without merging**
