### PR TITLE
Bump checkout action version

### PR DESCRIPTION
**Pull request by imbsky**

### CODE REVIEW

**Comment by imbsky** [comment]
Submodule option is no longer supported. (and the default depth is 1, so we don't need that option.)

**Comment by ry** [comment]
Is there some improvement? Checkout works fine and this looks more complex.

**Comment by imbsky** [comment]
Here is the changelog. It certainly looks a bit complicated, but I don't think it's a bad idea to keep following the new version. and current CI configuration is already a bit complicated.
https://github.com/actions/checkout/releases/tag/v2.0.0

**Comment by lucacasonato** [comment]
> Is there some improvement? Checkout works fine and this looks more complex.

Its apparently faster because it doesn't check out the entire history - only the commit that is actually being tested.

**Comment by hayd** [comment]
Best to wait til this is fixed in v2 (seems kinda crazy everyone would be copying this).
https://github.com/actions/checkout/issues/81

**Comment by bartlomieju** [comment]
Thanks @imbsky, but we're gonna stick with v1 for now

**Comment by imbsky** [comment]
2.1.0 has been released.
https://github.com/actions/checkout/releases/tag/v2.1.0

**Pull request closed without merging**
