### PR TITLE
fix(core): disable asm.js codegen+validation

### PR DESCRIPTION
**Pull request by 00ff0000red**
Fixes issue https://github.com/denoland/deno/issues/7949.

V8 provides the --validate-asm and --no-validate-asm flags, the latter causes V8 to ignore the "use asm" prologue directive, preventing V8 from logging misnumbered lines to the console.

I passed the flag via cli to v8-flags and it appeared to have worked without consequence or effect.

If, instead anyone on the Deno core team deems it worth investigating and fixing, please feel free to reject this PR.

Will this pass without a test?

### CODE REVIEW

**Comment by lucacasonato** [comment]
I don't see how this is testable so preliminary LGTM from me.

@bnoordhuis @piscisaureus do you have opinions on this?

**Comment by 00ff0000red** [comment]
> I don't see how this is testable so preliminary LGTM from me.

Maybe we could set up an invalid file that uses no IO, then ensure that it doesn't send anything to stdout; this would prevent the current behavior.

**Comment by 00ff0000red** [comment]
Added a test anyway, broke the lint, and added an *empty* file for comparison, should be good to go!

**Comment by bnoordhuis** [comment]
No objections from me.

@00ff0000red Are you the author of https://bugs.chromium.org/p/v8/issues/detail?id=11280 by any chance?

**Review by ry — APPROVED** [review]
LGTM - I confirmed test fails on master

**Comment by 00ff0000red** [comment]
> Are you the author of https://bugs.chromium.org/p/v8/issues/detail?id=11280 by any chance?

That is funnily suspicious, but no, I had actually seen their post while roaming around crbugs (interesting to read about V8's bad Wasm codegen), and it had prompted me to come back to this (I'd long since forgotten that asmjs existed), but I used it as my source of info for this PR.

**Comment by 00ff0000red** [comment]
> LGTM - I confirmed test fails on master

Doesn't seem to work either way, should I just remove the test?

**Comment by bnoordhuis** [comment]
Speaking for myself, I'm okay with landing this without a test.

**Comment by ry** [comment]
landed - thanks @00ff0000red

**Pull request merged**
