### PR TITLE
fix(napi): update env_test.js

### PR DESCRIPTION
**Pull request by bartlomieju**

### CODE REVIEW

**Review by lucacasonato — APPROVED** [review]
cc @littledivy

**Comment by littledivy** [comment]
This is supposed to return the `Node` global to Node-API modules. This test should pass.

**Comment by bartlomieju** [comment]
> This is supposed to return the `Node` global to Node-API modules. This test should pass.

This test was relying on "fake global" passed to "op_napi_open" constructor so it wasn't really testing the global object anyway.

**Comment by littledivy** [comment]
Oh I see, sounds good.

**Pull request merged**
