### PR TITLE
feat: dial tls

### PR DESCRIPTION
**Pull request by bartlomieju**
This PR is revamp of #2326 by @jorsi

Updated to latest ops infra

### CODE REVIEW

**Comment by bartlomieju** [comment]
Alright I got it to work :tada:

Unfortunately couldn't get it to work with local server and self-signed cert so I falled back to just connecting to github in tests.

CC @ry @jorsi

**Comment by bartlomieju** [comment]
In the future we'd want to add an option to allows users to add certificates - that should be fairly easy with [add_pem_file](https://docs.rs/rustls/0.15.1/rustls/struct.RootCertStore.html#method.add_pem_file) method.

**Comment by jorsi** [comment]
Woohoo!

**Comment by ry** [comment]
@bartlomieju I want to land https://github.com/denoland/deno/pull/2926 first. Please update your API to follow that branch: `dialTLS(address, options)`

**Comment by bartlomieju** [comment]
rebased on top of #2926

**Comment by ry** [comment]
@bartlomieju looks good - please merge this branch https://github.com/ry/deno/tree/feat-dial_tls which has some renames and another test

**Comment by ry** [comment]
actually - I'm going to land this in a new PR and attempt to get the author line correct 
https://github.com/denoland/deno/pull/3007

**Pull request closed without merging**
