### PR TITLE
fix(build) Refactor build.rs to better handle old glibc

### PR DESCRIPTION
**Pull request by LukeChannings**
Follow-up to #16208.

- Refactors build.rs behaviour to use `-exported_symbols_list` / `--export-dynamic-symbol-list`
- Since all build systems now rely on a symbols list file, I have added `generate_exported_symbols_list`, which derives the symbol list file depending on the platform, which makes `tools/napi/generate_link_win.js` redundant.
- Fixes a missed instance of `i8` being used instead of `c_char`

### CODE REVIEW

**Comment by LukeChannings** [comment]
@littledivy

**Comment by ry** [comment]
@LukeChannings What version of glibc does it support with this? It would be great if this allowed us to run on glibc 2.23 (Ubuntu 16)

**Comment by LukeChannings** [comment]
> @LukeChannings What version of glibc does it support with this? It would be great if this allowed us to run on glibc 2.23 (Ubuntu 16)

Seems to work fine against the ubuntu:16.04 docker image, tested against aarch64 only, see output below.

```
root@09bae5bd899f:/deno# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.7 LTS"
root@09bae5bd899f:/deno# ./target/
release/ tmp/
root@09bae5bd899f:/deno# ./target/release/
.fingerprint/    deno             examples/        incremental/     libnapi_sym.so   libtest_napi.so
build/           deps/            gn_out/          libdeno_ops.so   libtest_ffi.so   test_server
root@09bae5bd899f:/deno# ./target/release/deno --version
deno 1.26.1 (release, aarch64-unknown-linux-gnu)
v8 10.7.193.13
typescript 4.8.3
root@09bae5bd899f:/deno# ldd --version
ldd (Ubuntu GLIBC 2.23-0ubuntu11.3) 2.23
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
root@09bae5bd899f:/deno# uname -am
Linux 09bae5bd899f 5.10.124-linuxkit #1 SMP PREEMPT Thu Jun 30 08:18:26 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
root@09bae5bd899f:/deno#
```

**Review by littledivy — COMMENTED** [review]
@LukeChannings Thank you for looking into this. The symbol generation script was there to avoid doing this at build-time since its very rarely updated. Can we generalize `generate_link_win.js` for Linux and macOS?

The glibc check LGTM

**Comment by LukeChannings** [comment]
> @LukeChannings Thank you for looking into this. The symbol generation script was there to avoid doing this at build-time since its very rarely updated. Can we generalize `generate_link_win.js` for Linux and macOS?
> 
> The glibc check LGTM

I can look into it. Are we ok with having it output three separate files?

**Comment by LukeChannings** [comment]
@littledivy Can I get another review?

**Review by littledivy — APPROVED** [review]
LGTM!

**Pull request merged**
