### PR TITLE
fix: update deno_graph to fix importing config as JSON module

### PR DESCRIPTION
**Pull request by kitsonk**
Ref denoland/deno_graph#166

### CODE REVIEW

**Comment by kitsonk** [comment]
This will need publishes of deno_graph and then deno_doc and eszip to be completed.

Updating deno_doc does cause some changes in behaviour of `deno doc`, all improvements and fixes, but technically "new features" that come from other changes that can't be decoupled.

**Review by lucacasonato — APPROVED** [review]

**Comment by lucacasonato** [comment]
Mh, just tried my original example on canary, and it is still erroring with `error: Loading unprepared module: file:///mnt/artemis/Projects/github.com/denoland/fresh/www/deno.json`. Did I miss something?

**Comment by kitsonk** [comment]
Bah, I had a specific test case in deno_graph for this, but I didn't actually add a test case to this PR and I should have.  I will investigate. Apologies.

**Comment by nayeemrmn** [comment]
To propagate the changes, `ModuleEntry::Configuration` should be removed, graph imports should be added as a `GraphData` field and they should be walked in `GraphData::walk()` and cloned in `GraphData::graph_segment()`

**Pull request merged**
