### PR TITLE
feat(unstable): Add deno test --no-run

### LINKED ISSUE #7775: Add deno test --no-run
- `deno cache foo.ts bar.ts --test` -> `deno cache foo.ts bar.ts <...files captured by "deno test">`
- `deno cache foo.ts bar.ts --test=baz/,qux/` -> `deno cache foo.ts bar.ts <...files captured by "deno test bar/ qux/">`

Alternatively `deno test --no-run` (`cargo` has both).

EDIT: Went with the second option `deno test --no-run` to avoid the awkward flag value for `--test=dir1,dir2`.

### PR DESCRIPTION
**Pull request by nayeemrmn**
Closes #7775.

### CODE REVIEW

**Comment by bartlomieju** [comment]
@nayeemrmn I thought more about this problem and I propose:
```
deno cache
deno cache --worker
deno test --cache
```
`deno cache` currently caches dependencies and type checks all files from given entry point. If we were to add `deno cache --test` we're starting to interleave `deno test` glob resolution into `cache` command. Adding `deno cache --worker` just adds another TS library to type check. (Maybe it should be `deno cache --lib worker`?)

**Comment by nayeemrmn** [comment]
> I thought more about this problem and I propose:
> 
> ```
> deno cache
> deno cache --worker
> deno test --cache
> ```

Sounds good, as I said `cargo` has both `cargo build --tests` and `cargo test --no-run`. I think matching `deno test --no-run` would be more clear. It's a similar scheme to `--no-check`.

**Comment by bartlomieju** [comment]
> > I thought more about this problem and I propose:
> > ```
> > deno cache
> > deno cache --worker
> > deno test --cache
> > ```
> 
> Sounds good, as I said `cargo` has both `cargo build --tests` and `cargo test --no-run`. I think matching `deno test --no-run` would be more clear. It's a similar scheme to `--no-check`.

Agreed, I was thinking `--dry` but `--no-run` is self-explanatory 👍

**Comment by bartlomieju** [comment]
@nayeemrmn let's require `--unstable` for this flag for the time being

**Review by bartlomieju — APPROVED** [review]
LGTM, thanks @nayeemrmn

**Pull request merged**
