### PR TITLE
 feat: return a signal string instead number on ChildStatus 

### LINKED ISSUE #14491: Inconsistency in API between `Child.kill()` and `ChildStatus.signal`
To kill a child you need to send a `Deno.Signal`, but the child status report a `number` instead
It may make more sense to use the same type for both

https://doc.deno.land/deno/unstable/~/Deno.ChildStatus
```ts
type ChildStatus = {
  success: true;
  code: 0;
  signal: null;
} | {
  success: false;
  code: number;
  signal: number | null;
};
```

https://doc.deno.land/deno/unstable/~/Deno.Child#kill
```ts
class Child<T extends SpawnOptions> {
  kill(signo: Signal): void;
}
```

### PR DESCRIPTION
**Pull request by crowlKats**
Closes #14491

### CODE REVIEW

**Review by kt3k — DISMISSED** [review]
LGTM. Nice!

**Comment by kt3k** [comment]
Just saw @AaronO's comment in the chat room. Looks like we're not in agreement in general direction?

**Comment by kt3k** [comment]
BTW node.js looks returning string for this https://nodejs.org/api/child_process.html#subprocesssignalcode

Node.js accepts both string and number as input of `kill()` https://nodejs.org/api/child_process.html#subprocesskillsignal

**Comment by crowlKats** [comment]
> Just saw @AaronO's comment in the chat room. Looks like we're not in agreement in general direction?

well, during the meeting there was a general consensus, especially because of the node compat

**Review by kt3k — APPROVED** [review]
Ok. Then LGTM 👍

**Pull request merged**
