### PR TITLE
fix(cli/repl): keyboard interrupt should continue

### PR DESCRIPTION
**Pull request by caspervonb**
This changes the behavior of keyboard interrupts (ctrl+c) to continue, clearing the current line instead of exiting.

Exit can still be done with ctrl+d or by calling close().

### CODE REVIEW

**Comment by David-Else** [comment]
This sounds really bad, ctrl+c means kill the process. It has always meant that. What is the point of this bizarre perversion of Unix?!

https://superuser.com/questions/169051/whats-the-difference-between-c-and-d-for-unix-mac-os-x-terminal

```
CtrlC tells the terminal to send a SIGINT to the current foreground process, which by default translates into terminating the application. CtrlD tells the terminal that it should register a EOF on standard input, which bash interprets as a desire to exit.
```

**Comment by littledivy** [comment]
This seems to be the default behavior with Python, although Node does ask for confirmation.
image

**Comment by caspervonb** [comment]
> This sounds really bad, ctrl+c means kill the process. It has always meant that. What is the point of this bizarre perversion of Unix?!

Bash clears and continues.
Python clears and continues.
Ruby clears and continues.
Node clears and continues (but does allow you to hit it again immediately to exit).

**Comment by ry** [comment]
Maybe print "exit using ctrl+d or close()" again?

**Comment by nayeemrmn** [comment]
Note that the existing SIGINT behaviour still remains when an actual execution in interrupted:
image

**Comment by caspervonb** [comment]
> Maybe print "exit using ctrl+d or close()" again on ^c ?

Since you phrased that as maybe, I think its a bit noisy, never liked Node doing it.
Prefer mimicking bash/zsh as a good examples of prompts but I'll yield if anyone feels strongly about it.

> Note that the existing SIGINT behaviour still remains when an actual execution is interrupted:

Been playing around with the new Runtime.terminateExecution method but that ends up killing the whole process which is somewhat unexpected.

**Comment by bartlomieju** [comment]
@nayeemrmn @caspervonb this is a long standing issue - https://github.com/denoland/deno/issues/1725 - we need some kind of signal watchdog to implement that (I know tokio has APIs for that), and most likely tinker with `deno_core` to get it working.

**Comment by caspervonb** [comment]
> @nayeemrmn @caspervonb this is a long standing issue - #1725 - we need some kind of signal watchdog to implement that (I know tokio has APIs for that), and most likely tinker with deno_core to get it working.

In this case we are catching the signal, it's just a matter of what do we do with it but research required so out of scope for this PR.

**Comment by bartlomieju** [comment]
> Maybe print "exit using ctrl+d or close()" again on ^c ?

That sounds good to me, but I agree with @caspervonb that we should clear the input line on ^c.

**Review by bartlomieju — APPROVED** [review]
LGTM

**Pull request merged**
