### PR TITLE
fix(std/datetime): uppercase hour symbols

### PR DESCRIPTION
**Pull request by timreichen**
Fix wrong symbol casing.
replace `h` and `hh` with `H` and `HH` respectively.
Lowercase is reserved for 12 hour days, uppercase for 24 hour days.

### CODE REVIEW

**Comment by caspervonb** [comment]
Based on what? e.g https://en.wikipedia.org/wiki/ISO_8601 is 24 hours.

**Comment by timreichen** [comment]
> Based on what? in https://en.wikipedia.org/wiki/ISO_8601 hh is 24 hour format.
Yes, but based on http://www.unicode.org/reports/tr35/tr35-dates.html#Date_Field_Symbol_Table, the upper/lowercase convention is widely adopted in many different languages like swift and java. We  can also prevent a breaking change in the future if we chose to extend date formatting at some point.

**Comment by ry** [comment]
@timreichen Could you add that unicode.org link to the source code, so it's explicit which format we're following?

**Comment by caspervonb** [comment]
Existing code seems to be written with the intent of following ISO 8601.

While we can switch to another specification that should be the entire specification IMHO, not just renaming one symbol to break existing code without any additions.

**Comment by timreichen** [comment]
@caspervonb 
> Existing code seems to be written with the intent of following ISO 8601.

Not quite. ISO 8601 would use uppercase `YYYY` and `DD` symbols according to [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html). I think wikipedia got that wrong.

> While we can switch to another specification that should be the entire specification IMHO, not just renaming one symbol to break existing code without any additions.

I think a full implementation of http://www.unicode.org/reports/tr35/tr35-dates.html#Date_Field_Symbol_Table would be a huge task since it requires localisation of days/months etc. that would need to be hardcoded for every language at the moment. CLU as far as I know is not part of deno [yet](https://github.com/denoland/rusty_v8/pull/390).
The parser as well as the formatter concerns itself only with numbers at the moment.

I proposed switching because there is a lack of symbols in ISO 8601 to cover all [parts](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/formatToParts), is what the tokenizer returns and is compatible with. 

But you are right, maybe it makes more sense to have both upper and lowercase `HH` `hh` implemented instead of replacement.

**Comment by caspervonb** [comment]
Hmm, the temporal is going to the ISO 8601 route so I don't think we should diverge from that as we'd end up having two formats.

> The ParseTemporalTimeString abstract operation parses an ISO 8601 string representing a wall-clock time and returns the information needed to construct a Temporal.Time instance.

https://tc39.es/proposal-temporal/#sec-temporal-parsetemporaltimestring

**Comment by timreichen** [comment]
> Hmm, the temporal is going to the ISO 8601 route so I don't think we should diverge from that as we'd end up having two formats.

I think we are not quite talking about the same, we need to differentiate between `format` and `symbols`.
We don't need the formatter and parser for `ISO format` per se because
1. It is built in js [Date.prototype.toISOString](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString) and [new Date(isoString)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse#Date_Time_String_Format).
2. The formatter and parser are supposed to handle different formats too.

If you want to format a date to let's say uk time format, you cannot do that with `ISO symbols`, because ISO uses 24 hour representation.
Using `ISO symbols` you would get: `hh:mm` -> `13:23`.
You need a symbol to represent 12 hours as well as  `dayPeriod`, ergo the `unicode symbols`: `hh:mm a` -> `01:23 PM`.

**Comment by caspervonb** [comment]
> If you want to format a date to let's say uk time format, you cannot do that with ISO symbols, because ISO symbols use 24 hour representation only.
Using ISO symbols you would get: hh:mm -> 13:23.
You need a symbol to represent 12 hours as well as dayPeriod, ergo the unicode symbols: hh:mm a -> 01:23 PM.

Fair enough 👍

**Comment by timreichen** [comment]
close on favor of #7661

**Pull request closed without merging**
