### PR TITLE
fix(compile): handle TypeScript file included as asset

### LINKED ISSUE #27024: Deno compile leads to TS errors if root directory is included
Version: Deno 2.1.x

If you include the root `--include .` then the compiled executable fails with syntax errors. 

Steps to reproduce
1. Create a simple TS program
```typescript
// example.ts
// This is a TypeScript function and its parameter has a type
function tsFunction(param: any) {
    console.log(param);
}

tsFunction("Hello, World!");
```
2. compile with the root included: `deno compile -A --include . example.ts`

Run the resulting binary:
```
$ ./example
  .error: Uncaught SyntaxError: Unexpected token ':'
    at <anonymous> (file:///var/folders/0v/jhqzvwhx345fsngdr12f6zg00000gn/T/deno-compile-example/fresh-site/symlink_test/example.ts:2:26)
```
It seems that the runtime tries to execute the TS file as if it were a transpiled JS file, probably because it's included at the root.

### PR DESCRIPTION
**Pull request by dsherret**
Closes #27024

### CODE REVIEW

**Comment by irbull** [comment]
I took this PR for a spin and it still seems to be failing with the example I posted in the issue. I'm running on Mac, so maybe that's related? Could also be a problem with how I built (I can't seem to verify after the build that `./deno` was built from the right commit hash). However, I do have `6700ca8cc1b007a9aeae688fd31c75a86cd717c7` checked out and `cargo clean && cargo build` didn't produce any errors, so I'm fairly confident I have the right bits.

**Comment by irbull** [comment]
Actually, I can confirm that my custom built deno is in fact being used for `deno compile`, but I'm not sure that my custom built deno is being used as the runtime for the compiled artifact. Changes I made to `cli/standalone/file_system` do not seem to be reflected in the compiled executable. Would that make sense? Is there something I need to do during `deno compile` to ensure that I'm picking up the latest changes to the standalone runtime?

**Comment by dsherret** [comment]
@irbull you need to set the DENORT_BIN env var (see https://github.com/denoland/deno/pull/27015#discussion_r1855090869 for example)

**Comment by irbull** [comment]
Thanks David, that works! Google for `DENORT_BIN` produces no results, so I guess it's not documented. I've filed https://github.com/denoland/deno/issues/27035 to add it to the docs. Feel free to add my face to that issue and I'll put together a PR.

As for this issue, with a a customer DenoRT, I can confirm that this PR addresses the issue. Furthermore, if you actually try and load the bundled `.ts` file you see the TypeScript (not the transpired JS). Good work.

**Review by bartlomieju — APPROVED** [review]

**Pull request merged**
