### PR TITLE
chore: update std submodule and its imports

### PR DESCRIPTION
**Pull request by iuioiua**
This PR:
1. Updates the Deno standard library to the latest version, v0.171.0.
2. Updates imports to use the latest locations of functions within the Deno standard library due to changes relating to denoland/deno_std#2936.

Sidenote: the difference between the speed of CI now vs before is night and day. Good stuff, @dsherret!

### CODE REVIEW

**Comment by iuioiua** [comment]
The last removes two tests that appear not to be used. The reason is that they imported functions that didn't exist in the files they pointed to. It's possible that these files were read as pure text, rather than TypeScript, in some tests, but I could not find such tests and tests pass fine when these files are deleted. I'll happily restore these files if this is not the case.

**Review by bartlomieju — COMMENTED** [review]
`cat.ts` and `echo_server.ts` are used by `install_file_url` test

**Comment by iuioiua** [comment]
I see that in CI now. I don't know how I missed that... Files restored and updated.

**Review by bartlomieju — APPROVED** [review]
LGTM, thanks

**Pull request merged**
