### PR TITLE
BREAKING(std/fs): remove readJson and readJsonSync

### PR DESCRIPTION
**Pull request by caspervonb**
This removes readJson and readJsonSync from std/fs entirely as they are fairly peculiar functions and the only ones in the std/fs namespace that deals with file input and they only deal with reading JSON from a text file which is very specialized.

The same can be achieved quite easily with `JSON.parse(await Deno.readTextFile("path/to/input.json"));` as-well as  `JSON.parse(Deno.readTextFileSync("path/to/input.json"));` for the synchronous version.

### CODE REVIEW

**Comment by lcswillems** [comment]
I was happily using them in my code! I think these functions are a nice addition to Deno. JSON is a very common file type especially in JS/TS projects. Moreover, if the same can be achieved easily with a longer code, it is an argument to keep it in Deno because it is easy to main + it makes people's life easier for handling JSON files.

**Comment by bartlomieju** [comment]
@lcswillems thanks for the comment. If I'm not mistaken `readJson` and `readJsonSync` are legacy functions that were there before we had `Deno.readTextFile()` API. However I agree with @caspervonb on this one - it's an anti-pattern to add function to `std/` which are one-liners or two-liners. It gives a precedent to add more such helpers. 

I think we should go ahead with removal in `1.4.0` or at least schedule to deprecate in `1.5.0`.

**Review by bartlomieju — APPROVED** [review]
LGTM, thanks @caspervonb

**Comment by exside** [comment]
Mhm, broke many things here =)...but from an engineering standpoint I agree, was actually about to file an issue that readJson should support JSON.parse() reviver functions... as we have to use JSON.parse anyways, that issue is one less =)...

**Comment by Maxvien** [comment]
I have ported the `readJson` & `readJsonSync` into this module: https://deno.land/x/jsonfile

**Pull request merged**
