### PR TITLE
test: disable macos_shared_libraries test

### PR DESCRIPTION
**Pull request by bartlomieju**
This test is flaky: https://github.com/denoland/deno/issues/18341

### CODE REVIEW

**Comment by ry** [comment]
please add `/usr/lib/libobjc.A.dylib` to the list of libs rather than disabling

**Comment by ry** [comment]
It seems odd that this would be flaky - it shouldn't sometime link and sometime not. Maybe this was due to some dependency? Is this debug vs release?

**Comment by bartlomieju** [comment]
> It seems odd that this would be flaky - it shouldn't sometime link and sometime not. Maybe this was due to some dependency? Is this debug vs release?

These flakes happened on `main` branch so they were release builds. I really don't understand how this test could be flaky. Maybe the ordering is not deterministic?

**Comment by bartlomieju** [comment]
> please add `/usr/lib/libobjc.A.dylib` to the list of libs rather than disabling

I can do that, but when I run `otool` on my release build I don't see `libobjc.A.dylib`.

**Review by mmastrac — APPROVED** [review]
LGTM

**Comment by bartlomieju** [comment]
Err, I should have disabled auto-merge after pushing a commit :/

**Comment by littledivy** [comment]
> Maybe the ordering is not deterministic?

The test does not require a certain order tho.

**Pull request merged**
