### PR TITLE
Fix flakiness in std file_server tests

### PR DESCRIPTION
**Pull request by piscisaureus**
Fixes: #5275

### CODE REVIEW

**Comment by piscisaureus** [comment]
There were no leaked ops. 

The problem is that process.close() is neither asynchronous nor blocking. It fires a kill signal and then immediately "forgets" the process. However it takes a while for the process to actually be gone. That causes a problem here because we're creating new file_server processes before the old one is completely gone.

**Comment by ry** [comment]
> However it takes a while for the process to actually be gone.

Is that only on windows?

**Comment by piscisaureus** [comment]
> Is that only on windows? Maybe the drop handler for the process resource should wait?

Options:
  A. Make Process.close() return a promise.
  B. Add `Process.kill()` that sends SIGKILL by default or calls TerminateProcess() on windows. You could then do `p.kill(); await p.status();`.

**Comment by lucacasonato** [comment]
> Options:
> A. Make Process.close() return a promise.
> B. Add `Process.kill()` that sends SIGKILL by default or calls TerminateProcess() on windows. You could then do `p.kill(); await p.status();`.

@piscisaureus `Process.kill` already exists, its unstable at the moment though and does not support Windows.

**Pull request merged**
