### PR TITLE
chore(tests): Deprecate remaining usages of itest in check tests

### PR DESCRIPTION
**Pull request by ingalless**
This PR progresses #22907 by deprecating the usage of `itest` in `tests/integration/check_tests.rs`

### CODE REVIEW

**Comment by ingalless** [comment]
@MohammadSu1 @dsherret  I was in the `tests/integration/check_tests.rs` file recently and noticed 2 more usages of `itest` that needed to be moved. I didn't know if these usages were left deliberately - were they? If not I can move this from out of draft 😄

**Comment by bartlomieju** [comment]
@ingalless thanks for the PR, would you be able to update `tools/lint.js` to mark that `check_tests` have 0 `itest`s?

**Comment by ingalless** [comment]
@bartlomieju thank you for the nudge. All sorted :)

**Review by bartlomieju — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
