### PR TITLE
Support TLS in std http server

### PR DESCRIPTION
**Pull request by sh7dm**

### CODE REVIEW

**Comment by kevinkassimo** [comment]
Looks like we happen to be colliding on this PR. #3257

**Comment by sh7dm** [comment]
@kevinkassimo yea, let's let Ryan choose the best API. Your PR is pretty nice.

**Comment by kevinkassimo** [comment]
@sh7dm Thanks.
I do kind of having some concern over merging them to use a unified `serve` API though. Golang does differentiate `listenAndServe` and `listenAndServeTLS` though.

**Comment by sh7dm** [comment]
@kevinkassimo we can create two overloads, and a function with 1 arg (`addrOrOptions: string | ListenOptions | ListenTLSOptions`)

**Comment by sh7dm** [comment]
For options api we probably need `type HTTPListenOptions = Partial<ListenTLSOptions>` with further checking in fn body. And addr string as a fallback for backwards compat (with deprectaion notice)

**Comment by kevinkassimo** [comment]
https://github.com/denoland/deno/pull/3257/files#diff-a4c8846df7db4411cface37c385a0ac9R404

**Comment by sh7dm** [comment]
@kevinkassimo yea, I mean smth like this, but with `Partial` and required port, so it could be used for HTTP too.

**Comment by ry** [comment]
oops - indeed a collision! Thanks @sh7dm, but I think #3257 is more complete.

**Comment by sh7dm** [comment]
@ry, no problems, I agree with you.

**Pull request closed without merging**
