### PR TITLE
Remove v8::Locker from deno_respond

### PR DESCRIPTION
**Pull request by afinch7**
This looks unnecessary, but I'm not 100% sure.

### CODE REVIEW

**Comment by ry** [comment]
The benchmarks have been published - there is no noticeable effect from removing this.

**Comment by kevinkassimo** [comment]
Also for this one: https://github.com/denoland/deno/blob/master/core/isolate.rs#L554
Do we need to hold the lock for the whole period of `poll`? (Haven't actually investigated myself)

**Comment by ry** [comment]
@kevinkassimo The idea is that during poll we're calling into JS many times, so it's better to acquire the lock one for all of them rather than in each individual call.

(Looking at the Rust code now, I worry that the Rust compiler might try to free _locker before poll completes. Probably we should add `drop(_locker)` at the bottom.)

**Comment by afinch7** [comment]
@kevinkassimo I don't think so. I tried it, and it seems to work fine.
@ry It looks like we only call into Js when we have completed ops, and only call twice when we overflow the shared queue.

**Pull request merged**
