### PR TITLE
fix(ext/node): add basic node:worker_threads support

### PR DESCRIPTION
**Pull request by kt3k**
This PR restores `node:worker_threads` implementation and test cases from [`std@0.175.0/node`](https://github.com/denoland/deno_std/blob/0.175.0/node/worker_threads.ts).

### CODE REVIEW

**Comment by kt3k** [comment]
Note: This implementation handles the worker entrypoint as ESM, but that should be commonjs for more compatibility (when the file ext is not `.mjs`). Because of that incompatibility, none of native worker_threads test (from Node repo) can be enabled.

**Review by bartlomieju — APPROVED** [review]
LGTM, nicely solved Yoshiya, thanks!

**Comment by bartlomieju** [comment]
> Note: This implementation handles the worker entrypoint as ESM, but that should be commonjs for more compatibility (when the file ext is not `.mjs`). Because of that incompatibility, none of native worker_threads test (from Node repo) can be enabled.

Actually I will try to fix that before landing.

**Comment by bartlomieju** [comment]
Fixed CJS resolution. I will land it as is and enable some more tests in a follow up PR.

**Pull request merged**
