### PR TITLE
docs/build: details on updating rust

### PR DESCRIPTION
**Pull request by balupton**
turns out I was using an old version of rust, and encountering build errors, so added details on updating

this was the error I was getting before:

```
git clone --recurse-submodules  git@github.com:balupton/deno.git
cd deno
git checkout patch-1
rustc -V  # rustc 1.44.1 (c7087fe00 2020-06-17)
cargo -V  # cargo 1.44.1 (88ba85757 2020-06-11)
rustup target add wasm32-wasi
rustup target add wasm32-unknown-unknown
cargo clean && cargo build -vv
```

```
     Running `CARGO=/Users/balupton/.rustup/toolchains/stable-x86_64-apple-darwin/bin/cargo CARGO_MANIFEST_DIR=/Users/balupton/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_doc-0.1.0 CARGO_PKG_AUTHORS='the Deno authors' CARGO_PKG_DESCRIPTION='doc generation for deno' CARGO_PKG_HOMEPAGE= CARGO_PKG_NAME=deno_doc CARGO_PKG_REPOSITORY= CARGO_PKG_VERSION=0.1.0 CARGO_PKG_VERSION_MAJOR=0 CARGO_PKG_VERSION_MINOR=1 CARGO_PKG_VERSION_PATCH=0 CARGO_PKG_VERSION_PRE= DYLD_FALLBACK_LIBRARY_PATH='/Users/balupton/Projects/active/deno/target/debug/deps:/Users/balupton/.rustup/toolchains/stable-x86_64-apple-darwin/lib:/Users/balupton/.rustup/toolchains/stable-x86_64-apple-darwin/lib:/Users/balupton/lib:/usr/local/lib:/usr/lib' rustc --crate-name deno_doc --edition=2018 /Users/balupton/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_doc-0.1.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C debuginfo=2 -C metadata=b18566ee502e71cd -C extra-filename=-b18566ee502e71cd --out-dir /Users/balupton/Projects/active/deno/target/debug/deps -L dependency=/Users/balupton/Projects/active/deno/target/debug/deps --extern futures=/Users/balupton/Projects/active/deno/target/debug/deps/libfutures-259fd8a6bc51e7e8.rmeta --extern lazy_static=/Users/balupton/Projects/active/deno/target/debug/deps/liblazy_static-e9e04a3c8f4980f5.rmeta --extern regex=/Users/balupton/Projects/active/deno/target/debug/deps/libregex-c6d84bca3fcc5830.rmeta --extern serde=/Users/balupton/Projects/active/deno/target/debug/deps/libserde-e6f024cf6acc8b71.rmeta --extern serde_derive=/Users/balupton/Projects/active/deno/target/debug/deps/libserde_derive-0913af816063f9b6.dylib --extern serde_json=/Users/balupton/Projects/active/deno/target/debug/deps/libserde_json-2878a74fe7dacedf.rmeta --extern swc_common=/Users/balupton/Projects/active/deno/target/debug/deps/libswc_common-d52735ad550ecb74.rmeta --extern swc_ecmascript=/Users/balupton/Projects/active/deno/target/debug/deps/libswc_ecmascript-5535b4b4011e08a3.rmeta --extern termcolor=/Users/balupton/Projects/active/deno/target/debug/deps/libtermcolor-f047fca3e804fd8a.rmeta --cap-lints warn`
error[E0658]: use of unstable library feature 'weak_into_raw'
   --> /Users/balupton/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_lint-0.1.23/src/scopes.rs:179:5
    |
179 |     Rc::as_ptr(&self.0) == Rc::as_ptr(&other.0)
    |     ^^^^^^^^^^
    |
    = note: see issue #60728 <https://github.com/rust-lang/rust/issues/60728> for more information

error[E0658]: use of unstable library feature 'weak_into_raw'
   --> /Users/balupton/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_lint-0.1.23/src/scopes.rs:179:28
    |
179 |     Rc::as_ptr(&self.0) == Rc::as_ptr(&other.0)
    |                            ^^^^^^^^^^
    |
    = note: see issue #60728 <https://github.com/rust-lang/rust/issues/60728> for more information

error[E0658]: use of unstable library feature 'weak_into_raw'
   --> /Users/balupton/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_lint-0.1.23/src/scopes.rs:185:5
    |
185 |     Rc::as_ptr(&self.0).hash(state)
    |     ^^^^^^^^^^
    |
    = note: see issue #60728 <https://github.com/rust-lang/rust/issues/60728> for more information

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0658`.
error: could not compile `deno_lint`.

Caused by:
  process didn't exit successfully: `CARGO=/Users/balupton/.rustup/toolchains/stable-x86_64-apple-darwin/bin/cargo CARGO_MANIFEST_DIR=/Users/balupton/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_lint-0.1.23 CARGO_PKG_AUTHORS='the Deno authors' CARGO_PKG_DESCRIPTION='lint for deno' CARGO_PKG_HOMEPAGE= CARGO_PKG_NAME=deno_lint CARGO_PKG_REPOSITORY= CARGO_PKG_VERSION=0.1.23 CARGO_PKG_VERSION_MAJOR=0 CARGO_PKG_VERSION_MINOR=1 CARGO_PKG_VERSION_PATCH=23 CARGO_PKG_VERSION_PRE= DYLD_FALLBACK_LIBRARY_PATH='/Users/balupton/Projects/active/deno/target/debug/deps:/Users/balupton/.rustup/toolchains/stable-x86_64-apple-darwin/lib:/Users/balupton/.rustup/toolchains/stable-x86_64-apple-darwin/lib:/Users/balupton/lib:/usr/local/lib:/usr/lib' rustc --crate-name deno_lint --edition=2018 /Users/balupton/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_lint-0.1.23/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C debuginfo=2 --cfg 'feature="json"' --cfg 'feature="serde"' --cfg 'feature="serde_json"' -C metadata=dd072a982d58e49f -C extra-filename=-dd072a982d58e49f --out-dir /Users/balupton/Projects/active/deno/target/debug/deps -L dependency=/Users/balupton/Projects/active/deno/target/debug/deps --extern lazy_static=/Users/balupton/Projects/active/deno/target/debug/deps/liblazy_static-e9e04a3c8f4980f5.rmeta --extern log=/Users/balupton/Projects/active/deno/target/debug/deps/liblog-884541d0ed4c7378.rmeta --extern regex=/Users/balupton/Projects/active/deno/target/debug/deps/libregex-c6d84bca3fcc5830.rmeta --extern serde=/Users/balupton/Projects/active/deno/target/debug/deps/libserde-e6f024cf6acc8b71.rmeta --extern serde_json=/Users/balupton/Projects/active/deno/target/debug/deps/libserde_json-2878a74fe7dacedf.rmeta --extern swc_atoms=/Users/balupton/Projects/active/deno/target/debug/deps/libswc_atoms-1c4ec990b129b7cb.rmeta --extern swc_common=/Users/balupton/Projects/active/deno/target/debug/deps/libswc_common-d52735ad550ecb74.rmeta --extern swc_ecmascript=/Users/balupton/Projects/active/deno/target/debug/deps/libswc_ecmascript-5535b4b4011e08a3.rmeta --cap-lints warn` (exit code: 1)
warning: build failed, waiting for other jobs to finish…
```

### CODE REVIEW

**Comment by nayeemrmn** [comment]
I don't see why this is needed, it already says to use the latest stable release.

**Comment by balupton** [comment]
The user unfamiliar with rust (like myself) may think they are already on the latest stable release, and not know how to update it.

So this makes it clear and gives them details on how to update.

**Comment by nayeemrmn** [comment]
> So this makes it clear and gives them details on how to update to the latest release.

Why wouldn't they be able to look that up, if they already know to update? We don't have inlined instructions on how to install it in the first place. This doesn't make sense.

**Comment by balupton** [comment]
> Why wouldn't they be able to look that up, if they already know to update? We don't have inlined instructions on how to install it in the first place. This doesn't make sense.

We are talking past each other.

We can address the problem of making it explicitly clear that the user has to use the latest stable release by changing the wording. Right now, it is only explicitly clear that nightlies are not to be used. All that is explicitly clear about using the latest stable release, is that it is requirement at rust install time, not progressively for Deno development.

Whatever solution explicitly instructs the user to update to the latest rust releases I am in favour for.

**Comment by nayeemrmn** [comment]
> All that is explicitly clear about using the latest stable release, is that it is a requirement when installing rust, not when progressively using rust for Deno development.

Sure. Change the word "fetch" to "use" then. Throw the word "progressively" in there if you want. I'm just saying there's no reason to include code snippets on how to update Rust, or check the version (the comments you put there are only going to cause confusion when they go out of date), because it's noisily non-specific to the project.

**Comment by balupton** [comment]
@nayeemrmn how's that

**Comment by caspervonb** [comment]
Hm, we already link to rust/install, don't see this re-wording as being any clearer.

**Comment by dsherret** [comment]
@balupton is there a `third_party` directory on your local machine? (See https://deno.land/manual/contributing/building_from_source#cloning-the-repository on how to clone to get that)

**Review by bartlomieju — APPROVED** [review]
LGTM, @balupton could you run `tools/format.py` to get CI to green?

**Comment by balupton** [comment]
> @balupton is there a `third_party` directory on your local machine? (See https://deno.land/manual/contributing/building_from_source#cloning-the-repository on how to clone to get that)

Yes, the issue in the OP was due to an old rust version, hence the PR.

> LGTM, @balupton could you run `tools/format.py` to get CI to green?

Pulled in the latest and now that tool works. Submitted the change.

**Review by bartlomieju — APPROVED** [review]
LGTM, thanks @balupton

**Pull request merged**
