### PR TITLE
feat(watcher): clear screen on each restart

### PR DESCRIPTION
**Pull request by bartlomieju**
Closes https://github.com/denoland/deno/issues/10622

Quality of life improvement:

https://user-images.githubusercontent.com/13602871/139585342-d6b6e082-c4d1-4b66-87c8-0f7f04781726.mov

### CODE REVIEW

**Review by ry — COMMENTED** [review]
do other systems do this?

**Comment by bartlomieju** [comment]
> do other systems do this?

I saw it in Vite and Next.js

**Comment by lucacasonato** [comment]
I am in favor.

**Comment by David-Else** [comment]
@ry It would be great to get this merged soon! It is needed in Neovim's terminal to use Deno's built-in testing, without it the results just disappear from the bottom of the terminal as they update. The user has to focus on the terminal window and scroll down, this makes it useless in this situation.

**Comment by Im-Beast** [comment]
I'm not sure whether I should create separate issue for that (because it's QOL improvement just like clearing the screen), but imho after each restart watcher should also disable terminal raw mode (`Deno.setRaw`), as it makes it impossible to kill running command using `Ctrl+C`.

**Comment by bartlomieju** [comment]
> I'm not sure whether I should create separate issue for that (because it's QOL improvement just like clearing the screen), but imho after each restart watcher should also disable terminal raw mode (`Deno.setRaw`), as it makes it impossible to kill running command using `Ctrl+C`.

@Im-Beast it seems it's not directly related to this PR, so I suggest to open a new issue.

**Review by dsherret — APPROVED** [review]
LGTM

**Comment by zifeo** [comment]
Some feedbacks after a few days using it: works well but should be configurable. This is a real pain on multi environments where files are linked (dylib) and watch/reload chained.

**Comment by bartlomieju** [comment]
@zifeo please open an issue if you want to have configuration added.

**Pull request merged**
