### PR TITLE
fix(npm): add performance.markResourceTiming sham

### PR DESCRIPTION
**Pull request by bartlomieju**
This commit shams "performance.markResourceTiming" API by
using a noop function. It is done to provide compatibility with
"npm:undici" package. We should look into actually implementing
this API properly, but I wanted to unblock support for "undici" and
"astro" for now.

Ref https://github.com/denoland/deno/issues/19065

### CODE REVIEW

**Comment by bartlomieju** [comment]
Really? It's linking to https://w3c.github.io/resource-timing/#dfn-mark-resource-timing

**Comment by lucacasonato** [comment]
Can you add it just to Node's `perf_hooks` performance object, and not to the global one?

**Comment by bartlomieju** [comment]
> Can you add it just to Node's `perf_hooks` performance object, and not to the global one?
> 
> If unidici uses the global, we may need to do the global replacement thing like we do for `setTimeout`.

It's using the `performance` global. Alright, I'll inject the another global.

**Review by dsherret — APPROVED** [review]
“shim” -> “sham”

**Pull request merged**
