### PR TITLE
fix(ext/node): implement uv.errname

### PR DESCRIPTION
**Pull request by littledivy**
Fixes https://github.com/denoland/deno/issues/20617

### CODE REVIEW

**Review by bartlomieju — APPROVED** [review]
LGTM

**Review by bartlomieju — CHANGES_REQUESTED** [review]
Actually, can you add a test that exercises this function?

**Comment by ry** [comment]
I love to see these little compat bugs getting knocked out. Nice work @littledivy.

Thank you for the bug report @birkskyum

**Comment by birkskyum** [comment]
@ry , glad to be helpful. I'm a front end engineer, and despite being very excited about Deno for years, I haven't been able to let go of Node for a single project, because virtually my entire stack is incompatible. Opening the door towards node compat made me hopeful that this could change, so i decided to [screen](https://github.com/denoland/deno/issues/created_by/birkskyum) Deno support for a big part of the landscape I find myself in. I'm quite confident that delivering on these tickets, as well as allowing opt-in to run postinstall for certain trusted npm deps (sharp, puppeteer etc.), would boost adoption in the front end space significantly.

**Pull request merged**
