### PR TITLE
Styling & fix y axis labels & svg width correction

### LINKED ISSUE #1035: benchmark page: I broke the y-axis
In my quest to simplify the plots, I over generalized and made every y-axis "seconds"

screen shot 2018-10-20 at 12 56 50 am

### PR DESCRIPTION
**Pull request by kevinkassimo**
Closes #1035 

Added a bit more styling.
Fixed y axis labels
Tweaked svg width to make it look better on desktop

(I could separate the y axis label fix if the styling changes is not so okay)

Before:
screenshot from 2018-10-20 02-51-23
screenshot from 2018-10-20 02-51-37
screenshot from 2018-10-20 02-52-00

After:
screenshot from 2018-10-20 02-52-57
screenshot from 2018-10-20 02-53-04
screenshot from 2018-10-20 02-53-14
screenshot from 2018-10-20 02-53-57

(BTW, I own `denoland.org` and I could forward it to this page)

### CODE REVIEW

**Comment by bartlomieju** [comment]
@kevinkassimo looks awesome, what do you think about adding white bg to charts? It would make them more readable IMHO

**Comment by kevinkassimo** [comment]
@bartlomieju done

**Comment by ry** [comment]
Thanks- looks good! But can you leave out the header and image changes for now?

**Comment by kevinkassimo** [comment]
Closed for #1040

**Pull request closed without merging**
