### PR TITLE
Remove timezone dependent tests

### PR DESCRIPTION
**Pull request by ry**
cc @timreichen

### CODE REVIEW

**Comment by bartlomieju** [comment]
Supersedes https://github.com/denoland/deno/pull/7726?

**Comment by ry** [comment]
Probably it's better to just remove timezone specific tests. Then it still passes when you run `deno test std/datetime`. I think Id prefer to land this one than the other. WDYT?

**Comment by bartlomieju** [comment]
> Probably it's better to just remove timezone specific tests. Then it still passes when you run `deno test std/datetime`. I think Id prefer to land this one than the other. WDYT?

I agree with you on that one.

**Review by bartlomieju — APPROVED** [review]
LGTM

**Comment by timreichen** [comment]
@ry @bartlomieju agree, `test` should not have a different tz than `run` imo.

**Pull request merged**
