### PR TITLE
std(media_types): change .ts content type to application/typescript

### PR DESCRIPTION
**Pull request by zhmushan**
follow https://github.com/denoland/deno/pull/4555

### CODE REVIEW

**Comment by KSXGitHub** [comment]
I don't think this database should be modified directly. What if the standard change in the future and we need to update the database using automated script without having our custom patch (typescript in this case) erased? Beside, this is not standard complaint, nor is it useful for all cases.

Instead, I think you should leave the database alone and create another database (let's call it `web_media_types`) for our own patch. Web server can then get Content-Type by doing `web_media_types.contentType(ext) || media_types.contentType(ext)`.

**Comment by zhmushan** [comment]
@KSXGitHub In fact, TS videos cannot be played directly in the browser, and it's no big deal that we make changes

**Comment by ry** [comment]
I don't think it's such a big deal to fork the database... any changes to the database at this point are going to be very minor - I think we would be able to handle maintaining it.

@KSXGitHub your solution is a clean way to overlay changes on top of the existing database... but maybe it's less cognitive overhead to just fork.

**Comment by KSXGitHub** [comment]
@zhmushan Let me re-iterate my points:
1. We may need to update our media type database in the future. Doing so would likely erase this change you made today.
2. Not everyone wants to use /std/media_types for web server. So `.ts` file should report according to standard.

**Comment by KSXGitHub** [comment]
@ry 

Forking would duplicate the amount of data. On the other hand, making a specialized database is very lightweight: It contains only TypeScript and JavaScript.

**Comment by ry** [comment]
@KSXGitHub By "forking" I mean that we would never again pull updates from the origin.

cc @kitsonk

**Comment by kitsonk** [comment]
I'm fine with it. There is no official source for media types. Even this source db is a conglomeration of different sources. I think it is fine to maintain wholly seperate. Git history can serve as our record of differences. If we ever wanted to update from the source again, we would just apply a git diff.

**Pull request merged**
