### PR TITLE
fix(test): `deno test --watch` should default to CWD

### PR DESCRIPTION
**Pull request by GJZwiers**
Fixes https://github.com/denoland/deno/issues/16940

### CODE REVIEW

**Review by dsherret — APPROVED** [review]
LGTM!

**Comment by bartlomieju** [comment]
Can we add a test for this change? It's not immediately obvious what has changed looking at the code 😅

**Comment by GJZwiers** [comment]
@bartlomieju I've added a unit test for `deno test --watch ./`, there was already a test for `deno test --watch` without a path argument. Before the `test_parse` function would return an empty Vec leading to 0 files being watched, now it returns None which triggers the `unwrap_or_else` in the watch code to default to the current working directory (similar to fmt/lint/bench).

**Comment by GJZwiers** [comment]
I've actually fixed this issue in a slightly different way in https://github.com/denoland/deno/pull/17008. I think I will close this PR and move the new test to the other PR.

**Pull request closed without merging**
