### PR TITLE
feat(std/path): Add fromFileUrl()

### LINKED ISSUE #4915: Unexpected parsedArgs on Windows 10 with deno 0.41.0
just updated deno 
```
deno 0.41.0
v8 8.2.308
typescript 3.8.3
```

tried to run a simple script logging a file name and got this issue:
`Uncaught NotFound: The system cannot find the file specified`
referring to
`file:///D:/workspace/github/deno-utility-tex-to-text/tex-to-text.ts`
but pasting the file in Chrome location bar references the file just fine.

Now, this was also broken in 0.38.0 which I upgraded from, so I'm not saying there's a regression.

minimal repro code on Win10, running in git bash (VS Code terminal)
```
import * as path from "https://deno.land/std/path/mod.ts";
import { parse } from "https://deno.land/std/flags/mod.ts";

const parsedArgs = parse(args);
const inpath = parsedArgs.infile;
const outpath = inpath && inpath.replace('.tex', '.txt');

if (inpath && outpath) {
  const normalizedInpath = new URL(inpath, import.meta.url).pathname;
  const sOut = await read_line(normalizedInpath, handleLine);
  console.log(normalizedInpath)
} else {
  console.log('failed to parse infile, inpath, or outpath.')
}
```
ref: https://github.com/Vandivier/deno-utility-tex-to-text

### PR DESCRIPTION
**Pull request by nayeemrmn**
Requested many times recently. cc @seishun @Vandivier @David-Else. Closes #4915.

`new URL().pathname` leaves an unwanted leading slash for Windows drive letter paths.

```ts
// On Windows.
import * as path from "./std/path/mod.ts";

console.log(new URL("file:///C:/Users/Nayeem").pathname); // "/C:/Users/Nayeem"
console.log(path.fromFileUrl("file:///C:/Users/Nayeem")); // "C:\User\Nayeem"

console.log(new URL("abc", import.meta.url).pathname); // "/C:/Users/Nayeem/projects/deno/abc"
console.log(path.fromFileUrl(new URL("abc", import.meta.url))); // "C:\\Users\\Nayeem\\projects\\deno\\abc"

### CODE REVIEW

**Comment by seishun** [comment]
Node.js has [fileURLToPath](https://nodejs.org/api/url.html#url_url_fileurltopath_url) - why not name it the same here?

**Comment by nayeemrmn** [comment]
@seishun Our's is in a `path` "namespace" already.

**Comment by seishun** [comment]
Theirs is in a `url` "namespace" but they still chose to be explicit, which might be a good thing. 🤷

**Comment by nayeemrmn** [comment]
@seishun We have other functions in `path` which don't have a redundant "Path", they have other functions in `url` which don't have a redundant "URL". They wrote "URL" for that one because they needed to write "file URL" which for simplicity I've made ours not specific to. Seems pretty simple to me.

**Comment by seishun** [comment]
So what happens when you call `fromUrl` with a non-file URL?

**Comment by nayeemrmn** [comment]
Treats it like a file URL and ignores the origin. `URL::pathname` suggests any URL has a derivable path. Also I just didn't want to add a pointless assertion that it's a file URL. But even then I would call it `fromFileUrl()` :)

**Comment by seishun** [comment]
> URL::pathname suggests any URL has a derivable path. 

But you want to return a filesystem path, not a URL path. Currently `fromUrl('http://foo.foo/baz/baz')` returns `\baz\baz` on Windows, which is neither.

**Pull request merged**
