### PR TITLE
fix(cli): panic when stdio is null on windows (fix #6409)

### LINKED ISSUE #6409: Panic on executing `deno run` on stdin disabled environment
When executing `deno run` on stdin disabled environment, deno panics as following.

```
2020-06-20T07:11:34.862 [Information] Starting worker process:D:\home\site\wwwroot\bin\windows\deno.exe  run --allow-net --allow-env --allow-read "D:\home\site\wwwroot\worker.bundle.js"
2020-06-20T07:11:35.218 [Information] D:\home\site\wwwroot\bin\windows\deno.exe process with Id=16464 started
2020-06-20T07:11:35.484 [Information] thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 6, kind: Other, message: "The handle is invalid." }', cli\ops\io.rs:86:17
2020-06-20T07:11:35.485 [Information] stack backtrace:
2020-06-20T07:11:35.551 [Information] 0:     0x7ff7554d176f - CrashForExceptionInNonABICompliantCodeRange
2020-06-20T07:11:35.551 [Information] 1:     0x7ff7554f31bb - CrashForExceptionInNonABICompliantCodeRange
2020-06-20T07:11:35.551 [Information] 2:     0x7ff7554c732c - CrashForExceptionInNonABICompliantCodeRange
2020-06-20T07:11:35.551 [Information] 3:     0x7ff7554d4ccc - CrashForExceptionInNonABICompliantCodeRange
2020-06-20T07:11:35.551 [Information] 4:     0x7ff7554d490f - CrashForExceptionInNonABICompliantCodeRange
2020-06-20T07:11:35.551 [Information] 5:     0x7ff7554d54b7 - CrashForExceptionInNonABICompliantCodeRange
2020-06-20T07:11:35.552 [Information] 6:     0x7ff7554d503f - CrashForExceptionInNonABICompliantCodeRange
2020-06-20T07:11:35.552 [Information] 7:     0x7ff7554f1b10 - CrashForExceptionInNonABICompliantCodeRange
2020-06-20T07:11:35.553 [Information] 8:     0x7ff7554f1963 - CrashForExceptionInNonABICompliantCodeRange
2020-06-20T07:11:35.553 [Information] 9:     0x7ff753f0c616 - <unknown>
2020-06-20T07:11:35.553 [Information] 10:     0x7ff754122eca - <unknown>
2020-06-20T07:11:35.553 [Information] 11:     0x7ff753ec4c83 - <unknown>
2020-06-20T07:11:35.553 [Information] 12:     0x7ff753e6949e - <unknown>
2020-06-20T07:11:35.553 [Information] 13:     0x7ff753f7bf69 - <unknown>
2020-06-20T07:11:35.554 [Information] 14:     0x7ff753eb2724 - <unknown>
2020-06-20T07:11:35.554 [Information] 15:     0x7ff753ffc125 - <unknown>
2020-06-20T07:11:35.554 [Information] 16:     0x7ff753f57160 - <unknown>
2020-06-20T07:11:35.554 [Information] 17:     0x7ff7540e9326 - <unknown>
2020-06-20T07:11:35.554 [Information] 18:     0x7ff7554d56ca - CrashForExceptionInNonABICompliantCodeRange
2020-06-20T07:11:35.559 [Information] 19:     0x7ff753f5b027 - <unknown>
2020-06-20T07:11:35.559 [Information] 20:     0x7ff755503df0 - CrashForExceptionInNonABICompliantCodeRange
2020-06-20T07:11:35.559 [Information] 21:     0x7fff7e5a84d4 - BaseThreadInitThunk
2020-06-20T07:11:35.582 [Information] 22:     0x7fff80cae8b1 - RtlUserThreadStart
```

According to the above stack, it is caused by [this change](https://github.com/denoland/deno/commit/1e0808d501cf9adea65e7cacd123ea4fea06a13a#diff-52a4a7cdf78afa52dbd3506067839baa) in https://github.com/denoland/deno/pull/6126 .

I think that deno shouldn't panic even if stdin is disabled, because server side application doesn't necessarily require interaction using stdin. 

I would appreciate your comment.

Thanks
Hiro

Related to https://github.com/anthonychu/azure-functions-deno-worker/issues/13#issuecomment-646988127
/cc @anthonychu

### PR DESCRIPTION
**Pull request by Spoonbender**
Fix issue #6409 
Deno now expects that some standard handles may be missing (inaccessible or unclonable).
These streams are now added to the resource table only if they are present.

Open issues/questions:
- Perhaps it is better to just construct a `StreamResourceHolder` with `StreamResource::FsFile(None)` inside of it?
- Extract a function for repetitive code in static handle initializers?
- Expose stdio streams as `Option` or as `Result`?
- Write an integration test in PowerShell?

### CODE REVIEW

**Comment by ry** [comment]
Thanks - can you add a test that demos the panic?

**Comment by Spoonbender** [comment]
> Thanks - can you add a test that demos the panic?

Yeah, I'll work on that and push an update

**Comment by ry** [comment]
@Spoonbender If you have a small test script that demos the failure I can add it as a test

**Comment by Spoonbender** [comment]
@ry Sorry for the late response.
The following Windows PowerShell script demonstrates the problem by nullifying the STDIN handle, then running a Deno script:
File name: `run-no-stdin.ps`
```powershell
Add-Type @"
  using System;
  using System.Diagnostics;
  using System.IO;
  using System.Runtime.InteropServices;
  public class DenoTest {
    private const int STD_INPUT_HANDLE = -10;

    [DllImport("kernel32.dll")]
    private static extern void SetStdHandle(int nStdHandle, IntPtr handle);

    public static int RunDenoWithoutStdin(string pathToDenoExe, string pathToTestScript) {
      Console.WriteLine("Starting");
      SetStdHandle(STD_INPUT_HANDLE, (IntPtr)null);
      var startInfo = new ProcessStartInfo(pathToDenoExe)
      {
          RedirectStandardInput = false,
          RedirectStandardOutput = true,
          RedirectStandardError = true,
          ErrorDialog = false,
          UseShellExecute = false,
          Arguments = @"run -A " + pathToTestScript,
      };
      startInfo.Environment.Add("RUST_BACKTRACE", "1");
      Process p = new Process { StartInfo = startInfo };
      p.Start();
      StreamReader ereader = p.StandardError;
      string error = ereader.ReadToEnd();
      Console.Error.WriteLine(error);
      p.WaitForExit();
      return p.ExitCode;
    }
  }
"@
$exitcode = [DenoTest]::RunDenoWithoutStdin($args[0], $args[1])
Write-Output("Deno exited with code: $exitcode")
exit $exitcode
```

To run the test, pass the the path to Deno exe as furst argument, and path to a Deno script as second argument, for example: 
`.\run-no-stdin.ps1 D:\src\private\deno\target\debug\deno.exe D:\Temp\deno\test1.ts`

The content of the `test1.ts` file is:
```ts
const sleep = (msec:number) => new Promise(resolve => setTimeout(resolve, msec));

console.log('Start');
await sleep(100);
console.log('Finish')
```

**Comment by piscisaureus** [comment]
Is it possible to run that test as part our CI process?

**Comment by Spoonbender** [comment]
@piscisaureus I'm not familiar with Deno's CI process at all, but if it includes a modern-day Windows machine with PowerShell installed then it should be doable. If you can point me at the right direction then I can try to integrate this test in the CI.

**Comment by caspervonb** [comment]
Take a look at cli/tests/integration_test.rs, basically would want to add this as a custom rust #[test] case.

**Comment by Spoonbender** [comment]
@caspervonb @piscisaureus  
Thank you! I added the relevant tests + utility code, please let me know if further adjustments are needed for it to run in CI.

**Comment by Spoonbender** [comment]
@piscisaureus the advantage of the C# bit is that PowerShell compiles it on the fly. Rewriting in Rust, I guess we'll need a new binary crate just for this purpose... there could be other options though. 
Thanks for the PR.

**Comment by piscisaureus** [comment]
> Thanks for the PR.

Just to be clear, I totally agree!

**Pull request merged**
