### PR TITLE
feat(fmt): support HTML, Svelte, Vue, Astro and Angular

### PR DESCRIPTION
**Pull request by g-plane**
Initially this is a draft PR because there're pending optimizations from markup_fmt. Once I publish a new version of markup_fmt, I will update PR status. While in draft, this PR still can be reviewed.

Close #25015

### CODE REVIEW

**Comment by g-plane** [comment]
Note: I've also upgraded Malva to enable formatting `style` attribute in HTML.

**Comment by bartlomieju** [comment]
@g-plane we discussed this more internally and we'd like to have 2 unstable flags/configs for this PR: `--unstable-html` for HTML files and `--unstable-markup` for all the "framework formats". Could you please apply this change? I think we'll be good to merge this PR after that, unless we're still waiting for more crates updates?

**Comment by g-plane** [comment]
I'm fine with that, but can we call it `--unstable-fmt-component` instead of `--unstable-fmt-markup`?

**Comment by bartlomieju** [comment]
> I'm fine with that, but can we call it `--unstable-fmt-component` instead of `--unstable-fmt-markup`?

Sure!

**Review by dsherret — APPROVED** [review]
LGTM

**Review by bartlomieju — APPROVED** [review]
LGTM too, thank you @g-plane!

**Pull request merged**
