### PR TITLE
feat(core): Add a feature to control whether `include_js_files!` reads files at runtime

### LINKED ISSUE #11030: `deno_core` prints cargo related stuff if used as a dependency
After #10786 I'm getting `cargo:rerun-if-changed=.../core/core.js` and `cargo:rerun-if-changed=.../core/error.js` printed on the console when I have `deno_core` as a dependency, even in release builds.

### PR DESCRIPTION
**Pull request by andreubotella**
Just a prototype. Would close #11030.

### CODE REVIEW

**Review by littledivy — COMMENTED** [review]
@andreubotella This seems reasonable. Are there are any blockers? Please rebase.

**Comment by andreubotella** [comment]
This is now ready for review. I'll squash and write a commit message with details tomorrow.

**Comment by andreubotella** [comment]
The features with which a test is compiled with seem to depend on the directory from which `cargo test` is being run. So for the tests in `ext/net/ops`, running `cargo test` from `ext/net` will compile them without `deno_core/build-time-includes` (because `deno_net` doesn't have it by default), but running it from the root directory will have that feature. To prevent this change from making tests fail, I made it so files are included at compile time if `cfg(test)` is set. However, it seems like `cargo test` only compiles the crate containing the test with that option, and not any dependencies, which is causing the test failures.

I'm not sure how to solve this.

**Comment by andreubotella** [comment]
Closing because #14614 has now reverted the original cause of this bug.

**Pull request closed without merging**
