### PR TITLE
doc: add --unstable for file_server

### PR DESCRIPTION
**Pull request by zhmushan**

### CODE REVIEW

**Comment by zhmushan** [comment]
@ry My deno version is obtained by compiling the master branch
image

**Comment by zhmushan** [comment]
It seems that in v0.42.0, `cwd()` hasn't been marked as unstable

**Comment by ry** [comment]
@zhmushan Hmm. What's the command you're running? I'm using 

```
deno --allow-net --allow-read --reload https://deno.land/std@v0.42.0/http/file_server.ts
```
And it's not calling cwd for me.

(I want to make cwd as stable in the next release, but that's another issue.)

**Comment by zhmushan** [comment]
@ry 
```
.\deno\target\debug\deno --allow-net --allow-read --reload https://deno.land/std@v0.42.0/http/file_server.ts
```
If cwd is stable inthe next release, this pr can be closed

**Comment by ry** [comment]
https://github.com/denoland/deno/pull/5068

**Pull request closed without merging**
