### PR TITLE
feat(test): update test summary report

### LINKED ISSUE #13913: Improve footer in `deno test`
The current footer is a bit noisy and not easy to identify

A improved footer could look something like this:
image

Compared to the current one:
image

Backstory to this issue:
[vitest on twitter](https://twitter.com/alexlafroscia/status/1501204689278443530)
[discord chat](https://canary.discord.com/channels/684898665143206084/684911491035430919/951840231383007302)

### PR DESCRIPTION
**Pull request by mrkldshv**
Updates test summary report to make easier to read. 
* Show summary metric only if metric or its steps is greater than 0.
* Remove `test results` string and change delimiters.

Closes #13913.

**Before:**
Screen Shot 2022-05-16 at 12 55 50

**After:**
Screen Shot 2022-05-16 at 12 55 28

### CODE REVIEW

**Review by dsherret — APPROVED** [review]
Looks much better to me.

**Comment by bartlomieju** [comment]
LGTM too, but I feel we should wait until we release 1.22.3 before merging this PR, otherwise, it's gonna be hard to sync `v1.22` branch with this change.

**Comment by bartlomieju** [comment]
@mrkldshv please rebase, I still want to land it for v1.23

**Comment by mrkldshv** [comment]
@bartlomieju sure, I'll rebase and update tests

**Pull request merged**
