### PR TITLE
build: publish only "deno" crate on tags

### PR DESCRIPTION
**Pull request by bartlomieju**
This commit updates CI script to publish only "deno"
crate on tags.

Following crates are not automatically published anymore:
- deno_core
- deno_web
- deno_fetch
- deno_crypto

Before this commit creating a new release required to bump
version on all above crates even though in practice they
rarely change.

### CODE REVIEW

**Review by ry — APPROVED** [review]
LGTM

**Comment by lucacasonato** [comment]
I don't think this will work. `deno` crate requires the other crates (like `deno_core` crate). If we don't publish a new `deno_core` version, cargo will instead pull the old version (from the previous release), breaking the build. This is not an issue if between releases the crates have _no_ changes, but any change (even minor) will require us to manually bump and release the non `deno` crates. This is theoretically manageable, but seems pretty annoying.

**Comment by bartlomieju** [comment]
> I don't think this will work. `deno` crate requires the other crates (like `deno_core` crate). If we don't publish a new `deno_core` version, cargo will instead pull the old version (from the previous release), breaking the build. This is not an issue if between releases the crates have _no_ changes, but any change (even minor) will require us to manually bump and release the non `deno` crates. This is theoretically manageable, but seems pretty annoying.

@lucacasonato correct, but now the opposite is true, we're bumping version every week and some crates haven't seen a change for a few weeks.

**Comment by lucacasonato** [comment]
Still seems like its going to be very prone to us forgetting to bump one of the op crates, or core :upside_down_face:. I guess well see how it goes.

**Comment by hayd** [comment]
You could fetch the latest cargo version then git diff the directory against that tag (and publish if different).

**Pull request merged**
