### PR TITLE
WIP add homebrew file

### PR DESCRIPTION
**Pull request by ry**
Test in CI?

Use sccache?

cc @hayd

### CODE REVIEW

**Comment by hayd** [comment]
Re testing, I think it's easier to just make a pr to homebrew-core. I'm not sure how they've configured Jenkins, so previously I just waited to build.

I suspect no sccache, a slow build is ok. Once it's built by homebrew-core it's available as a "bottle" so users are just downloading a binary.

**Comment by ry** [comment]
@hayd Let's push forward on two fronts - can you update your PR with something like this script?

If we can figure out how to test this in Travis, I think it's better if we maintain a version since we have the domain knowledge about whats happening. Then we can periodically sync with them. (Then again, if they accept the PR and I never have to think about it again, that would be better... )

**Comment by hayd** [comment]
I pushed a version of this to the PR, and I think I've added you as a collaborator so hopefully you can push directly there now.

**Comment by ry** [comment]
trying a different approach with GN formula. closing.

**Pull request closed without merging**
