### PR TITLE
fix(ext/node): use primordials in `ext/node/polyfills/internal/buffer.mjs`

### PR DESCRIPTION
**Pull request by petamoriken**
Towards #24236

### CODE REVIEW

**Comment by bartlomieju** [comment]
We effectively vendor this file. I'm not sure if it's worth using primordials here. Feels like it's gonna make updates a lot harder. That said we only update it a couple times per year, so maybe it's not such a big deal?

**Comment by petamoriken** [comment]
IMHO, primordials are hard to introduce, but then updating the codes is not so hard.

**Comment by petamoriken** [comment]
Since Node.js also uses primordials, the diffs with the Deno impl may decrease and make it rather easy to update.
https://github.com/nodejs/node/blob/0301309493b2a4e80796517bdb46ec55202a4800/lib/buffer.js

**Comment by bartlomieju** [comment]
@petamoriken, sorry for a slow response. I was wrong, it's not this file that we vendor so this should be fine. Can you please rebase the PR?

**Review by bartlomieju — APPROVED** [review]
LGTM, thanks

**Pull request merged**
