### PR TITLE
refactor(core): remove opAsync

### PR DESCRIPTION
**Pull request by littledivy**

### CODE REVIEW

**Comment by aapoalas** [comment]
How was the "hitting" for the async functions done again? Did it rely on `new Function` usage?

**Comment by bartlomieju** [comment]
> How was the "jitting" for the async functions done again? Did it rely on `new Function` usage?

It's done in `01_core.js` in `initializeAsyncOps` and yes, it uses `new Function`, but that's problematic as described in https://github.com/denoland/deno/issues/16535 and Divy will rework it to do it from Rust side.

**Comment by bartlomieju** [comment]
@littledivy is anything blocking this PR?

**Comment by bartlomieju** [comment]
Please wait for https://github.com/denoland/deno/pull/17648 to land before merging this PR.

**Comment by aapoalas** [comment]
Fun rebase in store.

**Comment by littledivy** [comment]
Uno reverse by https://github.com/denoland/deno/pull/17899 

image

opAsync will stay.

**Pull request closed without merging**
