### PR TITLE
feature: inline and deferred statement resolution logging

### LINKED ISSUE #5142: Support inline & lazy log evaluation
_NB:  This is not a plug for our package._

Please support inline & deferred logging, similar to https://www.npmjs.com/package/@northscaler/bunyaner.  It's a small, single-file monkey-patch to bunyan that reduces lines of code & increases performance.

TL;DR
```
// inline logging
const o = log.info({ foo: 'bar' }) // logs & returns given argument
```

```
// lazy evaluation
log.debug(() => expensive()) // only calls expensive() if log level is debug or lower
```

It's particularly useful as shown at https://www.npmjs.com/package/@northscaler/bunyaner#use-aspects-for-tracing

### PR DESCRIPTION
**Pull request by cknight**
Closes #5142 

This PR adds three new capabilities to the logging framework.

**Inline logging** - data passed to logger is returned.  E.g.
```
const data = logger.debug('hello world');  // returns 'hello world'
```

**Deferred logging** - You can pass a function to the logger which resolves to the log message.  This function will only be called if the logger will log the message.  E.g.
```
logger.debug(() => expensiveLogMessageResolver(5, true));
```
and `expensiveLogMessageResolver` will  only be called if the logger can log debug statements.

**All types supported for log msg data** E.g.
```
const data1: string = logger.debug('abc');
const data2: number = logger.debug(123);
const data3: boolean = logger.debug(true);
const data4: { msg: string, value: number } = logger.debug({ msg: 'abc', value: 123 });
etc...
```

### CODE REVIEW

**Comment by matthewadams** [comment]
Is there a way to refactor this such that a caller could leverage the very common pattern of logging a string message along with a payload object, which would show up in the `LogRecord` under a new `payload` key and be returned?  This would allow for something like
```
const bar = "bar"
const foo = log.debug("here's my Foo", new Foo(bar))
// LogRecord.msg === "here's my Foo", LogRecord.payload === "{ bar: \"bar\" }"
```
I think this deserves a little more thought about what's returned, but leave the lazy evaluation of log messages in this PR.  WDYT?

**Comment by cknight** [comment]
> I'd prefer that the log level methods be changed from taking `string | () => string` to taking `object | () => object`. 

This is now addressed with the latest commits which change the signatures of each log method to accept all types, returning the passed in data with the exception of functions which return the resolved value of the function or undefined if the function isn't called.

> Is there a way to refactor this such that a caller could leverage the very common pattern of logging a string message along with a payload object, which would show up in the LogRecord under a new payload key and be returned?

This can be achieved using a custom log formatter.  E.g. 
```
await log.setup({
  handlers: {
    functionFmt: new log.handlers.ConsoleHandler("DEBUG", {
      formatter: logRecord => {
        return `${logRecord.level} msg=${logRecord.msg} payload=${JSON.stringify(logRecord.args[0]}`;
      }
    }),
  },
});
log.debug("here's my foo", new Foo(bar));
// logs, e.g., "DEBUG msg=here's my foo payload={\"bar\":\"bar\"}"
```

**Comment by matthewadams** [comment]
What is the return value of your example, `log.debug("here's my foo", new Foo(bar))`?  Is it the instance of `Foo`?  Here's what I intended:
```
const expected = new Foo(bar);
assertEquals(logger.debug("here's my foo", expected), expected);
```
I'm adding this to the `logger_test.ts` file in your branch and RTFMing on how to run the tests.

**Comment by cknight** [comment]
> What is the return value of your example, `log.debug("here's my foo", new Foo(bar))`? Is it the instance of `Foo`? Here's what I intended:
> 
> ```
> const expected = new Foo(bar);
> assertEquals(logger.debug("here's my foo", expected), expected);
> ```
> 
> I'm adding this to the `logger_test.ts` file in your branch and RTFMing on how to run the tests.

The API for this specific instance is this:
```
const result: {msg: string, args: unknown[]} = logger.debug("here's my foo", new Foo(bar));
```
with `args[0]` containing `new Foo(bar)`.  If you'd prefer less type gymnastics to get at `new Foo(bar)` you could always swap the parameter order.  E.g.
```
const result: {msg: Foo, args: unknown[]} = logger.debug(new Foo(bar), "here's my foo");
```
Any use of multiple parameters requires the use of a custom log formatter to log them, so how they are formatted is completely up to you.

**Comment by matthewadams** [comment]
Ok.  Can you add this to `test("All types map correctly to log strings and are returned as is"`?
```
  // msg & object
  class Foo { bar: string; constructor(bar: string) { this.bar = bar } }
  const foo = new Foo("snafu");
  const stringObject: {msg: string, args: unknown[]} = logger.debug("here's my foo", foo);
  assertEquals(stringObject.msg, "here's my foo");
  assertEquals(stringObject.args.length, 1);
  assertEquals(stringObject.args[0], foo);
  const objectString: {msg: Foo, args: unknown[]} = logger.debug(foo, "here's my foo");
  assertEquals(objectString.msg, foo);
  assertEquals(objectString.args.length, 1);
  assertEquals(objectString.args[0], "here's my foo");
```
I can also submit a PR to your branch if you want.  Let me know.  Thanks!

**Comment by cknight** [comment]
> Ok. Can you add this to `test("All types map correctly to log strings and are returned as is"`?

Will do.  I've one more commit to do anyway to improve the type safety a touch more.

**Comment by matthewadams** [comment]
At the risk of sounding greedy, `const objectString: {msg: Foo, args: unknown[]} = logger.debug(foo, "here's my foo")` still feels pretty verbose to get at `foo`.  Is there some way to change this such that I can write the following?
```
const foo = logger.debug(new Foo("snafu"), "here's my foo");
```
This really illustrates the inline logging use case the best.  IOW, if we changed the logging methods to the following form, it might be simpler and fit inline logging better:
```
  debug<T>(msg: T | (() => T)): T;
  debug<T>(
    msg: T | (() => T),
    ...args: unknown[]
  ): T | undefined {
    return this._log(LogLevels.DEBUG, msg, ...args);
  }
```
WDYT?

**Comment by cknight** [comment]
> At the risk of sounding greedy, `const objectString: {msg: Foo, args: unknown[]} = logger.debug(foo, "here's my foo")` still feels pretty verbose to get at `foo`. 

Getting at `foo` is pretty easy and not overly verbose:
```
 const foo: Foo = logger.debug(new Foo("snafu"), "here's my foo").msg;
```
However, thinking on this more, I'm not sure the extra complexity of returning the optional arguments is worth it.  I'm leaning towards returning just the msg argument, which aligns with your suggestion.  The resolution of optional arguments are never deferred and so could be captured prior to calling the log statement if required.  I'll work on this tonight.

**Comment by matthewadams** [comment]
Sweet.  I think that's a better solution.  Looking forward to `deno`!

**Comment by cknight** [comment]
@matthewadams that's my final commit pushed.  I haven't added the test cases you suggested, as after removing the return of the optional args what was left of your test cases was already covered by other tests.  Any additional comments or do you feel this is now ready for review?

**Comment by matthewadams** [comment]
@cknight fyi https://github.com/cknight/deno/pull/1

**Comment by matthewadams** [comment]
I'll save the documentation of how to log as JSON with inline logging for another PR just to get this out

**Comment by cknight** [comment]
thanks for all the feedback @matthewadams. I'd already updated the README.md, but I liked some of your content better, so made a few further documentation changes based on this.  Once the CI passes, this PR is ready for review.

**Comment by matthewadams** [comment]
@cknight great -- glad we could add this so quickly.

Unrelated, ask @ry to forward you my email message to him regarding other potential additions based on [our company's other npm libraries](https://www.npmjs.com/search?q=%40northscaler).  I didn't have your email address :/  Email me at matthew at matthewadams dot me if you want me to send it to you directly.

**Comment by cknight** [comment]
@ry @bartlomieju any feedback on this PR?  It was marked for milestone 0.53.0, but it looks like we've passed that now.  Thanks!

**Pull request merged**
