### PR TITLE
fix: update worker types to better align to lib.dom.d.ts

### LINKED ISSUE #7839: worker scope onmessage/MessageEvent bad typings
`self.onmessage = async (msg: MessageEvent) => {}` wont work because 
```
error: Uncaught Error: TS2322 [ERROR]: Type '(msg: MessageEvent) => Promise<void>' is not assignable to type '((e: MessageEvent) => void) & ((e: { data: any; }) => void | Promise<void>)'.
  Type '(msg: MessageEvent) => Promise<void>' is not assignable to type '(e: { data: any; }) => void | Promise<void>'.
    Types of parameters 'msg' and 'e' are incompatible.
      Type '{ data: any; }' is missing the following properties from type 'MessageEvent': origin, lastEventId, bubbles, cancelBubble, and 17 more.
```

and `self.onmessage = async (msg) => {}` wont work because `Parameter 'msg' implicitly has an 'any' type.`
It seems to be happening since 1.4.3.

from the `((e: { data: any; }) => void | Promise<void>)` i can see that `MessageEvent.data` was wanted to be of type `any`, but  from the typescript typings `MessageEvent` should actually take a type param that defines the type of `MessageEvent.data`

### PR DESCRIPTION
**Pull request by kitsonk**
Fixes #7839

### CODE REVIEW

**Comment by ry** [comment]
@crowlKats does this work for you?

**Comment by crowlKats** [comment]
Yep, LGTM

**Review by crypt096 — APPROVED** [review]

**Review by ry — COMMENTED** [review]
It would be great to have a simple unit test for this.

**Review by bartlomieju — APPROVED** [review]
LGTM, thanks @kitsonk

**Pull request merged**
