### PR TITLE
BREAKING(std/datetime): fix typo miliseconds -> milliseconds

### PR DESCRIPTION
**Pull request by mshrtsr**
## Summary

This PR fixes typo in time unit (miliseconds -> milliseconds)
The original issue is #7460 by @tgfrerer 

All existing tests in `cargo test` passed.

### type
 - [std/datetime] Unit
 - [std/datetime] DifferenceFormat
 - [std/datetime] DifferenceOptions
### function
 - [std/datetime] difference

## Impacted test
 - [std/datetime] difference ( `std/datetime/test.ts` )

### CODE REVIEW

**Comment by caspervonb** [comment]
Tag this as `BREAKING(std/datetime)` please 👍

**Comment by mshrtsr** [comment]
@caspervonb 
I found additional `mili-second` typo in [`std/encoding/_yaml/type/timestamp.ts#L73`](https://github.com/denoland/deno/blob/530f48d2fda74c2329fd293c516a583e316024cb/std/encoding/_yaml/type/timestamp.ts#L73).
Which would be better, fix in this PR or another PR?

**Comment by lucacasonato** [comment]
Fix it in this PR.

**Review by ry — APPROVED** [review]
Yikes. Thanks.

**Pull request merged**
