### PR TITLE
feat(ext/net): add `SOA` DNS record support

### PR DESCRIPTION
**Pull request by PatrickChoDev**
`SOA` is another DNS record type which should include after my last PR for `NS` record, mentioned in #14355.

### CODE REVIEW

**Review by bartlomieju — COMMENTED** [review]
Looks good, please add a test case to `test_resolve_dns` integration test

**Comment by PatrickChoDev** [comment]
`SOA` records still can't test with no clue. I've made a separated `Trust DNS server` and test with `dig` Linux command, the `SOA` returned but not with this test suites. Am I missing something?

**Comment by PatrickChoDev** [comment]
If this pull request was merged. I'd like to change the `test_resolve_dns` integration test structure to load DNS zone from a file Which make it more comfy for new record types and **multiple** same DNS record type like `A`,`NS`, etc.

I have to figure SOA record out for a while because a bit problems with zone file until I use parser as 6fa732e37e7b90bab2d80dd4895970a9c337c715 .

**Comment by lucacasonato** [comment]
Yeah, that sounds good.

**Comment by PatrickChoDev** [comment]
@lucacasonato @bartlomieju I have no idea about `rustc` in CI was panicked. Could you help me, please?

**Comment by PatrickChoDev** [comment]
I don't know these CI error happen so I will recreate this PR later. :disappointed:

**Comment by bartlomieju** [comment]
@PatrickChoDev it looks like `Cargo.lock` got out of date - you can update it locally if you checkout it from `main` branch and run `cargo check` locally again. Alternatively I can do that for you

**Comment by PatrickChoDev** [comment]
> @PatrickChoDev it looks like `Cargo.lock` got out of date - you can update it locally if you checkout it from `main` branch and run `cargo check` locally again. Alternatively I can do that for you

I think I should remake this by checkout from up-to-date `main` maybe I'll push this new PR next hour.

**Pull request closed without merging**
