### PR TITLE
Failing test for Atomics.waitAsync bug #14786

### PR DESCRIPTION
**Pull request by Eyal-Shalev**
PR for adding a failing test for the #14786 bug report.

### CODE REVIEW

**Comment by bartlomieju** [comment]
@andreubotella it feels like we should have a custom `TaskRunner` implementation that could wake up event loop to handle this case, do you have any knowledge about inner working of the runners in V8?

**Comment by andreubotella** [comment]
> @andreubotella it feels like we should have a custom `TaskRunner` implementation that could wake up event loop to handle this case, do you have any knowledge about inner working of the runners in V8?

I don't know too much about the V8 platform abstraction, but it seems like `TaskRunner::PostTask` could be implemented by simply calling `tokio::spawn`, and similarly with `TaskRunner::PostDelayedTask`. I'm not sure about the details of task nesting and idle tasks, but you can opt out of that by having the corresponding `Enabled` methods return false.

But it seems like in order to use a `TaskRunner`, you'd need a `Platform` implementation, and that might be more complicated to implement right. Although things like `Platform::CallOnWorkerThread` might map easily to `tokio::task::spawn_blocking`.

**Comment by bartlomieju** [comment]
> > @andreubotella it feels like we should have a custom `TaskRunner` implementation that could wake up event loop to handle this case, do you have any knowledge about inner working of the runners in V8?
> 
> I don't know too much about the V8 platform abstraction, but it seems like `TaskRunner::PostTask` could be implemented by simply calling `tokio::spawn`, and similarly with `TaskRunner::PostDelayedTask`. I'm not sure about the details of task nesting and idle tasks, but you can opt out of that by having the corresponding `Enabled` methods return false.
> 
> But it seems like in order to use a `TaskRunner`, you'd need a `Platform` implementation, and that might be more complicated to implement right. Although things like `Platform::CallOnWorkerThread` might map easily to `tokio::task::spawn_blocking`.

Thanks for the insight, it's something we should definitely explore, though I feel like it's not a very high priority at the moment.

**Comment by bartlomieju** [comment]
Thanks for the PR, but I'm gonna close it without a merge. All the `core/` code in now in denoland/deno_core repo and we're gonna have to fix this bug there. And that should happen this quarter since it's blocking some other work.

**Comment by Eyal-Shalev** [comment]
> Thanks for the PR, but I'm gonna close it without a merge. All the `core/` code in now in denoland/deno_core repo and we're gonna have to fix this bug there. And that should happen this quarter since it's blocking some other work.

Can you link to the new issue once it is created?

**Pull request closed without merging**
