### PR TITLE
feat(runtime/permissions): add `$PATH` resolution to run permission

### PR DESCRIPTION
**Pull request by crowlKats**
A usecase for this is when using `Deno.execPath()` but passing `--allow-run=deno`. I very well see that there is no need for this as one can just do `--allow-run=$(which deno)`, so it is just a "nice little thing" and I dont mind this not being merged

### CODE REVIEW

**Comment by caspervonb** [comment]
Personally, not really based on anything but gut-feeling I don't like the implicitness of this as my assumption is that --allow-`run=foo` would be the same as `--allow-run=./foo` (point of reference I suppose is that`chmod +x foo` doesn't chmod in $PATH, because that would be weird).

**Comment by bartlomieju** [comment]
I'm also not a fan of this PR, it will change the semantics of the `--allow-run` flag and could be thought of as a breaking change. Is there a bug that this PR fixes?

**Comment by crowlKats** [comment]
@bartlomieju nope, it was really just a spur of the moment idea, but since i am also not a real fan of it either, might as well just close it

**Comment by bartlomieju** [comment]
Let's close it then and revisit if there's a need for it.

**Pull request closed without merging**
