### PR TITLE
Rename ansi2colors

### PR DESCRIPTION
**Pull request by 7k8m**
`````
diff --git a/cli/ansi.rs b/cli/colors.rs
--- a/cli/ansi.rs
+++ b/cli/colors.rs
@@ -1,5 +1,4 @@
 // Copyright 2018-2019 the Deno authors. All rights reserved. MIT license.
-// TODO(ry) Rename this file to colors.rs
 // TODO(ry) Replace ansi_term with termcolor.
 use ansi_term::Color::Black;
 use ansi_term::Color::Fixed;
`````

### CODE REVIEW

**Comment by 7k8m** [comment]
Weird. Local execution of ./tools/unit_tests.py was OK.

```````
[tomohito.nakayama@shorthair deno (rename_ansi2colors)]$ ./tools/unit_tests.py  > unit_test.py.result
unit_test_runner (__main__.JsUnitTests) ... ok

----------------------------------------------------------------------
Ran 1 test in 17.954s

OK
```````
[unit_test.py.result.zip](https://github.com/denoland/deno/files/3613819/unit_test.py.result.zip)

**Comment by bartlomieju** [comment]
@7k8m just rerun CI, it sometimes fails randomly on Windows...

**Comment by 7k8m** [comment]
> @7k8m just rerun CI, it sometimes fails randomly on Windows...

Let me know how to rerun. 🙏

**Comment by bartlomieju** [comment]
```
git commit --allow-empty -m "reset CI"
git push
```

**Pull request merged**
