### PR TITLE
fix(cli/js/error_stack): Expose Error.captureStackTrace

### LINKED ISSUE #5127: Regression in exception stack handling
Hi there,

I'm trying to restore Unexpected support for deno 1.0. The most immediate issue is what looks like a regression in exception handling to do with stack traces - if you run execute `make test-deno` in the Unexpected branch `deno-v1-support` (https://github.com/unexpectedjs/unexpected/tree/deno-v1-support) it quickly dies with:

```
error: Uncaught TypeError: Cannot redefine property: __callSiteEvals
    at Function.defineProperties (<anonymous>)
    at Function.prepareStackTrace ($deno$/error_stack.ts:221:10)
    at Function.getOwnPropertyDescriptor (<anonymous>)
    at Object.propertyIsWritable (file:///some/path/unexpected/unexpected.esm.js:105:17361)
    at Gt (file:///some/path/unexpected/unexpected.esm.js:105:19389)
    at Object.Xt [as ensureErrorObject] (file:///some/path/unexpected/unexpected.esm.js:105:19465)
    at w._rejectCallback (file:///some/path/unexpected/unexpected.esm.js:105:64548)
    at w._settlePromiseFromHandler (file:///some/path/unexpected/unexpected.esm.js:105:65199)
    at w._settlePromiseAt (file:///some/path/unexpected/unexpected.esm.js:105:66370)
    at w._settlePromises (file:///some/path/unexpected/unexpected.esm.js:105:68217)
    at le._drainQueue (file:///some/path/unexpected/unexpected.esm.js:105:25498)
    at le._drainQueues (file:///some/path/unexpected/unexpected.esm.js:105:25560)
    at drainQueues (file:///some/path/unexpected/unexpected.esm.js:105:23830)
    at file:///some/path/unexpected/unexpected.esm.js:105:86829
    at Array.forEach (<anonymous>)
    at Object.drain (file:///some/path/unexpected/unexpected.esm.js:105:86808)
```

If there's anything else I can provide please let me know.

Thanks, Alex J Burke.

### LINKED ISSUE #5251: Async Stack Trace Capturing For Typescript Users
It would be really helpful to be able to use this as being able to preserve stack traces helps provide much better errors to end-users of a library.

image

image

### PR DESCRIPTION
**Pull request by nayeemrmn**
Fixes #5127.
Closes #5251.
Ref https://v8.dev/docs/stack-trace-api#stack-trace-collection-for-custom-exceptions.

### CODE REVIEW

**Comment by kevinkassimo** [comment]
Not super sure if we should expose it as part of the type? Since it is technically a non-standard v8 only feature

**Comment by nayeemrmn** [comment]
Maybe... but nothing in https://v8.dev/docs/stack-trace-api suggests that this is for internal runtime use only -- in fact it makes lots of references to "user scripts". Unless Deno has a special reason to override this we should just let it pass through IMO.

Couple this with the fact that users *do* seem to be using this API, and that it will continue to exist in JS, not supporting it in TS just seems like a stumbling block.

**Comment by kitsonk** [comment]
I agree with @nayeemrmn.  Deno is tightly coupled to V8, that means non-spec APIs supported by V8 are candidates for inclusion in Deno type definitions.

For reference, `@types/node` includes them: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/db4d8c51d2028805bfe722c83986f1693d27b9c2/types/node/v10/globals.d.ts#L131-L143.

**Comment by bartlomieju** [comment]
@nayeemrmn please merge with `master` - I'll land this PR for 1.0.3

**Pull request merged**
