### PR TITLE
set minimum timeout to be 4 milliseconds

### PR DESCRIPTION
**Pull request by ry**

### CODE REVIEW

**Comment by lucacasonato** [comment]
Per spec this is actually a little more complicated than this. The minimum timeout depends on the nesting level of the timeout. The actual spec wording is "If nesting level is greater than 5, and timeout is less than 4, then set timeout to 4.". Nesting level increases by 1 every time you call setTimeout or a new timer task is created for setInterval if the parent task of is also a timer task. The nesting level is reset back to 0 if the parent task is not a timer task.

I don't see an easy way to implement this at the moment though, so I'd say good enough for now. We should open an issue to track changing this behaviour to what the spec intends.

**Comment by ry** [comment]
created https://github.com/denoland/deno/issues/10974 and added a TODO comment

**Review by lucacasonato — APPROVED** [review]
LGTM once test passes.

**Comment by piscisaureus** [comment]
> I don't see an easy way to implement this at the moment though, so I'd say good enough for now.

I think this is good enough forever.

**Comment by lucacasonato** [comment]
> > I don't see an easy way to implement this at the moment though, so I'd say good enough for now.
> 
> I think this is good enough forever.

I don't think so - a single `setTimeout(() => {}, 0)` is a common way to schedule a piece of code after the microtask queue has cleared. Delaying for 4ms there is not great.

**Review by piscisaureus — APPROVED** [review]

**Pull request merged**
