### PR TITLE
fix(cli): Make --watcher CLEAR_SCREEN clear scrollback buffer as well as visible screen

### PR DESCRIPTION
**Pull request by chrisveness**
The --watch option should clear the screen scrollback buffer as well as the screen itself.

On Ubuntu (22.04 Jammy) the 'clear' command generates "\x1B[H\x1B[2J\x1B[3J"; that is:
- \E[H  - cursor home
- \E[2J - clear entire screen
- \E[3J - clear entire screen & scrollback buffer.

By contrast, Deno defined CLEAR_SCREEN as "\x1B[2J\x1B[1;1H", which fails to clear the scrollback buffer.

The "\E[H\E[2J\E[3J" sequence works on MacOS (Sonoma) (using printf); I'm not able to test on Windows.

Closes https://github.com/denoland/deno/issues/26514

### CODE REVIEW

**Comment by bartlomieju** [comment]
Thanks for the PR, could you give some context on why you think it's a desirable change? This functionality was modelled based on what other frameworks are doing (like `vitest`).

**Comment by chrisveness** [comment]
@bartlomieju, the Node.js file watcher for file changes (`node --watch`) clears the scrollback buffer as well as the visible part of the screen.

If I have a lot of logged output, when the watch option restarts the process, with Node.js I can scroll back to the top of the screen to see the start of the current process. With the current Deno watcher (`deno --watch`), the start of the process will be buried somewhere in the middle of the scrollback buffer.

I note there has  been discussion about test behaviour previously, but I believe this is unrelated to, and I assume would not affect, considerations around testing.

**Comment by chrisveness** [comment]
@bartlomieju did that explanation make sense? Do you want any further information?

**Comment by chrisveness** [comment]
@bartlomieju The Node.js File Watcher apparently uses "\x1Bc" (ESC c – [Reset to Initial State (RIS)](https://vt100.net/docs/vt510-rm/RIS.html)) to clear the screen on file change:
- [main/watch_mode.js#L117](https://github.com/nodejs/node/blob/231d5e4437163a2b99e87793d2766bf1ae283f38/lib/internal/main/watch_mode.js#L117)
- [main/watch_mode.js#L22](https://github.com/nodejs/node/blob/231d5e4437163a2b99e87793d2766bf1ae283f38/lib/internal/main/watch_mode.js#L22)
- [util/colors.js#L35](https://github.com/nodejs/node/blob/231d5e4437163a2b99e87793d2766bf1ae283f38/lib/internal/util/colors.js#L35)

I don't know if this might be preferable to "\x1B[H\x1B[2J\x1B[3J" – either way would appear to work well.

As I mentioned, this PR is unrelated to testing; Node.js is the obvious comparison (I don't know what bun does).

**Comment by bartlomieju** [comment]
Maybe fixes https://github.com/denoland/deno/issues/26514?

**Review by bartlomieju — APPROVED** [review]
I can't see a difference on mac and iTerm; I guess the biggest change is the scroll back history clearing. I don't have a strong opinion if this is desired or not, so let's land it. Thanks for the PR

**Comment by bartlomieju** [comment]
Okay I can see change in VSCode terminal. This should actually fix https://github.com/denoland/deno/issues/26514.

**Pull request merged**
