### PR TITLE
Update GitHub Actions, powershell is default on windows

### PR DESCRIPTION
**Pull request by khs1994**
* https://github.blog/changelog/2019-10-17-github-actions-default-shell-on-windows-runners-is-changing-to-powershell/

### CODE REVIEW

**Comment by khs1994** [comment]
should we use `$(pwd)` or `$(Get-Location)`? `pwd` is alias `Get-Location`

**Comment by ry** [comment]
@khs1994 Thanks for the fix! pwd is more understandable.

**Comment by ry** [comment]
We're still getting a failure on the deno_std test

```
cd std
  "../target/release/deno" test -A
  shell: C:\Program Files\PowerShell\6\pwsh.EXE -command ". '{0}'"
  env:
    pythonLocation: C:\hostedtoolcache\windows\Python\2.7.16\x64
At D:\a\_temp\93750590-11c7-4d46-997b-1a02dd9fdc39.ps1:3 char:26
+ "../target/release/deno" test -A
+                          ~~
Unexpected token 'test' in expression or statement.
+ CategoryInfo          : ParserError: (:) [], ParseException
+ FullyQualifiedErrorId : UnexpectedToken
```

trying to randomly fix it.. but if you know how to do this better, @khs1994, then please advise.

**Comment by ry** [comment]
I guess that worked.

LGTM - thanks again @khs1994 !

**Pull request merged**
