### PR TITLE
experiment: wgpu sync

### PR DESCRIPTION
**Pull request by AaronO**
An experiment to streamline keeping our `ext/webgpu` in sync with upstream `gfx-rs/wgpu`

## TODO

- [x] ~~`gfx-rs/wgpu` doesn't have `lib.deno_webgpu.d.ts` or `deno_webgpu::get_declaration()` https://github.com/gfx-rs/wgpu/pull/2402~~
- [x] Maintain the TS bindings ourselves outside of wgpu's `deno_webgpu` tree
- [x] ~~Sync `indexmap` versions (we use `1.7.0`, https://github.com/gfx-rs/naga uses `1.6.0` if using wgpu tip)~~
- [x] Bump `naga` dep in `wgpu-core` to resolve `indexmap` mismatch https://github.com/gfx-rs/wgpu/pull/2401
- [x] https://github.com/gfx-rs/wgpu/pull/2405
- [x] https://github.com/gfx-rs/wgpu/pull/2403

### CODE REVIEW

**Review by bartlomieju — COMMENTED** [review]
A README on how to upgrade these crates would be useful

**Comment by AaronO** [comment]
> A README on how to upgrade these crates would be useful

Simply:
1. Change `COMMIT` in `./tools/wgpu_sync.js`
2. Run `./tools/wgpu_sync.js`
3. Double check changes, possibly patch

**Comment by bartlomieju** [comment]
> > A README on how to upgrade these crates would be useful
> 
> Simply:
> 
> 1. Change `COMMIT` in `./tools/wgpu_sync.js`
> 2. Run `./tools/wgpu_sync.js`
> 3. Double check changes, possibly patch

Great, but if there's no README then it will be lost.

**Review by crowlKats — APPROVED** [review]
LGTM, just that README is missing

**Pull request merged**
