### PR TITLE
docs: refer to `globalThis` instead of `window` in declaration files

### PR DESCRIPTION
**Pull request by iuioiua**

### CODE REVIEW

**Review by dsherret — APPROVED** [review]
LGTM

**Review by bartlomieju — COMMENTED** [review]
Hmmm, @dsherret how do we ensure that these are not changed back when we upgrade TS next time?

**Comment by dsherret** [comment]
Oh yeah, I forgot these were generated. We should probably open a pr in typescript to change it.

**Comment by bartlomieju** [comment]
@iuioiua could you open a PR to TypeScript with these changes?

**Pull request merged**
