### PR TITLE
Remove http_client from CliState, lazily load it

### PR DESCRIPTION
**Pull request by ry**
Towards fetch op crate

### CODE REVIEW

**Review by bartlomieju — APPROVED** [review]
LGTM, although I'd prefer not to lazily load it, but create it during `Worker::new`

**Comment by ry** [comment]
> LGTM, although I'd prefer not to lazily load it, but create it during Worker::new

Why?

**Comment by bartlomieju** [comment]
> > LGTM, although I'd prefer not to lazily load it, but create it during Worker::new
> 
> Why?

It's just easier to grok than having lazy initialization.

**Comment by lucacasonato** [comment]
> Why?

I would additionally say that if the cli is fully responsible for initializing the client, the fetch op doesn't require access to `flags.ca_cert`.

**Pull request merged**
