### PR TITLE
test(cli): enable web platform timer tests

### PR DESCRIPTION
**Pull request by caspervonb**
Part of #9001

### CODE REVIEW

**Comment by caspervonb** [comment]
Unfortunately most of the interesting tests are in html documents.

**Comment by lucacasonato** [comment]
> Unfortunately most of the interesting tests are in html documents, so without attempting to parse them out into bundles (would have to be opt-in of course) this is the best we can get.

Can you try upstream this?

**Comment by caspervonb** [comment]
> > Unfortunately most of the interesting tests are in html documents, so without attempting to parse them out into bundles (would have to be opt-in of course) this is the best we can get.
> 
> Can you try upstream this?

Yup

**Review by lucacasonato — APPROVED** [review]
Thanks

**Pull request merged**
