### PR TITLE
Use cargo_gn to build using "cargo build"

### PR DESCRIPTION
**Pull request by piscisaureus**
Work in progress.
Rebased version of #2675 with fixes.

### CODE REVIEW

**Comment by piscisaureus** [comment]
cc @ry

**Comment by ry** [comment]
Is this working for you now?

**Comment by piscisaureus** [comment]
> Is this working for you now?

Yes if I manually work around the 2 issues in cargo_gn.

**Comment by piscisaureus** [comment]
So here's one rustc issue blocking us from switching to cargo: https://github.com/rust-lang/rust/issues/39016

**Pull request closed without merging**
