### PR TITLE
upgrade: deno_doc, deno_lint, dprint, swc

### PR DESCRIPTION
**Pull request by bartlomieju**

### CODE REVIEW

**Comment by bartlomieju** [comment]
@kdy1 @kitsonk PTAL, lots of different output from the bundler, I think that's expected, but want to double check.

**Comment by kdy1** [comment]
It seems like deno is not using inliner. The bundler switched from slow inliner to very fast **constant** propagation pass.

Note that the bundler now creates lots of more variables to make flattening easier.

(Previous approach was a result of misunderstanding about the nature of flattening.)

**Comment by kdy1** [comment]
The output seems correct.. (I forgot saying it)

**Comment by bartlomieju** [comment]
> It seems like deno is not using inliner. The bundler switched from slow inliner to very fast constant propagation pass. 
> 
Should we be using it? Could you point me to relevant API @kdy1?

**Comment by kdy1** [comment]
@bartlomieju 

It's not must, and I don't think it matters for users who will run the bundle via deno.
But some users want smaller bundle, so it may help.

Anyway, it's enabled by default and https://docs.rs/swc_bundler/0.17.1/swc_bundler/struct.Config.html#structfield.disable_inliner will help.

**Review by kitsonk — APPROVED** [review]
LGTM

**Pull request merged**
