### PR TITLE
chore: fix typos

### PR DESCRIPTION
**Pull request by not-my-profile**
The typos were found with the typos[1] spell checker.  That spell checker will be incorporated into the CI in a followup PR.

[1]: https://github.com/crate-ci/typos

### CODE REVIEW

**Comment by 0f-0b** [comment]
Can these fixes be included as well?

```text
`apliland` should probably be `apiland`
  tools/release/release_doc_template.md:191:18

`asynchornously` should be `asynchronously`
  cli/tests/unit/fs_events_test.ts:54:8

`cients` should be `clients`
  test_util/src/lib.rs:1375:65
  test_util/src/lib.rs:1420:65
  test_util/src/lib.rs:1466:65
  test_util/src/lib.rs:1530:65

`colide` should be `collide`
  cli/tests/integration/run_tests.rs:2469:35

`comapt` should be `compat`
  tools/node_compat/README.md:12:17
  tools/node_compat/README.md:44:42
  tools/node_compat/setup.ts:118:14

`completor` should be `completer` or perhaps `completion`
  cli/lsp/registries.rs:77:6
  cli/lsp/registries.rs:88:8
  cli/lsp/registries.rs:92:13
  cli/lsp/registries.rs:99:23
  cli/lsp/registries.rs:106:25
  cli/lsp/registries.rs:123:25
  cli/lsp/registries.rs:133:25
  cli/lsp/registries.rs:691:21
  cli/lsp/registries.rs:692:23
  cli/lsp/registries.rs:693:23
  cli/lsp/registries.rs:694:24
  cli/lsp/registries.rs:701:24

`constrol` should be `control`
  Releases.md:1449:17

`converage` should be `coverage`
  core/inspector.rs:75:25

`Datarror` should be `DataError`
  ext/crypto/00_crypto.js:2669:55

`defintion` should be `definition`
  cli/tsc/99_main_compiler.js:375:31

`emitable` should be `emittable`
  Releases.md:1245:42

`emoiji` should be `emoji`
  cli/tests/integration/lsp_tests.rs:1328:33

`examininig` should be `examining`
  cli/tools/repl/editor.rs:291:75

`finialize` should be `finalize`
  cli/napi/threadsafe_functions.rs:139:10
  cli/napi/threadsafe_functions.rs:171:28

`fixutre` should be `fixture`
  cli/tests/unit/text_encoding_test.ts:253:9
  cli/tests/unit/text_encoding_test.ts:256:14
  cli/tests/unit/text_encoding_test.ts:263:25

`formater` should be `formatter`
  Releases.md:2012:20

`gnored` should be `ignored`
  ext/console/01_console.js:1405:33

`inheritences` should be `inheritances`
  cli/tests/unit_node/worker_threads_test.ts:147:27

`itereate` should be `iterate`
  cli/tsc/dts/lib.deno.ns.d.ts:1436:10
  cli/tsc/dts/lib.deno.ns.d.ts:1470:10

`maybed` should be `maybe`
  cli/emit.rs:67:10
  cli/tools/coverage/mod.rs:706:23

`monomorpize` should be `monomorphize`
  Releases.md:69:45

`normalizd` should be `normalized`
  cli/tsc/99_main_compiler.js:781:39

`numer` should be `number`
  cli/tsc/dts/lib.deno.unstable.d.ts:824:26

`offst` should be `offset`
  cli/tests/unit_node/internal/_randomFill_test.ts:64:49

`primtives` and `promitives` should be `primitives`
  ext/io/Cargo.toml:11:19
  serde_v8/serializable.rs:32:35

`promordials` should be `primordials`
  Releases.md:612:54

`prvode` should be `provide`
  Releases.md:4260:9

`removesequently` should be `consequently`
  core/async_cell.rs:393:47

`rumtime` should be `runtime`
  Releases.md:434:7

`slotable` should be `slottable` (spec change: whatwg/dom#845)
  ext/web/02_event.js:519:12
  ext/web/02_event.js:589:9
  ext/web/02_event.js:589:22
  ext/web/02_event.js:597:11
  ext/web/02_event.js:598:9

`stabalized` should be `stabilized`
  ops/deno.rs:25:41

`stderrr` should be `stderr`
  test_util/src/builders.rs:650:17

`testsdata` should be `testdata`
  test_util/src/lib.rs:554:29

`unafected` should be `unaffected`
  core/Cargo.toml:27:39

`unfortuntely` should be `unfortunately`
  ext/web/timers.rs:94:56

`vesionstamp` should be `versionstamp`
  ext/kv/sqlite.rs:719:17
  ext/kv/sqlite.rs:724:31

`Webassemby` should be `WebAssembly`
  core/runtime/tests.rs:367:30

`workfaround` should be `workaround`
  cli/tools/fmt.rs:446:18

`wrorker` should be `worker`
  test_ffi/tests/thread_safe_test.js:72:66
```

**Comment by not-my-profile** [comment]
Sure ... ah nice, which spell checker did you use to find these?

**Comment by 0f-0b** [comment]
I… did not use a spell checker. I wrote a Deno script to extract from the codebase everything that looks like a word and compare them against a dictionary. False positives were removed by hand.

**Comment by not-my-profile** [comment]
Ok I think I got those covered now as well. I have split off the "slotable" typo fix into its own PR #19584, so that the reference to the whatwg PR can be properly preserved.

**Review by ry — APPROVED** [review]
LGTM - thank you!

**Pull request merged**
