### PR TITLE
chore(bench_util): fix syntax error in README.md

### PR DESCRIPTION
**Pull request by zhanghengxin**
fix:Updating grammar errors in readme.md

fix https://github.com/denoland/deno/issues/21491

### CODE REVIEW

**Comment by zhanghengxin** [comment]
@dsherret 

The signing has been completed as requested.

**Comment by zhanghengxin** [comment]
@dsherret 
What are the other things I need to do?

**Comment by zhanghengxin** [comment]
> @zhanghengxin I think just run `./tools/format.js` and it should be good to go. That code block has started being formatted by the formatter now that it doesn't contain a syntax error.我认为只要跑一跑 `./tools/format.js` ，它应该很好。该代码块已开始由格式化程序格式化，因为它不包含语法错误。

Because it is code in Markdown, nobody corrected it for two years.

**Comment by zhanghengxin** [comment]
sorry , I misunderstood the meaning.I got to do!

**Comment by zhanghengxin** [comment]
image
image


Nothing changed after the formatting was performed

**Review by kt3k — APPROVED** [review]
LGTM

**Pull request merged**
