### PR TITLE
feat(unstable/npm): support providing npm dist-tag in npm package specifier

### LINKED ISSUE #15753: Tagged versions in npm specifiers cause a panic
Attempting to run an npm package with a tagged version causes Deno to panic:

```
❯ RUST_BACKTRACE=1 deno run --unstable npm:rome@next

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.25.1
Args: ["deno", "run", "--unstable", "npm:rome@next"]

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Invalid version requirement.

Caused by:
    0: Invalid npm specifier version requirement 'next'.
    1: Unexpected character.
         next
         ~', cli/graph_util.rs:86:59
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/result.rs:1805:5
   3: deno::graph_util::GraphData::add_graph
   4: deno::proc_state::ProcState::prepare_module_load::{{closure}}
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  11: deno::run_command::{{closure}}
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  13: deno::main::{{closure}}
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  15: deno_runtime::tokio_util::run_local
  16: deno::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Tagged versions should probably be supported, but at the very least they should gracefully fail instead of panicking.

### PR DESCRIPTION
**Pull request by dsherret**
```ts
import ts from "npm:typescript@next";

console.log(ts.version); // 4.9.0-dev.20221015
```

Note: this does not fix dist-tags specified in dependencies

Closes #15753

### CODE REVIEW

**Review by bartlomieju — APPROVED** [review]
Tried locally, works like a charm. LGTM!

**Comment by KnorpelSenf** [comment]
> Note: this does not fix dist-tags specified in dependencies

Should we then open an issue to track this?

**Comment by bartlomieju** [comment]
@KnorpelSenf yes, that would be very helpful; thank you

**Comment by dsherret** [comment]
@KnorpelSenf it's here https://github.com/denoland/deno/issues/16321

**Pull request merged**
