### PR TITLE
feat(coverage): add breadcrumbs to deno coverage --html docs

### PR DESCRIPTION
**Pull request by lczerniawski**
This PR introduces breadcrumb navigation to the `deno coverage --html` documentation as suggested in #23670 
image

### CODE REVIEW

**Comment by kt3k** [comment]
Thank you for doing this!

Because we like to minimize the styling effort, we want to align the document structure as close to Istanbul output as possible.

Istanbul renders the breadcrumbs inside the `<h1>` tag. Could you move the breadcrumbs inside it (without adding any special css classes. They seem like just `<a>` tags and texts)

Another minor suggestions:
- Let's use `All files` instead of `Home`
- Maybe let's not use `<a>` for the last part of the breadcrumbs as it points to its document itself.

The below is a screenshot of Istanbul output:

Screenshot 2024-08-08 at 17 41 38

**Comment by lczerniawski** [comment]
> Thank you for doing this!
> 
> Because we like to minimize the styling effort, we want to align the document structure as close to Istanbul output as possible.
> 
> Istanbul renders the breadcrumbs inside the `<h1>` tag. Could you move the breadcrumbs inside it (without adding any special css classes. They seem like just `<a>` tags and texts)
> 
> Another minor suggestions:
> 
> * Let's use `All files` instead of `Home`
> * Maybe let's not use `<a>` for the last part of the breadcrumbs as it points to its document itself.
> 
> The below is a screenshot of Istanbul output:
> 
> Screenshot 2024-08-08 at 17 41 38

Thanks for the comment, on begging, I thought about adding it to the title but didn't want to mess with existing staff.
Done it, I removed custom CSS and rewrote it as you suggested.
image

**Comment by bartlomieju** [comment]
@kt3k do you think we can land this one now?

**Review by kt3k — APPROVED** [review]
Sorry for the delay (I was sick a few days).

This looks very good! Thank you for your contribution!

**Comment by marvinhagemeister** [comment]
I'm late to the party, just wanted to say that this is a great UX improvement!

**Pull request merged**
