### PR TITLE
feat: add Deno.TestDefinition.concurrent option

### PR DESCRIPTION
**Pull request by caspervonb**
This adds a concurrent option to Deno.TestDefinition which when enabled is used to partition the test into compatible grouping which it may run in concurrently with.

When a test is running concurrently the sanitizers and permissions are applied to the entire concurrency group as an execution unit.

Sequential tests are run before concurrent tests in their natural order.

Prior art: 
- https://jestjs.io/docs/api#testconcurrentname-fn-timeout
- https://github.com/avajs/ava/blob/main/docs/01-writing-tests.md#running-tests-serially (inverted)

Closes https://github.com/denoland/deno/issues/11409

### CODE REVIEW

**Comment by caspervonb** [comment]
Logical follow up to this would be to create a single stream unbuffered stream of concurrent jobs from all the workers.

**Comment by caspervonb** [comment]
cc @bartlomieju

**Comment by bartlomieju** [comment]
> cc @bartlomieju

@caspervonb I believe we should wait on https://github.com/denoland/deno/issues/11901 before we land this PR. I'm afraid they might clash in fundamental way.

**Comment by caspervonb** [comment]
> > cc @bartlomieju
> 
> @caspervonb I believe we should wait on #11901 before we land this PR. I'm afraid they might clash in fundamental way.

Am 100% confused as what that issue is about or trying to resolve, but the steps proposal does not handle concurrency for tests.

**Comment by bartlomieju** [comment]
> > > cc @bartlomieju
> > 
> > 
> > @caspervonb I believe we should wait on #11901 before we land this PR. I'm afraid they might clash in fundamental way.
> 
> Am 100% confused as what that issue is about or trying to resolve, but the steps proposal does not handle concurrency for tests.

That issue will a plan to implement both presented proposals (imperative and declarative). Concurrency was discussed for both proposals and will be supported.

**Comment by bartlomieju** [comment]
@caspervonb thank you for the PR and effort, but I'm going to close it without a merge as it became quite stale and it's not obvious how we could integrate this functionality with test-steps API.

**Pull request closed without merging**
