### PR TITLE
fix(cli): Display anyhow error chain

### PR DESCRIPTION
**Pull request by mitch292**
Resolves issue #9570 . This change adds anyhow error context to terminal output which will provide more detail on the error like below. In the case where `deno bundle foo.ts` is run. Deno's specific error message, `relative import path "foo" not prefixed with..`, is omitted as it's only checked at runtime to handle dynamic imports. Happy to make any changes or go in another direction!

```
error: Unable to output bundle during Graph::bundle().

Caused by:
    0: load_transformed failed
    1: failed to analyze module
    2: failed to resolve foo from <file:///Users/andrewmitchell/Code/denocode/temp/temp.ts>
    3: The graph is missing a dependency.
         Specifier: foo from file:///Users/andrewmitchell/Code/denocode/temp/temp.ts
```

### CODE REVIEW

**Comment by kitsonk** [comment]
Just stylistic opinion but the numbers in the stack are meaningless to the end user. Just a `-` or `>` would be better in my opinion. Thoughts @ry @bartlomieju @nayeemrmn?

**Comment by bartlomieju** [comment]
> Just stylistic opinion but the numbers in the stack are meaningless to the end user. Just a `-` or `>` would be better in my opinion. Thoughts @ry @bartlomieju @nayeemrmn?

@kitsonk I think this is the default formatting of `anyhow` and can't really be changed without copy-pasting this logic to our wrapper error type. It looks alright to me.

**Comment by mitch292** [comment]
@kitsonk Yeah unfortunately those numbers are coming from anyhow. If the error chain only has a depth of one they'll be omitted like below which is nice. 
```
Error: Failed to read instrs from ./path/to/instrs.json

Caused by:
    No such file or directory (os error 2)
```

@bartlomieju - Happy to write a test! I added an integration test for the use case from the original issue. Unfortunately, some of the errors from that chain are coming from SWC. So if the there are some changes in the underlying crate the test may break. I could mock some errors and test the local function that changed in `cli/main.rs`, but didn't see any other tests in the file so didn't know if I should be the first to add them :). Let me know if you want me to go in a different direction with the test.

**Comment by kitsonk** [comment]
Ok, if it is the default behaviour. 🤷

**Review by wperron — APPROVED** [review]
Looks good, thanks

**Pull request merged**
