### PR TITLE
[WIP] add test showing that TS doesn't refresh file

### PR DESCRIPTION
**Pull request by bartlomieju**
Ref #4743

I need to think a bit more how to fix this problem, for now just a test showcasing the problem

### CODE REVIEW

**Comment by bartlomieju** [comment]
Update 29.05.20:
This issue still occurs, I will fix it soon.

**Comment by parliament718** [comment]
I'm doing the same thing as OP in #5631 and seeing the same issue. Calling deno cache before bundle no effect on the problem (still being compiled from cache).

I see something like 5 issue on this github related to this problem, is there an ETA for the fix?

Thank you

**Comment by ry** [comment]
>  is there an ETA for the fix?

@parliament718 not yet

**Comment by ry** [comment]
Rebased. Still failing.

**Comment by kitsonk** [comment]
Feels like we should close this and make sure we address it as part of #7225.

**Pull request closed without merging**
