### PR TITLE
Revert "perf(ext/websocket): optimize socket.send (#16320)"

### PR DESCRIPTION
**Pull request by crowlKats**
This reverts commit 36307c45

### CODE REVIEW

**Comment by aapoalas** [comment]
> Why?
This and it's friends:
https://github.com/denoland/deno/issues/17332

**Review by bartlomieju — APPROVED** [review]
LGTM

**Comment by crowlKats** [comment]
> Why?

this was supposed to be reverted months ago, but for some reason the revert never landed on main.

**Comment by littledivy** [comment]
Ok but we don't have a reproduction for the issue and no failing test case. How can we get this relanded? This revert blocks #16315

**Comment by aapoalas** [comment]
> Ok but we don't have a reproduction for the issue and no failing test case. How can we get this relanded? This revert blocks #16315

There are a few reproductions linked in the issue I linked, I believe. There is also a ticket asking for more tests for WS to avoid these reappearing, like they've done in this case.

**Pull request merged**
