### PR TITLE
update (cli/tests/wpt.jsonc): Added working wpt wasm tests

### PR DESCRIPTION
**Pull request by Vishal19111999**
Helps with issue #9001
I have added wasm wpt tests that were passing

### CODE REVIEW

**Comment by Vishal19111999** [comment]
#9083 is causing the failing test

**Comment by lucacasonato** [comment]
@Vishal19111999 Can you also add all tests that don't pass, and comment them out? That way we know what we still need to get working.

**Comment by Vishal19111999** [comment]
@lucacasonato ok

**Comment by Vishal19111999** [comment]
@lucacasonato done

**Review by lucacasonato — APPROVED** [review]
LGTM, thanks

**Pull request merged**
