### PR TITLE
Deno.exit() is an alias to self.close() in worker contexts

### PR DESCRIPTION
**Pull request by bartlomieju**
Closes https://github.com/denoland/deno/issues/14818

<s>This is technically a breaking change. If we want to be more conservative we could alias `Deno.exit()` to `self.terminate()` in worker contexts similarly to Node.js as pointed by Colin below.</s>

This commit changes `Deno.exit()` to be an alias to `self.close()` in worker contexts,
and setting an exit code becomes a no-op in such case.

### CODE REVIEW

**Comment by bartlomieju** [comment]
@cjihrig is `process.exitCode` forwarded from the worker to main context in Node? I just noticed that I added such a case, but I'm not sure if that's the correct behavior.

**Comment by cjihrig** [comment]
> setting an exit code becomes a no-op in such case

This part seems like it could confuse users. Is it possible to delete this functionality in a Worker context (or have it be a stub that throws, or show a warning, etc.)? For example, in Node Workers, some functionality gets [stubbed out like this](https://github.com/nodejs/node/blob/78b410ff4bfb9a967668a6895b0f55c82eab3d49/lib/internal/bootstrap/switches/does_not_own_process_state.js#L8-L9).

**Comment by bartlomieju** [comment]
> > setting an exit code becomes a no-op in such case
> 
> This part seems like it could confuse users. Is it possible to delete this functionality in a Worker context (or have it be a stub that throws, or show a warning, etc.)? For example, in Node Workers, some functionality gets [stubbed out like this](https://github.com/nodejs/node/blob/78b410ff4bfb9a967668a6895b0f55c82eab3d49/lib/internal/bootstrap/switches/does_not_own_process_state.js#L8-L9).

I can throw an error in `Deno.core.opSync("op_set_exit_code");` but it's not really a public API, OTOH the code you pass to `Deno.exit()` is not saved/passed in anyway (ie. it's ignored). What should I adjust?

**Comment by cjihrig** [comment]
Hm, if it's not intended to be public API and the worker itself doesn't have an "exit code" then it's probably fine to leave as is, and just document the behavior.

**Comment by bartlomieju** [comment]
> Hm, if it's not intended to be public API and the worker itself doesn't have an "exit code" then it's probably fine to leave as is, and just document the behavior.

I'll update the manual accordingly and mention it in a blog post.

**Review by dsherret — APPROVED** [review]

**Pull request merged**
