### PR TITLE
API doc improvments

### PR DESCRIPTION
**Pull request by cknight**
Further improvements and examples for API docs.  This round includes updates to:
* loadavg
* hostname
* env (fix overload function docs)
* open/openSync
* read/readSync
* readAll/readAllSync
* mkdir/mkdirSync
* makeTempDir/makeTempDirSync
* makeTempFile/makeTempFileSync
* readFile/readFileSync
* readdir/readdirSync
* readlink/readlinkSync
* lstat/lstatSync
* listen
* listenTLS
* connect
* metrics

### CODE REVIEW

**Comment by dubiousjim** [comment]
I wish my filesystem PRs would get reviewed and merged before we did document updates on filesystem stuff. It's going to be a chore to fix the merge conflicts.

**Comment by kitsonk** [comment]
@dubiousjim while I am a long term contributor with quite a bit of influence, I am afraid I can't merge PRs.  I haven't been reviewing yours personally, because it isn't an area that I feel I have a super good understanding of, plus the time I can dedicate to Deno is quite limited, so I do what I can when I can.

**Comment by dubiousjim** [comment]
I didn't aim to be complaining, I started writing the comment just to point out there are going to be conflicts. But I guess I was tired of rebasing and conflict fixing. Sorry that it came out as it did. Nothing but props for @cknight!

**Comment by kitsonk** [comment]
@dubiousjim you raised a valid point... ageing PRs are a problem.

**Comment by cknight** [comment]
Sorry @dubiousjim, and here was me thinking to take this on to get out of your way and let you catch up on your file system changes!  Give me a shout if you want help resolving the conflicts.

**Pull request merged**
