### PR TITLE
fix(dts/unstable)!: stop default export type behavior

### PR DESCRIPTION
**Pull request by sno2**
Towards #14976

### CODE REVIEW

**Comment by nayeemrmn** [comment]
Weird, I thought the other `export` usages should already have this effect. But looks like the non-exported types are indeed exposed without this `export {}`. Are there any docs or other references for this behaviour?

**Comment by sno2** [comment]
@nayeemrmn Is there anything else that this needs to be merged?

**Review by bartlomieju — CHANGES_REQUESTED** [review]
I'm marking this PR as "request changes" as this is potentially a very breaking change. I want @kitsonk to review it before merging.

**Comment by sno2** [comment]
Alright, also note that you can find all of the types that will now be private by searching `"  type"` (note the two spaces).  It will show a single interface with a property named type but all of the rest of the results are valid.

**Review by kitsonk — APPROVED** [review]
LGTM

If there is breaking behaviour, I think it is unsupported unintentional behaviour anyways and not something we would want people to continue to do.

**Pull request merged**
