### PR TITLE
Remove ts_library_builder, maintain lib.deno_runtime.d.ts by hand

### PR DESCRIPTION
**Pull request by ry**
I want to temporarily rip out ts_library_builder - I'm basically ripping out all of our automated build processes towards the goal of getting "cargo build" to be our main build system. First was flatbuffers, now I'm doing snapshots - which is outlined in the https://github.com/ry/deno_typescript repo. This will involve removing rollup and changing our import syntax in //js to use file extensions. This breaks ts_library_builder... so want to just check in lib.deno_runtime.d.ts for now until the dust settles. Once build.py is gone, I will try to hook up the build to be more automated again. Eventually I want to rewrite ts_library_builder to take as input the d.ts file produced by outFile, rather than the whole tree.

Towards #2496, #2608, https://github.com/denoland/deno/issues/2711

### CODE REVIEW

**Comment by ry** [comment]
@kitsonk I've done some benchmarking. We will see about a 1.15x slow down on cold rebuilds due to fetching the assets. On the other hand, the executable becomes 2mb smaller.

This is simpler and the perf regression isn't too bad. 

I am trying to think about how to do "!string" style assets without rollup, but I think that can wait.

**Comment by piscisaureus** [comment]
So you don't want to keep ts_library_builder in the repo so it can be run manually?
I'm not changing too much .ts files but it seems like a pain to manually update the .d.ts file; might be easier to just run some script instead, even if it's not part of the build process.

**Comment by ry** [comment]
@piscisaureus due to the file extension change it won’t be runnable

**Comment by ry** [comment]
The main performance impact of this patch was to the memory usage of cold run typescript programs. This is due to the removal of assets from the bundle - they are now fetched from Rust - the memory gets duplicated. 

Screen Shot 2019-08-30 at 2 26 59 PM

Otherwise this massive change looks good software. It seems tests fail if lib.deno_runtime.d.ts gets out of sync with the code, so far.

**Pull request merged**
