### PR TITLE
fix(streams): add Float64Array to ReadableStreamByobReader.read

### LINKED ISSUE #13176: ReadableStreamBYOBReader.read<Float64Array>(view: Float64Array) returns DataView
When I ran the following code, it resulted in unexpected behavior.

```typescript
Deno.test('1.0f from bytes.', () => {
  const b = new Uint8Array([
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0xF0, 0x3F,
  ]);
  const f = new Float64Array(b.buffer);
  a.assertEquals(String(f), "1"); // Okay
});

Deno.test('1.0f from bytes via BYOB stream.', async () => {
  const b = new Uint8Array([
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0xF0, 0x3F,
  ]);
  const response = await fetch(URL.createObjectURL(new Blob([b])));
  if (!response.body) { throw new Error(); }

  const reader = response.body.getReader({ mode: 'byob' });
  const view = new Float64Array(1);
  // ReadableStreamBYOBReader.read<Float64Array>(view: Float64Array): Promise<ReadableStreamBYOBReadResult<Float64Array>>
  const result = await reader.read(view);
  a.assertEquals(result.done, false);
  a.assertEquals(Object.getPrototypeOf(result.value).constructor.name, 'Float64Array');
  // ...
  // failures:
  // 
  // 1.0f from bytes via BYOB stream.
  // AssertionError: Values are not equal:
  // 
  // 
  //    [Diff] Actual / Expected
  //
  //
  // -   DataView
  // +   Float64Array
  // ...
});
```

## Expect

ReadableStreamBYOBReader.read<Float64Array>(view: Float64Array) returns
`{ value: Float64Array, done: false }`

## Actual

ReadableStreamBYOBReader.read<Float64Array>(view: Float64Array) returns
`{ value: DataView, done: false }`

## Version

```bash
$ deno --version
deno 1.17.0 (release, x86_64-unknown-linux-gnu)
v8 9.7.106.15
typescript 4.5.2
```

### PR DESCRIPTION
**Pull request by crowlKats**
Closes #13176
will look into adding WPT separately later on.

### CODE REVIEW

**Review by bartlomieju — CHANGES_REQUESTED** [review]
Can you do WPT in this PR?

**Comment by petamoriken** [comment]
It would be better to use `TypedArrayPrototypeGetSymbolToStringTag`
https://github.com/denoland/deno/pull/17431#pullrequestreview-1264586320

**Comment by aapoalas** [comment]
Linked issue is now merged, this can probably proceed.

**Comment by crowlKats** [comment]
> Linked issue is now merged, this can probably proceed.

still need to write a WPT

**Comment by bartlomieju** [comment]
@crowlKats could you finish this PR?

**Comment by crowlKats** [comment]
Closing in favour of #18188

**Pull request closed without merging**
