### PR TITLE
enable bench bot

### PR DESCRIPTION
**Pull request by littledivy**
Run benchmarks on a bare metal server. The bot is a webhook on Deno deploy which can provision a spot instance on Equinix Metal. The machine type is `m3.small.x86` running a Ubuntu 22.04.

Commands:

`+bench` - Provision and schedule benchmarks for this PR.
`+bench status <id>` - Get current status of the metal instance.

The bot source is here: https://github.com/denoland/bench_bot

### CODE REVIEW

**Comment by littledivy** [comment]
+bench

**Comment by littledivy** [comment]
+bench status c9c7b041-ed10-4c37-bbb5-186e909d7055

**Comment by littledivy** [comment]
+bench status b3f44f02-2ef4-4680-955f-e11e899e1caa

**Comment by littledivy** [comment]
+bench

**Comment by littledivy** [comment]
+bench

**Comment by littledivy** [comment]
+bench

**Review by bartlomieju — APPROVED** [review]

**Pull request merged**
