### PR TITLE
feat(cli): Support using both `--watch` and `--inspect` at the same time

### LINKED ISSUE #20525: Allow using `--watch` and `--inspect` at the same time.
During development I frequently make use of `--watch` for auto reloading. But occasionally I might want to inspect the code that is running. Right now I have to change up the arguments in my deno.json and restart the process, which is somewhat tedious.

It seems like this was intentional (#7610), but I think the current situation is arguably worse. After all, right now if I make a change, I still have to restart the inspector in order to reconnect it. The only difference is that I now have to restart Deno manually as well.

Note though that using the 'dedicated DevTools for Node' option in Chrome does automatically reconnect a closed inspector. I'm not sure which use case #7610 was addressing. But maybe Deno could print a console message informing the user that they might have to reconnect their inspector.

### PR DESCRIPTION
**Pull request by jespertheend**
Fixes #20525

### CODE REVIEW

**Comment by jespertheend** [comment]
I tried `deno run --watch --inspect foo.js` and both vscode as well as dedicated DevTools for node seemed to automatically reconnect after a change.

But unsurprisingly, connecting to a specific thread using `chrome://inspect/#devices` didn't automatically reconnect.
In fact, it caused Deno to panic
```
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos aarch64
Version: 1.37.0
Args: ["./target/debug/deno", "run", "--watch", "--inspect", "inspecttest/foo.js"]

thread '<unnamed>' panicked at 'all branches are disabled and there is no else branch', runtime/inspector_server.rs:339:5
```
Although I can't seem to reproduce this anymore now.

Another issue might be that if the debugger is paused, making a change doesn't restart the application until the debugger is resumed.

@bartlomieju Are these the pointers you were referring to? Or was this about showing the console message?

**Comment by jespertheend** [comment]
I managed to reproduce it again

<details><summary>Full stack trace</summary>
<p>
```
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos aarch64
Version: 1.37.0
Args: ["./target/debug/deno", "run", "--watch", "--inspect", "inspecttest/foo.js"]

thread '<unnamed>' panicked at 'all branches are disabled and there is no else branch', runtime/inspector_server.rs:339:5
stack backtrace:
   0:        0x10c07e44c - std::backtrace_rs::backtrace::libunwind::trace::h65bc41667b946a9b
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x10c07e44c - std::backtrace_rs::backtrace::trace_unsynchronized::h11e85e00c64d2951
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x10c07e44c - std::sys_common::backtrace::_print_fmt::hd30f3b7be3b8d9bb
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys_common/backtrace.rs:65:5
   3:        0x10c07e44c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h56d7672c82815b65
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys_common/backtrace.rs:44:22
   4:        0x10c0a4a08 - core::fmt::rt::Argument::fmt::h6ead82aa10d38e42
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/fmt/rt.rs:138:9
   5:        0x10c0a4a08 - core::fmt::write::h632b3cc8e66b4f04
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/fmt/mod.rs:1094:21
   6:        0x10c077410 - std::io::Write::write_fmt::hc28441b249a4971d
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/io/mod.rs:1714:15
   7:        0x10c07e2a4 - std::sys_common::backtrace::_print::h0d2f8b8a08c5cc48
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys_common/backtrace.rs:47:5
   8:        0x10c07e2a4 - std::sys_common::backtrace::print::h8057ced4b0f9fdc1
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys_common/backtrace.rs:34:9
   9:        0x10c07ffc8 - std::panicking::default_hook::{{closure}}::h8157fa8f0f7934b5
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:269:22
  10:        0x10c07fd58 - std::panicking::default_hook::hdaefe3bfb5fe212c
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:288:9
  11:        0x104843cb8 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h89efc30d54daf8ea
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/alloc/src/boxed.rs:2007:9
  12:        0x1053b9934 - deno::setup_panic_hook::{{closure}}::haa503d51ff451c6d
                               at /Users/Jesper/repositories/deno/cli/main.rs:227:5
  13:        0x10c0806b8 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h4efc1b5830705729
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/alloc/src/boxed.rs:2007:9
  14:        0x10c0806b8 - std::panicking::rust_panic_with_hook::h21091a3c79c5da9c
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:709:13
  15:        0x10c080450 - std::panicking::begin_panic_handler::{{closure}}::hd2f65b958d3068b8
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:595:13
  16:        0x10c07e82c - std::sys_common::backtrace::__rust_end_short_backtrace::h53ec33e49ec66621
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys_common/backtrace.rs:151:18
  17:        0x10c0801f8 - rust_begin_unwind
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:593:5
  18:        0x10c0a1bec - core::panicking::panic_fmt::h3bbf9265d206434c
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:67:14
  19:        0x106634364 - deno_runtime::inspector_server::pump_websocket_messages::{{closure}}::h5a1b9c2b72c414cf
                               at /Users/Jesper/repositories/deno/runtime/inspector_server.rs:339:5
  20:        0x106632414 - deno_runtime::inspector_server::handle_ws_request::{{closure}}::h1c06c1b310f3b52a
                               at /Users/Jesper/repositories/deno/runtime/inspector_server.rs:185:65
  21:        0x106d7a200 - <deno_unsync::task::MaskFutureAsSend<F> as core::future::future::Future>::poll::hfc77d59c7df9d741
                               at /Users/Jesper/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_unsync-0.3.0/src/task.rs:129:13
  22:        0x1069f33f4 - tokio::runtime::task::core::Core<T,S>::poll::{{closure}}::h45d2576fc46e3273
                               at /Users/Jesper/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/core.rs:334:17
  23:        0x1069e29a0 - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::h00230be546f09fdf
                               at /Users/Jesper/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/loom/std/unsafe_cell.rs:16:9
  24:        0x1069e29a0 - tokio::runtime::task::core::Core<T,S>::poll::heeeb83f2f91434bf
                               at /Users/Jesper/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/core.rs:323:13
  25:        0x106715300 - tokio::runtime::task::harness::poll_future::{{closure}}::hbe17f90884fa02ed
                               at /Users/Jesper/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:485:19
  26:        0x1071694ec - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h86a4224f4c62f24d
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panic/unwind_safe.rs:271:9
  27:        0x1070119dc - std::panicking::try::do_call::h85133d9660da4122
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:500:40
  28:        0x1070b0c44 - ___rust_try
  29:        0x106fdc9d8 - std::panicking::try::he6ab7ec0dfe75a37
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:464:19
  30:        0x1072b6b90 - std::panic::catch_unwind::h3a01c8288205d650
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panic.rs:142:14
  31:        0x1066d3520 - tokio::runtime::task::harness::poll_future::ha3453b606e0e2d6b
                               at /Users/Jesper/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:473:18
  32:        0x106741154 - tokio::runtime::task::harness::Harness<T,S>::poll_inner::h828325aaedece084
                               at /Users/Jesper/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:208:27
  33:        0x1067c3428 - tokio::runtime::task::harness::Harness<T,S>::poll::hc2ad2a4c56b44cbe
                               at /Users/Jesper/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:153:15
  34:        0x106893048 - tokio::runtime::task::raw::poll::hb5fe9387bba2b5b8
                               at /Users/Jesper/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/raw.rs:276:5
  35:        0x10ac3075c - tokio::runtime::task::raw::RawTask::poll::h503514bcfcdc353f
                               at /Users/Jesper/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/raw.rs:200:18
  36:        0x10856704c - tokio::runtime::task::LocalNotified<S>::run::hdded06df7a4bf5ee
                               at /Users/Jesper/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/mod.rs:400:9
  37:        0x106d40178 - tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}::h0e5825dc55d555ce
                               at /Users/Jesper/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/current_thread/mod.rs:706:25
  38:        0x106d3dce4 - tokio::runtime::coop::with_budget::h99f30f5ccd7fd44e
                               at /Users/Jesper/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:107:5
  39:        0x106d3dce4 - tokio::runtime::coop::budget::h343019412cdac917
                               at /Users/Jesper/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:73:5
  40:        0x106d3dce4 - tokio::runtime::scheduler::current_thread::Context::run_task::{{closure}}::h3835eddd1110a263
                               at /Users/Jesper/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/current_thread/mod.rs:343:43
  41:        0x106d3cba4 - tokio::runtime::scheduler::current_thread::Context::enter::h07edc7c5db323e3c
                               at /Users/Jesper/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/current_thread/mod.rs:410:19
  42:        0x106d3d8b0 - tokio::runtime::scheduler::current_thread::Context::run_task::h74d1284a01f0e698
                               at /Users/Jesper/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/current_thread/mod.rs:343:23
  43:        0x106d3f118 - tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::h787d0e4378cd819d
                               at /Users/Jesper/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/current_thread/mod.rs:705:34
  44:        0x106d3e7f0 - tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}::h32f16cd577651602
                               at /Users/Jesper/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/current_thread/mod.rs:743:68
  45:        0x106f22fa4 - tokio::runtime::context::scoped::Scoped<T>::set::h6541d00e53500b1a
                               at /Users/Jesper/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/scoped.rs:40:9
  46:        0x106bea798 - tokio::runtime::context::set_scheduler::{{closure}}::h60e0a6b6f5301990
                               at /Users/Jesper/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context.rs:176:26
  47:        0x10730eef0 - std::thread::local::LocalKey<T>::try_with::h3d430385a37d8aaa
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/thread/local.rs:270:16
  48:        0x107308d54 - std::thread::local::LocalKey<T>::with::h1c6615a64f155562
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/thread/local.rs:246:9
  49:        0x106bea714 - tokio::runtime::context::set_scheduler::h80cbb2f3e0ee81eb
                               at /Users/Jesper/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context.rs:176:9
  50:        0x106d3e630 - tokio::runtime::scheduler::current_thread::CoreGuard::enter::he05dfb13df1031e8
                               at /Users/Jesper/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/current_thread/mod.rs:743:27
  51:        0x106d3e89c - tokio::runtime::scheduler::current_thread::CoreGuard::block_on::h18644154f8eca554
                               at /Users/Jesper/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/current_thread/mod.rs:652:19
  52:        0x106d1d908 - tokio::runtime::scheduler::current_thread::CurrentThread::block_on::{{closure}}::h18884be3551922a8
                               at /Users/Jesper/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/current_thread/mod.rs:175:28
  53:        0x1072cde7c - tokio::runtime::context::runtime::enter_runtime::hfd620552781ab0e7
                               at /Users/Jesper/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/runtime.rs:65:16
  54:        0x106d1d76c - tokio::runtime::scheduler::current_thread::CurrentThread::block_on::h1d90379b9887d3dc
                               at /Users/Jesper/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/current_thread/mod.rs:167:9
  55:        0x106dfc1e0 - tokio::runtime::runtime::Runtime::block_on::hf5c17839c28cac77
                               at /Users/Jesper/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/runtime.rs:347:47
  56:        0x1065442b0 - tokio::task::local::LocalSet::block_on::hb861b576d1190da4
                               at /Users/Jesper/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/task/local.rs:536:9
  57:        0x106631a64 - deno_runtime::inspector_server::InspectorServer::new::{{closure}}::hefed1dc983445a92
                               at /Users/Jesper/repositories/deno/runtime/inspector_server.rs:55:7
  58:        0x106556c30 - std::sys_common::backtrace::__rust_begin_short_backtrace::ha9e1742ee0ad326e
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys_common/backtrace.rs:135:18
  59:        0x1072d2034 - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::hf95daf79f147cee6
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/thread/mod.rs:529:17
  60:        0x107179fec - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hfdc3aab798cd0aa1
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panic/unwind_safe.rs:271:9
  61:        0x106feed30 - std::panicking::try::do_call::h0de8958c295620e0
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:500:40
  62:        0x1070b0c44 - ___rust_try
  63:        0x106f70da8 - std::panicking::try::h1a30cd72ba0d0cd5
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:464:19
  64:        0x1072d1b28 - std::panic::catch_unwind::hca50962187abcfc8
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panic.rs:142:14
  65:        0x1072d1b28 - std::thread::Builder::spawn_unchecked_::{{closure}}::h9988b937636c6e3d
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/thread/mod.rs:528:30
  66:        0x106a8c834 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h861496955bf09408
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/ops/function.rs:250:5
  67:        0x10c0863a8 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hb85015ba7f8e62e3
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/alloc/src/boxed.rs:1993:9
  68:        0x10c0863a8 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h5923e50a88401120
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/alloc/src/boxed.rs:1993:9
  69:        0x10c0863a8 - std::sys::unix::thread::Thread::new::thread_start::h8d5cf73423142312
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys/unix/thread.rs:108:17
  70:        0x1a0587fa8 - __pthread_joiner_wake
```
</p>
</details> 

I'm still not quite sure what the exact conditions are that triggers this, it seems to happen about 50% of the time.

**Comment by bartlomieju** [comment]
@jespertheend nice work! The panic you are hitting is somewhat expected - before this change, we didn't allow using `--inspect` and `--watch` together, as the inspector server assumed that it would be closed down when the process finishes. Now we need to handle closure of in-process WS pipe more gracefully, by shutting down the appropriate task. 

I think for starters, you can try to add an "else" branch to the `tokio::select!` macro in `pump_websocket_messages` that will break out of the loop and finish the spawned task. Looking at this code, I can say that it hasn't been updated much in the recent months, I might want to budget a couple hours this week to clean it up and refresh to make the code paths more obvious.

**Comment by jespertheend** [comment]
Thanks @bartlomieju! That seems to have done the trick, as I am no longer able to reproduce the panic.

As for the console message, my initial thought was to print the message inside the operation of `watch_func`, and use `cli_options` to figure out whether the `--inspect` flag has been set.
But then I figured maybe there's a way to include a flag the `PrintConfig` somehow.
Even more ideal would be if it only prints the message when an inspector was actually connected, but I'm not really sure how to go about that.

**Comment by bartlomieju** [comment]
@jespertheend sorry I'm misunderstanding something; what message are you referring to?

**Comment by jespertheend** [comment]
@bartlomieju In #20525 a console message was briefly discussed that warns the user that their inspector has been disconnected. Right now the regular "Debugger session ended" is not printed, and even if it were, the console is cleared when watching.

Not displaying a message is fine by me as well. A disconnected inspector is generally what I'd expect when the process restarts.

**Comment by bartlomieju** [comment]
@jespertheend maybe let's skip it for now since as you said the screen is cleared anyway.

**Review by bartlomieju — COMMENTED** [review]
@jespertheend this looks good to me, any chance you could add a test to `cli/tests/integration/watcher_tests.rs` that showcases this change?

**Comment by jespertheend** [comment]
@bartlomieju I wasn't sure how to write a test that specifically triggers the right conditions for that panic. But I've added a test that at least checks if the debugger restarts when a watched file is changed.

**Review by bartlomieju — APPROVED** [review]
LGTM, nice work @jespertheend. I'm gonna change the title of the PR to be "fix" as I think it's not really a new feature, just fixing a problem we had before that prevented it from working. Expect it to be released in v1.37.2 next week.

**Pull request merged**
