### PR TITLE
std/node: require_ -> require

### PR DESCRIPTION
**Pull request by seishun**
The underscore is no longer required.

### CODE REVIEW

**Comment by seishun** [comment]
This fails lint, but should it? I think the linter should consider `require` a regular function without any special meaning.

**Comment by ry** [comment]
@seishun Can you disable the lint rule `@typescript-eslint/no-var-requires` in those individual files by placing this at the top
```
// eslint-disable @typescript-eslint/no-var-requires
```

**Comment by seishun** [comment]
Sure, but maybe this rule should be disabled globally?

**Comment by ry** [comment]
I'm also ok with disabling it globally. Per-file would be a more conservative approach. eslint config is here:

https://github.com/denoland/deno/blob/master/.eslintrc.json

**Comment by seishun** [comment]
Why were 2 checks cancelled?

**Comment by ry** [comment]
@seishun I'm not sure. I was also experiencing this yesterday...

You can re-run CI by pushing an empty commit:
```
git commit --allow-empty -m x && git push
```

**Pull request merged**
