### PR TITLE
updated std/fs docs to provide more context on unstable perm

### PR DESCRIPTION
**Pull request by paulmj7**
Talked about this with some of the people in the Deno discord. Not all of the modules in std/fs need the unstable flag so I updated the docs to say "most" instead of "all". I also noted which modules I used that do not need the unstable flag.

Was told for a small doc change I probably wouldn't need to create an issue, but I can do so if needed.

### CODE REVIEW

**Comment by bartlomieju** [comment]
@paulmj7 thanks, please sign the CLA so we can land this PR

**Comment by paulmj7** [comment]
@bartlomieju my apologies! I thought I had already signed it but it must've not gone through.

**Review by bartlomieju — APPROVED** [review]
LGTM, thanks @paulmj7

**Comment by caspervonb** [comment]
Uhm... @bartlomieju this added documentation for non existing functions.

**Comment by nayeemrmn** [comment]
It was a merge error.

**Pull request merged**
