### PR TITLE
fix(bench): Fix table column alignments and NO_COLOR=1

### PR DESCRIPTION
**Pull request by ArmaanAS**
Fix table layout for `deno bench` command with and without color (`NO_COLOR=1`).

Fixes issue in #25156

## With Color

<p align="center">
  Bench with color
  <br>
  <em>Old (top) vs New (bottom) benchmark layout comparison.</em>
</p>

## Rounded to 1 d.p.

All numbers are displayed to 1 decimal place, fixed not varying. This keeps the dots all aligned with each other and makes the table cleaner and easier to read. Except for when iter/s above 999 where it displays no fractional digits. (I made this decision because the longest `iter/s` I managed to achieve was over 1,000,000,000.0 which is too many digits and adds too much blank space for smaller numbers.) This decision also allowed me to remove a large block of  `unsafe` code.

## `NO_COLOR=1`

<p align="center">
  Bench without color
  <br>
  <em>Old (top) vs New (bottom) benchmark layout, without color.</em>
</p>

## Column Widths

The column widths have been reduced due the change from 2 -> 1 decimal place, reducing the overall table width.
- `benchmark` Same (dynamic)
- `time (avg)` 14 -> 13
- `iter/s` 14 -> 13
- `(min ... max)` 24 -> 21
- `p75` 9 -> 8
- `p99` 9 -> 8
- `p995` 9 -> 8

## Other Alignments

In the spirit of aligning things together, I padded the CPU text so it aligned with the Runtime text. And I added an empty line below the file name.

I've also added a 1 character gap between each section in the header divider.

<p align="center">
  Bench error
  <br>
  <em>Old (top) vs New (bottom) benchmark error.</em>
</p>

Just to be OTT, I aligned the error message with the `time (avg)` column, as was originally intended.

### CODE REVIEW

**Comment by bartlomieju** [comment]
Great improvements, this is way easier to read! What do you think about changing `time (avg)` heading to `time/iter (avg)` and remove `/iter` in the values rows?

I marked this PR as "ready for review" to trigger CI.

**Comment by ArmaanAS** [comment]
Personally, I like the current style as it makes those values easy to distinguish from the other numbers. And it draws your attention as the "primary statistic".

<p align="center">
  Renamed time (avg) column
  <br>
  <em>Proposed column style</em>
</p>

Also "time/iter (avg)" is 15 characters long but the column is just 13. Actually, this still works but the heading will overlap into the next column by 1 char.

**Comment by ArmaanAS** [comment]
Whilst I'm here, I've improved the alignment of the summary section. The "x"'s all align properly. And I've rounded the "123456x faster than" number to 4 significant figures or 2 decimal places.

<p align="center">
  Summary comparison.
  <br>
  <em>Old (top) vs Proposed (bottom) summary comparison.</em>
</p>

And I've also fixed the formatting of your suggestion, @bartlomieju. Apologies, the previous image wasn't formatted well. After staring at it for an hour, I now prefer it the way you've suggested so I've included it 👍 Sorry for doubting you.

**Comment by ArmaanAS** [comment]
Took a while but the tests all pass now. Enjoy!

**Comment by ArmaanAS** [comment]
Large iter/s now get rounded to 4 significant figures.

<p align="center">
  Summary comparison.
  <br>
  <em>Old (top) vs New (bottom) iter/s rounding.</em>
</p>

Sorry, I couldn't help myself 😬 I had to go back and change it.

**Review by bartlomieju — APPROVED** [review]
Great improvement, thank you @ArmaanAS!

**Pull request merged**
