### PR TITLE
fix(lsp): don't pre-load documents matched in the config file's "exclude"

### PR DESCRIPTION
**Pull request by dsherret**
This prevents documents specified in a deno.json's "exclude" from being pre-loaded by the lsp.

For example, someone may have something like:

```jsonc
// deno.json
{
  "exclude": [
    "dist" // build directory
  ]
}
```

### CODE REVIEW

**Review by bartlomieju — DISMISSED** [review]
LGTM, let's land it before the release

**Review by bartlomieju — COMMENTED** [review]
Looks like test is failing because ordering is not deterministic

**Review by marvinhagemeister — APPROVED** [review]
Great idea!

**Comment by dsherret** [comment]
I forgot to exclude glob patterns so I just added that now.

**Review by bartlomieju — APPROVED** [review]
LGTM again

**Pull request merged**
