### PR TITLE
test(ext/node): Port node/https_test.ts from deno_std 

### PR DESCRIPTION
**Pull request by fbaltor**
Porting the `node/https_test.ts` from [deno_std v0.177.0](https://github.com/denoland/deno_std/blob/v0.177.0/node/https_test.ts), resolving one task of the bigger issue #17840.

### CODE REVIEW

**Comment by fbaltor** [comment]
This test is broken in two files: the [https_test.ts](https://github.com/fbaltor/deno/blob/74694a1e538451e209a85e072119b9da534b9acf/cli/tests/unit_node/https_test.ts) part, responsible for setting the TLS server and the [https_request.ts](https://github.com/fbaltor/deno/blob/74694a1e538451e209a85e072119b9da534b9acf/cli/tests/unit_node/testdata/https_request.ts) part, which is triggered by the first part and sends a request to the aforementioned server. It is mostly a copy of the original test in [deno_std](https://github.com/denoland/deno_std/blob/b4239898d6c6b4cdbfd659a4ea1838cf4e656336/node/https_test.ts).

But for some reason both assertions of the https_request.ts file regarding the "authorized" part of the server response are failing. Indeed, the `res.socket` object is missing it's `authorized` property.

**Comment by bartlomieju** [comment]
@crowlKats can you take a look at the failure?

**Comment by ktfth** [comment]
@fbaltor this could help

https://github.com/ktfth/deno/commit/abfa7487d860c722bdc50d1db8d293145681b997

**Comment by ktfth** [comment]
@fbaltor or with correct declaration of fake socket.

https://github.com/ktfth/deno/commit/e3acc31b1df4a8051f2db784960237da255ddc7b

**Comment by crowlKats** [comment]
@fbaltor yes ideally this would be the correct value, however this may prove tricky. We wont be changing from FakeSocket soon as that involves quite a lot of work, but if the right value is achieveable with the current system, then that would be ideal

**Comment by bartlomieju** [comment]
Thanks for the PR @fbaltor, but I'm gonna close it without a merge. Since it was opened we added a bunch more tests and enabled more native Node.js tests.

**Pull request closed without merging**
