### PR TITLE
feat(ext/fs): add isBlockDevice, isCharDevice, isFifo, isSocket to FileInfo

### PR DESCRIPTION
**Pull request by wafuwafu13**
recreate https://github.com/denoland/deno/pull/16064

`isFile`, `isDirectory`, `isSymlink` are defined in `Deno.FileInfo`, but `isBlockDevice`, `isCharacterDevice`, `isFIFO`, `isSocket` are not defined.
These are defined in [Node.js fs.Stats](https://nodejs.org/api/fs.html#class-fsstats), and it is good to be defined in `Deno.FileInfo` to improve compatibility.

### CODE REVIEW

**Comment by aapoalas** [comment]
Please turn the PR into a draft until it is ready for review / test running.

**Comment by wafuwafu13** [comment]
when add isBlockDevice
https://github.com/denoland/deno/actions/runs/4901413563/jobs/8752670724
```zsh
<                "exportMapKey": String("foo|6846|file:///a/b"),
>                "exportMapKey": String("foo|6845|file:///a/b"),
```

when add isBlockDevice, isCharDevice, isFifo, isSocket
https://github.com/denoland/deno/actions/runs/4952421541/jobs/8858694905?pr=19008
```zsh
<                "exportMapKey": String("foo|6849|file:///a/b"),
>                "exportMapKey": String("foo|6845|file:///a/b"),
```

**Comment by bartlomieju** [comment]
> ```
> ---- integration::lsp::lsp_completions_auto_import stdout ----
> deno_exe path /home/runner/work/deno/deno/target/release/deno
> thread 'integration::lsp::lsp_completions_auto_import' panicked at 'assertion failed: `(left == right)`
> ```
> 
> when add isBlockDevice https://github.com/denoland/deno/actions/runs/4901413563/jobs/8752670724
> 
> ```
> <                "exportMapKey": String("foo|6846|file:///a/b"),
> >                "exportMapKey": String("foo|6845|file:///a/b"),
> ```
> 
> when add isBlockDevice, isCharDevice, isFifo, isSocket https://github.com/denoland/deno/actions/runs/4952421541/jobs/8858694905?pr=19008
> 
> ```
> <                "exportMapKey": String("foo|6849|file:///a/b"),
> >                "exportMapKey": String("foo|6845|file:///a/b"),
> ```
> 
> I have yet to figure out if this is a fatal change...

It's not, it's expected. TypeScript provides completions that can change when new APIs appear. I've rebased the PR.

**Review by levex — APPROVED** [review]
LGTM

**Review by levex — APPROVED** [review]
LGTM

**Pull request merged**
