### PR TITLE
WIP feat(test): add timeout feature [HELP WANTED]

### LINKED ISSUE #7088: async iterator can cause silent process exit in `Deno.test()`
The following script `test.ts` causes `deno test` to silently perform the equivalent of `exit(0)` from within the test `fn()`:

```
$ deno test ./test.ts && echo OK
running 2 tests
test bug ... OK
```

All works as expected if the `bug` test is filtered out:

```
$ deno test ./test.ts --filter ok && echo OK
running 1 tests
test ok ... ok (3ms)

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 1 filtered out (3ms)

OK
```

My version info:

```
$ deno --version
deno 1.3.0
v8 8.6.334
typescript 3.9.7
$ grep DESC /etc/lsb-release
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
$ uname -s -p -v
Linux #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64
```

Note: This is a minimal reproducer for a bug that showed up in a timeout-based iterater, thus the odd construction.

File `test.ts`:

```typescript
class FooIterator implements AsyncIterableIterator<number> {
  resolve: any;

  constructor() {
    this.resolve = null;
  }

  [Symbol.asyncIterator](): AsyncIterableIterator<number> {
    return this;
  }

  next(): Promise<IteratorResult<number>> {
    return new Promise((res) => {
      this.resolve = res;
    });
  }
}

Deno.test({
  name: "bug",
  async fn() {
    const foo = new FooIterator();
    for await (const value of foo) {
      console.log(`value=${value}`);
    }
  },
});

Deno.test({
  name: "ok",
  async fn() {},
});
```

### PR DESCRIPTION
**Pull request by magurotuna**
Fixes #7088

This PR adds `timeout` option to `Deno.test`.

As described in #7088, a promise that will never be fulfilled or rejected causes strange behavior in deno test - as if the test exits with code 0.
The idea I came up to address this problem is to introduce timeout feature. If a test function is async one, it is wrapped so that the timer will run in parallel. It allows to detect and interrupt ever-pending promises as well as too long operations.
As far as I know, most of famous test frameworks (e.g. Jest) have the timeout option, so it's reasonable to adopt it IMO.

### Example

<details><summary>click here to see the example</summary>
<p>

We can write tests and specify timeout period like:

```ts
function delay(ms: number) {
  return new Promise((resolve) => {
    setTimeout(resolve, ms);
  });
}

function foo() {
  return new Promise((_resolve, _reject) => {
    console.log("in promise");
    // neither resolve nor reject is called
  });
}

Deno.test({
  name: "bug",
  async fn() {
    const a = await foo();
    console.log(a);
  },
});

Deno.test({
  name: "heavy task wituout await",
  async fn() {
    let sum = 0;
    for (let i = 0; i < 5000000000; i++) {
      sum += i;
    }
    console.log(sum);
  },
});

Deno.test({
  name: "sleep with await",
  async fn() {
    await delay(1400);
    console.log("sleep with await done");
  },
  timeout: 1000, // timeout period can be specified. the default value is 2000
});

Deno.test({
  name: "error",
  fn() {
    throw "error!";
  },
});

Deno.test({
  name: "ok",
  async fn() {},
});
```

The output looks like:

image

</p>
</details>

### Problem (help wanted)

To my sad, my timeout implementation does not work in some cases :( 
Consider the following test:

```ts
// `delay` function is the same as above
Deno.test({
  name: "one",
  async fn() {
    await delay(1200); // (a)
  },
  timeout: 1000,
});

Deno.test(
  "two",
  async function () {
    await delay(400);
  },
  1000
);
```

Unfortunately, this test resulted in the strange output like:

image

The test "one" was timed out. It's okay since the delay period is longer than the timeout.
But the test "two" failed unexpectedly due to leaking async ops.
This is because `await delay(1200)` in the test "one" (marked (a)) was still running at the beginning of the test "two", and it finished during the test "two". It is reported as "leaking async ops".

I spend today trying to find a solution to this but in vain.
I'm feeling like it is so hard for both the timeout feature and detecting leaking async ops to work simultaneously.
Should we take either? Or are there any great solutions? Any ideas would be very appreciated!

### CODE REVIEW

**Comment by ry** [comment]
Rather than adding this to the built-in test function, what if this was done as a helper function in std/testing ?

**Comment by magurotuna** [comment]
Thanks so much @ry for your quick advice!
I didn't look at std/testing. I'll take a look at it and re-consider.

**Comment by bartlomieju** [comment]
@magurotuna I don't think you'll be able to implement timeout and have async ops sanitization. Timers (in this case `timeout`) is an async op - so you might get leaking op error even for the test timeout. This feature would require more changes to the testing infrastructure.

**Comment by caspervonb** [comment]
> Rather than adding this to the built-in test function, what if this was done as a helper function in std/testing ?

This seems like a prime candidate for std/async.

**Comment by magurotuna** [comment]
Thank you @bartlomieju !
Yeah, today I've got the same conclusion as you're explaining... 😢 

> This feature would require more changes to the testing infrastructure.

Sounds too difficult for me since I'm just a newbie, though I want to try

**Comment by magurotuna** [comment]
@caspervonb Cool! I'll check std/async as well.

**Comment by magurotuna** [comment]
@ry @caspervonb 
Sorry if I misunderstand what you said.
If I add `timeout` function to somewhere in `std`,  can I achieve the original goal?
Here "the original goal" is, when end-users of Deno write a test returning a promise that will never be resolved or rejected mistakenly, the Deno runtime can detect and abort it using timeout. This kind of mistake actually happened in #7088 .

From my understanding, to achieve this goal we have to modify the build-in test function - otherwise end-users of Deno would need to write like the following to enable timeout:

```ts
import { timeout } from "<somewhere>";
Deno.test({
  name: "foo",
  fn: timeout(async () => {
    await delay(1200);
  }, 1000),
});
```

**Comment by magurotuna** [comment]
After consideration, I've found that the unref version of timer would be so helpful.

Close this for now, because I guess we have to follow the following steps:

1. fix the problem of counting time that happens when `setTimeout` is followed by `clearTimeout` #7599 (as this might prevent implementing the unref timer)
2. add unref version of `setTimeout` https://github.com/denoland/deno/issues/6141
3. back to here, add timeout feature to `deno test` using the unref timer

**Pull request closed without merging**
