### PR TITLE
fix(runtime): Extract error code for all OS error variants

### PR DESCRIPTION
**Pull request by kamilogorek**
Changes in https://github.com/denoland/deno/pull/17719 made all `read_file` methods return `ErrorData::Custom` instead of the original `ErrorData::Os`.
This is correct and unified behavior, however problematic at the same time, as `get_io_error_code` is not implemented for all possible `ErrorKind` variants.

In order to work around this, the newly created error is wrapped in `anyhow::Error` and the original `std::io::Error` is provided as its context. This makes a downcasting in `get_error_code` successful and allows `get_os_error_code` to be used for code extraction instead of problematic `get_io_error_code`.

File in question: https://github.com/denoland/deno/blob/main/core/error_codes.rs

It also changes error format from (`err, desc` to `err: desc`).

```

Error: Is a directory (os error 21), readfile 'test'
Error: Is a directory (os error 21): readfile 'test'


NotFound: No such file or directory (os error 2), readfile 'tes'
NotFound: No such file or directory (os error 2): readfile 'tes'
```

Note that on Windows, `EISDIR` is reported as `ENOENT` due to Deno using libuv mappings (Windows code for this is `267`) - https://github.com/libuv/libuv/blob/master/src/win/error.c

Fixes https://github.com/denoland/deno/issues/17950

### CODE REVIEW

**Review by aapoalas — APPROVED** [review]
LGTM, but needs rebase.

**Comment by kamilogorek** [comment]
Done. All green!

**Comment by aapoalas** [comment]
Thank you once again, and nice work!

**Comment by bartlomieju** [comment]
@aapoalas please land at first convenience

**Pull request merged**
