### PR TITLE
chore(tests): enable `upgrade_tests` again

### PR DESCRIPTION
**Pull request by GJZwiers**
Closes https://github.com/denoland/deno/issues/7412

These tests would sometimes throw an `ExecutableFileBusy` error, most likely due to parallel `std::fs::copy` calls of the same file. This is an attempt to fix the issue by switching to `std::fs::hard_link`.

### CODE REVIEW

**Review by aapoalas — APPROVED** [review]
LGTM. Let's hope this indeed does fix the flakiness.

**Comment by GJZwiers** [comment]
Looks like they are still flaky after all

**Comment by aapoalas** [comment]
Yup :(

**Comment by GJZwiers** [comment]
@aapoalas @bartlomieju The `upgrade_with_out_in_tmpdir` test seems to have broken in https://github.com/denoland/deno/commit/0742ea1170239b7d010e219b3349b2f9edaaefe5 (which was not caught because it is ignored on main) rather than it being flaky, because locally it fails consistently for me from that commit onwards but not before that.

**Comment by GJZwiers** [comment]
@bartlomieju I am getting test failures after pulling the latest main branch but only on Windows. Was anything changed to the CI recently?

```
thread 'integration::upgrade::upgrade_with_version_in_tmpdir' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 17, kind: CrossesDevices, message: "The system cannot move the file to a different disk drive." }', cli\tests\integration\upgrade_tests.rs:51:56
```

**Pull request closed without merging**
