### PR TITLE
fix(std/wasi): return flags from fd_fdstat_get

### PR DESCRIPTION
**Pull request by caspervonb**
This tracks fdflags from opened file descriptors and returns the tracked value in fd_stat_get.

### CODE REVIEW

**Comment by bartlomieju** [comment]
@caspervonb can we get a test exercising this change?

**Comment by caspervonb** [comment]
> @caspervonb can we get a test exercising this change?

Blocking-on #7042

**Comment by caspervonb** [comment]
Turns out there was a off by one error here too 😉

**Comment by caspervonb** [comment]
This should be good to merge @bartlomieju

**Pull request merged**
