### PR TITLE
chore: deprecate npm itests

### PR DESCRIPTION
**Pull request by MohammadSu1**
chore: Deprecate npm itests
This PR is part of solving #22907 
The npm_tests.rs file was deprecated in this PR, and most of the tests were moved under specs/npm_tests.

### CODE REVIEW

**Comment by MohammadSu1** [comment]
@dsherret Can you please review this PR?

**Review by dsherret — COMMENTED** [review]
Thanks! I think a lot of these files can now be deleted from the testdata folder though? It might have been good to move them instead of copy.

**Comment by MohammadSu1** [comment]
Of course, I missed deleting them. I will fix that and re-push the changes asap.

**Review by dsherret — APPROVED** [review]
Great. Thanks again!

**Pull request merged**
