### PR TITLE
feat(node:os) add availableParallelism

### PR DESCRIPTION
**Pull request by ruihe774**
Add `os.availableParallelism()`, which is introduced in Node.js v19.4.0 and v18.14.0.
It just wraps `navigator.hardwareConcurrency`.

### CODE REVIEW

**Comment by littledivy** [comment]
As the API states, it is not the same as the number of logical cores i.e `navigator. hardwareConcurrency`:

https://nodejs.org/api/os.html#oscpus

> os.cpus().length should not be used to calculate the amount of parallelism available to an application. Use [os.availableParallelism()](https://nodejs.org/api/os.html#osavailableparallelism) for this purpose.

**Comment by ruihe774** [comment]
> As the API states, it is not the same as the number of logical cores i.e `navigator.hardwareConcurrency`:
> 
> https://nodejs.org/api/os.html#oscpus
> 
> > os.cpus().length should not be used to calculate the amount of parallelism available to an application. Use [os.availableParallelism()](https://nodejs.org/api/os.html#osavailableparallelism) for this purpose.

@littledivy Yes. But `navigator.hardwareConcurrency` is not logical cores -- it has already considered available concurrency. I've tested it with cpu affinity masks.

**Comment by littledivy** [comment]
IIRC In Deno, navigator.hardwardConcurrency is simply the core count: https://github.com/denoland/deno/pull/11448

**Comment by littledivy** [comment]
Oh my bad, it does account for available cores: https://docs.rs/num_cpus/latest/num_cpus/fn.get.html

**Review by littledivy — APPROVED** [review]
LGTM

**Comment by ruihe774** [comment]
> Oh my bad, it does account for available cores: https://docs.rs/num_cpus/latest/num_cpus/fn.get.html

BTW, `available_parallelism` is in Rust std. Why we need a crate?

**Comment by littledivy** [comment]
Yeah, It was stabalised recently in rustc 1.59.0. We can get rid of numcpus now.

**Comment by ruihe774** [comment]
> Yeah, It was stabalised recently in rustc 1.59.0. We can get rid of numcpus now.

I'd like to do it in this PR.

**Pull request merged**
