### PR TITLE
Add hyper

### PR DESCRIPTION
**Pull request by thgh**
This makes implementing #416 and `window.fetch` a fair bit easier.

### CODE REVIEW

**Comment by NewLunarFire** [comment]
I was in the process of adding hyper using rustls as a crypto backend. You could add hyper-rustls and rustls dependencies as well and I could build on it for remote code fetching. (Adding those dependencies one-by-one is long and repetitive)

**Comment by thgh** [comment]
Just added some more dependencies 😛 I thought I would be able to implement fetch, but there are too many errors...

Good luck @NewLunarFire !

**Comment by NewLunarFire** [comment]
Ok I'll do my best. I'll rebase on your branch and take it from here. Thanks @thgh

**Comment by ry** [comment]
@thgh Thanks for doing this! We're waiting on windows support for #434... So it will be another day or so before I can land this. Thanks for your patience.

(And yes, I do think we want to use rustls instead of native-tls - to avoid further runtime dependencies. Thanks for adding that too.)

**Comment by ry** [comment]
closed in favor of #477

**Pull request closed without merging**
