### PR TITLE
chore: workspace inheritance

### PR DESCRIPTION
**Pull request by crowlKats**
This PR switches to use [workspace inheritance](https://blog.rust-lang.org/2022/09/22/Rust-1.64.0.html#cargo-improvements-workspace-inheritance-and-multi-target-builds). 
I only set inheritable deps to be ones that are used multiple times.

### CODE REVIEW

**Review by dsherret — CHANGES_REQUESTED** [review]
We'll need to make this work with the [release scripts](https://github.com/denoland/deno/tree/main/tools/release) before landing.

**Comment by dsherret** [comment]
Let's hood off on this until after the 1.28 release

**Comment by bartlomieju** [comment]
> Let's hold off on this until after the 1.28 release. One less thing to deal with as this might break the release scripts.

I agree, just wanted to touch base on this one as it seems to simplify quite a lot

**Review by dsherret — APPROVED** [review]
LGTM! This is a very nice improvement.

**Pull request merged**
