### PR TITLE
feat: add std/http/bodyparser,  issue#3500

### PR DESCRIPTION
**Pull request by chenshenhai**
https://github.com/denoland/deno/issues/3500

add the std mod `std/http/bodyparser.ts`  that parsing  POST-request-body

### CODE REVIEW

**Comment by ry** [comment]
Does this match Go's http server API? I don't have the time to research it right now - but the code should be ported directly from Go.

**Comment by chenshenhai** [comment]
> Does this match Go's http server API? I don't have the time to research it right now - but the code should be ported directly from Go.

No, it doesn't match Go's http server API,  and it's based on Deno and deno_std API.

**Comment by chenshenhai** [comment]
> Does this match Go's http server API? I don't have the time to research it right now - but the code should be ported directly from Go.

the usage is: 

```js
enum FormFieldType {
  text = "text",
  file = "file"
}

/** FormFieldData object */
interface FormFieldData {
  /** input-type */
  type: FormFieldType; // text, file
  /** input-name */
  name: string;
  /** input-value, the value of input, the value is Uint8Array if input-type="file" */
  value: Uint8Array | string;

  /** input-filename, input-filetype, if there is input-file in the form  */
  filename?: string;
  filetype?: string;
}


class BodyParser {
  constructor(contentType: string, body: Uint8Array) {
     // ...
  }
} 

const parser = new BodyParser("multipart/form-data",  [.....])
const formData: FormFieldData[] = await parser.getFormData();


```

**Comment by ry** [comment]
@chenshenhai thanks - your api looks good but I want to research how Go does this. I’ll get back to you in a couple days.

**Comment by kitsonk** [comment]
@ry, my understanding is that it isn't part of the standard library.  All body parsing is left up to the users in Go.  There are some frameworks or libraries for Go.

Personally feels like it is a higher order "framework" concern, versus a standard library thing, as you need to understand content types and choose to support similar body types.  This is the equivalent functionality in oak, for example: https://github.com/oakserver/oak/blob/master/request.ts#L148-L186

**Comment by ry** [comment]
So we have a multipart parser here https://github.com/denoland/deno/blob/master/std/mime/multipart.ts

I also saw this: https://github.com/denoland/deno/tree/master/std/multipart but I will remove it now.

**Comment by chenshenhai** [comment]
@ry  Oh!  Does the standard library of deno need the http-body parsers in deno official understanding?

**Comment by ry** [comment]
@chenshenhai Hey sorry for the slow response. Parsing form data is certainly within scope of std. I'm not sure how it would fit into the HTTP server as an API, but it should certainly use the existing multipart module. 
I'm closing this one because it's stale and there's problems.

**Comment by chenshenhai** [comment]
> @chenshenhai Hey sorry for the slow response. Parsing form data is certainly within scope of std. I'm not sure how it would fit into the HTTP server as an API, but it should certainly use the existing multipart module.
> I'm closing this one because it's stale and there's problems.

OK!

**Pull request closed without merging**
