### PR TITLE
chore: remove stale bot

### PR DESCRIPTION
**Pull request by bartlomieju**

### CODE REVIEW

**Comment by iuioiua** [comment]
Did you mean *stale* bot?

**Comment by ry** [comment]
Not useful?

**Comment by bartlomieju** [comment]
> Not useful?

Not useful, usually I have to reopen half of the closed issues anyway and most users are complaining about it.

**Review by littledivy — APPROVED** [review]

**Comment by iuioiua** [comment]
Related:
- denoland/deno_std#2860

**Pull request merged**
