### PR TITLE
Add unit tests for Timers

### PR DESCRIPTION
**Pull request by haoxli**
For #497

### CODE REVIEW

**Comment by hayd** [comment]
I just tested the original test file from #497 and it's still non-deterministic:

```
const timers = [];
let timeouts = 0;

for (let i = 0; i < 10; i++) {
  timers[i] = setTimeout(onTimeout, 20);
}

function onTimeout() {
  ++timeouts;
  for (let i = 1; i < 10; i++) {
    clearTimeout(timers[i]);
  }
}

setTimeout(function() { console.log(timeouts); }, 100);
```

Running:
```
$ ./out/debug/deno bar.ts
2
$ ./out/debug/deno bar.ts
2
$ ./out/debug/deno bar.ts
1
```

**Comment by haoxli** [comment]
@hayd `timers[i] = setTimeout(onTimeout, 20);` => `timers[i] = setTimeout(onTimeout, 20*i);`  make sure the second setTimeout is cleared before it run.

**Comment by hayd** [comment]
But that is a different test to #497 :)

**Comment by haoxli** [comment]
I think this test is designed to coverage the code path in `js/timers.ts` (from #434), not the performance, so the delay is changeable. Am I misunderstood?

**Comment by ry** [comment]
@piscisaureus please review

**Comment by ry** [comment]
@haoxli We have a new timer implementation that will be landed (hopefully) this week. At that point I will come back and try to use some of these tests. I think they're useful and I appreciate. But for now I want to clear out the old PR and this one will not be mergeable until the new timers implementation lands. Sorry for the delay. To be continued...

**Pull request closed without merging**
