### PR TITLE
fix(console): support NO_COLOR and colors option in all scenarios

### PR DESCRIPTION
**Pull request by crowlKats**
Noticed in #21607

### CODE REVIEW

**Review by dsherret — APPROVED** [review]
LGTM

**Comment by nicolo-ribaudo** [comment]
@crowlKats If you could fix this PR and make CI green, I can then rebase mine :)

**Comment by crowlKats** [comment]
@nicolo-ribaudo yep, will do though it requires some more work, will try to get it done today.
just for info: the remaining issue with this PR is I need to normalize escape sequences, as test assertions are having issues on different systems due to the escape sequences having different syntax.

**Review by dsherret — APPROVED** [review]
LGTM

**Pull request merged**
