### PR TITLE
Add a link to the Discord server to the Readme

### PR DESCRIPTION
**Pull request by YodaLightsabr**
Add Discord to Readme

- Does not change any code
- Related to #9712

### CODE REVIEW

**Comment by YodaLightsabr** [comment]
Why are the checks failing I didn't change any of the code.

**Comment by crowlKats** [comment]
The checks failing are formatting related. you need to run `tools/format.js`

**Review by kitsonk — APPROVED** [review]
LGTM

**Comment by kitsonk** [comment]
I've fixed the formatting... once CI passes I will merge this one and we can stop people submitting 6 PRs trying to add this without reading the contribution guidelines for the repository.

**Pull request merged**
