### PR TITLE
fix(cli): allow for specifying `noErrorTruncation` compiler option

### PR DESCRIPTION
**Pull request by kamilogorek**
> Seems reasonable to allow this.
— @dsherret 

Fixes https://github.com/denoland/deno/issues/16568

### CODE REVIEW

**Comment by dsherret** [comment]
Opened https://github.com/denoland/manual/pull/502

**Review by dsherret — CHANGES_REQUESTED** [review]
I've categorize this as a fix since this is mainly used for debugging and so that it will be in the next patch release.

We also need to update https://github.com/denoland/deno/blob/main/cli/schemas/config-file.v1.json for this change and also could you add an integration test to ensure it works and doesn't regress in the future (in `cli/tests/check_tests.rs)? I'm not sure what conditions would cause this to appear so maybe it would be too much of a hassle... in which case, don't bother.

**Comment by kamilogorek** [comment]
Schema updated, test added. Thanks for the pointers!

**Review by dsherret — APPROVED** [review]
Awesome. Thanks!

**Pull request merged**
