### PR TITLE
tests: add more jsxImportSource regression tests

### LINKED ISSUE #13389: `deno bundle` fails to resolve react/jsx-runtime
I'm seeing an issue with this when trying to do `deno bundle` with `react/jsx-runtime`, created repro here with description of error: https://github.com/pheuter/hello-deno#blocking-issue.

Currently unable to bundle client-side code using `react/jsx-runtime` despite `deno run` working just fine using the same code and config:

```
» deno bundle --config deno.json client/index.tsx static/client.js
Check file:///Users/mark/src/pheuter/hello-deno/client/index.tsx
Bundle file:///Users/mark/src/pheuter/hello-deno/client/index.tsx
error: Unable to output during bundling.

Caused by:
    0: load_transformed failed
    1: failed to analyze module
    2: failed to resolve https://esm.sh/react@17.0.2/jsx-runtime from file:///Users/mark/src/pheuter/hello-deno/client/index.tsx
    3: Cannot resolve "https://esm.sh/react@17.0.2/jsx-runtime" from "file:///Users/mark/src/pheuter/hello-deno/client/index.tsx".
```

```sh
» deno --version
deno 1.17.3 (release, aarch64-apple-darwin)
v8 9.7.106.15
typescript 4.5.2
```

Oddly enough, the issue appears to go away when I explicitly do `/** @jsxImportSource https://esm.sh/react@17.0.2 */` in every tsx file, which I'm trying to avoid with this optimization in the first place.

### LINKED ISSUE #14723: `deno check` appears to require `@jsxImportSource` pragma with `"jsx": "react-jsx"` in configuration
I've tested this on v1.21.2 and v1.22.0, both on macOS. Minimal example. Create these files an empty directory:

```
$ cat compile.jsonc
{
  "compilerOptions": {
    "allowJs": true,
    "lib": ["DOM", "ES2020"],
    "strict": true,
    "jsx": "react-jsx",
    "jsxImportSource": "foo"
  }
}
$ cat im.json
{ "imports": { "foo/jsx-runtime": "./jsx-runtime.ts" } }
$ cat test.tsx
/** @jsxImportSource foo */
export const makeParagraph = () => <p>A paragraph!</p>;
$ cat test2.tsx
export const makeParagraph = () => <p>A paragraph!</p>;
$ cat jsx-runtime.ts
export namespace JSX {
  export type IntrinsicElements = { [key: string]: unknown };
}
```

This call succeeds:

```
$ deno check test.tsx -c compile.jsonc --importmap=im.json
```

But this one doesn't:

```
$ deno check test2.tsx -c compile.jsonc --importmap=im.json
Check file:///Users/cscheid/Desktop/daily-log/2022/05/25/tsx-deno/test2.tsx
error: TS7026 [ERROR]: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
export const makeParagraph = () => <p>A paragraph!</p>;
                                   ~~~
    at file:///Users/cscheid/Desktop/daily-log/2022/05/25/tsx-deno/test2.tsx:1:36

TS7026 [ERROR]: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
export const makeParagraph = () => <p>A paragraph!</p>;
                                                  ~~~~
    at file:///Users/cscheid/Desktop/daily-log/2022/05/25/tsx-deno/test2.tsx:1:51

Found 2 errors.
```

It seems that `jsxImportSource` is not getting honored by some part of the code, even though `deno check` itself fails if I don't add `jsImportSource` to `compile.jsonc`. 

Strangely, if I use a "bad" value in either of those _two_ fields (say, replacing `foo` with `bar` in either the .jsonc or the pragma), `deno check` fails.

### PR DESCRIPTION
**Pull request by lucacasonato**
This commit adds some regression tests for using `jsxImportSource` in
the config file in combination with an import map.

These underlying issues were fixed by #15561.

Closes #13389
Closes #14723

### CODE REVIEW

**Review by kitsonk — APPROVED** [review]
LGTM

**Review by dsherret — APPROVED** [review]
LGTM too.

**Comment by aapoalas** [comment]
There's some newline issue with the bundle test and apparently the GitHub file editor automatically injects a newline even if you manually delete it (good for them!).

That being said, bundle is deprecated anyway so maybe that test should be deleted? I would like to land this PR otherwise.

**Comment by lucacasonato** [comment]
This should still be merged.

**Pull request merged**
