### PR TITLE
fix(task): allow hyphen values after task name

### PR DESCRIPTION
**Pull request by dsherret**
See https://github.com/denoland/deno/pull/14419#issuecomment-1113127332

### CODE REVIEW

**Review by bartlomieju — APPROVED** [review]
LGTM

**Comment by jsejcksn** [comment]
@dsherret Referring to [the comment](https://github.com/denoland/deno/pull/14419#issuecomment-1113127332) you linked:

With this change, I expect the commands from 2 and 5 to produce the same result (the result from 2), and for the commands from 3 and 7 to produce the same result (the result from 3). Is that the case?

**Comment by dsherret** [comment]
@jsejcksn it does for 2, 3, and 7, but I missed 5. Opened #14436. Thanks!

**Review by jsejcksn — COMMENTED** [review]
Thanks!

**Pull request merged**
