### PR TITLE
Update to rustc 1.31.0 and rust 2018

### PR DESCRIPTION
**Pull request by hayd**
`cargo check` succeeds, but `tools/build.py` [errors out](https://gist.github.com/hayd/4772d5d53cd60219a7c98e139ae6b0de).

### CODE REVIEW

**Comment by ry** [comment]
Cool! But let's wait until #1296 is done.

**Comment by hayd** [comment]
Now `cargo build` succeeds, but tools/build.py errors out. 😄 
Is build.py setting the rust version somehow?

**Comment by hayd** [comment]
It seems like the final stage for this PR is to add `args += ["--edition=2018"]` in [rust.gni](https://github.com/denoland/deno/blob/master/build_extra/rust/rust.gni#L172) BUT only on the deno executable not every crate (since not every crate is edition=2018). Any gn tips for this?

**Comment by hayd** [comment]
Passing an edition flag in gn seems to do the job here, see last commit.

**Comment by hayd** [comment]
RE appveyor fail, I'm not sure how to update rustc... cc @piscisaureus

**Comment by hayd** [comment]
I guess I'll try a few changes to the "rustc exists" appveyor check https://github.com/denoland/deno/pull/1306/files#diff-11c909939117928998b102a1fff7d363L302

I want it to be something like:
```diff
- if (-not (Test-Path $env:CARGO_HOME)) {
+ if (-not $(rustc --version | grep 1.31.0)) {
```

**Comment by hayd** [comment]
I'm not sure what to pass to appveyor in order to bump the version.

Happy to rebase if anyone works out what to put there, or we can bump to 1.31 in another PR then apply rust-2018.

**Comment by ry** [comment]
@hayd I'm just closing old PRs. We'd like to upgrade still, of course, but this isn't green. Happy to have a new PR in this direction.

**Comment by hayd** [comment]
@ry yep, this isn't green because I can't bump the rustc version to 1.31 on appveyor.
Once that is updated this is good to go, but it can be another PR.

**Pull request closed without merging**
