### PR TITLE
perf: use deno_native_certs crate

### LINKED ISSUE #18071: lazily load Security framework on macOS
- [ ] rustls_native_certs
dlopen drop-in-replacement crate: https://github.com/denoland/deno_native_certs 
- [x] ring 0.16.20
Newer unreleased ring has switched to `getrandom` that does not depend on Security.framework. So we just wait for a new release.

### LINKED ISSUE #20996: Zero macOS framework dependencies
Action items:

- [x] lazy load Security.framework #18071 
  - [x] #20824 
  - [x] #18072 
- [x] replace all chrono::Utc::now() usage with `cli::time::utc_now()`. 
  - [x] #18088 
  - [x] https://github.com/denoland/deno/pull/20995
- [x] update `nextest/quick-junit` to not use Chrono's "clock" feature. 
  - [x] https://github.com/nextest-rs/nextest/pull/1073
  - [x] https://github.com/denoland/deno/pull/21004
- [x] https://github.com/denoland/deno/pull/21027
- [ ] https://github.com/denoland/deno/pull/21028
  ```toml
  # Note: Do not use the "macos_fsevent" feature of notify, as it links us to CoreFoundation on macOS.
  notify = { version = "=5.0.0", default-features = false, features = ["macos_kqueue"] }
  ```

### PR DESCRIPTION
**Pull request by littledivy**
Fixes #18071
Fixes #20996 

Replace `rustls_native_certs` which links to Security framework. https://github.com/denoland/deno_native_certs uses dlopen to lazy load when needed.

### CODE REVIEW

**Comment by bartlomieju** [comment]
Is there any noticable startup performance difference with this PR?

**Comment by littledivy** [comment]
No difference, this itself isn't enough to get rid of Security framework. See #18071

**Review by bartlomieju — CHANGES_REQUESTED** [review]
I'm wary of landing this PR unless we can show end-to-end improvement in startup time.

**Comment by littledivy** [comment]
```
target/debug/deno:
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1953.255.0)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 1228.0.0)
	/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration (compatibility version 1.0.0, current version 1241.60.3)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.0.0)
```

SecurityFramework gone :-)

**Review by bartlomieju — APPROVED** [review]

**Pull request merged**
