### PR TITLE
fix(ext/node): implement "ascii" encoding for node:fs writeFile()

### LINKED ISSUE #18078: Implement "ascii" encoding for node:fs writeFile() polyfill
Not sure if this still belongs in the `deno_std` issue tracker now that node polyfills have been embedded in the Deno binary. Feel free to move if so.

I'd like to use [`npm:@poki/cli`](https://www.npmjs.com/package/@poki/cli) but it throws `Not implemented: "ascii" encoding`.
Not sure if this is easy to reproduce because you need a developer account to use the poki cli, but the error I get seems clear enough:

```
error: Uncaught Error: Not implemented: "ascii" encoding
    at notImplemented (internal:deno_node/polyfills/_utils.ts:7:11)
    at checkEncoding (internal:deno_node/polyfills/_fs/_fs_common.ts:40:9)
    at Object.writeFileSync (internal:deno_node/polyfills/_fs/_fs_writeFile.ts:60:22)
    at IncomingMessageForClient.<anonymous> (file:///home/jesper/.cache/deno/npm/registry.npmjs.org/@poki/cli/0.1.12/bin/index.js:185:44)
    at IncomingMessageForClient.emit (internal:deno_node/polyfills/_events.mjs:379:28)
    at Ea (internal:deno_node/polyfills/_stream.mjs:12:43461)
    at processTicksAndRejections (internal:deno_node/polyfills/_next_tick.ts:31:29)
```

### PR DESCRIPTION
**Pull request by Farsen976**
Closes #18078

### CODE REVIEW

**Review by ry — COMMENTED** [review]
Are there any tests that can be enabled?

**Comment by Farsen976** [comment]
> Are there any tests that can be enabled?

Hello, 
from my side, none of these tests can be enabled, 😕  Am I missing something ?

**Comment by kt3k** [comment]
Sorry toolings for updating node compat test cases are not yet ready in this repository. ref. https://github.com/denoland/deno/issues/18185

@Farsen976 Can you add a test case in `cli/tests/unit_node`, which tests `fs.writeFile` call with `ascii` encoding?

**Comment by Farsen976** [comment]
> Sorry toolings for updating node compat test cases are not yet ready in this repository. ref. #18185
> 
> @Farsen976 Can you add a test case in `cli/tests/unit_node`, which tests `fs.writeFile` call with `ascii` encoding?

@kt3k tests added

**Review by kt3k — APPROVED** [review]
LGTM. Thanks! @Farsen976

**Pull request merged**
