### PR TITLE
feat: log out which files changed on HMR or watch change

### PR DESCRIPTION
**Pull request by HasanAlrimawi**
This PR addresses issue #25504 

**Changes**
When using `--watch` or `--watch-hmr` with `deno serve`, and when using `deno run --watch` then on any file specified changed, logs will be shown indicating what files changed in a numbered manner.

PS: deno run `--watch-hmr` already shows if the script being executed was changed.

Screenshot to show the change:
image

### CODE REVIEW

**Comment by HasanAlrimawi** [comment]
@marvinhagemeister 
Can you give it a look if you have time please?

**Comment by marvinhagemeister** [comment]
Thanks for tackling this. The output already looks better than what we have today.

I noticed that when you change a single file and the HMR is applied successfully (like changing the body of a function), then the output looks like this:

```sh
HMR Replaced changed module file:///Users/marvinh/dev/test/deno-hmr/a.ts
```
Screenshot 2024-09-23 at 15 09 41

I like that it's compact and only takes up one line. The output logged by the changes in this PR always take up at least 3 lines.

```sh
HMR File change detected! Restarting!
Files Changed:
1: "/Users/marvinh/dev/test/deno-hmr/main.ts"
```

How do you feel about making it more compact? Maybe something like this:

```sh
# For single file updates
HMR Restarting! File changes detected: "/Users/marvinh/dev/test/deno-hmr/main.ts"

# For multiple file updates
HMR Restarting! File changes detected:
- "/Users/marvinh/dev/test/deno-hmr/main.ts"
- "/Users/marvinh/dev/test/deno-hmr/b.ts"
```

**Comment by bartlomieju** [comment]
I'm not really convinced that one can receive "multiple file change". We're restarting on every change and these changes are received one-by-one. I'd encourage to keep single line output and if multifile change happens only use the first one.

**Comment by HasanAlrimawi** [comment]
@marvinhagemeister 
Could you please take a look at the recent changes?

**Comment by bartlomieju** [comment]
@HasanAlrimawi thanks for the PR, we'll land it for Deno 2.1.

**Review by bartlomieju — APPROVED** [review]
Thanks!

**Pull request merged**
