### PR TITLE
feat(fmt): stabilize CSS, HTML and YAML formatters

### PR DESCRIPTION
**Pull request by bartlomieju**
This commits stabilizes CSS, HTML and YAML formatters
in `deno fmt`.

It is no longer required to use either of these flags:
- `--unstable-css`
- `--unstable-html`
- `--unstable-yaml`
Or these `unstable` options in the config file:
- `fmt-css`
- `fmt-html`
- `html-yaml`

### CODE REVIEW

**Comment by bartlomieju** [comment]
CC @g-plane

**Comment by g-plane** [comment]
I'm going to release a new version of markup_fmt tonight which fixes some issues of formatting HTML and components, so please wait for it.

**Comment by bartlomieju** [comment]
Note to self: add tests that check ignore comments before landing

**Review by dsherret — APPROVED** [review]
LGTM

**Pull request merged**
