### PR TITLE
feat(cli): enable --unstable-hmr and --watch to work with stdin

### PR DESCRIPTION
**Pull request by linde12**
Allow --unstable-hmr and --watch to work with stdin

Closes https://github.com/denoland/deno/issues/21069

### CODE REVIEW

**Comment by bartlomieju** [comment]
> It makes no sense to run --watch or --unstable-hmr and then pass - (stdin) as SCRIPT_ARG.

I don't agree, we should still allow HMR in this case - it will only be files that are imported that will be watched. Any chance you could rework the PR to handle this scenario?

**Comment by linde12** [comment]
@bartlomieju i have submitted a commit but as i am new to the code i would like some feedback if this is the right approach or if you had something different in mind before i continue

**Comment by bartlomieju** [comment]
Sorry for a slow reply. I will review this PR tonight.

**Comment by linde12** [comment]
> Sorry for a slow reply. I will review this PR tonight.

No worries at all, just wanna know if i'm on the right track and your thoughts about my earlier comment before i continue! 👍

**Review by bartlomieju — COMMENTED** [review]
Overall this looks good - unfortunately now we have some duplication going on. Let me think a bit more how we could unify both code paths - besides adding a dummy file for `stdin` there are no differences between the two.

**Comment by linde12** [comment]
@bartlomieju Great!

Exactly, they're pretty all three very similar. `run_from_stdin` could probably be merged into `run_script` (and it could check whether file is stdin or not), but then there is still the duplication between `run_script` and `run_with_watch`

**Comment by linde12** [comment]
@bartlomieju i added a fixup commit where i broke some of the duplication out into its own function - if you feel its worth it i will squash it into 622888ebbeb9e9088eb1085e47937a89456b3d5c

**Comment by linde12** [comment]
Not sure why `run_watch_stdin` is failing on windows but not linux. Don't have access to a windows machine atm, but if anyone is able to test then `cargo test watcher::run_watch_stdin -- --nocapture` should do it

**Comment by bartlomieju** [comment]
Thanks and sorry for a slow response. I can spin up my Windows machine to see what's going on

**Comment by linde12** [comment]
@bartlomieju we want to close this or how should we proceed?

**Pull request closed without merging**
