### PR TITLE
fix: align DOMException API to the spec and add web platform testing of it.

### PR DESCRIPTION
**Pull request by kt3k**
It is part of #9001.

This PR adds web platform testing of DOMException API and align our implementation to pass it.

### CODE REVIEW

**Comment by kt3k** [comment]
This passes WPT suites, but an uncaught DOMException doesn't show the stack trace now. I'm investigating the handling of uncaught error in `/core`.

**Comment by kt3k** [comment]
Restored the original behavior when thrown as uncaught error, but as a result I have to skip the case `"does not inherit from Error: class-side"` which I don't know how to pass for now.

Now it's ready for review.

**Review by ry — APPROVED** [review]
LGTM

**Comment by kt3k** [comment]
Thank you for your review!

**Pull request merged**
