### PR TITLE
[WIP] refactor(cli): improve SWC parse error

### PR DESCRIPTION
**Pull request by bartlomieju**
Closes https://github.com/denoland/deno/issues/8529

Blocked by upgrade of `deno_doc`, `deno_lint` and `dprint_plugin_typescript` (need to update `swc_common` dep in those crates)

### CODE REVIEW

**Comment by bartlomieju** [comment]
@kdy1 I've managed to rewrite handler to use single `ErrorBuffer`, unfortunately the output is not so great:
```
error: error: Unexpected token `}`. Expected an identifier, void, yield, null, await, break, a string literal, a numeric literal, true, false, `, -, import, this, typeof, {, [, (
Error:  --> <file:///home/runner/work/deno/deno/cli/tests/swc_syntax_error.ts>:4:1
  |
4 | }
  | ^



```
Notice "error" being repeated 3 times (the first one comes from Deno, as it's terminal error, the remaining two seem to come from SWC) as well as multiple newlines after the error. I'm not sure if we should land it after all, @kitsonk thoughts?

**Comment by kdy1** [comment]
@bartlomieju  I'm not sure if `Error` comes from swc.
I looked at the error reporting test of swc, but https://github.com/swc-project/swc/blob/faa1c5f4e5d956bc062542b42d123d42b31776eb/ecmascript/parser/tests/typescript-errors/arrow-function/async-rest-optional-parameter/input.ts.stderr does not contain `Error:`

**Comment by bartlomieju** [comment]
@kdy1 thanks, I will dig deeper then...

**Comment by kdy1** [comment]
I'll see if enabling `tty-emitter` removes the `Error`. If then, it should be bug of `swc_common`.

**Comment by kdy1** [comment]
I tried `cargo test swc` (without `tty-emitter`) after doing `gh pr checkout 8534`, and I got

```
error: error: Unexpected token `}`. Expected an identifier, void, yield, null, await, break, a string literal, a numeric literal, true, false, `, -, import, this, typeof, {, [, (
 --> <file:///Users/kdy1/projects/deno/cli/tests/swc_syntax_error.ts>:4:1
  |
4 | }
  | ^

```

I got this using mac os.

It seems like looking for `cfg(target_os = "linux")` or usage of threads in deno test would be the key.

**Pull request closed without merging**
