### PR TITLE
Update V8 to 7.0.247

### PR DESCRIPTION
**Pull request by ameerthehacker**

### CODE REVIEW

**Comment by ry** [comment]
Thanks @ameerthehacker 
```
Author: ameerthehacker <ameerjhanprof@gmail.com>
Date:   Thu Aug 23 04:35:59 2018 +0530

    Update V8 to 7.0.247
```
Could you please put your actual name in the commit log?

**Comment by ameerthehacker** [comment]
@ry I have changed the commit log to my original name. Hope so!

**Comment by ry** [comment]
Thanks - please update third_party to point to the 20180823_v8 branch.

**Comment by ameerthehacker** [comment]
Sure i will @ ry

**Comment by ameerthehacker** [comment]
Hey @ry I have added the **branch** option in the **.gitmodules** file so that it points to the branch you specified!

**Comment by ameerthehacker** [comment]
@piscisaureus I'm little confused over here. Can you please throw some more light into this. How can I make the deno repo to track the branch 20180823_v8 of the deno_third_party repo in denoland. If I try to update the branch it actually updates the .gitmodule file with a branch paramter assigned with 20180823_v8

**Comment by ry** [comment]
Thanks @ameerthehacker but i'll do the upgrade in #610

**Comment by ameerthehacker** [comment]
Cool @ry

**Pull request closed without merging**
