### PR TITLE
doc: Add reference on how to test deno types changes locally

### PR DESCRIPTION
**Pull request by cknight**
As per title, this PR documents how to run the `./tools/docs.py` to test your deno types changes locally.

### CODE REVIEW

**Comment by kitsonk** [comment]
The manual typically doesn't cover "how to develop Deno itself" which this is related to.  We need another location for those items, IMO, not the end user manual.  The end user has no idea that file exists (nor should they).

**Comment by cknight** [comment]
@kitsonk I very much agree that the contributing to deno section shouldn't be in the end user manual but in it's own home.  However, in the meantime and until such work is undertaken to move the "Contributing" section, I believe this is the correct place for this change, sitting in the "Testing and Tools" sub-section alongside the existing documentation on `./tools/format.py` and `./tools/lint.py` for example.

**Comment by cknight** [comment]
@ry - ready for review

**Comment by cknight** [comment]
@ry - gentle nudge to review.  Should be a quick one.

**Comment by ry** [comment]
I’m in agreement with @kitsonk - these are internal details that we don’t necessarily want to document. (I think I’m the only one who generates the docs)
Maybe this is a better fit for tools/README.md

**Comment by cknight** [comment]
Thanks for the feedback. I'll rework the PR to move this to a new README.md file in tools and link to the README.md from the user manual contributions section.  While you may be the only one who generates the public docs, I've found `docs.py` really useful for checking the formatting output when doing all the updates and has caught a number of issues during my updates.  It seems wrong not to publicise the useful tool for checking doc formatting during development.

**Comment by cknight** [comment]
Documentation on `docs.py` moved to `tools/README.md`.  I've also added notes on `format.py` and `lint.py`.  I'm not familiar enough with the other scrips to document them.

**Comment by cknight** [comment]
@ry This is getting pretty old.  Could you review and merge, or close without merge as appropriate?

**Comment by ry** [comment]
@cknight I think we're going to rip out typedoc support very soon now (since we have https://doc.deno.land/), but we might as well have documentation while it's still around. Thanks and sorry for the delay.

**Pull request merged**
