### PR TITLE
feat(ext/node): add `node:v8` module

### PR DESCRIPTION
**Pull request by littledivy**

### CODE REVIEW

**Comment by MierenManz** [comment]
Not trying to interfere but can I remind people that last time some of the ops in `node:v8` were suggested to be in the public API it got respectfully declined. So why is it now a better idea to do it?

Referencing: https://github.com/denoland/deno/issues/12379

**Comment by littledivy** [comment]
Waiting for ext/node snapshot https://github.com/denoland/deno/pull/17724

**Comment by ry** [comment]
Can we land this?

**Comment by littledivy** [comment]
Closing in favour of https://github.com/denoland/deno/pull/17806

**Pull request closed without merging**
