### PR TITLE
refactor: partially rewrite chown_test to not depend on Python

### PR DESCRIPTION
**Pull request by mrmodise**
Related to #8254

### CODE REVIEW

**Comment by lucacasonato** [comment]
Could you do all of the related changes in one PR? Opening a new PR for each one line change is rather tedious to review :-)

**Comment by mrmodise** [comment]
> Could you do all of the related changes in one PR? Opening a new PR for each one line change is rather tedious to review :-)

Cool. I need help though ;-)

I couldnt find a way to get the gid in Deno


```ts
const gidProc = Deno.run({
    stdout: "piped",
    cmd: ["python", "-c", "import os; print(os.getgid())"],
  });
```

**Comment by lucacasonato** [comment]
@mrmodise I don't think we have a call for `uid` or `gid` at the moment. You are using `Deno.ppid`,  but that is not the same as `os.getuid()`. `ppid` is the parent process ID, and `uid` is the user id.

**Comment by mrmodise** [comment]
> @mrmodise I don't think we have a call for `uid` or `gid` at the moment. You are using `Deno.ppid`, but that is not the same as `os.getuid()`. `ppid` is the parent process ID, and `uid` is the user id.

ah! okay so i can leave this out. I will do the same to few other ones I picked in `process_test.ts`.

**Comment by mrmodise** [comment]
1 last one, how do i run specific tests? I notice `cargo test` run all test suites, whereas my preference would be to run the specific files am working on. Currently, I have to do the heavy-lifting of copying the specific test into `Deno.test()` then `deno test...`

**Comment by bartlomieju** [comment]
@mrmodise take a look at https://github.com/denoland/deno/blob/master/cli/tests/unit/README.md

**Comment by mrmodise** [comment]
> @mrmodise take a look at https://github.com/denoland/deno/blob/master/cli/tests/unit/README.md

I missed it on the README 🤦🏾 . Thanks @bartlomieju

**Comment by bartlomieju** [comment]
@mrmodise thanks for the PR, but I'm gonna close without merge. We need to find "universal" command that will work on all OSes used in CI instead of relying on execution of `deno` binary (similar to https://github.com/denoland/deno/pull/8404)

**Pull request closed without merging**
