### PR TITLE
[WIP] feat(cli/web/fetch): AbortController

### PR DESCRIPTION
**Pull request by marcosc90**
Implement fetch `signal` option so the request can be aborted.

- [x] Cancel before the request begins
- [x] Cancel after the request is done, it closes the body
- [ ] Abort ongoing fetch (need a way to cancel async op)

Since I can't cancel the ongoing `opFetch` I reject `fetch` promise if an abort happens before `opFetch` finishes, it leaks async ops but the API works as expected:

```
 const controller = new AbortController();
 setTimeout(() => controller.abort(), 1000); // abort after 1 second

// Will throw after 1 second, opFetch will continue in the background
 await fetch("http://example.com/sleep/2", { signal: controller.signal }); 
```

`fetch` throws `AbortError` and after 1 second the request will finish in the background

---

I'm still working on some tests

### CODE REVIEW

**Comment by ry** [comment]
> need a way to cancel async op

I don't think we should add a primitive for canceling any async op, because in general it's not possible. One idea is to close the resource associated with the fetch. Another is to add a new cancelation op....

**Comment by kitsonk** [comment]
> One idea is to close the resource associated with the fetch.

That seems the most logical to me.  Leaves up to Rust to do any cleanup that is appropriate, like dropping a connection.

**Comment by marcosc90** [comment]
> One idea is to close the resource associated with the fetch

That's exactly what I was looking for, right now that resource is not exposed in TS, AFAIK. If that's the case, maybe it's a good time to also allow streaming a request body to fetch, I can implement the TS side of streaming in another PR.

https://github.com/denoland/deno/blob/42a04ea08a09e29417518524cbe2245c165e6f55/cli/js/web/fetch.ts#L274-L276

Unfortunately, I don't know any rust to take this task.

**Comment by kevinkassimo** [comment]
I actually had some abort op experimented before, but it was on the old codebase and I am not allowed to submit code anyways recently. But I remember doing something like adding a `Abortable` wrapper around the future on the Rust side resource table that also stores something called `AbortHandle` and `AbortRegistration`. When abort is requested the handle is used to abort the future. If anyone wants to work on the support further it might be a way to try (I would not be able to work on anything until after mid September)

**Comment by mrkurt** [comment]
To really abort a fetch you'd need op_fetch to return a resource for the `request` itself, right? We need pretty tight control over http request deadlines so I'm experimenting with this, but we frequently need to cancel a request before headers are returned.

**Comment by bartlomieju** [comment]
Just a heads up, we're actively working towards making `fetch` a standalone crate, so it might make more sense for this change to wait until the crate is done.

**Comment by kitsonk** [comment]
@marcosc90 really thanks for the effort... I am going to close this without merging because it needs a significant rebase effort to get it to with master and as @bartlomieju said, we are breaking fetch out into its own op crate very very soon.  It would be best to look at this feature once that is done.

**Pull request closed without merging**
