### PR TITLE
feat(ext/fetch) Added RequestMethod type

### PR DESCRIPTION
**Pull request by BoredSathvik**
It is for better suggestions only, does not change anything else

### CODE REVIEW

**Comment by lucacasonato** [comment]
I am not sure. What is the point here?

**Review by lucacasonato — COMMENTED** [review]
`fetch` does not support the `CONNECT` method, so that should definitely not be listed.

**Comment by BoredSathvik** [comment]
> I am not sure. What is the point here?

Just for auto suggest

**Comment by SeparateRecords** [comment]
Does this work in practice? I was under the impression that TS will simplify `"a" | "b" | string` to just `string` — was this changed recently?

To get this to work in one of my projects I had to do `"a" | "b" | (string & {})`, which I don't think is desirable to be built in

**Pull request closed without merging**
