### PR TITLE
feat(websockets): Narrow type of WebSocket message event

### PR DESCRIPTION
**Pull request by rotu**

### CODE REVIEW

**Comment by rotu** [comment]
[ci]

**Review by lucacasonato — COMMENTED** [review]
We should use the same type as lib.dom.d.ts here.

**Comment by rotu** [comment]
> We should use the same type as lib.dom.d.ts here.

That makes sense. Why *aren't* we importing these types from upstream e.g. [`WebSocketEventMap` as declared in TypeScript](https://github.com/microsoft/TypeScript/blob/a0e0104656415b6c6d18c6ba1100ae42157a4f09/src/lib/dom.generated.d.ts#L25328-L25333) or generating from with [TypeScript-DOM-lib-generator](https://github.com/microsoft/TypeScript-DOM-lib-generator)?

**Comment by crowlKats** [comment]
@rotu we use the exact same typings already as upstream TS

**Comment by rotu** [comment]
I think this PR no longer makes sense as of #25545

**Pull request closed without merging**
