### PR TITLE
fix: support missing features in --no-check

### PR DESCRIPTION
**Pull request by bartlomieju**
Fixes https://github.com/denoland/deno/issues/7080

### CODE REVIEW

**Comment by bartlomieju** [comment]
@kitsonk PTAL

**Comment by ry** [comment]
Waiting for Kitson’s review.

Are there any additional tests from Kitson’s branch relating to these no-check fixes?

**Review by kitsonk — COMMENTED** [review]
LGTM outside as @ry mentioned, we should have either integration tests for the new features or unit tests which I had in the branch: https://github.com/kitsonk/deno/blob/deno_compiler/compiler/ast.rs#L796-L846

**Comment by bartlomieju** [comment]
> LGTM outside as @ry mentioned, we should have either integration tests for the new features or unit tests which I had in the branch: https://github.com/kitsonk/deno/blob/deno_compiler/compiler/ast.rs#L796-L846

Thanks, I'll use those 👍

**Review by kitsonk — COMMENTED** [review]
LGTM 👍

**Pull request merged**
