### PR TITLE
fix(cli/test): decoding percent-encoding(non-ASCII) file path correctly

### LINKED ISSUE #10810: Serialize URLs as IRIs in commandline output
When running tests (`deno test`) or throwing errors (`deno run`), URLs are rendered according to the URI syntax, with non‐ASCII characters percent‐encoded. For example, one might see:

    running 8 tests from file:///Users/myUser/Repositories/MyRepo/E%C2%B7C%C2%B7M%C2%B7A%C2%B7262.test.js

when running a test located at `/Users/myUser/Repositories/MyRepo/E·C·M·A·262.test.js`.

This is horribly unreadable and serves very little utility to users. (Imagine programming in a language other than English!) It would be better if the URL was rendered according to the IRI syntax, with only the characters not allowed in IRIs percent‐encoded.

**Version Info:** `deno 1.10.2 (release, x86_64-apple-darwin)`

### PR DESCRIPTION
**Pull request by Hajime-san**
# Summary

This PR resolves about the issue.
fixes #10810

And the formerly context is in the PR. 
#22582

Here is an expected behaviour example with this change.

- 🦕.test.ts
```ts
import { assertEquals } from "https://deno.land/std@0.215.0/assert/mod.ts";

Deno.test("example test", () => {
  assertEquals("🍋", "🦕");
});
```

- terminal

```bash
% /path/to/deno test <0001f995>.test.ts
Check file:///path/to/repo/🦕.test.ts
running 1 test from ./🦕.test.ts
example test ... FAILED (3ms)

 ERRORS 

example test => ./🦕.test.ts:3:6
error: AssertionError: Values are not equal.


    [Diff] Actual / Expected


-   🍋
+   🦕


  throw new AssertionError(message);
        ^
    at assertEquals (https://deno.land/std@0.215.0/assert/assert_equals.ts:52:9)
    at file:///path/to/repo/%F0%9F%A6%95.test.ts:4:3

 FAILURES 

example test => ./🦕.test.ts:3:6

FAILED | 0 passed | 1 failed (29ms)

error: Test failed
```

## related issues

There are test reporter and runtime problems.
#18983

# How we handle runtime behaviour?

The terminal output log not only contains the test reporter but also runtime file path treatment as follows.
`at file:///path/to/repo/%F0%9F%A6%95.test.ts:4:3`

## spec

It seems that there is no specification for `Error.stack` today, and it is implementation-defined behaviour by browser engines.
(Thanks for the [article](https://zenn.dev/pixiv/articles/bb123b2f50cdab), @petamoriken)

- https://github.com/tc39/proposal-error-stacks

## behaviour

Here is an example code to show stack trace, and runs it on modern browsers.

- index.html

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script type="module" src="./🍋.js"></script>
</head>
<body>
</body>
</html>
```

- 🍋.js

```js
throw new Error('🍋')
```

#### Google Chrome(122.0.6261.112)

```log
🍋.js:2 Uncaught Error: 🍋
    at 🍋.js:2:7
(anonymous) @ 🍋.js:2
```

I think that the stack trace implementation is located as follows.

- https://source.chromium.org/chromium/chromium/src/+/refs/tags/122.0.6261.112:v8/src/inspector/v8-stack-trace-impl.cc;l=351-367

#### Firefox(117.0)

```log
Uncaught Error: 🍋
    <anonymous> http://localhost:8080/🍋.js:1
```

#### Safari(17.3.1)

```log
Error: 🍋
module code - 🍋.js:2
```

#### Node.js(20.12.0)

```log
% node 🍋.mjs         
file:///path/to/%F0%9F%8D%8B.mjs:1
throw new Error('🍋')
      ^

Error: 🍋
    at file:///path/to/%F0%9F%8D%8B.mjs:1:7
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12)
```

## deno implementation context

https://github.com/denoland/deno/blob/92a8ada7194ac013f8c34824f435f09b1f52ca5b/runtime/fmt_errors.rs#L37
https://github.com/denoland/deno_core/blob/5c3d303a6de112bb704620d8ba5956acf4e10a48/core/error.rs#L658

### CODE REVIEW

**Comment by bartlomieju** [comment]
Thanks for the PR @Hajime-san! It looks good, but it would be really great if you could exercise this change in an integration test. Would you be able to add a test to `tests/integrations/test_tests.rs` using the `itest!` macro?

**Comment by Hajime-san** [comment]
Hi @bartlomieju, thank you for pointing out about testing. I added it!
And, I found the lack of percent-encoding(non-ASCII) file path for checking types in running test when I was adding the integration test, so I commit it.

**Review by bartlomieju — APPROVED** [review]
Thanks!

**Comment by Hajime-san** [comment]
Thank you! @bartlomieju

BTW, how do you think to treat runtime behaviour that I wrote to [the description of this PR](https://github.com/denoland/deno/pull/23200#issue-2222469787)?
I'm not familiar with the behavior of the v8 engine, but it may affect runtime performance.
If you and the core team have something to think about, I'd like to move this into an issue.

**Comment by bartlomieju** [comment]
> Thank you! @bartlomieju
> 
> BTW, how do you think to treat runtime behaviour that I wrote to [the description of this PR](https://github.com/denoland/deno/pull/23200#issue-2222469787)? I'm not familiar with the behavior of the v8 engine, but it may affect runtime performance. If you and the core team have something to think about, I'd like to move this into an issue.

Sorry for a slow response. As a rule of thumb if something works in browsers and makes sense in Deno context we should follow browser behavior. So this is a good fix 👍

**Comment by bartlomieju** [comment]
@Hajime-san looks like GH actions doesn't like that we now have a file that contains an emoji. Any chance you could rewrite the test to create this file, run relevant subcommand and then delete the file?

**Comment by Hajime-san** [comment]
@bartlomieju 

> Sorry for a slow response. As a rule of thumb if something works in browsers and makes sense in Deno context we should follow browser behavior. So this is a good fix 👍

Sure! I moved to `deno_core` https://github.com/denoland/deno_core/issues/757

> looks like GH actions doesn't like that we now have a file that contains an emoji. Any chance you could rewrite the test to create this file, run relevant subcommand and then delete the file (or use a temp dir)?

I fixed it! e6941d2 It seems to pass all CI.

**Pull request merged**
