### PR TITLE
complain when `fetch` is called without --allow-net

### LINKED ISSUE #596: Fetch should require --allow-net
Calls to fetch should require --allow-net to be passed to deno.

### PR DESCRIPTION
**Pull request by IanS5**
Fixes #596

When fetch is called without `--allow-net` set, deno responds with `FetchRes`, with error set to "allow_net is off"

### CODE REVIEW

**Comment by NewLunarFire** [comment]
A lot of code that shouldn't be modified shows up in the changelog. Did you run tools/format.py? Did you change it to help yourself read the code?

**Comment by IanS5** [comment]
I ran `tools/format.py` after I made my changes. I think those lines were longer than 80 characters so it split them

**Comment by IanS5** [comment]
Anyway, just reverted back to the old formatting. Sorry about that.

**Comment by ry** [comment]
Fixed in #685. Thanks @IanS5 - even tho we didn't use this I think it provided a good reference.

**Pull request closed without merging**
