### PR TITLE
Declare globals explicitly in lib.deno_runtime.d.ts

### LINKED ISSUE #2888: Non-standard namespaces other than Deno declared in lib.deno_runtime.d.ts
As you can see, `lib.deno_runtime.d.ts` publicly declares namespaces `domTypes`, `blob`, `consoleTypes`, `event`, `customEvent`, `eventTarget`, `io`, `fetchTypes`, `textEncoding`, `timers`, `urlSearchParams`, `url`, `workers`, and `performanceUtil` which should all be internal.

You can't declare them as variables in typescript - `let url;` throws during compilation:
```
error TS2451: Cannot redeclare block-scoped variable 'url'.

► $asset$/lib.deno_runtime.d.ts:2514:19

2514 declare namespace url {
                       ~~~

  'url' was also declared here.
...
```

### PR DESCRIPTION
**Pull request by nayeemrmn**
Fixes #2888.

I added `export {};` (see comment and https://github.com/Microsoft/TypeScript/issues/19545). Everything global is in a `declare global {}` block.

@ry Not sure how I'd test this.

### CODE REVIEW

**Comment by kitsonk** [comment]
Can we hold off on this, until we restore the automatic library generation?  See #2868.

Library files should not be UMD `.d.ts` files.  They need to follow the pattern of other library files.  I understand the problem, and we can address it as part of #2868, which is that we need better names for some of the namespaces we have to avoid unintentional userland collisions.

**Comment by nayeemrmn** [comment]
@kitsonk Makes sense, I agree in that case.

>  we need better names for some of the namespaces we have to avoid unintentional userland collisions.

As far as I can tell, these namespaces only hold local aliases used to specify the actual global stuff above. Are you sure there's no way to to properly internalise them? If not, could they all go in `Deno`, like a `Deno.internal` namespace or something? That way we keep our compatibility. https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html#preventing-name-conflicts

**Comment by nayeemrmn** [comment]
@ry Can you merge https://github.com/denoland/deno/pull/2889/commits/7b333d7bd48745863140d23fc0aa3cd59f418fc2 on its own? That's going to bug me.

**Comment by kitsonk** [comment]
@nayeemrmn yeah, that might be possible too...  It had crossed my mind, but I dismissed it, but it actually makes sense that both functional code and types specific to Deno exist in the `Deno` namespace.

**Pull request closed without merging**
