### PR TITLE
ci: auto-clean cargo cache

### PR DESCRIPTION
**Pull request by ry**
https://github.com/matthiaskrgr/cargo-cache

### CODE REVIEW

**Comment by piscisaureus** [comment]
Do you have any numbers to share that show how this makes CI better?

**Review by piscisaureus — APPROVED** [review]
LGTM, some stats would be appreciated

**Comment by ry** [comment]
Results are not good so far. On 6e38fb9 ("after") I get

| build                     | before  | after   |
|---------------------------|---------|---------|
| test_release macos-10.15  | 1350 MB | 1582 MB |
| test_release windows-2019 | 1708 MB | 1708 MB |
| bench ubuntu-latest-xl    | 1563 MB | 1563 MB |
| lint ubuntu-latest        | 1012 MB | 1012 MB |
| test_debug ubuntu-latest  | "       | "       |
| test_release ubuntu-18.04 | 1582 MB | 1582 MB |

**Comment by ry** [comment]
This shows no improvemenet.

**Pull request closed without merging**
