### PR TITLE
Fixes #2033, shared queue push bug

### LINKED ISSUE #2033: Uncaught Error: Expecting promise in table. 0
## env
- OS: macOS 10.14.3
- deno: v0.3.5

## description

```
$ deno -A https://deno.land/std/http/http_bench.ts
```

```
$ wrk -t12 -c400 -d30s http://127.0.0.1:4500
```

got 

```
Uncaught Error: Expecting promise in table. 0
    at assert (js/util.ts:28:11)
    at handleAsyncMsgFromRust (js/dispatch.ts:16:3)
    at handleAsyncMsgFromRust (shared_queue.js:117:9)
```
`cmdId` on [here](https://github.com/denoland/deno/blob/master/js/dispatch.ts#L14) get 0. I tried to set `let nextCmdId = 1` and got the same error. Maybe `handleAsyncMsgFromRust` had been called with invalid argument.

### PR DESCRIPTION
**Pull request by ry**

### CODE REVIEW

**Comment by ry** [comment]
master branch
```
  "req_per_sec": {
    "node": 31770, 
    "deno_core_single": 74917, 
    "hyper": 99012, 
    "deno_core_multi": 78296, 
    "deno_net_http": 17691, 
    "deno": 44438, 
    "node_tcp": 73330
  }, 
  "max_latency": {
    "node": 8.47, 
    "deno_core_single": 8.22, 
    "hyper": 1000.0, 
    "deno_core_multi": 6.83, 
    "deno_net_http": 7.13, 
    "deno": 12.83, 
    "node_tcp": 8.65
  }, 
```

@keroxp's original patch
```
  "req_per_sec": {
    "node": 31658, 
    "deno_core_single": 69064, 
    "hyper": 90390, 
    "deno_core_multi": 74903, 
    "deno_net_http": 17603, 
    "deno": 42531, 
    "node_tcp": 73079
  }, 
  "max_latency": {
    "node": 11.82, 
    "deno_core_single": 9.92, 
    "hyper": 746.68, 
    "deno_core_multi": 8.18, 
    "deno_net_http": 7.25, 
    "deno": 12.24, 
    "node_tcp": 11.48
  }, 
```

this branch:
```
  "req_per_sec": {
    "node": 31795, 
    "deno_core_single": 74600, 
    "hyper": 96806, 
    "deno_core_multi": 78863, 
    "deno_net_http": 17186, 
    "deno": 44598, 
    "node_tcp": 70990
  }, 
  "max_latency": {
    "node": 10.74, 
    "deno_core_single": 8.96, 
    "hyper": 78.68, 
    "deno_core_multi": 8.14, 
    "deno_net_http": 7.0, 
    "deno": 11.86, 
    "node_tcp": 8.14
  }, 
```

**Comment by keroxp** [comment]
@ry https://github.com/denoland/deno/blob/master/core/shared_queue.js#L72 you may misses checking on js side?

**Comment by ry** [comment]
@keroxp I believe I fixed that now. PTAL

**Comment by keroxp** [comment]
@ry I tried using this branch for running std's http bench as #2156 and go same results. Can you check https://deno.land/std/http/http_bench.ts with this branch?

**Comment by keroxp** [comment]
I think `debug!` might not affect the result.

**Comment by ry** [comment]
@keroxp here is this branch (running `./target/release/deno -A https://deno.land/std/http/http_bench.ts`)
```
> wrk -d 10 http://localhost:4500/
Running 10s test @ http://localhost:4500/
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   683.39us  359.08us   9.48ms   94.58%
    Req/Sec     7.58k     0.88k    8.81k    90.59%
  152310 requests in 10.10s, 7.26MB read
Requests/sec:  15080.05
Transfer/sec:    736.33KB
```
and here is master branch
```
> wrk -d 10 http://localhost:4500/
Running 10s test @ http://localhost:4500/
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   702.47us  616.28us  18.67ms   95.87%
    Req/Sec     7.54k     1.02k    9.40k    86.63%
  151495 requests in 10.10s, 7.22MB read
Requests/sec:  14998.30
Transfer/sec:    732.34KB
```
So seems ok. I will put back in your `debug!()` calls before landing

**Pull request merged**
