### PR TITLE
third_party: add rust crates 'headers' and 'mime'

### PR DESCRIPTION
**Pull request by piscisaureus**
cc @bokuweb

### CODE REVIEW

**Comment by bokuweb** [comment]
@piscisaureus Thanks 👍 BTW Now other members can not add crate?

**Comment by piscisaureus** [comment]
> BTW Now other members can not add crate?

What do you mean?

**Comment by bokuweb** [comment]
Can I add crate by myself? (If so, where is the method written?) If not, should I ask you or @ry to add crate?

**Comment by bokuweb** [comment]
@piscisaureus Thanks for your information 👍  I'll check it 😄

**Comment by bokuweb** [comment]
Related #1453 

@ry @piscisaureus I tried to add `headers` crate like following. However I met some errors.
I guess we need to build `typenum` to generate `consts.rs` by ` typenum-1.10.0/build/main.rs`.
Unfortunately I don't know how to build it... Do you have any information to solve it??

```
rust_executable("hyper_hello") {
  source_root = "tools/hyper_hello.rs"
  extern = [
    "$rust_build:hyper",
    "$rust_build:ring",
    "$rust_build:tokio_fs",
    "$rust_build:tokio_io",
    "$rust_build:futures",
    "$rust_build:mime",
    "$rust_build:headers",
  ]
}
```

### error message

```
tools/build.py
ninja: Entering directory `/Users/bokuweb/ghq/github.com/bokuweb/deno/target/debug'
[1/1] Regenerating ninja files
[1/28] ACTION //build_extra/rust:typenum_rustc(//build/toolchain/mac:clang_x64)
FAILED: rust_crates/libtypenum.rlib 
python ../../build_extra/rust/run.py /Users/bokuweb/ghq/github.com/bokuweb/deno/prebuilt/mac/sccache rustc ../../third_party/rust_crates/registry/src/github.com-1ecc6299db9ec823/typenum-1.10.0/src/lib.rs --crate-name=typenum --crate-type=rlib --emit=link,dep-info --edition=2015 --out-dir=rust_crates -Cextra-filename= -Cmetadata=\"_rustc\ 1.31.1\ \(b6c32da9b\ 2018-12-18\)\" -L dependency=rust_crates --color=always -g -Dwarnings --cap-lints allow
error: environment variable `OUT_DIR` not defined
  --> ../../third_party/rust_crates/registry/src/github.com-1ecc6299db9ec823/typenum-1.10.0/src/lib.rs:61:18
   |
61 | include!(concat!(env!("OUT_DIR"), "/consts.rs"));
   |                  ^^^^^^^^^^^^^^^

error: couldn't read ../../third_party/rust_crates/registry/src/github.com-1ecc6299db9ec823/typenum-1.10.0/src/0/consts.rs: No such file or directory (os error 2)
  --> ../../third_party/rust_crates/registry/src/github.com-1ecc6299db9ec823/typenum-1.10.0/src/lib.rs:61:1
   |
61 | include!(concat!(env!("OUT_DIR"), "/consts.rs"));
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 2 previous errors
```

**Comment by piscisaureus** [comment]
@bokuweb 
We don't currently have a solution for that unfortunately. OUT_DIR is an environment variable that's set by cargo, but it seems that gn/ninja don't support passing environment variables.

Two weeks ago I was able to build `headers` without any problems though, so maybe you can get by with using a slightly older version?

**Comment by piscisaureus** [comment]
As for consts.rs, it seems that the generated file is always the same, so we could just add that to the third_party repo.
That said, I still don't have a great solution for the environment variable
Maybe we can invoke rustc through some python wrapper (`tools/rustc_wrapper.py`), and make that set OUT_DIR?

**Comment by bokuweb** [comment]
@piscisaureus I see. Thanks for your reply and information :) Ok, I'll try some approach 👍

**Comment by bokuweb** [comment]
Hmm, I built `typenum` then added `consts.rs` and  `OUT_DIR` for now. However I met another error...

```
ninja: Entering directory `/Users/bokuweb/ghq/github.com/bokuweb/deno/target/debug'
[1/1] Regenerating ninja files
[9/27] ACTION //build_extra/rust:syn_rustc(//build/toolchain/mac:clang_x64)
FAILED: rust_crates/libsyn.rlib 
python ../../build_extra/rust/run.py /Users/bokuweb/ghq/github.com/bokuweb/deno/prebuilt/mac/sccache rustc ../../third_party/rust_crates/registry/src/github.com-1ecc6299db9ec823/syn-0.15.26/src/lib.rs --crate-name=syn --crate-type=rlib --emit=link,dep-info --edition=2015 --out-dir=rust_crates -Cextra-filename= -Cmetadata=\"_rustc\ 1.32.0\ \(9fda7c223\ 2019-01-16\)\" -L dependency=rust_crates --color=always -g -Dwarnings --cap-lints allow --cfg feature=\"clone-impls\" --cfg feature=\"default\" --cfg feature=\"derive\" --cfg feature=\"extra-traits\" --cfg feature=\"parsing\" --cfg feature=\"printing\" --cfg feature=\"proc-macro\" --cfg feature=\"proc-macro2\" --cfg feature=\"quote\" --cfg feature=\"visit\" --extern proc_macro2=rust_crates/libproc_macro2.rlib --extern quote=rust_crates/libquote.rlib --extern unicode_xid=rust_crates/libunicode_xid.rlib
error[E0277]: the trait bound `proc_macro2::TokenStream: std::convert::From<proc_macro::TokenStream>` is not satisfied
   --> ../../third_party/rust_crates/registry/src/github.com-1ecc6299db9ec823/syn-0.15.26/src/buffer.rs:109:27
    |
109 |         Self::new2(stream.into())
    |                           ^^^^ the trait `std::convert::From<proc_macro::TokenStream>` is not implemented for `proc_macro2::TokenStream`
    |
    = note: required because of the requirements on the impl of `std::convert::Into<proc_macro2::TokenStream>` for `proc_macro::TokenStream`

error[E0308]: mismatched types
    --> ../../third_party/rust_crates/registry/src/github.com-1ecc6299db9ec823/syn-0.15.26/src/parse.rs:1069:52
     |
1069 |         self.parse2(proc_macro2::TokenStream::from(tokens))
     |                                                    ^^^^^^ expected struct `proc_macro2::TokenStream`, found struct `proc_macro::TokenStream`
     |
     = note: expected type `proc_macro2::TokenStream`
                found type `proc_macro::TokenStream`

error: aborting due to 2 previous errors

Some errors occurred: E0277, E0308.
For more information about an error, try `rustc --explain E0277`.
[11/27] ACTION //:test_rs_bin_rustc(//build/toolchain/mac:clang_x64)
ninja: build stopped: subcommand failed.
```

**Pull request closed without merging**
