### PR TITLE
fix(ext/node): surface Deno permission errors for process.env

### PR DESCRIPTION
**Pull request by itsajay1029**
Fixed remove Deno permissions for Env variables. Fixed Issue #18665

### CODE REVIEW

**Comment by kt3k** [comment]
@ry @bartlomieju We now have `A` option (Allow all same kind permissions, in this case all 'env') in permission prompt. I think removing this check is now reasonable. What do you think?

**Comment by itsajay1029** [comment]
@kt3k Please merge the PR

**Comment by bartlomieju** [comment]
@kt3k I'll review this week, need to better understand problem at hand

**Comment by kt3k** [comment]
@bartlomieju More context. We wanted to reduce the number of env permission prompts in node compat (invoked from `process.env[NAME]`) in the past because, for example, `npm:express` asks excessive number of envs (like ~10, and most are somethings nobody cares about) and it was very annoying. We started checking permission before actually calling `Deno.env.get` in https://github.com/denoland/deno_std/pull/3178, and only access to it when permission is already given. That resulted in another issue such as #18665

**Comment by dsherret** [comment]
@itsajay1029 thanks! I think this is a good change to do. The CI is pointing out that some tests are now failing due to this change though. Would you be able to fix them? Once those tests are fixed then we'll be able to land this.

**Comment by dsherret** [comment]
@itsajay1029 are you still wanting to contribute this one? There are some tests failures that just need to be fixed. I can take it over if not. It's unfortunate this one didn't get in the 1.40 release so it will have to land in 1.41 now.

**Comment by dsherret** [comment]
I'll take over this PR to get it landed today.

**Comment by dsherret** [comment]
Oh wait, just noticed https://github.com/denoland/deno/pull/22487 opened

**Review by dsherret — APPROVED** [review]
LGTM

**Comment by dsherret** [comment]
This was superceeded by the approach in #22487 to permission prompt, but not throw.

**Pull request closed without merging**
