### PR TITLE
fix(ext/http): avoid lockup in graceful shutdown

### PR DESCRIPTION
**Pull request by mmastrac**
Follow-up to #20822. cc @lrowe 

The `httpServerExplicitResourceManagement` tests were randomly failing on CI because of a race.

The `drain` waker was missing wakeup events if the listeners shut down after the last HTTP response finished. If we lost the race (rare), the server Rc would be dropped and we wouldn't poll it again.

This replaces the drain waker system with a signalling Rc that always resolves when the refcount is about to become 1.

Fix verified by running serve tests in a loop:

```
for i in {0..100}; do cargo run --features=__http_tracing -- test
 -A --unstable '/Users/matt/Documents/github/deno/deno/cli/tests/unit/ser
ve_test.ts' --filter httpServerExplicitResourceManagement; done;
```

### CODE REVIEW

**Comment by lrowe** [comment]
This looks a neat solution.

**Comment by mmastrac** [comment]
Waiting to land this until I get the benchmark bot fixed.

**Review by bartlomieju — APPROVED** [review]
LGTM

**Pull request merged**
