### PR TITLE
Remove xeval subcommand

### PR DESCRIPTION
**Pull request by ry**
I'm removing this ahead of 1.0 because it's too specialized. I would be happy to reintroduce this as std/examples/xeval.ts or something similar.

cc @kevinkassimo

### CODE REVIEW

**Comment by piscisaureus** [comment]
For posterity: I think that running a script specified from stdin *is* a useful feature.
However xeval has too much xeval-specific semantics which I don't like. So for that reason I agree with the removal of it.

**Comment by kevinkassimo** [comment]
Did not review in time but thumbs up for removal.

**Comment by stefanbuck** [comment]
`xeval` got me interested in Deno after watching [Rayn's talk](https://www.youtube.com/watch?v=HjdJzNoT_qg). I always struggle using `xargs` `grep` `sed` and I thought that `xeval` will become my new super power 😉Maybe it will come back in another form 🤞

**Comment by kevinkassimo** [comment]
Maybe we could bring back `xeval` to `std/examples`. I did not realize it was completely removed from `std` also...

**Pull request merged**
