### PR TITLE
BREAKING(std/hash): remove legacy hash modules

### PR DESCRIPTION
**Pull request by caspervonb**
This removes the undocumented(at-least in the README) legacy hash modules that predate the WebAssembly in std/hash.

Closes https://github.com/denoland/deno/issues/6672

### CODE REVIEW

**Comment by kitsonk** [comment]
There is a lot of code in the wild that depends on those.  The predated and we never deprecated them.  For example it would break oak: https://github.com/oakserver/oak/blob/main/deps.ts#L8.  I will look at migrating it, but it will cause a huge amount of carnage.  If we want to get rid of them, we really need to give people a heads up (and not implement duplicate APIs in `std` in the first place).

Is there no logical way provide those APIs but change the implementation?

**Comment by kitsonk** [comment]
(Also this doesn't at all address the concerns I originally raised in #6672, is simply drops the APIs 😞 )

**Comment by caspervonb** [comment]
> Is there no logical way provide those APIs but change the implementation?

We can stub out the constructors, or generate them as individual classes all depending on what we want the API to look like. We don't have to just export a single function from WASM it can be a set of classes.

> (Also this doesn't at all address the concerns I originally raised in #6672, is simply drops the APIs 😞 )

I'm expecting this one to sit for quite a bit since it's quite the change so I'll bring in HMAC support for the WebAssembly version in a standalone pull-request.

**Comment by caspervonb** [comment]
I'll draft this for the time being, look at it again after 1.4

**Comment by kitsonk** [comment]
Yes. The HMAC is "critical" the rest of the API is up for debate. Also we should find a way to deprecate the existing APIs for a period of time.

**Comment by caspervonb** [comment]
Blocking on #7297

**Comment by caspervonb** [comment]
> Yes. The HMAC is "critical" the rest of the API is up for debate. Also we should find a way to deprecate the existing APIs for a period of time.

Splitting this out into separate issues for tracking.

**Comment by bartlomieju** [comment]
@caspervonb pointed out that this PR would solve problem described in https://github.com/denoland/deno/issues/7739

We should move forward with this PR.

**Comment by caspervonb** [comment]
Closing, there's a WIP of WebCrypto. Lets review in std-wg once we get to hash.

**Pull request closed without merging**
