### PR TITLE
feat(ext/flash): add `reuseport` option on Linux

### LINKED ISSUE #15719: flash: enable `SO_REUSEPORT`

### PR DESCRIPTION
**Pull request by littledivy**
Sets `SO_REUSEPORT` on Linux. MacOS and Windows is a nop.

Closes #15719

### CODE REVIEW

**Review by bartlomieju — COMMENTED** [review]
That option is missing in type defintion. Consider using `reusePort`

**Review by lucacasonato — COMMENTED** [review]
Missing d.ts changes. Can you rename `reuseport` to `reusePort`?

**Review by lucacasonato — APPROVED** [review]
LGTM

**Comment by lucacasonato** [comment]
We should also add support to `Deno.listen` and `Deno.listenTls`.

**Pull request merged**
