### PR TITLE
fix(workspace): support wildcard packages

### PR DESCRIPTION
**Pull request by bartlomieju**
This commit adds support for wildcard packages in `workspace`
configuration option in `deno.json`. This is now supported:
```
{
  "workspace": [
    "./packages/*"
  ]
}
```

Closes https://github.com/denoland/deno/issues/25783

### CODE REVIEW

**Comment by bartlomieju** [comment]
This probably doesn't solve the linked issue.

```
$ git clone git@github.com:histoire-dev/histoire.git
$ cd histoire
# migrate pnpm-workspace.yaml to deno.json
$ cat deno.json
{
    "workspace": [
        "packages/*",
        "examples/*",
        "docs"
    ]
}
$ ../deno/target/debug/deno install --allow-scripts
Warning The following packages are deprecated:
┠─ npm:rimraf@3.0.2 (Rimraf versions prior to v4 are no longer supported)
┠─ npm:glob@7.2.3 (Glob versions prior to v9 are no longer supported)
┖─ npm:inflight@1.0.6 (This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.)
$ cd examples/vue2
$ ../../../deno/target/debug/deno install --allow-scripts
error: Config file must be a member of the workspace.
  Config: file:///Users/ib/dev/histoire/examples/vue2/package.json
  Workspace: file:///Users/ib/dev/histoire/
```
It appears the current change doesn't cover a mixes deno/npm members.

@dsherret could you advise?

**Comment by dsherret** [comment]
Can you add a failing test to this pr to demonstrate what you mean?

**Comment by dsherret** [comment]
Or actually, adding one to deno_config would be better.

**Comment by bartlomieju** [comment]
@dsherret sure, opened a PR with a test here: https://github.com/denoland/deno_config/pull/132

**Review by dsherret — APPROVED** [review]
LGTM.

To save on CI time you may want to consider deleting the test in favour of the one in deno_config (maybe)

**Comment by bartlomieju** [comment]
> To save on CI time you may want to consider deleting the test in favour of the one in deno_config (maybe)

I prefer to have end-to-end test for execution.

**Pull request merged**
