### PR TITLE
Remove unstable native plugins

### LINKED ISSUE #8490: Remove unstable native plugins
Opening this issue to start discussion on potential removal of native plugins.

Native plugins are an unstable feature that hasn't seen much adoption; partially
due to lack of documentation and partially due to shortcomings of plugin interface.

Currently there's one major problem that prevents from using plugins in the same
way to use "ops" in Deno; namely code loaded from dynamic library cannot obtain
proper handle to current thread which renders Tokio unusable from the plugins (#7990).

Moreover the plugin system adds some complexity to Deno's op interface and brakes 
the security promises of Deno (because we can't control what's going on in dynamically
loaded library).

Therefore I propose to completely remove native plugin interface in the next 
minor release, revisit this topic after Deno 2.0, and in the meantime encourage 
users to use WASM modules instead. I am aware that some of use cases for 
plugins are not achievable using WASM (eg. using webview), but for that 
purpose we're working on providing Rust "scaffold" for projects that want to 
integrate deeply with Deno. 

Related issues and PRs:
- #7990
- #7030
- #5478
- #4222
- #3598
- #7031
- #5721

CC @ry @piscisaureus @eliassjogreen @manyuanrong @andreespirela

### PR DESCRIPTION
**Pull request by bartlomieju**
Closes #8490

### CODE REVIEW

**Review by wperron — APPROVED** [review]

**Comment by wperron** [comment]
Seems like a substantial change (even if the API was under the unstable flag) I think we should include it in the upcoming 1.12 release instead of the next patch release for 1.11

**Comment by rracariu** [comment]
Is there any replacement in the works/planed?

**Comment by eliassjogreen** [comment]
Would a pr adding classic C ffi support (`dlopen`, `dlsym`, `dlerror`, `dlclose`) be welcome or should i wait for deno 2.0? Removing plugin support also removes the possibility to do native calls which is a thing which can be very useful for everything from webview support, native windowing for WebGPU, fast cpu optimized code and lots of other cool things. I think removing plugins would put deno at a disadvantage in many use cases to node and the napi.

**Comment by bartlomieju** [comment]
> Is there any replacement in the works/planed?

Yes, FFI API proposed in #11152

**Review by ry — CHANGES_REQUESTED** [review]
Let's discuss with @piscisaureus

**Review by ry — APPROVED** [review]
LGTM

We will land FFI soon after.

**Pull request merged**
