### PR TITLE
feat(cli): add `--unstable-node-globals` flag

### PR DESCRIPTION
**Pull request by marvinhagemeister**
This PR adds a new `--unstable-node-globals` flag to expose Node globals by default.

Fixes https://github.com/denoland/deno/issues/26611

### CODE REVIEW

**Comment by bartlomieju** [comment]
Let's update hints added in https://github.com/denoland/deno/pull/26610 to mention this flag.

**Review by bartlomieju — CHANGES_REQUESTED** [review]
Marking as "request changes" to update hints for terminal errors on Node.js globals

**Review by bartlomieju — APPROVED** [review]
LGTM

**Comment by birkskyum** [comment]
I can't really figure if it's related, but I"m trying out the flag here, is it supposed to fix this "document" not defined, or is there something additional I should do?

```
error: ReferenceError: document is not defined
      container: document.createElement("div"),
```

I have in my deno.json

```
    "lib": [
      "deno.window",
      "dom"
    ]
    ```

**Comment by redradist** [comment]
With this PR it looks like a global variable `process`, could be hidden behind this flag, see https://github.com/denoland/deno/issues/26549

**Pull request merged**
