### PR TITLE
fix: [std/testing] move assert() into util/assert.ts

### LINKED ISSUE #3933: gist bundle size tripled after #3927
#3927

### PR DESCRIPTION
**Pull request by keroxp**
- fixes #3933
- Split `assert()` and `AssertionError` into `util/assert.ts` from `testing/asserts.ts`
- assert() now has more use cases than testing matcher. It is imported from many non-test files. 
- At first I tried to port assert into Deno namespace for #4090  but found that assertion function can't be destructured and assigned to variable without explicit type annotation.

```ts
const { assert } = Deno;
assert(1); // Error
const assert2 = Deno.assert;
assert2(1); // Error
const assert3: (expr) => asserts expr = Deno.assert;
assert3(1); //OK
Deno.assert(1); //OK
```
- Actually this is not convenient for every usage.
- The most cheap solution is expose `assert()` into global scope maybe. Of course, that is not part of web standard.

### CODE REVIEW

**Comment by bartlomieju** [comment]
> At first I tried to port assert into Deno namespace for #4090 but found that assertion function can't be destructured and assigned to variable without explicit type annotation.

```ts
const { assert } = Deno;
assert(1); // Error
const assert2 = Deno.assert;
assert2(1); // Error
const assert3: (expr) => asserts expr = Deno.assert;
assert3(1); //OK
Deno.assert(1); //OK
```

@keroxp do you have a reproduction for this? Sounds very strange

**Comment by keroxp** [comment]
@bartlomieju  Try this:

```ts
type Asserter = {
  assert(expr: unknown): asserts expr;
}
const asserter: Asserter = {
  assert(expr: unknown): asserts expr {
    if (!expr) throw new Error()
  }
}

const {assert: assert1} = asserter;
assert1(1);
const assert2 = asserter.assert;
assert2(2);
const assert3: (u: unknown) => asserts u = asserter.assert;
assert3(3);
asserter.assert(4);
```

```
error TS2775: Assertions require every name in the call target to be declared with an explicit type annotation.

► file:///Users/keroxp/src/deno/assert.ts:11:1

11 assert1(1);
   ~~~~~~~

  'assert1' needs an explicit type annotation.

    ► file:///Users/keroxp/src/deno/assert.ts:10:16

    10 const {assert: assert1} = asserter;
                      ~~~~~~~


error TS2775: Assertions require every name in the call target to be declared with an explicit type annotation.

► file:///Users/keroxp/src/deno/assert.ts:13:1

13 assert2(2);
   ~~~~~~~

  'assert2' needs an explicit type annotation.

    ► file:///Users/keroxp/src/deno/assert.ts:12:7

    12 const assert2 = asserter.assert;
             ~~~~~~~



Found 2 errors.
```

This is TypeScript's limitation for asserts function. Bit a strange indeed.

**Comment by bartlomieju** [comment]
@kitsonk can you take a look and advise?

**Comment by kitsonk** [comment]
🤷‍♂ opened https://github.com/microsoft/TypeScript/issues/37818.  It doesn't make any sense to me, but the error is there for a reason, just the reason isn't obvious, and even then I think it was potentially just because it was "easier" on the compiler to determine, without predicting someone would try something like we are doing.

Personally, I would be fine with `assert()` in the global namespace.  While it isn't in browsers, it is in Node.js.

**Comment by keroxp** [comment]
@ry How do you think?

**Comment by keroxp** [comment]
Close because too outdated. Next time, I'll try to add assert() in global scope.

**Pull request closed without merging**
