### PR TITLE
fix: add missing `Object.groupBy()` and `Map.groupBy()` types

### PR DESCRIPTION
**Pull request by iuioiua**
These methods were added in Deno 1.37. However, TypeScript hasn't published the types.

Related https://github.com/denoland/deno_std/pull/3663

### CODE REVIEW

**Review by dsherret — CHANGES_REQUESTED** [review]
It would be good to add a test for this or these declarations will easily disappear in the next typescript upgrade.

Example: https://github.com/denoland/deno/pull/21048/files#diff-0ee3a1e1043b12767ecc1e32c661cddda23e46b55a7737d0e2c8e186fcf4071c

**Comment by iuioiua** [comment]
Thanks! Done. What's the cause of this linting failure?

**Comment by dsherret** [comment]
It's a build failure. I think the new file needs to be added here: https://github.com/denoland/deno/blob/ab72019a17ccc077384c37eaeae15fffc9ce4d92/cli/build.rs#L182

**Review by dsherret — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
