### PR TITLE
chore: fix `wpt_epoch` workflow

### LINKED ISSUE #22257: [WPT] actions workflow wpt_epoch.yml is failing
[Since Jan 26 2024 this workflow is failing](https://github.com/denoland/deno/actions/workflows/wpt_epoch.yml) and results are no longer submitted to wpt.fyi for aligned comparisons.

### PR DESCRIPTION
**Pull request by iuioiua**
Should fix #22257

### CODE REVIEW

**Review by mmastrac — APPROVED** [review]
LGTM

**Comment by mmastrac** [comment]
Does this fix need to update the suite submodule?

**Comment by iuioiua** [comment]
No, it doesn't. Bartek wanted it included in this PR.

**Comment by iuioiua** [comment]
On 2nd thought, I've omitted the WPT submodule upgrade to finish the fix sooner. We can upgrade in a follow-up PR.

**Pull request merged**
