### PR TITLE
fix(test): capture inherited stdout and stderr for subprocesses in test output

### PR DESCRIPTION
**Pull request by dsherret**
Waiting on #14393 first

### CODE REVIEW

**Comment by bartlomieju** [comment]
Looks like it's almost working, I spotted that some outputs are not enclosed between the markers:
Screenshot 2022-04-26 at 14 27 52

**Comment by dsherret** [comment]
@bartlomieju weird. It works for me
image

Also, it's strange that the caret is so high up for you. I will try on linux.

**Comment by bartlomieju** [comment]
It works locally for me too:
Screenshot 2022-04-26 at 15 47 32

One more test that looks broken:
Screenshot 2022-04-26 at 15 48 01

**Review by bartlomieju — APPROVED** [review]
LGTM, unless you want to address the issue with workers in this PR as well.

**Comment by dsherret** [comment]
Yeah, I'm going to do it in a separate PR. I haven't found a nice way of doing it yet.

**Pull request merged**
