### PR TITLE
fix(cli/tools/repl): do not panic when inspect throws

### PR DESCRIPTION
**Pull request by caspervonb**
Fixes https://github.com/denoland/deno/issues/11257

### CODE REVIEW

**Comment by bartlomieju** [comment]
Can we get a test case?

**Comment by caspervonb** [comment]
> Can we get a test case?

Not entirely sure what webidl does here to make it throw in the first place 🤔 
`Deno.inspect` shouldn't actually ever throw under _normal_ circumstances as we avoid inspecting getters and such.

**Comment by bartlomieju** [comment]
I believe tests are failing because you got a rogue checkout of `wpt/`

**Review by bartlomieju — APPROVED** [review]
LGTM thanks

**Pull request merged**
