### PR TITLE
Add ignore fn to deno test

### PR DESCRIPTION
**Pull request by calebmchenry**
Addresses `Deno.test.ignore` feature request of #5197 

**Known issues**
Currently the inline docs for .ignore are the same as .test. This means the examples use `Deno.test` instead of `Deno.test.ignore`. Not sure what the preferred solution to this would be.

I did not see a test for the existing ignore feature. So other than a test calling `Deno.test.ignore` there is no test ensuring the ignore flag is properly set on the test definition when calling `Deno.test.ignore`

### CODE REVIEW

**Comment by kitsonk** [comment]
We really need to try to get consensus from more of the core contributors before we try to raise PRs like this.

I personally am not supportive of adding to the API.  We have had a lot of conversations about keeping it minimal.  We have an `ignore` property, it is working well.

**Comment by calebmchenry** [comment]
Understood 👍no hard feelings if this PR gets closed.

**Comment by nayeemrmn** [comment]
Yeah, this adds some symbols and complexity to the testing API which was a concern earlier: https://github.com/denoland/deno/issues/4450.

I'll stress again that I think it's hard to build minimally on an API with a quirk like this.

**Comment by bartlomieju** [comment]
@calebmchenry thank you for opening the PR. There's already `ignore` option that can be used and I don't feel comfortable extending public testing API in this way (we already had overloads for `Deno.test()` but removed them before 1.0). Closing without merge.

**Pull request closed without merging**
