### PR TITLE
doc: Remove detailed / summary distinction

### LINKED ISSUE #6816: Deno doc output missing
I'm not sure if this is intentional, but much of the deno doc output is missing when using the default output format (not json).

For example, only the names of interfaces are displayed and not their functions:

image

Deno version: `1.2.0`, Windows 10

### PR DESCRIPTION
**Pull request by SyrupThinker**
~~This flag enables detailed view without a filter.~~

Closes #6816

### CODE REVIEW

**Comment by bartlomieju** [comment]
@ry WDYT? Maybe we should always print detailed docs without need for another flag...?

**Comment by ry** [comment]
> Maybe we should always print detailed docs without need for another flag...?

I agree with that.

**Comment by bartlomieju** [comment]
@SyrupThinker could you update the PR to remove the flag and always print details?

**Comment by SyrupThinker** [comment]
I think thats a bad default because it drowns out the relevant information in an overview, but sure.
The whole detailed distinction can be removed from the printer then.

**Comment by nayeemrmn** [comment]
My experience with `deno doc | less -r` is that I run it with the intention of being shown a huge wall of text either way, which I can easily filter using search (`/Deno.ListenOptions`). And then I get to the interface I was trying to lookup only to see nothing below it. I have to quit and re-enter `deno doc --builtin Deno.ListenOptions`. Why is "relevant information" defined as this opinionated overview?

The command should just print out a complete doc and leave the rest to external tools. For large docs like the built-ins, I have to use search either way. For small docs, it may as well just show everything. I would suggest an `--overview` flag instead but honestly don't see the point.

**Pull request merged**
