### PR TITLE
BREAKING(std/http): http_bench.ts -> bench.ts

### LINKED ISSUE #5706: Inconsistency in std/http file naming
Hi!

I've discovered a little file naming inconsistency in `std/http` module. While names in the module seem to be relative to `http` part (with some exceptions like `HTTPOptions`), just like file names, two files stand out from others:

- `http_status.ts`
- `http_bench.ts`

Is this intentional?

I'm bringing this issue here since Deno aspires to be a very interesting alternative to Node, so it would be cool to have file consistency in names, as of new way of importing modules via file names.

Cheers!

### PR DESCRIPTION
**Pull request by tokiedokie**
fixes #5706

### CODE REVIEW

**Comment by bartlomieju** [comment]
I'm in favor of this change - the less stutter, the better.

CC @ry @kitsonk

**Comment by kitsonk** [comment]
I am fine with `std/http/http_bench.ts`, but I think `std/http/http_status.ts` might be undesirable, as there is a) there is a lot of 3rd party code that depends on it, b) is specifically a module of HTTP Statuses.  I am not sure we would want that sort of chaos.  (Where as bench should have very limited dependency in the wild)

**Comment by tokiedokie** [comment]
@kitsonk that makes sense

**Review by bartlomieju — APPROVED** [review]
LGTM, thanks @tokiedokie

**Pull request merged**
