### PR TITLE
Upgrade deno_std

### PR DESCRIPTION
**Pull request by ry**
In particular to have [this improvement](https://github.com/denoland/deno_std/pull/324) to http_bench.ts

depends on https://github.com/denoland/deno/pull/2065

### CODE REVIEW

**Comment by ry** [comment]
This is failing because the unit test summary is printed twice for some reason.
```
> ./target/debug/deno --no-prompt js/unit_tests.ts permR0W0N0E0U0
[...]
test createSyscallCountColumnsIrregularData_permR0W0N0E0U0 ... ok
test createSha1ListRegularData_permR0W0N0E0U0 ... ok

test result: ok. 181 passed; 0 failed; 0 ignored; 0 measured; 112 filtered out

running 0 tests

test result: ok. 0 passed; 0 failed; 181 ignored; 0 measured; 112 filtered out
```
I assume this has something to do with the flag changes... Any idea @kt3k @bartlomieju ?

**Comment by kt3k** [comment]
@ry 
If I replaced the following line of unit_tests.ts:
```ts
import "deps/https/deno.land/std/testing/main.ts";
```

to the following:
```ts
import { runTests } from "deps/https/deno.land/std/testing/mod.ts";
runTests();
```
Then tests seem working normally (but I found another failure with `deno fmt`)

**Comment by bartlomieju** [comment]
In `testing/main.ts`:
```ts
// Copyright 2018-2019 the Deno authors. All rights reserved. MIT license.
import { runTests } from "./mod.ts";

async function main() {
  // Testing entire test suite serially
  await runTests();
  // Testing parallel execution on a subset that does not depend on exec order
  await runTests({ parallel: true, only: /^testing/ });
}

main();
```

There shouldn't be two calls to `runTests`. This was changed in denoland/deno_std#309

**Comment by zekth** [comment]
It was to test if parallel and serial test running were working properly. We encountered a non tested case when changing the exitonfail property.

**Comment by bartlomieju** [comment]
> (but I found another failure with `deno fmt`)

@kt3k what's the problem?

**Comment by ry** [comment]
@bartlomieju @zekth I think the future we should fail noisily if runIfMain() is called more than once.

**Comment by bartlomieju** [comment]
@ry agreed, however that wouldn't prevent this error. It was `runTests` that was called multiple times, and I think that might be desired actually.

**Pull request closed without merging**
