### PR TITLE
Release v1.8.3

### PR DESCRIPTION
**Pull request by kitsonk**

### CODE REVIEW

**Comment by lucacasonato** [comment]
LGTM. Can you merge this into main and then cherry pick it down into 1.8? We need to do two way cherry picking otherwise.

**Review by lucacasonato — APPROVED** [review]
LGTM

**Comment by kitsonk** [comment]
Well, the bump PR is only in 1.8, so it is already two qay cherry picking. 🤷

**Comment by lucacasonato** [comment]
Oh ok. I guess let's try that then

**Review by ry — APPROVED** [review]

**Pull request merged**
