### PR TITLE
Rename top-level crates

### PR DESCRIPTION
**Pull request by ry**
Depends on #3057 
Depends on https://github.com/denoland/deno/pull/3064

The purpose of this rename it to get the crate names to be closer aligned to the directory structure.
- Rename "deno" crate to "deno_core".
 - Move `//deno_typescript` to `//ts` (but still keep the "deno_typescript" crate name)

### CODE REVIEW

**Comment by piscisaureus** [comment]
> * Rename //deno_typescript to //ts (but still keep the "deno_typescript" crate name)

But why that? Seems better to just leave it.
Also strange that "//js" contains a bunch of typescript and "//ts" contains a rust crate...

**Comment by ry** [comment]
> But why that? Seems better to just leave it. Also strange that "//js" contains a bunch of typescript and "//ts" contains a rust crate...

"deno_typescript" directory seems wierd because it's prefixed with "deno_" where the other directories are not. Also there is no "//js" directory, it has been renamed to "//rt" to avoid your concern.

**Comment by bartlomieju** [comment]
> "deno_typescript" directory seems wierd because it's prefixed with "deno_" where the other directories are not. Also there is no "//js" directory, it has been renamed to "//rt" to avoid your concern.

"//runtime" would be even less confusing 🙄

**Comment by hayd** [comment]
What about: 

> Rename "deno_cli_snapshots" to "deno_rt". And move the corresponding //js directory to //runtime.
 > Move //deno_typescript to //typescript (but still keep the "deno_typescript" crate name)

I don't see the benefit of two char dir names... agree surprising ts/ or js/ would be a rust crate, usually one might expect them to contain typescript/javascript files respectively.

**Comment by ry** [comment]
@bartlomieju @hayd After discussing with Bert, I realized deno_cli_snapshots could be merged into deno_cli without any negative effects. I've done this in https://github.com/denoland/deno/pull/3064 

That means there won't be any deno_rt

**Comment by ry** [comment]
For whatever reason I can't get this to go green. I will attempt later. Closing this for now.

**Pull request closed without merging**
