### PR TITLE
bring back json ops

### PR DESCRIPTION
**Pull request by bartlomieju**
Ref: #2814

### CODE REVIEW

**Comment by ry** [comment]
I’d rather land a fix and test to the shared_queue and then bring back the ops in a separate commit.

**Comment by bartlomieju** [comment]
@ry agreed, I'm trying to verify that this is indeed a viable solution

**Comment by bartlomieju** [comment]
This PR should be landed after #2816

**Comment by bartlomieju** [comment]
@ry problem with benchmarks no longer occurs

**Comment by ry** [comment]
@bartlomieju Cool - this contains all of your changes that were reverted, and this is ready to land?

**Comment by bartlomieju** [comment]
@ry yes, I reverted the "revert" commit, it's ready to land

**Pull request merged**
