### PR TITLE
build: allow deno_runtime crate to build in docs.rs

### PR DESCRIPTION
**Pull request by bartlomieju**
Fixes https://github.com/denoland/deno/issues/10276

### CODE REVIEW

**Comment by bartlomieju** [comment]
This is not probably the cause of build fails. Investigating...

**Review by dsherret — APPROVED** [review]
LGTM

**Review by ry — APPROVED** [review]
LGTM

**Comment by bartlomieju** [comment]
For posterity: I tried creating an "empty" snapshot in `runtime/build.rs` due to the fact that `rusty_v8` doesn't build V8 on `docs.rs` (cause docs.rs doesn't allow to access net). However it didn't help and I still get a lot of linker errors (https://docs.rs/crate/deno_runtime/0.22.1/builds). I'm a bit at loss here as `deno_core` doesn't have a build script, nor does it tweak any settings and it builds just fine.

**Pull request closed without merging**
