### PR TITLE
fix(std/test): ignore startTls test

### PR DESCRIPTION
**Pull request by trivikr**
Fixes: https://github.com/denoland/deno/issues/7815

Creating a draft PR as a better solution could be to ignore the test in specific case, i.e., if ISP has blocked `smtp.gmail.com:587`

### CODE REVIEW

**Comment by nayeemrmn** [comment]
If the test passes in CI and most other developers, and doesn't affect any other test, there's no reason to disable it. (This test always fails for me, too.)

**Comment by trivikr** [comment]
> If the test passes in CI and most other developers, and doesn't affect any other test, there's no reason to disable it. (This test always fails for me, too.)

The reason is point 4 in PR template https://github.com/denoland/deno/blob/f4357f0ff9d39411f22504fcc20db6bd5dec6ddb/.github/PULL_REQUEST_TEMPLATE.md#L19

Is there a way to ignore the test only when `smtp.gmail.com:587` is blocked by ISP?

**Comment by kitsonk** [comment]
We should find a way to test this without needing to connect outside of the environment by creating a mock TLS server on the localhost, like we have for other tests.

**Comment by bnoordhuis** [comment]
@kitsonk I don't necessarily disagree but the test fails through no fault of the person running it. Marking it flaky seems okay to me as a stop-gap measure.

A propos a mock TLS server: that means it'd just be testing `Deno.startTls()` on both ends, unless it's written in e.g. python.

**Comment by lucacasonato** [comment]
Instead of disabling, couldn't we change the test to do HTTP over TLS with our TLS http test server? We could also just add an echoing TLS test server in our test_util that uses our self signed TLS certs.

**Comment by bartlomieju** [comment]
> Instead of disabling, couldn't we change the test to do HTTP over TLS with our TLS http test server? We could also just add an echoing TLS test server in our test_util that uses our self signed TLS certs.

This PR completely disables this test, even though it's passing on CI. That seems like a bad idea to me. I agree with @lucacasonato we should use self-signed cert and test server instead of hitting `smpt.gmail.com`. Closing without merge.

**Pull request closed without merging**
