### PR TITLE
perf(ext/headers): use regex.test instead of .exec

### PR DESCRIPTION
**Pull request by marcosc90**
This PR improves the performance of `Headers.get` by using `Regex.test` instead of `.exec`. Also replaced the `Map` used for caching with an object which is a bit faster

**This patch**

```
cpu: 13th Gen Intel(R) Core(TM) i9-13900H
runtime: deno 1.36.1 (x86_64-unknown-linux-gnu)

benchmark              time (avg)        iter/s             (min … max)       p75       p99      p995
----------------------------------------------------------------------- -----------------------------
Headers.get           124.71 ns/iter   8,018,687.3 (115.11 ns … 265.66 ns) 126.05 ns 136.12 ns 142.37 ns
```

**1.36.1**

```
cpu: 13th Gen Intel(R) Core(TM) i9-13900H
runtime: deno 1.36.0 (x86_64-unknown-linux-gnu)

benchmark              time (avg)        iter/s             (min … max)       p75       p99      p995
----------------------------------------------------------------------- -----------------------------
Headers.get           218.91 ns/iter   4,568,172.3 (165.37 ns … 264.44 ns) 241.62 ns 260.94 ns 262.67 ns
```

```js
const headers = new Headers({
  "Content-Type": "application/json",
  "Date": "Thu, 10 Aug 2023 07:45:10 GMT",
  "X-Deno": "Deno",
  "Powered-By": "Deno",
  "Content-Encoding": "gzip",
  "Set-Cookie": "__Secure-ID=123; Secure; Domain=example.com",
  "Content-Length": "150",
  "Vary": "Accept-Encoding, Accept, X-Requested-With",
});

Deno.bench("Headers.get", () => {
  headers.get("x-deno");
});
```

### CODE REVIEW

**Comment by marcosc90** [comment]
Correct benchmarks, since I was using an outdated build without the recent perf additions.

**main**
```
cpu: 13th Gen Intel(R) Core(TM) i9-13900H
runtime: deno 1.36.1 (x86_64-unknown-linux-gnu)

benchmark        time (avg)        iter/s             (min … max)       p75       p99      p995
----------------------------------------------------------------- -----------------------------
Headers.get     132.15 ns/iter   7,567,412.3 (126.84 ns … 142.25 ns)  133.9 ns 139.93 ns 141.56 ns
```

**Review by mmastrac — APPROVED** [review]
LGTM

**Comment by mmastrac** [comment]
If you want to try out an experiment we never landed, some testing we did a few months back showed that bit-testing is the absolute fastest way to do this

I _believe_ that this is the code we used for the experiment:

```
let a = []; for (var i = 0; i < 128; i++) { a[i >> 4] |= (HTTP_TOKEN_CODE_POINT_RE.test(String.fromCharCode(i)) ? 1 << (i & 15) : 0) }
```

```
  function bittest(val) {
    const BITMASK = [
        0,     0, 27898,
      1023, 65534, 51199,
      65535, 22527
    ];
    for (var i = 0; i < val.length; i++) {
      const c = val.charCodeAt(i);
      if ((BITMASK[c >> 4] & (c & 15)) == 0) {
        return false;
      }
    }
    return true;
  }
```

**Comment by marcosc90** [comment]
I'll do a bit of testing with that @mmastrac 

---

Regarding this PR, I noticed that @bartlomieju changed `.test` with `.exec` and resulted in a performance gain.

https://github.com/denoland/deno/pull/19364

Someone want to bench this and post results? All my benches result in `.test` being much faster than `.exec`

**Comment by mmastrac** [comment]
As @lino-levan said on the other PR

"The V8 engine is a whimsical place, seemingly random changes can have surprising differences in performance."

Are you using `tools/build_bench.ts` BTW? We built that tool to help w/benchmarking noise from incremental LTO builds.

**Comment by marcosc90** [comment]
I'm going to close for now, and do some further benching when I have some extra time.

**Comment by bartlomieju** [comment]
@marcosc90 I think we land this PR as is, we can run internal benches tomorrow to see if there's visible improvement.

**Comment by marcosc90** [comment]
@bartlomieju sounds good to me. I'm also going through all regex being used in headers/response to see if they can be optimized a bit.

**Comment by bartlomieju** [comment]
> @bartlomieju sounds good to me. I'm also going through all regex being used in headers/response to see if they can be optimized a bit.

Great to hear that as these regexes are showing up in the flamegraphs we plot. If you want to take a deeper look into what's going on when benching HTTP server I highly recommend using [`samply`](https://github.com/mstange/samply) - you can generate a flamegraph easily by doing `samply record -r 20000 deno run -A server.js`

**Comment by mmastrac** [comment]
Merged this one as is -- thanks for all the perf fixes!

**Pull request merged**
