### PR TITLE
Revert "feat: format deno bundle output (#5139)"

### PR DESCRIPTION
**Pull request by ry**
This reverts commit 93cf3bd5341d5985201ea0905280082d5a3310f9.
 

Alternative to https://github.com/denoland/deno/pull/6063

cc @kt3k

### CODE REVIEW

**Comment by wongjiahau** [comment]
@ry Line 406  at `cli/main.rs` is not reverted, that caused the build to fail.
```rs
let output_string = fmt::format_text(&output)?;
```

**Comment by ry** [comment]
I’m a little hesitant to remove this feature. We have no benchmark showing it to be the bottleneck.

**Comment by wongjiahau** [comment]
@ry We have no concrete benchmarks yet, but it will definitely be a bottleneck when the project-to-be-bundled becomes very huge, like the Terser.js example I provided.  

Some personal opinion here, I think we shouldn't add in something that does not serve any particular objective even though it seems harmless, else the codebase will eventually be littered with lots of purposeless code segments which undermine maintainability.

**Comment by ry** [comment]
@wongjiahau You're right - it's cosmetic only. Landing this.

**Pull request merged**
