### PR TITLE
Added browser chat example

### PR DESCRIPTION
**Pull request by keroxp**
https://gyazo.com/4ef820595ecf72bbd83a158dc1e36212

### CODE REVIEW

**Comment by ry** [comment]
Cool! I realize we don't have tests in the examples directory - but we should - I wonder if you'd be able to provide a basic test for this? Otherwise it's quite likely it will break...

**Comment by keroxp** [comment]
I've realized that remote modules can't serve file that located on the remote server...

```
deno --allow-net --allow-read https://deno.land/std/examples/chat/server.ts
```

It won't work after merged :(

**Comment by ry** [comment]
@keroxp Can you use `import.meta.url` to get the location of the html asset?

**Comment by keroxp** [comment]
@ry No, maybe. There is no way to "open" remote file from local.  

```ts
// deno -A https://deno.land/std/example/chat/server.ts -> https://deno.land/std/examples/chat/index.html 
// deno -A ./server.ts -> file:///src/deno/std/examples/chat/server.ts
const f = new URL("./index.html", import.meta.url).href;
fetch(f).then(resp => req.respond(resp))
```

Code above worked for `deno -A http://....` but didn't work for `deno -a ./server.ts`.
`Deno.open()`doesn't accept `http://...` and `fetch()` doesn't `file://...`

**Comment by keroxp** [comment]
AdditionallyI found another bug #4038

**Comment by keroxp** [comment]
@ry I fixed those problems by hacky way. Would you see the change?

**Pull request merged**
