### PR TITLE
fix: replace the @deno-types with @ts-types

### LINKED ISSUE #27309: LSP actions use `@deno-types` instead pf `@ts-types`
LSP code actions use `@deno-types` for adding types to the import statement. These should be replaced with `@ts-types` as `@ts-types` is now more recommended than `@deno-types`

```shellsession
$ git grep --line-number deno-types cli/lsp/
cli/lsp/analysis.rs:1390:        "{}// @deno-types=\"{}\"\n",
cli/lsp/analysis.rs:1403:          "Add @deno-types directive for \"{}\"",
cli/lsp/diagnostics.rs:1358:    // @deno-types and that's a bit complicated to explain
cli/lsp/diagnostics.rs:1526:  // TODO(nayeemrmn): This is a crude way of detecting `@deno-types` which has
cli/lsp/diagnostics.rs:1543:        // If not @deno-types, diagnose the types if the code errored because
cli/lsp/diagnostics.rs:1954:        // @deno-types="bad.d.ts"
cli/lsp/tsc.rs:3422:                  "// @deno-types=\"{}\"\n{}",
cli/lsp/tsc.rs:3598:            "// @deno-types=\"{}\"\n{}",
```

Version: Deno 2.1.3

### PR DESCRIPTION
**Pull request by MohammadSu1**
This PR closes #27309

### CODE REVIEW

**Comment by kt3k** [comment]
Thanks for the PR!

Can you also fix the test case `lsp::diagnostics::tests::duplicate_diagnostics_for_duplicate_imports`?

(Note: You can run only that case locally with the command `cargo test lsp::diagnostics::tests::duplicate_diagnostics_for_duplicate_imports`

**Comment by MohammadSu1** [comment]
Yes, I am currently working on this.

**Review by kt3k — APPROVED** [review]
Thanks! LGTM

@nayeemrmn @dsherret Can you take another look?

**Review by dsherret — APPROVED** [review]
Great. Thanks!

**Pull request merged**
