### PR TITLE
fix(cli/rt/performance): Check for object props in startOrMeasureOptions before throwing

### LINKED ISSUE #7876: performance.measure throws when measuring from navigation by providing undefined startMark
Attempting to measure from navigation by supplying `undefined` for `startOrMeasureOptions` results in the following error:

```
error: Uncaught TypeError: Options cannot be passed with endMark.
    at Performance.measure (deno:cli/rt/40_performance.js:254:17)
    at file:///main.ts:6:13
```

Code to reproduce (works in supported browsers):

```ts
const markerName1 = '1';
const markerName2 = '2';
performance.mark(markerName1);
performance.mark(markerName2);
performance.measure('measure between markers', markerName1, markerName2);
performance.measure('measure from navigation', undefined, markerName2);
console.log(performance.getEntriesByType('measure'));
```

Spec:
https://w3c.github.io/user-timing/#dom-performance-measure

Source: https://github.com/denoland/deno/blob/d8879feb8c832dbb38649551b1cb0730874f7be6/cli/rt/40_performance.js#L247-L323

### PR DESCRIPTION
**Pull request by jsejcksn**
Fixes #7876 

Still needs tests; not sure where they belong.
/cc @kitsonk

### CODE REVIEW

**Comment by kitsonk** [comment]
Cool. For the tests, they should get added here: https://github.com/denoland/deno/blob/master/cli/tests/unit/performance_test.ts

**Comment by jsejcksn** [comment]
PTAL @kitsonk 

Also:

1. The ubuntu ci build failed because of something related to rusty v8:

> error: could not find native static library `rusty_v8`, perhaps an -L flag is missing?

I think this is unrelated to my commits, but if I did something wrong, please let me know how to avoid it in the future.

2. In the tests, is `assert` used with `===` instead of `assertEquals` because `assertEquals` does not use object equality?

**Comment by kitsonk** [comment]
Yeah, something is wrong with CI right now... I'm waiting for other to come online because it is currently beyond my ability to know why it is broken.

**Comment by jsejcksn** [comment]
@kitsonk Is the CLI fixed yet? How can the checks be re-run so this PR is ready for review? I don't see any UI for that action...

**Comment by kitsonk** [comment]
@jsejcksn `git commit --allow-empty -m "bump" & git push`

**Comment by jsejcksn** [comment]
> `git commit --allow-empty -m "bump" & git push`

I thought there was a way for collaborators to manually re-run checks without another commit having to be pushed. I remember seeing it in the GitHub docs a while back, but I can't find it now.

**Review by kitsonk — APPROVED** [review]
LGTM

**Pull request merged**
