### PR TITLE
fix(http): add request-based abort signal

### LINKED ISSUE #21421: Can't react to request aborted by client
Version: deno 1.38.4 (release, aarch64-apple-darwin)

Deno is missing a way to detect if a connection has been closed by the client, both in `Deno.serve` and node compat:

```ts
// client.ts
const ctrl = new AbortController();
setTimeout(() => ctrl.abort("x"), 100)
try {
  await fetch('http://localhost:8000', { signal: ctrl.signal })
} catch (x) {
  console.log(x);
}
```

```ts
// server.ts
Deno.serve(async (request) => {
  const { promise, resolve, reject } = Promise.withResolvers();

  const operation = setTimeout(() => {
    console.log('Operation completed');
    resolve('Operation completed');
  }, 3_000);

  request.signal.addEventListener('abort', () => {
    console.log('Request was aborted by the client');
    clearTimeout(operation);
    reject('Operation aborted');
  });

  return new Response(await promise);
});
```

This will always log `Operation completed` after 3 seconds.

The story is different in Node.js:

```js
// server.mjs
import http from 'node:http';

const server = http.createServer((req, res) => {
  let completed = false;
  const operation = setTimeout(() => {
    completed = true;
    console.log('Operation completed');
    res.end('Operation completed');
  }, 3_000);

  req.on('close', () => {
    if (!completed) {
      console.log('Request was aborted by the client');
      clearTimeout(operation);
    }
  });
});

const port = 8000
server.listen(port, () => {
  console.log(`Server running on port ${port}`);
});
```

This will log `Request was aborted by the client` when used with the client above. 

Deno's node compat has the same issue: Running the above gives `Operation completed` again.

### PR DESCRIPTION
**Pull request by crowlKats**
Fixes #21421

### CODE REVIEW

**Comment by mmastrac** [comment]
Let me see if I can get kijunsan working well enough to run a bench on this

**Review by mmastrac — CHANGES_REQUESTED** [review]
Marking as "request changes" for now while we investigate the performance of AbortController.

**Comment by bartlomieju** [comment]
I did some benchmarking and here's what I found:
1. Creating an `AbortController` is quite fast - it takes roughly 20ns on my machine
2. Using `createDependentAbortSignal` is slow - doing that in combination with creating an AC is about 2us, which is 100x flower.
3. The slow part in `createDependentAbortSignal` is `WeakSet` handling - we spend a lot of time in `add()` function.

So I think we should look into adding an internal fast path equivalent of `createDependentAbortSignal` that only ever has 1 dependent signal and preferably skips `WeakSet` completely, instead using `WeakRef`. @crowlKats is it something you could look at?

**Comment by piscisaureus** [comment]
@mmastrac / @crowlKats what's the status of this?

**Comment by mmastrac** [comment]
Replaced by https://github.com/denoland/deno/pull/23425

**Pull request closed without merging**
