### PR TITLE
fix(std/http): Fix respond error test on Windows

### PR DESCRIPTION
**Pull request by nayeemrmn**
cc @kevinkassimo

### CODE REVIEW

**Comment by ry** [comment]
is this related to https://github.com/denoland/deno/issues/4373?

**Comment by kevinkassimo** [comment]
Hmm I am not quite sure about the behavior on WSL.

The original intention of this test was to trigger a failure during `req.respond` to see if the server can close the connection on error. I believe one other more reliable way to do this, based on current codebase, is to make `Response` take a bad status code, e.g. `req.respond({ status: 12345, body: ...  })`.

However, the test on double `req.respond` behavior is still an interesting case to keep. Is there a way to test if the platform is WSL?

**Comment by nayeemrmn** [comment]
@kevinkassimo The behaviour of the test is 100% preserved. The way the test was written is it would hang if the second response didn't throw an error (because it wouldn't break from for-await loop). I made it fail instead. The same checks are there. On WSL the test breaks like it would on Windows but is not skipped like it is on Windows, so I was experiencing that hanging. I would rather get a failure.

(We shouldn't branch logic based on WSL because it's supposed to work exactly like Linux and any case it doesn't (usually involving sockets) is a bug/shortcoming of WSL.)

**Comment by kevinkassimo** [comment]
> @kevinkassimo The behaviour of the test is 100% preserved. The way the test was written is it would hang if the second response didn't throw an error (because it wouldn't break from for-await loop).

Yeah I do understand that. It is just news to me that on WSL this is having the no RST behavior. I was just suggesting an alternative solution, since the original intention of that single test is to trigger a failure for server to close, which obviously is not working here under WSL.

**Comment by nayeemrmn** [comment]
Yeah with a lot of net stuff WSL takes the behaviour of Windows instead of Linux. I'm just making it throw instead of hang in the failure case, but it would be great if it could be fixed for Windows.

As I now understand: the test is supposed to make `req.respond()` fail (which is not itself the tested behaviour) and ensure that this failure caused the connection to be closed, and a more reliable way of making `req.respond()` fail is an invalid status code. I'll implement that here then.

**Comment by nayeemrmn** [comment]
@ry It's easiest to read through above discussion but basically the thing that was breaking it on Windows wasn't the behaviour that this was originally intended to test but part of the setup, as I understood from @kevinkassimo. It checks that the correct things happens when respond throws, but there are lots of ways to make it throw.

**Comment by ry** [comment]
@kevinkassimo do you approve of this change?

**Comment by kevinkassimo** [comment]
Strange now that it warns about leaking op, but otherwise lgtm

**Comment by ry** [comment]
@nayeemrmn please merge with master

**Comment by ry** [comment]
@nayeemrmn It seems this failed when merged into masterhttps://github.com/denoland/deno/runs/520656981

Any idea what's happening? Should I revert?

**Comment by nayeemrmn** [comment]
I get that error sporadically. It seems like the previous test `[http] close server while connection is open` is sometimes late to finish one of its ops and messes up the equality for the next one. Not to do with this change.

**Pull request merged**
