### PR TITLE
Add types for WebAssembly

### PR DESCRIPTION
**Pull request by sh7dm**
/cc @ry

### CODE REVIEW

**Comment by ry** [comment]
@sh7dm Thanks.


@kitsonk I'm playing around with how to import the wasm types ... Do you have any suggestions?

**Comment by kitsonk** [comment]
@ry I am not overly impressed with the Definitely Typed types. There are a few issues with them and how they vary from the spec.

Because of the way we generate the library, we only deal with types where we have functional code and depend upon a lib for everything else that is built in. So I would propose to add a lib specifically for web Assembly and prepend that to the runtime lib along side the esnext one. I have a branch where I am doing that. It will require a change to make the lib builder more flexible as well.

**Comment by ry** [comment]
@kitsonk Ok sounds good.

Is `declare namespace WebAssembly` the way to go? Or is that what you mean by varying from the spec?

**Comment by kitsonk** [comment]
@ry 

1. It doesn't include the streaming addendum (https://webassembly.github.io/spec/web-api/)
2. It doesn't include string literals where it should (in some of the descriptor)
3. Some of the names don't align to the IDL
4. It exposes properties on the errors
5. It redefines `BufferSource` instead of using the global one
6. It uses `any` in some instances where it should be using `object`

While my idea works, because the lib isn't included with the standard libs with TypeScript which means in editors, you will just get errors and the `--types` wouldn't work for most people.  I am going to have to inline the file into the type library.  Working on that now.

**Comment by ry** [comment]
Closed in favor of #1677 - thanks for getting this started @sh7dm!

**Pull request closed without merging**
