### PR TITLE
cli: replace crate `log` with `tracing`

### PR DESCRIPTION
**Pull request by attliaLin**

### CODE REVIEW

**Comment by attliaLin** [comment]
I'm not sure should I change the test case, because I think it's better to provide more information.

**Comment by bartlomieju** [comment]
@attliaLin what is the reason for this change?

**Comment by attliaLin** [comment]
> @attliaLin what is the reason for this change?

I saw this in code. So I think maybe I can fix it.

```md
// TODO(ry) Switch to env_logger or other standard crate.
```

**Comment by bartlomieju** [comment]
> > @attliaLin what is the reason for this change?
> 
> I saw this in code. So I think maybe I can fix it.
> 
> ```lisp
> // TODO(ry) Switch to env_logger or other standard crate.
> ```

Then yeah, there's an issue for that: https://github.com/denoland/deno/issues/3869 We want to use `env_logger` but not `tracing`.

Before introducing new crates it's best to open an issue, discuss and get a consensus.

**Comment by attliaLin** [comment]
> > > @attliaLin what is the reason for this change?
> > 
> > 
> > I saw this in code. So I think maybe I can fix it.
> > ```lisp
> > // TODO(ry) Switch to env_logger or other standard crate.
> > ```
> 
> Then yeah, there's an issue for that: #3869 We want to use `env_logger` but not `tracing`.
> 
> Before introducing new crates it's best to open an issue, discuss and get a consensus.

Sorry for not noticed that. I will reply there.

**Comment by bartlomieju** [comment]
@attliaLin thank you for your work and opening the PR. I'm gonna close it without merge - I don't know `tracing` crate and it would require more careful review before introducing it. 

We still want to migrate to `env_logger` instead of `log` for logging as per #3869 and I'd welcome such PR.

**Pull request closed without merging**
