### PR TITLE
[WIP] backport ast::ParsedModule

### PR DESCRIPTION
**Pull request by bartlomieju**

### CODE REVIEW

**Comment by kitsonk** [comment]
@bartlomieju the latest version of swc had some breaking changes... I've absorbed them into my PR and updated it.

**Comment by bartlomieju** [comment]
> @bartlomieju the latest version of swc had some breaking changes... I've absorbed them into my PR and updated it.

Thanks for the info @kitsonk I'll try getting it up to speed tomorrow. Do you think we could backport changes to tsconfig parsing from your PR as well?

**Comment by bartlomieju** [comment]
Waiting on https://github.com/denoland/deno/pull/7228

**Comment by bartlomieju** [comment]
Closing for now, I'll revisit

**Pull request closed without merging**
