### PR TITLE
chore(ext/webgpu): update wgpu and implementation

### PR DESCRIPTION
**Pull request by crowlKats**
after this lands I will open the same PR over at wgpu

### CODE REVIEW

**Comment by lucacasonato** [comment]
Can you do the reverse? Land the PR there first? I'd like to just copy over the folder from there.

**Comment by DjDeveloperr** [comment]
Looks like the PR at wgpu was merged: https://github.com/gfx-rs/wgpu/pull/2214

**Comment by crowlKats** [comment]
> Looks like the PR at wgpu was merged: [gfx-rs/wgpu#2214](https://github.com/gfx-rs/wgpu/pull/2214)

yes, but we cant update till they make a release.

**Comment by crowlKats** [comment]
Closing in favour of #13402

**Pull request closed without merging**
