### PR TITLE
refactor(cli/coverage): use json and error check protocol responses

### PR DESCRIPTION
**Pull request by caspervonb**
This gets rid of the hard-coded message ids, parses messages as JSON and adds error checking on message responses.

### CODE REVIEW

**Comment by bartlomieju** [comment]
@caspervonb could you look into feasibility of using this technique in `inspector_` integration tests?

**Comment by caspervonb** [comment]
> @caspervonb could you look into feasibility of using this technique in `inspector_` integration tests?

Sure thing.

**Review by bartlomieju — APPROVED** [review]
LGTM

**Comment by caspervonb** [comment]
Ties into #7473

**Pull request merged**
