### PR TITLE
fix(ext/fs): account for all ops in leak checks

### PR DESCRIPTION
**Pull request by iuioiua**
This is PR a smaller retry of #23066 that simply ensures all async `ext/fs` ops are accounted for if left hanging in tests. This also sorts the `OP_DETAILS` in alphabetical order for easy future reading.

When reviewing, it might be best to look at the commits in order for better understanding.

### CODE REVIEW

**Review by mmastrac — APPROVED** [review]
LGTM!

**Comment by iuioiua** [comment]
Perhaps there's an easy to do this automatically by ensuring the keys of `OP_DETAILS` are async ops. It'd only be worth it if easy to do. Otherwise, doing it manually is better.

**Comment by bartlomieju** [comment]
We now have a way to do this: https://github.com/denoland/deno_core/commit/4a4a609d710cfd3078cd6dd464f5cb5bba0dd925

We need to rewrite all async ops to use these macros and then make them required.

**Comment by iuioiua** [comment]
> We now have a way to do this: [denoland/deno_core@4a4a609](https://github.com/denoland/deno_core/commit/4a4a609d710cfd3078cd6dd464f5cb5bba0dd925)
> 
> We need to rewrite all async ops to use these macros and then make them required.

@nathanwhit, if you like, you can lay the groundwork with a working example for an op, and I can do the rest.

**Pull request merged**
