### PR TITLE
Correct media_types API

### LINKED ISSUE #4292: media_types API is not good
The media_types API employs too much magic leading to unexpected behavior:

```
lookup('html');                     // 'text/html'
lookup('file.html');                // 'text/html'
lookup('path/to/file.html');        // 'text/html'

contentType('html');                // 'text/html; charset=utf-8'
contentType('file.html');           // 'text/html; charset=utf-8'
contentType('path/to/file.html');   // 'path/to/file.html' - uhh, what??
```

Also, the naming, while understandable for someone who knows the implementation (e.g. how the database is keyed), is a bit confusing for a newcomer:
  - `lookup()`? Aren't they all lookups of some type or another?
  - `lookup()` returns a (non-full?) "content type", which you pass to `contentType()` and it returns a "full" content type" ?

So many exports/functions:
  - `lookup(path)`
  - `contentType(type)`
  - `extension(type)`
  - `charset(type)`
  - `extensions`
  - `types`

A (imo) much easier to understand API would be to just expose (maybe a subset of) the database record type:

```
export interface MediaType {
    identifier: string,
    extensions: string[],
    charset?: string,
    compressible?: boolean
}

export function lookupByIdentifier(identifier: string): MediaType|undefined
export function lookupByExtension(path: string): MediaType|undefined

```

### PR DESCRIPTION
**Pull request by ry**
Fix #4292

cc @kitsonk

### CODE REVIEW

**Comment by kitsonk** [comment]
The purpose of the API is to normalise content-types, when users take shortcuts.  See how this API is used in oak:

https://github.com/oakserver/oak/blob/99dfcda9d590b73a449e1258c7c0c2e4ab790b45/response.ts#L33-L40

So I would prefer to not make this change.  Clearing up documentation of its purpose, or changing the name of the API to `normalizeContentType` would be better.  The reason it resolves "extensions" is so that a user can set the content type to a response to something like `"json"` but end up with a full valid media type as output.  It was never designed to do paths, as that feature is `lookup()`.

**Comment by ry** [comment]
Actually, now that I'm looking more deeply into this library, I'm not happy with it. I want to delete it from std. In file_server, the only place it's used, we can just use a small map of filename extensions.

**Comment by kitsonk** [comment]
Again, personally, I don't care.  I originally ported it to oak because it was the easiest way to replicate functionality, but I always thought it was a bit overkill for a standard library, but people kept trying to build a whole express/koa type framework in standard, and this was an easy move to help stem that need.

**Comment by ry** [comment]
OK then I'm going to remove media_types. I think it's better to kick this out into deno.land/x rather than support it forever https://github.com/denoland/deno/pull/4594

**Pull request closed without merging**
