### PR TITLE
feat(ext/console): Add string abbreviation size option for "Deno.inspect"

### PR DESCRIPTION
**Pull request by bcheidemann**
Implements an option on `Deno.inspect` to set the maximum string size before it is truncated with an ellipsis.

This is required to fix [this issue in denoland/deno_std](https://github.com/denoland/deno_std/issues/2140).

### CODE REVIEW

**Comment by bcheidemann** [comment]
@bartlomieju @kt3k could you advise on where to add a test for this?

**Comment by bartlomieju** [comment]
> @bartlomieju @kt3k could you advise on where to add a test for this?

That would be in `cli/tests/unit/console_test.ts`

**Comment by bcheidemann** [comment]
This property currently doesn't apply to strings because strings are not currently truncated by `Deno.inspect`. Should this property also apply to `Deno.inspect(someLongString)`?

**Review by kt3k — APPROVED** [review]
LGTM

**Comment by kt3k** [comment]
> This property currently doesn't apply to strings because strings are not currently truncated by Deno.inspect. Should this property also apply to Deno.inspect(someLongString)?

I don't think we need it at this point.

**Review by bartlomieju — APPROVED** [review]
LGTM

**Pull request merged**
