### PR TITLE
feat: add sha3 hash

### PR DESCRIPTION
**Pull request by skdltmxn**
This PR implements following hash algorithms

- SHA3-224
- SHA3-256
- SHA3-385
- SHA3-512
- Keccak-224
- Keccak-256
- Keccak-384
- Keccak-512
- SHAKE-128
- SHAKE-256

eslint keeps complaining that SHA3 class names are not in camel case.
I cannot come up with a good alternative for 'Sha3-224' and its kinds.
If anyone has better idea, I will fix it.

### CODE REVIEW

**Comment by bartlomieju** [comment]
@skdltmxn thanks for opening the PR! CI is failing on lint/format test; make sure to run `tools/format.py` and `tools/lint.py` to get it to green

**Comment by skdltmxn** [comment]
@bartlomieju yes lint is failing due to Sha3 class names e.g. Sha3-256.
But I cannot come up with good alternatives to both satisfy lint and usability.
Should I ignore Sha3 classes from lint?

**Comment by bartlomieju** [comment]
@skdltmxn could you look up some prior art in Node/Go/Python/Rust? If there's a convention we could ignore linting

**Comment by skdltmxn** [comment]
@bartlomieju I've searched prior arts and it looks like most of them are using underscore conventions except Go which uses its unique interface.

- Rust
```rust
use sha3::{Digest, Sha3_256};

let mut hasher = Sha3_256::new();
// ...
```

- Node
```javascript
import { sha3_512 } from 'js-sha3';
sha3_512('Message to hash');
```

- Python
```python
# python3.6 and up
import hashlib
h = hashlib.sha3_256()
h.update('blahblah')
```

**Comment by ry** [comment]
@skdltmxn Use eslint-ignore

**Comment by skdltmxn** [comment]
@ry Do you mean .eslintignore?

**Comment by kitsonk** [comment]
It feels like this could/should be a single file.  Also both the SHA1 and SHA256 are based off the code by the same author, who also has a JavaScript version of SHA3: https://github.com/emn178/js-sha3/blob/master/src/sha3.js.  This implementations surface API is quite a bit different from that of SHA1 and SHA256 that we already have in standard.  It also doesn't need to be seperate files, IMO.

The exports include an underscore where the number would run together (`Sha3_256` for example).

As Ry mentions, the eslint failures should be ignored using code comments.  There are several examples in the code base already of how those are ignored.

**Comment by skdltmxn** [comment]
@kitsonk The major reason I separated the implementation into different files is because SHA-3 has many variants unlike SHA1 and SHA256.
I thought it would be natural to put each algorithm into its own file, Keccaks into keccak.ts, Shakes into shake.ts.

I will fix surface APIs to match Sha1 and Sha256, and apply eslint ignore code comments :)

Thank you!

**Comment by kitsonk** [comment]
I am still worried that the surface API of these varies quite a bit from the SHA1 and SHA256 ones.  We really should have the same surface API.  Currently a [class has something like this](https://doc.deno.land/https/deno.land/std/hash/sha256.ts#Sha256):

```ts
type Message = string | number[] | ArrayBuffer;

interface Hash {
  update(message: Message): Hash;
  hex(): string;
  toString(): string;
  digest(): number[];
  array(): number[];
  arrayBuffer(): ArrayBuffer;
}
```

This should really align to that API (or we should dumb down the other APIs, but the various APIs are really handy when dealing with different workloads, like `hex()` is great when doing web workloads where you are signing things in headers, cookies, etc. and we shouldn't be opinionated about the the typed array we return, it should be an `ArrayBuffer` at the very least))

**Comment by skdltmxn** [comment]
@kitsonk
I cannot agree more with you about the APIs. I will fix my implementation to go with existing APIs.

Just minor questions though... 
1. Should there be `array` method when we already have `digest`? It just returns `this.digest();`. Would there be any symantic reason?
2. Should we treat `number[]` when there is `ArrayBuffer`?

**Comment by kitsonk** [comment]
`ArrayBuffer` is more efficient than a `number[]`. All typed arrays are essentially views on an `ArrayBuffer` where a `number[]` is of fixed width and can at runtime contain anything.

I would be fine removing `.array()` in the other two implementations as they are just duplicates of `.digest()`.

**Comment by Brooooooklyn** [comment]
Just curious, why not implement it in the rust side, it seems to be a performance sensitive scenario.

**Comment by kitsonk** [comment]
> Just curious, why not implement it in the rust side, it seems to be a performance sensitive scenario.

`std` effectively is all user land JavaScript/TypeScript modules.  If we were going to do something it Rust, we would prefer it to be aligned to existing standards.  It could be implemented via https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/digest and I am sure a PR like that would be accepted.  We can always evolve forward, towards that as well, while still having a broad set of APIs available in `std` and we can then simply "proxy" those requests in the future if it does get implemented directly in the CLI.

**Comment by skdltmxn** [comment]
I modified surface APIs like existing SHA1 and SHA256 with some minor changes as below.

- `digest` returns `ArrayBuffer` instead of `number[]`
- removed `array` in favor of `digest`
- removed `arrayBuffer` in favor of `digest`
- removed `hex` in favor of `toString`

**Comment by skdltmxn** [comment]
It looks like the test is just cancelled?

**Comment by skdltmxn** [comment]
@kitsonk Could you take a look on the tests?

**Comment by skdltmxn** [comment]
@bartlomieju Great! Thanks :)

**Pull request merged**
