### PR TITLE
fix: [http] Consume unread body and trailers before reading next request

### PR DESCRIPTION
**Pull request by keroxp**
cc @kevinkassimo @bartlomieju 
- Added `ServerRequest.finalize()`:  consuming all unread body stream and trailers.
  - This is cleanup method for reading next request from same keep-alive connection.
  - Needed when handler didn't consume all body and trailers even after responding.
- refactor: `ServerRequest._bodyStream()`, `ServerRequestBody` are removed.
  - Now using `bodyReader()` and `chunkedBodyReader()` instead.
- fix: Trailers should only be read `transfer-encoding` is `chunked` and `trailer` header is set and its value is valid.
- fix: use `Headers.append()` on reading trailers.
- fix: delete `trailer` field from headers after reading trailers.
- reorg: Several functions related to IO are moved into `http/io.ts`
---

- [x] Adding more tests...

### CODE REVIEW

**Comment by keroxp** [comment]
Now ready for review.

**Comment by bartlomieju** [comment]
Sorry for delay @keroxp but I've been travelling. I'll review in the coming days

**Comment by keroxp** [comment]
@ry Would you start reviewing? It's hard to keep syncing branch to the latest...

This patch contains an important adjustment to HTTP/1.1 protocol about handling request from keep-alive connection. Yesterday I added new integration test cases in `racing_server_test.ts`. Those cases won't be passed in master branch.

**Comment by bartlomieju** [comment]
@keroxp sorry for the delay. I merge `master` into your branch; I don't have any comments for code; looks thoroughly tested. If CI goes green I think we can land it

**Comment by keroxp** [comment]
@bartlomieju Thanks! 
@ry How about?

**Comment by keroxp** [comment]
@ry Yeah thanks. I ported most of logic from my project (servestjs) but there may be bugs. I hope this patch improves deno's http stability.

**Pull request merged**
