### PR TITLE
fix(lsp): don't always use byonm resolver when DENO_FUTURE=1

### LINKED ISSUE #24863: regression lsp looks for a node_modules folder incorrectly
deno 1.45.5 (release, x86_64-unknown-linux-gnu)

```ts
import "npm:cowsay";
```

```
DENO_FUTURE=1 hx a.ts
```

-> lsp error 
```
Could not find a matching package for ‘npm:cowsay’ in a package. json
file. You must specify this as a package.json dependency when the
node_nodules folder is not managed by Deno.
```

without DENO_FUTURE set, it works correctly

### PR DESCRIPTION
**Pull request by dsherret**
Probably fixes #24863

Caused by https://github.com/denoland/deno/commit/a49d0bd10ba2a4745c291f3f413d97396213e4ec#diff-763c48dc07339b6f9b7800e2024d25f6ecd185d243f46a4416abc55917ccf0fcR446

I'm not bothering to add a test because we're going to completely revamp this in the coming weeks when we start work on Deno 2.0.

### CODE REVIEW

**Comment by dsherret** [comment]
@nayeemrmn the lsp_cjs_import_dual test seems to be failing because the script is at something like `/var/folders/v4/3smqxpkj0dx9w4cqs40nmh3c0000gn/T/`, but the node_modules directory gets canonicalized to `/private/var/folders/v4/3smqxpkj0dx9w4cqs40nmh3c0000gn/T/deno-cli-testku678u/node_modules/` and then loses the fact that it's byonm from the `/var/folders` scope. Any idea what we can do to solve this?

**Comment by nayeemrmn** [comment]
@dsherret Try checking against `*/node_modules/*` paths in `LspCache::is_valid_file_referrer()`

**Comment by dsherret** [comment]
Tried that just now and it causes `lsp_byonm_js_import_resolves_to_dts` to fail because that test opens files in the node_modules directory.

**Review by nayeemrmn — APPROVED** [review]
LGTM

**Pull request merged**
