### PR TITLE
feat(extensions/console): right align numeric columns in table

### PR DESCRIPTION
**Pull request by nicolasstucki**
Closes https://github.com/denoland/deno/issues/11294

The values of a column are left-aligned if and only if the column contains at least one non-numerical value.

#### Before
```
┌───────┬───────────┐
│ (idx) │ Values    │
├───────┼───────────┤
│ 0     │ "apples"  │
│ 1     │ "oranges" │
│ 2     │ "bananas" │
└───────┴───────────┘
```
#### After
```
┌───────┬───────────┐
│ (idx) │ Values    │
├───────┼───────────┤
│     0 │ "apples"  │
│     1 │ "oranges" │
│     2 │ "bananas" │
└───────┴───────────┘
```

### CODE REVIEW

**Comment by bartlomieju** [comment]
@nicolasstucki thanks! This looks great. Make sure to run `tools/format.js` and `tools/lint.js` to make CI happy.

**Comment by nicolasstucki** [comment]
`tools/format.js` added the missing `;`.

**Comment by nicolasstucki** [comment]
@bartlomieju CI is happy now.

**Comment by bartlomieju** [comment]
> @bartlomieju CI is happy now.

Thanks, since this is a feature PR we will land it after 1.13.2 is released later tonight

**Review by bartlomieju — APPROVED** [review]
LGTM

**Pull request merged**
