### PR TITLE
fix: handle signal 0 in process.kill

### PR DESCRIPTION
**Pull request by sigmaSd**
the last commit had a regression, where it removed this branch, I haven't tested the code  but I think it should work

### CODE REVIEW

**Comment by bartlomieju** [comment]
@sigmaSd could you add a test that calls this signal value?

**Comment by sigmaSd** [comment]
I updated the already present test

**Comment by sigmaSd** [comment]
A bit off-topic but:
Its unfortunate that deno follows golang std of trying to make unified interfaces where there isn't in reality, signals in kill are an example, windows don't have this concept, rust for example only expose <https://doc.rust-lang.org/std/process/struct.Child.html#method.kill> if one wants to use signals they will need to add a linux specific dependency like `nix`

More info here <https://fasterthanli.me/articles/i-want-off-mr-golangs-wild-ride#simple-is-a-lie>

**Review by littledivy — APPROVED** [review]
LGTM

**Pull request merged**
