### PR TITLE
Add native line ending conversion for Blob

### PR DESCRIPTION
**Pull request by kevinkassimo**

### CODE REVIEW

**Comment by piscisaureus** [comment]
I'm kind of against this. Native line endings are an arcane relic of the past that nobody wants.
Maybe we can support both \r\n and \n on input on all platforms, and write \n on output on all platforms?

**Comment by piscisaureus** [comment]
@ry thoughts?

**Comment by kevinkassimo** [comment]
@kevinkassimo I agree... It is somehow related to my question on Gitter about how well are we aiming for compatibility with web standard, since I feel some stuff are mostly legacy while some others just does not really make sense for server-side...

**Comment by kevinkassimo** [comment]
I would say it might be a better idea to just leave out web spec related but nonsensical stuff from deno and let some packages to introduce compatibility APIs. Closing this for now.

**Pull request closed without merging**
