### PR TITLE
feat(unstable): add Deno.systemCpuInfo()

### PR DESCRIPTION
**Pull request by eliassjogreen**
Related to #3802, I decided to not implement a node compatible `cpus` function due to the `sys_info` crate not fully supporting all the functionality needed (cpu model and times in different modes).

### CODE REVIEW

**Comment by caspervonb** [comment]
Hmm is there a struct we can expose here that is a single syscall that contains this information?

**Comment by eliassjogreen** [comment]
I'm not sure I understand, should the functions return structs instead or do you mean in the `sys_info` crate?

**Comment by bartlomieju** [comment]
> I'm not sure I understand, should the functions return structs instead or do you mean in the `sys_info` crate?

@eliassjogreen I'd be preferable to return this info in a single call instead of having two different ops. So maybe `Deno.systemCpuInfo` that returns `{ speed: number, cores: number }`?

**Comment by eliassjogreen** [comment]
Oops, rebased wrong. Will create a new pr...

**Pull request closed without merging**
