### PR TITLE
[WIP] Sandbox (VM) API (with REPL block scoped variable fix)

### PR DESCRIPTION
**Pull request by kevinkassimo**
Goal of this PR is to experiment to address #1159 at some point. With this prototype, when you run deno repl, you can
```
> const b = 1
undefined
> b
1
```

Current experiment exposes `makeContext` and `runInContext` to libdeno.

I am uncertain about almost everything about this PR (naming, whether expose directly in libdeno, v8, etc.)
(I'm still struggling to familiarize myself with v8...)

UPDATE:
Basic tests added.
Current prototype API:
```javascript
const s = deno.sandbox({a: 1, c: 0});
s.eval("a") // 1
s.env.b = 2;
s.eval("const d = 1; c = d + b");
s.env.c; // 3
```

### CODE REVIEW

**Comment by bartlomieju** [comment]
@kevinkassimo I managed to get exception details returned to JS side:
```
{
   "message":"ReferenceError: c is not defined",
   "frames":[
      {
         "line":1,
         "column":1,
         "functionName":"",
         "scriptName":"<sandbox>",
         "isEval":false,
         "isConstructor":false,
         "isWasm":false
      },
      {
         "line":133795,
         "column":44,
         "functionName":"eval",
         "scriptName":"gen/bundle/main.js",
         "isEval":false,
         "isConstructor":false,
         "isWasm":false
      },
      {
         "line":134046,
         "column":38,
         "functionName":"evaluate",
         "scriptName":"gen/bundle/main.js",
         "isEval":false,
         "isConstructor":false,
         "isWasm":false
      },
      {
         "line":134040,
         "column":11,
         "functionName":"replLoop",
         "scriptName":"gen/bundle/main.js",
         "isEval":false,
         "isConstructor":false,
         "isWasm":false
      }
   ]
}
```

Could you give me push access to the branch?

**Comment by kevinkassimo** [comment]
@bartlomieju sorry for the delay. Collaboration invitation sent

**Comment by kevinkassimo** [comment]
@bartlomieju I think there is some issue with processing stack trace here... Since the source-map related logic has been moved to Rust side, the JSON returned would be the location in the compiled script but not the original...

**Comment by kevinkassimo** [comment]
Hmm Travis now complains memory leak... I was using [`SetWeak`](https://v8.paulfryzel.com/docs/master/classv8_1_1_persistent_base.html#aebb8a2c97e219102f613ff3749c956f6) to let v8 decide when to cleanup ([same behavior as in Node's context](https://github.com/nodejs/node/blob/master/src/node_contextify.cc#L113))

**Comment by ry** [comment]
@kevinkassimo Sorry for the delayed review. It'll be another day before I can look at this fully. I think the leak detector is running properly - try running it yourself locally:
```
echo is_asan=true >> target/debug/args.gn
echo is_lsan=true >> target/debug/args.gn
export ASAN_OPTIONS=detect_leaks=1
./tools/build.py -C target/debug -j2
./target/debug/test_cc
```
It may be that you have to force a GC before calling `deno_delete()` in order to get the weak callbacks. You can try to use the `--expose-gc` flag and call `gc()` in JS.

**Comment by kevinkassimo** [comment]
So currently we encountered issues with `instanceof` and thus `console.log` not working as intended in a few scenarios, which is caused by the fact that the new context uses a completely different set of builtins. To make relevant behavior working we might need to define a bunch of property callbacks (as in [Node](https://github.com/nodejs/node/blob/8828426af45adc29847d0d20717c8fa3eb9bb523/src/node_contextify.cc#L148-L163))...

**Comment by bartlomieju** [comment]
@kevinkassimo this PR is very stale, maybe we can close it and start afresh?

**Comment by ry** [comment]
Yes.

**Pull request closed without merging**
