### PR TITLE
BUGFIX and refactor op_utime

### PR DESCRIPTION
**Pull request by dubiousjim**
As mentioned in a comment to #4428 after it was merged, some portion of the bug fix to op_utime, where it wasn't using `resolve_from_cwd(Path::new(&args.path))?;` accidentally got dropped. This resolves that.

### CODE REVIEW

**Comment by dubiousjim** [comment]
All the `path` arguments are passed through `cli/fs.rs`'s `resolve_from_cwd`, which I vaguely understand to be doing some normalizing. Have to go re-read it to be sure...

In this case, the `path` argument was passed through that function and then the result was erroneously ignored. The use of that function pre-dates my work on these functions. It's possible I introduced the erroneous ignoring. It would have been many many commits ago.

**Comment by dubiousjim** [comment]
> The use of that function pre-dates my work on these functions. It's possible I introduced the erroneous ignoring. It would have been many many commits ago.

The first sentence is wrong. I noticed in 69303e21495a14a2c6709f96af364682a485ac21 that all the other ops in that file were passing `path` through that function, but this one was not. So I added the use of `resolve_from_cwd` at that location. But for some reason, the patch was incomplete, and so the result was being ignored.

**Comment by ry** [comment]
I think we should remove the resolve_from_cwd instead. These file system syscalls are already resolved from cwd.

**Comment by dubiousjim** [comment]
Yeah, i didn't really understand why it was there. Here's the function, from `cli/fs.rs`:

```
pub fn resolve_from_cwd(path: &Path) -> Result<PathBuf, ErrBox> {
  let resolved_path = if path.is_absolute() {
    path.to_owned()
  } else {
    let cwd = current_dir().unwrap();
    cwd.join(path)
  };

  Ok(normalize_path(&resolved_path))
}
```

It's also copying a `&Path` into a `PathBuf`. But that can be inlined.

Should I take the `resolve_from_cwd` out of all the filesystem ops?

**Comment by dubiousjim** [comment]
Does Windows resolve from the cwd automatically? I guess we take that out and see what happens to the tests.

**Comment by ry** [comment]
Yes it does - all syscalls do. This is the purpose of cwd.

**Comment by ry** [comment]
Hi @dubiousjim - very sorry for the slow review (again). I don't think we need to call resolve_from_cwd, as that's what the posix fs does. Closing without merge.

**Pull request closed without merging**
