### PR TITLE
feat(cli): add ignore directives to bundled code

### PR DESCRIPTION
**Pull request by gliheng**
This fixes https://github.com/denoland/deno/issues/12949 adds ignore directives in deno bundle emitted code/

### CODE REVIEW

**Comment by bartlomieju** [comment]
Thanks for the PR, can you add a test that checks that these directives are present in the bundled code?

**Comment by gliheng** [comment]
Sure, will do.

**Comment by bartlomieju** [comment]
@gliheng looks good! It appears there are two failing tests:
- `integration::compile::standalone_error`
- `integration::compiler_api`
The former appears to have difference in line numbers in stack trace (which is expected, since you add 3 lines to all bundles), while the latter needs a bit more debugging to see what's going wrong. Let me know if you need any help.

**Comment by gliheng** [comment]
This latter one is caused by this line 
`assert(files["deno:///bundle.js"].startsWith("(function() {\n"));`
Since I added some comments at the front, this is no long true.
To fix this, either we only add ignore directives for deno bundle but not Deno.emit.
Or we add an option to toggle this in EmitOptions for Deno.emit. I dont't know which way is preferred. Any idea on this?

**Comment by gliheng** [comment]
I tried the first approach and PR was updated

**Comment by bartlomieju** [comment]
> I tried the first approach and PR was updated

I believe we should add the directives for `deno bundle` output, as well as for `Deno.emit()`. @kitsonk do you concur?

**Comment by gliheng** [comment]
@bartlomieju  These directives are also added to Deno.emit and updated test cases.

**Review by bartlomieju — APPROVED** [review]
LGTM, thank you @gliheng!

**Pull request merged**
