### PR TITLE
fix(bug/cli): formatting bench with colors

### PR DESCRIPTION
**Pull request by WingZer0o**
#18721 

Marking this is a draft first because I am tired and I have some test cases failing. This screenshot looks a bit better.
image

### CODE REVIEW

**Review by crowlKats — COMMENTED** [review]
implementation looks fine to me; could we get a test for this?

**Comment by WingZer0o** [comment]
Sure, would this test go under `cli\tools\test.rs`?

**Comment by crowlKats** [comment]
`cli/tests/integration/bench_tests.rs`

**Comment by WingZer0o** [comment]
Wouldn't that be a standard rust test case that would be included in said file addressed as #[test]? I do not see any of the test cases from `cli/tests/integration/bench_tests.rs` being run in `cargo test`

**Comment by bartlomieju** [comment]
> Wouldn't that be a standard rust test case that would be included in said file addressed as #[test]? I do not see any of the test cases from `cli/tests/integration/bench_tests.rs` being run in `cargo test`

They are definitely run, if you issue `cargo test integration::bench` you will see all tests from `cli/tests/integration/bench_test.rs` being run. `itest!` is our own helper macro that is expanded into a regular `#[test]`.

**Comment by WingZer0o** [comment]
I see now. Thanks for pointing me in the right direction I'll have a test for this tonight or tomorrow.

**Comment by WingZer0o** [comment]
`test integration::js_unit_tests::read_text_file_test` isn't failing on my local machine. Is there a way to retrigger the build without doing a commit?

**Comment by bartlomieju** [comment]
@WingZer0o unfortunately only maintainers can retrigger specific CI pipeline steps. I've merged `main` branch into your PR to retrigger CI.

**Comment by WingZer0o** [comment]
No problem. Looks like it passed this time, might be a flaky test. Let me know if anything needs to be revised.

**Review by crowlKats — APPROVED** [review]
LGTM, thanks

**Pull request merged**
