### PR TITLE
fix(coverage): ignore comments

### LINKED ISSUE #7652: Coverage output quirks
Screenshot_2020-09-24_at_11 56 08

- comments are marked as not covered

Screenshot 2020-09-24 at 12 05 13

- non-consecutive lines are collapsed together - there should be an empty line between them 

CC @caspervonb

### PR DESCRIPTION
**Pull request by caspervonb**
Ignores comments when tallying up line counts.

Closes #7652

### CODE REVIEW

**Comment by bartlomieju** [comment]
@caspervonb if I'm not mistaken after this PR we'd still be counting block comments `/** */`? I think we'll need some more robust solution possibly involving SWC to parse out which lines in source code are not comments, wdyt?

**Comment by caspervonb** [comment]
> @caspervonb if I'm not mistaken after this PR we'd still be counting block comments `/** */`? I think we'll need some more robust solution possibly involving SWC to parse out which lines in source code are not comments, wdyt?

Yep only single line comments being explicitly ignored at the moment (draft), will probably go with swc's token stream similar to the repl validator.

**Comment by caspervonb** [comment]
Rewrote this to use the token lexer instead of trying to manually scan for comments.
Just need to come up with some tests.

**Review by bartlomieju — APPROVED** [review]
LGTM, nice fix Casper

**Pull request merged**
