### PR TITLE
Experimental decorators

### PR DESCRIPTION
**Pull request by afinch7**
Added an option to enable experimental decorators for the typescript compiler.
I've also added in some room for other user configurable compiler options.

### CODE REVIEW

**Comment by bartlomieju** [comment]
We were pretty conservative about adding command line arguments, so it doesn't look like a good idea to add another flag just for TS option.

Also @kitsonk might be interested, I think he wanted to add custom compiler configs, but it was on hold due to recent compiler refactors.

**Comment by afinch7** [comment]
Is there some existing code for the compiler refactors, because I would like to give some input on that.

**Comment by afinch7** [comment]
On closer review I realized that if we change the compiler options deno won't automatically recompile the source unless it has changed. It will just use the last successful build unless the source changes. 

Put this one on indefinite hold I would rather invest time into getting a better system into a new compiler than continue down this road right now.

**Comment by kitsonk** [comment]
This should only be supported via supporting `tsconfig.json` in my opinion.  See #51.

The existing compiler refactors is largely done.  There is this issue #1738 which is what I am working on now, which I wanted to do before we tackled #51 (thought not directly related).  There is the restoring of compiler unit tests which we don't have a specific issue for, but it is a rather complex thing, which is directly related to the rewrite of Deno core though (as we need to create a build that loads the compiler isolate and executes the tests within that isolate).  Adding in the customer `tsconfig.json` support (or any other compiler feature) really needs that.

**Comment by afinch7** [comment]
@kitsonk Yep I think we are pretty much one the same page with this one. I submitted it and almost immediately had regrets, but I did make some useful discoveries. The most important thing I noted working on this is the ts language service doesn't need to reinitialized to update some settings. That means that at least some compiler settings can be changed without a huge cost to startup time.

**Pull request closed without merging**
