### PR TITLE
fix(URLPattern): Handle search parameters correctly in URLPattern with base URL

### LINKED ISSUE #24266: URLPattern with search parameters and base url doesn't work
Version: Deno 1.41, 1.44

```
deno repl   
Deno 1.44.2

> const p = new URLPattern("/api/data/", "http://localhost:8000")
p.exec("http://localhost:8000/api/data/?w=1&g=2")

null
```

```
// Chrome 126.0.6478.62

const p = new URLPattern("/api/data/", "http://localhost:8000")
p.exec("http://localhost:8000/api/data/?w=1&g=2")

{Object}
```

-----

```
Deno 1.44.2
exit using ctrl+d, ctrl+c, or close()
> const pattern = new URLPattern("/books/:id(\\d+)", "https://example.com");
console.log(pattern.test("https://example.com/books/123"))
true
console.log(pattern.test("https://example.com/books/123?d=1"))
false

```

```
// Chrome 126.0.6478.62

const pattern = new URLPattern("/books/:id(\\d+)", "https://example.com");
console.log(pattern.test("https://example.com/books/123"))
true
console.log(pattern.test("https://example.com/books/123?d=1"))
true
```

### PR DESCRIPTION
**Pull request by yazan-abdalrahman**
Ensure that URLPattern correctly parses and matches URLs with search parameters when a base URL is provided. This fixes the discrepancy where URLPattern in Deno was returning null for URLs with search parameters, unlike the behavior observed in Chrome.

- Adjusted URLPattern parsing to include search parameters when matching against base URLs.

Fixes #24266

### CODE REVIEW

**Comment by crowlKats** [comment]
@yazan-abdalrahman thank you for the PR, however the proper fix would be upstream in [rust-urlpattern](https://github.com/denoland/rust-urlpattern), and needs checking with the specification where we are actually wrong.
I will take a deeper look on sunday or monday.

**Comment by yazan-abdalrahman** [comment]
@crowlKats 
 I will take a look also

**Comment by yazan-abdalrahman** [comment]
@crowlKats 
I found the issue, which is with the UrlPatternInit constructor. I made the necessary changes, but certain tests failed because the behavior changed. I will fix it and push a pull request for review.

**Comment by yazan-abdalrahman** [comment]
@crowlKats  
please check this PR and read my comment

**Pull request closed without merging**
