### PR TITLE
Support repl multiline input

### PR DESCRIPTION
**Pull request by hayd**
This works, ~but I had to comment out the setTimeout test, maybe due to #1161.~

Note: It's not _interactive_ over multiple lines (only the last line is editable).

### CODE REVIEW

**Comment by kevinkassimo** [comment]
Yeah. This solution currently has problems like
```
> var a = "{";
```
it won't check if `{` is in quotes...

**Comment by ry** [comment]
I would just have a look at how node does this...

**Comment by kevinkassimo** [comment]
@hayd Actually your intuition is correct. Node does the following: 
https://github.com/nodejs/node/blob/8344f2458111904ad1de4ce08ffd9b4360ce81ed/lib/repl.js#L655-L668
```js
// If error was SyntaxError and not JSON.parse error
      if (e) {
        if (e instanceof Recoverable && !sawCtrlD) {
          // Start buffering data like that:
          // {
          // ...  x: 1
          // ... }
          self[kBufferedCommandSymbol] += cmd + '\n';
          self.displayPrompt();
          return;
        } else {
          self._domain.emit('error', e.err || e);
        }
      }
```
Also we might want to implement something similar to Node's `vm` that relies on binding to V8 context to make `let/const` work

**Comment by hayd** [comment]
I _think_ we can wait on some compiler improvements (to compile ts) by @kitsonk, once that is in, it could be refactored to include vm... I'm not sure it makes sense to define until then.

**Pull request merged**
