### PR TITLE
fix: `deno task` should forward double hyphens

### PR DESCRIPTION
**Pull request by dsherret**
When someone runs:

```
deno task node:test -- test-assert.js
```

It should forward everything after the task name like so:

```
Task node:test deno test --unstable --allow-all node/_tools/test.ts "--" "test-assert.js"
```

Currently it does:

```
Task node:test deno test --unstable --allow-all node/_tools/test.ts "test-assert.js"
```

### CODE REVIEW

**Review by bartlomieju — APPROVED** [review]
LGTM, thanks for a quick fix!

**Comment by jsejcksn** [comment]
@dsherret With this change, is it no longer possible to utilize the first element of `Deno.args` for any other value than `--` in a script that is run as a task command?

If that is the case, can you provide some clarity on why this change was requested and implemented?

**Comment by kt3k** [comment]
@jsejcksn
> With this change, is it no longer possible to utilize the first element of Deno.args for any other value than "--" in a script that is run as a task command?

Right, we can't pass the 1st arg to the internal script, and that looks like a bug to me.

I think we shouldn't parse anything in `<task_args>` and just pass everything to the internal command (like `yarn` does)

> deno task log_args -1

I think this should invoke `deno run log_args.ts -1` instead of throwing an error

What do you think? @dsherret @bartlomieju

**Comment by jsejcksn** [comment]
In additional testing, this change also appears to break the [`std/flags`](https://deno.land/std@0.137.0/flags) parser module. 😕

**Comment by dsherret** [comment]
It's correct that it's forwarding `--` now, but it should allow running `deno run log_args.ts -1`

**Pull request merged**
