### PR TITLE
fix(ext/console): Console log error with a Proxy of a Map

### PR DESCRIPTION
**Pull request by CGQAQ**
closed: #13991 

before
image

after this pr
image
I don't know if this is the right way to resolve this issue, if not please let me know the right way, I'll change the PR

### CODE REVIEW

**Review by kt3k — COMMENTED** [review]
@CGQAQ Thanks for the PR. Can you add a test case for `console.log(new Proxy(new Map(), {}));`?

**Comment by CGQAQ** [comment]
> @CGQAQ Thanks for the PR. Can you add a test case for `console.log(new Proxy(new Map(), {}));`?

sure

**Comment by kt3k** [comment]
BTW node and chrome seem doing the different things for this. Which do you think is better?

node
スクリーンショット 2022-03-19 20 55 58

chrome
スクリーンショット 2022-03-19 20 56 22

**Comment by CGQAQ** [comment]
I think chrome way is better, it just prints out proxyDetails and you can tell it's a proxy, not a vanilla Map. But that way will break a LOT of existing tests

**Review by kt3k — APPROVED** [review]
@CGQAQ LGTM. Thanks for the fix!

**Pull request merged**
