### PR TITLE
docs: document how to stop file watcher

### LINKED ISSUE #9399: watchFs is not abortable
Right now there is no way to cancel a watch on the file system.

This function will never return and is not abortable from the outside:
```typescript
async function* onDbChange(dbPath: string) {
  console.log(`Watching for changes to ${dbPath}...`);
  const watcher = Deno.watchFs(dbPath);
  for await (const event of watcher) {
    if (event.kind === 'modify') {
      yield;
    }
  }
}
```

Possible solution would be to pass an `AbortSignal`:

```typescript
Deno.watchFs(dbPath, { signal });
```

### PR DESCRIPTION
**Pull request by kt3k**
This PR documents how to stop the file watcher.

closes #9399

### CODE REVIEW

**Review by ry — APPROVED** [review]
LGTM - tho we should probably change this behavior to match the async iterators elsewhere.

**Comment by kt3k** [comment]
`.return()` seems a part of async iterator definition according to our dts file https://github.com/denoland/deno/blob/bf99300/cli/dts/lib.es2018.asynciterable.d.ts#L35

**Comment by jsejcksn** [comment]
> LGTM - tho we should probably change this behavior to match the async iterators elsewhere.

@ry While what @kt3k said is true, did you mean `watcher.close()`? Like here, for example?

https://doc.deno.land/builtin/stable#Deno.Listener

**Comment by ry** [comment]
@jsejcksn Yes, we should probably update the style guide to say something about how the `return()` method in AsyncIterators should not be used to close resources...

Unfortunately changing this in FsWatcher is a breaking change, so we'd need to deprecate the current behavior and phase it out before.

**Pull request merged**
