### PR TITLE
chore: update references to `deno_std` to use JSR

### PR DESCRIPTION
**Pull request by iuioiua**
There are more uses of `deno.land/std` in the codebase, but for URL parsing purposes rather than network calls or documentation.

### CODE REVIEW

**Comment by iuioiua** [comment]
Do you know why this isn't working, @dsherret?

**Comment by dsherret** [comment]
Change `typecheck_declarations_ns` to do `let context = TestContextBuilder::for_jsr().build();`. Also, the test server needs deno_std to be in the fake JSR registry under tests/testdata/jsr/registry. I'd recommend just adding the bare minimum to get it compiling.

**Comment by iuioiua** [comment]
It worked. Thank you. We should document this somewhere.

**Review by dsherret — APPROVED** [review]
LGTM!

**Pull request merged**
