### PR TITLE
Add radix to parseInt

### PR DESCRIPTION
**Pull request by kizerkizer**
Otherwise 0x... hexadecimal content-lengths could be parsed

### CODE REVIEW

**Comment by ry** [comment]
@kizerkizer I'm not sure I understand - are you saying that if a header "Content-Length: 0xabc" was sent that `parseInt("0xac")` would be successful? If so, I guess we should also add a test for this.

**Comment by kizerkizer** [comment]
> @kizerkizer I'm not sure I understand - are you saying that if a header "Content-Length: 0xabc" was sent that `parseInt("0xabc")` would be successful? If so, I guess we should also add a test for this.

I believe that's the behavior. I checked on MDN [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt).

**Comment by kizerkizer** [comment]
Looks like the basic case is failing? I’ll have to look into this more. It’s failing on “1776”.

**Comment by keroxp** [comment]
FYI: `Content-Length` must be a decimal number.  We shouldn't expect its value to be other formats.
https://tools.ietf.org/html/rfc2616#section-14.13

**Comment by kizerkizer** [comment]
> FYI: `Content-Length` must be a decimal number.  We shouldn't expect its value to be other formats.
> 
> https://tools.ietf.org/html/rfc2616#section-14.13

Is there a parser in between? The Tokyo layer? Then it’d be fine.

**Comment by ry** [comment]
Thanks for the patch @kizerkizer but I can't merge since it's red. Please resubmit if you feel inclined.

**Pull request closed without merging**
