### PR TITLE
BREAKING(unstable): remove --compat mode

### PR DESCRIPTION
**Pull request by bartlomieju**
This commit removes "compat" mode. We shipped support for "npm:" specifier support in v1.25 and that is preferred way to interact with Node code that we will iterate and improve upon. Compat mode adds a loooot of complexity and is ridden with strange bugs. 

I'm still not sure about removal of `--compat` - on one hand removal will break people's CIs, on the other I think it's better to break explicitly than accept this flag which will still break CI.

Effectively all issues below become irrelevant

- Closes https://github.com/denoland/deno/issues/15670
- Closes https://github.com/denoland/deno/issues/14662
- Closes https://github.com/denoland/deno/issues/14413
- Closes https://github.com/denoland/deno/issues/13883
- Closes https://github.com/denoland/deno/issues/13747
- Closes https://github.com/denoland/deno/issues/13424
- Closes https://github.com/denoland/deno/issues/13002
- Closes https://github.com/denoland/deno/issues/12482
- Closes https://github.com/denoland/deno/issues/13322
- Closes https://github.com/denoland/deno/issues/12495
- Closes https://github.com/denoland/deno/issues/13945

### CODE REVIEW

**Comment by bartlomieju** [comment]
Raised by @kt3k there's a question of polyfilling [`child_process.fork`](https://nodejs.org/api/child_process.html#child_processforkmodulepath-args-options). Before merging this PR we need to figure out how to handle that.

**Review by dsherret — APPROVED** [review]
LGTM!

**Comment by jsejcksn** [comment]
It looks like the manual wasn't updated in step with this change. Is there any process for coordinating changes and manual updates?

**Comment by dsherret** [comment]
As noted in https://github.com/denoland/manual/issues/388, the manual is being completely rewritten.

**Comment by jsejcksn** [comment]
> As noted in [denoland/manual#388](https://github.com/denoland/manual/issues/388), the manual is being completely rewritten so it's tracked there, but yeah this was missed.

@dsherret Thanks. I'm still interested to know if the rewrite will include some kind of process for coordinating manual updates when changes happen — in order to reduce the likelihood of these misalignments. Is that already the case or not at this time?

**Comment by dsherret** [comment]
The current process is to update the manual when making a CLI feature change. As stated, this was just missed (probably because it's unstable).

**Pull request merged**
