### PR TITLE
fix(info): revert #6978

### PR DESCRIPTION
**Pull request by lucacasonato**
This PR reverts the changes from commit #6978, re-adding the `--no-check` flag. This is a temporary measure until #6786 lands.

The reason for this is, is because `deno info` does not work at all with typescript files with type imports at the moment, because swc does not strip these. THis is an issue because when they are loaded in V8, it can not resolve the types in the imports anymore.

### CODE REVIEW

**Comment by lucacasonato** [comment]
> Is this the expected error?

Yes - we try to load a file with an import statement, importing a type into v8 (the type doesn't exist so it errors).

**Comment by nayeemrmn** [comment]
If it's temporary, sure it's not better to just flip the switch to always type check instead? Seems better than changing the API back and forth.

**Comment by ry** [comment]
@nayeemrmn It's temporary - yes.

**Comment by lucacasonato** [comment]
> If it's temporary, sure it's not better to just flip the switch to always type check instead? Seems better than changing the API back and forth.

we can revert this entire thing (minus the tests), once the other pr lands

**Pull request merged**
