### PR TITLE
upgrade: tokio 1.0

### PR DESCRIPTION
**Pull request by bartlomieju**
This commit upgrades all crates to "tokio 1.0" along with
crates from tokio ecosystem.

### CODE REVIEW

**Comment by yos1p** [comment]
I would like to help with upgrading test_util crate to tokio 1. #8885

**Comment by protheory8** [comment]
Is this PR still blocked by #8512?

**Comment by bartlomieju** [comment]
> Is this PR still blocked by #8512?

No, we're waiting for releases of `reqwest` and `tokio-tungstenite`

**Comment by caass** [comment]
links for me and/or others: [`tokio-tungstenite#142`](https://github.com/snapview/tokio-tungstenite/pull/142), [`reqwest#1076`](https://github.com/seanmonstar/reqwest/pull/1076)

**Comment by bartlomieju** [comment]
In `net_test.ts` there is a hang in `netHangsOnClose`. It is `op_read` that is hanging. Interesting finding is that if I close the connection from the other side (the side that wrote bytes `op_read` is hanging on) then `op_read` immediately unhungs.

**Review by piscisaureus — APPROVED** [review]

**Pull request merged**
