### PR TITLE
feat(fs): Add `isBlockDevice` to `FileInfo`

### PR DESCRIPTION
**Pull request by wafuwafu13**
[std::os::unix::fs::FileTypeExt](https://doc.rust-lang.org/std/os/unix/fs/trait.FileTypeExt.html) is defined in Rust.
`isFile`, `isDirectory`, `isSymlink` are defined in `Deno.FileInfo`, but `isBlockDevice`, `isCharacterDevice`, `isFIFO`, `isSocket` are not defined.
These are defined in [Node.js fs.Stats](https://nodejs.org/api/fs.html#class-fsstats), and it is good to be defined in `Deno.FileInfo` to improve compatibility.
In this PR, `isBlockDevice` is defined. If this PR is approved, I will add `isCharacterDevice`, `isFIFO`, `isSocket` as well in next PR.

### CODE REVIEW

**Comment by wafuwafu13** [comment]
[memo]
https://github.com/denoland/deno/actions/runs/3144203452/jobs/5109899791
```zsh
console.log(
      s,
      "||||||||||||||||||||||||||||||||||||||||||||||||||||||||\n",
);
console.log(
      s.isBlockDevice,
      "==========================================================\n",
);
{
  isFile: true,
  isDirectory: false,
  isSymlink: false,
  size: 5,
  mtime: 2022-09-28T14:15:07.768Z,
  atime: 2022-09-28T14:15:07.768Z,
  birthtime: 2022-09-28T14:15:07.768Z,
  dev: null,
  ino: null,
  mode: null,
  nlink: null,
  uid: null,
  gid: null,
  rdev: null,
  blksize: null,
  blocks: null,
  isBlockDevice: false
} ||||||||||||||||||||||||||||||||||||||||||||||||||||||||

false ==========================================================
```

TODO: edit https://github.com/denoland/deno/blob/6c55772f0d5101e0d2b8df3b0653a02e1581122f/runtime/js/30_fs.js#L208

**Review by littledivy — COMMENTED** [review]
I'm in favour. 

Although I should point out that we have too many fields in FileInfo. Deno does not have an API for `exists` / `access`.  Those cases will use `Deno.stat` and won't be accessing these meta fields at all.

**Review by aapoalas — APPROVED** [review]
LGTM: Can you rebase this?

**Review by aapoalas — CHANGES_REQUESTED** [review]
Requires a rebase.

**Pull request closed without merging**
