### PR TITLE
docs(lsp): Add Emacs eglot lsp configuration example

### PR DESCRIPTION
**Pull request by danielpza**
see https://github.com/joaotavora/eglot/issues/660#issuecomment-813100804

### CODE REVIEW

**Comment by kitsonk** [comment]
@danielpza if you could sign the CLA, I can take care of the linting and land this.

**Comment by danielpza** [comment]
@kitsonk  Signed, thanks.

**Comment by bartlomieju** [comment]
Something's wrong with this branch, after merging `main` there are no changes and I don't see any changes to docs about LSP in commit history. @danielpza could you reapply your changes? Sorry for the inconvenience.

**Comment by kitsonk** [comment]
Yeah, I meant to run linting on it, but it happened to have the same name of a branch as another patch that I tried to lint and fixup and ended up overwriting the commit.  @danielpza if you force push your local branch, it should resolve the issue.

**Comment by danielpza** [comment]
I don't have the commit locally it was all done from the github interface, however it was not a very verbose description on how to integrate with eglot, it mostly provided an example for the config.

Something along the lines "Inlcude this in your eglot/emacs config", see https://github.com/joaotavora/eglot/issues/660#issuecomment-813100804

```elisp
  (add-to-list 'eglot-server-programs '((js-mode typescript-mode) . (eglot-deno "deno" "lsp")))

  (defclass eglot-deno (eglot-lsp-server) ()
    :documentation "A custom class for deno lsp.")

  (cl-defmethod eglot-initialization-options ((server eglot-deno))
    "Passes through required deno initialization options"
    (list :enable t
	  :lint t))
```

**Review by bartlomieju — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
