### PR TITLE
chore(wpt): Implement timeouts for WPT tests.

### PR DESCRIPTION
**Pull request by andreubotella**
Helps with #11301

### CODE REVIEW

**Comment by andreubotella** [comment]
In CI, `/webstorage/storage_local_setitem_quotaexceedederr.window.html` is timing out as it should, but the websockets tests seem to stay under 60 seconds even though they don't when I run them in local.

**Comment by lucacasonato** [comment]
@andreubotella Debug vs release build disparity?

**Comment by andreubotella** [comment]
> @andreubotella Debug vs release build disparity?

On my machine, the websocket tests time out even with a release build. And with a debug build, `/webstorage/storage_setitem.window.html` also fails sometimes.

I think I'll set the expectations to the CI results.

**Comment by andreubotella** [comment]
So these are the timeouts I get on CI and on my machine:
- `/WebCryptoAPI/generateKey/successes_RSA-PSS.https.any.html?31-last` (debug mode CI)
- `/websockets/Create-blocked-port.any.html` (my machine, debug or release mode)
- `/websockets/Create-blocked-port.any.html?wpt_flags=h2` (my machine, debug or release mode)
- `/websockets/Create-blocked-port.any.html?wss` (my machine, debug or release mode)
- `/webstorage/storage_local_setitem_quotaexceedederr.window.html` (everywhere, including release mode CI)
- `/webstorage/storage_session_setitem_quotaexceedederr.window.html` (debug mode CI)

Looks like we need a way to mark tests as flaky.

**Comment by andreubotella** [comment]
The timeouts in worker tests that made this PR necessary are now resolved thanks to web-platform-tests/wpt#29970 and web-platform-tests/wpt#29848. However, there are still some worker tests that time out – in particular, tests which outside of a worker would end up in the event loop running out of tasks before the test would finish.

**Comment by bartlomieju** [comment]
@andreubotella @lucacasonato this PR has been stewing for almost half a year now, do we want to land it or should we close it?

**Pull request closed without merging**
