### PR TITLE
feat: bundle installed script

### PR DESCRIPTION
**Pull request by kt3k**
This partially addresses #5069. This PR bundles installed script and saved it next to the executable shell/batch script.

The command works like the below:
```
$ ./target/debug/deno install --allow-net https://deno.land/std/examples/echo_server.ts
Bundling https://deno.land/std/examples/echo_server.ts
Download https://deno.land/std/examples/echo_server.ts
Emitting bundle to "/Users/kt3k/.deno/bin/echo_server.js"
2661 bytes emmited.
✅ Successfully installed echo_server
/Users/kt3k/.deno/bin/echo_server
```

I checked 2 examples working on mac and windows:

```
./target/debug/deno install --allow-read https://deno.land/std/examples/cat.ts
./target/debug/deno install --allow-net https://deno.land/std/examples/echo_server.ts
```

- [x] check examples on windows.

Closes https://github.com/denoland/deno/issues/5069

### CODE REVIEW

**Comment by kt3k** [comment]
I checked the the command works on a windows machine as well.

@ry @bartlomieju PTAL

**Comment by bartlomieju** [comment]
Thanks @kt3k, can you fix the CI? I tried merging master but it seems it requires more changes. We'll try to land it for v1.1

**Comment by kt3k** [comment]
@bartlomieju Thank you for the ping! I'm trying.

**Comment by kt3k** [comment]
done!

**Comment by bartlomieju** [comment]
I tested locally and it works fine. Unfortunately https://github.com/denoland/deno/issues/4207 is still not resolved meaning that any script installed using TLA will break now.

**Comment by kitsonk** [comment]
> any script installed using TLA

Only top level for await...  TLA works fine.

**Comment by ry** [comment]
@kt3k can you rebase this? I would be interested in landing it now.

**Comment by kt3k** [comment]
@ry OK. I'll try today and tomorrow.

**Comment by kt3k** [comment]
Rebased!

By the way I dropped the copying of tsconfig into bin directory because this bundles the script into `.js` and `tsconfig.json` is no longer necessary for running the bundled script.

**Review by bartlomieju — APPROVED** [review]
LGTM, thank you @kt3k and sorry it took so long to land!

**Pull request merged**
