### PR TITLE
fix(lsp): code action imports of types are `import type`

### PR DESCRIPTION
**Pull request by kitsonk**
Fixes: #10776

### CODE REVIEW

**Comment by lucacasonato** [comment]
Wouldn't enabling `"importsNotUsedAsValues": "error"` result in more diagnostics than in the CLI (where this is not set to "error")?

I.e. wouldn't this error in LSP, but not `deno run`?

```ts
import { Foo } from "https://example.com/foo.ts";
const foo: Foo = { };
```

**Comment by kitsonk** [comment]
It does but, a) there is no other way to get TypeScript to import as `import type` when auto importing types, and b) while Deno CLI can run such code, it runs the risk of being "transpile unfriendly", so it encourages better code anyways.  I would be for setting it to `"error"` for CLI as well, as it avoids some problems people can get themselves into (like doing an `export * from "foo"` that is doing a named import from some other module, which we have seen in the wild).

Given the module *a.ts* of:

```ts
export interface A {
  a: string;
}

export const a = "a";
```

The following would have no diagnostics:

```ts
import { A, a } from "./a.ts";

const b: A = {
  a,
};

console.log(a);
```

The following would also not have any diagnostics:

```ts
import type { A } from "./a.ts";

const b: A = {
  a: "a"
};

console.log(a);
```

The following would have `This import is never used as a value and must use 'import type' because 'importsNotUsedAsValues' is set to 'error'.` for the import statement:

```ts
import { A } from "./a.ts";

const b: A = {
  a: "a"
};

console.log(a);
```

**Comment by lucacasonato** [comment]
Mh - this feels like it would slot into a larger discussion about the `importsNotUsedAsValues` option. We used to have it set to "error" (https://github.com/denoland/deno/pull/7413), but then reverted back to "remove" a few weeks later (https://github.com/denoland/deno/pull/7800). The "remove" option is unambiguous already with `isolatedModules: true`, so I don't know.

Very hesitant to land this in LSP without also landing for the rest of CLI. But doing so would result in a lot of churn for users for no big benefit that I can see.

**Comment by kitsonk** [comment]
🤷  I won't lose any sleep over it. It was only because people were reporting it as an issue.

**Comment by kitsonk** [comment]
Let's close this, as the potential pain ain't worth the squeeze.

**Pull request closed without merging**
