### PR TITLE
fix: empty include in config file excludes all

### LINKED ISSUE #20393: Empty `include` list in config file should exclude all
Currently it's the same as not specifying one.

Besides being a needless special case, same problems mentioned in https://github.com/denoland/vscode_deno/issues/908:

- If a user has a single element in their `include` list and they want to temporarily disable that path, they will delete it and unexpectedly enable everything.
- If `include` is determined programmatically, this is at best an annoying quirk to handle and worse if they don't know about it.

### PR DESCRIPTION
**Pull request by nayeemrmn**
Fixes #20393.

### CODE REVIEW

**Review by bartlomieju — COMMENTED** [review]
Does this change impact other editors besides vscode?

**Comment by nayeemrmn** [comment]
> Does this change impact other editors besides vscode?

This isn't LSP related, it's the `include` field in `deno.json`.

**Review by bartlomieju — APPROVED** [review]

**Comment by nayeemrmn** [comment]
> Could you update the manual after landing this PR?

I think this is an undocumented case, I can't find anything to update unless you can point me to it. The natural expectation is met now.

**Comment by bartlomieju** [comment]
@nayeemrmn we need to revert this PR, it causes test failures on `main` branch.

**Pull request merged**
