### PR TITLE
WebSocket Protocol and Version support

### PR DESCRIPTION
**Pull request by Industrial**
Hi.

These are the headers sent between client and server on the WebSocket: https://tools.ietf.org/html/rfc6455#section-11.3.5

This PR adds support for Protocol and Version headers.

### CODE REVIEW

**Comment by Industrial** [comment]
I'm not sure why the tests failed. It has nothing to do with my code, I think. What now?

**Comment by bartlomieju** [comment]
@Industrial I'm still interested in landing this PR, but to do that we'll need signed CLA and some small test case exercising new code.

**Comment by Industrial** [comment]
@bartlomieju Hi, I'm currently not in the position (hit some bad times) to write the test code and I will not be for several months probably. I signed the CLA.

**Comment by bartlomieju** [comment]
> @bartlomieju Hi, I'm currently not in the position (hit some bad times) to write the test code and I will not be for several months probably. I signed the CLA.

@Industrial sorry to hear that. I'll add test cases, thank you for your contribution.

**Comment by bartlomieju** [comment]
Closing in favor of https://github.com/denoland/deno/pull/8505

**Pull request closed without merging**
