### PR TITLE
refactor(std/testing): Get rid of default export and make std/testing/diff.ts private

### PR DESCRIPTION
**Pull request by tokiedokie**
## BREAKING

changes default export diff to not be defalt in std/testing/diff.ts and make std/testing/diff.ts private

### CODE REVIEW

**Comment by nayeemrmn** [comment]
This `std/testing/diff.ts` should be private IMO.

**Comment by tokiedokie** [comment]
@nayeemrmn I agree with your opinion

**Comment by bartlomieju** [comment]
@tokiedokie please rebase the branch

**Review by bartlomieju — APPROVED** [review]
LGTM

**Pull request merged**
