### PR TITLE
refactor: use primordials for extensions/timers

### PR DESCRIPTION
**Pull request by SimonRask**
I accidentally deleted the fork for Deno. Therefore I'm making this copy of #11234

Towards #11224

### CODE REVIEW

**Review by satyarohith — DISMISSED** [review]
In file `extensions/timers/02_performance.js`.
1. Line 18-21
```js
return performanceEntries
    .slice()
    .reverse()
    .find((entry) => entry.name === name && entry.entryType === type);
```
2. Line 219-242
```js
    clearMarks(markName) {
      if (markName == null) {
        performanceEntries = performanceEntries.filter(
          (entry) => entry.entryType !== "mark",
        );
      } else {
        performanceEntries = performanceEntries.filter(
          (entry) => !(entry.name === markName && entry.entryType === "mark"),
        );
      }
    }
    clearMeasures(measureName) {
      if (measureName == null) {
        performanceEntries = performanceEntries.filter(
          (entry) => entry.entryType !== "measure",
        );
      } else {
        performanceEntries = performanceEntries.filter(
          (entry) =>
            !(entry.name === measureName && entry.entryType === "measure"),
        );
      }
    }
```
3. Line 279
```js
      if (
        startOrMeasureOptions && typeof startOrMeasureOptions === "object" &&
        Object.keys(startOrMeasureOptions).length > 0
      )
```

**Comment by SimonRask** [comment]
@satyarohith Sorry I didn't mention this. I'm waiting for #10887 as per [this comment](https://github.com/denoland/deno/issues/11224#issuecomment-873288656)

**Comment by lucacasonato** [comment]
@SimonRask #10887 is now merged :-)

**Review by bartlomieju — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
