### PR TITLE
fix(docs): add another vscode-deno

### PR DESCRIPTION
**Pull request by justjavac**
I hope to add the vscode extension developed by me to the docs.

At the end of last year, I never updated this extension for 3 months due to work. Now I refactored the [typescript-deno-plugin](https://github.com/justjavac/typescript-deno-plugin) code to support import maps and other Deno features.

I am currently rewriting the plugin with LSP(like axetroy's). And I also created [deno_vscode_languageserver](https://github.com/denodev/deno_vscode_languageserver) repo, maybe in the future we can develop vscode language server with Deno itself.

-------------

the good idea is, to create a `denoland/vscode-deno` repo, and we jointly maintain the same code base.

cc @ry @lucacasonato @axetroy

### CODE REVIEW

**Comment by ry** [comment]
Hi @justjavac  : )
I'd be happy to manage denoland/vscode-deno - is @axetroy ok with this?

**Comment by lucacasonato** [comment]
That sounds like a great idea :-D

Maybe `denoland/vscode-extension` would be a better name?

**Comment by nayeemrmn** [comment]
> Maybe `denoland/vscode-extension` would be a better name?

Why organised repos have a redundant prefix: `/mnt/c/Users/Nayeem/projects/vscode-extension` :(

**Comment by axetroy** [comment]
The existence of multiple vscode extensions will trouble users

I am happy to move the repo to deno or denolib or merge with @justjavac

**Comment by justjavac** [comment]
> Hi @justjavac : )
> I'd be happy to manage denoland/vscode-deno - is @axetroy ok with this?

I sent him a message, but he hasn't respond me yet. Our time is 23:30, he may see the news tomorrow.

**Comment by justjavac** [comment]
Yes, we should cooperate, not split it.

**Comment by justjavac** [comment]
> > Maybe `denoland/vscode-extension` would be a better name?
> 
> Why organised repos have a redundant prefix: `/mnt/c/Users/Nayeem/projects/vscode-extension` :(

`denoland/vscode-extension` looks good

**Comment by ry** [comment]
Ok. I will setup the repo. Which one should I start from? https://github.com/justjavac/vscode-deno or https://github.com/axetroy/vscode-deno ?

**Comment by ry** [comment]
After looking into it a bit I will move @justjavac's repo, because it has fewer contributors - should be easier to merge @axetroy's work.

https://github.com/denoland/vscode_deno

Once we get CI setup, and @axetroy has merged his changes, I'll publish the plugin.

**Comment by hayd** [comment]
Atm @justjavac's is at the top of the "deno" search due to it's download numbers. I wonder if there's a way to transfer ownership and publish to that so denoland's becomes at the top.

**Comment by justjavac** [comment]
https://github.com/Microsoft/vscode/issues/21478#issuecomment-283118349

> There are really two approaches, both are not 100% ideal but I'll share them here:
> 
> 1. Ask `mjmcloug` to give you permission to publish the extension (this is possible through the marketplace management experience).  For example we regularly publish the `lukehoban.go` extension on Luke's behalf.  The upside here is all of the metadata for the extension remains intact (download count, rating, ...) the downside is that you can publish as `mjmcloug` and that may not be desirable.
> 
> 2. Deprecate the existing extension by publishing an update and point users to the next extension.  This is something we did for `editorconfig` and `sql`.  The pros here are that you get a fresh new identity and total control of publishing.  The downside is some customer action is required and the metadata is lost.

We can also use the second option, just like `vscode-mssql`:

1. Publish `denoland/vscode_deno`(or other name) on the VS Code Marketplace.

2. I marked my extension as deprecated.

```diff
 {
-  "deno.displayName": "Deno",
-  "deno.description": "Deno support for VSCode",
+  "deno.displayName": "[Deprecated] Deno",
+  "deno.description": "*Deprecated*. Get official 'deno' extension from the VS Code Marketplace.",
```

3. Every time the user activates this extension `justjavac/vscode-deno`, will show the info message to tell users to install the official extension

```ts
const extensionUpgradeMessage = "This prototype is deprecated. Get official 'deno' extension from the VS Code Marketplace.";
vscode.window.showInformationMessage(extensionUpgradeMessage, 'Go to VS Code Marketplace' ).then(selected => {
    if (selected === 'Go to VS Code Marketplace') {
        open('https://marketplace.visualstudio.com/items?itemName=denoland.vscode_deno');
    }
});
```

**Comment by justjavac** [comment]
People always like to install the most downloaded, but no one will install an deprecated extension

**Pull request closed without merging**
