### PR TITLE
fix: remove intellij module configuration

### PR DESCRIPTION
**Pull request by orvitpng**

### CODE REVIEW

**Comment by kitsonk** [comment]
What issue is this causing?

**Comment by orvitpng** [comment]
> What issue is this causing?

Not a major issue, but when using IntelliJ, it will create a `deno.iml` file if used as a module, which is nice to add to gitignore.

**Comment by kitsonk** [comment]
In my opinion this is something you should do in your [local environment](https://git-scm.com/docs/gitignore) by adding to `$GIT_DIR/info/exclude`.

**Comment by orvitpng** [comment]
> In my opinion this is something you should do in your [local environment](https://git-scm.com/docs/gitignore) by adding to `$GIT_DIR/info/exclude`.

I thought it'd be useful as `.idea` and `.vscode` are both in the .gitignore.

**Comment by orvitpng** [comment]
Obviously very stale.

**Pull request closed without merging**
