### PR TITLE
fix(fetch): set content-length for empty POST/PUT

### LINKED ISSUE #11920: bug(ext/fetch): content-length is not set to 0 when body is not present with PUT/POST
According to fetch spec, we should be setting `content-length` to 0 if no body is provided with a `PUT`/`POST` request.

Spec URL: https://fetch.spec.whatwg.org/#http-network-or-cache-fetch (under section 4.6 point 8.6).

Browsers do, Deno doesn't.

image

### LINKED ISSUE #12597: [fetch] Content-Length not set on fetch
Hello 👋 

Simplest example i just tested right now

Possibly related: https://github.com/denoland/deno/pull/12451/files#diff-1d2654eb8b069ed838b6477304b52294806eb59c1e99f646acab2b39d583a72bR388 @AaronO 

```ts
await fetch("https://google.com", {
  method: "PUT",
  headers: {
    Authorization: "Token 123",
    "User-Agent": "idk whatever",
  // COMMENT THIS LINE TO GET A 411 ERROR. WITH THIS LINE YOU GET A 405 ERROR WHICH IS THE EXPECTED ERROR
    "Content-Length": "0"
  },
})
  .then(console.log)
  .catch(console.error);
```

deno 1.15.3 (release, x86_64-unknown-linux-gnu)
v8 9.5.172.19
typescript 4.4.2

Thank You

### PR DESCRIPTION
**Pull request by lucacasonato**
This commit changes `fetch` to set `content-length: 0` on POST and PUT
requests with no body.

The relevant fetch spec text:
image

Fixes #12597
Fixes #11920

### CODE REVIEW

**Review by AaronO — APPROVED** [review]
LGTM

**Comment by AaronO** [comment]
Might be useful to link to the spec in the comment

**Comment by andreubotella** [comment]
Are there no WPT tests for this?

**Comment by lucacasonato** [comment]
> Are there no WPT tests for this?

Couldn't find any. We should add some, but I didn't have the nerve to do it right now, considering we are releasing today 😉

**Comment by DjDeveloperr** [comment]
Also fixes #11920

**Pull request merged**
