### PR TITLE
BREAKING: Remove support for .wasm imports

### PR DESCRIPTION
**Pull request by bartlomieju**
Importing .wasm files is non-standardized therefore deciding to
support current functionality past 1.0 release is risky.

Besides that .wasm import posed many challenges in our codebase
due to complex interactions with TS compiler which spawned
thread for each encountered .wasm import.

This commit removes:
- cli/compilers/wasm.rs
- cli/compilers/wasm_wrap.js
- two integration tests related to .wasm imports

### CODE REVIEW

**Comment by hayd** [comment]
Couldn't it be --unstable, wasm support is a huge win.

**Comment by bartlomieju** [comment]
@hayd WASM is still supported, this PR only removes `import "./foo.wasm";` support.

You can still use `WebAssembly` API:
```ts
const bytes = new Uint8Array([
  0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00, 0x01, 0x07, 0x01, 0x60,
  0x02, 0x7f, 0x7f, 0x01, 0x7f, 0x03, 0x02, 0x01, 0x00, 0x07, 0x07, 0x01,
  0x03, 0x61, 0x64, 0x64, 0x00, 0x00, 0x0a, 0x09, 0x01, 0x07, 0x00, 0x20,
  0x00, 0x20, 0x01, 0x6a, 0x0b
]);

async function main() {
  const wasm = await WebAssembly.instantiate(bytes);
  const result = wasm.instance.exports.add(1, 3);
  console.log("1 + 3 =", result);
  if (result != 4) {
    throw Error("bad");
  }
}

main();
```

**Comment by kevinkassimo** [comment]
Sad to see it go, but I guess we can bring it back some time in the future once we figure out what could be the best solution.

**Comment by ry** [comment]
@kevinkassimo that's the idea. I'm also sad to see this go, but it's hindering refactors in the compiler and a case can be made that wasm imports are not standard. I think we'll have this feature back relatively soon.

**Comment by annymosse** [comment]
:cry: Really so sad to see this super wanted feature get out from :sauropod: travels stories.

**Pull request merged**
