### PR TITLE
feature: Deno.ttySize()

### PR DESCRIPTION
**Pull request by sinclairzx81**
This PR implements the `Deno.ttySize()` API for obtaining the current terminal dimensions `columns/rows`. This update takes a dependency on the [crossterm](https://github.com/crossterm-rs/crossterm) crate which should facilitate cross platform queries for current terminal dimensions.

PR is submitted for review and feedback with reference to issue #3456

### CODE REVIEW

**Comment by bartlomieju** [comment]
I wonder if [`enable_raw_mode`](https://docs.rs/crossterm/0.14.2/crossterm/terminal/fn.enable_raw_mode.html) will work with Tokio's stdio just like that 🤔 that would save us a lot of headache

**Comment by ry** [comment]
Actually I'm having second thoughts about crossterm because we have a lot of TTY crates and I would either like to reduce them to a single dependency, and it doesn't seem like crossterm would allow that.

* https://crates.io/crates/rustyline We use this for the REPL. But it seems like crossterm doesn't have very good readline support - https://github.com/crossterm-rs/crossterm/issues/55 ... If we could replace rustyline with crossterm I would be all for it.
* https://crates.io/crates/atty a small utility that allows us to call the isatty syscall (and works on windows).. Doesn't seem crossterm provides this either.
* https://crates.io/crates/ansi_term https://crates.io/crates/termcolor stupidly we have two color crates. These could certainly be combined and it seems like crossterm does know how to do colors - so this is fine.

So I wonder if there is a smaller crate which can provide the functionality? Or can we just rip out the implementation from crossterm? We can certainly issue the `ioclt` ourselves without much difficulty https://stackoverflow.com/questions/1022957/getting-terminal-width-in-c

**Comment by sinclairzx81** [comment]
@ry Hi, thanks, yes, sorry, missed the unit test code in there, thanks for moving that.

Happy to keep an eye on this and help out on any enhancements down the road. I am guessing this is all fairly preliminary at this point, so happy to follow along with all design considerations on the tty api as things progress.

Many thanks

**Comment by ry** [comment]
Wow I totally forgot that we've already got term width/height in our code:

https://github.com/denoland/deno/blob/c824eb5817db675be4d9966a0d1a43d90dfa61fd/cli/shell.rs#L398

I'm not sure what to do yet, but I'm more convinced that we need to clean up the TTY crate situation rather than adding a new dep.

**Comment by ry** [comment]
Thanks for the patch @sinclairzx81  but I'm going to close without merge. I don't want to add this crossterm dep. This ttySize op is definitely desirable, but I think we can achieve it (at least on unix) with a single line as I gave above.

**Comment by apatrida** [comment]
@ry it seems like you'll need something like CrossTerm anyway for node `tty` support.  Resize event can be had via signals already, but we are missing `columns`, `rows` that this patch was focusing on, and `clearLine`, `clearScreenDown`, `cursorTo`, `moveCursor`, `getColorDepth`, `hasColors` (covered by `noColor`?), ... Some are just ANSI sequences, but not all.

**Comment by Yamboy1** [comment]
Any update on this? My current deno readline-esque implementation for my shell is broken when you hit the edge of the terminal, not sure if I can go any further without checking the size of the terminal as well as resize events

https://github.com/Yamboy1/denosh

**Pull request closed without merging**
