### PR TITLE
fix(ext/http): patch regression in variadic args to serve handler

### PR DESCRIPTION
**Pull request by jflatow**
I'm not sure what was the purpose of trying to be so clever with the args were (maybe an optimization?), but it breaks variadic args as pointed out in #20054.

### CODE REVIEW

**Comment by mmastrac** [comment]
Unfortunately there is a pretty significant performance hit when generating all the args for handlers that don't need them. For delegation, we recommend requesting the args directly and forwarding those, rather than using arguments or rest params.

**Comment by mmastrac** [comment]
Closing this one -- if there is a way we can avoid taking a hit on perf if those parameters are not requested, we can revisit this.

**Comment by jflatow** [comment]
> Unfortunately there is a pretty significant performance hit when generating all the args for handlers that don't need them. For delegation, we recommend requesting the args directly and forwarding those, rather than using arguments or rest params.

What benchmark are we looking at for this? Maybe I can figure something out

**Comment by mmastrac** [comment]
Thanks for your contribution, we definitely appreciate someone looking at this. If you'd like to give it a shot, you can run this benchmark (https://gist.github.com/mmastrac/ac3855dd1f8c80d6b166557ecad5fbc7) against any possible solutions.

Note that we might be able to detect variadic handlers by checking the function's string representation against a regex (ie: does `...` appear before the first `)`), however I haven't fully thought through that solution.

**Comment by jflatow** [comment]
Thanks. Yeah parsing the string could sort of work, but still a little weird as it wouldn't handle `arguments`. One question I have is, what kind of serious servers are completely ignoring the request? I have a hard time imagining a good use case for that one. If the bulk of the cost comes from the second arg and that's what we're worried about, perhaps we could just handle that case specially? I'll do some benchmarking before proposing anything.

**Comment by jflatow** [comment]
Actually, I don't really detect any performance penalty as is (or improvement from the supposed optimization). I think this PR should be re-opened since the sneaky change in behavior for `...args`/`arguments` is truly undesirable and unexpected IMO. Here's a [benchmark for this branch](https://github.com/denoland/deno/commit/f87bb7697a268fe201f0b47280828d985724d795) compared to a [baseline benchmark against main](https://github.com/denoland/deno/commit/a2f173c339ace82817ffb60acb54eb89ba913d97).

**Comment by jflatow** [comment]
Actually, I don't really detect any performance penalty as is (or improvement from the supposed optimization). I think this PR should be re-opened since the sneaky change in behavior for `...args`/`arguments` is truly undesirable and unexpected IMO. Here's a [benchmark for this branch](https://github.com/denoland/deno/commit/85b24d54c7d05afc319397bae3006282ed3851a0) compared to a [baseline benchmark against main](https://github.com/denoland/deno/commit/e09b6a001b580ae21f617aec97c108ff22a04718).

**Comment by mmastrac** [comment]
@jflatow Thanks for running those. Can you run a test using wrk instead? The fetch implementation isn't currently enough to saturate a serve handler

**Comment by jflatow** [comment]
Here are some sample results I got using `deno run serve.ts` on the [baseline](https://github.com/denoland/deno/commit/e09b6a001b580ae21f617aec97c108ff22a04718):

```
[jflatow@Jareds-Air deno]$ wrk -d 10s --latency http://localhost:8080
Running 10s test @ http://localhost:8080
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.29ms    0.90ms  26.53ms   95.02%
    Req/Sec     3.99k   400.04     4.41k    87.00%
  Latency Distribution
     50%    1.09ms
     75%    1.43ms
     90%    1.87ms
     99%    3.20ms
  79413 requests in 10.00s, 11.36MB read
Requests/sec:   7938.24
Transfer/sec:      1.14MB

[jflatow@Jareds-Air deno]$ wrk -d 10s --latency http://localhost:8081
Running 10s test @ http://localhost:8081
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.26ms  522.61us  10.95ms   87.82%
    Req/Sec     4.02k   400.31     4.43k    89.00%
  Latency Distribution
     50%    1.09ms
     75%    1.41ms
     90%    1.86ms
     99%    3.11ms
  80058 requests in 10.01s, 11.45MB read
Requests/sec:   7999.10
Transfer/sec:      1.14MB

[jflatow@Jareds-Air deno]$ wrk -d 10s --latency http://localhost:8082
Running 10s test @ http://localhost:8082
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.23ms  699.15us  25.88ms   92.87%
    Req/Sec     4.16k   311.41     4.82k    81.50%
  Latency Distribution
     50%    1.04ms
     75%    1.34ms
     90%    1.79ms
     99%    3.04ms
  82936 requests in 10.02s, 11.86MB read
Requests/sec:   8278.84
Transfer/sec:      1.18MB
```

And here are the results from the [patched benchmark](https://github.com/denoland/deno/commit/85b24d54c7d05afc319397bae3006282ed3851a0):

```
[jflatow@Jareds-Air deno]$ wrk -d 10s --latency http://localhost:8080
Running 10s test @ http://localhost:8080
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.21ms  500.53us  10.02ms   87.89%
    Req/Sec     4.17k   276.71     4.83k    78.50%
  Latency Distribution
     50%    1.04ms
     75%    1.34ms
     90%    1.80ms
     99%    3.04ms
  82908 requests in 10.00s, 11.86MB read
Requests/sec:   8289.56
Transfer/sec:      1.19MB

[jflatow@Jareds-Air deno]$ wrk -d 10s --latency http://localhost:8081
Running 10s test @ http://localhost:8081
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.19ms  470.90us   8.10ms   87.14%
    Req/Sec     4.23k   369.22     4.93k    79.21%
  Latency Distribution
     50%    1.02ms
     75%    1.32ms
     90%    1.77ms
     99%    2.93ms
  84981 requests in 10.10s, 12.16MB read
Requests/sec:   8412.13
Transfer/sec:      1.20MB

[jflatow@Jareds-Air deno]$ wrk -d 10s --latency http://localhost:8082
Running 10s test @ http://localhost:8082
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.22ms  489.18us  10.14ms   87.03%
    Req/Sec     4.13k   388.32     4.62k    80.69%
  Latency Distribution
     50%    1.06ms
     75%    1.39ms
     90%    1.81ms
     99%    2.97ms
  83092 requests in 10.10s, 11.89MB read
Requests/sec:   8224.54
Transfer/sec:      1.18MB
```

I'm not really sure why it's necessary to perform this test under intense load, but here it is. I think it's okay?

**Comment by mmastrac** [comment]
Let me take a closer look here. The numbers from wrk are much lower than they should be in both cases.

**Comment by mmastrac** [comment]
The benchmarks suggest this is slightly faster or approximately the same, so I'm inclined to land this. The original reason we did this was for performance and it looks like switching to the class has made that reason moot.

I'll set this to merge when the build passes. Thanks!

**Review by mmastrac — APPROVED** [review]
LGTM!

**Pull request merged**
