### PR TITLE
feat(std/hash): reimplement all hashes in rust

### PR DESCRIPTION
**Pull request by skdltmxn**
This PR reimplements all hash algorithms in std/hash in rust (Rust Crypto).
Also I have defined a new interface `Hasher` ensuring all hash algorithms have uniform API structure.
I believe we should deprecate existing hashes that don't implement `Hasher` interface.

All supported hash algorithms are as below.

- md2
- md4
- md5
- ripemd160
- ripemd320
- sha1
- sha224
- sha256
- sha384
- sha512
- sha3-224
- sha3-256
- sha3-384
- sha3-512
- keccak224
- keccak256
- keccak384
- keccak512

### CODE REVIEW

**Comment by ry** [comment]
@skdltmxn Interesting! Do you have some performance benchmarks?

**Comment by skdltmxn** [comment]
@ry Here's the benchmark result!
- CPU: i7-8700
- RAM: 32G
- Deno 1.0.4 release

| Algorithm | Time |
| --- | --- |
| md2 | 292ms |
| md4 | 240ms |
| md5 | 233ms |
| ripemd160 | 237ms |
| ripemd320 | 249ms |
| sha1 | 241ms |
| sha224 | 242ms |
| sha256 | 256ms |
| sha384 | 260ms |
| sha512 | 272ms |
| sha3-224 | 252ms |
| sha3-256 | 248ms |
| sha3-384 | 263ms |
| sha3-512 | 264ms |
| keccak224 | 250ms |
| keccak256 | 250ms |
| keccak384 | 257ms |
| keccak512 | 264ms |

**Comment by halvardssm** [comment]
I think this is a great contribution! I would love to see bcrypt and argon2 integrated as well, would this be possible to include? I found [this crate providing bcrypt](https://docs.rs/rust-crypto/0.2.36/crypto/) and [this crate providing argon2](https://docs.rs/just-argon2/1.2.0/argon2/)

**Comment by skdltmxn** [comment]
@ry Can you please elaborate about WASM? I'm not clear on the best practice of using WASM in this case.

Thanks!

**Comment by ry** [comment]
@skdltmxn Unfortunately our WASM story isn't complete - because one is unable to "import" wasm files. They must be loaded at runtime. 

That said, have a look at these projects to get an idea of how this works currently:
https://twitter.com/deno_land/status/1266750050681708545

**Comment by caspervonb** [comment]
Hit me up on the project's discord if you need a hand in porting this to WebAssembly @skdltmxn.

**Comment by skdltmxn** [comment]
Closing PR in favor of #6292

**Pull request closed without merging**
