### PR TITLE
fix(npm): check if module actually has __esModule set to true

### LINKED ISSUE #15865: Unable to import `npm:eslint-plugin-jsdoc@39.3.6`
Running the following file:
```js
import "npm:eslint@8.23.0";
import jsdoc from "npm:eslint-plugin-jsdoc@39.3.6";
console.log(jsdoc);
```
results in `undefined` being logged.
When running with the inspector, it seems like index.js.deno_cjs_to_esm.mjs is trying to `export default mod["default"];`, but 'mod' is already the default so this should `export default mod;` 

I'm using Deno 1.25.2+ffffa2f

### PR DESCRIPTION
**Pull request by dsherret**
Previously we were just relying on the cjs export analysis for this, but there are some scenarios where packages do strange things that means the analysis might not line up with what's actually done.

Closes #15865

### CODE REVIEW

**Comment by guybedford** [comment]
In Node.js itself, this is handled by always treating `default` as the `module.exports` CJS exports object, even in the case of `__esModule`. The reason we do this in Node.js is that because the static exports detection is not always fully accurate, having the ability for `import mod from 'mod'` to always directly correspond to the `module.exports` CJS object in every single case is important to maintain as a baseline. This is also the source of interop frictions unfortunately, but the ecosystem and tooling have already started to accept and deal with this!

**Comment by dsherret** [comment]
@guybedford yeah, the node esm -> node cjs in Deno works that way like Node. I wanted to see how far we could get with the deno esm importing node cjs doing it this way as it seems to be more compatible with the ecosystem.

**Comment by guybedford** [comment]
Okay, just remember this is another moving target for bundlers and other tooling to follow as well. Is the Deno exports analysis accurate enough for it that you don't risk masking the default / losing access to bindings at all?

**Comment by dsherret** [comment]
> Okay, just remember this is another moving target for bundlers and other tooling to follow as well.

I don't think this specific part will be too much trouble, but yes it's yet another thing.

> Is the Deno exports analysis accurate enough for it that you don't risk masking the default / losing access to bindings at all?

I'm not sure and we'll find out. I'm hoping that in combination with this new runtime check it will be accurate enough. I was thinking that the runtime check should also fall back to using the module when the "default" export doesn't exist as well, but TypeScript doesn't do that and I was trying to align with TypeScript's esmodule interop here.

**Comment by guybedford** [comment]
> I don't think this specific part will be too much trouble, but yes it's yet another thing.

Configuring bundlers to bundle with ESM - CJS interop in "Deno mode" as distinct from "legacy" and "nodeesm" is definitely a new layer of complexity to handle.

> I'm not sure and we'll find out.

Is there some way to lower the risk in the process?

> I'm hoping that in combination with this new runtime check it will be accurate enough.

__esModule cases can be highly dynamic by it's nature of being a runtime check. Static analysis will always have cases missed I think. And in those cases, if there is a `default` export, you risk not being able to get access to the bindings _at all_. Unless I'm missing particular details about how Deno is supporting this?

> I was thinking that the runtime check should also fall back to using the module when the "default" export doesn't exist as well, but TypeScript doesn't do that and I was trying to align with TypeScript's esmodule interop here.

So if there is a `exports.__esModule = true; exports.name = 'name';` with no `default` export, `import m from 'm'` would be the direct module you mean? I think that would be worthwhile to have for Node.js compat.

When there are names and default and __esModule, default interop is very variable between bundlers and Node.js so that most authors are naturally tending towards not doing it anyway. Leaving all the interop issues to this particular combination can be fine to do as well, although I would obviously prefer full Node.js parity on interop for Node.js compat!

**Comment by dsherret** [comment]
> __esModule cases can be highly dynamic by it's nature of being a runtime check. Static analysis will always have cases missed I think. And in those cases, if there is a default export, you risk not being able to get access to the bindings at all. Unless I'm missing particular details about how Deno is supporting this?

Yes, this is the one risk case—where it has identified a default export and __esModule === true, and the analysis fails to identify a named export. In this case, the named export would be lost. I think you're right that we should probably just revert to doing exactly as node does in its cjs interop and make the default export always the module. I was hoping to see though how big of an issue this was and if we'd be able to overcome it.

> So if there is a exports.__esModule = true; exports.name = 'name'; with no default export, import m from 'm' would be the direct module you mean? I think that would be worthwhile to have for Node.js compat.

Yes, exactly. I updated the PR to include this for now.

**Comment by dsherret** [comment]
One example of something we'd never be able to statically analyze:

```ts
const fileData = JSON.parse(fs.readFileSync(...));

for (const exportName of Object.keys(fileData)) {
  exports[exportName] = ...
}
```

**Comment by dsherret** [comment]
I'm going to open a new PR that aligns the Deno esm importing Node cjs with Node esm importing Node cjs. As mentioned, it will be impossible for us to analyze all named exports in certain scenarios. Thanks for the feedback, @guybedford!

**Comment by dsherret** [comment]
Opened https://github.com/denoland/deno/pull/15879

**Pull request closed without merging**
