### PR TITLE
chore: deprecate `Deno.Reader`, `Deno.ReaderSync`, `Deno.Writer`, `Deno.WriterSync` and `Deno.Closer`

### PR DESCRIPTION
**Pull request by iuioiua**
This change deprecates `Deno.Reader`, `Deno.ReaderSync`, `Deno.Writer`, `Deno.WriterSync` and `Deno.Closer` in favour of the [Web Streams API](https://developer.mozilla.org/en-US/docs/Web/API/Streams_API). After discussing with Yoshiya, we both thought now might be the right time to deprecate these interfaces with v2 getting closer.

### CODE REVIEW

**Review by ry — APPROVED** [review]
LGTM

**Comment by bartlomieju** [comment]
@iuioiua are there any APIs in `deno_std` that use these types that are not deprecated?

**Comment by iuioiua** [comment]
In std, we use a [types.d.ts](https://github.com/denoland/deno_std/blob/84a1373b394a34e69cb86f0be208d6047e5fc541/io/types.d.ts) file which copies these IO interfaces exactly. Sub-modules that use these identical interfaces from types.d.ts and are not deprecated include:
* `std/archive` - https://github.com/denoland/deno_std/pull/1985 aims to migrate to the Web Streams API.
* `std/log`

**Comment by iuioiua** [comment]
Sidenote: IMO, having these identical types is confusing, and I think we should remove them and use `Deno.*` types.

**Review by bartlomieju — APPROVED** [review]
> In std, we use a [types.d.ts](https://github.com/denoland/deno_std/blob/84a1373b394a34e69cb86f0be208d6047e5fc541/io/types.d.ts) file which copies these IO interfaces exactly. Sub-modules that use these identical interfaces from types.d.ts and are not deprecated include:
> 
> * `std/archive` - [feat: web streams based archive/tar deno_std#1985](https://github.com/denoland/deno_std/pull/1985) aims to migrate to the Web Streams API.
> * `std/log`

I spoke with @crowlKats about `std/archive` and it seems we could do compression side, but decompression is currently blocked 🤔 As for `std/log` - could we rewrite it to use Web streams APIs instead?

That said, I think these two shouldn't be a blocker for landing this deprecation

**Comment by iuioiua** [comment]
> I spoke with @crowlKats about `std/archive` and it seems we could do compression side, but decompression is currently blocked 🤔

Yeah, I looked into it and couldn't fix the issue. See [here](https://github.com/denoland/deno_std/pull/1985#issuecomment-1846503350).

> As for `std/log` - could we rewrite it to use Web streams APIs instead?

Yep, I've already created an issue to do that [here](https://github.com/denoland/deno_std/issues/3907).

> That said, I think these two shouldn't be a blocker for landing this deprecation

Agreed.

**Comment by mmastrac** [comment]
Landing for v1.39

**Pull request merged**
