### PR TITLE
[wip] perf: snapshot deno_runtime ops

### PR DESCRIPTION
**Pull request by littledivy**
Work in progress...

Depends on https://github.com/denoland/deno_core/pull/303

Introduces 3 traits to do `deno_runtime` functionaility from the extension: `RuntimePermission`, `WorkerHost`, `WebWorkerHost`

### CODE REVIEW

**Comment by mmastrac** [comment]
This is a great result, but can we do it without creating another crate? CLI already depends on the runtime. What if we split op registration from JS registration?

**Comment by littledivy** [comment]
@mmastrac Sure, what do you propose? 

IMO Ideally, in the startup path new ops should **not** be registered when the snapshot is loaded (no work == no time). It's necessary for these ops to live in another crate so we can reference from the build script that does the snapshot.

I think this was something we wanted to do during the early extension refactors but turned out to be harder. 

The option to load ops with a snapshot still exists, I'll open a deno_core PR that this PR depends on.

**Comment by mmastrac** [comment]
This is probably another good argument for getting rid of the build-time snapshots TBH, but I guess I don't really understand why we can't do the snapshot work in the cli crate.

I would probably start by moving as much of the code as possible out of cli and runtime's build.rs into a new snapshot_utils mod inside of runtime, and then call that code from cli's build.rs.

We could probably remove the build.rs script from runtime entirely.

**Comment by littledivy** [comment]
>  I don't really understand why we can't do the snapshot work in the cli crate.

@mmastrac The full CLI snapshot does happen in the CLI crate (both CLI and runtime code):

- https://github.com/littledivy/deno/blob/no_op_initialzation/cli/build.rs#L411-L415
- https://github.com/littledivy/deno/blob/735d2dd08122c04219b4b538e28935c56091c583/cli/Cargo.toml#L58

using deno_runtime's `dont_create_runtime_snapshot` feature flag

> I would probably start by moving as much of the code as possible out of cli and runtime's build.rs into a new snapshot_utils mod inside of runtime, and then call that code from cli's build.rs.

This was attempted before https://github.com/denoland/deno/pull/14794 but we reverted it because it broke publishising: https://github.com/denoland/deno/pull/15076#pullrequestreview-1027904413

**Comment by mmastrac** [comment]
In this case the crate would be upstream? CLI would pull in code from runtime, not the other way around, which will be fine from a publishing perspective.

I am not totally convinced that we can't do it that way and tbh this snapshot code is so complex and hairy I think it's worth exploring this fully before we add even more complexity to an already overcomplex system.

**Comment by littledivy** [comment]
Closing in favour of https://github.com/denoland/deno/pull/21127

**Pull request closed without merging**
