### PR TITLE
Update to TypeScript 3.7

### LINKED ISSUE #3273: Update to TypeScript 3.7
Just and FYI, I'm working on this...

### PR DESCRIPTION
**Pull request by kitsonk**
Also, update `assert()` and remove not null assertions where possibly in `cli`.  Lots of the not null assertions need to be removed in `std` though.

Closes #3273

### CODE REVIEW

**Comment by kitsonk** [comment]
BAH! It appears prettier doesn't support the TypeScript 3.7 syntax features.  It is fixed in master of prettier, but they haven't released it yet.

**Comment by kitsonk** [comment]
It looks like prettier [1.19 is imminent](https://github.com/prettier/prettier/pull/6486) which should include all the 3.7 syntax fixes, so I guess we should hold off on this until that is released.

**Comment by zekth** [comment]
Could you raise an issue for the problematic asserts in std?

**Comment by axetroy** [comment]
> It looks like prettier [1.19 is imminent](https://github.com/prettier/prettier/pull/6486) which should include all the 3.7 syntax fixes, so I guess we should hold off on this until that is released.

Prettier@1.19.0 has been released now.

**Comment by kitsonk** [comment]
Ok this now includes prettier 1.19 in `third_party/node_modules` as well as re-lints the codebase.  There was a bit of churn with this version of prettier, but mainly it was fixing some bugs that were there, so it ends up with better formatted code.

If it passes it CI it should be ready to go @ry

**Comment by kitsonk** [comment]
@ry ok, I think I have fixed everything and this PR is ready now

**Comment by ry** [comment]
FYI I'm disabling the flaky test lock_check_ok2 in this change. It also calls 019_media_types.ts which is known to be flaky.

**Pull request merged**
