### PR TITLE
(std/datetime): add timezone symbols

### PR DESCRIPTION
**Pull request by timreichen**
- add timezone symbols Z and ZZZZZ
- add _ to formatter.ts and tokenizer.ts
- improve regexes
- update readme

### CODE REVIEW

**Comment by bartlomieju** [comment]
@timreichen what's the status of this PR?

**Comment by timreichen** [comment]
@bartlomieju parsing and formatting works, but I have a problem with test implementations for `format`.
Since the outcome is dependent on the timezone/DST where the test is run, the tests need dynamic generated code, which feels like reverse engineering the feature instead of testing it. Maybe you know the proper way to add these tests?

**Comment by bartlomieju** [comment]
> @bartlomieju parsing and formatting works, but I have a problem with test implementations for `format`.
> Since the outcome is dependent on the timezone/DST where the test is run, the tests need dynamic generated code, which feels like reverse engineering the feature instead of testing it. Maybe you know the proper way to add these tests?

Thanks for explanation, I don't have solution on hand, I'll discuss with the rest of the team and get back to you.

**Comment by bartlomieju** [comment]
@timreichen we won't land this PR before standard library migration to a separate repository (https://github.com/denoland/deno/issues/9029#issuecomment-766934654). 

I'm still very much interested in discussing these changes on upcoming meetings and potentially landing the PR.

**Comment by timreichen** [comment]
@bartlomieju that is understandable, I also have not found a solution to the timzone testing issue yet. So we can have a look at that preferably at a std lib meeting.

**Comment by bartlomieju** [comment]
Deno standard library was moved to [denoland/deno_std](https://github.com/denoland/deno_std), please reopen your PR there.

**Pull request closed without merging**
